### ISSUE TITLE
boot sequnce and rom code

### ISSUE THREAD

**Issue by nicolast0604** [lowRISC/opentitan#10078]
Hi 
Is there any information about boot sequence and rom code?

Is there source code for boot rom code in opentitan github?

Any information is welcome.

BR

**Comment by tjaychen** [comment]
are you curious what will be the eventual rom? or the rom that you currently see used in the FPGA?
That's currently a simplified version that does not represent the long term plan.

**Comment by nicolast0604** [comment]
Firstly I would like to know the rom currenly seen in FPGA. 
As I knew very little about that so could you please provide me more information?

So, I am curious about the long term plan or final.

Thanks for your quick response. :)

**Comment by tjaychen** [comment]
the rom used in fpga is quite simple.
Have a look [here](https://github.com/lowRISC/opentitan/tree/master/sw/device/lib/testing/test_rom)

There's not much documentation on it, since it is for test purpose purely.  All it does it execute enough instructions to jump to flash.  It also supports code flashing via SPI.

**Comment by tjaychen** [comment]
i will close down this issue for now since there hasn't been further questions.
Feel free to open another if there are more concerns.
