### ISSUE TITLE
JTAG programmer support for Xilinx evaluation board and custom FPGA board

### ISSUE THREAD

**Issue by nashsrg** [lowRISC/opentitan#1008]
The current Digilent nexys Board use Digilent propitiatory FTDI 2232 interface to communicate with  RISC JTAG .
Is current tool chain support any other Open OCD JTAG(e.g Olimex)  for board does not have digilent propitiatory FTDI2232 interface.
If support for initializing BRAM with application code(the way boot_rom fuse in bitstream) is available that is also helpful.

**Comment by imphil** [comment]
You can connect the JTAG pins of the toplevel to any kind of JTAG adapter, including the Olimex adapter. You possibly need to modify the configuration in the openocd config file for that.

Can you elaborate a bit more on where exactly you're stuck?

**Comment by nashsrg** [comment]
Hi,
Thanks for quick reply,
I have generated bit file for zcu111 board by modifying all require changes in rtl,xdc and tcl file.
I have mapped JTAG connection to ZCU111 board PDOM connector and I am planning to use olimex JTAG to download and run compiled 'c' application in compile in build/sw/device/example/hello_world directory.
As per my understanding current tool flow support on Digilent Nexys FTDI 2232 RISCV JTAG interface.
If i want run 'c' application using Olimex JTAG i want to know what are dependencies need to meet and current tool chain support to meet my requirement.

**Comment by nashsrg** [comment]
I am able to boot boot_rom on zcu111 board. I can see commit id and build date in uart console. still not clear how i can download 'c' application code using JTAG. From sources it looks like the SPI interface is used for downloading sw.bin file in co-ordination with jtag interface. I compared pins of digilent ft2232 and olimex ft2232 device i found gpio which control jtag and spi interface(mux) is not present in olimex jtag.

**Comment by imphil** [comment]
As you have mentioned, our standard way of doing software loading is through SPI, meaning you need some way to connect the SPI interface to your host PC. In our design, we do that through the FT2232 chip, which has a programmable protocol engine (MPSSE) which supports SPI. If that chip is not available to you, you need to find another SPI to host PC adapter.

Alternatively, you can load software through JTAG and the debug system instead of SPI. That's actually untested, so you might need to experiment a bit. (And that's nothing we plan to support going further.)

A couple hints if you choose to go down that route:
- The general flow is: GDB (optional) -> OpenOCD -> JTAG -> debug system -> Debug System Bus Access (SBA) -> any bus device in the SoC (see a [list of SBA -> device connections in the RTL](https://github.com/lowRISC/opentitan/blob/553ca956e0204e5b67b3bbea47f2e067f60b5510/hw/top_earlgrey/data/xbar_main.hjson#L105))

- On the host side, you can either use GDB with its `load` command, or OpenOCD with its `load_image` commands (and related commands). 
- On the SoC side, you need to choose a target to write to by selecting the right base address: probably writing to RAM directly will do the trick, which [starts at address 0x10000000](https://github.com/lowRISC/opentitan/blob/553ca956e0204e5b67b3bbea47f2e067f60b5510/hw/top_earlgrey/data/top_earlgrey.hjson#L117). (Writing to flash probably won't work this way.)

Note that program loading through JTAG directly into RAM can get you started, but we will remove this possibility in the future, so please use this as a stopgap until the your SPI <-> host PC communication is ready.

**Comment by nashsrg** [comment]
Thank for hint.
Please can you provide some inputs on following approach.
I am able to initialize spi_device->u_memory_2p-> gen_regmem->gen_mem_xilinx RTL with application 'c' code vmem file(As per my understanding SPI programming utility download application .bin file to this memory) the way boot_rom is fuse in bitstream.
But Boot_rom is executing but Application is not executing after programming bitstream!
I think default boot_rom require changes for this.
Please let me know if i can execute application with this approach.

As i know if this approach work i have to recompile design every time but if i able to run only bitstream generation step with modified 'c' application executable that will useful for me.

**Comment by imphil** [comment]
The SPI flash utility doesn't initialize the bootrom, but the flash, which we use as program memory. The bootrom is built into the bitstream and doesn't change (it's meant to be a read-only memory, after all).

If you want to modify the bootrom after a bitstream has been synthesized, you can use the util/fpga/splice_nexysvideo.sh script.


Unfortunately it's hard for me to help you out here, since we don't have your setup available and you're trying out something new. 

I recommend staying close to what we support by either getting a FT2232 chip as a PMOD (highly recommended!), or trying to route a second of the four channels of the FT4232 chip built into the ZCU111 board to the processing system. I'm not sure if the Xilinx device allows you to do that, but I'd try routing the PS_UART0 to the FPGA fabric. Then use the FTDI channel B for UART, and channel C for SPI/JTAG (you need to use the RTS/CTS lines for spi_jtag_n and bootstrap).

![image](https://user-images.githubusercontent.com/1467123/69346021-03521880-0c6a-11ea-8d28-0f0d428c7d55.png)

https://www.xilinx.com/support/documentation/boards_and_kits/zcu111/ug1271-zcu111-eval-bd.pdf

Finally: If you need commercial support to get the OpenTitan chip design running on this board please reach out to lowRISC.
