### ISSUE TITLE
[mask_rom] OpenOCD fails to connect to Verilator when ePMP Whitelist Policy enabled

### ISSUE THREAD

**Issue by dbeitel-opentitan** [lowRISC/opentitan#10131]
I get the following error when I try to connect to Verilator running a mask_rom image:

```
Open On-Chip Debugger 0.11.0
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
Info : only one transport option; autoselect 'jtag'
Info : Hardware thread awareness created
force hard breakpoints
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Info : Initializing remote_bitbang driver
Info : Connecting to localhost:44853
Info : remote_bitbang driver initialized
Info : This adapter doesn't support configurable speed
Info : JTAG tap: riscv.tap tap/device found: 0x04f5484d (mfg: 0x426 (Google Inc), part: 0x4f54, ver: 0x0)
Info : datacount=2 progbufsize=8
Error: unable to halt hart 0
Error:   dmcontrol=0x80000001
Error:   dmstatus =0x00000c82
Error: Fatal: Hart 0 failed to halt during examine()
Warn : target riscv.tap.0 examination failed
Info : starting gdb server for riscv.tap.0 on 3333
Info : Listening on port 3333 for gdb connections
```

I can successfully connect if I comment out this instruction in _mask_rom_epmp_init_:

```
  // Enable Machine Mode Whitelist Policy (MMWP).
  // TODO(#5653): Enable Machine Mode Lockdown (MML)?
  csrsi EPMP_MSECCFG, EPMP_MSECCFG_MMWP

  ret
```

**Comment by mundaym** [comment]
I don't think we want to support interactive debugging of the mask ROM. The memory protection scheme in use is deliberately restrictive and we shouldn't relax it just to enable debugger support. @moidx @alphan if you agree I suggest we close this issue?

@dbeitel-opentitan since you are using verilator you can make use of the instruction trace (`trace_core_00000000.log`) file that is created. If you are comfortable working with assembly it can be a useful way to determine what is happening at runtime without needing a debugger. The `*.dis` files created at build time contain source annotated disassembly that you can use to map machine code addresses to source code.in source annotated disassembly that you can use to map machine code addresses to source code.

**Comment by alphan** [comment]
> Ok. One more question, Is JTAG access controlled by LCS in HW?

Yes, according to the [life cycle hwip spec](https://docs.opentitan.org/doc/security/specs/device_life_cycle/#manufacturing-states) JTAG is enabled in TEST_UNLOCKED_*, DEV, and RMA states (should see the table if you search for "HW_DEBUG_EN" in the page).

@tjaychen Please correct me if I'm wrong.

**Comment by tjaychen** [comment]
yes that's correct.

**Comment by tjaychen** [comment]
i think what @mundaym is saying is that we don't want too many conditional checks inside the ROM (if life cycle == blah, enable debug etc). So even though hardware allows all jtag access during RMA, the ROM can still choose to lock itself out.

@moidx / @alphan i do think early on, it might be helpful to have jtag access in ROM, it "can" be helpful for very early or low power exit kind of debug.

**Comment by dbeitel-opentitan** [comment]
I've submitted a pull request that enables Debug ROM in the ePMP for RMA lifecycle (PR #10426). Let me know if there are any objections.

**Comment by mundaym** [comment]
This issue was discussed in the security meeting and it was decided that it should be fixed. @alphan and I will review the PR @dbeitel-opentitan sent to address the issue.
