### ISSUE TITLE
[opentitantool] Proposal - Simulator capability and simulated DUT control protocol

### ISSUE THREAD

**Issue by semihalf-mazurek-michal** [lowRISC/opentitan#10217]
I would like to discuss the possibility of extending the transport trait capabilities so it can support control of the simulated DUT.

Motivations:
During the implementation of 'HostEmulation' support for opentitantool, there was a problem with the lack of a 'session' concept on the opentitantool side. I think adding a general protocol for communicating between opentitantool and DUT (simulator/simulator supervisors) would be useful for everyone.

The documentation below presents a proposal for such a solution based on the backend that I am currently implementing for 'HostEmulation'. The API / Protocol described below is flexible enough for other backends e.g Verilator or QEMU to use it as well.

Current documentations:
https://docs.google.com/document/d/1n9JcT3VlbeHd0DaCoaKjlDO0RXZkfdqLSy4bYw6-bc8/edit?usp=sharing

Deprecated documentations:
https://docs.google.com/document/d/1ypNZxelXSLpuzjndsg_V_WB2ELgs93pLu87QrkTWQEs/edit?usp=sharing

**Comment by timothytrippel** [comment]
In opentitantool today, their exists a [`console`](https://github.com/lowRISC/opentitan/blob/88db0fb5ac32d6dda2ecc1c99d52e061e0910cfb/sw/host/opentitantool/src/command/console.rs#L25-L43) command that is designed to launch an "interactive" UART session with various hardware backends, presuming you had some sort of console SW on the hardware that was monitoring the UART. But really it seems you want the notion of an interactive session on the host side, that can instantiate a hardware backend (particularly simulation-type backends), connect to it, and allow opentitantool users to issue as many follow on commands to manipulate that same backend before closing the session. (Just want to confirm I have that correct?)

As opentitantool/lib exist today, you can write a custom host-side test program (modeled after the opentitantool [`main()`](https://github.com/lowRISC/opentitan/blob/88db0fb5ac32d6dda2ecc1c99d52e061e0910cfb/sw/host/opentitantool/src/main.rs#L140-L157)) that imports opentitanlib, creates a transport to a backend, then issues any series of calls to opentitanlib (i.e. to manipulate some GPIOs, send some UART packets, etc.) but the opentitantool main() is not interactive as it stands. This works for us today since we are only using opentitantool to run fully self-contained on-device tests right now.  Particularly, when used in the context of running a self-contained device-side test (such as our [UART smoke test](https://github.com/lowRISC/opentitan/blob/master/sw/device/tests/uart_smoketest.c)) on our Verilator RTL simulation platform, opentitantool first instantiates the backend, which it does by creating a separate sim process with the proper args, then runs the requested command. Specifically, our Verilator sim binary takes as input vmem files that backdoor load the respective memories (ROM, Flash, and OTP), the location of which are runtime args to opentitantool which hands these off to the Verilator sim binary, and the when the test status is set to `pass` (by writing to a specific mem address that the testbench monitors), the Verilator sim automatically tears itself down.

Overall, I definitely see some value here in terms of providing interactive debugging capabilities with our RTL  simulation platforms (as they evolve) in addition to your additional host emulation platform. Maybe this is less useful for FGPA and silicon backends, since once you use opentitantool to bootstrap firmware into the chip, and the FPGA / chip are powered on, that firmware will continuously run, so opentitantool as it stands today could be used in an interactive manner with those backends. Simulations backends require starting and stopping however (though Verilator sims currently automatically tears themselves down when a test status bit is set), so this proposal definitely makes sense. Thanks for submitting this! Tagging @a-will and @arunthomas to take a look as well. I dropped some comments in your doc, but let's continue to iterate on this and we can start adding features to opentitantool to support this use case.

**Comment by semihalf-mazurek-michal** [comment]
In connection to Issue [#10889](https://github.com/lowRISC/opentitan/issues/10889) and documentation above following task list was proposed:

Extending the Transport trait with necessary modifications
- [ ] Add new 'Emulator' trait and capabilities.

Add new backend for TockOS Host Emulation - Ti50Emulator:
- [ ] Implementation of Emulator trait
- [ ] Implementation of GPIO trait
- [ ] Implementation of UART trait
- [ ] Implementation of SPI trait
- [ ] Implementation of I2C trait

Extending the current Verilator backend with a new session and emulator concept.
- [ ] Implementa Emulator trait for Verilator Backend

**Comment by semihalf-mazurek-michal** [comment]
Updated documentation file:
https://docs.google.com/document/d/1n9JcT3VlbeHd0DaCoaKjlDO0RXZkfdqLSy4bYw6-bc8/edit?usp=sharing

**Comment by timothytrippel** [comment]
Can we close this issue now?

**Comment by semihalf-mazurek-michal** [comment]
I think this ticket can now be closed.
