### ISSUE TITLE
[otp_ctrl] Enhancement for device-specific scrambling keys

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#10434]
The OTP_CTRL currently uses a global random netlist constant for secret partition scrambling. This could be enhanced in the future by making the scrambling key device-specific. For this to work, we would have to allocate another partition (possibly scrambled by a netlist constant) which holds the scrambling key. That partition would then have to be sensed and checked before descrambling any other secret partition.

**Comment by tjaychen** [comment]
yeah i think scrambled with another netlist constant is probably ideal.  Then at least we mandate breaking two separate things to get the final scramble key.

**Comment by johannheyszl** [comment]
Sec WG 2023-10-12:
Will likely only be a small security improvement since, an attacker needs to recover the global netlist constant and OTP data in both cases. If an additional individual scrambling key is stored in another OTP partition, this only means that the attacker needs to recover more OTP bits. This only adds a small percentage of linear improvement.

Conclusion: Close
