### ISSUE TITLE
[lc_ctrl] Add debug register for observing critical system signals

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#10462]
This is a future enhancement identified on #10444.
A debug register could be added to `lc_ctrl` in order to expose important system-level signals through the life cycle TAP.

**Comment by gdessouky** [comment]
Triaged for `lc_ctrl`:  this is nice to have, but not priority for M2.5, in line with what has been decided in the discussion in [#10444](https://github.com/lowRISC/opentitan/pull/10444). Labelled as https://github.com/lowRISC/opentitan/labels/Type%3AFutureRelease.

`rom_ctrl` internal integrity error alerts (from mux or checker FSM) now cause squashing of responses from the ROM to the bus, and bus transactions would hang, but it is unclear whether these alerts will not be captured  by alert handler and watchdog timer since these are not yet configured at this point.

rom_ctrl **has** to work (assuming it is verified extensively) for the chip to actually boot, so exposing system-level good/done signals through `lc_ctrl` debug register would be nice for observability and diagnostics in case the chip does not boot, but probably wouldn't help much beyond that...could it also reveal potentially exploitable signals (re. timing in boot flow) that an attacker can exploit?

**Comment by msfschaffner** [comment]
Noting that this could be implemented if we add a debug bus to the system.

CC @a-will

**Comment by msfschaffner** [comment]
I am moving this to the backlog for now, since I don't think we need to change anything for Earlgrey-PROD.

Regarding the good/done signals from ROM_CTRL, I would argue that these should not be exposed during a PROD life cycle state for security reasons. In a debug-enabled life cycle state the ROM_CTRL status can already be checked by inspecting its CSRs via the RV_DM, hence exposing these signals through the LC_CTRL TAP is not strictly required (although it could be convenient).

CC @vogelpi @johannheyszl

**Comment by vogelpi** [comment]
Thanks @msfschaffner . I agree that it's better to not expose the ROM_CTRL signals in non-DEV devices.
