### ISSUE TITLE
[dv/top_level] Randomize jitter for the system clock 

### ISSUE THREAD

**Issue by sha-ron** [lowRISC/opentitan#10554]
Enable and disable jitter in tests that activate modules that use the system clock

**Comment by tjaychen** [comment]
@sriyerg not sure if P1 is the right priority, but I've placed it there for now.

**Comment by matutem** [comment]
There is a top_level chip_sw_clkmgr_jitter_test that enables jitter. We currently check that the jitter_enable CSR causes the jitter_en_o output to track, and we also check that that output is connected to the AST clk_src_sys_jen_i input.

To confirm the AST actually jitters the clock we could check that the clock count measurement show a drop in the counts, since jitter should result in an average slower frequency.

**Comment by sha-ron** [comment]
Thanks Matute. The issue doesn't refer to the AST, I meant that we need to check the functionality of things that use the jittery system clock with such clock in the simulation.

**Comment by weicaiyang** [comment]
As @tjaychen mentioned, we may want to enable jitter for a set of chip-level tests.
With #12297, we can add `+en_jitter=1` to enable it for the test.

**Comment by tjaychen** [comment]
i think this is done now, we've added a set of tests with jitter enabled.
