### ISSUE TITLE
Can I use ZCU102 to develop FPGA instead of CW310?

### ISSUE THREAD

**Issue by nicolast0604** [lowRISC/opentitan#10642]
Hi All
As I always encounted issues of transfering by using CW310, can I use ZCU102 to do the opentitan FPGA verfication ?

Any suggestion is welcome.

**Comment by cryptobsv** [comment]
I can't answer your question, but because "any suggestion is welcome", I'll comment anyway, as I also had difficulties getting the board to work.
What exactly is not working? Loading the bitstream? Loading the firmware?
Loading the bitstream takes a while, a few minutes in my setup. Loading the firmware immediately after the bitstream (without disconnecting) seems to be a bit more stable to me.

**Comment by msfschaffner** [comment]
Hi @nicolast0604, 

Indeed it would be good to know a bit more about what exactly is not working.

You are welcome to use another FPGA board - but you would have to port OpenTitan over to that board yourself, since the ZCU102 is currently not among the FPGA boards we support and maintain.

CC @colinoflynn for CW310-specific questions.

**Comment by colinoflynn** [comment]
Hi @nicolast0604 - The boards do get "opentitan specific tests" run (loading the bitstream + tests). Normally the loading time is ~60 seconds for the FPGA (I haven't timed recently), and the firmware is much faster after. There is a speed setting for how quickly the programming happens on the first stage, which you can also tune (it's set to a "mostly safe" default, there is some variation in practice).

If you aren't on the latest CW310 firmware that can also be helpful, you can drop a note here or reach out to support@newae.com for general CW310 firmware updates (that is - updating the firmware that power the actual CW310 USB interface, *not* the open-titan specific firmware).

**Comment by johngt** [comment]
Tagging this issue as closed / resolved. If there is anything to follow-up on please reference this in a new issue.
