### ISSUE TITLE
SPI_HOST Little&Big Endian Design Verification

### ISSUE THREAD

**Issue by visbaz** [lowRISC/opentitan#10764]
Test for SPI HOST endian fronm spi_host.hjson is as below:
 name: endian
      desc: '''
            Stimulus:
              - set the compile time parameter to configure the DUT in both modes.
              if possible this should be randomized for all test to verify support in both modes

            Checking:
              - Check all features are supported correctly in both little and big endian mode
            '''
      milestone: V2

ByteOrder is a paramater from spi_host.hjson.
This is passed on to RTL and DV from pkg files.

I find no possible way of randomizing as mentioned in the test.
Design should be recompiled and built in order to verify big and little endian.

Should this parameter be local parameter rather than a  hjson parameter?
Should we explore possible alternatives to achieve verification for both little and big endian RTL implementations?

@martin-lueker and @rasmus-madsen please add your thoughts.
please add relevant stake holders if required.

**Comment by martin-lueker** [comment]
Is there any reason to change this?

**Comment by sriyerg** [comment]
The design may have changed since the testplan was originally written. The testplan may hence need updates to reflect the current state of the design specification (which is well within the scope of DV effort). Please remove the test from the testplan, make a PR and get the designer to approve. 

We do not verify what is not taped out - so there is no need to verify design configurations (i.e. parameter settings) that are not in use in our chip implementation(s).

**Comment by visbaz** [comment]
Will remove the test from testplan and make a PR for @martin-lueker to approve
