### ISSUE TITLE
[entropy_src] Bucket test may not address 4-bit symbol APT health test requirements

### ISSUE THREAD

**Issue by zi-v** [lowRISC/opentitan#10815]
APT test is described in https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-90B.pdf, section 4.4.1, quoting:
"Let next() yield the next sample from the noise source. Given a continuous sequence of noise
samples, the cutoff value C and the window size W, the adaptive proportion test is performed as
follows:
1. A= next()
2. B=1.
3. For i = 1 to W–1
     If (A = next()) B=B+1
     If (B ≥ C) signal a failure
4. Go to Step 1.
"
I did not get it at first reading, but I am now convinced that APT test runs on a moving window (in our case, a window size of 512 samples), while the results should be re-evaluated after every sample (starting from the 512th).
This can be implemented by having the test hardware consider both head and tail of a 512-depth sample FIFO (which we luckily have) by adding the head samples and subtracting the tail samples to/from the relevant buckets. However, I don't think we currently do that.

Note that 90B section 4.3/b allows 'approved health test' substitution under some terms, quoting:
"Some developer-defined tests that meet the requirements for a substitution of those
approved tests, as described in Section 4.5. If developer-defined health tests are used in
place of any of the approved health tests, the tester shall verify that the implemented tests
detect the failure conditions detected by the approved continuous health tests ...
"
I wonder if we can somehow use this by running the health test on a larger window (say 1024 samples, but without the overlap)

**Comment by martin-lueker** [comment]
Hi @zi-v , 
   Thanks for taking a look.  It's great to have these checks.  
   The implementation we have is actually inclusive and superior to the one above.   The implementation above (quoted from SP 800-90B) will only alert if the _first_ symbol is repeated too much.   Our implementation will trigger if any symbol is repeated.  This is analogous to the variation mentioned in the text, which I quote:
> For binary sources, the developer is allowed to extend the test by also checking that W-B ≥ C,
> which would guarantee that a binary value occurring too frequently will be caught on the first test
> window.
We apply this variation in the binary adaptive proportion, and for the symbol bucket-test.  By maintaining histograms for all symbols, we are implementing the test so that any symbol recurring too frequently will be "caught in the first test window."

  Regarding the "moving window" hypothesis, I understand your proposal.  However I do not see that as supported in the text.  Furthermore if look at Table 2 in section 4.4.2, and the accompanying footnote, you can see that there is an assumption of statistical independence between windows, i.e. this alpha calculation does not take into account the moving window.  It uses a function to calculate the inverse CDF of a binomial distribution.   Such an alpha calculation assumes that all windows are being computed as independent samples (not a moving window).  I am able to compute alpha values from this description and reproduce their table, but only if I assume a fixed window.  That said, I claim the text and statistical tables support fixed, independent windows.
  
   There is also the timing of this change to consider.  If the moving window changes you suggest were simple, I would suggest a switch to pass the decision on to software, as in #9759.  However the change you are suggesting will require significant changes to the control logic, the policies on when data is passed on the the conditioning block, and the accompanying DV.   It will not be quick to even specify how this fits into the pipeline.  If we want to move forward on this we will have to have a meeting to discuss the impacts on schedule.  We'll then have to restart our working group to establish the exact behavior for this moving window.   So let's certainly discuss whether we need to do such a thing, and if needed, we can establish a timeline for it, but if past experience is any guide, this particular change will not happen quickly.

**Comment by zi-v** [comment]
Martin, thanks. After reading your above note and the 90B text again, I think you are right. 
I agree that it is not a good time for unnecessary changes. Let's simply close it then

**Comment by mwbranstad** [comment]
@zi-v i will close this issue but can you give one final confirm to do so?

**Comment by zi-v** [comment]
Confirmed

**Comment by mwbranstad** [comment]
thanks, closing.
