### ISSUE TITLE
[fpv] guidelines for RTL assertion

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#1082]
related to issue #1079, as @rasmus-madsen brought up, discuss with RTL and DV engineers for the guidelines on where to write assertions.

**Comment by rasmus-madsen** [comment]
@cindychip 
I like adding Assertions in a bind file then they are easy to locate if there is an issue.
and easy to overwrite if you have a special case or altered use of a module.

but I don't have a strong feeling against putting assertions directly in code, I think there are things that are in favor of that. 
I do on the other hand feel that it is important to put interface checks with the interface etc.
to make sure they are shared by all users of the interface.

eitherway I think it is important to write a set of guidelines for this

**Comment by cindychip** [comment]
Thanks for the input Rasmus. I would like to see all the assertions in one place as well. My current concern is: if a module includes some sub-modules, then when running simulation, we should also include the bind file assertions for the sub-modules. That might be less convenient than directly writing the essential assertions in the RTL code. Wonder what design engineers think about it @msfschaffner @eunchan?

**Comment by msfschaffner** [comment]
from the designer's point of view, I think we should allow placement of basic assertions directly into RTL (let's call these "embedded SVAs" for now). these are usually assertions that the designer thinks about when writing the RTL, and I find it much more convenient to directly have them co-located with the functionality itself. as an added benefit, these "sanity checks" are always present even without an extra bind file.

there is also a class of assertions like the KNOWN assertions that are usually placed inside each module in order to check its interface/outputs, and I find it convenient to have this in the same file as well.

further, @tjaychen, @eunchan and I will soon present a suggestion for guidance on how to treat `X` in our code base, and this will likely involve heavy use of embedded KNOWN assertions (also around case statements) which will become very cumbersome if they cannot be directly placed into RTL.

I think of the additional assertions located in a bind file as complementary SVAs assuring coverage closure, and these are then typically written by the DV engineer.

**Comment by sjgitty** [comment]
> I think of the additional assertions located in a bind file as complementary SVAs assuring coverage closure, and these are then typically written by the DV engineer.

In addition it is common sense to put portable assertion collections in a file, like
what we've done for TLUL. These are useful when binding to more than one design,
so one could make that determination when writing the assertions, as to whether
or not they would be useful elsewhere in the chip.

**Comment by cindychip** [comment]
Thanks everyone for the inputs. Seems like most comments can be summarized as below:
1. Assertions can be either in RTL file or separate file bound with RTL. 
2. Common shared assertions such as TLUL assertions should be in a separate file and bound with the RTL. 
3. Sanity check assertions (mostly written by the designers) are recommended to write directly in the RTL files.
4. Assertions written for FPV are recommended to write in a separate file. If sub-modules have separate assertion files, it is recommended to bind them in the top level.
Let me know if anyone has any concerns/add-ons to the summary. If not, I will work on updating the guideline.

**Comment by msfschaffner** [comment]
SGTM, @cindychip

**Comment by cindychip** [comment]
close as PR #1179 merged
