### ISSUE TITLE
[OTBN/SRAM/Icache] Investigate interaction of scrambling and bus integrity

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#10976]
Issue initially raised by @GregAC 

> For the next security meeting can we have a slot to discuss the interaction with ECC and scrambling? 
> In our OTBN testing we found instances where corrupting a single bit of scrambled memory results in a valid ECC codeword when unscrambled.

> This is a reasonably obvious outcome when you do ECC before scrambling but we wanted to ensure everyone was aware this was the case and discuss the implications. We don't see it as a problem as due to the scrambling it's infeasible to get a useful, repeatable attack out of this. You'll just corrupt some data or produce useless/invalid instructions if you do get lucky in flipping memory bits (many single bit flips in scrambled memory will still give ECC errors when unscrambled).

**Comment by tjaychen** [comment]
i think as long as the ECC isn't misbehaving, there isn't nothing more we can do here unless we increase the storage to have fewer collisions. 

Although this kind of accidental match is in my mind no different from an attack on the data path directly, which we are known to be vulnerable against. Those attacks we are guarding with software redundancy, so it will have to do here as well.

**Comment by msfschaffner** [comment]
Hey @rswarbrick - I think your assumptions make sense for a first order estimation. There may be a slight statistical bias, though, since the diffusion layer employed does not have cryptographic strength. It's would be interesting to gathering some statistics at some point (just randomly inject faults and check ECC after unscrambling) -  but I don't think that is high prio at the moment.

**Comment by msfschaffner** [comment]
This has been discussed in the security WG meeting today. The consensus is that it would be good practice to empirically estimate whether the chance of an undetected error is indeed close to 1/128, or whether there is unforeseen interaction between the ECC code and scrambling logic (given that it uses non-standard / weak crypto primitives). The most straightforward way to evaluate this would be to reuse existing functionality from the `rom_ctrl` scrambling script, and develop a python script to simulate the probabilities.

We may also want to assess the probability that an undetected error produces a valid OTBN instruction, since the OTBN uses this scrambling mechanism on the imem (this is not needed for Ibex since we do not allow execution from SRAM in PROD states).

**Comment by tjaychen** [comment]
Just a note that this might apply to `ibex` also because of the icache. So we do have a scrambled memory with storage integrity along the way as well.

**Comment by msfschaffner** [comment]
A shoot, you are right! I forgot about that one.
In terms of mitigation, that one gets a new ephemeral key on every boot, I believe.

**Comment by tjaychen** [comment]
> A shoot, you are right! I forgot about that one. In terms of mitigation, that one gets a new ephemeral key on every boot, I believe.

and thanks to the lowrisc folks, every `FENCE.I` too i believe!

**Comment by tjaychen** [comment]
would it be accurate to say.. that we're worried about..
if whatever integrity mechanism has a N % of a false positive, we want to make sure applying scrambling does not make make that % higher? But should stay roughly the same in a large random sampling?

**Comment by msfschaffner** [comment]
Yeah we basically want to make sure the custom construction and the employed ECC polynomial do not interact in a weird way that distorts the statistics by too much (it will not be perfect, but we do not want a scenario where, say, the probability is like 10x off).

**Comment by cdgori** [comment]
the classic way to do this kind of diffusion testing is to pick a random input, run it through the scrambler, grab the "good output", then flip the MSB and run it through the scrambler, and see how which bits change in the output vs the "good output".  Then do that again a few thousand (or million) times and collect the stats about how many bits change.  Then that again for MSB-1, MSB-2 etc.  Basically you are looking to see if there are bins in the outputs with zero or really small numbers, where a change in some input NEVER (or almost never) affects an output bit, which would indicate something is wrong.  And then I guess layer on the ECC to see the compounded effect.

For AES or SHA you'll see massive diffusion such that tons of bits change.

**Comment by GregAC** [comment]
I think this becomes future release work as re-architecting the scrambling for M2.5 isn't feasible, @vogelpi would you agree?

**Comment by vogelpi** [comment]
I agree with you @GregAC , major changes to the scrambling aren't feasible for M2.5. For a future release we should probably do the experiment/analysis described by @cdgori to be on the safe side.

To make sure everybody is on the same page, we will discuss this in the next Security WG meeting.

**Comment by johannheyszl** [comment]
Summary of the discussion in Security WG 2023-03-16: 
- A change for M2.5 is not desired due to the low urgency (as judged now) and high effort. Additional countermeasures (algorithmic and lower level) do exist and potential remaining issues could be addressed through SW mitigation. 
- Nonetheless, more investigation should be done: **Action**: Perform analysis of current situation as outlined below in (2) for M2.5 OT and derive potential guidelines for SW mitigation. This will also help for integrated OT.
- A change for integrated OT is highly recommended since single bit flips unscramble to multi-bit flips which are partly not detected and lead to silent data corruption which is not acceptable in the integrated setting (high-availability / server systems with one bit faults possible). 
- **Action**: A new issue will be created to capture this. 


**Issue summary: The question is whether there are severe issues from fault attacks against the combination of scrambling and ECC.**
- This is relevant for memories where we use ECC for integrity, _then_ scrambling on top of this before storing. This is: (1) OTBN IMEM and DMEM, and (2) ibex ICACHE, SRAM and retention SRAM, and (3) OTP.
- The intent of ECC is to _prevent targeted few-bit faults_. Stored data (39b), first gets unscrambled (still 39b), then goes through ECC to derive original words (32b). 
- Doing ECC closer to the CPU means this effectively _prevents low Hamming weight faults on the original data_. Note that this is true even if the attacker reverse engineers the scrambling and injects dedicated multi-bit faults that lead to precise few-bit faults after scrambling. This is why this order makes sense - to prevent few bit faults on the original data! Also, doing ECC closer to the CPU allows to cover FI protection in all the memory itself, the scrambling logic, as well as the interconnect bus.
- But while this approach _effectively prevents precise few-bit edits of the original data_, the unscrambling leads to an unspecific broad fault pattern even for single bit flips on the scrambled data. This means that any fault may lead to an unscrambled 39b word that may pass ECC with a certain probability. While the word will be largely different from the original, this is still undesired. This probability is in the range of 1/2^7 potentially in low single digit percentages (The original [Hsiao paper](https://people.eecs.berkeley.edu/~culler/cs252-s02/papers/hsiao70.pdf) states that SECDED(72, 64) is able detect 4-bit errors with a probability of 99% (For SECDEC(39, 32) used in many places it's going to be less).

**(1) About checking uniformness of scrambling (as discussed in a previous Security WG):**
- If the scrambling was _not_ uniform, then specific bit flips would e.g. lead to other specific (few) bit flips but the subsequent ECC should detect those.
- If the result of scrambling was _uniform_, a fault would have a 1/2^7 probability of passing ECC as valid codeword. From the resulting 32b instruction candidate, if we e.g. assume that 2^8 outcomes of 2^32 are useful (assumption!), this would lead to a 2^8/2^(32+7) = 1/2^31 ~= 10^-9 chance which means about >6 years at 100ms per FI. This could be prohibitive enough but is based on the above assumption. For this it makes sense to check for uniformity. Note that if uniformly corrupted data words help the attacker this does not apply.
- Question: Is the unscrambled fault model close to uniform?
- Question: Can attackers predict how bit-flips will change bits in the unscrambled word?
Testing method for diffusion properties of unscrambling (as proposed by Chris):
- Pick a random input, scramble to get ‘good storage word’, then flip e.g. MSB, unscramble and see how many/which bits change vs. the original input. Repeat thousands/millions of times and collect stats about how many bits change. Repeat for other bits. See if there are bins with zero or really small numbers of changed bits, i.e. diffusion not uniform. Add ECC layer to see the compound effect. 
Jade performed a short, preliminary [test](https://gist.github.com/jadephilipoom/bdcec3adb2bebf4da5c21a569745dd5f):
- Gathered initial evidence that single bit-flips likely cause unscrambled output words with a) low Hamming distance from the original value and b) biased/predictable bit-flip locations. 
- This is unfavorable and encourages further testing (incl. ECC) as described below.

**(2) How secure is the overall ECC+scrambling mechanism and what SW mitigation do we need for M2.5?**
- Testing method for overall scrambling+ECC (as proposed by Bilgiday)
- ECC+scrambling characterization for very low-level Ibex and OTBN binaries (ROM, cryptolib): Take binary, transform to memory image, inject faults, transform back and characterize outcome.
- This helps to understand the fault model better, develop software mitigation, and to create software programming guidelines.
- Note: Confirm specifics of combination of ECC and scrambling for different uses in OT.


Thanks for the discussions everybody and particuarily @bilgiday, @vogelpi @andreaskurth @zi-v @neeraj-rv @jadephilipoom

**Comment by johannheyszl** [comment]
Thx. Sg. Issue to capture for integrated has been created [#17661](https://github.com/lowRISC/opentitan/issues/17661)

**Comment by matutem** [comment]
I run some experiments while developing https://github.com/lowRISC/opentitan/pull/19332: indeed, the chances of missing an error seems close to 1/128, but I also found there is an almost 50% chance of getting a double bit error for a single one, and vice versa. This is not a problem for us since (at least for sram errors) any error is treated the same, but it may be good to know.

**Comment by johannheyszl** [comment]
Will be addressed by RFC under consideration #20788
