### ISSUE TITLE
[ibex] Yosys synthesis missing lowrisc_ip

### ISSUE THREAD

**Issue by nasahlpa** [lowRISC/opentitan#11060]
Hi,
Is it planned to support the Yosys design flow in `hw/vendor/lowrisc_ibex/syn` for the Ibex? If yes, the [lowrisc_ip](https://github.com/lowRISC/ibex/tree/master/vendor/lowrisc_ipl) directory is missing in `hw/vendor/lowrisc_ibex/vendor`. When adding this directory, synthesizing the Ibex works out of the box.
If requested, I can open a PR.
Best,
Pascal

**Comment by rswarbrick** [comment]
Hah! The problem is that `lowrisc_ip` is vendored from OpenTitan into Ibex. Then the Ibex RTL is vendored from the Ibex repo into OpenTitan. We drop the `lowrisc_ip` stuff to avoid vendoring OpenTitan into itself(!). But we're lazy and don't carefully rip out all the supporting code like, it seems, the `syn` directory.

Can you run the experiments you need from the Ibex repository? That's probably the easiest approach.

**Comment by nasahlpa** [comment]
Ah, good to know!
Sure, I'll do that.
