### ISSUE TITLE
[edn] Lockup when both EDNs are running in boot mode

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#11071]
@mwbranstad and I have done some debugging of this issue: https://github.com/lowRISC/opentitan/issues/8935

Mark identified that both EDNs are configured in boot mode. Initially it was expected only one EDN would ever be run in boot mode. However there is no particular reason they shouldn't work when they are.

Looking through the waves for #8935 it appears the CSRNG/entropy_src are behaving well and it's edn1 potentially misbehaving. It transitions to a `BootDone` state via `BootPulse` shortly before EDN1 stops responding to requests.

@mwbranstad will aim to reproduce this in a testbench that contains the entropy complex. I will provide him with a .vcd.gz of the waves he can use for further debug.

**Comment by mwbranstad** [comment]
Due to a recent change to entropy_src, it can be programmed to either do the one-time boot mode, producing 1 seed, or in mission mode where a startup sequence produces 1 seed, with subsequence seeds generated in the continuous mode.
Because of this change, both EDN modules cannot both be in boot_req_mode since only will get the seed and the other EDN will hang forever. So at a minimum, the programming must change to avoid this condition.

**Comment by tjaychen** [comment]
i guess all these tests should really switch to the continuous mode @mwbranstad ? And limit the boot mode entropy to actual boot only.

I'm a bit out of the loop here, but does anyone know if rsa/ec verify routine makes use of edn1...? I'm guessing no, but wanted to double check.

**Comment by mwbranstad** [comment]
Yes - the obtn tests all should switch to non-boot mode configuration for the EDN blocks. There still may be an issue, but for sure it will lock up with two EDN blocks both programmed to boot_req_mode.

**Comment by rswarbrick** [comment]
Ok, this is a firmware change that we need to make. Probably in the mask rom and also in our test rom. @mundaym: As lowRISC's resident mask rom guru :-), do you know the places that we need to tweak? (I can grep, but I'm worried I'll miss something)

**Comment by tjaychen** [comment]
@mwbranstad just to clarify, i dont think the switch to continuous mode is something we intend to do in boot rom.
The main concern is that it will simply take too long.  I think the idea was always to do it in the stages after boot rom, so in this case it would probably be in the test itself.

**Comment by mwbranstad** [comment]
@tjaychen totally agree. I did not state that very well, mostly going straight to the root cause of the issue. As with a real system, I would expect the boot ROM to set EDN0 to boot mode, and EDN1 to either auto_req mode or sw port mode. Once up and running, the entropy complex should probably be all re-configured to what might be called mission mode.
