### ISSUE TITLE
[rom] Turn back on disabled peripherals upon reboot

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#11081]
A new full-chip test was created in https://github.com/lowRISC/opentitan/pull/11080 (clkmgr_peri_off test). It disables the uart peripheral using clkmgr clk_enables CSR, and then attempts a CSR access to it, which causes the CPU to freeze. The test sets up a watchdog bite, so the chip resets.

However, after the reset the clk_enables CSR remains unchanged, which is expected since clkmgr is not reset (it is in the AON domain). This means any subsequent access to the peripheral in question will freeze again. The expectation is that the ROM should re-enable any peripherals upon reset.

To make matters worse, the peripheral in question was uart0 (it could have been any), so any attempt to generate logging messages will cause a freeze.

**Comment by timothytrippel** [comment]
(as we discussed offline) Logging messages are only an issue for Verilator and FGPA, since in DV sim I believe these are logged through backdoor memory writes. Regardless, since we want to run tests on these platforms too, it sounds like the **test ROM** should be updated to reenable peripherals (by setting **all?** clk_enable and clk_hint CSRs to their reset values) on reset?

Also not sure how mask ROM handles this. Maybe @moidx, @alphan, or @mundaym can comment?

**Comment by matutem** [comment]
By the way, a similar issue may arise for the clk_hints CSR, since we could reboot with AES, HMAC, KMAC, and/or OTBN disabled.

**Comment by tjaychen** [comment]
sorry i should clarify one thing and add to @matutem point.

It's not specific to UART, it really applies to ANY block the rom might want to make use of (both test and mask).

Since we don't know exactly why the system reboot when watchdog fires, (it could be that someone was trying to access otbn but the otbn hint was set to disable clock), so as a precaution ROM should make sure to turn on the clocks / resets to whatever block it needs to access.

**Comment by timothytrippel** [comment]
Should it just be what {test,mask} ROM needs to operate (e.g., for test ROM that would just be UART for logging and I think HMAC for primitive bootstrap)? Or should we just be safe and re-enable everything? I guess the question is, is there a downside to re-enabling everything besides some wasted power?

**Comment by tjaychen** [comment]
i think re-enabling everything is okay. As long as nothing is using those blocks, they shouldn't consume THAT much power. 
And we can always start turning things down again once we get to later stages of code that can be updated.

**Comment by matutem** [comment]
I think it *should* turn everything back on. By the way, a similar issue may arise with rstmgr sw_rst_ctrl_n CSR.

If the ROM didn't turn things back on we will have a very complicated chip behavior, since it could effectively boot in a lot of different combinations of units on/off or reset, and all of these will need to be fully tested... A bad recipe for success...

**Comment by timothytrippel** [comment]
I just filed #11083 to address clkmgr issue in test ROM. PTAL when you get a moment.

**Comment by matutem** [comment]
It seems this can be marked as Fixed. @tjaychen WDYT?

**Comment by timothytrippel** [comment]
I spoke with @matutem today and he said that the HW was updated to no longer require ROM to reenable/reset clocks. If this is indeed true, then #14312 cleans up the test ROM, and when it merges, this issue can be closed.

Can you either confirm / deny @tjaychen ?

**Comment by alphan** [comment]
@tjaychen ping :)

**Comment by tjaychen** [comment]
ah yes, confirmed!

**Comment by alphan** [comment]
Thanks @tjaychen!
