### ISSUE TITLE
[dv] Create FPV connectivity test for lc_escalation tests in top-level

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#11208]
As discussed in an email thread, once the cpu is escalated then it is not able to run software. FPV connectivity test is a better way to verify this.

cc: @sriyerg @msfschaffner @davebwil @timothytrippel

**Comment by msfschaffner** [comment]
Indeed, this is probably the right way for most IPs since we verify all of these actions at the block level.

However, for the CPU itself, do we need a test that makes sure that indeed it does not run anymore once LC_ESCALATE_EN has been asserted?

I am not sure that path is tested at the block level, since this functionality is part of the `rv_core_ibex` wrapper, which I believe is not part of the Ibex block-level DV environment.

**Comment by tjaychen** [comment]
yeah that's something we should check. 
I don't think it could be fully self contained, but it would be good to probe the fetch signals and possibly the PC is no longer advancing.

**Comment by weicaiyang** [comment]
> However, for the CPU itself, do we need a test that makes sure that indeed it does not run anymore once LC_ESCALATE_EN has been asserted?

yeah, we don't have a block-level testbench to test this ibex glue logic in top_eargley, so we need to have a top-level SW test to verify it

**Comment by weicaiyang** [comment]
Thanks @cindychip for adding the connectivity tests in https://github.com/lowRISC/opentitan/pull/11261
There are 2 remaining items
1. add a ibex with lc_esc test in top-level
2. clean up other lc_esc tests in top-level testplan and add a connectivity testplan

**Comment by sriyerg** [comment]
> Indeed, this is probably the right way for most IPs since we verify all of these actions at the block level.
> 
> However, for the CPU itself, do we need a test that makes sure that indeed it does not run anymore once LC_ESCALATE_EN has been asserted?
> 
> I am not sure that path is tested at the block level, since this functionality is part of the `rv_core_ibex` wrapper, which I believe is not part of the Ibex block-level DV environment.

This is a simple assertion check to prove when lc_escalate_en asserts, the PC does not advance.

**Comment by msfschaffner** [comment]
Connectivity tests for `lc_escalate_en` have been added in #11261 and an assertion checking that the PC does not advance when the CPU is disabled is added here: https://github.com/lowRISC/opentitan/pull/15101 (note that it is sufficient to check this, since the block level DV checks that the `cpu_en` signal is not asserted when in escalation mode).

**Comment by weicaiyang** [comment]
> Connectivity tests for `lc_escalate_en` have been added in #11261 and an assertion checking that the PC does not advance when the CPU is disabled is added here: #15101. Note that it is sufficient to check this, since the block level DV checks that the `cpu_en` signal is not asserted when in escalation mode.

SGTM. Thanks @msfschaffner. Closing this issue
