### ISSUE TITLE
SPI_HOST: DUT unresponsive with RX FIFO reads at the end when active = 0

### ISSUE THREAD

**Issue by visbaz** [lowRISC/opentitan#11526]
For some of the seeds i find the below scenario.

all tx transactions are sent.
finally any rx transactions are read out.
while active = 0 and TB continue to read transactions from FIFO suddenly DUT is non responsive.
I am polling for rxqd = 0 in status and timing out.

some example seeds:
PR : https://github.com/lowRISC/opentitan/pull/11082
util/dvsim/dvsim.py hw/ip/spi_host/dv/spi_host_sim_cfg.hjson -i spi_host_event --waves --fixed-seed 2838982550
util/dvsim/dvsim.py hw/ip/spi_host/dv/spi_host_sim_cfg.hjson -i spi_host_performance --waves --fixed-seed 714456067

I wandered too much in the design . I needs some debug insights on this.
Could be a corner case as well.

**Comment by martin-lueker** [comment]
Hi Viswa: FYI, I'm running these now.  The seeds you have input though no longer seem to be failing.  This can happen if you rebase your PR, or edit it. (as of course one will).  That said, in the future can you make a separate branch for the _issue_, and point to that?   That way even if the PR gets updated, the issue-related branch will stay unchanged.

In the meantime, I see that there are many failing seeds to choose from.  So there is plenty to fix! However I'm not sure that these other bugs that I'm finding are the same as your issue here.  (So I don't know if your evaluations of the failures applies).  However I will look at these seeds and try to fix some bugs.

**Comment by visbaz** [comment]
@martin-lueker closing this issue now and will raise a new one if i find the same in latest regression
