### ISSUE TITLE
[bazel] build with -c dbg flag

### ISSUE THREAD

**Issue by drewmacrae** [lowRISC/opentitan#11549]
Bazel allows for control of compilation mode as described in their documentation:

    "--compilation_mode (fastbuild|opt|dbg) (-c)

    The --compilation_mode option (often shortened to -c, especially -c opt) takes an argument of fastbuild, dbg or opt, 
    and affects various C/C++ code-generation options, such as the level of optimization and the completeness of debug 
    tables. Bazel uses a different output directory for each different compilation mode, so you can switch between modes 
    without needing to do a full rebuild every time.

    fastbuild means build as fast as possible: generate minimal debugging information (-gmlt -Wl,-S), and don't optimize. 
    This is the default. Note: -DNDEBUG will not be set.
    dbg means build with debugging enabled (-g), so that you can use gdb (or another debugger).
    opt means build with optimization enabled and with assert() calls disabled (-O2 -DNDEBUG). Debugging information 
    will not be generated in opt mode unless you also pass --copt -g."

This should be changed from the default fastbuild to debug, but doing so appears to cause issues with our builds that should be debugged.

**Comment by mcy** [comment]
@cfrantz could you confirm this is still an issue? I think we decided that we didn't want to bother making the mask ROM build in -c dbg. I think there's a separate question about making fastbuild be -O1, because the code clang emits in -O0 is hot garbage. Clang allocates everything on the stack in -O0 and needs a [mem2reg](https://llvm.org/docs/Passes.html#mem2reg-promote-memory-to-register) pass from LLVM to be halfway decent. If we don't want to build at -O1 I think `-mllvm -mem2reg` might do what we want...?

**Comment by alphan** [comment]
lowRISC/bazel-embedded#9 updated `fastbuild` to use `-Os` and `-g`
