### ISSUE TITLE
[otbn,dv] Cover and trigger URND/RND spurious ack checking

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#11546]
OTBN is going to have checks that make sure we don't get acks from either EDN interface when we're not expecting them. Add coverage for these events and then write sequences to trigger them.

> estimate 8
> remaining 2022-08-11 4
> remaining 2022-08-15 2
> remaining 2022-09-15 1

**Comment by ctopal** [comment]
@vogelpi and @GregAC : Is this one only about repetition and `FIPS` related checks?

**Comment by vogelpi** [comment]
No, this is not related to repetition and FIPS checks. The repetition and FIPS check tell us something about the quality of the received entropy.

The spurious ack checks tell us whether we've received entropy without requesting it. This is a strong sign that something doesn't behave as expected which may be due to a) a bug, or b) some FI attack going on.

**Comment by johngt** [comment]
Adding coverage point to see it happening.
Change response to see random ack.

**Comment by andreaskurth** [comment]
> estimate 4 2022-08-11

**Comment by andreaskurth** [comment]
> remaining 2022-08-15 2

**Comment by johngt** [comment]
Triggering done. Cover points not yet complete @prajwalaputtappa

**Comment by ctopal** [comment]
>remaining 2022-09-15 1

**Comment by GregAC** [comment]
#14919 merged so closing
