### ISSUE TITLE
[sysrst] intr_status can be only triggered once for a pin edge change 

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#11565]
@msfschaffner 

Found an issue when I tried to test a pin edge triggered interrupt.

The key_intr_status was triggered twice, but in the 2nd time, the intr_status kept low. Looks like the `q_sync_q` wasn't clear so that intr_status was no longer set after the 1st interrupt.
![Screen Shot 2022-03-18 at 9 25 59 PM](https://user-images.githubusercontent.com/49293026/159106689-461b4d71-dc62-4164-b4b2-2ddb357299c7.png)

Use this command to open waves
> ot_debug -j smart:43fbabc0-ae75-4800-8b71-9242d470b6e0

cc: @patel-madhuri

**Comment by msfschaffner** [comment]
It looks like the interrupt pulse was generated based on the `wkup_req` register status, which means that the interrupt does not fire unless that register is cleared. 
This feels awkward from a programming model perspective.
I changed this so that interrupt generation is not dependent on the state of that register in #11575.

**Comment by weicaiyang** [comment]
> It looks like the interrupt pulse is generated based on the `wkup_req` register status, which means that the interrupt does not fire unless that register is cleared. This feels awkward from a programming model perspective. I changed this so that interrupt generation is not dependent on the state of that register in #11575.

I see. The fix makes sense. Thanks @msfschaffner
