### ISSUE TITLE
Hardware revision register

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#11605]
It looks like we don't have a register for reading the hardware version yet but we should probably have one, e.g. to populate the device id used during bootstrap and reporting purposes. [context](https://github.com/lowRISC/opentitan/pull/11573#discussion_r831558917)

lc_ctrl seems like a good place for this register.

**Comment by tjaychen** [comment]
yeah sorry, i completely forgot something like this is needed. We need to put it "somewhere".
Life cycle makes sense, as it's somewhere we can read out along with device ID. 

@moidx 
@msfschaffner 
@cindychip 

I think how this will work is that it will be defined as a top level constant that is then fed into places.
So one would be `lc_ctrl`, and we can feed it into other places as needed. 

Any thoughts @msfschaffner ?

**Comment by msfschaffner** [comment]
This would be easy to add, and LC makes sense since this will allow us to read it even in locked / raw life cycle states (via the LC TAP) where the processor cannot run.

We would have to coordinate with DV, though, since this will need a minor update to the DV env.
@cindychip this should not be much work, right?

CC: @NigelScales
