### ISSUE TITLE
Clarification regarding pattgen count rollover test

### ISSUE THREAD

**Issue by patel-madhuri** [lowRISC/opentitan#11791]
The pattgen count rollover test description in testplan says:

Program the pre-divider and size registers to unconstraint random values
Program the clk_cnt, bit_cnt and rep_cnt to values less than but close to predivider and size registers, so that counting would take a reasonable number of clock cycles
 
In my test, I am assigning below values 
 `DV_CHECK_RANDOMIZE_WITH_FATAL(ch_cfg,
      ch_cfg.prediv == 'hffff;
      ch_cfg.len    == 'h3f;
      ch_cfg.reps   == 'h3ff;

With the clk_cnt (which is prediv value), bit_cnt (which is len), rep_cnt(which is reps) less than but closer to prediv and size registers, and unconstraining the random values, the test runs for a very long time. For me it ran for 40 mins and gives testbench timeout error. 

Do we still want to unconstraint the random values? Or What maximum values are excepted for a real time scenarios? 

@cindychip I am not aware who is the responsible person for pattgen block  from google. Could you please reassign to the responsible person?

**Comment by cindychip** [comment]
Thanks Madhuri for raising this issue. From DV perspective, I agree running such a long test does not really worth the simulation time. Can we force the internal value, such as:`rep_cnt` to be closer to `3ff` to reduce the simulation time, but still test the overflow cases?

**Comment by cindychip** [comment]
Hi Madhuri,

Constrain the reg values will work but can you try the following - 
Instead of testing all the extreme max values, can we constrain to have at most one max value per run? Will that also reduce the simulation time?
I think it is still good to hit the max val of the register, just not all together.

If the above suggestion works, could you also ensure the functional coverage is implemented to capture the max value of the registers?

**Comment by patel-madhuri** [comment]
Thank you Cindy for all your inputs. Since this test is now merged and running in regression we can close this issue.
