### ISSUE TITLE
[prim_secded_inv_hamming_39_32] Error detection

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#11849]
Hi Michael,
In the FPV testbench, I saw failures on some assertions when running `../../../util/dvsim/dvsim.py top_earlgrey_fpv_cfgs.hjson --select-cfgs prim_secded_inv_hamming_39_32_fpv  --gui`

Main issue was that:
When FPV testbench input 1 bit error to the input of the `dec` module, we somehow saw the `dec` module categorize that as a 2-bits error. Here are the values from the screenshot:
1). `data_in` into `enc` module: `32'hffef_ffff`
2). `data_o` out of `enc` module: `39'h68_ffef_ffff`
3). `data_in` into `dec` module after error injection: `39'h68_ffff_ffff`
4). `data_o` out of `dec` module: `32'hffff_ffff`
      `err_o`: `2'b10`.

From the sequence above, looks like this `secded_inv_hamming_39_32` could not correct 1 bit error injection. Is that expected?

![image](https://user-images.githubusercontent.com/11466553/161331190-67448248-0e1f-49ed-9d58-3dc0bfd87fd2.png)

Thanks,
Cindy

**Comment by msfschaffner** [comment]
Thanks @cindychip. I found the problem and fixed it in this PR: #11861

Note: this issue was only present in inverted Hamming codes. It had to do with the fact that the Hamming codes we use are _extended_ Hamming codes, meaning that the last ECC bit is a parity bit calculated over all bits, including ECC bits. The generated encoder logic mistakenly inverted ECC bits before calculating the last parity bit, thereby leading to wrong results in certain cases.

**Comment by cindychip** [comment]
sorry for the late reply! Thanks Michael
