### ISSUE TITLE
[spi_device] Write enable (WREN) and write disable (WRDI) should be handled in hardware

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#11869]
The write enable command (WREN, 0x06) sets the write enable latch (WEL) bit, while the write disable command (WRDI, 0x04) clears it. The host sends WREN every time before "writing" to the device, e.g. before chip/sector erase or page program. Since handling this in software would introduce additional latency; WREN & WRDI commands should be handled in hardware.

cc @cfrantz @a-will

**Comment by eunchan** [comment]
I remember @a-will @cfrantz and @tjaychen and I had discussion about this. The conclusion was to not implement the feature in HW at the first silicon due to the schedule issue and assumed it is OK to be processed in SW (no latency issue at all here).

If WE is 0, and host sends WREN and PROGRAM commands, SW can process WREN first then PROGRAM, as CMD_FIFO has multiple entries. Then PROGRAM can set BUSY 1. Host will poll the BUSY status to send next PROGRAM commands.

I don't see any side effect on this.

**Comment by a-will** [comment]
> I remember @a-will @cfrantz and @tjaychen and I had discussion about this. The conclusion was to not implement the feature in HW at the first silicon due to the schedule issue and assumed it is OK to be processed in SW (no latency issue at all here).

That is not strictly true. Hosts can check the status register immediately following a WREN command, and that would be too fast for firmware to make the observable change. We're playing fast and loose without hardware handling of WREN, but I can't claim to have seen the host that behaves in the way described.

**Comment by eunchan** [comment]
What happens if the host system issues WREN then read back the STATUS but it shows still WE bit is 0?

Honestly, I don't want to revise the design as we are approaching the RTL freeze. If the status read is rare and host is able to handle the incorrect status bit , then I think it is ok to move on?

**Comment by a-will** [comment]
> What happens if the host system issues WREN then read back the STATUS but it shows still WE bit is 0? Honestly, I don't want to revise the design as we are approaching the RTL freeze. If the status read is rare and host is able to handle the incorrect status bit , then I think it is ok to move on?

It's a misbehaving spi_device, and the host would consider this to be a fault of some sort. I can't exactly give guidance about what response the host application would have, since the severity and action to take would depend on the context.

I would also advocate for us getting this done. If you're concerned about schedule, shall we chat about options?

**Comment by tjaychen** [comment]
@eunchan i think is out for a few days, so just to summarize:

1. if we have a well behaving host that always does WEN then PROGRAM, I think the claim is that this will be okay since we can rely on the second operation setting "BUSY=1" to stall the operations.

2. However if we have a host that sets the status and reads it back, we would be a non-compliant device since it will look like we "ignored" the host's request to set the status.  Is that correct?

**Comment by eunchan** [comment]
I understand the reason of the HW-processed WREN/ WRDI commands. @domrizz0 may comment about the schedule :)

**Comment by eunchan** [comment]
https://docs.google.com/document/d/1ogKkYK3G9XCXBwhdflMmyRE4SBvUXvBRhb3zHY7QyvQ/edit

Here's the summary doc. Please take a look.

**Comment by eunchan** [comment]
Recent PRs addressed this feature request. Can we close this issue?
