### ISSUE TITLE
[bazel] cannot load rules and deps for lowRISC misc-linters in CI

### ISSUE THREAD

**Issue by drewmacrae** [lowRISC/opentitan#11981]
https://github.com/lowRISC/misc-linters/blob/master/rules/deps.bzl provides rules that are incompatible with CI

It's running an instance of pip that isn't supported in CI's Python 3.6, it should be rolled back to avoid quietly pushing an upgrade requirement onto CI.

**Comment by drewmacrae** [comment]
Since they're currently loaded in the bazel WORKSPACE it makes it incompatible with CI which is a thing

**Comment by rswarbrick** [comment]
Honestly, I don't really understand why that repo (which contains ONE PYTHON SCRIPT!!!!) has a whole load of Bazel rules. My preference would probably be to:
1. copy those rules over to OpenTitan
2. Add an ignore file to the vendored directory to ignore the stuff that was there
3. Remove from misc-linters and re-vendor

**Comment by mcy** [comment]
Hi Rupert,

The rules are there because the logic to set up appropriate application of the script are somewhat involved (as it is for any linter). This logic is re-used in other lowRISC repositories, including embargoed repos.

The correct solution here is to make misc-linters pick up the python interpreter from OT. I can look into this next week-- I am already underwater with other Bazel cleanups.

**Comment by drewmacrae** [comment]
I'll see what I can do to get the python interpreter loading. I think I wrote the commit to take it as-is.

**Comment by drewmacrae** [comment]
Bazel doesn't support python 3.6 because it's gone EOL https://github.com/lowRISC/opentitan/issues/11984

**Comment by mcy** [comment]
Fixed: https://github.com/lowRISC/misc-linters/pull/27
