### ISSUE TITLE
The UART should be enabled by default at power-on/reset

### ISSUE THREAD

**Issue by rminnich** [lowRISC/opentitan#1208]
Platforms in general should always have the UART enabled at PO/R. This makes it easy to debug the pinmux setup. Decades of firmware experience has shown that systems that don't have UART enabled at PO/R are a real headache to debug. From what we are seeing OT is a "UART not on by default" system.

**Comment by mdhayter** [comment]
Does this suggest one UART should always be on dedicated pins? If the system starts with pinmux connecting the UART then (a) the pins for UART are forced (b) switching the TX pin to another use with the pinmux has the issue that the pin will be driven high for a period after reset dictating something about the alternative use (c) if the RX pin is used for something else then any resistors ensuring state at reset time could cause the UART to get unhappy.

Counter could be if you were just using the pinmux to select between two RX pins.

**Comment by tjaychen** [comment]
i agree with @mdhayter, i don't really think we should be defaulting any pins to a specific functionality unless we are comfortable enforcing a specific use case for all applications. 

In addition, our UART functionality isn't enabled by default, it needs to be setup by some piece of software (for example baudrates, which are dependent on clock frequencies), so that same piece of software may as well also setup the pin selections (this will happen in ROM, modulated by some OTP selections, so it's quite close to hardware default anyways)

**Comment by mdhayter** [comment]
Of course if the ROM code uses a uart then the discussion may be moot because the ROM code will set it up anyway. On the other hand, Im not sure I agree we would want the ROM to set up most of the pinmuxing.

**Comment by tjaychen** [comment]
yeah definitely not. I'd only want ROM code to setup pins it needs.  Certainly dumping debug messages out of ROM is sometimes a nice feature to have, that's why I said it should be modulated by an OTP setting.

**Comment by imphil** [comment]
All UARTs are on muxed pins in top_earlgrey, it's up to bootrom to configure the muxing.

@tjaychen @cfrantz Can you have another look at @rminnich's comment above and check that what we have currently is what we want, and then close the issue?

**Comment by tjaychen** [comment]
yeah i think it's fine to just let ROM set this up. For all practical purposes the uart pins used by ROM are dedicated (from a system integration sense), but i think we prefer to leave it muxable for later flexibility.
