### ISSUE TITLE
[sram_ctrl, flash_ctrl, icache, otbn] Protecting scrambling keys at rest

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#12111]
Scrambling keys are currently obtained from OTP and then stored locally in a register for use with the scrambling device.
However, that register is not protected against any FI injection, which may in rare cases be exploited.
Should we ECC protect these key registers and trigger an alert if there is a mismatch?

**Comment by tjaychen** [comment]
i honestly think sram_ctrl, otbn, icache by virtue of being ephemeral, it is okay for now. 
otbn specifically will get software redundancy layered across. 

For sram, really sensitive variables will need to be separately hardened by software, and i'm hoping if the key is attacked, it will mostly look like garbage instruction for the icache. In theory this should be difficult to reproduce across power cycles.

For flash the key is installed really early during manufacturing, so any disturbance later will actually cause code verification to fail. Any stored data will also get really wonky. 

@msfschaffner could you add Bilgiday also to get his thoughts? 

While i'm not saying this is bad to do, for the blocks that have passed D2S I really think we should refrain from re-opening unless we absolutely have to. The `we` protection I think was necessary because for ibex at least, those were unprotected otherwise. Here it is already protected, and it is just more layering.

**Comment by msfschaffner** [comment]
Your reasoning makes sense. I just wanted to bring it up so we can document this decision somewhere. I will mark this as a future enhancement for now.

**Comment by andreaskurth** [comment]
Triaged for `sram_ctrl`. Suggest to keep https://github.com/lowRISC/opentitan/labels/Type%3AFutureRelease as per the arguments above.

**Comment by GregAC** [comment]
Triaged for `flash_ctrl`, happy to keep https://github.com/lowRISC/opentitan/labels/Type%3AFutureRelease

**Comment by GregAC** [comment]
Triaged for `otbn`, same conclusion as above

**Comment by GregAC** [comment]
Triaged for `ibex`, same conclusion as above

**Comment by msfschaffner** [comment]
Do we think this is still useful to do? It seems like defense in depth and may not be warranted to spend much effort on, given that these are just ephemeral scrambling keys.

**Comment by msfschaffner** [comment]
@johannheyszl @vogelpi WDYT?

**Comment by vogelpi** [comment]
Johann and I think it would make sense to at least bring this up in the Sec WG. I am thus adding the corresponding label.

Personally, I think additional ECC can make sense when there is a long timing window between refreshing the scrambling key and actually using it. Otherwise, injected bit flips likely lead to ECC errors upon reading the memory with an invalid key as Tim pointed out above. Then the attacker needs to glitch the key upon loading which is harder because the timing needs to be right.

**Comment by vogelpi** [comment]
The new OTBN-specific issues is here: #20162
