### ISSUE TITLE
[usb_fs_nb_pe] Move to usbdev or hw/vendor

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#12140]
It just occurred to me that `usb_fs_nb_pe` is actually not a real comportable IP, but rather something like a vendored in IP with some patches applied. It would therefore make more sense to move this under `hw/vendor` with an associated patch repository - or if that is not an option, move the files under `usbdev`.

WDYT?

**Comment by tjaychen** [comment]
i think it would be nice to clean this up, but i'm not really sure it's worth doing at the moment.
there have been fixes made to the block itself, and going back to re-create all the patches at this point seems a bit overkill.

If we have to move it I would suggest under usbdev.

**Comment by a-will** [comment]
Realistically, we've hard forked this module from its roots. The original module looks very different in a lot of places, and we have no intention of following upstream (different use case). Thus, I don't think vendoring this module is the best path.

Does that make sense? Am I missing a good reason for it?

**Comment by msfschaffner** [comment]
Ok, that makes sense. In that case I would suggest we collocate it together with the `usbdev` files, since it is not a comportable IP in itself. Does that make sense?

**Comment by a-will** [comment]
> Ok, that makes sense. In that case I would suggest we collocate it together with the `usbdev` files, since it is not a comportable IP in itself. OK?

SGTM.

**Comment by mdhayter** [comment]
I know it is not used in the current OT, but this code is also used by the usbuart IP. That is why it was put as its own directory.
(Of course usbuart has probably decayed because nobody has been testing it for interface or primitive changes. I was doing that for a while, but probably not in 15 months.)

I agree this is now very different code from its upstream (which was usb_fs_pe, i.e. had the buffers that the nb non-buffered version removed) and has been fixed for coding convention.

**Comment by tjaychen** [comment]
it probably makes sense to move this under `usbdev` and give it its own core file in case we want finer granularity re-use in the future.
