### ISSUE TITLE
[dv/exp_alert] Enable checks with multiple alerts

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#12282]
The clkmgr frequency checks trigger alerts whenever there is a recoverable error in the clock count measurements. By default this triggers the cip_base_scoreboard exp_alert checker, which currently can only handle one alert at a time, and if multiple alerts of the same kind fire it will cause a failure. The measurement functionality depends on clock domain crossings, which makes it impractical to make sure only one such alert will fire. This means we need to disable alert checks.

The ask is to provide some way to handle multiple alerts.

**Comment by rswarbrick** [comment]
This might be difficult to do in general. Imagine that I know two alerts, A and B, are pending but are indistinguishable to the alert machinery. Suppose A is due in the next 10 cycles and B is due in the next 100. If B arrives first then we'll have no way to know that it wasn't "A". What happens if A actually arrives after 50 cycles. That's a bug, but it's indistinguishable (to the generic code) from A arriving immediately and then B arriving after 50 cycles.

I suspect the best thing is to disable the generic machinery in the clock manager and do something custom (where you have extra "out of band" information to tell you whether what you're seeing is right or not).

**Comment by matutem** [comment]
I agree it is difficult, and I was considering just checking the alert outputs for these cases. Even more: we could just check connectivity from each of the recoverable error bits to the alert sender: if they are connected we are okay since the tests check the recoverable error CSRs. This is simple and practical.

**Comment by matutem** [comment]
Hmm, I noticed the clkmgr_frequency_timeout faced a similar problem, and we decided to directly use the cip maintained alert count instead. We can do the same for clkmgr_frequency.

Closing this issue.
