### ISSUE TITLE
[doc:aes] functionality not documented sufficiently 

### ISSUE THREAD

**Issue by rasmus-madsen** [lowRISC/opentitan#1229]
@vogelpi 
I would like the auto functionality to be documenteed more explicitly

i.e it does not state what causes the AES module to start a new calculation.
I assume that happens when data_in3 is written - but it needs be in the spec.
as far as I can tell there is nothing in your spec that prevenst me from adding data from data_in3  to 0.
or in a random order.
is this allowed?

same goes for the force_overwrite functionality
how does the aes module know data has been read?
what happens If read the output registers from top to bottom or in a random order?

**Comment by vogelpi** [comment]
Hi @rasmus-madsen,
thanks for creating this issue.

The order in which those registers are to be written or read is not documented because it does not matter. Software just needs to write/read every register of the set at least once.

I can add this to the documentation. However, thinking more about it: Would it make sense from a DV perspective to change this? Would it be better for DV to e.g. require that the input registers are written in the order data_in0, data_in1, data_in2, data_in3? Then DV would not have to check all possible sequences of writing those registers. WDYT?

**Comment by rasmus-madsen** [comment]
@vogelpi 
oh ok, 
I think any order is great - I will just have the sequence randomize which order they are written in.
