### ISSUE TITLE
[dvsim] prints abbreviated usage to avoid issue with `argparse` and argument specification

### ISSUE THREAD

**Issue by drewmacrae** [lowRISC/opentitan#12377]
argparser prefers and lists usage as:
`dvsim.py [options] positional-arguments`
but then doesn't support it if the final option is of arbitrary length (it interprets positional args as part of the list of arbitrary length and complains that they're missing).
It's hard to make small changes to the usage message from argparser to either include the `--` to terminate the arbitrary length list or change the order.
It's also hard to make argparser identify the positional arguments correctly if written as shown in the usage.

We mostly document a workaround already, but not directly, but the described usage is repeated once more in OT, incorrectly in a script that suggests how to kick off a dvsim run after building artifacts.

**Comment by rswarbrick** [comment]
Does anyone actually use the `--nargs '*'` / `--nargs '+'` behaviours? (@cindychip, @weicaiyang, as long-standing Google DV'ers)

Another option would be to change the syntax from e.g. `dvsim.py --build-modes foo bar --blah blah` to `dsim.py --build-modes foo,bar --blah blah`. This looks much more like "normal" tools and avoids all sorts of weird parsing corner cases.

If anyone has strong feelings about it, speak up! Otherwise I'll probably push a PR to switch to a more conventional argument parsing approach in a week or so.

**Comment by drewmacrae** [comment]
@rswarbrick I think this describes a more maintainable set of invocations, and would be an improvement, but I don't know how much of the tools are opensource so it's hard for me to assess the cost of the transition.

If we have such a preference (and we probably should) it should get [documented here](https://docs.opentitan.org/doc/rm/python_coding_style/#python-conventions) to keep our tools more normal or conventional in the future.

There appear to be [32 python files that use nargs='wildcard'](https://cs.opensource.google/search?q=filepath:.py%20nargs%5Cw*%3D%5Cw*(%5C%22%7C%5C%27)(%5C%2B%7C%5C*%7C%5C%3F)(%5C%22%7C%5C%27)%20OR%20argparse.REMAINDER&ss=opentitan%2Fopentitan).

The statement: "Python3 is the main language used for simple tools." might give us some leeway to leave them as-is with an understanding that we'll take the edges off when the tools get reworked to hold increased complexity.

**Comment by rswarbrick** [comment]
I don't think that anyone can describe dvsim as a simple tool while keeping a straight face :-)

I'm not particularly worried about breaking closed stuff with dvsim changes. The arguments in question are generally used on the command line ("just run the following tests for me"): I wouldn't really expect them to appear in the nargs=* form in a script.

But I'm not advocating some wholesale rewrite across the repository either: it just looks like this might be a good place to clean things up.

**Comment by drewmacrae** [comment]
All the open references to dvsim.py that I looked at consume zero or one additional argument per option.

**Comment by weicaiyang** [comment]
> Does anyone actually use the --nargs '*' / --nargs '+' behaviours? (@cindychip, @weicaiyang, as long-standing Google DV'ers)
Another option would be to change the syntax from e.g. dvsim.py --build-modes foo bar --blah blah to dsim.py --build-modes foo,bar --blah blah. This looks much more like "normal" tools and avoids all sorts of weird parsing corner cases.

I use `dvsim.py a.hjson -i test1 test2`. Since I always put the required positional args first, it's not an issue to me.

**Comment by rswarbrick** [comment]
Heh, that's really funny! Once upon a time, it was super-important to put the flags to programs first and the positional arguments last (argument parsing has improved since then). There are two different unambiguous ways to encode things we could switch to. Do you have a preference between `-i test1 -i test2` and `-i test1,test2`?

**Comment by weicaiyang** [comment]
> There are two different unambiguous ways to encode things we could switch to. Do you have a preference between -i test1 -i test2 and -i test1,test2?

I don't have a preference. Both look good to me. And they should solve the issue

**Comment by sriyerg** [comment]
> Another option would be to change the syntax from e.g. `dvsim.py --build-modes foo bar --blah blah` to `dsim.py --build-modes foo,bar --blah blah`. This looks much more like "normal" tools and avoids all sorts of weird parsing corner cases.

One issue I can think of is if comma is a part of the option value itself, for example. `--run-opts +myplusarg=a,b,c,+myotherplusarg=foo`. The UVM code has usecases like this.
