### ISSUE TITLE
[otp_ctrl] HW_CFG partition question

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#12428]
Hi Michael,

1). Current [otp_ctrl_img_raw.hjson](https://github.com/lowRISC/opentitan/blob/master/hw/ip/otp_ctrl/data/otp_ctrl_img_raw.hjson) needs a mubi type as default value. Otherwise we will see assertion failures.
So I think we will need to add a hw_cfg section in raw_img.hjson as PR: https://github.com/lowRISC/opentitan/pull/12427

2). With this change, I do not think user can write from False -> True or True -> False in OTP_CTRL even though the HW cfg partition is not locked, because it is an 8 bit mubi type.
Writing them again will have a write-blank error.
Do you think this will be an issue? Will we ever have a usecase where we needs to update the access from `False` to `True`?

Thanks,
Cindy

**Comment by msfschaffner** [comment]
Hi @cindychip!

Good catch - that is indeed an issue.

While we will likely burn MUBI values into OTP as either `true` or `false` during provisioning, we do expect the unprogrammed all-zero values to be interpreted as `false`. 
There are two potential solutions to this that I can think of:
- either we loosen up the assertions on MUBI signals that come from OTP
- or we "rectify" all MUBI values stored in OTP so that they have the correct encoding when they leave the OTP controller.

@tjaychen WDYT? This is similar to the rectification problem we discussed in CSRs - but in this case we have no way to set the reset state to a legal value.

**Comment by tjaychen** [comment]
i feel like rectifying all of it might be a bit overkill, since we've so far required all downstream users to consume these MUBi's in a specific way.  Especially if the users are in a different clock domain, they have flops along the way, which are even more vulnerable. So I feel like correcting at the source isn't quite worth it.  If we were to map this to the csr case we discussed, I think it makes a bit more sense to ensure that the input program must be MUBI of some kind, and that if the value ever becomes non-mubi, we automatically trigger an alert instead of correcting (perhaps when locked).

In this case I feel like just loosening the assertion is probably more reasonable. We probably won't have many tests with a completely blank OTP right? For others it seems like @cindychip PR will do the trick?

**Comment by cindychip** [comment]
Thanks @tjaychen for the feedback. So I guess that means - once we stream in the initial OTP image at raw stage with the mubi values, these values are set to either true or false, and cannot be changed. Is that expected?

**Comment by tjaychen** [comment]
o sorry. I misread this. I read it as "rma" and not "raw".
We can't do this for raw, since it would completely invalidate the definition of raw.
Do we have a lot of cases where we need to use a raw hjson? I was thinking for those we could loosen the assertion.

**Comment by cindychip** [comment]
No worries! There have not been much use-cases - this is probably the only one so far.
Yeah, loosen the assertion should solve the issue :)

**Comment by tjaychen** [comment]
does my rationale on not correcting make sense? I'm not sure it's worth a detect and reconstruct there...since it doesn't decrease the downstream's burden of checking, and may create another vulnerable attack point.

So to me it makes more sense to regulate on program, and potentially detect as alert once locked.

**Comment by cindychip** [comment]
I agree, I do not think it is necessary to correct it at the beginning.

**Comment by msfschaffner** [comment]
Agreed, I would also prefer not to add rectifyers to the HW because it adds more complexity and thereby vulnerable points. The downstream logic should still work correctly when all-zero values are present due to the use of the `strict` MUBI checking functions.

**Comment by cindychip** [comment]
sounds good. I am going to disable the assertion then! Feel free to re-open this issue if you think we need to discuss more on it.
