### ISSUE TITLE
[sw] Enable Ibex's icache in test_rom

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#12883]
The icache within Ibex starts disabled and needs to be specifically enabled via a write to the Ibex specific `cpuctrl` CSR (see https://ibex-core.readthedocs.io/en/latest/03_reference/cs_registers.html#cpu-control-register-cpuctrl).

Do we enable the icache anywhere? We should turn it on for at least some chip level testing (as these are also helping verify Ibex along with the specific things they're aimed at). Has any consideration be given as to when to enable it in the boot flow?

@arunthomas @cfrantz @mundaym

**Comment by tjaychen** [comment]
no it's not turned on right now.
I'm hesitant to turn it on because the flash isn't fully verified and i'm pretty sure could break against the aggressive fetching nature of the icache. 

I have brought up this poihnt with both @alphan and @cfrantz before, and it's just something that's pending.  Thanks for filing an issue though.

**Comment by tjaychen** [comment]
sounds good to turn on to me. 
if you guys find any weird flash blocking issues, let me know.

**Comment by alphan** [comment]
@GregAC and @tjaychen I tried enabling icache in #13110 but after that I didn't receive anything from UART (cw310). That PR adds an OTP entry and updates the DEV and RMA hjson files. I've just pushed an update that reverts the value of the OTP entry to `0`. If this doesn't fix the issue I might have to comment out the `CSR_WRITE()`.

cc @moidx @cfrantz

**Comment by tjaychen** [comment]
yep that sounds good! thanks for changing the title also to better reflect the issue.

**Comment by moidx** [comment]
Hi @arunthomas, can you provide an update on the next steps here? Thanks!

**Comment by arunthomas** [comment]
@timothytrippel will work on this

**Comment by tjaychen** [comment]
hey all, very related to this topic, @alphan had brought up the idea of using a singular ROM for all purposes, with maybe specific features turned off (such as verification and certain hardening).  Do we want to consider this path? Or do we feel its lower priority and okay to live with testrom for now? 

I don't know how much work @alphan suggestion is, and I'm not sure how many things in the DV TB are currently dependent on specific testrom behavior (like setting the test_status for example).

**Comment by alphan** [comment]
Thanks for pointing this out @tjaychen. I think it's a good idea to enable this sooner rather than later to unearth any hidden issues (like the interaction between icache and address translation) but @timothytrippel is aware of our plans for _eventually_ converging to a single ROM (with some specializations) and thus I recommended implementing something as simple as possible.

**Comment by tjaychen** [comment]
> Thanks for pointing this out @tjaychen. I think it's a good idea to enable this sooner rather than later to unearth any hidden issues (like the interaction between icache and address translation) but @timothytrippel is aware of our plans for _eventually_ converging to a single ROM (with some specializations) and thus I recommended implementing something as simple as possible.

sounds good. Thanks @alphan / @timothytrippel
