### ISSUE TITLE
[sw/hart] busy_spin_micro not completely accurate 

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#12889]
While debugging #12871 , we noticed that the `busy_spin_micro` routine is not completely accurate.
So if you wanted 10us and that equated to 1000 cycles, the actual cycle count you get is slightly lower due to the formula being based on 1.04M insetad of 1M.

@engdoreis has some ideas on how to fix this, so we are opening an issue to track.

**Comment by matutem** [comment]
Some notes: I created https://github.com/lowRISC/opentitan/pull/13255 with a proposed change that is accurate.

There is one potential drawback: there are comments in the code saying sim_dv may set the main clock to some random value, but I don't really think we do. If we did, then I think a proposal by @drewmacrae that computes the cycles as (kClockFreqCpuHz * (usec + (usec >> 4))) >> 20 is the next best.

Another note: regardless of how this is computed, when the chip runs with jitter enabled the effective wait will be larger than required by some small percentage since the effective clock period is longer: jitter makes some cycles longer, but should never make them shorter or we could end up with timing violations.

**Comment by drewmacrae** [comment]
Before we consider this issue fixed, can we remove the comments in the code saying sim_dv may be randomly set to ensure that's not the plan of record?

**Comment by matutem** [comment]
One more point about setting the clocks to random values in DV. It is not clear what it accomplishes. We do that for unit testing, but in full chip the frequencies are set at manufacturing.

@drewmacrae removing this comment in the source is a good idea.

**Comment by matutem** [comment]
Oops, I didn't remove the comment. I would like to talk to @sriyerg about it next week to close the loop. Reopening this so I don't forget.

**Comment by engdoreis** [comment]
Hi @matutem, this is a kind remind, can we close this issue?

**Comment by tjaychen** [comment]
let's close this for now. We can re-open this if needed.
