### ISSUE TITLE
English breakfast, test_rom, and bootstrap

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#12905]
I ran into this issue while working on #12875 which replaces the previous bootstrap implementation with the new SPI Flash based one. The new implementation performs an OTP read but since it doesn't exist in the english breakfast toplevel all related CI jobs fail.

My workaround to unblock #12875 was to ~fake the OTP using the retention RAM (spoke too soon, turned out to be more complicated than I anticipated)~ define a new target for bootstrap when building for english breakfast and fake the relevant otp, lifecycle, and rstmgr functions.
 
ot-sca repo already seems to be using cw310 binaries (screenshot below). I was wondering if we are planning to maintain this separate top in the long-term.

![image](https://user-images.githubusercontent.com/57949550/170706629-1c15cbf6-b32a-48e6-9ca8-80d9438b5ae1.png)

**Comment by alphan** [comment]
@tjaychen @mundaym @vogelpi

**Comment by alphan** [comment]
Related: #12065

**Comment by vogelpi** [comment]
Hi @alphan ,
the CW305 is still the primary choice for AES SCA. The reasons are mainly twofold: 1) due to the smaller and different FPGA fewer traces are required to observe any SCA leakage compared to the CW310, 2) due to the smaller FPGA and smaller design, Vivado has less freedom in place & route, as a result we get more reproducible results/less variance due to P&R on the CW305.

I did a comparison of the two boards a while ago and the differences were considerable. For this reason we should keep support for English Breakfast. Another reason for keeping a different top level alive is the topgen tooling. With just one top level in CI the tools quickly become top-level specific. Back when I created English Breakfast, quite some effort went into fixing these tools to make them top-level agnostic.

**Comment by vogelpi** [comment]
Regarding OTP: English Breakfast doesn't have it because of resource constraints. What I don't understand, why does faking OTP with retention RAM or even skipping the OTP read completely for the test ROM not work?

**Comment by alphan** [comment]
> the CW305 is still the primary choice for AES SCA. 

Ack. I remember the trials with CW310 but I think I misremembered that we transitioned to CW310.

> Regarding OTP: English Breakfast doesn't have it because of resource constraints. What I don't understand, why does faking OTP with retention RAM or even skipping the OTP read completely for the test ROM not work?

It unnecessarily complicates the silicon_creator code (which is our production code). Also, this wasn't the only dependency that caused an issue when building for cw305. I'll take another look. Thanks!

**Comment by alphan** [comment]
> hmm....do you mean to keep code consistent @alphan , we need some kind of super lightweight otp that can redirect the flow?

We don't actually need any hardware changes, just fake the driver calls so that they return some meaningful value. I was able to put something together that doesn't touch silicon_creator or test_rom sources in #12875.
