### ISSUE TITLE
[uart] default values of tx_empty and tx_watermark

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#1290]
In spec, default values of tx_empty and tx_watermark are 0.

After reset, tx_empty_prev_q will be set to 0 while tx_empty_d is 1. This will trigger an event to update tx_empty. So, after reset, tx_empty will be set.

```
  assign event_tx_empty     = tx_empty_d & ~tx_empty_prev_q;
  assign tx_empty_d = tx_fifo_depth == 6'h0;
  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (!rst_ni) begin
       ...
      tx_empty_prev_q      <= 1'd0;
    end else begin
      ...
      tx_empty_prev_q       <= tx_empty_d;
    end
  end
```

Since we reset tx_watermark_prev_q to 1, and tx_watermark_d is also 1 after reset,  event_tx_watermark remains 0.
```
assign event_tx_watermark = tx_watermark_d & ~tx_watermark_prev_q;
  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (!rst_ni) begin
      tx_watermark_prev_q   <= 1'd1;
    end else begin
      tx_watermark_prev_q   <= tx_watermark_d;
    end
  end
```
Since these 2 interrupts are edge-triggered, should we also change tx_empty_prev_q to reset to 1 and default value of tx_empty becomes 0, or change the spec?

**Comment by tjaychen** [comment]
yeah that seems like a good idea. Let me add that.

**Comment by weicaiyang** [comment]
@tjaychen 
Assume tx fifo is empty and we clear tx_empty interrupt, then write a few tx items into the fifo. 
When the 1st item is written to the fifo and tx is enabled, fifo will pop it out in next cycle. So, fifo changes from non-empty to empty, which triggers the tx_empty interrupt. This interrupt will occur no matter how fast the data are written. It seems a little bit annoying.

Maybe we can use tx_idle to gate it, the actual empty is fifo_size==0 && tx_idle==1

**Comment by weicaiyang** [comment]
Similar issue happens to tx_watermark==0 (1 character)
when 1st item is written to tx fifo, fifo size will change from 1 to 0 as the item is popped for transfer. Then, tx_watermark will be triggered.

Maybe we can change tx_watermark==0 to be 2 character?

**Comment by tjaychen** [comment]
Thanks weicai. I definitely agree on the watermark one, right now the less
than 1 character is the same as empty, so it's not really serving a purpose.

Let me think a bit about the empty case.  I'm not sure I want to qualify
with idle because that means during the entire transfer of the last byte
when the software could have known to prepare new data it's actually doing
nothing.  Maybe there isn't something better to be done, but let me think
me a bit.

**Comment by tjaychen** [comment]
@gkelly @mcy @phil-levis-google

it would be good to get your take on the TX_EMPTY issue.

The implementation as is right now I dont think will work.  As @weicaiyang pointed out, once you write an entry, the hardware almost immediately takes it out and begins to try and transmit it, meaning EMPTY will assert before the next write data has a chance to come in.  I think this has a chance of confusing software and causing problems later.

This essentially boils down to a timing problem.  We could as @weicaiyang suggested, qualify the TX_EMPTY with the entire uart being idle, but even this would be still be vulnerable to the same issue, because if your first and second write had a large enough gap for whatever reason, the same issue could manifest (although very unlikely).

What do you think software prefers here? I prefer not to use uart_idle completely because it means nothing can be done during that last byte transfer time (see #1132), but that's probably the safest thing to do here outside of an explicit software acknowledgement that it is safe to generate empty interrupts.

**Comment by tjaychen** [comment]
@phil-levis

**Comment by weicaiyang** [comment]
design updated at #1406 and DV is done at #1482
