### ISSUE TITLE
[ci] Instructions on how to reproduce FPGA failures

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#13103]
Currently, there are two options for reproducing FPGA test failures:

1. Download artifacts and run things manually. 
2. Instruct Bazel to built the FPGA bitstream as part of the test invocation, for example `./bazelisk.sh test //sw/device/tests:aes_smoketest --define bitstream=vivado`

Both options are rather time consuming. 

It would be nice if CI could upload the FPGA bitstream artifacts to GCS `opentitan-bitstreams` to avoid having to rebuild the bitstream locally.  To manage GCS costs, we could consider setting a TTL.

**Comment by moidx** [comment]
Setting initial priority as P2 as this is not currently blocking production. It will become a P1 later on once we start getting more involved in debugging FPGA test failures.

**Comment by GregAC** [comment]
@milesdai what's the status here?

**Comment by milesdai** [comment]
Sorry, forgot to update this issue. #14550 addresses this problem by adding documentation to the website describing how to reproduce these errors locally. #13115 is not going to be completed since we currently have the functionality to manually load the bitstream and then skip the loading during a test, so it is redundant.

#13070 was supposed to be an attempt to refactor the test-running script to see if we can make that locally runnable, but at the moment, the script is just side-loading the bitstream cache and then make the Bazel invocation. This should not be done manually if someone is debugging, so it's probably fine to defer to the website documentation about manual bitstream loading and just close that issue now.
