### ISSUE TITLE
[clkmgr/dv] Tweak cascade reset assertions for reset domain change

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#13248]
#13095 moved the `clkmgr` reset from `por` domain to `lc` domain.
This changes many of default cascading assertions.  For now, they are commented out, but need to be restored in the future. 

See [hack alert](https://github.com/lowRISC/opentitan/pull/13095/commits/4e147e93ea0776398a64a94c6d21461becc736c0)

**Comment by matutem** [comment]
The RTL has sophisticated checks for cascading that will trigger alerts if violated. This means the cascading assertions could be removed.

**Comment by jeoongp** [comment]
Is it to remove the cascading assertion temporarily or permanently?

**Comment by matutem** [comment]
I think they should be removed permanently. I will send out a PR soon.

**Comment by tjaychen** [comment]
@matutem was this actually done../ I thought I saw a PR, but now I can't remember (and also can't find it).

**Comment by matutem** [comment]
The branch with the changes is ready, but I am not getting the huge fall-out I expected from the reset domain changes, so I was procrastinating on pushing it.

The other part of this issue, that you labelled hack alert is already fixed, since we created special rst_root* interfaces driving reset. The timing of them is such that they release before all non-root resets. I forgot to remove the "hack alert" comment.

However, clkmgr unit tests seem to always apply_reset "HARD". I guess I could apply_reset of random kind between rounds of many of the *mgr tests. I created https://github.com/lowRISC/opentitan/issues/16148 to track that enhancement, so this issue can be closed once the cascading assertions are removed.

**Comment by matutem** [comment]
An update: the rstmgr_cascading_sva_if interface has a number of assertions that are not specific to the cascading behavior. t seems better to remove only the cascading ones and rename the file for clarity.

**Comment by tjaychen** [comment]
that sounds good to me.

**Comment by matutem** [comment]
More recent developments: I uncommented the assertions that were commented out in https://github.com/lowRISC/opentitan/pull/13095, and got no rstmgr failures with a full regression. This means we have no cause for concern regarding these assertions, and it is safe to make this an M3 issue.

**Comment by matutem** [comment]
Closing this, since these assertions are passing.
