### ISSUE TITLE
[top, flash_ctrl] cpu <-> flash transactions cause spurious test failure during ndm reset test

### ISSUE THREAD

**Issue by jdonjdon** [lowRISC/opentitan#13266]
This subsequent issue to #13179 
- After #13179 fix with #13208, the ndm reset request test (#13261) still fails
  due to residue of outstanding transaction in flash_ctrl.

**Comment by tjaychen** [comment]
The issue turned out to be related to flash ctrl's reset domain. flash_ctrl is currently in the `lc` reset domain, this means an `ndm reset req` does not reset it.  This causes a problem because that means if the reset comes when there are tlul transactions inflight it's effectively left "hanging". 

So when the reset releases a unexpected response might just show up at the door step of ibex.  This PR moves flash to the sys domain so this problem no longer persists.

Overall, this issue can happen to any block that is on the `lc` domain, so we need to be careful and judicious about which blocks end up there, and that there is a good reason to be there.
