### ISSUE TITLE
Update the test ROM to handle reset reasons the same way as the mask ROM. Write the reset reason to the retention SRAM, then clear the RESET_INFO register.

### ISSUE THREAD

**Issue by drewmacrae** [lowRISC/opentitan#13265]
As @a-will  suggests in #13096, this should get our tests more consistent and compatible with back-door loading or bootstrapping. It may end up touching all the tests that reboot or check reset info, but we're committed to the cleanup so it seems worthwhile and should fix some of our tests that are having trouble with reboot on the cw310

**Comment by drewmacrae** [comment]
Looking at the test-plan I want to check none of the tests require checking of reset_info that would be invalidated by moving the data to a reset_regions register in retention sram. I think that
- The structure is the same and can hold the same data
- The registers are reset with the same logic
Therefore we shouldn't have an issue rewriting to retention sram.

I will update the chip_testplan to record the change

**Comment by drewmacrae** [comment]
Should the rstmgr dif be rewritten to find the reset_reason in sram to stay useful and do this under the hood? Or should we keep the dif as is and just ensure tests aren't using it when it's not useful?

**Comment by drewmacrae** [comment]
Are the DIFs meant to be portable between environments with both the test rom and the mask rom?

**Comment by drewmacrae** [comment]
I'm wary of leaving dif_rstmgr_reset_info_get if it's always going to point to cleared reset_info. If someone wants to check this does what we say they might want to use it, so I'm planning to leave it for now, but I'm not confident that's the best way to do it.

**Comment by timothytrippel** [comment]
Perhaps we want a testutil to replace `dif_rstmgr_reset_info_get` that chip-level tests can use to get the reset info from retention SRAM? 

Also, we may not want to remove the `dif_rstmgr_reset_info_get` DIF since it will probable be used in the test ROM to populate the ret SRAM with the reset info. However, we may want to add a pretty noticeable comment around the `dif_rstmgr_reset_info_get` DIF to inform chip-level test developers that it should not be used for most (maybe there will be some corner cases where this is not true?) chip-level tests, instead the testutil that reads from ret SRAM should be used.

thoughts?
