### ISSUE TITLE
[otbn, dv] OTBN status is not going to locked when prefetch address doesn't match with fetched address

### ISSUE THREAD

**Issue by prajwalaputtappa** [lowRISC/opentitan#13323]
@GregAC @vogelpi,

In this testcase, I'm trying to verify OTBN.PC.CTRL_FLOW.REDUN countermeasure. Prefetch address is corrupted and it doesn't match with fetched address. A fatal alert is raised. However, OTBN status is not moved to locked. The instruction counter is also getting incremented. Please find the screenshot below. 
![Screenshot from 2022-06-22 10-13-16](https://user-images.githubusercontent.com/91126414/175007678-f9bb480d-f935-4ad3-8ba3-002956215d88.png)

**Comment by ctopal** [comment]
I checked it now and it seems like the problem is probably coming from how we handle (or actually not handle) on the model side of things when there is a mismatch. RTL actually propagates the fatal error and initiates secure wipe (we don't go into locked state until the secure wipe is done). I tried to encapsulate the relevant signals in the screenshot below.
![Screenshot from 2022-06-23 15-34-09](https://user-images.githubusercontent.com/87007427/175324981-10ce7133-687b-4048-986f-537b5bc52204.png)

**Comment by prajwalaputtappa** [comment]
Hi @ctopal, 
I've run this testcase with seed 1. The model is going to locked status after 99 clocks (once secure wipe finishes). The RTL isn't going to locked status and hence there is a mismatch between the statuses. The instruction counter is incrementing. Please look at the screenshot I've provided above. I will also provide the zoomed in picture here. 
![Screenshot from 2022-06-23 17-04-49](https://user-images.githubusercontent.com/91126414/175344361-b37ed414-13b9-4a38-9a9b-cb18ab8f94c4.png)

**Comment by ctopal** [comment]
Hey Prajwala, I think I finally got to the bottom of the issue. It's related with us not passing the escalate signal back into the internal parts of the core (since it's getting caught in the `instruction_fetch` module, controller wouldn't necessarily know about the fatal error). Since the error is now coming at a relatively later time (because we are getting the fatal errors kind of indirectly!) the mismatch happens. Hopefully #13364 would fix it (it seems like it does on my setup)
