### ISSUE TITLE
[otbn,dv] Verify OTBN.SCRAMBLE.KEY.SIDELOAD

### ISSUE THREAD

**Issue by prajwalaputtappa** [lowRISC/opentitan#13327]

**Comment by ctopal** [comment]
- [ ] Update the testplan explaining in more detail about how to verify it using non-valid scrambling key

Note: I believe we might already driving the valid signal sideload agent randomly throughout our tests. Need a double check and maybe a talk with the design team to decide if it's enough.

**Comment by ctopal** [comment]
After some talks with @vogelpi and @GregAC, it definitely looks like this countermeasure is not actually verifiable since it's more of an architectural countermeasure rather than a functional one. Might need further talk about what to do for this kind of cases in OpenTitan as a whole. For now, no work needs to be done here.

**Comment by GregAC** [comment]
Closing this as no action is required for OTBN V2S.
