### ISSUE TITLE
[dvsim] enhance dvsim to handle jobs that are hung

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#13348]
When one of the jobs gets hung, the regression result won't be published. This happened frequently recently

These solutions may resolve or mitigate the issue
1. periodically print out what running tests are
2. kill the job if it runs over a time limit like 10h
3. incrementally publish result rather than publish after all jobs are done

cc: @tjaychen @cindychip

**Comment by tjaychen** [comment]
yeah i think if it's easier to just kill the regression after 10 hours and at least indicate what might have hung, that would be an improvement already.

@cindychip how do you find out what's hanging now..? If there's a set procedure I wonder if we should add documentation for it so that others can triage this too.

**Comment by weicaiyang** [comment]
> yeah i think if it's easier to just kill the regression after 10 hours and at least indicate what might have hung, that would be an improvement already.

I like this approach too. Hope it's not hard to implement

**Comment by sriyerg** [comment]
I believe this issue is addressed now? 
Incremental result publish is sort of unrelated and should be tracked as a separate issue.

**Comment by weicaiyang** [comment]
closing this as it's fixed now. Thanks @sriyerg
