### ISSUE TITLE
[flash_ctrl] controller issue same address twice when it compete with host direct access

### ISSUE THREAD

**Issue by jdonjdon** [lowRISC/opentitan#13408]
In the test,
controller and host compete to access flash device by issuing read request on the same bank (bank1)
For test convenience, all host request(direct) has byte address bit[18] set to distinguish from 
controller request.
At the bank 1 phy interface, dut issues bunch of read request mixed with host and controller read request.
But the frist two "controller" read request have the same address (address 0).
This can be reproduced by fetching (#13407)

**Comment by tjaychen** [comment]
@jdonjdon and i had a look at this.
This is happening because of the flash local buffering. 
Since flash words are wider than bus words, flash reads are buffered locally. If the next read matches the address of the local buffer, it reads from there directly instead of the flash.

In the host/controller interleave test however, the first buffered controller read data gets evicted by the burst of host read activity. So as a result when the controller reads the second word, it ends up reading the same location again to get the remaining data from the same flash word.

**Comment by jdonjdon** [comment]
TB is updated to model local buffer behavior. Will be added with direct rd test.
