### ISSUE TITLE
[otbn, sram_ctrl] Secure wipe of SRAM state upon RMA entry

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#13546]
This is something that came up while discussing the secure wipe mechanism for the OTBN registers in https://github.com/lowRISC/opentitan/issues/13499#issuecomment-1178253330.

In particular, the question is whether we should also hook up all SRAM wiping mechanisms (secure wipe inside OTBN, init feature in SRAM) to the RMA wipe request coming from the life cycle controller, so that no SRAM state survives a life cycle transition into RMA (where DFT and debug features are enabled again).

Note that we already have scrambling on these memories, which gives us some level of protection since the keys are changed upon reset. The scrambling is however not of cryptographic strength and may not offer enough protection if secrets are stored in those memories.

**Comment by tjaychen** [comment]
i think we can file this as future release. I don't think we need this for the current version.

Upon RMA entry, as @msfschaffner pointed out, we need to reboot.

When rebooting, I think we should also be clearing the sram via the init function, although I don't remember why mask rom is not doing it right now (@alphan / @moidx do you guys remember?)

The otbn memory usually gets secure wiped as well. Is the primary concern that after RMA, someone could come in via JTAG to read out the potentially secret contents?  The software angle should still be pretty difficult because secure boot is still required. Likewise coming in through JTAG needs to be guarded by RMA entry in general. So this feels like a very nice to do, but not critical at the moment if you don't have the time. 

For this feature, I assume the main change is another life cycle FSM state of sorts that requests for wipe? Similar to flash, is that right?

**Comment by tjaychen** [comment]
after discussing with @msfschaffner offline, it sounds like we've already decided to move forward with the wiping in `otbn`, so that's fine with me. 

I was also wrong earlier, `mask_rom` does wipe the [sram contents](https://github.com/lowRISC/opentitan/blob/master/sw/device/silicon_creator/mask_rom/mask_rom_start.S#L236) upon reboot always.

**Comment by msfschaffner** [comment]
Thanks @tjaychen. I'll rename this issue so that we can use it to track secure wipe upon RMA entry in `sram_ctrl` as a future enhancement.

**Comment by andreaskurth** [comment]
Triaged for `sram_ctrl`. Suggest to keep https://github.com/lowRISC/opentitan/labels/Type%3AFutureRelease as documented above and discussed in Security WG.

**Comment by gdessouky** [comment]
Triaged for `lc_ctrl`:  keep as `Type:FutureRelease` since no functionality or security implications arise. 
Currently SRAM gets wiped still but by the `init` mechanism at reboot which happens upon RMA entry (not before entering though). This is in contrast to OTBN SRAM secure wiping and state wiping that occur _before_ RMA entering (as a result of RMA wipe request coming from the life cycle controller.)

**Comment by gdessouky** [comment]
Following up here: can't we do SRAM initialization prior to enabling debug access in the sequence of boot ROM events?

**Comment by zi-v** [comment]
For most unlock states, it is doable, but then it is not required.
For RMA in particular, there's a pro and a con here. On one hand, it will reduce the security risk but on the other, it will depart the RMA flow from the PROD flow which may increase the risk of reproducing problems or even getting stuck in RMA without the ability to boot.
Having said that, the overall risk either way is not big. Overall, IMO we should either wipe it as part of the RMA flow as originally suggested by this issue or keep it as is (I wouldn't add an RMA specific routine here).

**Comment by gdessouky** [comment]
Thanks @zi-v! I also wouldn't add an RMA specific routine, but generally (irrespective of life cycle state) triggering SRAM initialization earlier in the boot process? Flows would be the same then, right?

**Comment by zi-v** [comment]
Yes. Triggering unconditional SRAM wipe is definitely good for security, but if we want to apply it on PROD* mode, we need to consider the boot time delay (SRAM size is 128kB so it is not negligible).

**Comment by gdessouky** [comment]
But SRAM is already re-scrambled and initialized in boot ROM [here](https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/silicon_creator/rom/rom_start.S;l=352) irrespective, right? So this also happens for PR0D* mode at every reboot IIUC. If this is true, then can we somehow run this earlier in the boot process, which happens to be before we enable debug access in case of RMA?

**Comment by zi-v** [comment]
Oh, I did not remember that, which also remind me that the lifecycle decision which affect the debug, is made by hardware, before ROM starts to run. At the time we discussed the option of further gate the debug enablement by ROM but I don't think it was implemented.

**Comment by johannheyszl** [comment]
Closing this issue because we have discussed the same topic in #17944. 
From there we have spun a dedicated issue dealing with the same improvement under #18114 .
