### ISSUE TITLE
[aes] Forcing main/cipher core FSM signals sometimes doesn't trigger fatal alerts

### ISSUE THREAD

**Issue by rasmus-madsen** [lowRISC/opentitan#13572]
@vogelpi 
if you look at PR #13571
and run /util/dvsim/dvsim.py hw/ip/aes/dv/aes_masking_sim_cfg.hjson -i aes_control_fi -r 1 -t xcelium  -s=1108401101

you will see tb.dut.u_aes_core.u_aes_control.gen_fsm[2].gen_fsm_n.u_aes_control_fsm_i.u_aes_control_fsm.cipher_in_ready_i
begin forced  high - and the two other interfaces continuing on as usual - not fatal is asserted.
this is one of the signals in the list you wanted me to check.
![image](https://user-images.githubusercontent.com/53917183/178275817-3675aad7-bccd-4f7b-8e3d-0ba27a7aff65.png)

**Comment by vogelpi** [comment]
I've renamed the issue to make it representative for #13646 as well. The behavior of these tests is very similar.

It's not a problem in the RTL but the test. The test forces a signal which doesn't have an effect in a reasonable amount of time
At the moment, about 1 out of 10 FI test runs fail because of this. Since we have many passing seeds for these FI tests and coverage looks pretty good, I am proposing to fix the test after V2S/M2.
