### ISSUE TITLE
[dif] Standardize the behavior of difs for locking register functions

### ISSUE THREAD

**Issue by engdoreis** [lowRISC/opentitan#13643]
Some difs return `kDifLocked` when asked to lock an already locked register such as (`dif_flash_ctrl`),  and others difs return `kDifOk`.

1. Should we standardize this behavior?
2. Which would be the adopted behavior?

I advocate to always return `kDifOk` no matter the current lock state 

@timothytrippel for visibility.

**Comment by timothytrippel** [comment]
Yes I agree with @engdoreis, according to the DIF [style guide](https://docs.opentitan.org/sw/device/lib/dif/) the `kDifLocked` return code is for `DIFs which may fail due to lockout, which is software-detectable...`. The locking DIFs themselves should be reentrant, always returning `kDifOk` if they succeed at doing their job, i.e. locking the IP. Since their job is so simple, the only other return value they should ever return is `kDifBadArg` in most cases, in case of a bad handle pointer.

I also agree this behavior should be standardized.

**Comment by a-will** [comment]
Just keep in mind that certain "lock registers" do _not_ behave the same way for flash_ctrl. `kDifUnavailable` is the correct return value for CSRs guarded by `CTRL_REGWEN`. `CTRL_REGWEN` changes state based on the flash controller's status; it is not actually a lock register in the same sense as others, and it unlocks simply with time.

**Comment by timothytrippel** [comment]
Ah good point, @a-will.
