### ISSUE TITLE
[aes] Forcing cipher core FSM signals does not result in fatal alert

### ISSUE THREAD

**Issue by rasmus-madsen** [lowRISC/opentitan#13646]
hi @vogelpi 
in the cipher_control_fsm forcing the key_dec_sel does not result in the expected fatal
here you can see one is set to two
while one of the two other is set to key_dec_expand
![image](https://user-images.githubusercontent.com/53917183/178997378-9efd1c49-5417-45e8-81b7-1a73bc197b9b.png)

to recreate use PR#13645
and run
./util/dvsim/dvsim.py hw/ip/aes/dv/aes_masking_sim_cfg.hjson -i aes_cipher_fi -r 1 -t xcelium -w=shm -v=m -s=806002346

**Comment by vogelpi** [comment]
Hi @rasmus-madsen ,
I just had a look at this. The specified seed no longer results in a failure. But what's happening is very similar to #13572.

For example, forcing the following signals doesn't result in a fatal alert:
- out_ready_i to 1, seed 2366617437
- sub_bytes_out_req_i to 1, seed 3323654017
- key_expand_out_req_i to 1, seed 901639764

**Comment by msfschaffner** [comment]
Has this been fixed by now or is this still occurring?

**Comment by vogelpi** [comment]
About 1 out of 10 runs fails because of this currently. It's not a problem in the RTL but the test. The test forces a signal which doesn't have an effect in a reasonable amount of time (see #13572). Since we have many passing seeds for these FI tests and coverage looks pretty good, I am proposing to fix the test after V2S/M2.

Since this is very similar to #13572, I am closing it and rename the other issue/make it more general. Let's continue any discussions over there.
