### ISSUE TITLE
[dv/xcelium] simulation run always dumps waves

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#13735]
I wonder if this happened to anyone else?
When I run any command with xcelium, for example: `./util/dvsim/dvsim.py hw/ip/entropy_src/dventropy_src_sim_cfg.hjson -i entropy_src_rn*`
The output always has `waves.shm` even though I did not specify the `-w` option.
I think we could fix this to improve runtime.

**Comment by rasmus-madsen** [comment]
@cindychip 
the waves are not actually dumped - so this is not a time consuming thing.
the issue comes from the default setting in waves.tcl
`setDefault dump_tb_top 1`
I am not sure why this is default set, @sriyerg can you elaborate here?
either way I think this is a none issue - and we don't have to do anything

**Comment by sriyerg** [comment]
I just ran locally and I noticed that `waves.shm` directory gets created regardless of whether wave dump is enabled or not. If you check the size of the directory, it's vastly different **(16K v/s 1.01G)** compared to when waves are actually dumped and when they are not:

```console
# Without wave dump enabled.
$ ./util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i chip_sw_uart_tx_rx --fixed-seed 1  -v h --local -t xcelium
# ...
00:07:50  [     run     ]: [Q: 0, D: 0, P: 1, F: 0, K: 0, T: 1] 100%                                                                                                       
$ du -sch .../waves.shm
16K	waves.shm
16K	total

# With shm wave dump enabled. 
$ ./util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i chip_sw_uart_tx_rx --fixed-seed 1  -v h --local -t xcelium --waves shm
# ...
00:25:26  [     run     ]: [Q: 0, D: 0, P: 1, F: 0, K: 0, T: 1] 100%                                                                                                       
$ du -sch .../waves.shm
1014M	waves.shm/
1014M	total
```

Notice the difference in the runtimes - with shm waves enabled, it's more than triple the runtime **(7.5min v/s 25min)** of simulation without waves. If you are not seeing the same outcome, we should definitely explore further (please provide an example). 

The `dump_tb_top` in `waves.tcl` represents what hierarchy to dump by default, which is "dump the entire tb top". That mechanism allows users to dump specific hierarchies to speed up sim runtime, rather than dump everything. For example, users can do:
```tcl
  # in sim.tcl, before waves.tcl is imported
  set dump_tb_top 0
  import waves.tcl
  
  wavedumpScope tb.dut.foo.bar
  wavedumpScope tb.dut.baz
  run 
  quit
```

It does not represent whether to dump waves or not - that is wired through the dvsim `--waves <format>` switch. `waves.tcl` uses the value of the variable `$waves` set from the dvsim switch to know whether to enable wave dumping or not.

**Comment by sriyerg** [comment]
I will make a PR to make some minor enhancement to `waves.tcl` to make this usage clear.

**Comment by rasmus-madsen** [comment]
@sriyerg I think we are saying the exact same, that it only actually dump a wave when you ask it to.
my comment was just - since it is not actually dumping waves, this fix was not a MUST.

**Comment by sriyerg** [comment]
> @sriyerg I think we are saying the exact same, that it only actually dump a wave when you ask it to. my comment was just - since it is not actually dumping waves, this fix was not a MUST.

Agreed. @cindychip, please close the issue if you agree with our assessment.

**Comment by cindychip** [comment]
Great! Thanks Sri!
