### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Avani8** [lowRISC/opentitan#1392]
do you have specific reason for dividing the flash image into 1KB chunk (in bootstrap) and measuring hash rather measuring hash of single file?

**Comment by tjaychen** [comment]
ah i cannot remember.  There's probably no reason this could not be increased, we just need to make the appropriate changes in both the ROM and spiflash tool.

I've cc'd the people who will know this best.

@gkelly 
@mcy

**Comment by GregAC** [comment]
The spiflash tool can resend corrupt frames, so by breaking it into chunks you just have to resend a chunk rather than the whole image if it's corrupt. Plus if you do have a slightly dodgy SPI line that corrupts the occasional bit you may never manage to send a full uncorrupted image across it but can manage 1kb chunks (with some of the failing and getting resent)

You see the code that handles this in the spiflash tool here: https://github.com/lowRISC/opentitan/blob/3d93afbe25200089f60e6e6c0ff2a315a882c97e/sw/host/spiflash/updater.cc#L58-L107

(Now I'm looking at it I'm wondering if the decrement on line 99 should actually be there but in principle it resends corrupt fra,es)

**Comment by Avani8** [comment]
Thanks, @tjaychen and @GregAC  for the explanation... this helps a lot.  actually decrement on line 99 should be there as in bootstrap.c when hashes mismatches it retries the corrupt frame check.

**Comment by tjaychen** [comment]
so one thing i should mention about the spiflash timing... because we are
using SPI directly instead of having external signals to do flow control,
when the host sends a frame, it is simultaneously receiving an ack.
So i think the way it works (as you suggest) is that the host sends a
frame, and proceeds to send the next frame while waiting for the previous
ack. If that ack fails, then it drops back to sending the previous frame
again.

Personally I prefer a slightly more controlled protocol similar to TCG
SPI_TPM or SPI -> flash device interface but that's something we can
discuss later if / when those bits of HW are available.
