### ISSUE TITLE
Separate the buffer and the syncronizer functions in prim_mubi*_sync and prim_lc_sync cells

### ISSUE THREAD

**Issue by Jacob-Levy** [lowRISC/opentitan#13985]
In order to eliminate lint issue and reduce complexity, it is suggested to remove the parameter AsyncON and add na new cells
prim_mubi*_buf and prim_lc_buf.

This will enable to bypass the enum error issue in Spyglass and the issue with Xecilum.

The current implementation when AsyncOn=0  only a buffer is generated and when the parameter is set to '1' a syncronizer 
will be added.  These might create an issue with scanmode if 'no_scan' is not part of the instant name.

Adding the prim_mubi*_buf and prim_lc_buf can be done without the need to change the code.

In order to eliminate the parameter and fix the enum error, the code of the prim_mubi*_sync and prim_lc_sync needs to change 
and also the code that uses thou cells. For buffer function it is simple use of the new cells. for syncronizers removing the 
parameter is advisable.

@arnonsha

**Comment by msfschaffner** [comment]
Thanks @Jacob-Levy. We've discussed this in the weekly Nuvoton meeting today.

For the Xcelium warning: 
We ran into these as well and think it would be best to just promote the warning to an error.
This would have the least impact on the code base, since only the violating instances would have to be fixed (and we fixed already most of them). The fix is straightforward: either make sure the port type matches, or use curly braces around the output assignment `.out_port_o({out_sig})` (CC @sriyerg). 

For the concerns related to scan mode: 
We would like to avoid changes that touch many modules in the design, since several modules (like lc_ctrl, otp_ctrl etc) that would be affected are already at D3. Since there is currently no issue with scan, the recommendation is to review the parameterization of the prim modules related to scan closely. We can still tag this as a future cleanup so that we can come back to it after ES.
