### ISSUE TITLE
[spi_device] Widen TPM WrFIFO to 32-bit

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#13996]
Related Issue #13816 

Widen WrFIFO width requires logic change in SPI_TPM. The idea is tabled for future release.

**Comment by andreaskurth** [comment]
Triaged for `spi_device`. IIUC, widening the TPM Write FIFO would allow SW running on OT to empty it in fewer clock cycles. Since that FIFO can already store a full TPM transaction (64 B), however, I don't think this is necessary for this release and it's thus correctly labeled https://github.com/lowRISC/opentitan/labels/Type%3AFutureRelease.

**Comment by msfschaffner** [comment]
CC @a-will
