### ISSUE TITLE
[lc_ctrl] keymgr div key inconsistency

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#14047]
@msfschaffner 

KEYMGR_EN is only enabled in one of these states: DEV, RMA, PROD, PROD_END.

Why the key is still available in TEST_UNLOCKED*?

Life Cycle State Group | Assigned Diversification Constant
-- | --
TEST_UNLOCKED*, DEV, RMA | LcKeymgrDivTestDevRma
PROD, PROD_END | LcKeymgrDivProduction

cc: @cindychip

**Comment by msfschaffner** [comment]
I believe the main idea here was to reduce the amount of diversification constants needed (no matter whether the key manager is enabled or not). Hence, `TEST_UNLOCKED*` gets the same diversification constant as the `DEV` and `RMA` states (instead of creating yet another diversification constant).

The important part is that the `PROD*` states have a different constant than  `TEST_UNLOCKED*`, `DEV` and `RMA`.

CC @tjaychen

**Comment by weicaiyang** [comment]
As discussed with @msfschaffner, using `LcKeymgrDivInvalid` for TEST_UNLOCKED* may be more consistent as keymgr is disabled at that state.
But as @msfschaffner  mentioned it's not the same one used in PROD state and LC_CTRL is already in D3, I guess it's fine to leave it as is.

**Comment by cdgori** [comment]
Agree with @msfschaffner / @weicaiyang - using `LcKeymgrDivInvalid` is better here, but as long as it is not the one used in PROD state, this could be deferred in the interest of keeping D3 freeze/stable on LC_CTRL.

**Comment by tjaychen** [comment]
sounds good to me.

**Comment by gdessouky** [comment]
Triaged for `IP:lc_ctrl` - given that this is only a small consistency fix (little engineering overhead), and KEY_MANAGER_EN is not active for TEST_UNLOCKED* anyway, and the RTL for LC_CTRL will likely not stay frozen anymore, then I'd say we might as well fix it. If by end of triaging, it turns out we are not touching RTL, then we can drop this one since it has no functionality/security impact.

**Comment by gdessouky** [comment]
> estimate 2

**Comment by msfschaffner** [comment]
@moidx @johannheyszl @vogelpi any objections if we use different diversification constants for all life cycle states? E.g.

Life Cycle State Group | Assigned Diversification Constant
-- | --
TEST_UNLOCKED* | LcKeymgrDivTest
RMA | LcKeymgrDivRma
DEV | LcKeymgrDivDev
PROD, PROD_END | LcKeymgrDivProduction

**Comment by moidx** [comment]
No issues on my end. Leaving the key disabled in `TEST_UNLOCKED` state is still beneficial if we can leave that part as is. We don't expect key advance operations to work given that the `SECRET2` partition is only expected to be provisioned in mission mode.

CC @timothytrippel

**Comment by msfschaffner** [comment]
Yeah the `keymgr` will still be disabled in that state, but we would be making the diversification value different nonetheless...

**Comment by vogelpi** [comment]
This sounds good to me as well.
