### ISSUE TITLE
[kmac] LC transition kmac reset question

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#14072]
Hi Tim,

Michael and I would like to confirm the following behavior with you:
1). LC state transition request starts
2). LC requests KMAC scrambled value
3). KMAC gets a reset from sys domain, but this reset does not affect LC
4). -> Would like to confirm here: LC will hang at waiting for KMAC value until a POR or LC domain reset

The above sequence, chip level test will make sure LC did not go to next state, and the transition cnt could be incremented.
Do you have any concern about the expected behavior above? Do you think we need a kmac wait timeout?

FYI: @msfschaffner 

Thanks,
Cindy

**Comment by msfschaffner** [comment]
I think it should not matter since we are not allowing the LC_CTRL to proceed. The only "bad" thing that happens is that the transition counter gets incremented - but then again this is clearly not correct use of the life cycle transition mechanism (SW should ensure everything remains stable during that time).

We just want to confirm whether you think so, too, or whether we need to plan for a feature enhancement further down the road (post ES).

**Comment by cindychip** [comment]
Hey Michael and Tim,

I just realized that LC_CTRL actually connects to KMAC rst/clk ports. So even though they are in the different clock domain, LC will resend the KMAC data request if kmac is being reset. So I think the only possible way for LC to hang is just KMAC somehow does not response to LC request.

**Comment by tjaychen** [comment]
Yeah i think this is fine. I'm guessing that if kmac resets in the middle, the kmac results are going to either be wrong (if we reset when it's still processing), or a hang (if the reset happens when the results are sent back).

In the former case I guess the transition would just fail.  Even if the two sides were the same reset domain, if I remember the counter would have been incremented anyways, so the behavior isn't really different. (@msfschaffner can you confirm?)

The latter case, if it happened in a real system, a watchdog will eventually take over and reset the system. 

Having said that though, the one sided reset of `prim_sync_reqack` is still kind of weird and may lead to assertion errors. That one specifically is probably still worth addressing (ie, change the connection for rst_ni on lc_ctrl side), even if the macro behavior is acceptable.

**Comment by cindychip** [comment]
Thanks Tim, so I think we are safe to close this issue but leave #14086 open.

**Comment by msfschaffner** [comment]
RE
> In the former case I guess the transition would just fail. Even if the two sides were the same reset domain, if I remember the counter would have been incremented anyways, so the behavior isn't really different. (@msfschaffner can you confirm?)

That is correct - we first increment the counter before sending anything to KMAC. Hence the outcome is essentially the same.
