### ISSUE TITLE
Render DV regression reports from Markdown to HTML inline in hardware block docs

### ISSUE THREAD

**Issue by gkelly** [lowRISC/opentitan#1411]
As title, probably need to use a JS markdown renderer. 

@sriyerg @weicaiyang

**Comment by sjgitty** [comment]
Garret can you elaborate or point to a preferred implementation because
I'm looking to do something similar with my specboard port.

**Comment by gkelly** [comment]
> Garret can you elaborate or point to a preferred implementation because I'm looking to do something similar with my specboard port.

Absolutely.  My current thinking is to write a shortcode that takes URL and generates a javascript snippet to fetch the URL contents, run it through a markdown to HTML renderer, and then inject the resultant HTML at that position in the document.  It will inject a few hundred ms of latency in the full page load, but it has the benefit of still getting HTML out of markdown without having it in the tree during docgen.

**Comment by msfschaffner** [comment]
This seems to be implemented now, so I am closing this issue.
Please reopen if this is not the case.

**Comment by sriyerg** [comment]
I think this refers to adding a shortcode in the `docs.opentitan.org` area itself such that all regression results are directly expanded in there, rather than a separate `reports.opentitan.org` area.

**Comment by msfschaffner** [comment]
Apologies if I closed this prematurely - I understood that the mechanism for rendering inline snippets has been implemented, but we're not using it currently since we have settled on a different solution (publishing directly to `reports.opentitan.org`).

Do we still have plans to move the regression results into the docs? If so, let's reopen this issue.
