### ISSUE TITLE
[docs] Provide breadcrumb navigation

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#1420]
Our documentation is structured as a tree, but this tree structure is not visible when browsing through the docs.

Can we have the path the current document at the top of the docs, e.g. 
Docs -> User Guide -> Install Build Requirements on top of https://docs.opentitan.org/doc/ug/install_instructions

**Comment by towoe** [comment]
relates to #866

**Comment by sjgitty** [comment]
I like this one, and it is a bit easier to create an algorithm that makes sense.
In my vision this could look like this, for a couple of examples. I'm imagining
it *above* the auto-generated TOC on the left sidebar. The second example
is a little harder to guide the algorithm since it skips two directories with no
entry in the tree, since they have no root _index.md in those directories.

[&#x2b1d; Introduction to OpenTitan](_index.md)
&nbsp;&nbsp;[&#x2ba1; lowRISC Documentation Overview](doc/_index.md)
&nbsp;&nbsp;&nbsp;&nbsp;[&#x2ba1; User Guides](doc/ug/_index.md)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[&#x2ba1;  Design Verification Methodology within OpenTitan](doc/ug/dv_methodology.md)

[&#x2b1d; Introduction to OpenTitan](_index.md)
&nbsp;&nbsp;[&#x2ba1; Hardware Specifications](hw/_index.md)
&nbsp;&nbsp;&nbsp;&nbsp;[&#x2ba1; UART HWIP Technical Specification](hw/ip/uart/doc/_index.md)

**Comment by towoe** [comment]
Closing this as the commit message was not correctly formatted for automatic closing.
