### ISSUE TITLE
[docs] Provide previous/next links

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#1421]
Within one hierarchy level of documentation (e.g. in the user guide), it would be nice to jump between documents on the same hierarchy level using previous/next buttons.

**Comment by sjgitty** [comment]
My vision of what this might look like is *below* the auto-generated TOC
on the left panel we could have something like below. Is this what you
were thinking? For many docs there are no "siblings" so they don't always
make sense. Also, alphabetic previous/next are not typically what you
really want. WDYT?


[&#x2BC7; Getting Started with an OpenTitan Hardware Design](doc/ug/getting_started_design.md)
[&#x2BC8; Getting started on FPGAs](doc/ug/getting_started_fpga.md)

**Comment by msfschaffner** [comment]
CC @towoe 

Is this something we would still like to implement, or can we close this issue?

**Comment by rswarbrick** [comment]
Our current documentation structure isn't really arranged logically in chapters. It probably should be! But I'm not convinced it's worth tracking this feature until it is. I propose closing.

Also, it's been almost 6 months since the last ping, so I really don't think there's anyone who cares too much!
