### ISSUE TITLE
[otbn,dv] Loop warps does not work for OTBN

### ISSUE THREAD

**Issue by ctopal** [lowRISC/opentitan#14223]
Trying to do a loop warp in our current DV environment generates an count error from `prim_counter`. However, we assume it shouldn't at the ISS side. That results with mismatches. This can be reproduced by running:

`util/dvsim/dvsim.py hw/ip/otbn/dv/uvm/otbn_sim_cfg.hjson -i otbn_sw_errs_fatal_chk --reseed=1 --tool=xcelium -w --fixed-seed=2654402148`

@msfschaffner I think this behaviour might have started with commit https://github.com/lowRISC/opentitan/commit/0794cfc4a8c1a5cbcd8d94ae3d8664215185afbf so you might have an idea about this problem, please let me know if I can help with more details.

**Comment by GregAC** [comment]
I think this is due to the renaming of the internal counter flops that hold the counts. The loop warping code probe these directly. I can take a look though it should be a pretty easy fix if you want to check it out @ctopal? The RTL side of the loop warping is handled in C++ via DPI, there's some functions to directly set counter values that will need updating.

**Comment by ctopal** [comment]
Hi Greg, I assigned this back to myself because I think I can handle it with your explanation about the RTL side. Thanks!

**Comment by msfschaffner** [comment]
Yeah I attempted to update most of the DV environment, but there may be some things that I missed. 
Let me know if you have further questions regarding the updated `prim_count` internals.
The internal structure should be a bit more homogeneous now.
