### ISSUE TITLE
[alert_handler] Question on escalator signal duration and escalator phases length

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#1427]
Hi Michael, 

I am working on checking the escalation signal length and would like the confirm the question:
Should escalator phases lengths be equal to esc_tx_o lengths?

If so I think here is an mismatch as the waveform shows:
When register `classa_phase0_cyc`, `classa_phase1_cyc`, `classa_phase2_cyc`,  and `classa_phase3_cyc` are all left as default value `0`,  `CLASSA_STATE` `phase0, phase1, phase2, phase3` states are all lasted one clk cycle length. But `esc_tx_o` signals are two clk cycles length (in order to distinguish between pings and escs).

I personally think this scenario we can 
1). change phase duration from 1 clk cycle to 2 clk cycles, and state that "if phase_cyc" is set to <2, it will be 2 clk cycles.
2). if not changing RTL, can we add some comments to explain this scenario?

![image](https://user-images.githubusercontent.com/11466553/73237405-581e7d80-414a-11ea-991c-94f240af3a75.png)

![image](https://user-images.githubusercontent.com/11466553/73237689-44274b80-414b-11ea-9484-72a8879f3a17.png)

**Comment by msfschaffner** [comment]
Hey @cindychip , good point.

So towards the end of section `Programmable Escalation Protocol` the spec states that 
```
It should be noted that each of the escalation phases have a duration of at least 1 clock cycle, even if the cycle count of a particular phase has been set to 0.
```
This basically covers exactly the case you have run into. 
However, you are right that the wave diagram is not entirely correct since it shows the differentially encoded escalation signals, which are always N+1 cycles in length.

That means that for N being the escalation cycle count configuration, you should observe the following pulse lengths on the differential pairs:
```
N=0: 2 cycle pulse
N=1: 2 cycle pulse
N=2: 3 cycle pulse
N=3: 4 cycle pulse
...
```

I would prefer not changing the state machine, since it is already one of the more complex ones, and adding more logic will just make it more complex to test in FPV also. 

I hence suggest to go for your 2nd solution and change the wave diagram above, and highlight this aspect of the implementation again when explaining the wave diagram. I can do that when I am back in the office next Monday.

**Comment by cindychip** [comment]
That sounds good to me. Thanks Michael.

Cindy
