### ISSUE TITLE
Question about secure boot public key initialization

### ISSUE THREAD

**Issue by ChiaweiW** [lowRISC/opentitan#14315]
hi all,

I have a question about the initial Creator public keys used for secure boot.
The codebase shows that the keys are hardcoded in the ROM code. The OTP only controls their validity.

I am wondering why OpenTitan does not use OTP to keep public keys in the hash digest way?
Silicon creators would have more flexibility to decide the secure boot keys with OTP provisoning at the manufacturing phase.
If the public keys are hardcoded in the ROM code, the keys must be determined at design phase.
Could you help me to clarify on this? Any guidance is appreciated.

Thanks,
Chiawei

**Comment by tjaychen** [comment]
others can chime in more, but from my perspective.. allowing otp digest of keys means at some point in the flow, the keys used for verification can be arbitrarily controlled. By baking it into ROM, we are enforcing that each revision / version of opentitan is strongly bound to the creator.  The early stages of code, as you see in our documentation, were also not meant to be controlled by owners later, since it has ownership transfer responsibilities. 

On another related point, the digest comparison has also been vulnerable to attacks in other chipsets.  I believe there was one such attack on tegra some years ago.

**Comment by moidx** [comment]
What @tjaychen summarizes our thinking behind storing the keys in the ROM. We want a strong link to the creator to ensure ROM_EXT signatures are verifiable against operational and infrastructure production requirements.

We also want to avoid having to rely on the security of the manufacturing process to provisioning the verification keys, and don't plan to use identity key injection in our reference provisioning flows. Ideally, we want to get to a place where the device under test can authenticate itself directly with the provisioning infrastructure to avoid having to store secrets in ATE. In order to get there, we need the ability to establish trust in the device life cycle state and code running on the DUT, thus leaving OTP verification keys outside the scope of this implementation.

**Comment by ChiaweiW** [comment]
Thanks for your kind explanation!

The reason I have this question is due to the consideration on commercial chain.
If one chip vendor joins different creator groups, the chip may not be commonly used unless all of the secure boot public keys are forseen and embedded in ROM. (not a good idea)

**Comment by tjaychen** [comment]
if you follow along our security documentation, i think our recommendation is to diversify a lot of the related use cases to the next stage of code.  This means the first stage of software after ROM (ROM_EXT in our terminology) is really tightly coupled with the ROM and bears the responsibility of adapting to later use cases.

By doing this, it allows us to keep the branches inside ROM small and the logic very linear, and defer a lot of the more complex decisions to later. This also reduces the need to have everything figured out inside the ROM early on. Of course, this may not be something that is applicable to every scenario out there.

Lastly, OpenTitan is an open source project after all, so if you have different ideas, we really encourage you to make a proposal and share it with the community.

**Comment by ChiaweiW** [comment]
Agree to keep ROM small and simple.
Balancing security and flexibility is always the dilemma.

Great thanks for your kind response, giving me more clear picture about the security design.
Issue closed.
