### ISSUE TITLE
[test-triage] chip_sw_rv_core_ibex_address_translation

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#14327]
### Hierarchy of regression failure

Chip Level

### Failure Description

Error was reported as 

```
ERROR: no such package 'sw/device/tests/rv_core_ibex_address_translation_test': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
   - /workspace/mnt/repo_top/sw/device/tests/rv_core_ibex_address_translation_test
```

Could be related to [[test-triage] chip_sw_rv_core_ibex_rnd](https://github.com/lowRISC/opentitan/issues/14206) but seems different.

Then changed to 
```
Offending '((~pending_dside_accesses_d[(MaxOutstandingDSideAccesses - *)].valid) | data_rvalid_i)'
```
```
[ASSERT FAILED] MaxOutstandingDSideAccessesCorrect
```
from  16 August - see https://reports.opentitan.org/hw/top_earlgrey/dv/2022.08.16_16.23.56/results.html 

### Steps to Reproduce

Missing file observable in nightlies between 12 August and 16 August.
Then new error reported 16 August and beyond.
See https://reports.opentitan.org/hw/top_earlgrey/dv/2022.08.16_16.23.56/results.html

### Tests with similar or related failures

NA

**Comment by tjaychen** [comment]
@HU90m is this currently being triaged? If not, you can unassign it for the next on-call.

**Comment by abdullahvarici** [comment]
I have run the simulation and reviewed the code. Thanks to @andreaskurth, we have found out that the related assertion line has an error and it was fixed in [here](https://github.com/lowRISC/ibex/commit/8282a0d2448463762dba22305896c05377a44f25) and included opentitan yesterday at [this commit](https://github.com/lowRISC/opentitan/commit/a836c21da9116be160a50553ac41b645c8b81a33). Now the test is working successfully.
