### ISSUE TITLE
[chip-test, otbn] Speed up otbn_ecdsa_op_irq_test

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/opentitan#14385]
As mentioned in https://github.com/lowRISC/opentitan/pull/14279#discussion_r946000686 the otbn_ecdsa_op_irq_test chip-level test now takes over 5 hours to complete in VCS. This is massive and we should try to reduce the run time spent for this test. In general, most of these OTBN programs take a very long time to run. This is why we typically don't simulate them but rather just execute them on the FPGA emulator for CI purposes. This particular test performs signing and afterwards verification of the signature using ECDSA P-256. In between and afterwards, the DMEM is zeroed by Ibex which takes a long time itself and can be removed. I'll file a PR to do this. However, we should further check whether a) we can further speed up the execution of this test or b) switch to a different and faster OTBN program.

Back in the day, this OTBN program was selected for the chip-level test mainly because it was available. Since then, a few other routines have been developed. In case there are other, faster routines available we should try to switch to that. @GregAC @jadephilipoom do you maybe have a good alternative in mind?

**Comment by jadephilipoom** [comment]
Based on the chip testplan item that this test covers, the only requirement is to run "an ECDSA operation" and then use the interrupt to check when it completes:
https://github.com/lowRISC/opentitan/blob/fdf456cb19475b19d5a1b6e84a9dd21359408f58/hw/top_earlgrey/data/chip_testplan.hjson#L2106-L2117

I'm unsure if there's a need for this to be specifically an _ECDSA_ operation at all, if all we're testing is the interrupt; if it can be any OTBN program then I can certainly recommend faster ones. Depending on requirements, here are three suggestions:

**Option 1: A different ECDSA operation.** Rather than a full sign/verify loop, we could simply verify a hardcoded signature. That should more than halve the time that this test takes (I see 677,554 cycles for sign and 498,050 for verify from a quick OTBN simulator check, so about 42% of current runtime).

**Option 2: A full cryptographic operation, but not ECDSA.** RSA verify would be only 160,723 cycles, so it would take only about 14% of the current runtime for ECDSA sign/verify.

**Option 3: A very small subroutine that is not a full cryptographic operation.** Tests for Ed25519 field arithmetic currently take only 10,031 cycles, and that tests several routines. The shortest individual subroutine would take on the order of a few dozen cycles. This would make the OTBN portion of the test runtime pretty much negligible.

**Comment by vogelpi** [comment]
Thanks @jadephilipoom for your input! I've now filed #14428 which replaces the clearing to 0 with a secure wipe of DMEM. This should shave off around 444000 clock cycles from the test already. Now most of the time is actually spent on initializing/loading IMEM and DMEM (2x ~360000 cycles). Maybe there is some low hanging fruit for optimizing this further. Otherwise, switching from sign/verify to verify only (your Option 1) seems most straight forward to me.

**Comment by vogelpi** [comment]
Actually, I just noted that there is another clearing of DMEM to all 0 inside `otbn_load_app()`. This can probably be removed, too.

**Comment by johngt** [comment]
@vrozic - do you mind taking a look at where @vogelpi got to with this and pick up the thread?

**Comment by vogelpi** [comment]
Sorry I forgot to update this issue. Several PRs have been done related to this issue (see references in this thread) which brought down the simulation time substantially. The latest nightly tests ran for 54min (w/o jitter) and 49 min (w/ jitter) compared to 5 hours before. I think this should be sufficient. I am thus closing the issue.
