### ISSUE TITLE
[alert_handler] classa_clr and classa_ctrl regs

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#1447]
Hi Michael,

I think the clear class registers might need some clarifications. 
Take classa as an example. `classa_clr` register is used to "clears the accumulator and aborts escalation (if it has been triggered)".
In `classa_ctrl` register, I set field `en` to 1, but fields `en_e0`, `en_e1`, `en_e2`, `en_e3` all to 0. Escalator threshold is 0. I assume there should not be any accumulator and escalations, thus I did not write `classa_clr` reg in the end.
But from the RTL, seems like once filed `en` is set to 1, and one of the two conditions to trigger escalator meets, then the `alert_handler_esc_timer` will go to `Phase0`, and stays there until I clear the escalator. If not cleared it, once I re-write `classa_ctrl` regs and enable fields `en_e0`, `en_e1`, `en_e2`, `en_e3`, it will trigger escalator again.

Could you help either add one more gating for RTL state machine, or clarify the spec? Thanks so much and please let me know what you think about it.

**Comment by msfschaffner** [comment]
Hey @cindychip , yeah that behavior probably needs to be explained better, but it is legal. Let me explain why.

The `en_e0`,  `en_e1`,  `en_e2` and  `en_e3` control bits are basically just "gating" control bits, meaning that they only affect whether the escalation signals will be sent out or not. They do not have any influence on the escalation triggers.

If class A is enabled via `classa_ctrl.en=1`, it is perfectly legal for escalation to trigger, and escalation can not be disabled via any other means than `classa_clr`. Even when you disable and enable the class again, escalation will in any case proceed. 

This has been designed that way on purpose in order to limit the ways how escalation can be cleared. I.e., if you also set the automatic locking mechanism `classa_ctrl.lock=1`, there will be no way whatsoever to disable escalation - even if you write to `classa_clr`.

Does that make sense? I can amend the spec to explain that better, if needed.

**Comment by cindychip** [comment]
Hi Michael,

Thank you for the clarification. I agree that it makes sense when we treat
en_0/1/2/3 as hating signals. Then even though I disable all of them, the
accumulation will still run.

I think it would be nice to mention this case in the spec. Do you think it
is necessary?

**Comment by msfschaffner** [comment]
Hey Cindy,

I will definitely amend the spec to explain this better, and I am also
thinking about whether we should do something different in the case where
all four gating bits are disabled. I.e., we could require that at least one
of the enable bits is set to 1, and otherwise disable the class (i.e. en &
(en_e0 | en_e1 | en_e2 | en_e3).

**Comment by cindychip** [comment]
Hi Michael,

Yes, I personally think it is reasonable to add the requirement that at least enable one of the `en_eX` when the class is enabled.
