### ISSUE TITLE
[dv/kmac] Make sure kmac does not hang when sideload key valid bit is dropped

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#14596]
Implement a sequence where sideload key valid bit is dropped or toggled during kmac operation.
Make sure the kmac operation won't hang.

**Comment by tjaychen** [comment]
huh this is interesting... i'm not sure we actually thought through this case between keymgr / kmac.
If this were to happen, (the valid line goes low for no apparent reason), it actually might be okay for `kmac` to completely misbehave, since it's basically an attack scenario.

Maybe we should actually add an assertion on `keymgr` side to make sure this doesn't happen outside of an escalation. 
Eventually an alert would probably be even better. 

@moidx 
@jadephilipoom any thoughts?

**Comment by cindychip** [comment]
I think it is expected for kmac to output unexpected data, I just want to make sure kmac won't wait forever for the valid sideload key :)

**Comment by tjaychen** [comment]
o okay sounds good. That's good too. Should we actually check that kmac's output will be incorrect? If that is easy to do?

**Comment by cindychip** [comment]
> o okay sounds good. That's good too. Should we actually check that kmac's output will be incorrect? If that is easy to do?

Sorry I realized I never replied here. In this case, we expect to see an error and expect the keymgr output to be all 0. 
This should be checked in the interface already :)

**Comment by cindychip** [comment]
Based on the conclusion for #16855, we can decide the DV implementation.

**Comment by johngt** [comment]
@cindychip - last this was tagged at was P1. Could you please update the priority label if incorrect?

**Comment by moidx** [comment]
Moving to M2.5.Backlog, for consideration for M3. Priority to be reassessed then.

**Comment by johannheyszl** [comment]
@ballifatih pls to have a look: could this likely to be an issue in your view? I think it is probably not one.

**Comment by johannheyszl** [comment]
- Was originally raised as a DV concern. Correct use is subject to the SW implementation.
- @ballifatih and I discussed and do not see any relevant security concern. Hence removing Hotlist:Security.
- @msfschaffner to judge DV need but seems as a close not planned candidate to me

**Comment by msfschaffner** [comment]
@vogelpi what do you think? close as not planned ok from your end as well?
