### ISSUE TITLE
[AES/CSR] csr_rw test fails when checking ral.ctrl

### ISSUE THREAD

**Issue by rasmus-madsen** [lowRISC/opentitan#1470]
TEST_NAME= aes_csr_rw
SEED=1660844691
(only reproduceable in my fork)

Wave and log
https://drive.google.com/drive/folders/1aINrAN_fyjvdc3sk24GZxqzQVFUN2QAX?usp=sharing

hi Pirmin 
when the CSR is writing 0x32 to the CTRL reg (
 ```
mode: 0,
 key_len= 001, 
manual_start_trigger = 1
force_data_overwrite = 1
```

it would expect to get the same back but is getting 0x02
```
mode: 0,
 key_len= 001, 
manual_start_trigger = 0
force_data_overwrite = 0
```

could you take a look and tell me if that is expected.
I was assuming these registers to be readable.

I am up to date with commits including
7b5bedfe89c93451db141fd1707543b2e49f9df1

**Comment by vogelpi** [comment]
Hi @rasmus-madsen ,
thanks for creating the issue. Unfortunately, the waves are empty. When I run the same test with the same seed from your development branch. I just see two writes to the CTRL register:
1. Writing 0x0000_00002:
```
mode = 0
key_len = 001
manual_start_trigger = 0
force_data_overwrite = 0 
```
2. Writing 0xE0DB_9F86:
```
mode = 0
key_len = 011 (correctly resolved to 001)
manual_start_trigger = 0
force_data_overwrite = 0 
```
The CONTROL register is never read. The test still fails but I don't know why.

I uploaded the waves,log + a screenshot.

**Comment by rasmus-madsen** [comment]
HI Pirmin
Yes that is expected.  you need some fixes for you to reproduce..
I have uploaded a new wave
please note that I have added additional fixes so the log is a little different this time. 
error is similar

**Comment by vogelpi** [comment]
Thanks for posting new waves. Now, indeed those fields are written with 1.

However, it is expected behavior that the register does not change the value. As documented [here](https://docs.opentitan.org/hw/ip/aes/doc/#register-table), writes to the CONTROL and KEY registers are ignored while the AES unit is busy. In this particular case, the test causes the AES unit to perform a clear operation before writing the CONTROL register.

I am closing this issue.
