### ISSUE TITLE
[sw] Bazel: Move default `--output_base` to within OpenTitan Repo

### ISSUE THREAD

**Issue by martin-lueker** [lowRISC/opentitan#14767]
Bazel by default is putting in `$HOME/.cache`.  For some users the `$HOME` directory has fairly restrictive quotas.  (For instance our job-queuing system rejects all jobs launched in the `$HOME` filesystem).  The `--output_base` option to bazel can be used to fix this, and select something like `$OT_ROOT/bazel-build`, which I see is already in the `.gitignore` file.   

We can in principle request users to put this in their individual `.bazelrc` files, but because our user environments aim to maintain some isolation between project-specific environment configurations (and some of us are frequently switching configs), this is somewhat clumsy. 

Could we perhaps make `--output_base` point to somewhere inside $OT_ROOT as part of the the project `.bazelrc` file?

**Comment by dmcardle** [comment]
IIUC, the suggestion is to move Bazel output directories to a subdirectory of the checkout path. Off the top of my head, I have a couple questions:

* Do any CI runners currently benefit from persistent Bazel build directories? If they delete and re-clone the repo, they would now be throwing away build directories and increasing build times. (I suspect they start from scratch, so this is a non-issue.)
* Some folks use git worktrees locally. Will this increase their build times too much? (This is probably mitigated by the remote cache.)

Backing up to address some technical points:

* Did you perhaps mean [`$REPO_TOP`](https://cs.opensource.google/opentitan/opentitan/+/master:util/build_consts.sh;l=27;drc=762b9ae2d286ad9d5783d43526bf4174d6af68fb) instead of `$OT_ROOT`? I only see [a few references](https://cs.opensource.google/search?ss=opentitan&q=OT_ROOT) to `$OT_ROOT` in `sw/vendor/patches/riscv_compliance/`. I'm also struggling to find `$OT_ROOT/bazel-build` in a `.gitignore` file :)
* We probably would want to set `--output_user_root` rather than `--output_base`. In the Bazel docs example (https://bazel.build/remote/output-directories), the output base is `/home/user/.cache/bazel/_bazel_$USER/7ffd56a6e4cb724ea575aba15733d113`, whereas the output user root is the prefix `/home/user/.cache/bazel/_bazel_$USER`.

**Comment by martin-lueker** [comment]
Hi Dan, 
   Thanks for your comments!  My bad about `$REPO_TOP` vs. `$OT_ROOT` (we have a local convention of using $XYZ_ROOT ) for each project.) 
   Right now it looks like the easiest way to handle this may be to adopt @a-will's suggestion in #14768 of just having a secondary bazelrc file (e.g. something like .bazelrc-site) that does not go into git, but allows each site to add their own policies for this.
