### ISSUE TITLE
[bazel] Support for non-standard location of `srec_cat`

### ISSUE THREAD

**Issue by martin-lueker** [lowRISC/opentitan#14769]
In `sw/rules/opentitan.bzl` it seems that `srec_cat` is invoked directly without checking where it may be in the PATH.   This is not working when this application is in not in some standard path location.   Is there any way in bazel to search the user's PATH to find the correct location?  Passing `PATH` to bazel via the `--action_env` option does not fix this problem (nevermind that this is probably not a good idea anyway..,)

Interestingly enough this is not a problem when bazel is looking for the external native toolchains, which we also have in a non-standard path.

For now I have a workaround where I've added a complete path for this in `opentitan.bzl`, but this is not sustainable, as it only fixes my environment.

**Comment by timothytrippel** [comment]
This should be fixable by bringing the `srec_cat` tool under bazel management.

**Comment by timothytrippel** [comment]
Admittedly this might be easier said than done as we would be making assumptions about your system to do so, or building the tool from source after having Bazel pull it down, which might have a significant impact on overall build times.

@martin-lueker  To help me better understand what is not working here, can you share the env vars you plan on passing with `--action_env` using the site-specific `.bazelrc` in #14775 ?

**Comment by martin-lueker** [comment]
Hi @timothytrippel, I am currently passing `--action_env=PKG_CONFIG_PATH=/path/to/some:/various/pkg-config/directories`. Coincidentally, these directories hold all of the usb/ftdi libraries that we've needed for building `srec_cat`.   So I think odds are good that if you can add srec_cat to the bazel externals, we may be able to link it.

**Comment by timothytrippel** [comment]
> Hi @timothytrippel, I am currently passing `--action_env=PKG_CONFIG_PATH=/path/to/some:/various/pkg-config/directories`. Coincidentally, these directories hold all of the usb/ftdi libraries that we've needed for building `srec_cat`. So I think odds are good that if you can add srec_cat to the bazel externals, we may be able to link it.

Sorry I'm not sure I follow the last bit, are you suggesting we instruct Bazel to pull down the `srec_cat` source code as an external dep and then have Bazel build the `srec_cat` tool from src?

**Comment by martin-lueker** [comment]
> Sorry I'm not sure I follow the last bit, are you suggesting we instruct Bazel to pull down the `srec_cat` source code as an external dep and then have Bazel build the `srec_cat` tool from src?

Ah, I thought this is what you meant by bringing `srec_cat` under bazel management.  What else did you have in mind?

**Comment by timothytrippel** [comment]
No worries at all! Sorry I wasn't very clear above.

There were two meanings to "bring this under bazel management" that I was thinking of (the second is the one you pointed out) I just was confused when you said "we may be able to link it":

1. If the dependency is pre-built, as is the case with lowRISC toolchain, then bazel can simply download and unpack the tarball, which looks like [what we do](https://github.com/lowRISC/crt/blob/7b99c6f96b902283f73a9133564e27c85922d88a/config/repo.bzl#L26); however whatever we download and unpack, we assume has been built for the target system we are running on, otherwise this doesn't work.

2. If the dependency is some source code that we either want to pull in directly (e.g., maybe we just want to use a filegroup or some bazel rules) to another target, or we want to build as part of building the dependency chain of another target (the scenario you described), then we can do so too. However, to build a target dependency would require the dependency itself be a bazel project, or have a way to easily generate the BUILD rules for such (as is the case with rust crates and the `cargo raze` tool, though [rules\_foreign\_cc](https://github.com/bazelbuild/rules_foreign_cc) usually gives us a way around this too).

From the looks of things, both the [`srecord` source code](http://srecord.sourceforge.net/download.html) and [prebuilt Linux binaries](https://sourceforge.net/projects/srecord/files/srecord/1.64/) are available to download, so we could take either approach:



1. have bazel just pull down the prebuilt Linux binaries
    1. should yield fastest build time as we aren't building anything
    2. will only work on a Linux system, which is all we support now anyway
2. have bazel pull down the source code and build the tool as part of the dependency chain of another target
    3. might increase build times, won't know magnitude of impact until we try
    4. the srecord tools are built with a configure-make build setup, so we will need to make use of [rules\_foreign\_cc](https://github.com/bazelbuild/rules_foreign_cc) to build the tools
    5. building also requires the following deps: `libboost-dev libgcrypt-dev`

I am leaning towards option 2 since it is more portable in the long term, and the tool looks relatively small, only took 8 seconds to build on my (albeit quite powerful: 72 core) workstation. 28 seconds if I only build using 8 cores.

**Comment by martin-lueker** [comment]
Hi @timothytrippel, 
   A potentially much simpler solution: Would it be okay to just set `use_default_shell_env=True` for `_bin_to_vmem_impl`?
This works on our system

**Comment by timothytrippel** [comment]
yep I think that should be ok, provided it passes CI (which it looks like it is). Glad that works!

I think in the long term, for the sake of hermiticity, we probably still want to do one of the two options above, and since this this issue will close when your linked PR merges I will break my above comment out into an issue with lower priority.
