### ISSUE TITLE
[bazel] Handle site-specific environments through env

### ISSUE THREAD

**Issue by martin-lueker** [lowRISC/opentitan#14768]
Due to the multi-tenant nature of our development system almost nothing we use is installed in the default directory.   Our `PATH`, `LD_LIBRARY_PATH` and `PKG_CONFIG_PATH` environments consist of long strings of site-specific paths holding everything.  We have environment module tools in place to quickly switch from one project to another, and we generally try to do everything through environment variables.  When file configurations are necessary, we try to store them in common space shared by the team.

Could we use environment variables to pass site-specific `PATH`s into bazel via `bazelisk.sh`.  For example one could create an OPENTITAN_BAZEL_BUILD_ENV variable, that could for instance contain any number of `--action_env` options for `bazelisk.sh` to pass into `.bin/bazelisk`.

**Rationale for this request:**
I realize that the same functionality can be accommodated using `$HOME/.bazelrc`, but this is suboptimal for two reasons:
1. Fixed configuration files would make it hard for us to reproduce issues or switch projects.   We generally discourage users from storing configuration information in their home directory for reasons related to reproducibility.
2. Our paths are configured via many different files that are updated independently.

**Comment by a-will** [comment]
For a slightly different approach, would an `OPENTITAN_USER_BAZELRC_PATH` work? Then, when it's defined, we can pass in a user-defined bazelrc arg in bazelisk.sh, and all the bazelrc flexibility exists for site-specific configuration.

**Comment by martin-lueker** [comment]
Hi Alex, 
   As I was reading more about the documentation was just thinking something similar.  Another approach could be to have something like `try-import .bazelrc-site` in `.bazelrc`.  I'm giving that a try right now actually.   If that works then this would close both #14767 and #14768 for us.

**Comment by martin-lueker** [comment]
Having a `.bazelrc-site` located in the repo, would work pretty well in our environment as we are already tracking the repo and so we could just make a common file that our environment script drops into the repo.   Would this be okay for the rest of the team?

**Comment by martin-lueker** [comment]
Though I can see how having it completely outside the repo and pointed to by an environment variable would also be cleaner, as there may be less possibility for confusion & cross-site contamination

**Comment by a-will** [comment]
I think both approaches work fine. They are described in https://github.com/bazelbuild/bazel/issues/10904#issuecomment-818717854 . You can see there is quite a discussion there around a similar request, heh.

Compared to the wrapper script with the environment variable, the advantage of `try-import` is that you can potentially use the `bazel` executable directly on the command line, which is nice for bash completion on the interactive side. On the other hand, the environment variable is a bit less cumbersome for setup, since new worktrees can "just work" instead of requiring generation of the user bazelrc file again.

As a user of such a feature, your input will hold more weight about which is the nicer workflow. :)

**Comment by martin-lueker** [comment]
Hey neat!  I knew this was probably discussed somewhere, but I just didn't go back far enough.  This is good stuff.  Thanks for the pointer.
