### ISSUE TITLE
[otp/dv] sec_cm can link to more than one alert

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#14790]
The current sec_cm test assumes all the security counter measures only trigger one alert, but in otp_ctrl, all close source related logic will trigger `fatal_prim_otp_alert` instead of `fatal_check_error`.
Shall we support this infrastructure in DV?

**Comment by weicaiyang** [comment]
not sure if we could handle it like this
For the assertion, add one more line for the other alert
  `ASSERT_PRIM_FSM_ERROR_TRIGGER_ALERT(Check1_A, the_same_path, ALERT1)
  `ASSERT_PRIM_FSM_ERROR_TRIGGER_ALERT(Check2_A, the_same_path, ALERT2)

And override the sec_cm sequence to check it also triggers another alert.

Since only 1-2 blocks have this requirement, it may be easier to treat them separately than updating the DV framework.

WDYT?

**Comment by cindychip** [comment]
PR #14911 resolves the issue.
