### ISSUE TITLE
[kmac] entropy refresh

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#14832]
Hello everyone,

I discussed with @eunchan offline about the entropy refresh and would like to get your opinions. 

The current design will re-request an entropy when the entropy_cnt reaches a register-configurable threshold.
But in terms of what counts for an entropy_cnt, currently we increment the entropy_cnt when the operation consumes secret key.

However, there are two ways that entropy is consumed:
1). During key scrambling.
2). During msg scrambling (this only happens if the `msg_mask` is set to 1)

Should we also increment the entropy_cnt when the msg mask is applied, or are we okay with the current implementation? 

Reference:
entropy_cnt register definition: https://github.com/lowRISC/opentitan/blob/master/hw/ip/kmac/data/kmac.hjson#L650

@johannheyszl @cdgori @tjaychen

Thanks!
Cindy

**Comment by tjaychen** [comment]
My understanding of this is that the key masking of the "mac" is really what's important. 
It would probably be ideal that we be consistent and do with the message portion also, but maybe not something we have to change now.

I think @johannheyszl and @jadephilipoom can speak better to this.

**Comment by jadephilipoom** [comment]
If I'm correctly understanding the original message, it seems like not incrementing `entropy_cnt` when entropy is consumed for `msg_mask` could have implications for the protection of the key as well -- if KMAC consumes all its available entropy for `msg_mask` and doesn't refresh because `entropy_cnt` wasn't incremented, what happens if it then tries to mask the key?

> My understanding of this is that the key masking of the "mac" is really what's important. It would probably be ideal that we be consistent and do with the message portion also, but maybe not something we have to change now.

One area to be careful about the message portion is for key manager operations during boot. For instance, when the key manager advances to the `CreatorRootKey` state, it adds a  `DiversificationKey` and `HardwareRevisionSecret` to the _message_ portion of the KMAC-based key derivation:
https://docs.opentitan.org/doc/security/specs/identities_and_root_keys/#creator-root-key

Later advances to the key manager state, as described in that page, also involve secret message portions (the `KM_DERIVE(K, M)` in that document involves a `KMAC(K, <something containing M>)` under the hood).

**Comment by johannheyszl** [comment]
Thx @jadephilipoom, sounds very convincing to me. Looks like it would be great to increment in both cases.

**Comment by tjaychen** [comment]
sorry i think i misled the conversation. I don't know what I was thinking yesterday. I read it incorrectly as message not being masked, but that's not what @cindychip  is saying.

I think what she's saying is that the [entropy refresh counter](https://docs.opentitan.org/hw/ip/kmac/doc/index.html#Reg_entropy_refresh_threshold_shadowed) increments only for the key masking usage, and not the message.  To clarify what this means, it does not mean the message doesn't get entropy.  

When the threshold is met, fresh entropy is requested from the `edn` by `kmac` to reseed the local lfsr.  So this just means the message still gets entropy, but it's locally generated.  So only when the appropriate number of "keys" have been processed, do we actually interact with `edn` again to fresh input. 

So while I think it would be nice to be consistent and increment on both, I don't know if it is a must have at this point.

**Comment by eunchan** [comment]
> sorry i think i misled the conversation. I don't know what I was thinking yesterday. I read it incorrectly as message not being masked, but that's not what @cindychip is saying.
> 
> I think what she's saying is that the [entropy refresh counter](https://docs.opentitan.org/hw/ip/kmac/doc/index.html#Reg_entropy_refresh_threshold_shadowed) increments only for the key masking usage, and not the message. To clarify what this means, it does not mean the message doesn't get entropy.
> 
> When the threshold is met, fresh entropy is requested from the `edn` by `kmac` to reseed the local lfsr. So this just means the message still gets entropy, but it's locally generated. So only when the appropriate number of "keys" have been processed, do we actually interact with `edn` again to fresh input.
> 
> So while I think it would be nice to be consistent and increment on both, I don't know if it is a must have at this point.
> 
> @cindychip @eunchan let me know if I understood correctly.
>

Yep. You correctly described the issue. Thanks!

**Comment by johannheyszl** [comment]
@tjaychen no worries, you did not mislead. we understood exactly this.

however, @jadephilipoom pointed out 2 things:
- if we consume entropy for masking msg, we might take it away from some subsequent key masking.
- masking msg may not be less important since (longterm) keys are generated through such msgs.

pls @jadephilipoom to add/correct if im inaccurate, thx

**Comment by cindychip** [comment]
TODO item for @cindychip: Add a sequence to request entropy in the middle of any kmac operation.

**Comment by eunchan** [comment]
We've discussed this issue offline. Here's summary:

- Cryptolib does not prevent the cSHAKE/SHAKE from being used for security sensitive msg
  It means, technically, attacker or non-trusted app (SW app) can request very long cSHAKE XOF op to get the internal 25 x 32b LFSR state, (it is quite hard though)
- KMAC refreshes the entropy only in KMAC mode and `hash_cnt` hits the threshold.
- KMAC also provides a SW interface to refresh the entropy from EDN manually. It can be requested while in an operation.

So, the current HW impl is OK, cryptolib will limit the maximum output length of cSHAKE op and if an sw app requests squeeze multiple times, it will refresh the entropy.

@johannheyszl @jadephilipoom plz correct me if I am wrong.

**Comment by jadephilipoom** [comment]
I'll just add a couple extra notes from the discussion so I don't forget them :slightly_smiling_face: 

- The KMAC  entropy refresh happens _after_ each KMAC operation. So if we want to prevent KMAC and hashing operations from ever using the same entropy in cryptolib, then we need to reseed KMAC _before_ each KMAC operation as well.
- Software-forced reseeding is via the [CMD register](https://docs.opentitan.org/hw/ip/kmac/doc/#Reg_cmd) and can be done in the middle of a hashing operation (for instance, if the cryptolib sees a request for an incredibly extended output that could cycle the LFSRs, then cryptolib could force a reseed between `squeeze()` operations to prevent the attacker from getting too much information with the same entropy).
- One implication of `hash_cnt` not increasing for non-KMAC operations is that a malicious application could request a lot of SHAKE/cSHAKE/SHA3 operations in order to figure out the masks, and then wait for another application to request a SHAKE/cSHAKE/SHA3 operation _on secret data_ so they could extract it via a side channel. However, physical side-channel protection for messages is already limited because the message FIFO is unmasked, and it makes sense that the protection for the message is less robust than protection for actual keys. The cryptolib documentation should be clear about the level of protection available for Keccak messages.

**Comment by eunchan** [comment]
Thanks for the summary @jadephilipoom ! Just one note I want to add here.

> I'll just add a couple extra notes from the discussion so I don't forget them 🙂
> 
> * The KMAC  entropy refresh happens _after_ each KMAC operation. So if we want to prevent KMAC and hashing operations from ever using the same entropy in cryptolib, then we need to reseed KMAC _before_ each KMAC operation as well.
>
KMAC refreshes when it hits the hash count threshold not each KMAC op.

**Comment by tjaychen** [comment]
thanks for the clarification all.

**Comment by jadephilipoom** [comment]
Maybe so. An attacker who wanted to cycle the LFSRs could also request a KMAC for a really huge message, in which case a reseed during `absorb` would be helpful in the same way a reseed during `squeeze` already is. Assuming the bounds for how long this would need to be are quite high, though (which seems to be the case? I don't know the exact number), we can work around it in software by placing limits on how long the message for KMAC can be.

**Comment by tjaychen** [comment]
sounds good.

**Comment by cindychip** [comment]
Looks like the conclusion is - the current design is fine. I will close this issue.
