### ISSUE TITLE
[test-triage] chip_sw_lc_walkthrough_dev

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#14850]
### Hierarchy of regression failure

Chip Level

### Failure Description

Job chip_earlgrey_asic-sim-vcs_run_default killed due to: Exit reason: Pod abruptly killed. Check resource usage. has 2 failures:

Most likely the test times-out for wall-clock time. It already sets run_timeout_mins to 240, which is very long! It failed 1 out of 3 runs.

### Steps to Reproduce

- Commit hash: https://github.com/lowrisc/opentitan/tree/b73727cd502c1a66545c7f84d7861a1474342963
- ./util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i chip_sw_lc_walkthrough_dev --fixed-seed 3616320371 --build-seed 2341666946 --waves -v h

**Comment by cindychip** [comment]
Oh! Thanks Matute, yeah lc_walkthrough goes through RMA state that takes a long time to erase flash memory. Let me check other tests that also goes to RMA state and see their timeout value.

**Comment by tjaychen** [comment]
@cindychip i should have added a run time option to reduce the flash program latency. 
That "should" help a little. Do you know how these tests would changed based on random seed otherwise? Is it the primary clock frequency? I can't remember if these tests do the "fake" clock calibration thing to get to a set frequency.

**Comment by cindychip** [comment]
HI Tim, sorry for the late reply:
1). If the seed randomization should have little impact on this, but it might have some depends on how OTP init fetches the EDN requests.
2). This test currently only hard code to use internal clock.

**Comment by tjaychen** [comment]
sounds good, let me know if you want me to help have a look.
I thought reducing the program latency would be enough to help..

one thing I forgot, during this walkthrough, we probably progress through certain states where ROM may not run (is that the case..?) If that's true, the clock remains uncalibrated, and the frequency for that clock could vary from run to run.  So it's possible that maybe one particular test happened to land on a slower clock and everything just takes longer?

**Comment by cindychip** [comment]
Thanks Tim, we discussed about this offline, but just want to put the summary here:

1). Yes, this test enabled your run time flash optimization `+flash_program_latency=5`
2). This is the current stages of this test:

RAW -> TestUnlocked0 -> Dev -> Rma
a). RAW state is the only one that did not use ROM.
b). TestUnlocked0 -> Dev: use internal clock
c). Dev -> Rma: use external clock
Since dev -> rma uses external clock, we believe the latency due to un-calibrated clock should not be the case.

I will keep monitoring the case for a full night and see it is still timeouts.

**Comment by tjaychen** [comment]
thanks cindy!

**Comment by cindychip** [comment]
I have not seen this issue since 9/12, and before 9/12 there was some pinmux issue that causes the test to fail.
I will monitor it until the end of this week, if still did not see any failure, I will close it.

**Comment by cindychip** [comment]
I am going to close this issue because it never happened again. Potentially Tim's flash enhancement fixed it :)
