### ISSUE TITLE
Does OpenTitan have the ability to reset individual blocks? (UART, SPI, I2C)? If not is it too late to add it?

### ISSUE THREAD

**Issue by drewmacrae** [lowRISC/opentitan#14922]
Especially with I2C, the block has a reasonable amount of state which can be challenging to clear if impacted by a reset/loss of power etc. Is there a means with which to reset the state of the peripheral block individually? I've looked and can't find it.

How would we decide about implementing such a reset?

**Comment by tjaychen** [comment]
yep! This is not super well documented, because our documentation is not templated, so it is not able to take information from the hjson to properly populate.

So for the time being..refer to [here](https://github.com/lowRISC/opentitan/blob/master/hw/top_earlgrey/sw/autogen/top_earlgrey.h#L1648).  All the IO interfaces basically have a reset because we are worried they can get stuck.

Most of the others modules do not though.

**Comment by cdgori** [comment]
> Most of the others modules do not though.

Tim didn't say it, but this (not having a module-level reset) is intentional, to mimimize the possibility of two blocks being in inconsistent states which can enable certain kinds of security issues due to violated interblock assumptions.  

For IO interfaces we understand the (potential) need to get to a known-good-state and therefore support this.

**Comment by drewmacrae** [comment]
And UART doesn't have sufficiently durable state to merit it?

**Comment by tjaychen** [comment]
yeah there's a chance UART was missed because it was considered "simple" (ie, the track record of it getting stuck because of a bad host is lower).

But if we think it's important to have, we should probably file an issue for it.  The design change is trivial, but the verification will take a bit.
