### ISSUE TITLE
I2C dif doesn't support line loopback

### ISSUE THREAD

**Issue by drewmacrae** [lowRISC/opentitan#14931]
The i2c has a line loopback setting that can't currently be exercised with the dif
This is independent from #14930 because I'm not ready to fix it yet

**Comment by drewmacrae** [comment]
I'm not sure what the use case for this functionality is or how it works, so it's challenging for me to write code to exercise it.

**Comment by tjaychen** [comment]
@drewmacrae sorry this part is a bit confusing.
As you says, almost none of our blocks (outside of maybe uart) supports a line loopback.

So this loopback is more of a device level loopback. I'm working on #14851 right now, which is the host equivalent of this test.

And the idea is basically the device needs to send i2c data out to "somewhere".  The somewhere then replays this data back to device when a read transaction is issued. 

In your case, since it's i2c target, the roles are reversed. If you have to assume someone will send you data, and after receiving you will play it back at some point.  Or we could prepare the payload directly in the device, have it read out and then written back, and then eventually compare in the test to see if it matches.

The "somewhere" will differ per platform. For fpga its' going to eventually be hyperdebug, but for simulation it has to be one of the verification agents. The I2C one is not completely developed yet.

**Comment by drewmacrae** [comment]
In https://docs.opentitan.org/hw/ip/i2c/doc/#Reg_ctrl there's a reference to a i2c.ctrl.LLPBK bit that controls line loopback. I'm not currently planning to add it to the dif because I'm not sure when/why it might be set or read or what other concerns to have around it. I filed this issue to point to in a "FIXME" comment I wrote as I'm working on adding what I need to control the device to the I2C dif.

**Comment by tjaychen** [comment]
thanks @drewmacrae ! I actually misread your original issue, i didn't even know we had a line loopback feature. 
I think long term it would be good to test against an external DV agent though.

**Comment by drewmacrae** [comment]
It looks like it configures the block to have data as if it's getting it on the active function (host or device) and to write data it's previously received either as writes or responses. My mental model of it is shaky so far. @a-will pointed out that the I2C block might be used as both host and target simultaneously, and I think I can see how something like this might be useful to bring up a bus during development.
