### ISSUE TITLE
[rtl/rstmgr] Revise reset consistency checks

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#15093]
The reset consistency checkers are connected to clk_io_div4_secure, so they are less active than if they were connected to clk_io_div4_powerup. This is a concern, since it seems they should be active as much as possible. In addition, reset consistency checks are disabled for
u_d0_lc_io_div4
u_d0_lc_io_div4_shadowed
u_daon_lc_io_div4
u_daon_lc_io_div4_shadowed
This could be functionally okay, but it may need to be changed if the clock driving them is changed.

Of course, clk_io_div4_powerup will be turned off during deep low power, but there are cases when it will remain on while clk_io_div4_secure is off.

Another area of concern is whether unexpected reset changes are detected when clocks are disabled. the latch behavior in the consistency checkers suggests an unexpected reset will be detected, but it may be possible for an unexpected reset drop to escape undetected.

**Comment by jeoongp** [comment]
I fixed this connection issue from clk_io_div4_secure to clk_io_div4_powerup in #15183.

For consistency checks on u_dx_lc_io_div4(or div4_shadowed), they are automatically disabled because rst_ni comes from lc_io_div4. That is, the main reset does not need to check itself. All these blocks are driven by clk_io_div4. Currently, each reset is paired with its corresponding clock. 

However, if the clock driving them is somehow changed later and rst_lc_io_div4 is paired with different clocks, we need to update script files to handle different clocks. If you have any question, let me know.

**Comment by matutem** [comment]
Hmm, what if we used io_div4_powerup for consistency checkers? Would that enable all resets to be checked? Yes, even the powerup clocks get turned off, but they probably stay on for enough cycles to perform the checks.

**Comment by jeoongp** [comment]
They are still disabled because both clk_io_div4_i and clk_i are connected to the same net clkmgr_aon_clocks.clk_io_div4_powerup.

**Comment by matutem** [comment]
Ah, you are right. Any thoughts about unexpected resets going inactive when clocks are stopped?

**Comment by jeoongp** [comment]
That's a good point! rstmgr_cnsty_chk is not able to check reset while clocks are stopped. But, once clocks are resumed, as I guess it will check both resets (child reset and parent reset). If reset discrepancy is detected, an error will be raised. 

If we can generate this case, we can make sure what's going on.

**Comment by tjaychen** [comment]
cc @tjaychen

**Comment by matutem** [comment]
Apparently there are no remaining issues here.
