### ISSUE TITLE
[rtl,rv_core_ibex] Desired fetch disable behaviour

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#15219]
Currently when the `fetch_enable_i` input is set to false ibex stops requesting new instructions in the fetch stage, however it doesn't flush out any inflight requests that may be buffered.

When the instruction cache is present requests are buffered in the 4 fetch buffers the icache has. These are effectively prefetches, as it doesn't take branches into account, but assuming no branching these requests continue.

Ibex will eventually come to a halt but only after some small number of instructions have executed after `fetch_enable_i` is set to false.

Is this acceptable behaviour for the OT use case?

@tjaychen @msfschaffner @cdgori

**Comment by tjaychen** [comment]
This seems acceptable to me. We did after all name this signal `fetch_enable` and not `execution enable`. 
We can also reasonably argue that when this signal arrives, the things that have already been fetched have passed the smell test (integrity check etc), so it's reasonable to just finish them off.  

It may be nice in the future to have an execution enable for immediate stop, but I don't think that's something we have to add now. 

I also think that assertion probably belongs better in ibex and not rv_core_ibex, since the latter really doesn't know about the internal structure.

**Comment by msfschaffner** [comment]
I agree. We could for instance relax the assertion to allow *linear* execution of up to N instructions, where N is the maximum number of instructions that the prefetch buffer can hold.

As for the place of the assertion: it makes sense to move it into Ibex itself, although in that case we should replace the one in the `rv_core_ibex` wrapper with a generic one that tests for correct propagation to the Ibex ports. It is slightly more than a connectivity test, since there is some glue logic.

@GregAC if you want to take the Ibex side, I can update the OT assertion.

**Comment by cdgori** [comment]
I think it's ok as well.  

However, two questions:
1) What conditions de-assert `fetch_enable_i` ?
2) What happens if there one of the 4 prefetch buffers contains a branch?

**Comment by GregAC** [comment]
Following the silicon meeting we have decided to alter the implementation of the fetch enable to gate instructions moving from the fetch stage to the decode/execute stage. There was concern around the lockstep mismatch in particular. This triggers the local escalation path which disables fetch but with the current behaviour this would may allow a few instructions to executed following a potential glitch attack against Ibex. Altering the fetch enable behaviour enables a lockstep mismatch to become a 'hard stop' bringing execution to an immediate halt rather than a 'soft stop' bringing execution to an eventual halt.

**Comment by GregAC** [comment]
PR for new fetch enable in Ibex here https://github.com/lowRISC/ibex/pull/1844

**Comment by GregAC** [comment]
Fetch enable behaviour now vendored into OT
