### ISSUE TITLE
[top / rom] Medium term solution for rma / escalation handling

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#15222]
#14867 has surfaced a somewhat fundamental trade-off for OpenTitan, specifically security vs debugability. 
The core issue is whether we should trade off the ability to enter RMA state for security.

Currently in the OpenTitan design, if the device escalates (either to virtual scrap or reset), RMA entry will fail. 
In the former case, `lc_ctrl`, `otp_ctrl` and `flash_ctrl` will all transition to a state where RMA transition commands cannot be handled.
The latter case is described in #14867 

While long term this may be an okay trade-off, this may be a dangerous approach to take for earlier versions of silicon. 

One solution is to piggyback on `ROM bootstrap` to help mitigate the situation. 
If `ROM bootstrap` is not disabled through `otp`, it is then possible for an external actor to "halt" ROM's execution process.  This prevents the ROM, or any later stage software, from entering the escalation protocol or rebooting through the watchdog timer.  When the device is in this state, we can then safely issue an RMA transition command.

This however, leaves open a tiny window BEFORE `ROM` is halted.  During that window, `ROM` will already configure alert settings based on `otp`, so it is possible that escalation could already be triggered. 

There are a few approaches for this time:
1.  The earlier state of `ROM` is much controlled and less prone to corner cases, so it is a reasonable trade-off to use boot-strap to only halt later stages and accept the risk on `ROM`.  The early `ROM` behavior we can heavily verify and qualify with `otp`, so that in the worst case we do not give `ROM` many options to actually escalate.

2.  Add an option in early `ROM` to "stall"  if the observed reset reason is escalation reset. This stall period will give an external agent time to supply an RMA transition command.  After the "stall" period, the `ROM` can then check if there's an ongoing command from the `lc_ctrl` (TBD that this is possible) and if yes, simply not proceed.

This was the overall approach discussed during the silicon WG.
I personally favor option 1 because i think the `ROM` risk is acceptable for the early period. If we have any doubts during manufacturing, we can simply choose to not allow `ROM` to enable alert escalation and leave that all to `ROM_EXT`, so to me there is no need to add extra branching and conditional logic early in the `ROM`.

Please add your thoughts
@zi-v 
@alphan 
@moidx 
@johannheyszl 
@msfschaffner 
@cdgori 
@vogelpi 
@GregAC 
@cindychip 
@timothytrippel

**Comment by msfschaffner** [comment]
I agree with @tjaychen, the first approach should be good enough since the early alert settings are programmable in OTP. If we went with that approach we would avoid having to open up ROM again and insert this additional feature.

RE: the question in 2. about observability: the life cycle [status register](https://docs.opentitan.org/hw/ip/lc_ctrl/doc/index.html#Reg_status) is not modulated by the mutex and can hence be inspected by SW while a transition is ongoing.

**Comment by zi-v** [comment]
A dedicated RMA strap sounds safer to me. This way, RMA entry is agnostic to all but some HW and LC state array. 
The first approach may be a reasonable bypass for the stage we are in. A couple of questions before we conclude:
1. By hardware default, are all escalation paths disabled, and are only enabled by OTP configuration?
2. What other mechanisms may cause the chip to stuck before the bootstrap stage? I guess inconsistent LC state array is an inevitable one but are there other OTP fields that can cause that (e.g. due to erroneous SW programing)?

**Comment by tjaychen** [comment]
yes by default, the escalation paths in `alert_handler` are not turned on.  The `rom` does not turn on any of the alert handler feature while in `TEST_UNLOCKED` states, so the otp settings only apply to the later states.   However, it is not entirely true that there are no defenses even if alert escalation is disabled. In addition to `lc_ctrl` and `otp_ctrl`, the `pwrmgr` also will auto escalate if the clock to the escalation receiver ever stops.

In terms of what is before boot-strap, there is a fair amount of initialization.
Primarily you can look [here](https://github.com/lowRISC/opentitan/blob/master/sw/device/silicon_creator/rom/rom_start.S) and [here](https://github.com/lowRISC/opentitan/blob/0ea3c9ccf15917b9e61bfdef6c0637c5c2a42cf0/sw/device/silicon_creator/rom/rom.c#L120)

The things I am most concerned however, are:
1. turning on the entropy complex and enabling sram scramble
2. copying values into the ast (otp controlled) and related ast check
3. turning on the icache (otp controlled)
4. turning on the watchdog (although a very large value)

**Comment by zi-v** [comment]
Indeed, there seem to be a lot of OTP activity, and if I got it right flash info block as well, prior to bootstrap decision.
My concern is that faulty bits in those zones will prevent us from moving to RMA.

**Comment by tjaychen** [comment]
@alphan 
@moidx 
any thoughts from you guys?

**Comment by cdgori** [comment]
> Indeed, there seem to be a lot of OTP activity, and if I got it right flash info block as well, prior to bootstrap decision. My concern is that faulty bits in those zones will prevent us from moving to RMA.

I think we inherently have to have some level of working OTP once things are provisioned.  There are the vendor-partition tests that can be run before that which could uncover fundamental issues, I believe.

**Comment by alphan** [comment]
> if I got it right flash info block as well

@zi-v, you're right. We currently `boot_data` from the flash info partition. We already have an OTP item to allow a default value to be used in `PROD` and `PROD_END`. But since bootstrap does not really require `boot_data` I think it makes sense to move the `boot_data_read()` call from `rom_init()` to `rom_try_boot()`, i.e. after bootstrap to derisk it. See #15379.

**Comment by msfschaffner** [comment]
@zi-v the OTP only allows up to 1 faulty bit in each word (correctable via ECC). 
For multibit failures, the OTP automatically escalates whenever it accesses the word.
This means that it will automatically escalate on all detectable multibit failures in the hardware governed partitions and digest values upon boot, since these are read out automatically. So in these cases it does not matter where you halt ROM via a strap in order to go to RMA, since OTP will not even let the chip boot (by design).

As for multibit errors inside SW partitions (`CREATOR_SW_CFG`, `OWNER_SW_CFG`): 
OTP will escalate when words with detectable multibit faults are accessed by SW. So as long as the ROM does not access these words before halting it via a strap, you could technically move into RMA and debug OTP via the test interface.

But to @cdgori's point above, didn't we add `VENDOR_TEST` exactly for this purpose so that we can make sure that the OTP is working before programming it? (`VENDOR_TEST` is the only partition that tolerates all sorts of multibit errors without escalating).

**Comment by zi-v** [comment]
>

**Comment by cdgori** [comment]
I have my usual cavalier attitude about SW misconfiguration not being something hardware should solve for :) but fully agree that statistical programming issues are real (and potentially painful to troubleshoot during initial bring-up).  

But, I think (?) we can still sort out those issues with the `VENDOR_TEST` area to find our programming "recipe" before going on to the rest of the OTP.  If the programming process is that highly varying from partition to partition, we have much bigger issues, I think.  As @msfschaffner says, there are a great many partitions that are hardware governed and automatically read, and so we have to get that right.

I also fully agree with making the bootstrap flash agnostic, at least for ES.

**Comment by tjaychen** [comment]
I actually think i should close this down now, we settled on a solution in #15613.

**Comment by cdgori** [comment]
I want to make sure that #15613 captures what @zi-v was trying to get to - it still depends on being able to program some OTP values but that looks like the bare minimum to me.

**Comment by alphan** [comment]
> @alphan if bootstrap initiation can be flash agnostic it indeed reduce the RMA risk

I initially thought it could be but we discovered another dependency. I think the consensus that we reached (captured in #15613 as @tjaychen pointed out) is probably much safer than just relying on the bootstrap but we decided to include some additional OTP and lc_ctrl checks to limit the duration of the busy loop.
