### ISSUE TITLE
[test-triage] chip_sw_uart_rand_baudrate test runs over timelimit

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#15277]
### Hierarchy of regression failure

Chip Level

### Failure Description

Job chip_earlgrey_asic-sim-vcs_run_default killed due to: Exit reason: User job exceeded runlimit: User job timed out

### Steps to Reproduce

Commit hash: [67a41e3bc](https://github.com/lowrisc/opentitan/tree/67a41e3bc3ff025554a024cdb15fbf892c4752b3)
dvsim invocation command to reproduce the failure, inclusive of build and run seeds:
./util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i chip_sw_uart_rand_baudrate --fixed-seed 3735278523 --build-seed 3413385032 --waves -v h

**Comment by cindychip** [comment]
I think this issue is resolved?

**Comment by msfschaffner** [comment]
It looks like this has been mostly passing over the last days - but once in a while it fails with one seed. 
From the regression script:
```
chip_sw_uart_rand_baudrate | 100.00 | 100.00 | 100.00 | 95.00 | 100.00 | 100.00 | 95.00 | 100.00 | 100.00 | 100.00 | 100.00 | 100.00 | 95.00 | 95.00 | 100.00
```
The last one failed last week on 2022.10.12. We may still want to take a look at the failing seed. Maybe the timeout value just needs to be increased.

**Comment by engdoreis** [comment]
Closing as it is passing since Oct 14th.
Tests | latest | 2022.10.22 | 2022.10.21 | 2022.10.17/2 | 2022.10.17/1 | 2022.10.15 | 2022.10.14 | 2022.10.12/2 | 2022.10.12/1 | 2022.10.11 | Suite
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
chip_sw_uart_rand_baudrate | 100.00 | 100.00 | 100.00 | 100.00 | 100.00 | 100.00 | 100.00 | 95.00 | 95.00 | 100.00 | chip_sw_uart_rand_baudrate
