### ISSUE TITLE
AES counter measure verification issues

### ISSUE THREAD

**Issue by rasmus-madsen** [lowRISC/opentitan#15433]
Currently there are 2 outstanding verification Items on the AES sec cm testplan.
- sec_cm_key_masking
- sec_cm_data_reg_local_esc

We need to come up with a good method of verifying both of these.
this includes defining what  to probe, and when to probe.
@vogelpi @weicaiyang 
Any suggestion on how to go about this? 
what was done in the Kmac I assume you have similar issues there?

**Comment by rasmus-madsen** [comment]
@vogelpi can you point me to the best place to sample data before and after the escalate?
also if the escalate signal is available in the same place that would be awesome

**Comment by vogelpi** [comment]
Sorry, I mixed up two countermeasures, I've now edited my previous message. Regarding `sec_cm_data_reg_local_esc`:

We need to check that the data out and IV register contents don't correspond to these signals inside `aes_cipher_core`:
- `add_round_key_out[0] ^ add_round_key_out[1]` (Where [0] is share 0 and [1] is share 1.)

In addition, we also need to ensure that the data out and IV register contents don't correspond to the above signal XORed with these signals inside `aes_core`:
- `iv_q`
- `data_in_prev_q`

The assertion should probably check a couple of clock cycles around the assertion. So the output should not correspond to the sum in cycle -1, -2, -3.

Please note that the byte order between the data out / IV registers and these internal signals is different. You need to apply `aes_transpose()` to get from one to the other.

**Comment by rasmus-madsen** [comment]
@vogelpi 
I am confused - do we agree that the register content is the the *_q version of the signal?

so you are saying the register content should not match it self x'or with the round_key?

**Comment by vogelpi** [comment]
This picture is from the documentation:
![image](https://user-images.githubusercontent.com/20307557/195844352-e7cb0973-bd76-4871-92e2-798bd466fac7.png)

We need to ensure two things upon escalation:
1.  The `data_out` registers inside the CSRs don't contain something that's related to the output signal of the core. This is `add_round_key_out`. It's not sufficient to just check that it doesn't match. Because there is another XOR in the path to the `data_out` registers. The second input to the XOR is either `iv_q` or `data_in_prev_q`. These values are not secret. Knowing these and the output, you can infer the value that "leaked" through `add_round_key_out`.
2. The IV registers don't contain something that is related to `add_round_key_out`. As you can see in the figure, there is a path going from `add_round_key_out` into IV and one going from the XOR result into the IV.

**Comment by rasmus-madsen** [comment]
ok so if I understand it correctly the expressions we want to check are

```
data_out != add_round_key_out[0] ^ add_round_key_out[1]
data_out != (add_round_key_out[0] ^ add_round_key_out[1]) ^ iv_q
data_out != (add_round_key_out[0] ^ add_round_key_out[1]) ^ data_in_prev_q
```

and that 
`iv !=  (add_round_key_out[0] ^ add_round_key_out[1])`

any other combinations that I should check?

**Comment by vogelpi** [comment]
I've now merged PR #15589 , but we need to rework the assertion part / verification `sec_cm_data_reg_local_esc` a bit. I am now looking into this.

`sec_cm_key_masking` and `sec_cm_data_reg_key_sca` are done (see #15810).

**Comment by vogelpi** [comment]
The follow-up PR reworking `sec_cm_data_reg_local_esc` is here #15844.

**Comment by vogelpi** [comment]
All PRs related to this issue have been merged. I am thus closing the issue.
