### ISSUE TITLE
[kmac] EDN doesn't timeout on FPGA

### ISSUE THREAD

**Issue by ballifatih** [lowRISC/opentitan#15530]
With FPGA, I cannot trigger timeout for KMAC's EDN handshake.

For example, I choose the smallest waiting time configuration for KMAC's EDN by setting entropy_prescaler = 0x00 and entropy_wait_timer=0x01, but EDN response still doesn't timeout. This issue is only on the FPGA side, and there is not an issue with verilator and dvsim.

The related chip_sw test is https://github.com/lowRISC/opentitan/pull/14637, and CI fails because of this FPGA test.

**Comment by ballifatih** [comment]
With FPGA, I cannot trigger timeout for KMAC's EDN handshake. 

For example, I choose the smallest waiting time configuration for KMAC's EDN by setting `entropy_prescaler = 0x00` and `entropy_wait_timer=0x01`, but EDN response still doesn't timeout. This issue is only on the FPGA side, and there is not an issue with verilator and dvsim.

The related chip_sw test is #14637, and CI fails because of this FPGA test.

**Comment by ballifatih** [comment]
I also tried this with a larger number of KMAC invocations (~100) as an experiment, and none of them times out. 

https://github.com/ballifatih/opentitan/blob/edn_timeout_fpga/sw/device/tests/kmac_entropy_test.c

**Comment by msfschaffner** [comment]
CC @tjaychen @alphan @moidx @weicaiyang @cindychip 

I am not certain, but may be this is because of different clock ratios between req/ack domains on the FPGA.

Given that the DV test works I move this into M3 for now, but please LMK if you think this needs to be addressed as part of M2.

**Comment by tjaychen** [comment]
i think it's fine to table. As long as we have a good feel for this on simulation for now.
The clock ratios on FPGA should actually maintain between edn and kmac.  However, in fpga, the entropy source i think is way faster (need to confirm this), so it just might be that by the time you request everything is already pre-generated...

**Comment by alphan** [comment]
> i think it's fine to table. As long as we have a good feel for this on simulation for now. The clock ratios on FPGA should actually maintain between edn and kmac. However, in fpga, the entropy source i think is way faster (need to confirm this), so it just might be that by the time you request everything is already pre-generated...

Makes sense, thanks for the possible explanation @tjaychen! I also think that it's OK to move this into M3.

**Comment by ballifatih** [comment]
Cross referencing an earlier (closed) issue that somewhat touched the same problem #14638, in case the discussions there might also be useful for later.

**Comment by vogelpi** [comment]
Hey @ballifatih ,
I just came across this issue when doing the effort scoping for KMAC. What FPGA bitstream did you use to test this on FPGA? Because the default bitstream also generated in CI will implemented the unmasked KMAC version. This version also doesn't have the `kmac_entropy` module instantiated. The outputs to EDN are always 0, i.e., no entropy request is ever made. Similarly, the entropy timer settings are just ignored for this version. This would also explain why things work in DV and Verilator where indeed the masked version is used.

To test these features, the masking has to be switched on. But due to resource constaints we can't do that by default. In ot-sca we have a prepared bistream with the masked implementation in case you want to test it (on this bistream we have to disable AES masking and stub out OTBN to make the design fit the FPGA).

**Comment by ballifatih** [comment]
Thanks @vogelpi. 
I remember following [the guideline for reproducing CI failures](https://docs.opentitan.org/doc/getting_started/setup_fpga/#reproducing-fpga-ci-failures-locally), so I must have gotten the bitstream from CI artifacts. I think your explanation makes sense.

I will not be able to test this on FPGA for a while, because I don't have access to FPGA at the moment. If this is not urgent, I can also try this with the _correct_ bitstream later. Also, can you point me to where I can get the OT-SCA bitstream? (I am guessing removal of AES and OTBN does not make much impact on the EDN network that is feeding KMAC, so the test should work fine)

I can also self-assign this issue, if this issue will not be a blocker for you.

**Comment by vogelpi** [comment]
Thanks for the quick feedback @ballifatih . I don't think it's super urgent now that we know the failure is probably just due to the masking being switched off. I might be able to quickly test this next week but I don't expect it to fail with the masked bitstream, nevertheless it doesn't hurt to try it out. I'll let you know.

For reference, the masked bitstream can be found here: https://github.com/lowRISC/ot-sca/commit/bae283c76622e0b7dc9eddd8bdbeb0e07994ce98

**Comment by vogelpi** [comment]
I managed to test this on the FPGA with the masked bitstream. The following was needed:

1. Load the masked bitstream from the ot-sca repo:
```
./bazelisk.sh run //sw/host/opentitantool fpga load-bitstream PATH_TO/ot-sca/cw/objs/lowrisc_systems_chip_earlgrey_cw310_0.1_kmac_dom.bit
```

2. Modify the DIF as follows, inside `dif_kmac_mode_kmac_start()` in `kmac_dif.c` change
```c
return poll_state(kmac, KMAC_STATUS_SHA3_ABSORB_BIT);
```
to
```c
return kDifOk;
```
This is needed because the bitstream in ot-sca has some modifications to simplify SCA that change KMAC to not start immediately after providing the START command. Instead also the PROCESS command has to be sent and then there is a delay of 40 clock cycles. This change is not needed when using a normal, non-SCA bitstream with masked KMAC.

3. Compile and run the test without flashing a bitstream:
```
/bazelisk.sh test --define bitstream=skip --test_output=streamed //sw/device/tests:kmac_entropy_test_fpga_cw310_test_rom
```

This gives the following result output:
```
I00000 test_rom.c:133] Version: earlgrey_silver_release_v5-8498-g0ea6df3a2, Build Date: 2022-11-07 18:32:12
I00001 test_rom.c:157] TestROM:3dad3cea
I00002 test_rom.c:195] Boot strap requested
I00000 test_rom.c:133] Version: earlgrey_silver_release_v5-8498-g0ea6df3a2, Build Date: 2022-11-07 18:32:12
I00001 test_rom.c:157] TestROM:3dad3cea
I00002 test_rom.c:235] Test ROM complete, jumping to flash (addr: 20000480)!
I00000 ottf_main.c:126] Running sw/device/tests/kmac_entropy_test.c
I00001 kmac_entropy_test.c:115] Running KMAC ENTROPY test...
I00002 kmac_entropy_test.c:148] loop_ctr = 0
I00003 kmac_entropy_test.c:186] EDN timed out.
I00004 kmac_entropy_test.c:222] hash_ctr = 1
I00005 kmac_entropy_test.c:148] loop_ctr = 1
I00006 kmac_entropy_test.c:186] EDN timed out.
I00007 kmac_entropy_test.c:222] hash_ctr = 2
I00008 kmac_entropy_test.c:148] loop_ctr = 2
I00009 kmac_entropy_test.c:188] EDN seed received before timeout.
I00010 kmac_entropy_test.c:222] hash_ctr = 3
I00011 kmac_entropy_test.c:148] loop_ctr = 3
I00012 kmac_entropy_test.c:188] EDN seed received before timeout.
I00013 kmac_entropy_test.c:222] hash_ctr = 0
I00014 ottf_main.c:100] Finished sw/device/tests/kmac_entropy_test.c
I00015 status.c:28] PASS!
```

So I think it's all good and we can close this issue. WDYT @ballifatih ?

**Comment by ballifatih** [comment]
Yes, this log is what I expect from a successful pass. We can close this issue. Thanks for resolving it @vogelpi!

A follow-up question: with the 40-cycle-delay modification on ot-sca bitstream, because we have to also send `PROCESS` after `START`, this means we cannot run KMAC with large messages, right? (AFAIU, `PROCESS` signals to HWIP that we are done sending message blocks). We are limited up to `MSG_FIFO` size for message inputs. This is not really an issue here, but just asking out of curiosity. I seem to vaguely remember something like this from one of our SCA meetings.

**Comment by vogelpi** [comment]
No worries, you welcome.

Yes, I think you're right regarding the analysis of large messages for analysis using the current ot-sca FPGA bitstream / architecture. On ES we will be able to also analyze large messages but more effort will be needed for trace pre-processing and filtering.

**Comment by alphan** [comment]
Thanks @vogelpi and @ballifatih !
