### ISSUE TITLE
[dv/ast] Speed up clocks enabled

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#15599]
In top-level tests the ast seems to add a large number of cycles before clocks are stable and units can start really working. This causes tests to start after a random time duration, and to take longer to complete. The impact of this is particularly large for tests that reset multiple times, as many tests do.

The ask is to have some way to make this wait be predictable and small, ideally with some plusargs so it won't require a different compilation.

**Comment by matutem** [comment]
Added @tjaychen as an interested party, not a real assignee.

**Comment by Jacob-Levy** [comment]
@matutem I am not sure it is the clocks... It might be the power supply that only after that the oschilator get activated.
Can you send me a wave file with one of the clocks.

**Comment by tjaychen** [comment]
@matutem another part about the clock stabilization is that it depends on on ROM initializing the calibration constants. So even if we fix something in AST, that part will still need to wait though.

**Comment by tjaychen** [comment]
ah so there are multiple things here.
The ast starts off with uncalibrated clocks, and I believe @Jacob-Levy set this up such that frequency is within a random range.
That's why we get variable time until the rom begins to execute.

Before the rom executes though, the `pwrmgr` has to go through its power up FSM and that takes some time. Eventually the `pwrmgr` fsm will request the clocks to turn on, and that's when ast actually turns on the clocks.  So we can probably shorten some time on the ast side, but you will still be bound by the design itself though.. which goes through both life cycle control initialization and otp initialization before it lets the rom execute.

I think an even faster approach might just be to disable dumping until the later in the sim.

**Comment by matutem** [comment]
The ast por_ni input goes inactive at after 10 microseconds, and the next relevant change is ast's ast_pwst_o output, which asserts aon_pok and main_pok at about 905 micros. This seems to be due to dly_cnt in rglts_pdm_3p3v, which counts down from LC2HCOC[8:0] down to zero on the aon clock. These are the 102 cycles you mention above, but the AON clock frequency starts uncalibrated, and in the particular case I am looking at it is 117633 Hz, which explains why it is not 520 us, but closer to 900 us.

So the starting of the pwrmgr is determined by both the increase of aon cycle time early on, and the hi start value of Lc2HcTrCyc.

Changing either or both of these (under plusargs) could help speed things up.

**Comment by Jacob-Levy** [comment]
@matutem The 102 was derived from the fastest AON clock which is the calibrated one for the switching back from PD. The AON clock does not loose calibration unless VCC is lost.

I will add a plusargs to accelerate only the Cold Power-up case.

**Comment by matutem** [comment]
Thanks Jacob.

**Comment by Jacob-Levy** [comment]
The code is done. Will test it and PR it next.

**Comment by Jacob-Levy** [comment]
All changes done and awaits for PR approval & merge...

**Comment by msfschaffner** [comment]
I believe this has been implemented in https://github.com/lowRISC/opentitan/pull/15701 which is now merged. Can we close this issue?

**Comment by tjaychen** [comment]
yeah let's close.
