### ISSUE TITLE
AES automatic mode not working with more than two blocks

### ISSUE THREAD

**Issue by labbott** [lowRISC/opentitan#1560]
The AES automatic mode doesn't seem to work after two blocks. I followed the software programming guide at https://docs.opentitan.org/hw/ip/aes/doc/ but after doing a write of block 2, I never see OUTPUT_VALID get set again. If I run in manual mode (writing trigger each time) I can successfully encrypt.

I have a branch https://github.com/labbott/opentitan/tree/aes_test that extends the existing AES test to four blocks. This test has two functions: aes_test_trigger and aes_test_automatic. If you enable just aes_test_trigger you will see the encryption pass successfully. If you run just aes_test_automatic, you will see it get stuck:

Version:    opentitan-snapshot-20191101-1-598-g1798a827
Build Date: 2020-02-12, 09:47:59
INFO: Boot ROM initialisation has completed, jump into flash!
INFO: start AES test
INFO: wrote intial data
INFO: got data for block 0
INFO: write for block 2

From OpenOCD after this completes:

$ telnet localhost 4444
Trying ::1...
telnet: connect to address ::1: Connection refused
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Open On-Chip Debugger
> mdw 0x40110048 0x1
0x40110048: 00000001 

> mdw 0x40110030 0x4
0x40110030: 85d5d3f5 9d69b903 5a8985e7 afbafd96 

> mww 0x40110020 0x12345678
> mww 0x40110024 0x12345678
> mww 0x4011002c 0x12345678
> mww 0x40110028 0x12345678
> mdw 0x40110048 0x1       
0x40110048: 00000001 

> mdw 0x40110030 0x4       
0x40110030: 85d5d3f5 9d69b903 5a8985e7 afbafd96 

This is on commit cb346df7417a8bea707ade8cde95a00aa68a5d44

**Comment by vogelpi** [comment]
Thanks @labbott for reporting this issue. I could reconstruct the problem using your commit.

There is a hardware bug in the stalling mechanism between the cipher core and the main controller. Because software is not fast enough in reading out the DATA_OUT registers, the cipher core must be stalled until it is safe to overwrite the DATA_OUT registers. Instead of waiting for the DATA_OUT registers being read, the main controller erroneously completes leaving the cipher core waiting forever.

I have a fix ready and will create a PR in a minute.
