### ISSUE TITLE
[edn] Generate / Reseed Command FIFO reduction

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#15857]
This is something that was recently seen in a test.
Since the generate and reseed command fifos can be fully software written, it means that it is possible for software to write the "wrong" command into the fifo (ie, write a payload with the command as reseed into the generate fifo, or a payload with command as generate into the reseed fifo).  In fact this actually happened and caused the entire entropy complex to behave in an odd way.

It seems this could be simplified to one of 2 ways:

1. Since the two fifos are physically separated and written to via different registers, we don't actually need to remember the "command" and can simply hardcode it into the respective data paths, this will save some storage bits.  This change would be very trivial and prevent software from shooting itself in the foot. 

2. We could also combine into one shared fifo, and used the stored command to differentiate how each "pop" should be handled. This is a way more significant change and probably better to be tabled to a later date. 

If time permits, we may try to make the first fix since we've actually observed errors with this and it would help to make sure we don't burn debug cycles over this stuff in the future.

**Comment by tjaychen** [comment]
@cindychip 
@moidx

**Comment by tjaychen** [comment]
dropped this to P4 to represent it's an optimization.

**Comment by cindychip** [comment]
@jdonjdon

**Comment by andreaskurth** [comment]
Triaged for `edn`. Assigning to M2.5 with https://github.com/lowRISC/opentitan/labels/Priority%3AP3 because I think the first suggestion could be within scope but it's meant to "prevent software from shooting itself in the foot", so it's not critical.  The second suggestion seems out of scope for this release.

**Comment by vogelpi** [comment]
Option 2) does not seem feasible as two separate FIFOs are needed because the two commands can have different additional data and the hardware automatically play the content of the FIFOs. Option 1) would be doable but as @andreaskurth noted, it would mainly "prevent software from shooting itself in the foot". But I think we wouldn't gain much here and think we can live without this. Closing as not planned.
