### ISSUE TITLE
[chip-test] chip_sw_flash_lc_escalate_en

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#15971]
### Test point name

[chip_sw_flash_lc_escalate_en](https://cs.opensource.google/opentitan/opentitan/+/master:hw/top_earlgrey/data/chip_testplan.hjson;l=2853?q=chip_sw_sram_lc_escalation&ss=opentitan%2Fopentitan:hw%2Fa)

### Contact person

@tjaychen @matutem

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [ ] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [ ] Host-side component developed
- [ ] HJSON test plan updated with test name (so it shows up in the dashboard)
- [ ] Test added to dvsim nightly regression (and passing at time of checking)

**Comment by weicaiyang** [comment]
AIs from the last DV meeting for this test

[matute] Update this testplan to map with all_escalation test and explain how this is actually tested.

**Comment by weicaiyang** [comment]
I vaguely remember we wanted to test this test as follows. @matutem please correct me if it's wrong.

When lc_esc happens in a block, we increment a counter in flash mem. But if this happen to flash, the counter won't be incremented, which indicates that the flash is locked up. After the chip is reseted, SW reads the counter back to check the value is expected.
I'm not sure if the all_escalation test already has this check. perhaps @matutem can confirm.

**Comment by tjaychen** [comment]
the thing is, once life cycle controller escalate, no one will be able to run any code out of flash.
The flash doesn't allow access which means there is no code execution unless you run the test out of rom. 

I think matute changed the all escalate test to prove that escalation happens even if we cannot access any code, but I think what this test specifically wants is that we check flash controller cannot be accessed during escalation. 

I think the best way to check that would probably be through a stub cpu, since that one won't be vulnerable to all the faults / exceptions that are going to happen.

**Comment by matutem** [comment]
Actually we don't need a new test for this, but just change the all_escalation_resets test to require the interrupt counter(s) not increment when the fault is for flash_ctrl. Otherwise the test currently checks that the alert is for the expected cause using alert_info dump.
