### ISSUE TITLE
Meson pain points tracking issue

### ISSUE THREAD

**Issue by mcy** [lowRISC/opentitan#1617]
# About this Issue
This bug exists to track all issues with have with using Meson to build things. It is *not* an attempt to pick a new build system of raise the question of whether we should, and that is explicitly not a viable short-term solution.
 
Attempting to *patch* Meson is probably of equivalent engineering cost to switching build systems, especially since our pain points come from explicit design decisions, not implementation bugs.
 
Finally, while all of these things are painful, they are not utter showstoppers. Meson is significantly more readable and less dangerous than Make, and we are in a better place for having gotten rid of it. If you have additional problems with Meson, please bring them up on this issue.
 
# No custom functions
Perhaps the largest failing of Meson is the [lack of user-defined functions or macros](https://mesonbuild.com/Syntax.html#userdefined-functions-and-methods). The stated reason is avoiding Turing-completeness of the build language, though other build languages, like Starlark (used by Bazel and other build systems) provides user functions while not being Turing-complete (recursion is an error in Starlark). It is also unclear if non-Turing-compelteness is a useful property, but that is out of scope.
 
This is a non-starter for a lot of reasons, mostly because we cannot define our own custom build rules. Three separate build rules are necessary for building an OpenTitan executable, because it needs to be compiled and linked as an ELF, which is then copied into a VMem file, a binary image, and a disassembly. These four artifacts then need to be exported into the binary directory. There are currently seven instances of this pattern (six flash applications and one boot rom) that need to be updated any time the the "embedded binary creation" process changes. This process also needs to make use of custom_target with external scripts to subvert some of Meson's other restrictions.
 
Meson's documentation suggests using `foreach`, which we already do for defining executables for different targets using link-time dependency injection. It's not onerous, but does not seem to scale well, since we can't avoid duplicating the complicated invocation described above for each executable.
 
In essence, building OpenTitan is complex, but we have epsilon code reuse abstractions, and [the underlying language is actively resistant to trying to do this](https://github.com/mesonbuild/meson/issues/17).
 
# Inflexible, underspecified execution model
Meson's execution model is essentially as follows:
- The top-level Meson file is executed; the `subdir()` behaves essentially like textual inclusion of a subdirectory's Meson file, though `subdir_done()` can be used to prematurely end execution of a Meson file.
- Everything is global, everything is public (like in C), and we seem to have developed ad-hoc prefixing for global names (like in C).
- Directories cannot have circular dependencies, due to the above `subdir` mechanism. This means that the following dependency chain is forbidden: `a/b -> b/c -> a/d`, even though directory structure is otherwise irrelevant (Bazel and Make do not have such a restriction).
 
It is also unclear when things are mutable and what scoping rules exist. For example, loops cannot reassign variables in parent scopes, but they can mutate lists and dicts by appending to them. Meson's reference documents make some attempt to specify this, but the specification does not use uniform language everywhere.
 
# Strict target structure
Meson names targets (as seen by Ninja) according to their output files, *not* the names they are given in the build system. As such, `static_library('my_target', ...)` is *not* `path/to/my_target`, but rather `path/to/libmy_target.a`, which confuses users. This is exacerbated with `custom_target` targets which do not output files that Meson can see, so the name for the target is non-obvious.
 
Meson also expects that outputs for a target are in the directory they are defined in (making $OBJ_DIR -> $BIN_DIR copies very hacky), and, in general, tries to introspect things that look like file paths, to the point that it blindly converts backslashes in strings into forward slashes, in an attempt to canonicalize Windows paths.
 
Meson has a long tail of other surprising, "helpful" behaviors that are not called out in documentation, which make writing novel target types needlessly frustrating.

**Comment by lenary** [comment]
## Assembly Files

Meson does not have "native" support for assembly files (`.S`). It merely passes them into the first compiler it has that can support them, which is usually the C compiler (if using GCC or Clang). This means any assembly-specific flags need to go into `c_args`, which is not obvious.

Not only this, but often assembly files need to be passed in the `sources:` key of declare_dependencies to ensure they are not linked to the final executable too early (or sections might be discarded). 

Because `declare_dependency` does not allow you to pass `c_args` to the targets that depend on you (for compiling the `sources:` with) (it only allows this for `link_args`), arguments for the assembler cannot go with their source files, and have to go with anything that depends on that dependency, which is not obvious. The workaround is to just pass assembler arguments globally to c_args, but that may not always be sensible.

**Comment by lenary** [comment]
## No support for per-executable map files

Often when debugging, it is useful to get the linker to emit a map file, so you can see where code has come from, and why it is the size it is. Not only does meson not support this, it's also nearly impossible to accomplish on a per-executable basis, due to not being part of `executable`, and not being natively supported, and having no way to substitute the current executable name into any arguments (that is documented, at least).

**Comment by lenary** [comment]
# Tool Quality

Meson has a lot of build quality issues, especially around cross compilation and native: true/false in build targets. One particularly wonderful edge-case is that we currently get the following warning in when running meson:
```
WARNING: Unknown options: "build.c_std, build.cpp_std"
```
This is actually entirely incorrect! Meson does know those options, and is taking them into account (if they are deleted, the generated build rules lack the `-std=` options in targets where `native: true`.

This is not remarked upon in the documentation, and nor is the warning suppressed. Indeed there's a long debate about how broken meson is for configuring options for cross compilation in https://github.com/mesonbuild/meson/issues/5590.

**Comment by lenary** [comment]
## Multiple Cross-Compilers

We now have both OTBN and Ibex in-tree. Meson only supports a cross-compiler configuration for one device's toolchain, rather than more than that. This means all but the primary device builds have to use `custom_command` to orchestrate their build through meson, rather than using a meson-native compilation flow. This also makes it difficult to have cross-device dependencies (we will need to inject OTBN blobs into Ibex device executables).

**Comment by imphil** [comment]
## No paths in output of custom_target()
Preserving the subdirectories seems to be impossible with custom_target() not accepting paths but only file names for its `output` key.

See the sw/otbn/meson.build file for details.

**Comment by moidx** [comment]
Closing as obsolete. We have now switched to Bazel.
