### ISSUE TITLE
[top] Clean up FPGA / synthesis constraints for JTAG

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#16323]
The jtag constraints for fpga / synthesis deserve a second look.
On jtag specifically the `tdi/tdo` don't have an explicit relation defined to the clock, and the create clock point is also done inside the device instead of the pad, possibly missing some of the insertion delays.  This might not be super easy to clean-up because jtag is on muxed pins, but it is worth a second look.

**Comment by cdgori** [comment]
It's important to have these constrained, if just to make sure hold time is met when the shift chain is implemented.  The missing insertion delay could cause a surprise in post-layout timing too.

We should be able to constrain tdi/tdo under case_analysis to handle the muxing (I am probably speaking out of turn by suggesting this since I'm almost certainly not the one who has to figure out the case values...)

**Comment by tjaychen** [comment]
this has been done on the `fpga` already. See #16637. 
I guess we still should have synthesis constraints a second look?

**Comment by a-will** [comment]
Resolved by #18847
