### ISSUE TITLE
[dv/prim_mubi*_sync] Improve coverage closure support

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#16586]
For V3 we need 100% coverage, and it will be desirable to reduce the need for explicit coverage exclusions.

There are two cases that can be improved in prim_mubi*sync:
- When instantiated with AsyncOn == 0 and the clk_i and rst_ni inputs are tied to constant both OutputDelay_A and OutputsKnown_A concurrent assertions never fire because the clock doesn't tick. We could make them non-concurrent, as in always @(mubi_i) begin <add immediate assertions instead>, or pass clk_i and rst_ni just for the assertions.
- When StabilityCheck == 1 there is a coverage hole in u_mux (a prim_clock_mux2 instance) where selKnown1 never fires. This is because clk1_i is tied to reset_value, which is a parameter.

**Comment by msfschaffner** [comment]
For the first one, we should probably just connect the clocks/resets. We have other modules that just pull in the clock/reset for the SVA, so this would be nothing new...

**Comment by msfschaffner** [comment]
For the second one: we can probably replace the `prim_clock_mux2` primitives since they are not strictly necessary. I.e., the input signals `mubi_q[k]` and `sig_unstable_buf` come out of a constrained buffer or reg, and the output `mubi[k]` goes through a constrained output buffer again - hence we do not loose any constraints by doing that.

**Comment by msfschaffner** [comment]
This can be closed since the items have been addressed in https://github.com/lowRISC/opentitan/pull/16587.
