### ISSUE TITLE
[dv/tools] Use more recent VCS version

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#16617]
VCS has fixed some coverage-related issues in 2022.06-SP1-1. These will be useful to help with coverage closure.

This can be fixed in both the internal Google tooling and agreed to by the partners.

**Comment by sriyerg** [comment]
@sha-ron @arnonsha @GregAC FYI.

**Comment by matutem** [comment]
We intend to switch directly to the more recent 2022.06-SP2 instead of 2022.06-SP1-1.

**Comment by msfschaffner** [comment]
@vogelpi

**Comment by sha-ron** [comment]
I moved to this version today.

**Comment by matutem** [comment]
Thanks @sha-ron, we expect to switch today as well.

**Comment by matutem** [comment]
This was fixed in google's internal settings.

**Comment by vogelpi** [comment]
Sorry, I was meant to reply earlier. I think we have version 2022.06 (without any SP) installed but would need to upgrade to 2022.06-SP2. @GregAC is managing these installations but he has been feeling well for the last couple of days. I can give this a try. Once we can confirmed that things are working, we should probably also upgrade `tool_requirements.py` to enforce the newer version. Or did you intend to leave the minimal version at 2020.12-SP2?

**Comment by matutem** [comment]
I am not sure how the minimal versions relates to the version to be used. We would prefer to have all collaborators using the same version to avoid "repro" problems, so perhaps the minimal version should ideally be 2022.06-SP2 as well?

**Comment by vogelpi** [comment]
I agree that all collaborators should use the same version. In the past, we used to increase the minimal version e.g. when knowing that an old version had a critical bug that didn't allow correct simulation of our codebase. IIRC the switch to version 2022.06-SP2 is happening because of coverage-related bug fixes. So one could argue the designs probably still correctly simulate and we don't need to upgrade the minimum version but there might be "just" differences in the reported coverage numbers. However, as coverage now becomes more and more important we might just want to enforce it to avoid issues related to collaborators accidentally using different versions? I don't have a strong opinion on this. What do you think @sriyerg , @weicaiyang , @ctopal , @andreaskurth ?

**Comment by andreaskurth** [comment]
I think it's easiest to collaborate if all use the exact same version of the tools. So unless there are strong arguments against it, I would prefer a single version.

**Comment by weicaiyang** [comment]
Agree that we should all use the same version.
I also notice some improvements/bug fix in the new version.
1. the new version recognizes condition coverage on `out = a_express & b_express`, and we need to test 4 combinations (00, 01, 10, 11) in order to get 100% coverage.
2. it excludes more on unreachable coverage.

It sounds worth upgrading the version.

**Comment by sriyerg** [comment]
Agree as well - better to have all collaborators use the same version.

**Comment by vogelpi** [comment]
Okay thanks for you feedback everybody. I've installed 2022.06-SP2 in our environment and did the PRs to update the version used in private CI and then to also enforce this version as minimum version.
