### ISSUE TITLE
Getting started with JTAG documentation issues

### ISSUE THREAD

**Issue by drewmacrae** [lowRISC/opentitan#16635]
1. When we use openocd as managed by our bazel workspace, there isnt an olimex-arm-usb-tiny-h.cfg file. I think that was installed when openocd was installed on your system the old way.

It can be generated with 
```
bazel build //third_party/openocd:jtag_adapter_cfg
```
and can be found with:
```
 ./ci/scripts/target-location.sh //third_party/openocd:jtag_adapter_cfg
```

After that I'm able to bazel run openocd or use the path to the binary in the instructions to find and use it.

2. I had to download a new apt-requirement which is probably fine, specifically: libncursessw5
3. The shell commands to run openocd and opentitantool could both be bazelified

**Comment by AlexJones0** [comment]
`//third_party/openocd:jtag_adapter_cfg` currently no longer exists, so we'll need to find out what happened to that. That is currently being tracked by issue https://github.com/lowRISC/opentitan/issues/22881 and so this is blocked on resolution of that issue.

**Comment by AlexJones0** [comment]
The previous issue is now resolved - `//third_party/openocd:jtag_adapter_cfg` was renamed to `//third_party/openocd:jtag_olimex_cfg` in the interest of supporting multiple JTAG adapters.

The current documentation has already been updated to locate the `olimex-arm-usb-tiny-h.cfg` by using `./ci/scripts/target-location.sh`, and the shell commands to run openocd and opentitantool are now being run through bazel. We could potentially make these separate bazel rules but these commands are sufficient for now and expose relevant parameters in a relatively clear way. These changes were largely made in https://github.com/lowRISC/opentitan/pull/18823 and then amended to use the new `jtag_olimex_cfg` target in https://github.com/lowRISC/opentitan/commit/6dc58eff36932c51d3b48dad01a064cedd5091cf.

Assuming that the mentioned apt-requirement was a typo of `libncursesw5`, then that has since been updated to be included in `apt-requirements.txt` in https://github.com/lowRISC/opentitan/commit/6e2cf65b5e316d0fb6d349921060e0363cf52aaa - see below.

https://github.com/lowRISC/opentitan/blob/0c061a59b7da958a99ffd112535b8cee9a5b648b/apt-requirements.txt#L31

As a result of all the mentioned issues already being fixed by previous PRs, I'm going to mark this issue as closed.
