### ISSUE TITLE
Proposal: RFC Adding automatically generated Rust 'headers' for top _{chip} 

### ISSUE THREAD

**Issue by semihalf-mazurek-michal** [lowRISC/opentitan#16650]
The repository now contains a C header describing all the necessary structures and constants needed to work with the OT chip. For example: [top_earlgrey.h ](https://github.com/lowRISC/opentitan/blob/master/hw/top_earlgrey/sw/autogen/top_earlgrey.h)

That's why I'm proposing to add automatic generation of files with key constants for Rust as well.
Generated Rust structures, constants and enumerations should be independent of any operating system/crate.
The current header generation code for C language is located in: [topgen/c.py](https://github.com/lowRISC/opentitan/blob/master/util/topgen/c.py)

**Comment by timothytrippel** [comment]
@cfrantz hasn't this been added already?

**Comment by timothytrippel** [comment]
@semihalf-mazurek-michal has informed me what exists is only the update to the `reggen.py` tool to generate the Rust equivalent to C header files for the IPs, it has not yet been added to `topgen.py` as stated above.

**Comment by semihalf-mazurek-michal** [comment]
The main goal is to enable automatic generation of all constants and structure for a specific chip version.
Tool reggen cover only register layout, symbolic name for interrupts/alarm/pinmux and base address are generated in topgen.

**Comment by semihalf-mazurek-michal** [comment]
After implementing this functionality, it will be possible to create one package (for example *.gz archive) with all the constants necessary for the implementation of operating system drivers.

**Comment by cfrantz** [comment]
All of the register field definitions are created by `util/regtool.py`.  This tool supports a number of output formats, including C headers, tock `registers!`.  There is support for a more generic "rust" output mode, but I found the output to not be very useful (and since nothing is using it, we could change it to whatever we need).

The `top_earlgrey.h` file is emitted by a separate tool called `topgen`.  This header is regenerated infrequently and, unlike the `reggen` constants, it is committed into the codebase.  It is probably worthwhile to add some form of rust support for these chip-level constants (addresses, irq ids, alert ids, gpio pad constants).

**Comment by semihalf-mazurek-michal** [comment]
- [ ] Generating all rust  consts and enums.
- [ ] Generating rust module
- [ ] Adding code formatting check
- [ ] Integrating to auto-generated register map package (bazel)

**Comment by cfrantz** [comment]
- [ ] Generate in a style useful in opentitanlib, similar to [earlgrey.rs](https://github.com/lowRISC/opentitan/blob/master/sw/host/opentitanlib/src/chip/earlgrey.rs) in opentitanlib.

**Comment by semihalf-mazurek-michal** [comment]
To avoid flickering underline script should be connected to bazel somehow.
I think that any modification can cause this line to change.
`// https://github.com/lowRISC/opentitan/tree/7a7139c8af345f423ac27a0186febdda027f7127`

**Comment by semihalf-mazurek-michal** [comment]
@cfrantz @timothytrippel 
I think all code are merged so i decide to close this issue.
Topic of  array and enum optimization should be addressed latter during usage of this code in TockOS.
