### ISSUE TITLE
[opentitantool] Overlapping meaning of PullMode and WeakPushPull

### ISSUE THREAD

**Issue by jesultra** [lowRISC/opentitan#16685]
In my original Gpio trait, each pin had a mode (Input, OpenDrain, PushPull), and on top of that, they had a (weak) pull mode (None, PullUp, PullDown). Togerther with the boolean output "value" (relevant only of mode was not Input), that determined the driving behavior of the pin, which could be either strongly or weakly pulling up or down, or hi-z.

It appears that subsequently, another more WeakPushPull has been introduced, but I am confused what it is supposed to mean to set WeakPushPull, and the same time as setting pull mode to something.  It appears that every single transport driver either honors pull mode, while not implementing WeakPushPull, or implements WeakPushPull whine not honoring pull mode.

In my (not so humble) opinion, the separate pull mode mode closely mimics how hardware output drivers are typically implemented.  (I have not encountered a device which could be configured in weak driving mode, after which the ordinary boolean output value could be used to control whether pulling up or down.)

For the sake of maintaining concise trait interfaces, and to simplify the work of implementing a new transport, I would like to explore if the two features could be merged.

**Comment by jesultra** [comment]
@cfrantz , I understand that the Gpio trait as is does not support a way of reading whether the OT device under test is pulling weakly or strongly. Such a feature could maybe be useful, though only something that could be realized in Verilator or similar environment, in which the "debugger" had insight into the internals of the output driving stage of the device under test.

However, the WeakPushPull mode added to opentitanlib relates only to how the simulated environment to the OT device under test drives the lines.  And as far as I can tell, the PullMode enum in the Gpio trait already allowed users of transport implementations to request all combinations of weak or strong pull up or down.

Can you elaborate on why WeakPushPull was added, I fear that having overlapping means of achieving the same thing adds to the burden of implementing new transports correctly.

**Comment by cfrantz** [comment]
> @cfrantz , I understand that the Gpio trait as is does not support a way of reading whether the OT device under test is pulling weakly or strongly. Such a feature could maybe be useful, though only something that could be realized in Verilator or similar environment, in which the "debugger" had insight into the internals of the output driving stage of the device under test.

`WeakPushPull` refers to the drivers on the test apparatus, not to whether the DUT has a particular pull configuration.

IOW, `WeakPushPull` is intended to be how opentitantool or an opentitanlib derived test would drive a weak one or zero to the DUT.  I couldn't make heads or tails of what was supposed to be happening with the WeakOne/WeakZero suport in the ti50_emulator code and it seemed to me (at the time I read it)  to be taking about the configuration of the DUT rather than how the DUT was being driven by the test apparatus.

Currently, _only_ the verilator transport is capable of simulating weak vs. strong drives into the GPIO inputs of the DUT.

We should clean this up - I may have misunderstood the intent or meaning of the existing code.  The purpose of the `WeakPushPull` support is to simulate all of the possible strap values to make sure the ROM is able to detect the bootstrap conditions that affect it.

**Comment by jesultra** [comment]
I see, I may not have pul in writing, but I assumed the pull modes to be sufficient to simulate all the strap values.  That is, in order to do weak pull down, you would put the pin into "Input" mode, with a pull mode of "Down".
I realize this could be a little roundabout, but it closely mimics how the HyperDebug hardware works, so I hoped that it would suffice.

I think it is confusing to have both WeakPushPull mode, and also have a separate pull mode setting, and I think we do need the pull mode setting, for use in Input mode.

**Comment by jesultra** [comment]
`WeakPushPull` has been removed, the functionality provided by `PullMode` instead.
