### ISSUE TITLE
[chip-test] chip_sw_csrng_edn_error

### ISSUE THREAD

**Issue by sriyerg** [lowRISC/opentitan#16837]
### Test point name

[chip_sw_csrng_edn_error](https://github.com/lowRISC/opentitan/blob/316831f8c2199f2288dd57ac4aeaec3334b5dfb8/hw/top_earlgrey/data/chip_testplan.hjson#L2371)

### Host side component

SystemVerilog

### OpenTitanTool infrastructure implemented

None

### Contact person

@vogelpi, @cindychip

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [ ] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [ ] Host-side component developed
- [ ] HJSON test plan updated with test name (so it shows up in the dashboard)
- [ ] Test added to dvsim nightly regression (and passing at time of checking)

See issue #16516 for more discussion on this.

**Comment by marnovandermaas** [comment]
Effort for M2.5 added to EDN:
> estimate 16

**Comment by moidx** [comment]
Leaving open to track test plan update as part of #16516.

**Comment by vogelpi** [comment]
I've removed the test point from the CSRNG chip testplan with 33258aa. The reason is that the version of CSRNG in Earl Grey ES (and most likely also the one for PROD) doesn't signal the error condition to EDN. Instead, CSRNG will signal a recoverable alert and stop serving entropy. This functionality can be tested using automated alert tests at the top level or using block-level tests. I am thus closing this issue.

If we decide to implement correct error signaling in CSRNG, this should primarily be tested at the block level (see #15894, and #16516), but we can re-discuss testing this at the top level and for SiVal as well.
