### ISSUE TITLE
How to monitor the internal signals of a design (Opentitan) using  Integrated Logic Analyzer (ILA).

### ISSUE THREAD

**Issue by ladmangesh805** [lowRISC/opentitan#1719]
I want to understand working internal signals.
Issue is How to connect ILA IP core to this (opentitan)design??

**Comment by GregAC** [comment]
The Xilinx/Vivado documentation would be the best place to find the details of the ILA setup.

From the OT side you can open up the vivado project file directly from the GUI which can be found in build/lowrisc_systems_top_earlgrey_nexysvideo_0.1/synth-vivado/ if you've already run fusesoc to generate an image. Though beware it will have a separate copy of the RTL files.

You can generate a project file that uses the RTL in the OT tree (rather than a copy under build/) see the details here: https://docs.opentitan.org/doc/ug/getting_started_fpga/#develop-with-the-vivado-gui

In the past I've just opened up the project in Vivado, generated an ILA IP which I've instantiated at top-level then used hierarchical references to connect down to the signals I'm interested in.

**Comment by silvestrst** [comment]
Hi @ladmangesh805 in general it would be helpful if you could add more details in your questions:
* What are you planning to do?
* What have you tried so far?
* What the issues are?
* Have you got any specific signals in mind?
* Anything else you could think of to help people answer your questions?

Thanks

**Comment by ladmangesh805** [comment]
Hi @silvestrst 
Answers of above questions
1.I planning to add SHA3 in opentitan project.
2.I have removed SHA2 and  added the SHA3 core in HMAC , but not able to check his  working compatibility and simulation (how much cycle it takes ).
3.Issue is I do not have VCS and xcelium for simulation so I trying another method i.e ILA for singal monitoring.
4.The specific signal is HMAC .
5.After adding SHA3 i want run C code on it....now i do not know how it will work.

Thanks for Guidance

**Comment by imphil** [comment]
@GregAC gave a good introduction of how ILA can be used with OpenTitan. If you have ILA-specific questions, please ask in the Xilinx Forum. If you find a bug in OpenTitan that makes ILA unusable, please open a bug report here with *exact steps to reproduce the issue*.
