### ISSUE TITLE
[pinmux, fpv] Review FPV results

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#17355]
The published FPV result for pinmux: https://reports.opentitan.org/hw/top_earlgrey/formal/ip/summary/latest/report.html do not include any details. In particular the assertions that aren't passing could be undetermined or failing. The coverage numbers are also a little low, we should ensure we understand these numbers.

@cindychip any comments as to the status of the pinmux FPV runs?

**Comment by cindychip** [comment]
Hey @GregAC thank you for rising this issue.
Pinmux FPV test covers most of the functions but for detailed coverage in this specific chip level, we can refer to chip level testplan and coverage:
https://reports.opentitan.org/hw/top_earlgrey/dv/latest/cov_report/mod272.html#inst_tag_11129

We did not black box pinmux because for this tape out, we still want to use DV to sign off.
Hope that helps.
