### ISSUE TITLE
[test rom] Test ROM configures SW straps pads as output

### ISSUE THREAD

**Issue by sha-ron** [lowRISC/opentitan#17486]
### Description

Test rom calls pinmux_testutils_init that selects gpio22 as output function on IOC0  pad.
https://github.com/lowRISC/opentitan/blob/bf216c2854ac80f441edfee8e0e14706e7812044/sw/device/lib/testing/test_rom/test_rom.c#L105 
https://github.com/lowRISC/opentitan/blob/b24aaee4ba4cfea846949c4797eef49a6d49b8c5/sw/device/lib/testing/pinmux_testutils.c#L29

**Comment by a-will** [comment]
Note that this does not make the pad an output--The output buffer's enable is merely tied to the GPIO IP's configuration / signal, which should leave the pin as an input.

**Comment by timothytrippel** [comment]
Yes this is true ^, for the pin to be an "output" it has to be muxed as an output (at the pinmux) and then declared an output in the GPIO IP itself.

In any case, if there is no test using `pinmux_testutils_init` that requires this to be muxed as an output (a simple grep should help you find if this is true) then you could update it to not mux that pin as an output in the pinmux. (Though it shouldn't be hurting anything as is since its just the test rom no?)

Would you like to check if this is the case @sha-ron ?

**Comment by a-will** [comment]
This does raise the question of what state the ROM and test ROM should leave the system in. Should the pinmux have residual configuration after jumping to the next stage of boot? Or should it "clean up" and go back to the power-on values?

At least, differences between the reset state in IP blocks and the state the next firmware sees probably ought to be documented. (if they aren't already)

**Comment by sha-ron** [comment]
Thanks @a-will @timothytrippel for clarifying that GPIO IP output selection is needed as well for the output buffer enable,
gpio_test.c test uses pinmux_testutils_init (this is where I failed in the closed-source because the DV TB keeps driving the SW straps). 
During the debug I saw that the test_rom configures MIO outsel and I didn't understand why. I can close the issue if you think it is ok.

**Comment by timothytrippel** [comment]
Since it looks like the [gpio test](https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/tests/sim_dv/gpio_test.c;drc=406c6a795ede9c34a7c841107948917a3b6896f2;l=206) you reference already reconfigures the pinmux to output on the SW strap pins, I went ahead and fixed the pinmux testutils to align the pinmux initialization of the SW strap pins to that used in the ROM. See #17562.
