### ISSUE TITLE
[bazel] `cw310_params` disables opentitantool's rcfile mechanism

### ISSUE THREAD

**Issue by andreaskurth** [lowRISC/opentitan#17567]
The definition of `cw310_params` contains
https://github.com/lowRISC/opentitan/blob/099596b1402ce0df8a980e936a1700dd287afe8a/rules/opentitan_test.bzl?plain=1#L221-L227
which disables the rcfile mechanism of opentitantool (OTT) and sets its `--interface` parameter.

I have an rcfile for OTT, however, which sets `--cw310-uarts` and `--interface` correctly for my environment*, so I currently cannot run `bazel test` for FPGA tests (workaround: locally remove line 222 and 226 for that file).

Doesn't `--rcfile=` as default argument defeat the purpose of having an rcfile for OTT? If we really do need `--rcfile=` in that rule, can I override it when invoking `bazel`?

*The environment that requires this is a rootless podman OT container, where OTT's device detection does not seem to work correctly. That's a [different issue](https://github.com/lowRISC/opentitan/issues/17569), though.

**Comment by andreaskurth** [comment]
CC @cfrantz as you have committed the original rule in https://github.com/lowRISC/opentitan/commit/0b548fa240ca2fe11a38244b9e8a02a11be7db5f :slightly_smiling_face:

**Comment by a-will** [comment]
FYI, `bazel test` can be provided arguments like `bazel run`, but the syntax is different. Each arg needs to be passed as an option value to `--test-arg`.

The `--rcfile=` should be able to be overridden in the test invocation. It's admittedly not the most ergonomic setup, since batch tests would need to all share this argument.

In https://github.com/lowRISC/opentitan/blob/master/util/opentitan_functest_runner.sh#L35 , the `args` can be overridden with later assignments to the same option, but the `test_cmds` cannot.

**Comment by cfrantz** [comment]
Overriding rcfile to nothing is intentional for bazel tests - we don't want the user's local configuration leaking into the test environment.

We have an override for `--cw310-uarts` for CI containers.  See `//ci/BUILD` for details.  The override causes the cw310 uarts to use `/dev/ttyACM_CW310_1,/dev/ttyACM_CW310_0`.  See `//rules/opentitan_test.bzl` to see where the override is applied.
