### ISSUE TITLE
[spi_device] tx fifo not fully utilized

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#1759]
@eunchan 
I found a minor issue.

In spi_device, we have async_fifo with 2 words depth. If I set the TX sram fifo to 2 words wide too, we can only save up to 3 words in these 2 fifos.

For RX, if I set RX sram fifo to 2 words wide, we can save 4 words data in fifos.

Not sure if we can update design to fully utilize the TX fifos and make it consistent with RX.

Here is the command to open the waveform.
cd /edascratch/weicai-opentitan/ot/spi_device.sim.vcs/spid_intr_test/0.spi_device_intr/out
verdi -ssr Verdi.ses &

**Comment by eunchan** [comment]
Hi Weicai, Thanks for testing this first.

The reason is that the FIFO pointer is updated only after it writes the word into the FIFO. If it hit the full condition at the end of the write, then it waits until the FIFO is not full condition. I think current behavior is fine. The software only need to take care of the full condition of the SRAM FIFO.

**Comment by weicaiyang** [comment]
Thanks @eunchan 
Yes, software should only check the SRAM FIFO. It's not functional issue, but it will be easier for DV to model the behavior if TX FIFO can be fully utilized like RX.

Close this issue.
