### ISSUE TITLE
[ottf] spi_device console enhancements

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#17819]
Through several PRs that addressed #17494, the spi_device was added to the OTTF as a potential console device. However, several enhancements could still be made to realize the full potential of this interface

- [ ] investigate the need for / implement a mechanism to send/receive messages that are larger than SPI FIFO
- [ ] enable the RX direction; currently we can only TX messages to the host

**Comment by jwnrt** [comment]
I was going to use the SPI device for UART sival tests, however those need RX communication for receiving commands from the host. We started implementing this, but hit some problems and are deferring it for now:

First, we thought about using the EEPROM / flash emulation protocol where the host sends read / write commands to the device. Unfortunately, that would make TX from the device synchronous, since the host must send `READ` commands to empty the buffer and the device has to be processing those commands in a loop.

Instead, we would probably keep asynchronous TX and have the host read/flush the TX/RX buffer before it writes any data to the device. The device would probably have to do the same to avoid wiping and RX data when it prints with `INFO_LOG`, etc.

This ended up feeling too complicated, so for now we're going to try avoid OTTF commands in the UART tests, but did you have any ideas for how RX communication to the device would work?

**Comment by timothytrippel** [comment]
Unfortunately, both sides have to do some method of polling to either fill or empty a buffer. Which adds some complexity, but you can hide it in the transport protocol itself.

**Comment by timothytrippel** [comment]
Closing this as the spi_device console was recently removed when generic mode was removed.
