### ISSUE TITLE
[entropy_src] SHA3 core / Keccak active without CS AES Halt

### ISSUE THREAD

**Issue by andreaskurth** [lowRISC/opentitan#17941]
`entropy_src` sometimes activates its SHA3 core (and in particular the Keccak round) without requesting CSRNG's AES to halt, as described in [this comment on issue #14193](https://github.com/lowRISC/opentitan/issues/14193#issuecomment-1497734855). This is against the intention of the `cs_aes_halt` interface (see the definition added in #17943). How frequently this happens varies strongly with enabling/disabling, configuration and operation mode, and entropy availability and demand.

Here's an example (`util/dvsim/dvsim.py hw/ip/entropy_src/dv/entropy_src_sim_cfg.hjson -t xcelium -r 1 -w shm -i entropy_src_rng_with_xht_rsps -s 307146402` at 86d6bcef3dcd7a589eb08c72f036ff3540e44bed):
![2023-04-12T12:09:43+00:00](https://user-images.githubusercontent.com/3583291/231452713-39371472-c113-43cc-8d9d-262cf9ed439b.png)
The bottom signal shows when Keccak is active and the signal just above shows when CS AES Halt is active. Clearly, Keccak is frequently active when CS AES Halt is not. The other signals show parts of the operation mode and state of `entropy_src`.

This happens in all modes: during startup, in firmware entropy insertion mode, and in FIPS mode during continuous health tests.
- When Keccak gets triggered, it runs 24 rounds, which together take 24 clock cycles (unmasked implementation).
- In firmware entropy insertion mode, I've seen as little as 200 clock cycles between two Keccak rounds. The actual lower bound may be even less, depending on SW.
- Outside firmware entropy insertion mode, there seem to be at least 512 clock cycles between two Keccak rounds.

In the short term (for M2.5), we are adding the current behavior to the specification together with assertions to ensure the implementation matches our understanding: #17943.

In the longer term, we have to decide (a) if the CS AES Halt interface is necessary at all and (b) if the current implementation is sufficient. Depending on this, we should then:
| (a) | (b) | action           |
|-----|-----|:------------------|
| no  | X   | remove interface |
| yes | no  | fix implementation    |
| yes | yes | keep status quo  |

**Comment by msfschaffner** [comment]
CC @moidx

**Comment by msfschaffner** [comment]
This is low priority for PROD. 
If someone has time to look into this for half a day, we can clean this up. 
Otherwise I think it would be ok to leave as is.

**Comment by vogelpi** [comment]
When studying the internals of the SHA3 engine as well as the ENTROPY_SRC to answer some questions regarding FIPS mode, I think I've found managed to root cause the issue here:

The SHA3 engine can get active under two circumstances:
1) Whenever the main FSM sends the `sha3_process_o` signal to the SHA3 engine. This happens when we've collected enough entropy to produce a full 384-bit seed (equals the configured health test window size). This case is or should be fully covered by the CS AES Halt interface.
2) Whenever the SHA3 engine has received 832 bits of raw entropy, it triggers the compression of the current state. After that, additional raw entropy can again be XORed into the compressed state. The 832 bits correspond to the rate or block size for SHA3-384. This case is fully under control of the SHA3 engine. In the current version of ENTROPY_SRC, there is no point in the main FSM trying to request an AES halt for this because it simply doesn't know when the 832 bits are reached.

So what should be done if we want to keep and fix the CS AES Halt interface is to add the REQ/ACK interface to the SHA3 core itself or more precisely the SHA3 padding logic. This is not a big change and it doesn't have major impact on physical design or security. Earlgrey-PROD.M4 sounds right to me!
