### ISSUE TITLE
[clkmgr, sw] Clocks measurement counts are too tight

### ISSUE THREAD

**Issue by sha-ron** [lowRISC/opentitan#18037]
### Description

According to the spec:
https://opentitan.org/book/hw/top_earlgrey/ip/ast/index.html#clock-outputs
the precision of the clocks (including aon clock)  is +/-3%.
The theshold values configured in
https://github.com/lowRISC/opentitan/blob/master/sw/device/lib/testing/clkmgr_testutils.c#L131
don't take this into account so alert is issued.

**Comment by matutem** [comment]
Sha-ron, the variability of all clocks is 3%, but this may not be compounded by the aon clock, since I imagine that can easily be generated with a simple counter hooked to the IO clock for example. This means we would not need a variability of 5 or 6%.

I bring this up because I think we should set the thresholds as tight as the chip should deliver.

**Comment by sha-ron** [comment]
@matutem I am not sure I fully understand what you mean by "can easily be generated with a simple counter hooked to the IO clock for example", in the silicon, the Aon clock (and all other clocks) are generated by analog components that have a certain precision.

**Comment by matutem** [comment]
My concern is about the precision of the measurements: the AST says the variability is 3%, but if all clocks are separately generated there is no way to ensure that is the case because variability gets compounded, thus the 5% I mention above. It would be trivial to generate the AON clock with a counter from the IO clock (for example), and that would reduce or eliminate the compounding of variability. @Jacob-Levy and @msfschaffner may be able to comment as well.

**Comment by msfschaffner** [comment]
@matutem I don't think the AON clock can actually be generated by division of a fast clock, since that would likely consume more power than just generating a slow clock directly. 

@arnonsha @zi-v can you confirm whether the AON clock is generated separately as well so that we can set the variability thresholds correctly?

**Comment by zi-v** [comment]
as @msfschaffner mentioned, the AON clock has its own oscillator.
