### ISSUE TITLE
[sw/device] Discuss design of chip_info and lc_ctrl.HW_REV

### ISSUE THREAD

**Issue by dmcardle** [lowRISC/opentitan#18198]
### Description

I'm filing this issue (1) so we have a place to discuss some open issues with `chip_info` and (2) to unblock #18100.

CC: @cfrantz @alphan @moidx 

Context:
* https://github.com/lowRISC/opentitan/issues/14892
* https://github.com/lowRISC/opentitan/pull/18100#discussion_r1178031417

## 1. Should `chip_info` contain the commit hash?

I think the consensus is "yes". This should be useful when debugging malfunctioning chips.

## 2. Should `chip_info` contain [`lc_ctrl.HW_REV`](https://opentitan.org/book/hw/ip/lc_ctrl/data/lc_ctrl.html#hw_rev)'s CHIP_GEN and CHIP_REV?

  * Pros: This enables us to tag software binaries with the intended hardware target. It gives us more information than just the commit hash. It enables us to quickly verify that the binary is attempting to run on the correct target.
  * Cons: How does hardware versioning work? (@msfschaffner, please advise!)

    * Hardware revisions do not always need corresponding software changes, so `chip_info.hw_rev.chip_rev != lc_ctrl.HW_REV.CHIP_REV` does not necessarily indicate a problem.
  
    * @cfrantz points out that embedding HW_REV in ROM_EXT is unnecessary because different hardware targets will have different signing keys — we'd never even enter ROM_EXT on the wrong chip.

## 3. Should we put the `chip_info` in both ROM and ROM_EXT?

If `chip_info` contains a commit hash, I think ROM_EXT needs to have its own copy — it can be upgraded, so it may come from a different commit than ROM.

As @alphan pointed out, `shutdown` is used by both ROM and ROM_EXT, so if there's only one `chip_info` in ROM, we'll need to make `shutdown` always use the ROM's `chip_info`.

## 4. Alternatively, should we add a `hw_revision` field to the manifest?

> I might suggest that we add a `hw_revision` field to the manifest (e.g. usage_constraints?) to both announce the HW intended for this payload and provide a consistency check (@alphan, @moidx thoughts on this?)
> 
> It is _possible_ that a non-ROM_EXT payload would be compatible with different HW (e.g. an owner-level OS payload), but I think the ROM_EXTs are always going to have to be specialized to a particular chip (and the final line of per-chip enforcement is the signing keys).
> 
> _Originally posted by @cfrantz in https://github.com/lowRISC/opentitan/pull/18100#discussion_r1178223577_
>

**Comment by cfrantz** [comment]
1. Yes, `chip_info` should contain the commit hash.  _Which_ hash should it contain?  I'd say the hash at which the chip netlist was synthesized.
2. I'm ambivalent about this one as long as we decide what the consistency rules are between the lc_ctrl hw_rev register and the hw_rev copy in chip_info.
3. I'm going to quibble on terms.  `chip_info` is the information about the chip.  If we want information about software versioning, that information should be embedded somewhere else (e.g. the manifest or somesuch).  There is a perspective that the ROM isn't software: once we build the chip it can never change.  The ROM is hardware.
4. I'm also ambivalent about this one.  Signing keys are going to bind ROM_EXTs to their product.  I'm not sure how much value we add by putting a `hw_rev` into usage constraints.

**Comment by msfschaffner** [comment]
1. A note about @cfrantz's point: the final hash will likely be different from the open-source hash of the dropped netlist, since there are some netlist preparation steps that are done inside the secure domain (e.g. regenerating of netlist constants). Unless we have a way to publish that final hash value, there is no way to know what the "correct" hash is based on public resources on GitHub. 
2. We have a proposal regarding semantic versioning for individual IPs, but haven't really thought about extending this to the chip-level yet. I imagine GEN.REV can be used similarly MAJOR.MINOR, though. This essentially means that chips are at x.0, except for cases where respins with minor fixes are made.

**Comment by moidx** [comment]
Maybe then it is worth keeping two hashes:

1. Open source hash: used to reproduce the ROM. 
2. Closed source hash: used to reproduce the closed source gate level constants, etc.

**Comment by cdgori** [comment]
There's potentially going to be some tracking to be done to handle any post-synthesis manual ECOs that are done as well, no one likes to do them but they do happen.  Usually what is done is then some RTL is updated to match the ECO gate-level patch and it's formally equivalence checked to make sure the RTL matches the hackery that was done.

Is the intent to have the `chip_info` describe the "baseline" RTL that was fed to synthesis?  It's unclear to me if we would want to update the hash to correspond to the repo hash that includes the RTL-to-match-the-ECO-patch or if we have another way of tracking that some ECOs were applied (manually) - since the RTL-to-match-the-ECO-patch wasn't strictly the actual input to the synthesis tool, but it (should) be logically what is corresponding to what will be taped out.

(Basically are you trying to track the provenance or capture the functional intent with the hash?  Either is potentially valid.)

**Comment by moidx** [comment]
Please see hardware changes here: #18393

**Comment by moidx** [comment]
Since we are freezing the ROM for release, any further changes will have to be covered in a future milestone. Moving to  M2.5.Backlog. Please feel free to close if there are no further changes needed.

**Comment by dmcardle** [comment]
I think this is wrapped up, but before I close the issue, I'll summarize.

The `chip_info_t` struct now contains two pieces of information: the Git commit hash and a handy version field that enables readers to identify the format.  This is where we generate the value of `chip_info_t kChipInfo`:

https://github.com/lowRISC/opentitan/blob/396b5cba078cf35c707cb7a0d02e96e687fef857/util/rom_chip_info.py#L35-L42

We do *not* bake the hardware revision into `chip_info_t`, making it a slight misnomer (perhaps it's close enough because there's a sense in which the ROM is hardware). As a result of omitting the hardware revision, `kChipInfo` really indicates the functional intent rather than the provenance of the chip.

I won't attempt to summarize the details of hardware revisions — this is discussed in #18393.
