### ISSUE TITLE
[rv_dm] V2 + V2S tests back to 90% pass rate

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#18310]
V1 tests all pass 90% except
- [ ] rv_dm_csr_bit_bash: 4/5

V2 tests all pass 90% except
- [ ] rv_dm_stress_all: 0/50

V2S tests all pass 90% except the uncovered testpoints listed below
uncovered testpoints:
- [ ] sec_cm_bus_integrity
- [ ] sec_cm_lc_hw_debug_en_intersig_mubi
- [ ] sec_cm_dm_en_ctrl_lc_gated
- [ ] sec_cm_sba_tl_lc_gate_fsm_sparse
- [ ] sec_cm_mem_tl_lc_gate_fsm_sparse
- [ ] sec_cm_exec_ctrl_mubi
others covered by issues in effort estimation doc

>estimate 4

**Comment by GregAC** [comment]
Looking at the current nightly results (https://reports.opentitan.org/hw/ip/rv_dm/dv/latest/report.html) there are a number of failures in `rv_dm_csr_mem_rw_with_rand_reset` and `rv_dm_tap_fsm_rand_reset`. Both of these mix other tests with the `stress_all_with_rand_reset` sequence which is well known to break things as other sequences often cannot handle arbitrary design resets at any point. From a quick look at some failures the design looks to be functioning correctly and it's a UVM sequence that is acting oddly leading to the test failure (in a typical case the JTAG TAP will be continuously driven through the `test-logic-reset` state, the JTAG FSM is working correctly, the stimulus just isn't doing any other than that).

There are sporadic failures in `rv_dm_bad_sba_tl_access` and `rv_dm_autoincr_sba_tl_access`. A detailed investigation hasn't been conducted but these are likely testbench issues (a brief look at waveforms from failures shows the design working suitably given the stimulus). Furthermore neither related to critical rv_dm functionality.

There is no V2S related testing at present.

Given the V2.5 waiver the current regression results look acceptable for M2.5.2

@msfschaffner any other thoughts?

**Comment by msfschaffner** [comment]
Hi @GregAC, I think it is ok to postpone this item, given that the blocklevel is not even at V2 yet.
We make up for the missing blocklevel testing via our directed top-level tests that cover the use cases that we are interested in.

CC @moidx

**Comment by moidx** [comment]
Most of the test issues seem to be resolved. Moving to M5 carry over remaining work.

**Comment by rswarbrick** [comment]
I'm feeling pleased after hacking on the stress all test all day. And I just got 32 passes in a row on my work branch!

It should hopefully be sorted once #23744, #23746, #23747, #23750, #23752, #23754 and #23755 are merged.

The timing changes needed for the other two tests are merged, so hopefully they will be ok in the next nightly.

Still to do: implement 6 countermeasure sequences...

**Comment by rswarbrick** [comment]
I'm pleased to say that things are pretty solid now. The V1 and V2 tests all passed last night with a high sucess rate (all zero except for stress_all, which was 94%). As such, I claim that the "back to" bit of this issue is definitely addressed.

There is one missing V2 testpoint, which is tracked in #17034 (so doesn't really need tracking here as a duplicate).

Similarly, there are several V2S testpoints that are not implemented. This is tracked in #23721.

The uncovered testpoint items in the description are tracked in a different place. The success rate is over 90% as requested, so I'm happy that this can be closed.

(Note that this won't have an impact on milestone items: this is in the M5 milestone, the two items that we're punting to are on the same milestone)
