### ISSUE TITLE
[usbdev] Tests to V2(S) level 

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#18407]
### Description

From effort estimation exercise referencing the full DV testplan in [#10255](https://github.com/lowRISC/opentitan/issues/10255)

- [x] Csr_bit_bash at 80% (needs to be at 90%+) [2d]
- [x] Tl_intg (V2S tests failing) [1d]

>estimate 12

**Comment by msfschaffner** [comment]
Is this something we're still trying to fix for M2.5.1 at the block-level?

**Comment by alees24** [comment]
I've had a look at a few of these failing tests and see only testbench issues so far:

Failing every time:
- usbdev_stress_all(_with_rand_reset) does not have a virtual sequence; "not registered with factory"
- usbdev_smoke throws a uvm_error saying 'FIXME' because there simply isn't any tb code
- usbdev_sec_cm - drives (almost?) entirely Xs over the T-L connection for the duration; cursorily does not appear sensible/functional.

Seed-dependent timeouts:
- usbdev_csr_bit_bash - timeout for one or more seeds (726935604) but there seems nothing wrong with the T-L/register behavior as far I can see.
- usbdev_intg_err - likely the same as above

If somebody with more CSR/T-L experience can run the latter and investigate, it'd be helpful; doesn't require USB(dev) knowledge. I have to prioritize the suspend/resume/wakeup testing in case it shows up any issues.

@johngt

**Comment by johngt** [comment]
@GregAC  / @hcallahan-lowrisc ; For the bullet points that look like stub items or incomplete Todos / fixmes - can you suggest workarounds if time (I suspect there is no underlying issue but @alees24 to comment)
* usbdev_stress_all(_with_rand_reset) does not have a virtual sequence; "not registered with factory"
* usbdev_smoke throws a uvm_error saying 'FIXME' because there simply isn't any tb code

For usbdev_sec_cm this seems like it needs more investigation
The other errors seem to be lower risk from what @alees24 has suggested in the comment above. @hcallahan-lowrisc might be able to help with the T-L experience part of this?

**Comment by GregAC** [comment]
I don't think we need to look at this further for M2.5.1. usbdev is already known to be effectively un-tested at the block level, so the small amount of framework and auto-generated code that does exist for the block-level DV not functioning correctly is of little consequence.

**Comment by alees24** [comment]
> estimate 8

**Comment by msfschaffner** [comment]
@johngt @alees24 how much of this are we still planning to do for M2.5.2?

**Comment by alees24** [comment]
As above, not progressed yet, and not prioritized because of suspend-resume investigations.

**Comment by mundaym** [comment]
Closing as both tests are passing at 100%.
