### ISSUE TITLE
[test-triage] chip_sw_lc_ctrl_volatile_raw_unlock timeout Job ID

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#18466]
### Hierarchy of regression failure

Chip Level

### Failure Description

```
0.chip_sw_lc_ctrl_volatile_raw_unlock.3920870537
Log /container/opentitan-public/scratch/os_regression/chip_earlgrey_asic-sim-vcs/0.chip_sw_lc_ctrl_volatile_raw_unlock/latest/run.log

  Job ID: smart:0e37e9ac-4749-41aa-b7e4-1df3547f4c7e
```

### Steps to Reproduce

- GitHub Revision: [bc163b70f](https://github.com/lowrisc/opentitan/tree/bc163b70f077a821f16aeeaafa721f1c10a919bc)
- dvsim invocation command to reproduce the failure, inclusive of build and run seeds:
  ./util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i chip_sw_lc_ctrl_volatile_raw_unlock --build-seed 488598207 --fixed-seed 3920870537 --waves fsdb

### Tests with similar or related failures

- [ ] chip_sw_lc_ctrl_volatile_raw_unlock

**Comment by johngt** [comment]
Note - may be resolved by https://github.com/lowRISC/opentitan/issues/18246

**Comment by abdullahvarici** [comment]
I couldn't generate the failure locally with the commit number and seed defined [here](https://reports.opentitan.org/hw/top_earlgrey/dv/latest/report.html). This is the command I used: `./util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i chip_sw_lc_ctrl_volatile_raw_unlock --build-seed 488598207 --fixed-seed 3920870537 -pi 1`. The test passes on my machine. Maybe it is failing on nigthlies due to a tooling issue because the failure message in the nightlies does not mean anything to me: "Job ID: smart:0e37e9ac-4749-41aa-b7e4-1df3547f4c7e".

**Comment by moidx** [comment]
I will modify the timeout. I think it was too short for the build to complete in the VM used in the nightly configuration.

**Comment by moidx** [comment]
Fixed by https://github.com/lowRISC/opentitan/pull/18476
