### ISSUE TITLE
[i2c] Clock speed mismatch

### ISSUE THREAD

**Issue by johngt** [lowRISC/opentitan#18492]
Promoting this issue as this was captured in [I2C test plan](https://github.com/lowRISC/ot-discrete-eg/issues/11) previously.
During testing of power monitor, a mismatch between the expected clock timings and those captured has been observed.

This was using a USB Logic analyser. Possible that there is a setup or test issue. Capturing here for more full discussion.

**Comment by marnovandermaas** [comment]
My understanding of this issue is that the timing parameters are calculated in a conservative way. So if you say the bus clock should be 100 kHz it gives you the timing parameters that make sure you do not *exceed* this frequency. We need to document this discrepancy.

**Comment by a-will** [comment]
https://github.com/lowRISC/ot-discrete-eg/issues/11#issuecomment-1575126104 explains where some of the mismatch with expectation comes from.

In short, the round-trip latency of ~3 cycles for the IP's output change to observing responses adds to `thigh` time. Due to the much larger peripheral clock period on the FPGA, the effect here is much more noticeable.

Why is there a round-trip? It's because the I2C IP must monitor for clock stretching, so it needs to wait to see SCL go high before counting out high time.

**Comment by moidx** [comment]
Moving to M2.5.3 as this is something that we should capture in the programming guide as part of the datasheet release.

**Comment by marnovandermaas** [comment]
The documentation of the speed mismatches that I am aware of are captured in this PR: https://github.com/lowRISC/opentitan/pull/18964

**Comment by msfschaffner** [comment]
@jesultra @a-will what is your opinion on this discrepancy - are we ok with the documented behavior, or do we need to optimize this behavior for PROD?

**Comment by a-will** [comment]
I'd recommend at least getting rid of the double-counted t_fall, since that is just a quick parameter update. From https://github.com/lowRISC/opentitan/issues/18958

I forget if the problems were more than that + the 3 added cycles to t_high from needing to detect clock stretching (https://github.com/lowRISC/opentitan/issues/18962), but it's a considerable reduction in speed for fast-plus if both effects are present.

For a back-of-the-envelope calculation for fast-plus, we take 24 MHz and target a minimum of _0.26 us_ t_high, _0.5 us_ t_low, and _0.12 us_ for t_rise and t_fall. Since we'll have to round up all factors, that leaves us with counts of 7, 12, 3, and 3 cycles, respectively, resulting in a rate of 24 MHz / (7 + 12 + 3 + 3) = 960 kHz.

If we don't add some speculative counting for the clock stretching case, we add 3 cycles to t_high, resulting in a drop to ~857 kHz. If we also don't fix the handling of t_fall, that doubles (adding 3 more cycles in this case), dropping further down to ~774 kHz.

**Comment by marnovandermaas** [comment]
This issue is now only open to determine whether there is more affecting the clock speed than just the fall time being counted twice (https://github.com/lowRISC/opentitan/issues/18958) and the clock stretching affecting the high time (https://github.com/lowRISC/opentitan/issues/18962). Once we are happy that that is not the case, we can close this issue.

**Comment by andreaskurth** [comment]
> This issue is now only open to determine whether there is more affecting the clock speed than just the fall time being counted twice (https://github.com/lowRISC/opentitan/issues/18958) and the clock stretching affecting the high time (https://github.com/lowRISC/opentitan/issues/18962). Once we are happy that that is not the case, we can close this issue.

#18958 should get resolved by #21765 and #18962 by #21813. Once those PRs are merged, which tests are planned to check that this issue has been resolved, @marnovandermaas?

**Comment by marnovandermaas** [comment]
According to @hcallahan-lowrisc he sees "clock frequencies within the 4-cycle possible float". We can double check that the frequencies are as expected on FPGA. Maybe @engdoreis can do this if he has time?

**Comment by andreaskurth** [comment]
Okay, then since the known issues are tracked separately and what remains here is 'double checking', let's move this from M2 to M4.

**Comment by marnovandermaas** [comment]
Sounds good to me.

**Comment by engdoreis** [comment]
@hcallahan-lowrisc and I tested the master branch on the FPGA CW340 board and measured with the Logic analyser.
The clock now matches at 100Khz, and we noted a difference at 400Khz and 1Mhz that can be explained by the fact that the peripheral clock is not high enough on the FPGA.  
I will repeat the test again and post the results here before closing the issue.

**Comment by andreaskurth** [comment]
Thanks, @engdoreis! Do you already have the results from repeating the test?

**Comment by engdoreis** [comment]
These are the results:
|configured|measured|registers values|
|:-|:-|:-|
|100kHz|98.3kHz|fall=1, rise=3, hi=28, lo=29|
|400kHz|375kHz|fall=1, rise=3, hi=4, lo=8|
|1000kHz|599kHz|fall=1, rise=3, hi=2, lo=4|

**Comment by andreaskurth** [comment]
Thanks @engdoreis :+1:

@a-will: Does the timing at 100 kHz meet expectations / specification, and does the hypothesis that the faster frequencies are off solely due to the relatively slow peripheral clock on the FPGA hold in your view? If so, I suggest we close this.

**Comment by a-will** [comment]
Those measurements match the register values within a small tolerance, so there is no longer a mismatch.

The particular choice of register values is affected by the FPGA's 6 MHz base rate.
