### ISSUE TITLE
[crt] Make the build system aware that English Breakfast does not have bitmanip

### ISSUE THREAD

**Issue by pamaury** [lowRISC/opentitan#18683]
### Description

@luismarques wants to [enable](https://github.com/lowRISC/opentitan/pull/18413) bitmap in the [toolchain ](https://github.com/lowRISC/crt/commit/e202d6a428aec1349dd86768407efe785d4db456).
However, English Breakfast does not have bitmanip enabled to keep it small. This creates an issue because it makes every test on this device fail. The goal of this issue to discuss how to fix this.

I had a look at how this is handle and here is a suggestion, probably based on a very insufficient understanding of the CRT:
- create a new constraint for the cpu that does not bitmanip, e.g. `@platforms//cpu:riscv32_nobitmanip` (or alternatively keep `@platforms//cpu:riscv32` and add `@platforms//cpu:riscv32_zb` for bitmanip)
- have the CRT define two devices, one for each cpu (we just need to change the `ARCHITECTURE`)
- in `rules/opentitan.bzl`, create a config option to distinguish between the two CPUs and choose `OPENTITAN_CPU` based on that, make the necessary changes related to that (hopefully none)
- edit `hw/top_englishbreakfast/util/prepare_sw.py` and `ci/scripts/run-english-breakfast-verilator-tests.sh` to use this config to select the CPU without bitmanip

This is a bit hackish admitedly, but that's because English Breakfast is a hack that is not properly integrated into the build system.

**Comment by pamaury** [comment]
Tagging @vogelpi would can answer your first question.

Question about `//sw/device:is_english_breakfast` (which I didn't know): it seems to set a `copt` option. Why do the two scripts that I mentioned in the issue don't use it and pass the `copt` config directly?

**Comment by vogelpi** [comment]
At least today, the prime application of English Breakfast is to have a minimal top-level for SCA evaluation on small FPGAs. Small FPGAs are much better for these kind of evaluations because:
1. Stronger signal, i.e., less noise. Meaning fewer traces need to be captured for analysis.
2. More reproducible results over bitstreams due to less P&R variation.
3. Much faster turn around time: FPGA build time for the CW305 is 15min compared to 1.5 - 3 hours for the CW310 (depending on overall utilization of the FPGA). This is very important to debug/fix and optimize countermeasures efficiently.

A minimal top-level is important for that because:
1. The FPGAs are smaller
2. The fuller the FPGA gets, the less meaningful / harder to reproduce results get. We usually try to not go beyond 70% utilization. I've recently worked very hard to get the utilization down again to that level.

Bitmanip is disabled exactly for that reason. It maps very badly to FPGA: Taking the core without PMP as a baseline, the area increase on ASIC is roughly 25%, on FPGA it's 60%.

Please let's not enable it on englishbreakfast.

**Comment by cfrantz** [comment]
Sounds good.  I needed to understand the reasoning to make sure that adding the extra sub-architecture complexity to the build system is the right solution.

**Comment by pamaury** [comment]
I believe this issue can be closed?

**Comment by vogelpi** [comment]
I think so yes. QQ: from the linked toolchain PR it's not entirely clear whether the toolchain now supports the unratified extensions or "just" the ratified ones (zba, zbb, zbs, zbc). Do you know what the status is?

**Comment by pamaury** [comment]
I am not sure to be honest, I think @luismarques would be the best person to answer that.

**Comment by luismarques** [comment]
> I think so yes. QQ: from the linked toolchain PR it's not entirely clear whether the toolchain now supports the unratified extensions or "just" the ratified ones (zba, zbb, zbs, zbc). Do you know what the status is?

All toolchains versions should support unratified bitmanip. The older ones support it because there was upstream support. The most recent ones support it because I backported that support.

**Comment by vogelpi** [comment]
Fantastic, thanks for clarifying @luismarques !
