### ISSUE TITLE
[top-level] Clarify uncalibrated IO/SYS/AON clock frequency test

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#18848]
### Description

This closed-source test needs some clarification:

What is the purpose of the test? We have an external clock, which should enable clock calibration, so it is not clear what is the use of running completely uncalibrated frequency measurements.

Are all clocks meant to be uncalibrated (including AON)? What is the pass/fail criterium?

**Comment by sha-ron** [comment]
The purpose is to check the HW functionality until the clocks are calibrated or until we can switch to external clock 
The most important thing is to check that we can move from raw to unlock0 LC state when all four clocks (AON, IO, System (MAIN), USB)  are un-calibrated, we are supposed to have manuf_cp_unlock_raw test.
Then in unlock0 LC we need  to check we can switch to external through clock manager.
(external clock should be selected by clkmgr, because when it is selected by lc ctrl only IO clock is derived from the external clock).
Another scenario is when we start from prod lc and until we see the clock are calibrated (indicated by AST init_done output).

**Comment by matutem** [comment]
Referring to https://docs.google.com/spreadsheets/d/18Aj0hV44XGYGRlqnSZo6pEcVuZy7n7qNnPRHmPlHrQ4/edit?pli=1#gid=178420566, I think the check we can move from raw to unlock0 is the subject of line 6 in the Tasks tab, and switching to external clock is the subject of line 21. In any case, the task in line 22 explicitly refers to clock frequency test, so I think we can conclude it is invalid.

**Comment by matutem** [comment]
Clock frequencies cannot be measured if the clocks are not calibrated, because until ast_init is done (at which point the clocks should be calibrated) the clkmgr clock frequency measurement hardware is disabled.

Regarding the Nuvoton tasks sheet mentioned above, I think we need to have a better description of the tasks, preferably as an issue?

Regarding a test that moves from raw to unlock0 LC state when all four clocks (AON, IO, System (MAIN), USB) are un-calibrated, is this a missing test? Line 6 seems to address the volatile RAW -> TEST_UNLOCKED0 transition, and the test seems to have been merged in https://github.com/lowRISC/opentitan/pull/18276.

I think the tests to transition to external clock is  covered by the various chip_sw_clkmgr_external_clk_src_for_sw_* tests.

Regarding a test with uncalibrated clocks starting from prod life cycle and the ROM code runs until we see the clock are calibrated (indicated by AST init_done output), all tests go through this specific transition, so I don't see the need for additional tests.

**Comment by matutem** [comment]
The description in line 22 of https://docs.google.com/spreadsheets/d/18Aj0hV44XGYGRlqnSZo6pEcVuZy7n7qNnPRHmPlHrQ4/edit?pli=1#gid=178420566 is incorrect. Once that is updated I will close this issue. Makes sense?

**Comment by msfschaffner** [comment]
The test description can be found here:
https://github.com/lowRISC/opentitan/blob/40ef2cae3b3955acd586f216c01b8010a0f0f2f2/hw/top_earlgrey/data/chip_testplan.hjson#L3510-L3533

I am closing this now, since I think this is addressed - but please reopen if something is still unclear.
