### ISSUE TITLE
[verilator] Reset behavior different between verilator and DV

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#1884]
Hey all,
I'm working on a chip level reset manager in #1752 and noticed the reset behavior in verilator is different from DV, and this causes verilator to fail everything with the new reset change. 

My specific failure revolves around the default privilege level.

Specifically, before the change, it looks like below. 
![passing](https://user-images.githubusercontent.com/1026250/78320091-8723e780-751d-11ea-9591-126fb5b260fa.png)

You can see that the privilege doesn't actually reset until a clock pulse shows up.  But this works out okay because this is still way before anything runs.  

In my modified version, the input `rst_ni` is stretched and synchronized to the destination clock, and we end up with something that looks like below (the stretching is basically some reset filtering done while assuming the input is coming from an analog comparator).

![fail](https://user-images.githubusercontent.com/1026250/78320188-bdf9fd80-751d-11ea-8de0-4388b7b11fa6.png)

The clock does not resume until after the reset because it is dependent on a `core_busy` signal that resets to 0.  So the clock gate does not release until after reset releases and the busy has a chance to change to 1, allowing clocks to flow through.  However now `priv_lvl_q` is completely wrong, and stays "unprivileged" until much later in the simulation when there is a transaction made to the csr block.  This causes a privilege error and every single verilator C tests fails.

What do we think is the right fix here..? I can probably make core_busy_q reset to '1', but I don't think that's the intent of all this. My understanding of how verilator works is that it is mostly synchronous, so does this mean without a clock edge, even the reset signal has no impact?

Sorry I don't really know who the best person to ask, so for now I'm blasting this out while I experiment with other things.

**Comment by tjaychen** [comment]
ah... maybe i just need to pulse the reset twice... it looks like this was the original way. I'll give that a try.

**Comment by tjaychen** [comment]
Okay, extending the reset delay seems to have done the trick...this is still a weird fix though...with reset high from time 0...it technically means nothing inside rstmgr was reset...it just so happens that a default value of 0 (i guess this is the unknown value) works out? 

I'll leave it be for now and close this issue.  If anyone has a better suggestion on how this should be fixed, do let me know.

**Comment by cdgori** [comment]
> Okay, extending the reset delay seems to have done the trick...this is still a weird fix though...with reset high from time 0...it technically means nothing inside rstmgr was reset...it just so happens that a default value of 0 (i guess this is the unknown value) works out?
> 
> I'll leave it be for now and close this issue. If anyone has a better suggestion on how this should be fixed, do let me know.

I have a weird memory of some class of event-driven simulator bugs at time-zero, where signals going X->0 had a different behavior than X->1.  It might have been that one of those cause an event to propagate and the other didn't?  Not sure that you are seeing exactly this and the memory is really foggy for me, but maybe it's something like this?  What you described definitely feels like a simulator/tool issue to me.

**Comment by vogelpi** [comment]
Ibex requires a negative edge on `rst_ni` is required to actually reset `priv_lvl_q` to M-mode.

I suspect that with the new reset manager, Ibex never gets this negative edge in Verilator because Verilator does not know X. In this case it is mapped to 0 (but I have also seen non-zero values occuring in registers when writing X).

The reason it worked before but not any more is probably because of the synchronizer flops in the new reset manager: These are reset to 0 and it will take at least 2 cycles until the 1 that is fed in occurs at the output. But according to your waves, by that time, the reset becomes active. This means the synchronizer flop never outputs a 1 and thus no negative edge is seen on the reset. 

Extending the reset delay is the correct workaround here. We could also extend the default reset delay in our Verilator framework to be greater than the number of synchronizer flops. But since the framework lives in the Ibex repo and is vendored into OpenTitan, extending the reset delay in just in OpenTitan seems more suitable.

**Comment by tjaychen** [comment]
@vogelpi thanks for the explanation, but i think what you're saying, are also some of my concerns.

If we require a negedge to reset, it means until that negedge shows up, we are effectively in 'x', which just falls to however verilator interprets it, (apparently 0) is that right?

So my worry is that I happened to have logic that relied on the reset value being non-zero to release a reset, wouldn't this get forever stuck? (let's say a reset count value of 5 that needed to be compared).  My point is that if I understood this correctly, this seems very fragile.  I know there may not be a better way, but I was more or less just thinking out loud.

**Comment by vogelpi** [comment]
> If we require a negedge to reset, it means until that negedge shows up, we are effectively in 'x', which just falls to however verilator interprets it, (apparently 0) is that right?

Yes, I think so.
> 
> So my worry is that I happened to have logic that relied on the reset value being non-zero to release a reset, wouldn't this get forever stuck? (let's say a reset count value of 5 that needed to be compared). My point is that if I understood this correctly, this seems very fragile. I know there may not be a better way, but I was more or less just thinking out loud.

I am not sure I get your point. The problem is not about the release of the reset, but about the assertion of the reset (this gives the required negedge). In the new rstmgr design, there reset forwarded to the core is synchronized to the clock using two flops.

At simulation start in Verilator, we get (this is my assumption, I can't verify it):
Cycle 0: Main simulation reset is not active. Thus the synchonizer flops are actually `2'bXX`. Verilator maps these to 0. While other simulators keep it as X.
Cycle 1: Main simulation reset is not active. The synchronizer flop is `2'b1X` (you feed in a `1'b1`). In Verilator it is `2'b10`.
Cycle 2: Main simulation reset becomes active. The synchronizer flop is `2'b00` in any simulator.

This means for simulators supporting X, we get a negedge from X to 0 in Cycle 2 whereas for Verilator the reset just remains 0 (no negedge).

To be on the safe side, we should make sure that before the reset is propagated, it is at least high for one clock cycle (to get the negedge). This can be done 1) by extending the reset delay (maybe in all simulators, to also catch different behavior/interpretation of X -> 0), or  2) by changing the logic.

For 2), I don't know if there is a good solution to it and if this matters in practice/outside of simulation.

I am reopening the issue to allow others to chime in.

**Comment by tjaychen** [comment]
thanks for the discussion! i'll close this one for now.
