### ISSUE TITLE
[entropy_src/dv] Verify rng_fips_o

### ISSUE THREAD

**Issue by andreaskurth** [lowRISC/opentitan#18842]
`rng_fips_o` signals the noise source whether FIPS-compliant entropy is required. Entropy Source currently drives this to the inverse of Bypass Mode (i.e., 0 if bypass mode is enabled and 1 if bypass mode is disabled). AFAIK we have not specified `rng_fips_o`, and the current implementation seems sensible. We don't verify this, though.

The chance that a bug is lurking here is near zero, so I'm assigning this to V3.

**Comment by vogelpi** [comment]
Thanks for flagging this and creating the issue @andreaskurth . As you say, we haven't specified `rng_fips_o` and the current implementation seems sensible.

Since the enablement of FIPS mode or boot-time/bypass modes is a bit tricky, I did look at the RTL to convince myself. What we have is:
```sv
  assign es_bypass_mode = (!fips_enable_pfe) || (es_bypass_to_sw && es_route_to_sw);

  // send off to AST RNG for possibly faster entropy generation
  assign rng_fips_o = !es_bypass_mode;
```
So whenever we set `FIPS_ENABLE` to true, `rng_fips_o` will be high unless `ES_TYPE` and `ES_ROUTE` are both set. Setting both `ES_TYPE` and `ES_ROUTE` is documented as resulting in non-FIPS qualified entropy independent of `FIPS_ENABLE` field. So all is fine.

It would have been very bad if Entropy Source could be configured to deliver FIPS qualified entropy at the output while at the same time having `rng_fips_o` being low. But I am now convinced this cannot happen.

**Comment by vogelpi** [comment]
We have reworked the generation of this signal with https://github.com/lowRISC/opentitan/pull/21369 for improved flexibility. The signal now directly comes out of the configuration register. I am not sure whether we model this, or if modeling/verification is overkill now.

**Comment by vogelpi** [comment]
Discussed with @h-filali , we should add an SVA for this.

**Comment by vogelpi** [comment]
Moving to M7 as we have more pressing items to take care of.
