### ISSUE TITLE
[sw, dif] Error code enum per function

### ISSUE THREAD

**Issue by silvestrst** [lowRISC/opentitan#1911]
Yesterday working on adding error codes to my UART DIF, I have ran into a potential issue with having error codes per function.

Consider the following setup:
header file

```
typedef enum dif_uart_init_error {
  kDifUartInitErrorNone = 0,        /**< Success. */
  kDifUartInitErrorInvalidArgument, /**< Input parameter is not valid. */
  kDifUartInitErrorBadConfig,       /**< Configuration is not valid. */
} dif_uart_init_error_t;

dif_uart_init_error_t dif_uart_init(mmio_region_t base_addr,
                                    const dif_uart_config_t *config,
                                    dif_uart_t *uart);

typedef enum dif_uart_config_error {
  kDifUartConfigErrorNone = 0,        /**< Success. */
  kDifUartConfigErrorInvalidArgument, /**< Input parameter is not valid. */
  kDifUartConfigErrorSomething1,
  kDifUartConfigErrorSomething2,
  kDifUartConfigErrorSomething3,
  kDifUartConfigErrorSomething4,
} dif_uart_config_error_t;

dif_uart_config_error_t dif_uart_configure(const dif_uart_t *uart,
                                           const dif_uart_config_t *config);
```

source file

```
static dif_uart_config_error_t uart_configure(const dif_uart_t *uart,
                                              const dif_uart_config_t *config) {
  if (config->baudrate == 0 || config->clk_freq_hz == 0) {
    return kDifUartConfigErrorBadConfig;
  }
  if (something1) { return kDifUartConfigErrorSomething1 };
  if (something2) { return kDifUartConfigErrorSomething2 };
  if (something3) { return kDifUartConfigErrorSomething3 };
  if (something4) { return kDifUartConfigErrorSomething4 };
...

dif_uart_init_error_t dif_uart_init(mmio_region_t base_addr,
                                    const dif_uart_config_t *config,
                                    dif_uart_t *uart) {
  if (uart == NULL || config == NULL || base_addr.base == NULL) {
    return kDifUartInitErrorInvalidArgument;
  }

  uart->base_addr = base_addr;

  // You can do it this way, but then you loose some error information
  // that has been returned from the static config function.
  if (uart_configure(uart, config) != kDifUartConfigErrorNone) {
    return kDifUartInitErrorBadConfig;
  }

  return kDifUartInitErrorNone;
}

dif_uart_config_error_t dif_uart_configure(const dif_uart_t *uart,
                                           const dif_uart_config_t *config) {
  if ((uart == NULL) || (config == NULL)) {
    return kDifUartInitErrorInvalidArgument;
  }

  return uart_configure(uart, config);
}
```

So basically what error codes do you make a common static function return, if you require the full set of error codes that this function can produce. And how do you then handle it in the public DIF caller functions to return the error codes to the external caller (how do you map one set of error codes to another)?

At the moment I just do this:
```
  // You can do it this way, but then you loose some error information
  // that has been returned from the static config function.
  if (uart_configure(uart, config) != kDifUartConfigErrorNone) {
    return kDifUartInitErrorBadConfig;
  }
```

**Comment by silvestrst** [comment]
@lenary @gkelly @mcy @alphan @jon-flatley

**Comment by silvestrst** [comment]
UART is not a best example, being a simple device, I expect that these issues may arise in more complicated devices - such as USB.

Just decided to share my findings, so that you guys could give a second, third, ... opinion :)

**Comment by lenary** [comment]
The approximate guidance is "Functions that can fail in the same way should share error enums" (sorry I have not had time to write up the guidance on error codes yet, I'll try put that on the list for today).

My approach for this particular issue would be that both `dif_uart_init` and `dif_uart_configure` would return `dif_uart_config_error_t`.

**Comment by mcy** [comment]
> So basically what error codes do you make a common static function return, if you require the full set of error codes that this function can produce. And how do you then handle it in the public DIF caller functions to return the error codes to the external caller (how do you map one set of error codes to another)?

Sam already explains that the guidance is different, anyway... but I think this is a very good illustration as to why per-function error enums is kind of a bad idea.

**Comment by silvestrst** [comment]
`My approach for this particular issue would be that both dif_uart_init and dif_uart_configure would return dif_uart_config_error_t.`

I guess that's why initially I was in favour of per DIF error codes, as opposed to per function. As this feels slightly hacky and somewhat confusing. I agree with @mcy on this one, it worked very well for pinmux, but I am afraid that it will lead to some headache down the line with more complicated drivers.

**Comment by mcy** [comment]
I mean, I think the right answer is "write as few enums as possible but as many as you need". C has almost no room for abstraction boundaries, so we aught to just work with what we've got...

**Comment by lenary** [comment]
So I have no problem with what is done in `dif_gpio.h` right now where all the functions are largely similar and can all fail in the same way, so all share a single result enum (in this case `dif_gpio_result_t`). This probably makes sense for a lot of functions that are just prodding registers and have no real way of failing.

I am keen that every return code enums (I'm being specific and calling them "return code enums", because "success" is not an error) include a variant for "invalid arguments", and potentially another for "general error" (which is already required for enum switches). 

A good example where this simple enum is not good enough is `dif_uart_init` and `dif_uart_configure` (as pointed out above) which both can return extra errors, to say "you tried to set an invalid NCO". This would mean `dif_uart.h` had two error enums:
- one for most functions (like `dif_gpio_result_t`)
- one for `_init` and `_configure` (which is the same with one extra error code for a bad configured NCO value).

Looking at other DIFs:
- PLIC - I have no issue with all the functions sharing a single result enum, as they all can fail in the same way (either badarg, or succeed)
- rv_timer - this seems to follow what I'm proposing.
- spi_device - this seems to follow what I'm proposing.
- pinmux - i think you can deduplicate some of the return code enums here - `dif_pinmux_outsel_set_error_t` and `dif_pinmux_insel_set_error` seem to fail in the same way, I think?
- padctrl - this seems to follow what I'm proposing.
- hmac - this seems to follow what I'm proposing.

---

My instinct would be to choose standard names and suffixes for anything we mandate. I realise this could be controversial.

I think the naming scheme I'm most satisfied with is in `dif_gpio.h`:
- the enum type is called `dif_<ip>_result_t` or if more specific, `dif_<ip>_<operation>_result_t`. 

Then the normal enum constant prefix rules apply, and I suggest the following:
- the "invalid argument" constant is named `kDif<ip><operation?>ResultInvalidArgument`
- the "general error" constant should be named `kDif<ip><operation?>ResultGeneralError`. 
- success should probably follow GPIO and go with `kDif<ip><operation?>ResultOk` (we seem to not capitalise initialisms in enum names, see `Dif`).

---

I'm keen to hear opinions on this proposal. I plan to discuss it at the software meeting. I think the fundamentally important part is the first one - that we use simple enums, and can share them between DIFs when two functions can fail in the same manner - exactly what we name the constants is not going to fundamentally change how they work or how easy they are to use.

I'm especially keen to hear where we think this either won't allow us to do what we need to with DIFs, or will return too much information (a concern we may have to be mindful of if preserving some security properties, I think @cdgori may have an feedback about this).

Comments welcome! I'd like to try and settle this at the latest on the 15th April, so that we can implement the consensus we find.

**Comment by mcy** [comment]
@lenary This sounds great! It's basically what I've been thinking the right answer is lately. A few comments:
- I think we should require that the `Ok` variant always have the representation `0`; I'd like things like CHECK macros and such to "just work" with result enums.
- The names of these enums are kind of gigantic and can be unpleasant to read or write. I think that, especially in the per-operation case, the `Result` portion should not be included. Similarly, I think we should pick shorter names for `InvalidArgument` and `GeneralError`: for the former, I've been using `BadArg`.
- I don't quite understand why we need `GeneralError`? If anything, I think it's a not a good name; I would have gone with `Unknown` to specify that something bad and unspecified happened.

>  and can share them between DIFs when two functions can fail in the same manner

I think the important observation you've made is that there are two kinds of enums: the "common" enum, which is the triple "Ok", "BadArg", and "Unknown", and specific enums which include the common enum as an ancestor. If we agree that this encompasses all errors, I think it might be a good idea to create
```
enum dif_result { kDifOk, kDifBadArg, kDifUnknown, };
```
in `errors.h` or something, and require that all functions return either `dif_result_t` or have a prelude like
```
enum dif_ip_op_result {
  kDifIpOpResultOk = kDifOk,
  // ... repeat for other variants
}
```
(This prelude could easily be made into a simple macro.)

I don't think this last bit needs to be something we decide on now, but I think it squarely solves our recurring enum inheritance problems.

**Comment by alphan** [comment]
@lenary, sounds great and I support your proposal. I experimented with several options while writing the GPIO DIF lib and converged to what we have now since IMHO it was the most reasonable approach for that DIF.

@mcy,
1. I think defining a shared `dif_result_t` and requiring all functions to either use it directly or use the values of its variants to define their enums would be nicer. (Basically, what you are suggesting towards the end of your message)
2. I like `BadArg`, shorter than `InvalidArgument` and essentially means the same thing. The length of the names is due to our `enum` naming conventions though.
3. +1 regarding the need for `GeneralError`, maybe because I haven't seen a compelling use-case in our code yet. But, if we need it, I would prefer having the word "error" somewhere in the name instead of just "unknown".

**Comment by mcy** [comment]
> The length of the names is due to our enum naming conventions though.
I'm suggesting waiving them in this case, to be clear. Given that `kDif<ip>` already introduces a per-file namespace, I don't see a reason to add boilerplate past that.

**Comment by silvestrst** [comment]
Thank you @lenary for the detailed description of how you see the error enums. Thank you @mcy and @alphan for your suggestions. 

```
in errors.h or something, and require that all functions return either dif_result_t or have a prelude like

enum dif_ip_op_result {
  kDifIpOpResultOk = kDifOk,
  // ... repeat for other variants
}
(This prelude could easily be made into a simple macro.)
```

I like this idea, I think @lenary have played around with similar concepts, but maybe not exactly what you were proposing? @lenary what do you think of this? I think initially we didn't want common "dif_errors.h" file, but it does make sense if it only defines small subset of common arguments and a convenience MACRO?

>  I'd like things like CHECK macros and such to "just work" with result enums.

I personally don't see much us ein `CHECK` macros, it simply wraps `if (var != success)`, or am I missing something?

> The names of these enums are kind of gigantic and can be unpleasant to read or write. I think that, especially in the per-operation case, the Result portion should not be included. Similarly, I think we should pick shorter names for InvalidArgument and GeneralError: for the former, I've been using BadArg.
> 
> I don't quite understand why we need GeneralError? If anything, I think it's a not a good name; I would have gone with Unknown to specify that something bad and unspecified happened.

* I agree, maybe `result` portion could be dropped?
* I also found that without shortening something like "...InvalidArgument" these enums grow way too large, I agee with BadArg.
* I also think that `GeneralError` is maybe not needed, as for `switch` default case we can use `BadArg`?

**Comment by mcy** [comment]
> I personally don't see much us ein CHECK macros, it simply wraps if (var != success), or am I missing something?

I think that it's pretty painful to have to write `if (var != success) { trivial control flow }`. Rust has `?`, and a number of Google C++ projects have similar macros (usually called RETURN_IF_ERROR).

CHECK_OK is also useful, because things that use DIFs almost always want to immediately crash if they get back BadArg or such (as I brought up when we originally discussed e.g. null checking).

**Comment by silvestrst** [comment]
Well I see your point, but I personally don't find it painful, and it is more readable this way.

I guess I am a bit skeptical about macros in general. In one project that I have worked on in the past there were more macros than grains of sand in Sahara desert. Some of them had trivial flow, then the others not so much, in the end it was hard to remember and required looking around the source code to get an idea.

I guess just slightly paranoid that we don't rely on convenience macros a bit too much.

**Comment by lenary** [comment]
Having discussed this at the software meeting, I will begin to prepare a PR to update the DIF style guide.

This will encompass:
- A better explanation of the expected use of "general error" (and how it differs from "invalid argument"), based existing code in the repo.
- An allowance of `dif_<ip>_result_t` for most functions (which is just OK, invalid argument, and "general error")
- the "OK" variant will always have value 0 (this is a lot simpler than macros for inheritance, which I do feel are more complex than we need).
- A relaxation on the requirement that `result` is in the enum constant names, as well as a shortening of each of the variant suffixes - to `Ok`, `BadArg` and maybe just `Error`? I'm not sure `Unknown` is exactly right, but I can see `GeneralError` being more wordy than necessary.

At the moment, I do not propose to suggest adding a DIF error header, though we can revisit this later.
