### ISSUE TITLE
[sw, dv] Avoid CSR write reordering

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#19234]
### Description

Some CSRs in the device are written to registers in the AON clock domain, so they go through synchronizers. If there is a couple of CSR writes done sufficiently close in time, it is possible they end up being performed in the opposite order they were issued, which can cause unexpected results.

One such instance is when handling an aon_timer wakeup, where the dif code writes to disable the wakeup (writing to AON_TIMER_WKUP_CTRL_REG_OFFSET), and then clear the wakeup cause (writing to AON_TIMER_WKUP_CAUSE_REG_OFFSET). When the order is inverted we end up clearing the cause and in the following AON cycle disabling wakeups, which means the wakeup cause ends up being set again, so the wakeup persists.

One simple way to fix this is to do a read back to AON_TIMER_WKUP_CTRL_REG_OFFSET, since any read will wait for a write to the same CSR to be completed (after synchronization). Notice this can take around 30 us: 3 AON cycles for the write and 3 more for the read. An alternative approach would wait for one AON cycle (5 microseconds), since that is the maximum time the first write can slide after the second, and that can cause the writes to complete at the same time, but not out of order.

The chip_sw_pwrmgr_random_sleep_all_wake_ups test fails for this reason when run with CDC instrumentation enabled and seed 153045692.

The IPs that seem susceptible to this are
- adc_ctrl
- aon_timer
- clkmgr
- pinmux
- pwm
- sysrst_ctrl
- usbdev

This is because they instantiate prim_reg_cdc in their CSR register RTL.

**Comment by msfschaffner** [comment]
Thanks @matutem for finding this!

For context, the register node CDC scheme has been designed in that way on purpose, see slides from Tim Chen [here](https://docs.google.com/presentation/d/1o-3Kf7DkppXVgwrkHhGP4HnaXTx2emTgb3XxXXgVAOk/edit#slide=id.p). 

Basically we needed a standardized solution since every block with CSRs going to different clock domains handled this in an ad-hoc manner. In particular, the problem was that without extra hardware handling, blocking writes to registers in the AON domain had the potential to dramatically slow down parts of the SW code, which can have a significant impact on boot time etc. Examples for such code sections include initialization of `aon_timer` and `sysrst_ctrl`, among others. 

However, as observed by @matutem above, the currently implemented scheme can have ordering issues since each register is synchronized separately. The read back solution works to resolve this issue (in fact the slides also mention that SW should use that solution if explicit confirmation for write completion is required). However, I am not sure we want to do that on all AON register writes, since that would defeat the purpose of the parallel synchronization scheme.

It would be good to get feedback on whether software guidance for the memory model is enough or whether more needs to be done - either via standardized functions or additional ordering support in HW (note that the latter may have quite some impact on hardware complexity, though).

**Comment by msfschaffner** [comment]
CC @vogelpi @GregAC @andreaskurth 

I don't think we should change anything in this area for the Earlgrey PROD iteration since the HW itself behaves correctly and changing this synchronization scheme (or introducing more hardware support for ordering) would be rather intrusive. Rather, I think this is a behavior of the current implementation that the SW should be aware of. I am therefore triaging this into the backlog, but please LMK if you have any concerns with that.

**Comment by vogelpi** [comment]
This sounds good to me @msfschaffner .

**Comment by matutem** [comment]
The second write will always arrive to a synchronizer some fast clock cycles later than the first one. I assume the slow clock distribution would guarantee all synchronizers clock rise at around the same time. In other words, this could be an artifact of our CDC instrumentation, but I would like to get feedback about the slow clock expectations.

**Comment by msfschaffner** [comment]
You may be right, this could be an artifact of our CDC instrumentation since it introduces artificial stagger in the target domain, which is very slow in this case.

The spread of the AON clock distribution is almost certainly narrower than one peri clock cycle. Thus, writes to different registers should not be able to overtake one another. In the worst case, I would expect them to be synchronized over in the same AON clock cycle.

**Comment by matutem** [comment]
Closing it since it is a CDC instrumentation artifact.
