### ISSUE TITLE
[csrng] Don't handle Generate, Reseed, or Update commands on uninstantiated interfaces

### ISSUE THREAD

**Issue by andreaskurth** [lowRISC/opentitan#19293]
## Summary

CSRNG currently handles Generate, Reseed, and Update commands even if the app interface that receives the command is not instantiated.

## Context

Proper usage of CSRNG requires an Instantiate command before any of the other commands. On the HW interfaces, we are currently not aware of a scenario in which EDN would send a Generate, Reseed, or Update command before an Instantiate command. On the SW interface, however, CSRNG could in principle receive a Generate, Reseed, or Update command before any Instantiate command, although we are currently not aware that this is the case for any OT software.

## Expected behavior

When CSRNG receives a Generate or Reseed command on an uninstantiated (a.k.a. uninitialized) interface, it must not handle that command but flag an error [NIST SP 800-90A: Section 9.2.1 for Reseed, Section 9.3.1 for Generate].

When CSRNG receives an Update command on an uninstantiated interface, we probably don't want it to handle it (although this matters much less and can be discussed).

## Current behavior

CSRNG does not check whether an interface is instantiated or not when handling commands; it handles commands with valid encoding in any order.

## Impact

The most problematic scenario is that in which CSRNG receives and handles a Generate command on an uninstantiated interface. In that case, an uninitialized state (zero after reset) is used to generate bits and provide them on the interface. The FIPS bit for the generated bits is not set if this happens after a reset or disable+re-enable of CSRNG, although I'm not sure if there's no scenario in which the FIPS bit couldn't be set incorrectly (I don't *think* so, though).

## Possible resolution

We could extend `csrng_main_sm` to track which interfaces are initialized and let it handle Generate, Reseed, and Update commands only on initialized interfaces, signaling a recoverable alert if one of these commands is seen on an uninitialized interface.

**Comment by andreaskurth** [comment]
Credits to @rivos-eblot for reporting this
CC @moidx, @msfschaffner, @vogelpi, @johannheyszl for assessment and feedback

**Comment by vogelpi** [comment]
Thanks for reporting this. We have been aware of this as part of #16516. I think what we discussed in the Sec WG and reported in the other issue also holds for this particular case here in large parts: the issue is triggered due to mis-use/misconfiguration by software. There is however an important difference between this case and other internal error conditions: CSRNG will deliver entropy and not indicate anything to software (instead of just stalling eventually). Anyway, I believe we should fix both issues in the near future. But given that this needs to be explicitly triggered by software / can be completely avoided by proper software, I believe it's probably not ultra critical.

Good catch on the FIPS bit, this might help to avoid some catastrophic failures. Whether the FIPS bit is correctly deasserted is something we wanted to verify as part of  #18568.

**Comment by vogelpi** [comment]
@johannheyszl and I discussed this. We would like this to see fixed for production. Area impact is low but it can be seen as stabilizing / fixing the feature set. So M2 seems right. I'll give this slightly higher prio given that this simplifies / improves the software API and improves security. But we can rediscuss/evaluate priorities later again if needed.

**Comment by vogelpi** [comment]
This needs #16516. Then modify FSM to not perform the Generate and report and error to SW_CMD_STS / the command interface to EDN.

**Comment by rivos-eblot** [comment]
Somewhat related: it would be really helpful for SW developers to document the behavior of the hardware related to the _Generate_ commands. All commands but _Generate_ complete "quickly" so that it is possible to execute another command, such as _Uninstantiate_. However as _Generate_ command does not complete till the full count of 128-bit random numbers has been delivered to the requester, which seems to means that _Uninstantiate_ cannot be executed till the same interface has receveid the count of 128-bit packets that has been requested to the _Generate_ command. In other word, the _Uninstantiate_ command is unlikely to be used if the count is high, knowing that it is close to impossible to define an exact/precise count of random bit packets that need to be generated.
