### ISSUE TITLE
[SPI] Latches

### ISSUE THREAD

**Issue by rw1nkler** [lowRISC/opentitan#2001]
Hey, I have found 5 latches in the SPI core generated for the earlgray design. I was following the [getting-started](https://docs.opentitan.org/doc/ug/getting_started_fpga/) instructions for FPGA. Are those latches intentional?

![latches](https://user-images.githubusercontent.com/52699314/79761802-36d0c600-8322-11ea-876b-62bd55f9c40c.png)

The design was generated from: d4d5d2f3bb87af5ca2f2787af5bc19bee04ffc6a

Here is the vivado log file:
[vivado.log](https://github.com/lowRISC/opentitan/files/4504042/vivado.log)

**Comment by sjgitty** [comment]
Thanks @rw1nkler for reporting. @eunchan can look into it soon.

**Comment by eunchan** [comment]
Thanks! I missed the default value part in the always_comb block. Thanks for the report I will revise and update the design. Curious why this isn't catched by lint tool...

**Comment by cdgori** [comment]
The lint miss is actually a much bigger concern to me.  Who would normally try to figure this out?

**Comment by eunchan** [comment]
> The lint miss is actually a much bigger concern to me. Who would normally try to figure this out?

Should be me. I will check the lint result again.

**Comment by eunchan** [comment]
Hum.. checked lint report again but cannot find latch error.. @msfschaffner you have better knowledge than me about the lint, do you know how to enable to catch latches?

**Comment by msfschaffner** [comment]
Thanks for catching this @rw1nkler!

Let me check why this has not been flagged by lint. 
That is something we should amend in our policy.

**Comment by msfschaffner** [comment]
So after a few experiments with that particular part of the FSM, I can say that this issue is likely a YAVSI (yet another Vivado synthesis issue ;)). I.e., the code enumerates all possible states in that `always_comb` block. Our linter has rules to check for this and will complain if 1) the `always_comb` semantics are violated, and 2) if latches are inferred. If you remove one branch from the affected `if / else` statement, our linter correctly flags this. 

For now, #2004 should fix this, but I am going to report this to Xilinx as well.

**Comment by eunchan** [comment]
Thanks @msfschaffner . So the lint tool is smart enough to check whether the `if..else if` meets full condition or not but Vivado doesn't. Anyway I will keep it in my mind to use `else` explicitly.

**Comment by cdgori** [comment]
Yep, thank you @msfschaffner for checking this out!
