### ISSUE TITLE
[chip-test,si-val]  chip_sw_edn_entropy_reqs

### ISSUE THREAD

**Issue by h-filali** [lowRISC/opentitan#20054]
### Test point name

[chip_sw_edn_entropy_reqs](https://github.com/lowRISC/opentitan/blob/master/hw/top_earlgrey/data/ip/chip_edn_testplan.hjson)

### Host side component

None Required

### OpenTitanTool infrastructure implemented

None

### Silicon Validation (SiVal)

Yes

### Emulation Targets

- [ ] None
- [X] CW310
- [ ] Hyperdebug + CW310

### Contact person

@vogelpi @h-filali

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [x] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes): **This test already exists in [chip_sw_edn_entropy_reqs](https://github.com/lowRISC/opentitan/blob/master/sw/device/tests/entropy_src_edn_reqs_test.c) and [chip_sw_csrng_edn_concurrency](https://github.com/lowRISC/opentitan/blob/master/sw/device/tests/csrng_edn_concurrency_test.c).**
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [x] Host-side component developed
- [x] HJSON test plan updated with test name (so it shows up in the dashboard): *testpoint exists in testplan*
- [x] Test added to dvsim nightly regression (and passing at time of checking)
- [x] For SiVal test cases, test is running relevant FPGA or silicon regression

**Comment by h-filali** [comment]
This test doesn't have the sival arguments in the testplan. Should we even consider this test a sival test or can we close this issue?

FYI: @vogelpi @andreaskurth

**Comment by vogelpi** [comment]
Just had a quick look at the two tests:
- [chip_sw_edn_entropy_reqs](https://github.com/lowRISC/opentitan/blob/master/sw/device/tests/entropy_src_edn_reqs_test.c) is testing all entropy consumers except AST and I think it would be valuable to have this as kind of a smoketest for the EDNs in SV1. Would you mind updating the test plan accordingly? There is one [comment with a TODO](https://github.com/lowRISC/opentitan/blob/master/sw/device/tests/entropy_src_edn_reqs_test.c#L241-L244) in the code which seems outdated (the test is now using auto mode). Would you mind removing this please?
- [chip_sw_csrng_edn_concurrency](https://github.com/lowRISC/opentitan/blob/master/sw/device/tests/csrng_edn_concurrency_test.c) seems to concurrently test both hardware instances of CSRNG. I couldn't fully understand the mechanics of the test and the pass/fail criteria. Also some comments seem outdated. Since the test is already implemented I suggest to keep it and use it for SiVal though. Would you mind having a look at this @h-filali please ? Conceptually, it seems familiar to your newly implemented auto-mode test.

**Comment by vogelpi** [comment]
PR #20275 just took care of the first part of this issue. The second part is still open and I'll discuss this with @h-filali once he's back.

**Comment by vogelpi** [comment]
We had a look at this together. There is a single comment inside [chip_sw_csrng_edn_concurrency](https://github.com/lowRISC/opentitan/blob/master/sw/device/tests/csrng_edn_concurrency_test.c) which is incorrect and should be reworked. The rest of the test is indeed in very good shape.
