### ISSUE TITLE
[CI] RISC-V Compliance test is failing.

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#2012]
Current RISC-V Compliance test is failing in Azure Pipeline.

**Comment by silvestrst** [comment]
Yeah, just noticed as well on #1477 . Thank you @eunchan for raising it.

**Comment by GregAC** [comment]
I will take a look

**Comment by GregAC** [comment]
I think we'll need to disable it for now (https://github.com/lowRISC/opentitan/pull/2013) as the reason for the failure isn't obvious and looks like something to do with the azure environment.

**Comment by eunchan** [comment]
Thanks for the update Greg!

**Comment by GregAC** [comment]
So the issue turned out to be varying performance of azure agents. We have a 60 second timeout where the test fails if it hasn't seen a 'PASS!' message come out of the UART. When the azure job executes on a slower agent we hit this timeout. I've increased the timeout so things should work now (#2019), just awaiting github to start working again properly so the azure CI can run.
