### ISSUE TITLE
[top_earlgrey] clang-format and generated top_earlgrey.c 

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#2035]
After re-basing on #2025, my local clang-format invocations seems to change the spacing on top_earlgrey.c.. this eventually leads to a CI failure. 

I'm not yet sure if it's clang-format version differences (our local is using 5+, while it seems like CI uses 3.8.0) or maybe clang-format was never run?

Anyhow, I thought I'd file first while experimenting..

**Comment by tjaychen** [comment]
@eunchan

**Comment by tjaychen** [comment]
hey all, 
so i dug up clang-format.3.8.0 (which in my failing PR was the version being used), and basically there's a difference between what that produces and what our Google locally installed version produces.

Should we all just revert to 3.8.0 in general? Not really sure what the right answer is.

**Comment by eunchan** [comment]
Personally, I prefer having later version of clang-format tool, installing 3.8 is quite annoying (multiple versions in a machine). So, to satisfy with the requirement, this tool need to be run inside docker (means, reggen , topgen need to be run in docker).

Can we change the minimum requirement of clang-format to higher version (at least 6?)

**Comment by lenary** [comment]
It's a known problem that clang-format changed how it formatted things between 3.8.0 and versions since then. Version 3.8.0 was chosen because it's the version that we can most easily get in CI (via the package manager on ubuntu 16.04).

I have felt the same pain around having to install clang-format 3.8.0 manually on my own machine to match CI, as have other googlers and some lowriscers who are running on more up-to-date linux distributions.

We are intending to ship a more recent version of clang-format when we make improvements to the compiler toolchain (which is in planning at the moment). With this in mind, I'd prefer we wait until then to update our clang-format version, rather than coordinating a change to the clang-format version (which would involve providing instructions to build from source, and finding a way to update CI) and a few weeks later coordinating another change to the entire toolchain tarball.

In the short term, I could look at turning off clang-format warnings for that entire header, rather than running it through clang-format. This would mean CI stopped complaining when it is generated, and non-software developers would not need to care as much about the version of clang-format they are running if they're not changing C files.

What do you think about this approach?

**Comment by tjaychen** [comment]
i think that may work in the short term...but longer term i think many of the HW guys will start writing C test cases for both sanity, integration and bring-up type tests. So maybe we'll run into more issues having incompatible clang-formats. 

I didn't actually know you could install multiple versions of the same package on a single machine (a quick google search yesterday seemed to tell me no), so i ended up just getting the pre-compiled binaries. I think as long as I can do that, it's not TOO bad right now.

**Comment by sriyerg** [comment]
I ran into this issue as well. I made PR #2082 as a stop gap solution (run git clang-format inside the docker to stay aligned with CI).

**Comment by lenary** [comment]
#2038 should have solved this for autogenerated and vendored code, and #2082 has ensured there's a version of clang-format that can be used in the utilities docker container. I think this means we can close this issue for now?

**Comment by tjaychen** [comment]
sounds good to me. thank you.
