### ISSUE TITLE
[i2c] D2(S) Signoff 

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#20971]
### Description

Ensure D2(S) signoff criteria are fulfilled after focus area changes have landed.

**Comment by hcallahan-lowrisc** [comment]
> WIP
>
> As a focus block with significant RTL changes in the interim period, I am proposing to follow the fuller D2 Dev Stage - Sign-off Process. These signoff notes will follow the checklists in that procedure. There is an associated sign-off review meeting document created \<insert-link-here\>.

## Changes since ES tape-out
### Commits

### Pull Requests
- #21765 
- 

### Issues
- 

## Issues (that will not be addressed)
- 

# [D2 Checklist Items](https://opentitan.org/book/doc/project_governance/checklist/index.html#d2)

## NEW_FEATURES
- #21857 
- #21827 
Other changes amount to bugfixes and optimizations of existing functionality.

## BLOCK_DIAGRAM
- [ ] ACQFIFO [diagrams here](https://opentitan.org/book/hw/ip/i2c/doc/theory_of_operation.html#acquired-formatted-data) to be updated based on #21857 changes
- [ ] Implementation FSM [diagrams here](https://opentitan.org/book/hw/ip/i2c/doc/theory_of_operation.html#implementation-details-format-flag-parsing) to be updated based on #22049 

## DOC_INTERFACE
Unchanged.

## DOC_INTEGRATION_GUIDE
- Additional constraints on timing parameters have been documented in multiple issues.
  - Min `THIGH`
  - Su/Hd minimums to reject S/P conditions

## MISSING_FUNC
- No known missing functionality that is untracked or undocumented.

## FEATURE_FROZEN
- Feature requests are still open in-parallel to this signoff, with the goal of improving support for I2C-derived protocols such as SMBus and higher derivatives. These are out of scope for this sign-off, and will be assessed as part of a different revision for this block.

## FEATURE_COMPLETE
- [x] I2C.MODE.HOST
- [x] I2C.MODE.TARGET
- Actual performance was previously lower than expected due to design limitations and oversights. These have been rectified for this milestone. Note that actual performance is dependant on the input clock frequency and the user-configured timing parameters, but performance should now reach the maximum possible when taking into account quantization errors as a result of the oversampling-based architecture and implementation. 
  - [ ] I2C.SPEED.STANDARD
  - [ ] I2C.SPEED.FAST
  - [ ] I2C.SPEED.FASTPLUS
- [x] I2C.OVERRIDE
- [x] I2C.OPERATION.READ
- [x] I2C.OPERATION.WRITE
- [x] I2C.PROTOCOL.CLOCKSTRETCHING
- [x] I2C.PROTOCOL.NACK
- [x] I2C.PROTOCOL.REPEATEDSTART

## PORT_FROZEN
No change to top module ports.

## ARCHITECTURE_FROZEN

### CSRs
TODO : describe changes to CSRs.

## REVIEW_TODO
No untagged TODOs in `i2c/rtl/`.

## STYLE_X
No use of 'x' in i2c.

## CDC_SYNCMACRO
Appropriate 'prim' macros are utilized for synchronization of SDA/SCL inputs.

## LINT_PASS
TODO when all PRs are merged.

## CDC_SETUP
No CDC flow available.

## RDC_SETUP
No RDC flow available.

## AREA_CHECK

## TIMING_CHECK

## SEC_CM_DOCUMENTED

**Comment by andreaskurth** [comment]
We just discussed this in a signoff meeting with @hcallahan-lowrisc, @a-will, and @andreaskurth, and we agree with signing i2c off at D2S. Two diagrams need updating (https://github.com/lowRISC/opentitan/issues/22318) but we agreed that this shouldn't gate D2S signoff.
