### ISSUE TITLE
[spi_device] D2 Signoff 

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#20974]
### Description

Ensure D2 signoff criteria are fulfilled after focus area changes have landed.

**Comment by a-will** [comment]
Note: This will be filled in over time. It is not complete yet.

## Changes since ES tape-out

- https://github.com/lowRISC/opentitan/pull/19164
- https://github.com/lowRISC/opentitan/pull/19575
- https://github.com/lowRISC/opentitan/pull/20856
- https://github.com/lowRISC/opentitan/pull/20942
- https://github.com/lowRISC/opentitan/pull/21119
- https://github.com/lowRISC/opentitan/pull/21120
- https://github.com/lowRISC/opentitan/pull/20966
- https://github.com/lowRISC/opentitan/pull/21161
- https://github.com/lowRISC/opentitan/pull/21322
- https://github.com/lowRISC/opentitan/pull/21656
- https://github.com/lowRISC/opentitan/pull/21701
- https://github.com/lowRISC/opentitan/pull/21595
    - top-level constraints

## NEW_FEATURES
A 2-stage pipeline was added as an optional path for flash reads with dummy cycles, so as to effect higher clock rates for compatible commands (especially Quad Output Read).

  - Issues
    - https://github.com/lowRISC/opentitan/issues/11718
  - PRs
    - https://github.com/lowRISC/opentitan/pull/20966
    - https://github.com/lowRISC/opentitan/pull/21595

In addition, generic mode and support for SPI timings other than mode 0 were dropped (these are related features).

- Issues
  - https://github.com/lowRISC/opentitan/issues/15452
  - https://github.com/lowRISC/opentitan/issues/16339
- PRs
  - https://github.com/lowRISC/opentitan/pull/20856
  - https://github.com/lowRISC/opentitan/pull/21161

The rest of the changes do not precisely amount to new features. Instead, they are sometimes significant refinements of the implementation to fix bugs.

## BLOCK_DIAGRAM
Updated in https://github.com/lowRISC/opentitan/pull/21656

## DOC_INTERFACE
No changes since tape-out, so all still documented.

## DOC_INTEGRATION_GUIDE
Added clocking requirements in the documentation here:
https://github.com/lowRISC/opentitan/blob/599ab38d27d05b61d88fefbd3b54103cd44fb403/hw/ip/spi_device/README.md?plain=1#L88

## MISSING_FUNC
The missing compatibility with the TPM spec is documented in these two places:

https://github.com/lowRISC/opentitan/blob/599ab38d27d05b61d88fefbd3b54103cd44fb403/hw/ip/spi_device/doc/theory_of_operation.md?plain=1#L352

https://github.com/lowRISC/opentitan/blob/599ab38d27d05b61d88fefbd3b54103cd44fb403/hw/ip/spi_device/doc/theory_of_operation.md?plain=1#L387-L389

## FEATURE_FROZEN
TBD after review meeting, but expected to be.

## FEATURE_COMPLETE
- [x] SPI_DEVICE.MODE.FLASH_EMULATION
- [x] SPI_DEVICE.MODE.PASSTHROUGH
- [ ] SPI_DEVICE.MODE.TPM
  - Not fully compliant, but feature level is considered satisfactory
  - https://github.com/lowRISC/opentitan/issues/21160
- [x] SPI_DEVICE.HW.LANES
- [x] SPI_DEVICE.HW.SERDES_ORDERING
- [x] SPI_DEVICE.HW.CSB_STATUS
- [x] SPI_DEVICE.MODE.FLASH_EMULATION.COMMANDS
- [x] SPI_DEVICE.HW.FLASH_EMULATION_BLOCKS
- [x] SPI_DEVICE.MODE.FLASH_EMULATION.READ_COMMAND_PROCESSOR
- [x] SPI_DEVICE.MODE.FLASH_EMULATION.DUMMY_CYCLE
- [x] SPI_DEVICE.MODE.FLASH_EMULATION.WRITE_ENABLE_DISABLE
- [x] SPI_DEVICE.HW.LAST_READ_ADDR
- [x] SPI_DEVICE.HW.CMDINFOS
- [x] SPI_DEVICE.HW.COMMAND_UPLOAD
- [x] SPI_DEVICE.HW.3B4B_ADDRESSING
- [x] SPI_DEVICE.MODE.PASSTHROUGH.CMD_FILTER
- [x] SPI_DEVICE.MODE.PASSTHROUGH.ADDRESS_MANIPULATION
- [x] SPI_DEVICE.MODE.PASSTHROUGH.STATUS_MANIPULATION
- [x] SPI_DEVICE.MODE.PASSTHROUGH.OUTPUT_ENABLE_CONTROL
- [x] SPI_DEVICE.MODE.PASSTHROUGH.INTERCEPT_EN
- [x] SPI_DEVICE.MODE.PASSTHROUGH.MAILBOX
- [x] SPI_DEVICE.MODE.TPM.RETURN-BY-HW_REGS
- [x] SPI_DEVICE.MODE.TPM.AUTO_WAIT
- [x] SPI_DEVICE.MODE.TPM.READ_FIFO_MODE
- [x] SPI_DEVICE.MODE.TPM.CAPABILITY

## PORT_FROZEN
Only interrupt ports changed:

```diff
-  // INTR: Generic mode
-  output logic intr_generic_rx_full_o,              // RX FIFO Full
-  output logic intr_generic_rx_watermark_o,         // RX FIFO above level
-  output logic intr_generic_tx_watermark_o,         // TX FIFO below level
-  output logic intr_generic_rx_error_o,             // RX Frame error
-  output logic intr_generic_rx_overflow_o,          // RX Async FIFO Overflow
-  output logic intr_generic_tx_underflow_o,         // TX Async FIFO Underflow
+  output logic intr_tpm_rdfifo_cmd_end_o,
+  output logic intr_tpm_rdfifo_drop_o,
```

## ARCHITECTURE_FROZEN

### RAMs
- Support for 1r1w RAMs has been added, but it is not used in earlgrey.
  - Access controls are the same for 2p RAMs, though.
  - Egress section is write-only for SW.
  - Ingress section is read-only for SW.
- The 64B TPM Write FIFO and TPM Read FIFO have been moved to the bigger SRAMs.
  - No longer separate.

### CSRs
```diff
CONTROL:
- CONTROL.ABORT
+ CONTROL.FLASH_STATUS_FIFO_CLR
+ CONTROL.FLASH_READ_BUFFER_CLR
- CONTROL.MODE:fwmode
+ CONTROL.MODE:disabled
- CONTROL.RST_TXFIFO
- CONTROL.RST_RXFIFO
- CONTROL.SRAM_CLK_EN

CFG:
- CFG.CPOL
- CFG.CPHA
- CFG.TIMER_V
- CFG.ADDR_4B_EN

+ ADDR_MODE:
+ ADDR_MODE.ADDR_4B_EN
+ ADDR_MODE.PENDING

- FIFO_LEVEL
- ASYNC_FIFO_LEVEL

STATUS:
- STATUS.rxf_full
- STATUS.rxf_empty
- STATUS.txf_full
- STATUS.txf_empty
- STATUS.abort_done

- RXF_PTR
- TXF_PTR
- RXF_ADDR
- TXF_ADDR

- FLASH_STATUS.status (bits = 23:1, rw)
+ FLASH_STATUS.wel (bits = 1, rw1c)
+ FLASH_STATUS.status (bits = 23:2, rw)

+ UPLOAD_CMDFIFO.busy
+ UPLOAD_CMDFIFO.wel
+ UPLOAD_CMDFIFO.addr4b_mode

+ CMD_INFO*.read_pipeline_mode

- TPM_STATUS.wrfifo_depth
+ TPM_STATUS.wrfifo_pending
+ TPM_STATUS.rdfifo_aborted

- TPM_WRITE_FIFO
```

## REVIEW_TODO
WIP

## STYLE_X
WIP

## CDC_SYNCMACRO
WIP

## LINT_PASS
WIP

## CDC_SETUP
WIP

## RDC_SETUP
WIP

## AREA_CHECK
WIP

## TIMING_CHECK
WIP

## SEC_CM_DOCUMENTED

N/A. There are no security countermeasures for this block.

**Comment by msfschaffner** [comment]
Thanks for putting this together @a-will! 
This has been reviewed together with @hcallahan-lowrisc @vogelpi @antmarzam @msfschaffner and @rswarbrick today.

Open action items for closing out D2S:
- [ ] Remove irrelevant ICEBOX TODOs and close associated issue as not planned
- [ ] Update outdated checklist
  - [ ] Remove outdated D1 FUNC_IMPLEMENTED comment on checklist
  - [ ] Update waived and N/A items on D2 (DOC_INTEGRATION_GUIDE, MISSING_FUNC)

**Comment by a-will** [comment]
The action items were covered by https://github.com/lowRISC/opentitan/pull/21795
