### ISSUE TITLE
[spi_host] D2(S) Signoff

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#20975]
### Description

Ensure D2(S) signoff criteria are fulfilled after focus area changes have landed.

**Comment by hcallahan-lowrisc** [comment]
# spi_host D2(S) Signoff 

This **is** a focus area block.
I am proposing to follow the lightweight signoff procedure for this block, as there are 3 RTL changes all of which are minor.

## Commits since Earlgrey-ES tapeout

`$ git rev-parse --short HEAD`
b2d9173578

`$ git log Earlgrey-M2.5.2-RC0..HEAD --oneline hw/ip/spi_host`
369be91feb [spi_host,doc] Regenerate register documentation
272787cf68 [spi_host,rtl] Factor the byte_sel block into TX FIFO status signals
51394dc45b Revert "[spi_host,rtl] Use sd_en_o[0] ..." ( fbbd660 )
fbbd660c94 [spi_host,rtl] Use sd_en_o[0] to only drive sd_o[0] during TX (std_mode)
0d14dd693f [docs] Fix repetitions of the definite article
61a237e197 [util/reggen] reverse order of substruct generation
fc8484601e [reggen,hw] Create index parameter for registers windows
de31bdf1c2 [reggen] Remove the devmode input
963a5006cc [doc] Minor tweak to md sanitisation code
975a6eb927 [adc_ctrl,dv] Tidy up access to intr_state in env_cfg files
3f128e781f [spi_host] Add feature list for block
1b16ca2122 [reggen] Add mubi support SWAccess that sets/clears a reg
59f8142826 [doc] Moved badges over to using hosted images
8c772349f3 [doc] spi_host registers and interfaces now use CMDGEN
7688e714e8 [reggen] Add initial support for version and cip_id hjson fields
fbd888eea8 Revert "[reggen] Add CIP_IDs and bump all major versions"
0ba10b3cd3 [reggen] Add CIP_IDs and bump all major versions

## Issues closed since the Earlgrey-ES tapeout

- #17644
- #15074 

Doc
- #19183

## Currently open issues

- #12989 
  - Will be closed by #21278 
- #14969
  - Will be closed by #22040
- #21208
  - Will be closed by #21278 

## Currently open issues (that will not be closed for D2)
- #10055 : P3
- #10832 : P4
- #15072 : Icebox
- #15073 : Icebox
- #15077 : Icebox
- #18886 : V2 task

## Summary 

Changes that impact RTL:
- #21325
- #21278 
- #22040 
  - (Redux of the reverted PR #21338)

For the above changes:
- [ ] Make sure the documentation is in sync with the change
  - 21278 changed the 'spi_event' interrupt from a CIP "Event-Type" to a CIP "Status-Type", but did not change the name. This interrupt is still an aggregate of different events that could occur in the normal operation of the IP, but it is a "[Status-Type](https://opentitan.org/book/doc/contributing/hw/comportability/index.html#status-type-interrupt)" interrupt as far as signalling/handling is concerned. This could be confusing, and should be clarified in the documentation. #TODO.
- [ ] Note whether the DV environment has been updated accordingly already.
  - No significant changes need to existing DV.
  - The only change which (arguably) could have wider implications would be 21278 (Interrupt-type alignment), as this change to the programming model is likely to break non-regressed software which was written against the old behaviour.
- [ ] Look over the [D checklist](https://opentitan.org/book/doc/project_governance/checklist/index.html#signoff-checklist) items.
[NEW_FEATURES](https://opentitan.org/book/doc/project_governance/checklist/index.html#new_features) No significant features added.
[BLOCK_DIAGRAM](https://opentitan.org/book/doc/project_governance/checklist/index.html#block_diagram) No change needed.
[DOC_INTERFACE](https://opentitan.org/book/doc/project_governance/checklist/index.html#doc_interface)
[DOC_INTEGRATION_GUIDE](https://opentitan.org/book/doc/project_governance/checklist/index.html#doc_integration_guide)
[MISSING_FUNC](https://opentitan.org/book/doc/project_governance/checklist/index.html#missing_func)
[FEATURE_FROZEN](https://opentitan.org/book/doc/project_governance/checklist/index.html#feature_frozen)
[FEATURE_COMPLETE](https://opentitan.org/book/doc/project_governance/checklist/index.html#feature_complete)
[PORT_FROZEN](https://opentitan.org/book/doc/project_governance/checklist/index.html#port_frozen)
[ARCHITECTURE_FROZEN](https://opentitan.org/book/doc/project_governance/checklist/index.html#architecture_frozen)
[REVIEW_TODO](https://opentitan.org/book/doc/project_governance/checklist/index.html#review_todo)
[STYLE_X](https://opentitan.org/book/doc/project_governance/checklist/index.html#style_x)
[CDC_SYNCMACRO](https://opentitan.org/book/doc/project_governance/checklist/index.html#cdc_syncmacro)
[LINT_PASS](https://opentitan.org/book/doc/project_governance/checklist/index.html#lint_pass) : #TODO Check lint after PRs merged.
[CDC_SETUP](https://opentitan.org/book/doc/project_governance/checklist/index.html#cdc_setup)
[RDC_SETUP](https://opentitan.org/book/doc/project_governance/checklist/index.html#rdc_setup)
[AREA_CHECK](https://opentitan.org/book/doc/project_governance/checklist/index.html#area_check)
[TIMING_CHECK](https://opentitan.org/book/doc/project_governance/checklist/index.html#timing_check)
[SEC_CM_DOCUMENTED](https://opentitan.org/book/doc/project_governance/checklist/index.html#sec_cm_documented)
- [x] Make sure that there are no open TODOs
  - No untagged TODOs in `spi_host/rtl/`

> Note that Reggen, documentation or SiVal changes are not considered RTL changes.

**Comment by hcallahan-lowrisc** [comment]
This block did not have it's design_stage reverted, so for signoff it should be sufficient to close this issue as completed.

@rswarbrick @a-will @andreaskurth PTAL

**Comment by a-will** [comment]
I think for V2, we should make sure to test Dual I/O and Quad I/O opcodes, so we uncover whether there is still a gap for those modes after https://github.com/lowRISC/opentitan/pull/22040 fixed up Standard mode.  Looks like this is mentioned in #22182

If you can get a utilization report from a current chip_earlgrey_cw310_hyperdebug FPGA build, we can knock out the `AREA_CHECK` component here. The ES utilization for spi_host_0 was...

| LUTs (logic) | Flops |
| -- | -- |
| 2249 | 5536 |

If others want to waive it, that's also fine with me. I'm not anticipating a large change.

Otherwise, LGTM.

**Comment by andreaskurth** [comment]
Thanks for preparing this signoff, @hcallahan-lowrisc, and for the review @a-will. Signing spi_host off at D2S LGTM. I think for the *AREA CHECK* item in a lightweight signoff it's sufficient that we reviewed the RTL changes and don't expect a significant change in area through them. Additionally, we are currently closely monitoring the area from chip synthesis results, so we would notice an increase in spi_host area quickly.
