### ISSUE TITLE
[uart] D2 Signoff

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#20984]
### Description

Ensure D2 signoff criteria are fulfilled after focus area changes have landed.

**Comment by GregAC** [comment]
Review Hash: 93fedf909d

# Commits since Earlgrey-ES tapeout

91b22bb936 [uart,dv] Fix loopback test when using CDC sync
51fc76c365 [uart] Speed up uart_intr test
6577de1d5a [uart,doc] uart watermark documentation update
fbe9bae308 [uart,dv] Fix uart TX watermark interrupt test
0576a09be3 [uart] Correct timeout comment units
0c580fad04 [uart] Further limit baud in uart_rx_oversample
8ea8f8f4f9 [uart,rtl,dv] Switch watermark interrupts to status type
61a237e197 [util/reggen] reverse order of substruct generation
de31bdf1c2 [reggen] Remove the devmode input
eccaba59fb [doc] Updated Chromium EC URL
5d25eb8536 [uart,sival] Add a feature list for the uart block
1b16ca2122 [reggen] Add mubi support SWAccess that sets/clears a reg
59f8142826 [doc] Moved badges over to using hosted images
3346485ce7 [doc] uart registers and interfaces now use CMDGEN
7688e714e8 [reggen] Add initial support for version and cip_id hjson fields
fbd888eea8 Revert "[reggen] Add CIP_IDs and bump all major versions"
0ba10b3cd3 [reggen] Add CIP_IDs and bump all major versions

Of these commits only one effects UART RTL specifically:

8ea8f8f4f9 [uart,rtl,dv] Switch watermark interrupts to status type
 - Agreed RTL change for PROD switching tx_watermark and rx_watermark to be status type interrupts

Other commits that effect RTL are from general tooling and primitive changes
that effect multiple blocks.

# Closed issues

 - https://github.com/lowRISC/opentitan/issues/18912
 - https://github.com/lowRISC/opentitan/issues/16689
 - https://github.com/lowRISC/opentitan/issues/15378

# Open issues

 - https://github.com/lowRISC/opentitan/issues/22025
    - To be closed for D2, PR already open, https://github.com/lowRISC/opentitan/pull/22026
 -  https://github.com/lowRISC/opentitan/issues/21518
   - Questa related issue, not a D2 concern
 - https://github.com/lowRISC/opentitan/issues/21188
   - DV environment issue, not a D2 concern
 -  https://github.com/lowRISC/opentitan/issues/18648
   - chip-level test failure, likely DV issue, not a D2 concern
 -  https://github.com/lowRISC/opentitan/issues/17813
   - chip-level test failure, likely SW issue, not a D2 concern
 -  https://github.com/lowRISC/opentitan/issues/17348
   - generic doc issue, using UART as an example
 - https://github.com/lowRISC/opentitan/issues/16693
   - Switching interrupts to status types, complete for tx_watermark/rx_watermark. Request for new true 'tx_empty' interrupt (current 'tx_empty' is more accurately 'tx_done'). Minor new feature, that's not essential and can be done post D2
 -   https://github.com/lowRISC/opentitan/issues/10137
   - General DV environment issue effecting UART and other blocks, not a D2 concern
 - https://github.com/lowRISC/opentitan/issues/7826
   - Enhancement to standardize how FIFOs work across all OpenTitan IPs, not being implement for PROD so not a D2 concern
 - https://github.com/lowRISC/opentitan/issues/3421
   - Consolidate interrupts for various IPs (including UART) to reduce the total interrupt lines out of each IP, not being considered for PROD so not a D2 concern

Once PR: https://github.com/lowRISC/opentitan/pull/22026 is merged I am happy UART fulfills D2 sign-off criteria.

**Comment by GregAC** [comment]
@msfschaffner PTAL

**Comment by GregAC** [comment]
I think we need to move it to D2 given there's known post D2 RTL change (the 'proper' tx_empty interrupt). But yes can bump the version as well.

**Comment by msfschaffner** [comment]
Ah ok I oversaw that one - agreed and D2 sounds good to me. You could just go all the way to D2S actually, since this is not a security block and the bus integrity alert is connected.

**Comment by GregAC** [comment]
PR here to change version and design stage: https://github.com/lowRISC/opentitan/pull/22167

**Comment by andreaskurth** [comment]
Closing as completed in #22167.
