### ISSUE TITLE
[rstmgr] D2(S) Signoff

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#20991]
### Description

Ensure D2(S) signoff criteria are still maintained (this is not a focus area block).

**Comment by matutem** [comment]
## Commits since Earlgrey-ES tapeout

```shell
git log Earlgrey-M2.5.2-RC0.. --oneline -- hw/ip/rstmgr/ hw/ip_templates/rstmgr
```

- 15cd8d31e5 [ipgen,rstmgr] Remove hw/ip/rstmgr and old autogen files
  - no impact: transition to ipgen
- 0750df297b [ipgen,rstmgr] Fix core files
  - no impact: transition to ipgen
- b16179dd74 [ipgen,rstmgr] Fix BUILD files
  - no impact: transition to ipgen
- f3227f1ea1 [ipgen,rstmgr] Change templates to use plain dictionaries
  - no impact: transition to ipgen
- f9d8ed1ea2 [ipgen,rstmgr] Turn a few more files into templates and fix paths
  - no impact: transition to ipgen
- f58a9a1d5e [ipgen,rstmgr] Remove files that are generated
  - no impact: transition to ipgen
- f99c77fd28 [ipgen,rstmgr] Move some template files to their intended destination
  - no impact: transition to ipgen
- a23c70bb8d [ipgen,rstmgr] Copy all hw/ip/rstmgr files to ip_templates
  - no impact: transition to ipgen
- 275cf144d7 [ipgen,rstmgr] Add tpldesc hjson file
  - no impact: transition to ipgen
- 27309c63f3 [topgen,rstmgr] Remove useless reset_obj generation variable
  - no impact: transition to ipgen
- 61a237e197 [util/reggen] reverse order of substruct generation
  - no RTL impact, and DV impact is transparent to the code
- ce648ca68e [ipgen.pwrmgr] Change core files to vlnv naming and label as virtual
  - no impact: core file enhancement to avoid multi-top issues
- de31bdf1c2 [reggen] Remove the devmode input
  - no impact: devmode_i was set to constant 1'b1 and changes are transparent
- 0c759b93ab [dv,rstmgr] Fix lint warning in constraint
  - no impact: fixes lint waning with a simple rename
- af22161547 [sival,chip_testplans] Handle alert_handler enables tests
  - no impact: it corrects a mistake in the testplan
- 3f88a55120 [pwrmgr,ipgen] Generate pwrmgr ip_autogen files with topgen
  - no impact: it only changes some links to pwrmgr in documentation
- 1ecc9b9d6e [rstmgr,pwrmgr] Replace tabs with spaces in plans
  - no impact: trivial formatting change in testplans
- 1f7c806403 [sival,rstmgr] Add features in rstmgr.hjson.tpl
  - no impact: adds `features` in hjson file for sival tracking
- 1b16ca2122 [reggen] Add mubi support SWAccess that sets/clears a reg
- 59f8142826 [doc] Moved badges over to using hosted images
  - no impact: documentation-only change
- 324a77e814 [doc] rstmgr registers and interfaces now use CMDGEN
  - no impact: documentation-only change
- 0e6148c74b [dv/rstmgr] Add SVA checking rst_en_o track resets_o
  - positive impact: adds SVA to check resets and rst_en (for alert handler) are in sync, fixing outstanding issue 
- 9d1f184c89 [dv/rstmgr] Fix leaf_rst_cnsty test
  - no impact: fixes a test flakiness due to issuing transactions that violate the alert proocol
- 7688e714e8 [reggen] Add initial support for version and cip_id hjson fields
  - no impact: adds version and cip_id in hjson metadata
- fbd888eea8 Revert "[reggen] Add CIP_IDs and bump all major versions"
  - no impact: reverts PR below
- 0ba10b3cd3 [reggen] Add CIP_IDs and bump all major versions
  - no impact: this PR was reverted

## ssues closed since the Earlgrey-ES tapeout

- https://github.com/lowRISC/opentitan/issues/20700 

- https://github.com/lowRISC/opentitan/issues/20415

- https://github.com/lowRISC/opentitan/issues/20030

- https://github.com/lowRISC/opentitan/issues/20029

- https://github.com/lowRISC/opentitan/issues/19819

- https://github.com/lowRISC/opentitan/issues/19259

- https://github.com/lowRISC/opentitan/issues/19256

- https://github.com/lowRISC/opentitan/issues/19044

- https://github.com/lowRISC/opentitan/issues/16641

- https://github.com/lowRISC/opentitan/issues/16562

- https://github.com/lowRISC/opentitan/issues/16384

- https://github.com/lowRISC/opentitan/issues/8538

## Currently open issues

- https://github.com/lowRISC/opentitan/issues/20798
  - This is an AST issue, and it is expected to be fixed for PROD. It refers to rstmgr since the issue causes a failure in a top-level test associated to rstmgr.

- https://github.com/lowRISC/opentitan/issues/20589

- https://github.com/lowRISC/opentitan/issues/20194

- https://github.com/lowRISC/opentitan/issues/19797

- https://github.com/lowRISC/opentitan/issues/19538

- https://github.com/lowRISC/opentitan/issues/18258

- https://github.com/lowRISC/opentitan/issues/17300

- https://github.com/lowRISC/opentitan/issues/16846

- https://github.com/lowRISC/opentitan/issues/16640

- https://github.com/lowRISC/opentitan/issues/16148

- https://github.com/lowRISC/opentitan/issues/15986

- https://github.com/lowRISC/opentitan/issues/15427

- https://github.com/lowRISC/opentitan/issues/15123

- https://github.com/lowRISC/opentitan/issues/13640

- https://github.com/lowRISC/opentitan/issues/12848

- https://github.com/lowRISC/opentitan/issues/11520

- https://github.com/lowRISC/opentitan/issues/8945

- https://github.com/lowRISC/opentitan/issues/8440

- https://github.com/lowRISC/opentitan/issues/8185

- https://github.com/lowRISC/opentitan/issues/7978

- https://github.com/lowRISC/opentitan/issues/7780

- https://github.com/lowRISC/opentitan/issues/6220

- https://github.com/lowRISC/opentitan/issues/3637

- https://github.com/lowRISC/opentitan/issues/2929

**Comment by msfschaffner** [comment]
Thanks for putting this together, @matutem.

Agreed that the RTL change for MUBI CSRs could use a dedicated CIP CSR test.
The RTL side of it should be done however.

Given the priorities and recommendation for #16384, I do not think that we will be able to enhance this for Earlgrey PROD.
My suggestion would therefore be to leave the design as it is today and sign it off for D2S.
