### ISSUE TITLE
[rv_timer] D2(S) Signoff

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#20998]
### Description

Ensure D2(S) signoff criteria are still maintained (this is not a focus area block).

**Comment by rswarbrick** [comment]
## Commits since Earlgrey-ES tapeout

Checked with version dc22677a68 (the head of `master` on 26/2/24).
Commits since the Earlgrey ES tapeout, found by `git log Earlgrey-M2.5.2-RC0..HEAD --oneline hw/ip/rv_timer`
(and dropping the CIP_ID change/revert combo):

- 61a237e197 [util/reggen] reverse order of substruct generation
  + Moved around cfg0 register ordering.
- de31bdf1c2 [reggen] Remove the devmode input
  + No functional change (this was already tied to 1)
- b3bd66c923 [rv_timer] Update the documentation
  + Documentation tidyup.
- 110239cb42 [rv_timer, sival] List the features
  + SiVal only
- 1b16ca2122 [reggen] Add mubi support SWAccess that sets/clears a reg
  + Tooling change: no change in behaviour.
- 59f8142826 [doc] Moved badges over to using hosted images
  + Documentation format change
- 5670965b32 [doc] rv_timer registers and interfaces now use CMDGEN
  + Documentation format change
- 7688e714e8 [reggen] Add initial support for version and cip_id hjson fields
  + HJson-only change

## Issues closed since the Earlgrey-ES tapeout

Using the filter `is:issue is:closed closed:>2023-06-27 rv_timer`
finds the following two issues. Both are SiVal tasks and needn't
affect the D2S status of rv_timer.

- #19979
- #19978

## Currently open issues

Here is a list of tests based on the filter `is:issue is:open rv_timer`.
I've skipped SiVal and the V2(S)/D2(S) signoff issues.

- #18918
  + This is planned design work which is currently intended to land before the M2 milestone.
  + I'm don't believe it disqualifies `rv_timer` from D2S status. This is a bugfix, not a new feature.
- #18093
  + Top-level wiring change: it won't affect the internals of
    rv_timer.
- #270
  + Ancient top-level tooling change. No direct connection with
    rv_timer.

## Summary 

- None of the changes that have landed will affect D2S status.
- The only issue that's currently open and might affect rv_timer is #18918
- This is essentially a bugfix, so needn't affect D2S status.

**Comment by rswarbrick** [comment]
Tagging @GregAC (as a relevant design TL).

Greg: if you're happy with this assessment, please close this issue.

**Comment by msfschaffner** [comment]
Due to our priorities, the interrupt alignment is deferred into PROD.M4 since it does not have notable PD impact.
