### ISSUE TITLE
[pwrmgr] D2(S) Signoff

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#20990]
### Description

Ensure D2(S) signoff criteria are still maintained (this is not a focus area block).

**Comment by matutem** [comment]
# pwrmgr D2(S) Signoff

This is not a focus area block.

## Commits since Earlgrey-ES tapeout

```
$ git rev-parse --short HEAD
af85dad7af
$ git log Earlgrey-M2.5.2-RC0..af85dad7af --oneline -- hw/ip/pwrmgr hw/ip_templates/pwrmgr
```

dd117372ca [doc,pwrmgr] Document wakeup signal requirements
b16179dd74 [ipgen,rstmgr] Fix BUILD files
ab4b36f6b9 [ipgen,rstmgr] Fix paths to rstmgr in md files
ce648ca68e [ipgen.pwrmgr] Change core files to vlnv naming and label as virtual
4a9a881d44 [topgen] Pass topname key/value pair to ipgen
da087bbddd [rtl,pwrmgr] Fix escalation timeout persistence
de31bdf1c2 [reggen] Remove the devmode input
963a5006cc [doc] Minor tweak to md sanitisation code
748235cbb6 [dv,pwrmgr] Fix pwrmgr_escalation_timeout test
729f744642 [dv/pwrmgr] Add escalation_timeout test
c87db05473 [pwrmgr,ipgen] Remove the hw/ip/pwrmgr and their autogen files
7215f8d9cb [pwrmgr,ipgen] Fix hjson files
78c7edd733 [pwrmgr,ipgen] Fix pwrmgr template and autogen core files
988b584da3 [pwrmgr,ipgen] Fix BUILD files
3f88a55120 [pwrmgr,ipgen] Generate pwrmgr ip_autogen files with topgen
8034e000d6 [pwrmgr,ipgen] Turn a few more files into templates
a8529ce8a9 [pwrmgr,ipgen] Copy all hw/ip/pwrmgr files to ip_templates
c288cc3968 [pwrmge,ip_gen] Add tpldesc hjson file
77278de68f [pwrmgr] Replace tab with spaces in test plan
709d4e7ca0 [doc/pwrmgr] Improve theory of operation doc
9e006e2554 [sival,pwrmgr] Add features in pwrmgr.hjson.tpl
1b16ca2122 [reggen] Add mubi support SWAccess that sets/clears a reg
f4f5d98064 [dv/pwrmgr] Allow transitions to invalid fsm state
59f8142826 [doc] Moved badges over to using hosted images
13c6152a0e [doc] pwrmgr registers and interfaces now use CMDGEN
f7edbbb6a3 [pwrmgr,dv] Correct name of disabled assertion
51d31a1aae [dv/pwrmgr] Complete SVAs for rom integrity checks
7688e714e8 [reggen] Add initial support for version and cip_id hjson fields
fbd888eea8 Revert "[reggen] Add CIP_IDs and bump all major versions"
0ba10b3cd3 [reggen] Add CIP_IDs and bump all major versions
9a61b02fe1 [pwrmgr] Fix xcelium compile error
143faa6be5 [pwrmgr] Synchronize lc signals
e47df29f3e [misc] Use lc_tx_t testing functions at endpoints

**Comment by msfschaffner** [comment]
Thanks for summarizing this @matutem.

I reviewed the RTL changes in more detail above:

- da087bb [rtl,pwrmgr] Fix escalation timeout persistence
  - bugfix that is already tested in DV -> OK

- de31bdf [reggen] Remove the devmode input
  - the alternative mode was never used -> OK

- 1b16ca2 [reggen] Add mubi support SWAccess that sets/clears a reg
  - bugfix in reggen -> OK

- 9a61b02 [pwrmgr] Fix xcelium compile error
  - no functional change -> OK

- 143faa6 [pwrmgr] Synchronize lc signals
  - this cleanup does not affect functionality and is thus already tested in DV -> OK

- e47df29 [misc] Use lc_tx_t testing functions at endpoints
  - this cleanup does not affect functionality and is thus already tested in DV -> OK

I believe the only open design issue is https://github.com/lowRISC/opentitan/issues/20518, which is an enhancement that intend to look into at PROD.M3, so this should not gate D2S/V2S for now.

The Hjson still lists v1.0.0 D2S, so no change is needed to the Hjson (the interface did not change, hence no version increase is necessary):
https://github.com/lowRISC/opentitan/blob/7e196e6f072791aa17817b7691aed6b258399eeb/hw/ip_templates/pwrmgr/data/pwrmgr.hjson.tpl#L34-L40
