### ISSUE TITLE
[pwm] D2(S) Signoff 

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#21003]
### Description

Ensure D2(S) signoff criteria are still maintained (this is not a focus area block).

**Comment by rswarbrick** [comment]
pwm is not a focus block.

## Commits since Earlgrey-ES tapeout

Commits since Earlgrey-ES until dc2267, as generated by
`git log Earlgrey-M2.5.2-RC0..HEAD --oneline hw/ip/pwm`
are below.

I've discarded the reverted CIP_IDs commit

- 61a237e197 [util/reggen] reverse order of substruct generation
  + Reggen change
- de31bdf1c2 [reggen] Remove the devmode input
  + Reggen change
- 963a5006cc [doc] Minor tweak to md sanitisation code
  + Docs only
- bfd4f7823e [pwm,SiVal] Add feature list to `pwm.hjson`
  + SiVal only
- 1b16ca2122 [reggen] Add mubi support SWAccess that sets/clears a reg
  + Reggen change
- 59f8142826 [doc] Moved badges over to using hosted images
  + Docs only
- c9cdb74959 [doc] pwm registers and interfaces now use CMDGEN
  + Docs only
- 7688e714e8 [reggen] Add initial support for version and cip_id hjson fields
  + Reggen change

There are no RTL changes that need tracking for this signoff
procedure.

## Issues closed since the Earlgrey-ES tapeout

Listed with filter `is:issue is:closed closed:>2023-06-27 pwm`:

- #17696
  + Chip-level test
- #16689
  + DV
- #16562
  + Tooling problem for reporter of issue.

None of these closures are caused by RTL changes that would affect D2S
signoff for the block.

## Currently open issues

Listed with filter `is:issue is:open pwm`, but I'm skipping the
D2(S)/V2(S) signoff issues and sival issues.

- #19234
  + DV only
- #18390
  + All TODOs are in dv directory
- #17913
  + DV only
- #17369
  + DV only
- #16734
  + Chip-level test
- #13588
  + DV only
- #9999
  + Documentation only
- #9830
  + This is possibly a HW bug, but a fix would not be a new feature,
    so it should not affect D2S status.
- #3421
  + Chip-level issue. The only mention of pwm was to talk about how
    the issue isn't related to pwm!º

None of these issues seems relevant to D2S status.

## Summary 

- No changes that would affect RTL
- D checklist items are unchanged (since there are no real design changes)
- No design-related TODOs

I believe PWM's D2S status should be unchanged.

@GregAC: Please could you take a look as a design-side TL? If you agree with the assessment, please close.

**Comment by msfschaffner** [comment]
Regarding #9830: this error may just be due to rounding effects in the counter configuration, but it would be good to verify that.
In any case, I agree that this can be treated as a bug fix that needs more verification and should hence not gate this sign-off.
