### ISSUE TITLE
[edn] V1 Signoff

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#21017]
### Description

Ensure V1 signoff criteria are fulfilled after focus area changes have landed.

**Comment by johngt** [comment]
@vogelpi / @h-filali - When you have a chance could you revise the expected effort. Remember that this is to V1 level

**Comment by vogelpi** [comment]
Sorry for the delay @johngt , there is no effort left for EDN at all. @h-filali did all the DD and DV work. What's left is just the sign-off and I will aim to keep everything at D2S/V2S.

I'll revise the estimate now.

**Comment by andreaskurth** [comment]
@vogelpi: For a V1 signoff I think we don't need the DV stats. The smoke test still passes according to [current nightly results](https://reports.opentitan.org/hw/ip/edn/dv/latest/report.html), and if the changes made to EDN as part of M2 are covered either by existing tests or by additional testplan items (with issues to track their completion in M4/M5), then I think this can be closed as completed.

The V2S signoff *can* be done post M2. If the V2S signoff can be closed today, that's fine -- otherwise I'd prefer not gating M2 on a V2S signoff that's not strictly needed for M2.

**Comment by vogelpi** [comment]
I have now prepared the D2/D2S signoff and as part of that studied the criteria for V2/V2S. @h-filali worked very hard to update the DV inline with the RTL for M2 and we are very close to V2S except for one test which has a pass rate below the bar (85% vs 90%) and the FSM coverage is also below the bar (82% vs 90%), see below.

![Screenshot from 2024-03-30 01-05-36](https://github.com/lowRISC/opentitan/assets/20307557/f4f73ded-4146-4157-8a3a-3d73f7a3a6f0)


Thus, we have to sign off at V1 unfortunately.

Fixing the two things is tracked in #20818 and #22352. And the PR to lower the verification stage back to V1 is here: #22353.
