### ISSUE TITLE
[keymgr] V2(S) Signoff

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#21016]
### Description

Ensure V2(S) signoff criteria are still maintained (this is not a focus area block).

**Comment by andreaskurth** [comment]
keymgr has seen only minimal changes since Earlgrey-ES TO, as described in the [D2S signoff analysis](https://github.com/lowRISC/opentitan/issues/20981#issuecomment-2020487042), and it had been signed off at V2S before.

Commits and issues closed since Earlgrey-ES tapeout as well as currently open issues are captured in the D2S signoff analysis. Relevant for block-level DV are:
- #8458
- #17472 
- #17773
- #18013
- #18344 

All these are tracked for V3 and M4 or M5.

The pass rate of all V1, V2, and V2S tests in [current nightlies](https://reports.opentitan.org/hw/ip/keymgr/dv/latest/report.html) is (far) greater than 90%. All coverage scores are also >90%:
![Image](https://github.com/lowRISC/opentitan/assets/3583291/abf9b3c7-242c-4e13-bd25-8ae8a988b82a)

Thus I think we can keep keymgr at V2S.

Thoughts @ballifatih @vogelpi ?

**Comment by vogelpi** [comment]
This sounds good to me! Thanks @andreaskurth for putting this together.
