### ISSUE TITLE
[kmac] V2S Signoff

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#21013]
### Description

Ensure V1 signoff criteria are fulfilled after focus area changes have landed.

**Comment by vogelpi** [comment]
While doing the PRNG work (#20820 ) I've run the full regression several times. Also the DV integration is done already for the new PRNG. I don't think that there is 12 days left of DV work.

**Comment by vogelpi** [comment]
All relevant DV work has been done together with the RTL work already (tracked in issues). I've thus lowered the effort estimate here to 0.

**Comment by andreaskurth** [comment]
`kmac_smoke` passes 100% according to [current nightly results](https://reports.opentitan.org/hw/ip/kmac_unmasked/dv/latest/report.html). The only other [V1 checklist](https://opentitan.org/book/doc/project_governance/checklist/index.html#v1) item I think needs a more detailed look is [TESTPLAN_COMPLETED](https://opentitan.org/book/doc/project_governance/checklist/index.html#testplan_completed) to check that the RTL changes since Earlgrey-ES TO are covered by an existing test or captured in the testplan. According to the [D2S signoff analysis](https://github.com/lowRISC/opentitan/issues/20978#issuecomment-1991521137), the main changes are:
- #19248 -- microarchitectural change covered by existing tests now that the assertion is no longer disabled
- #19262 -- microarchitectural change covered by existing tests
- #21624 -- architectural change covered by existing tests
- #21657 -- not sure if covered by DV?
- #21787 -- architectural change covered by existing tests

WDYT @vogelpi? Do we need to create an issue to verify the change in #21657 as part of M4/M5?

**Comment by vogelpi** [comment]
Hi @andreaskurth ,
this looks good to me. There was only one change which isn't verified yet (the status type FIFO empty interrupt) but it also wasn't verified before (when it was of type event). Software currently doesn't use this interrupt anyway (because it wasn't really usable before).

LGTM!

**Comment by vogelpi** [comment]
Ah, and thanks for pulling the information together and preparing the issue @andreaskurth !
