### ISSUE TITLE
[rstmgr] V2(S) Signoff

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#21026]
### Description

Ensure V2(S) signoff criteria are still maintained (this is not a focus area block).

**Comment by matutem** [comment]
## Commits since Earlgrey-ES tapeout

```shell
git log Earlgrey-M2.5.2-RC0.. --oneline -- hw/ip/rstmgr/ hw/ip_templates/rstmgr
```

- 15cd8d31e5 [ipgen,rstmgr] Remove hw/ip/rstmgr and old autogen files
  - no impact: transition to ipgen
- 0750df297b [ipgen,rstmgr] Fix core files
  - no impact: transition to ipgen
- b16179dd74 [ipgen,rstmgr] Fix BUILD files
  - no impact: transition to ipgen
- f3227f1ea1 [ipgen,rstmgr] Change templates to use plain dictionaries
  - no impact: transition to ipgen
- f9d8ed1ea2 [ipgen,rstmgr] Turn a few more files into templates and fix paths
  - no impact: transition to ipgen
- f58a9a1d5e [ipgen,rstmgr] Remove files that are generated
  - no impact: transition to ipgen
- f99c77fd28 [ipgen,rstmgr] Move some template files to their intended destination
  - no impact: transition to ipgen
- a23c70bb8d [ipgen,rstmgr] Copy all hw/ip/rstmgr files to ip_templates
  - no impact: transition to ipgen
- 275cf144d7 [ipgen,rstmgr] Add tpldesc hjson file
  - no impact: transition to ipgen
- 27309c63f3 [topgen,rstmgr] Remove useless reset_obj generation variable
  - no impact: transition to ipgen
- 61a237e197 [util/reggen] reverse order of substruct generation
  - no RTL impact, and DV impact is transparent to the code
- ce648ca68e [ipgen.pwrmgr] Change core files to vlnv naming and label as virtual
  - no impact: core file enhancement to avoid multi-top issues
- de31bdf1c2 [reggen] Remove the devmode input
  - no impact: devmode_i was set to constant 1'b1 and changes are transparent
- 0c759b93ab [dv,rstmgr] Fix lint warning in constraint
  - no impact: fixes lint waning with a simple rename
- af22161547 [sival,chip_testplans] Handle alert_handler enables tests
  - no impact: it corrects a mistake in the testplan
- 3f88a55120 [pwrmgr,ipgen] Generate pwrmgr ip_autogen files with topgen
  - no impact: it only changes some links to pwrmgr in documentation
- 1ecc9b9d6e [rstmgr,pwrmgr] Replace tabs with spaces in plans
  - no impact: trivial formatting change in testplans
- 1f7c806403 [sival,rstmgr] Add features in rstmgr.hjson.tpl
  - no impact: adds `features` in hjson file for sival tracking
- 1b16ca2122 [reggen] Add mubi support SWAccess that sets/clears a reg
  - has RTL and DV impact: it needs improved testing
- 59f8142826 [doc] Moved badges over to using hosted images
  - no impact: documentation-only change
- 324a77e814 [doc] rstmgr registers and interfaces now use CMDGEN
  - no impact: documentation-only change
- 0e6148c74b [dv/rstmgr] Add SVA checking rst_en_o track resets_o
  - positive impact: adds SVA to check resets and rst_en (for alert handler) are in sync, fixing outstanding issue 
- 9d1f184c89 [dv/rstmgr] Fix leaf_rst_cnsty test
  - no impact: fixes a test flakiness due to issuing transactions that violate the alert protocol
- 7688e714e8 [reggen] Add initial support for version and cip_id hjson fields
  - no impact: adds version and cip_id in hjson metadata
- fbd888eea8 Revert "[reggen] Add CIP_IDs and bump all major versions"
  - no impact: reverts PR below
- 0ba10b3cd3 [reggen] Add CIP_IDs and bump all major versions
  - no impact: this PR was reverted

## Issues closed since the Earlgrey-ES tapeout

- https://github.com/lowRISC/opentitan/issues/20700
  - Documentation-only
- https://github.com/lowRISC/opentitan/issues/20415
  - Darjeeling only
- https://github.com/lowRISC/opentitan/issues/20030
  - Fixes test
- https://github.com/lowRISC/opentitan/issues/20029
  - Fixes test
- https://github.com/lowRISC/opentitan/issues/19819
  - Issue was mistakenly filed
- https://github.com/lowRISC/opentitan/issues/19259
  - Closed since the issue was not relevant
- https://github.com/lowRISC/opentitan/issues/19256
  - DV failure was fixed
- https://github.com/lowRISC/opentitan/issues/19044
  - Closed after checking this was not a problem
- https://github.com/lowRISC/opentitan/issues/16641
  - There was a fix for this issue 
- https://github.com/lowRISC/opentitan/issues/16562
  - Was not a real issue
- https://github.com/lowRISC/opentitan/issues/16384
  - Needs some feedback to really sort out the issue
- https://github.com/lowRISC/opentitan/issues/8538
  - Closed after analysis

## Currently open issues

- https://github.com/lowRISC/opentitan/issues/20798
  - This is an AST issue, and it is expected to be fixed for PROD. It refers to rstmgr since the issue causes a failure in a top-level test associated to rstmgr.
- https://github.com/lowRISC/opentitan/issues/20589
  - This issue relates to a test failure that has been diagnosed and it relates to a test environment problem, not an actual device defect.
- https://github.com/lowRISC/opentitan/issues/20194
  - This is a tracking issue for multiple blocks, and shows no open issues for rstmgr.
- https://github.com/lowRISC/https://github.com/lowRISC/opentitan/issues/20991#issuecomment-1950472455opentitan/issues/19797
  - Another tracking issue that shows no open items for rstmgr.
- https://github.com/lowRISC/opentitan/issues/19538
  - This is a multi-top issue that is not required for PROD.
- https://github.com/lowRISC/opentitan/issues/18258
  - This is a dv infrastructure issue, and does not suggest a functional problem. I think the issue is obsolete anyway.
- https://github.com/lowRISC/opentitan/issues/17300
  - This issue is open, but the use-case is unclear, and may not require hardware changes. It is mostly a USB issue, and refers to rstmgr only as a way to reset the USB block.
- https://github.com/lowRISC/opentitan/issues/16846
  - This is an AST issue related to lint checkers, and most likely should be closed.
- https://github.com/lowRISC/opentitan/issues/16640
  - This is a clkmgr issue, and it only relates to improving the coverage flow.
- https://github.com/lowRISC/opentitan/issues/16148
  - This is an enhancement request for block level, but the full-chip tests exercise the functionality and show no defects.
- https://github.com/lowRISC/opentitan/issues/15986
  - I doubt we should fix this for PROD, so I think it is not a relevant issue.
- https://github.com/lowRISC/opentitan/issues/15427
  - This issue needs to be discussed and we need to agree if anything is needed.
- https://github.com/lowRISC/opentitan/issues/15123
  - This seems to be a low priority issue, but needs resolution.
- https://github.com/lowRISC/opentitan/issues/13640
  - This is a non-indispensable enhancement.
- https://github.com/lowRISC/opentitan/issues/12848
  - This issue needs a better description, and it is documentation-only.
- https://github.com/lowRISC/opentitan/issues/11520
  - This is a non-indispensable enhancement.
- https://github.com/lowRISC/opentitan/issues/8945
  - This is a non-indispensable enhancement.
- https://github.com/lowRISC/opentitan/issues/8440
  - The rstmgr work in this issue was already completed.
- https://github.com/lowRISC/opentitan/issues/8185
  - This is not required for PROD, and perhaps we can just close the issue?
- https://github.com/lowRISC/opentitan/issues/7978
  - This won't be addressed for PROD, and perhaps the issue can be closed.
- https://github.com/lowRISC/opentitan/issues/7780.
  - This should not be done for PROD, and may be addressed for multi-top, though IMO it is low priority
- https://github.com/lowRISC/opentitan/issues/6220
  - This issue is open, and needs software feedback. Not necessarily a rstmgr issue though.
- https://github.com/lowRISC/opentitan/issues/3637
  - This is an fpga issue.
- https://github.com/lowRISC/opentitan/issues/2929
  - This is not an issue for rstmgr since it is generated by ipgen. The issue for clkmgr and flash_ctrl will also be gone once ipgen is completed for them.

## Summary

- The CSR testing infrastructure needs to be enhance to test MuBi regwens due to the failure to detect the bug leading to the RTL change in https://github.com/lowRISC/opentitan/pull/19575/commits/eb412d16d977211c11760f208a6370e6fb35ffa7 (1b16ca2122).
- The issue https://github.com/lowRISC/opentitan/issues/16384 needs a more complete analysis.

**Comment by msfschaffner** [comment]
Thanks @matutem. 
Agreed with the assessment.
No change needed in the Hjson since that still shows V2S:
https://github.com/lowRISC/opentitan/blob/c5faa9b8b368c89fcef131440ba906f62f9595d5/hw/ip_templates/rstmgr/data/rstmgr.hjson.tpl#L39-L44
