### ISSUE TITLE
[pwm] V2(S) Signoff

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#21038]
### Description

Ensure V2(S) signoff criteria are still maintained (this is not a focus area block).

**Comment by antmarzam** [comment]
# Commits since Earlgrey-ES tapeout

```
git log Earlgrey-M2.5.2-RC0..HEAD --oneline hw/ip/pwm/
```
61a237e197 [util/reggen] reverse order of substruct generation
de31bdf1c2 [reggen] Remove the devmode input
963a5006cc [doc] Minor tweak to md sanitisation code
bfd4f7823e [pwm,SiVal] Add feature list to `pwm.hjson`
1b16ca2122 [reggen] Add mubi support SWAccess that sets/clears a reg
59f8142826 [doc] Moved badges over to using hosted images
c9cdb74959 [doc] pwm registers and interfaces now use CMDGEN
7688e714e8 [reggen] Add initial support for version and cip_id hjson fields
fbd888eea8 Revert "[reggen] Add CIP_IDs and bump all major versions"
0ba10b3cd3 [reggen] Add CIP_IDs and bump all major versions

## Issues closed since the Earlgrey-ES tapeout
- #17696 
chip-level test
- #16689 
DV change
- #16562 
Community support issue

## Currently open issues
- #19841
 chip-level test
- #19797 
- SW test
- #19234 
DV: moved to the backlog 
- #18390 -> //TODOs  are still present in the TB 
- #17913
moved to a later prod stage
- #17369
Missing covergroups defined in the testplan -> moved to a later prod stage 
- #16734 
Chip-level test
- #13588 -> //TODOs for a later sign-off stage
- #9999 -> Doc issue, moved to a later stage
- #9830 -> DD/DV issue (TB should catch this): moved to a later sign-off stage
- #3421 -> moved to backlog




### Coverage report from 25/02/2024
The following report comes from the nightly regression dashboard (hash#[[49a27e136c](https://github.com/lowrisc/opentitan/tree/49a27e136c7b79a3c738dd77cdae3764e19210c0)])

![Screenshot from 2024-02-29 12-25-45](https://github.com/lowRISC/opentitan/assets/156205999/38f77372-4ae3-4094-951d-5e0d0dbaeee1)



The passing rate is over 88% for all verification stages (inc V2S). Though there are intermittent failures in `pwm_rand_output` and `pwm_stress_all`. 

### Summary
There aren't outstanding changes required for this stage. @rswarbrick / @msfschaffner  Could any of you take a look to make sure you agree with this?

**Comment by rswarbrick** [comment]
I've gone through the checklist carefully. I think I agree with your notes.

The #18390 issue looks like a genuine bug: we should probably just fix it instead of punting further! But that's something I'd be arguing if we were having a "from scratch V2 review", rather than confirming that nothing has regressed. I'm happy to keep the existing V2S stage.
