### ISSUE TITLE
[aon_timer] V2(S) Signoff

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#21030]
### Description

Ensure V2(S) signoff criteria are still maintained (this is not a focus area block).

**Comment by antmarzam** [comment]
### Commits since Earlgrey-ES tapeout
```
git log Earlgrey-M2.5.2-RC0..HEAD --oneline hw/ip/spi_device/ hw/dv/sv/spi_agent/
```
599ab38d27 [spi_device] Update block diagram for TPM / generic mode
2d1e029c82 [spi_device] Add read pipeline diagram
1d2e3fe49a [spi_device] Remove data transfer diagram
094cb9f0f2 [spi_device] TPM port name change: rst_n -> rst_ni
2f0b93372a [spi_device] Fix up TPM synchronization between domains
4ed1a8f639 [spi_device] Add synchronous clear to spid_fifo2sram_adapter
9b5f4e05da [spi_device] Clean up TPM address check
cbda9eaf09 [spi_device] Fix up TPM command handling
0d14dd693f [docs] Fix repetitions of the definite article
39cfb3ee40 [spi_device] Remove all timing mode CSRs
4c3debe8c3 [spi_device] Document the high-speed read pipeline
7f855dc3cb [spi_device] Add pipelined reads for flash / passthrough
f28b713409 [spi_device] Remove generic mode mentions
56c127c24b [spi_device] Write mode and status bits alongside command
d914f7532d [spi_device] Enable continuously polled status registers
aff3fbd111 [reggen] Add unused we field statement for hwext
81cfbe0cfd [spi_device] Harmonize address mode syncs to byte beats
40a6acefc1 [spi_device] Relax stringent CSB pulse width requirements
61a237e197 [util/reggen] reverse order of substruct generation
f83506bbdb [spi_device] Add params for DPRAM offsets
f554d45fc8 [spi_device] Add support for 1r1w RAMs and parity init
fc8484601e [reggen,hw] Create index parameter for registers windows
726cd46d0a [spi_device] Remove generic mode
de31bdf1c2 [reggen] Remove the devmode input
963a5006cc [doc] Minor tweak to md sanitisation code
f91b5b47a4 [spi_device] Add 'features' list to spi_device.hjson
1b16ca2122 [reggen] Add mubi support SWAccess that sets/clears a reg
59f8142826 [doc] Moved badges over to using hosted images
e85f47cbfb [doc] spi_device registers and interfaces now use CMDGEN
7688e714e8 [reggen] Add initial support for version and cip_id hjson fields
fbd888eea8 Revert "[reggen] Add CIP_IDs and bump all major versions"
0ba10b3cd3 [reggen] Add CIP_IDs and bump all major versions
93783054f3 [regtool] Correct register QE assignment

### Issues closed since the Earlgrey-ES tapeout

### Currently open issues

### Coverage report from xx/xx/xxxx

### Summary

**Comment by andreaskurth** [comment]
Thanks for the analysis @antmarzam. I agree with bringing aon_timer back to V2S. The open DV issues listed above can be resolved as part of coverage closure for M4 (or M5), which they are currently assigned to.

**Comment by GregAC** [comment]
@andreaskurth @antmarzam apologies for not flagging this earlier but this is an issue with the aon_timer testbench that requires looking at: **https://github.com/lowRISC/opentitan/issues/22313**

I spotted this a little while ago, forgot to fail and issue and was reminded by seeing the activity on this issue.

**Comment by andreaskurth** [comment]
Thanks @GregAC. Resolving #22313 as part of M4 SGTM, so I think this shouldn't block this signoff. Does that SGTY?

**Comment by GregAC** [comment]
@andreaskurth SGTM, can view it as a test bench bug that is reasonably addressed post V2
