### ISSUE TITLE
[hmac] V1 Signoff

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#21031]
### Description

Ensure V1 signoff criteria are fulfilled after focus area changes have landed.

**Comment by andreaskurth** [comment]
`hmac_smoke` passes 100% according to [current nightly results](https://reports.opentitan.org/hw/ip/hmac/dv/latest/report.html). The only other [V1 checklist item](https://opentitan.org/book/doc/project_governance/checklist/index.html#v1) I think needs a more detailed look is [TESTPLAN_COMPLETED](https://opentitan.org/book/doc/project_governance/checklist/index.html#testplan_completed) to check that the RTL changes since Earlgrey-ES TO are covered by an existing test or captured in the testplan. According to the [D2S signoff analysis](https://github.com/lowRISC/opentitan/issues/20996#issuecomment-2025029674), the main changes are:
- #21604: DV tracked for M4 in #22102 
- #21307: DV tracked for M4 in #21708
- #21809: DV tracked for M4 in #21815

Thus, I think we can sign off hmac at V1 once we have added the items above to the testplan. I'd create a PR to do both and close this issue. Do you agree, @gdessouky?

**Comment by vogelpi** [comment]
The proposed plan of actions sounds good to me @andreaskurth . Let me know when the testplan PR is ready and I am happy to approve it.
