### ISSUE TITLE
[top_darjeeling] Lifecycle controller `lc_owner_seed_sw_rw_en_o` signal not connected

### ISSUE THREAD

**Issue by loiclefort** [lowRISC/opentitan#21044]
### desc

Not sure if this is an oversight or if this is by design but lifecycle controller `lc_owner_seed_sw_rw_en_o` signal is not connected in `top_darjeeling`.
On Earlgrey, this signal is used to prevent software access to owner seed located in internal flash.
On Darjeeling, only `lc_creator_seed_sw_rw_en_o` is connected:
- owner seed has moved to OTP (SECRET3 partition)
- both SECRET2 (silicon creator seeds) and SECRET3 are marked as `iskeymgr`
- software access to `iskeymgr` partitions is gated by `lc_creator_seed_sw_rw_en_o`
- `lc_creator_seed_sw_rw_en_o` follows `otp_lc_data_o.secrets_valid` (or is false, depending on LC_STATE)
- `otp_lc_data_o.secrets_valid` is true if SECRET2 partition is locked

AFAIU, this means that SECRET2 and SECRET3 must be provisioned at the same time, starting with SECRET3.

**Comment by neeraj-rv** [comment]
Good catch @loiclefort 
@msfschaffner and @andreaskurth are looking at it

**Comment by msfschaffner** [comment]
Thanks for reporting this! I made a patch for this here https://github.com/lowRISC/opentitan/pull/21116 - PTAL.

This basically splits the `iskeymgr` in the memory map definition into the two flavors `iskeymgr_creator` and `iskeymgr_owner` so that one can choose which lifecycle signal to associate the key material with. This should solve the sequencing issue with provisioning that you reported.

A few things to note:
- Secret partitions become unreadable by SW after locking, no matter the LC enablement signal
- Secret partitions holding key material do not output their contents to the keymgr until they are locked, no matter the LC enablement signal
- In addition to the previous point, all secret material is additionally modulated by `lc_seed_hw_rd_en` which is only asserted if at the creator root key has been provisioned.

This basically means that while the owner and creator key material / seeds can be provisioned separately now, we still require that both partitions be provisioned in order to use the key material in the key manager.

**Comment by Razer6** [comment]
Lets close this as the associated PR has been merged.
