### ISSUE TITLE
[spi_device] Change of interrupt types to status

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#21207]
### Description

Split out from https://github.com/lowRISC/opentitan/issues/15378:

Change the following interrupts to status type:
- [ ] readbuf_watermark
- [ ] upload_cmdfifo_not_empty
- [ ] upload_payload_not_empty

**Comment by msfschaffner** [comment]
FYI @jesultra

**Comment by jesultra** [comment]
Does it make sense to discuss these small refinements, before it is settled whether some major redesign of the SPI device IP will be done?

**Comment by a-will** [comment]
`upload_cmdfifo_not_empty` is a misnomer. For one thing, the source is a pulse event from another domain, and for another, spi_device can't actually handle multiple flash commands (nor would it follow the usual flash protocols if it did, since the BUSY bit should guard against a second long-running command being accepted). I think we should leave this as an event.

`upload_payload_not_empty` can't be a status, and it would more appropriately be called something like `upload_payload_written`. The payload buffer presents a RAM interface to software, so there is no concept of emptying a FIFO.

**Comment by a-will** [comment]
`readbuf_watermark` also doesn't seem to be able to be a status type, as the read buffer _also_ doesn't work like a FIFO with depth tracking. That could potentially be changed, but I don't think that is in scope for M2.

Thus, I recommend no change to spi_device's interrupts. @msfschaffner @jesultra Do you agree? Can we close this?

**Comment by jesultra** [comment]
No change here sounds good to me.
