### ISSUE TITLE
[spi_host] Change of interrupt types to status

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#21208]
### Description

Split out from https://github.com/lowRISC/opentitan/issues/15378:

spi_host: It seems that six different sources are combined into one event-type interrupt, spi_event. Four of them are clearly status type (RXFULL, TXEMPTY, RXWM, TXWM), the other two READY and IDLE could also work as status-type, so I would like to ask that the entire spi_event interrupt become status-type. (Already, the description of e.g. RXFULL makes it sound as if status-type logic applies, "To prevent the reassertion of this interrupt, read more data from the RX FIFO, or increase CONTROL.RX_WATERMARK.")

**Comment by msfschaffner** [comment]
CC @jesultra @moidx

**Comment by msfschaffner** [comment]
Completing this issue should also address https://github.com/lowRISC/opentitan/issues/12989

**Comment by jettr** [comment]
The idle and ready interrupts do seem somewhat suited to be event style instead of status since the host controller may not need to take any further action if there is no more data waiting to be sent out.

However, if idle and ready were event style interrupts, then FW would have to take special care to enable interrupts then check status bit in that order when FW wants to initially take action on the SPI state.

If idle and ready were status-style interrupts, then FW has manage enabling/disabling `EVENT_ENABLE.IDLE` and `EVENT_ENABLE.READY` instead of leaving the them always enable and just getting the initial  set up correct.

It is manageable either way in FW, and it seems simplier from the hardware perspective to make everything a status, so making all 6 interrupts mentioned in the first comment SGTM.
