### ISSUE TITLE
[DVSIM] Unable to use test case name during makefile build phase

### ISSUE THREAD

**Issue by yandaweixx** [lowRISC/opentitan#21545]
### Description

Hello everyone, I would like to use the content of the {test} variable during the dvsim build phase, which is used to generate the run_dir_name in common_sim_cfg.hjson, but it seems that I cannot retrieve it. It can only be obtained from the command line -i parameter during the run phase. Is there any way to solve this?

**Comment by rswarbrick** [comment]
Hi there,

You're right: the `{test}` variable doesn't have a value in the build phase. The reason is that we build a whole bunch of tests at once in the build phase, and then run them by name in the run phase.

I'm not sure what you're trying to do, but we might be able to help. I suggest you re-open this issue when you have a specific question/problem and we might be able to help.
