### ISSUE TITLE
[rom] Reading resistor straps should differentiate weak versus strong pulls

### ISSUE THREAD

**Issue by jettr** [lowRISC/opentitan#21630]
If the ROM only performs a single read operation on the resistor strapping pins, then it will not be able to tell the difference between weak (e.g. 1M) and strong (e.g. 5.1k) pull resistors. This effectively eliminates the possibility of using the weak pulls values for the owner firmware if that aliases to a known ROM bootstrap combination.

https://github.com/lowRISC/opentitan/blob/2714197f3235f1737937ad20421a3f32ff4a7030/sw/device/silicon_creator/rom/bootstrap.c#L46

Right now there are 2 resistor straps combinations on IOC0, ICOC1, and ICO2:

[SW_STRAP_BOOTSTRAP](https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/silicon_creator/lib/base/chip.h;drc=1ff6f6ea02a1711224a284a8855264406750eabd;bpv=1;bpt=1;l=98?gsn=SW_STRAP_BOOTSTRAP&gs=KYTHE%3A%2F%2Fkythe%3A%2F%2Fgithub.com%2FlowRISC%2Fopentitan%3Flang%3Dc%252B%252B%3Fpath%3Dsw%2Fdevice%2Fsilicon_creator%2Flib%2Fbase%2Fchip.h%23SW_STRAP_BOOTSTRAP%2523m%25402500): Strong PUp,  Strong PUp,  Strong PUp

and 

[SW_STRAP_RMA_ENTRY](https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/silicon_creator/lib/base/chip.h;drc=1ff6f6ea02a1711224a284a8855264406750eabd;bpv=1;bpt=1;l=89?gsn=SW_STRAP_RMA_ENTRY&gs=KYTHE%3A%2F%2Fkythe%3A%2F%2Fgithub.com%2FlowRISC%2Fopentitan%3Flang%3Dc%252B%252B%3Fpath%3Dsw%2Fdevice%2Fsilicon_creator%2Flib%2Fbase%2Fchip.h%23SW_STRAP_RMA_ENTRY%2523m%25402241): Strong PDown, Strong PUp, Strong PUp

However if Owner Firmware wants to use  Weak PUp, Weak PUp, Weak PUp, then the ROM will incorrectly think that the `SW_STRAP_BOOTSTRAP` combination is getting triggered.

With 3 pins that should be able to detect 4 states, we should have a total of 4 ^ 3 = 64 available strapping combinations. If the ROM doesn't differentiate between strong and weak pulls, then the 2  out of 64 values it tries to reserve actually turn into to 16 out of the 64 that are unusable by the owner firmware.

It is entirely possible that I misread the code and this isn't a problem, but I definitely wanted to double check there won't be any conflicts between ROM strap values and our Owner Firmware strap values.

**Comment by cfrantz** [comment]
The ROM code is correct and only a single read is required.

The reason we need only a single read at that location is that the pinmux is already initialized with the internal pulldowns activated so that a weak pull-up will not be read as a logic-high.

There are tests in `//sw/device/silicon_creator/rom/e2e/weak_straps` that test all 64 strap combinations and confirm that only the ROM_BOOTSTRAP (`111`) and RMA_BOOTSTRAP (`110`) patterns are recognized by the ROM.

**Comment by cfrantz** [comment]
The correct operation of strap detection can be independently verified on the ES chip by running an `opentitantool console` in one window and the [teacup-strapping.sh](https://gist.github.com/cfrantz/2c80e9380ddf05a93f7b61f9b538f757) script in another.

- For strapping value 63, you will see the ROM respond with `bootstrap:1`.
- For strapping value 60, you will see nothing because the ROM hangs (and bootloops) to wait for the JTAG LC-tap connection.
- For all other values, the next stages (ie ROM_EXT and owner code) will boot.  If you happen to be running the test binary associated with `//sw/device/silicon_creator/rom/e2e/weak_straps:sw_strap_value`, it will read the straps and print the value when it starts.
