### ISSUE TITLE
[sw] Avoid use of early return due to security concerns

### ISSUE THREAD

**Issue by sriyerg** [lowRISC/opentitan#2179]
Context: https://github.com/lowRISC/opentitan/pull/2150#discussion_r421699144

According to @cdgori, a security-oriented coding style recommendation is for functions (in prod software) to have only a single return. Early returns are to be avoided. Considering we are doing this in all of our DIF code, filing an issue for further discussion.

**Comment by cdgori** [comment]
I think one of the big reasons is in the case of any clean-up steps necessitated by a return, we can guarantee the execution of those steps, whereas in multiple/early return cases it's possible to either have to duplicate code, or inconsistent handling of clean-up.

It's generally easier to review a single return (for me) as well.  But the `break`/`goto` needed to make it work can be equally ugly in some cases.

**Comment by tjaychen** [comment]
@mundaym @cfrantz 
since DIF is not really meant to be production code anymore, but rather more examples and for testing purposes, does this issue still make sense? I'm also certain there's probably a software secure guideline somewhere that already accounts for these ideasl

In other words, feels like this issue can be closed.

**Comment by cfrantz** [comment]
This is certainly not a concern for DIFs or test code.

I'm not sure about the validity of this advice with respect to compiler optimization.  Its rather typical for the compiler to generate a single function epilogue and have all early returns in the high-level language turn into jumps to the single exit point (with the result pre-loaded into the ABI's result register.  IMHO, this is isomorphic to the advice given in the linked comment).

The Mask ROM code already has plenty of infrastructure to defeat the optimizer when needed in order to double-check results and ensure control flow integrity.

I think we can close this issue.

**Comment by tjaychen** [comment]
thanks @cfrantz
