### ISSUE TITLE
[lc_ctrl,dv] Regression results lost for one config of lc_ctrl tests

### ISSUE THREAD

**Issue by a-will** [lowRISC/opentitan#22122]
https://reports.opentitan.org/hw/top_earlgrey/dv/summary/latest/report.html ended up running tests for both configs for lc_ctrl, but one of them seems to have no results for the majority of tests:

https://reports.opentitan.org/hw/ip/lc_ctrl/dv/2024.03.18_04.36.41/report.html

_Originally posted by @a-will in https://github.com/lowRISC/opentitan/issues/22104#issuecomment-2007877974_

**Comment by rswarbrick** [comment]
Marking this as part of M4 since the bug currently means we can't extract nightly test results for one config. The fix should be reasonably easy: we can nick the code that's already doing this correctly for AES, KMAC, sram_ctrl.

If we fix this, we should probably extend the fix to `rom_ctrl` as well, which has the same issue.
