### ISSUE TITLE
[ci,i2c] Re-enable "i2c_host_eeprom_test" in CI

### ISSUE THREAD

**Issue by hcallahan-lowrisc** [lowRISC/opentitan#22347]
### Description

This test was disabled in https://github.com/lowRISC/opentitan/pull/22346 as it broke, this issue tracks its re-enablement.

**Comment by andreaskurth** [comment]
This test might have been broken by #22049, where [this test failed](https://dev.azure.com/lowrisc/opentitan/_build/results?buildId=147244&view=logs&jobId=d89e056e-6446-5926-00a7-11a2b28fa178&j=d89e056e-6446-5926-00a7-11a2b28fa178&t=a49a45e3-0956-5a06-797b-44acbb659374) (for the first time?).

**Comment by moidx** [comment]
I2C DV carried over to M5.

**Comment by hcallahan-lowrisc** [comment]
This test likely broke because the software was not updated to handle and acknowledge a NACK event, causing the hardware to halt indefinitely awaiting this action.

**Comment by pamaury** [comment]
The software issue was fixed with #23772 but the `i2c_host_eeprom_test_rom` test still fails around 1% of the time. Debugging suggests that this is a UART issues on the CW310 since the test logs quite a bit of data. In contrast, `i2c_host_eeprom_sival` nevers fails with the fix and it uses hyperdebug for UART. Therefore the options are:
- keep both test enabled, but keep in mind that the random failures are unrelated to i2c,
- or disable specifically the test_rom and only keep the sival version.

**Comment by johngt** [comment]
Thanks @pamaury - flagging to @timothytrippel / @cfrantz to see what they would like to do with this.

**Comment by hcallahan-lowrisc** [comment]
Thanks @pamaury ! Based on your comment, and that any remaining issues with this test are more likely UART-related, I'm going to close this issue. I presume that ongoing UART issues are tracked already in open issues, so can we possibly link the failure modes you are now seeing with one of the pre-existing issues? If not, would you mind opening a new issue? If you disagree, please feel to re-open this one. Thanks :)
