### ISSUE TITLE
[csrng] V2S Signoff

### ISSUE THREAD

**Issue by andreaskurth** [lowRISC/opentitan#22467]

**Comment by moidx** [comment]
Discussed moving as P1 to M5 due to RTL risk analysis performed during last issue triage.

**Comment by vogelpi** [comment]
I will collect the required information and update the issue on THU. In short, we almost signed of CSRNG at V2S as part of M2 but had to [signoff at V1 instead](https://github.com/lowRISC/opentitan/issues/21011) for the following reason:
- The branch and expression coverage dropped to below 90%.

This drop occurred a long time ago and unrelated to the M2 work. It's tracked in #19033 and @h-filali is investigating this (he'll return tomorrow).

**Comment by vogelpi** [comment]
## Commit since Earlgrey-PROD.M2

For Commits since Earlgrey-ES tapeout, see https://github.com/lowRISC/opentitan/issues/20976#issuecomment-2027839323 .

`git rev-parse --short HEAD` 45565ef186

`git log 9ddf276..HEAD --oneline hw/ip/csrng`
b633a21801 [csrng/dv] Exclude AES core from coverage analysis
-> Changes to the AES core for reducing CSRNG area prior to M2 made it necessary to adjust the coverage exclusions.
66e3f8e21f [csrng/dv] Fix sfifo_gadstage_err and sfifo_gbencack_err tests
e1f34675a7 [csrng/dv] Fix syntax causing vcs to fail
763bf42672 [dv] Reduce number of seeds for stress_all_with_rand_reset tests
b447bf7c06 [csrng/rtl] Make the main SM error test signal fatal
-> Fix a minor discrepancy compared to ENTROPY_SRC and EDN (see also 01551bc32e)
afd59fca01 [csrng/dv] Add the right err_test codes to fatal errors
6381071bac [csrng] Flush command FIFO after signaling ACK errors
-> RTL bug fix to respect valid/ready handshake protocol in error case and fix error signaling between EDN and CSRNG (see https://github.com/lowRISC/opentitan/issues/23526)
89d7f21bfa [csrng/dv] Correct prediction of FIPS/CC compliance flag for UNI cmd
01551bc32e [csrng] Locally escalate upon FSM errors
-> Aligning error / local escalation behavior with ENTROPY_SRC and EDN
16d7604335 [csrng/dv] Disable some SVAs during fatal error injection in csrng_intr
3a4c42f721 [csrng] Add per-instance internal state read enable
c903d65d25 [csrng] Make reseed counters readable at any point in time
-> RTL fixes related to #23539 
3b47465d33 [csrng/dv] Add DV for forced fips flag
baa7e6a8cf [csrng/doc] Correct documentation around INVALID_ACMD errors
eecef82d6d [csrng/doc] Use enum type for SW_CMD_STS.CMD_STS field
8577cceb8a [csrng] Add option to force FIPS/CC compliance flag
-> RTL fix for #23324
3931c3255d [csrng/rtl] Check for GENU instead of GEN for CMD_STS_INVALID_GEN_CMD
-> RTL bug fix
604d2b2791 [csrng/doc] Correct the documentation for invalid application commands
bb02ff0cf4 [csrng/dv] Add DV for the cmd status responses
73b62e5700 [csrng/dv] Add command status checks to send_cmd_req
b9e0388ab1 [csrng/rtl] Move cmd checks to the cmd stage
7f84f7cdb8 [csrng/rtl] Add reseed interval status error
-> RTL changes to improve error handling and reporting
28ddb84d2b [csrng/dv] Add missing type declaration
fa7af7a20e [csrng/dv] Fix forcing of ack_sts signals in csrng_intr vseq
da67f469dd [csrng/dv] Remove disabling/enabling of reworked and renamed SVA
0c397d7073 [csrng] Add SVAs to check for unexpected pushes to the genbits FIFO
b65b9ef718 [csrng/rtl] Fix lint error
1d12ff7a6c [csrng/rtl] Remove zeroize state after uni error from ctr drbg cmd
-> Remove an uneeded RTL check that should rather be checked using an SVA
903b319171 [csrng/rtl] Add command out of sequence cmd_sts error
042e0b9158 [csrng/rtl] Change and assign cmd_sts signal
-> RTL changes to improve error handling and reporting
8295903d7e [bazel,autogen_hjson] Split C and rust header generation
30d7e787c7 (tag: Earlgrey-PROD-M2-RC5, tag: Earlgrey-PROD-M2) Add the project name to the copyright header
c2dd19d802 [csrng] Increase version number, revert verification stage to V1

## Issues closed since Earlgrey-PROD.M2 - WIP

For issues closed since Earlgrey-ES tapeout, see https://github.com/lowRISC/opentitan/issues/20976#issuecomment-2027839323

- #3353
- #8120
- #15393
- #15561
- #15729
- #15894
- #16516
- #16563
- #16846
- #17772
- #19293
- #19568
- #19789
- #20468
- #20818
- #20953
- #20976
- #20978
- #20981
- #20982
- #20983
- #20986
- #20988
- #20993
- #21017
- #21018
- #21028
- #21155
- #21652
- #21686
- #22121
- #22209
- #22352
- #22385
- #22468
- #22524
- #22732
- #22753
- #22819
- #22997
- #23131
- #23526

## Currently open issues - WIP

- #7826
- #10738
- #14363
- #15337
- #16017
- #16269
- #16565
- #16572
- #16593
- #16636
- #17109
- #17595
- #18350
- #18649
- #18797
- #19031
- #19356
- #19361
- #19797
- #19846
- #19847
- #19848
- #20194
- #21222
- #21495
- #21706
- #21888
- #21936
- #22117
- #22127
- #22157
- #22219
- #22241
- #22283
- #22293
- #22301
- #22366
- #22467
- #22633
- #22666
- #22705
- #22799
- #22833
- #22850
- #22851
- #22869
- #23179
- #23606
- #23663
- #23773

## Coverage report from 2024-06-24 - WIP

## Summary

**Comment by vogelpi** [comment]
@h-filali , I've now updated the sign-off issue / comment above to reflect the latest changes. Would mind reviewing this please?

**Comment by h-filali** [comment]
@vogelpi I double checked the dashboard and I agree. The coverage metrics are all above 90% and the failing tests consist of mainly stress_all_with_rand_reset which is V3 and some rare failures on other tests (<6%). This has been consistently the case for multiple weeks (apart from where we had some general regression issues).
I double checked the commits and they are the same for me.
I double checked if the relevant CSRNG issues that I could find (closed or open) are all mentioned here.
I double checked that the issues that are mentioned here all are relevant for CSRNG.
This signoff issue LGTM! Great work ^^
