### ISSUE TITLE
[sensor_ctrl] D3 Signoff

### ISSUE THREAD

**Issue by rnongie** [lowRISC/opentitan#22651]

**Comment by andreaskurth** [comment]
## Analysis of changes since previous signoff

sensor_ctrl got previously signed off at D3 in 9f31bc3b2ea59614655532e00294248f7bbbb04a and that wasn't changed when the version was increased to 2.0.0 in d352f0cf45299ed1a9715ca72fce052be21cb00b. So technically, sensor_ctrl is currently still signed off at D3. For completeness' sake, however, here are the changes since the previous D3 signoff (`git log --pretty=oneline 9f31bc3b2ea59614655532e00294248f7bbbb04a..HEAD hw/top_earlgrey/ip/sensor_ctrl/rtl | tac`, thus old to new):
* e063764dd06f0c61dad3f992cee794d13679c716 [tlul] Add access latency and ifetch to adapter_reg
* 0ba10b3cd3157d233c6a9a21676b058971399b99 [reggen] Add CIP_IDs and bump all major versions
* fbd888eea85260f03095b7b7f12537638ca27183 Revert "[reggen] Add CIP_IDs and bump all major versions"
* 1b16ca2122d956f4b1f909ba2e996b01ff22001e [reggen] Add mubi support SWAccess that sets/clears a reg
* de31bdf1c26be2714ca787c6041a56eb56eb7d1e [reggen] Remove the devmode input
* eef87110bb60997becccdf1cec4ed736ea673b99 [rtl,sensor_ctrl] Fix CDC bug
* 61a237e1973d6a29d377c2be871139553c7d344f [util/reggen] reverse order of substruct generation
* d352f0cf45299ed1a9715ca72fce052be21cb00b [sensor_ctrl] Add enable register for AST alerts
* 30d7e787c753caaa03fe68a4a70da1bbcbc1d96f Add the project name to the copyright header
* 8b15c287f8b8e5618681b4d9d1a28ea7d400ed72 [top_earlgrey,sensor_ctrl] Add input disable attribute for manual pads
* 4c15bdc9fa0d882c5d53068d9d86658c2a48ee07 [sensor_ctrl] Change reset value of `ALERT_EN` CSRs to MuBiTrue
* 39157f7a7ac94e42f05cde9daa8ae8cde9d900e1 [top_earlgrey,sensor_ctrl] Add pull attributes for manual pads
