### ISSUE TITLE
[fpv] Investigate prim and top-level IP FPV results and figure out what to do

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/opentitan#22721]
### Description

The following two regressions have several tests with pass rates below 100% and with some tests not running (reporting N/A):
- https://reports.opentitan.org/hw/top_earlgrey/formal/ip/summary/latest/report.html
- https://reports.opentitan.org/hw/top_earlgrey/formal/prim/summary/latest/report.html

We should investigate what we did for those in the past and decide whether that is acceptable. For some tests, pass rates were never 100% as outlined [here](https://github.com/lowRISC/opentitan/issues/22385#issuecomment-2059075443). IIRC, pinmux is mainly verified using FPV, so not having any results is probably not acceptable but I might be wrong about this.

Factored out of [#22385](https://github.com/lowRISC/opentitan/issues/22385).

**Comment by rswarbrick** [comment]
For the failing pinmux tests, PR #22754 should get them running again.

**Comment by andreaskurth** [comment]
@rswarbrick: How much effort is left just to get pinmux numbers above the limit, what do you think?

**Comment by rswarbrick** [comment]
I spent some time looking at this yesterday and the answer is "quite a bit, for coverage" and also "but maybe the limit is wrong".

In more detail, across all the FPV tests in the issue:
- Pass rates are mostly high.
  - The `pinmux_fpv` pass rates from last weekend were low, but these should have been fixed by #23216 (which was merged on Tuesday)
  - Other pass rates are high, except for `prim_fifo_sync_fpv` and `prim_fifo_async_sram_adapter_fpv`. These are both tooling issues: probably worth working around in each case, but neither shows meaningful missing test coverage.
- Coverage numbers for the IP FPV results (including for pinmux) are currently well under the 90% limit
  - I think they are currently better than they were when we taped out the ES chip(!), so we probably weren't too worried then...
  - There is some sensible work that we could do to include the coverage numbers, but it can probably reasonably go an the back burner.
- Finally, the headers in the FPV results aren't quite right. The tool calls the columns "Formal coverage", "Stimuli coverage" and "Checker coverage" in that order. I'm not sure, but maybe the names in our Python match the Jasper version that was in use by the Google team in 2020.
  - I have a fix for this and I'll push it up (when I'm using the right computer!) next week.

**Comment by vogelpi** [comment]
Thanks for your investigations @rswarbrick. IIRC, FPV is run weekly, so we'll get an update for #23216 next Monday. 

IIRC you've also investigated the coverage gaps and reported that most of these gaps were due the COIs of our assertions not touching the signals in question, in particualr inside `u_reg`, and further that this most likely hasn't been covered before. Further, you've also been checking the ` Earlgrey-M2.5.2-RC0` tag again and the results look better now.

Based on this, I am supportive to conclude this work for Earlgrey-PROD / close this M4 issue. It would probably be worth to document the open gaps and outline the next steps for closing these. This would give us a starting point for the future and will speed up things when we decide we need to more work here. Let's discuss this in the issue triage meeting.

**Comment by andreaskurth** [comment]
Discussed in triage: No regressions w.r.t. Earlgrey-ES. We also have added top-level test cases to cover pinmux permutations. prims are a known gap. The `PROVE_COV` from `prim_onehot_check` looks concerning, though. @rswarbrick What are your thoughts on that one?

**Comment by rswarbrick** [comment]
It's not all that bad:
```
|+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++|
| Instance Name                                              | Formal                                   | Stimuli                                  | Checker                                  |
|                                                            | Coverage                                 | Coverage                                 | Coverage                                 |
|+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++|
|prim_onehot_check                                           |100.00% (3/3)                             |100.00% (3/3)                             |0.00% (0/0)                               |
|+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++|
```

Maybe `0/0` should appear in grey in some way, rather than being a red `0%`. But there's no uncovered item here.

**Comment by vogelpi** [comment]
@vogelpi to take a look

@rswarbrick future work would probably be to work around tooling issues (about prim). For pinmux it's just coverage.

@moidx much better than what we had before!

**Comment by vogelpi** [comment]
The latest regression results look as follows. 
- IPs:
![fpv_regression_pinmux](https://github.com/lowRISC/opentitan/assets/20307557/aaf8f1a3-4e5a-448c-a0a3-5162269d9a8e)

- prims:
![fpv_regression_prim](https://github.com/lowRISC/opentitan/assets/20307557/a588313f-d411-420f-b302-b3bca6a54bd8)

As previously mentioned, we're done here. I am closing this issue and will create a new one to track potential future work (low priority). Thanks @rswarbrick for the hard work here!

**Comment by vogelpi** [comment]
The new issue is here #23499
