### ISSUE TITLE
[edn] Investigate why there are many EDN requests after ROM_EXT

### ISSUE THREAD

**Issue by pamaury** [lowRISC/opentitan#22819]
### Description

When working on the `edn_kat` test, I have identified a strange behaviour that only seems to happen when running the ROM_EXT: there seems to be too many requests going through the EDN. Specifically, we stop the entropy complex, setup the EDN in auto mode and start gathering 10 words of entropy thought the Ibex. By the time the Ibex has gotten 10 words, CSRNG reports that it got 150 requests through EDN0 (each generate commands generates 16 words).

Investigate why this number is so high.

Ping @vogelpi @h-filali

**Comment by andreaskurth** [comment]
By @vogelpi: Could be that a configuration in ROM_EXT triggers this. Maybe KMAC?

By @moidx: I'll take a look and add my findings here.

**Comment by vogelpi** [comment]
Together with @pamaury, I've been able to track down the issue: keymgr has an [internal, SW-configurable timer to automatically reseed it's local PRNG](https://opentitan.org/book/hw/ip/keymgr/doc/registers.html#reseed_interval_shadowed). The current ROM_EXT implementation doesn't alter the default value of 0x100, meaning keymgr is constantly reseeding it's internal PRNG every 256 clock cycles.

What's really problematic about this is that the counter doesn't currently factor in whether the PRNG is actually advanced or not. This is problematic as it leads to several issues:
- High idle power consumption #22241
- KATs on EDN0 become impossible

For now, ROM_EXT should probably be changed to configure the max reseeding interval of 65536 clock cycles. This will still request a reseed operation every 655us which is not going to be sufficient, but it might already help against some of the issues we have seen on different fronts. FYI @moidx @timothytrippel 

I am filing another issue start discussing design changes for keymgr, because we really should change this and there are easy changes we can do.

**Comment by vogelpi** [comment]
Update: the following changes have been made to alleviate/fix the underlying issue:
- The cryptolib EDN configuration has been adjusted to do more longer and more Generate commands between Reseed commands. See #22716,  #22972,  #22944
- The keymgr hardware has been fixed to only count up the reseed counter when actually using the PRNG. See #22951.
- The keymgr configuration used in ROM_EXT should be adjusted to do fewer reseed operations of the internal PRNG. I'll file an issue to track this.
