### ISSUE TITLE
[test] Fix test timeouts

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#22871]
### Description

The following targets are broken due to `TIEMOUT` as of https://github.com/lowRISC/opentitan/pull/22744:

- [ ] //sw/device/silicon_creator/lib/sigverify/sphincsplus/test:verify_test_hardcoded_fpga_cw310_sival_rom_ext
- [ ] //sw/device/tests/autogen:alert_test_fpga_cw310_sival_rom_ext 
- [ ] //third_party/riscv-compliance:I-CSRRW-01_fpga_cw310_sival_rom_ext

**Comment by AlexJones0** [comment]
These have been re-enabled by #25398 because the nightly SiVal runs showed that the first two seem to be consistently passing (> 30 runs) without any timeout issues, and manual testing of many iterations of the `riscv-compliance` test target also seems to pass consistently on an FPGA. This suggests that the underlying issues have since been resolved. Please do re-open if you feel that anything has been missed here.
