### ISSUE TITLE
[doc] Setup FPGA guide with openocd is incorrect

### ISSUE THREAD

**Issue by pamaury** [lowRISC/opentitan#22881]
### Description

On https://opentitan.org/guides/getting_started/setup_fpga.html, the guide says to run
```
./bazelisk.sh run //third_party/openocd -- \
    -f "bazel-opentitan/$(./bazelisk.sh outquery //third_party/openocd:jtag_adapter_cfg)" \
    -c "adapter speed 500; transport select jtag; reset_config trst_only" \
    -f util/openocd/target/lowrisc-earlgrey.cfg
```
but `jtag_adapter_cfg` does not exists.

**Comment by AlexJones0** [comment]
This appears to be only an issue on https://opentitan.org/guides/getting_started/setup_fpga.html and not on the equivalent https://opentitan.org/book/doc/getting_started/setup_fpga.html page.

After further investigation it looks like these guides are very out of date - they are not in use and are not being updated, but remain available because the relevant bucket is not cleaned and so these outdated files stick around, mostly accessed via search engines. I don't have access to that so @jwnrt is looking at that instead.

I'm curious how you found this? Was it just via a search engine or do you have an active use case for `opentitan.org/guides`?

**Comment by AlexJones0** [comment]
Also for reference the reason for this error (which is not present in the up to date `opentitan.org/book/...` documentation) is because of the renaming of `:jtag_adapter_cfg` to `:jtag_olimex_cfg` in https://github.com/lowRISC/opentitan/commit/6dc58eff36932c51d3b48dad01a064cedd5091cf to allow for multiple JTAG adapters.

**Comment by jwnrt** [comment]
I've deleted https://opentitan.org/guides from the bucket. Maybe we should be wiping and rebuilding the bucket when content changes?

**Comment by AlexJones0** [comment]
As the guides have been removed now this issue no longer exists. For future reference up to date versions of these guides can be found under the relevant sections in https://opentitan.org/book/doc e.g. [here](https://opentitan.org/book/doc/getting_started/setup_fpga.html).
