### ISSUE TITLE
[hmac/spec] Output pin doesn't go to Idle in case of HMAC stop invoked

### ISSUE THREAD

**Issue by martin-velay** [lowRISC/opentitan#23036]
### Description

Seen in simulation while testing the Save and Restore feature, the output pin `idle_o` is not moving into idle state after a hash_stop has been triggered.

**Comment by gdessouky** [comment]
After `hash_stop` is triggered, the message fed so far has to be at block size for the intermediate digest to be computed and then `hmac_done` gets asserted, and then `idle_o` is only then asserted. Otherwise, the IP will wait for the remaining data words to be fed until the message words reach the block size in FIFO. 

Is what you observe above after the message fed is at block size?

**Comment by andreaskurth** [comment]
@martin-velay @gdessouky Did this get fixed by PR #23432?

**Comment by martin-velay** [comment]
Solved with #23432
