### ISSUE TITLE
[dvsim] Listing regressions fails with "Substitution for the wildcard "UVM_HOME" not found"

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#2305]
```
$ util/dvsim/dvsim.py hw/top_earlgrey/dv/top_earlgrey_sim_cfgs.hjson  --list regressions
ERROR: [utils] Substitution for the wildcard "UVM_HOME" not found
$ util/dvsim/dvsim.py hw/top_earlgrey/dv/top_earlgrey_sim_cfgs.hjson  --list tests
ERROR: [utils] Substitution for the wildcard "UVM_HOME" not found
```

Running the sanity regression works through dvsim, so it's not a general problem.

**Comment by imphil** [comment]
@sriyerg

**Comment by GregAC** [comment]
In the past when I've seen this error an added `-t vcs` has got rid of it (set simulator to vcs). This seems to fix things in this case also.

Obviously still requires a fix as listing regressions/tests has nothing to do with the simulator so it shouldn't matter what `-t` is but may help in debugging the issue plus a useable workaround in the meantime.

**Comment by imphil** [comment]
Yes, `-t vcs` gets around that, thanks! Would still be nice to either give a useful error message, or avoid this behavior altogether.

**Comment by rswarbrick** [comment]
This is because the simulator support files for `xcelium` and `dsim` include stuff like `+incdir+{UVM_HOME}/src`. The hjson interpolation code searches various places for `{UVM_HOME}`, including the environment (where people with xcelium presumably have it defined). If you don't have that environment variable, everything fails.

When called without `-t`, dvsim looks at the configuration file you give it and reads the tool to use from there. It then reads in the support files for that tool and tries to interpolate all their references. Boom.

I think the easiest way to fix this is for the interpolation code to pass back a list of un-interpolated strings. If you're running a command that actually needs everything substituted, it should then fail if there's anything in the list (and can now give a better error message, listing all missing names). The `-l` functionality only needs to check that its resulting list doesn't contain `{foo}` for any `foo` in the list of missing names. If not, all is well.

**Comment by sriyerg** [comment]
I'm working on addressing this now.
