### ISSUE TITLE
[usbdev] Exposing beacon signal for easier integration

### ISSUE THREAD

**Issue by meisnere** [lowRISC/opentitan#23467]
### Description

Exposing beacon signal might ease integration effort.\
We have it exposed on DFT mode, but integration won't use this mode therefore we recommend to be able to expose it on other modes.

Maybe exposing the beacon valid would also ease integration effort.

**Comment by vogelpi** [comment]
Hi @meisnere ,
thanks for assigning me. Can you please elaborate a bit on the specific signal which needs a valid bit? I am also looping in @alees24 our USB hero :-)

**Comment by alees24** [comment]
I've never heard it called a beacon signal, but presumably this is the reference pulse `usb_ref_pulse_o` that the USBDEV emits, qualified by  `usb_ref_val_o`, at the top level of USBDEV.

When declared valid because a connection to the USB host is detected, the reference pulse should be asserted high every 1ms (on the host's clock) for a single cycle of the USBDEV's 48MHz clock, allowing the USBDEV clock frequency to be adjusted to match that of the host.
