### ISSUE TITLE
[hmac,rtl] FIFO Empty interrupt raised after FIFO seen full

### ISSUE THREAD

**Issue by martin-velay** [lowRISC/opentitan#23738]
### Description

Note: it might be a bug, and I have already a fix to propose. It's not impacting so much the number of gates, one additional FF. See PR: https://github.com/lowRISC/opentitan/pull/23739

While testing the HMAC with back pressure test, it appears that a `fifo_full` is seen at the same moment than a `reg_hash_stop` is triggered. The HASH stop should tie `fifo_full_seen_d` to 0 and thus prevent the FIFO empty to be propagated to the interrupt register, but in that case it's not as the `fifo_full_seen_d` assignment is giving the priority to `fifo_full`. Additionally, we should only trigger `fifo_full_seen_d` on the rising edge `fifo_full` as then signal is latched and this is again preventing the FIFO Empty to behave as expected. This explanation is maybe not so clear, but the PR will help to understand and the screenshot below as well:
![image](https://github.com/lowRISC/opentitan/assets/165653139/350b5a4a-880d-4bbe-80b9-790b4d67df8a)

**Comment by johngt** [comment]
Tagging @moidx / @vogelpi / @GregAC  for awareness.

**Comment by vogelpi** [comment]
Thanks for creating this issue and proposing a fix @martin-velay !

I think we should fix this for future versions and your fix in https://github.com/lowRISC/opentitan/pull/23739 seems perfectly viable for this. But for Earlgrey-PROD, I suggest to leave the design as is because:
- We should not create another RC to avoid any potential schedule impact unless absolutely necessary of course. We could discuss to do an ECO but I think we shouldn't as we shouldn't do ECOs unless absolutely necessary.
- This bug is no deal breaker as:
  - It's quite a corner case we're hitting here and I doubt we're going to be able to trigger this in silicon. IIUC to trigger this, Ibex 1) needs to write the final data word which causes the FIFO to become full, and 2) before the FIFO starts get emptied again Ibex needs to trigger the STOP command.
  - Even a single pop operation from the FIFO before the STOP command will avoid the bug. Software could read the FIFO full status flag before providing the STOP command to avoid this.
  - Even if the FIFO empty interrupt got signaled erroneously it wouldn't be a massive issue for the chip. The interrupt is not critical for the system's operation (today software doesn't use it at all).

So unless others think differently, I suggest not to merge the bug fix right now but only after the TO branch has forked off.

**Comment by moidx** [comment]
Based on the current implementation, it is very difficult for Ibex to fill the FIFO. The HMAC processing speed is faster than Ibex + TLUL. Because of this, I agree with @vogelpi that this is a corner case, and should not be a show stopper for `Earlgrey-PROD`. 

Discussed in triage meeting 2024-06-21. OK to merge post `Eargrey-PROD.M5` branch. No ECO for `Earlgrey-PROD`.

**Comment by moidx** [comment]
Moving to M7 to keep track of merging the fix after branch time.
