### ISSUE TITLE
[dvsim] Question: Where to find a handbook including all the keywords available in hjson and core file

### ISSUE THREAD

**Issue by desorya** [lowRISC/opentitan#23851]
Hi there,

I'd like to ask if there is a handbook for the hjson and core file which includes the fully-mapped available keywords and how they work?

Thank you.

**Comment by hcallahan-lowrisc** [comment]
Hey @desorya,

The `.core` files are [Fusesoc](https://github.com/olofk/fusesoc) core files, which have a complete API documentation page [here](https://fusesoc.readthedocs.io/en/stable/ref/capi2.html).

The `.hjson` files used throughout OpenTitan have a number of different uses, so there isn't one schema that covers everything. However, I can give you a few examples:
- Files defining Comportable IP HWIP blocks (e.g. `hw/ip/i2c/data/i2c.hjson`) have keys defined in the [Comportatbility Specification](https://opentitan.org/book/doc/contributing/hw/comportability/index.html) (e.g. [here](https://opentitan.org/book/doc/contributing/hw/comportability/index.html#configuration-description-hjson)), as well as register definition fields from the [reggen/regtool](https://opentitan.org/book/util/reggen/index.html) tooling docs.
- `.hjson` files for DV simulations have some documentation available. Files defining [testplans](https://opentitan.org/book/util/dvsim/doc/testplanner.html) (e.g. `hw/ip/i2c/data/i2c_testplan.hjson`) are documented, but the configuration files that drive our simulation runner [dvsim](https://opentitan.org/book/util/dvsim/index.html) (e.g. `hw/ip/i2c/dv/i2c_sim_cfg.hjson`) are not.
- Files defining top-level assemblies (e.g. `hw/top_earlgrey/data/top_earlgrey.hjson`) are ingested by the [topgen](https://opentitan.org/book/util/topgen/index.html) tool, but the schema here is not formally documented afaik.

This is something we should improve in the future. In the meantime, I suggest trying to find keywords using the search on the documentation site (click the magnifying glass in the topbar or use the keyboard shortcut `s`). Otherwise, grepping the codebase while limiting your search to python files may bring up some code comments around where a particular keyword is parsed.

I hope that was helpful. If so, would you mind closing the issue? Thanks
