### ISSUE TITLE
[OTBN] Specify instruction encoding

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#2391]
This issue is to track the creation of an instruction set encoding for bignum.

> estimate 2

**Comment by imphil** [comment]
@wallento has started work on that.

**Comment by wallento** [comment]
You can assign this to me. The straightforward mapping of the instructions to the available space in the custom encoding space can be found here: https://docs.google.com/spreadsheets/d/1zOSGkT0Hua3IS6u3bUk56FoGj8vfEf0-UNo8oydRC40

**Comment by rswarbrick** [comment]
I think we have a problem with the encoding for the mulqacc instruction: the scheme currently in that document doesn't have space for `<zero_acc>` or `<wb_variant>`. I found this because the proposed encoding failed some automated checks in my YAML stuff (yay! programming!).

We could probably fit in one bit by shoving (say) `<zero_acc>` into bit 14. Then we'd need to rejig the `funct3` assignment slightly. For example, maybe we could tolerate shortening the `loopi` immediate by a bit? If so, `loop` and `loopi` could share a value of `funct3` and `bn.sid` could have the other one.

I'm less sure of how to fit the `<wb_variant>` flag. Fundamentally, I think the proposed instruction has the following fields:

 - `wb_variant` (3 values; 2 bits)
  - `zero_acc` (1 bit)
  - `wrs1` (5 bits)
  - `wrs1_qwsel` (2 bits)
  - `wrs2` (5 bits)
  - `wrs2_qwsel` (2 bits)
  - `wrd` (5 bits)
  - `acc_shift_imm` (2 bits)

This sums to 24 bits. We are using 7 bits (bits 6:0) to pick one of two custom encoding slots, so we have 32-(24+7) = 1 bit left: the proposed instruction would use half of the encoding space for that slot. Eek!

@GregAC: Have I got the bit counts right? If so, is there a way we could knock some of the fields down somewhat? Quick ideas:

  - Register pairing (source registers N and N|1)
  - Operate in place (wrs1 == wrd)
  - Only allow some combinations of `wrs*_qwsel`
  - Only allow `acc_shift_imm` in non-writeback modes (which don't need `wrd`)

**Comment by rswarbrick** [comment]
Oh, also `bn.cmp` and `bn.cmpb` don't currently fit: both instructions are documented as having `<shift_type>` and `<shift_bytes>`, but we're using bits 30:25 for literal bits. Fortunately, we can shove the flags in question into the space where `<wrd>` would normally be, so that should be an easy fix.

**Comment by rswarbrick** [comment]
I take it back: if you move stuff as I suggested for `bn.cmp` and `bn.cmpb`, the results are ambiguous with `bn.addi`. I think that `bn.cmp` and `bn.addi` are already ambiguous in the current proposal (e.g. for `32'b0011_0000_0000_0000_0100_0000_0000_1011`).

**Comment by rswarbrick** [comment]
If you want to sanity check new encodings, the code at #2801 should help. Fill in the relevant fields in `insns.yml` and then run e.g.
```
hw/ip/otbn/util/yaml_to_doc.py hw/ip/otbn/data/insns.yml
```
from the top of the OpenTitan tree.

If all is well, it will spit out a load of Markdown. If something is bad, it will instead print an error message to stderr. To see the rendered documentation (if that succeeds), you can run:
```
util/build_docs.py --preview
```
and point your browser at `http://localhost:1313`.

**Comment by wallento** [comment]
Hi,

I can now generate the information from the model. Did dinner further massive refactoring for that and now no information is specified twice, limiting the impact of mistakes. 

Do you prefer it to generate yml or better directly integrate with the conversion tool?

Cheers,
Stefan

**Comment by wallento** [comment]
I have promoted RSHI to custom-2 and I we can squeeze mulacc into it too

**Comment by wallento** [comment]
Please see the update. MULQACC can get its two bits from funct3 and share custom-2 with the right shift. We still have one custom space left.

**Comment by wallento** [comment]
I agree with @rswarbrick that CMP and CMPB are aliases

**Comment by wallento** [comment]
No, they are not, w0 is not immutable in OTBN, right?

**Comment by GregAC** [comment]
> @GregAC: Have I got the bit counts right? If so, is there a way we could knock some of the fields down somewhat?

Yes you have

> Register pairing (source registers N and N|1)
> Operate in place (wrs1 == wrd)

Both of these are too constraining for building up arbitrary size multiply kernels, or rather would involve lots of extra instructions copying registers around

> Only allow acc_shift_imm in non-writeback modes (which don't need wrd)
With the standard schoolbook multiply example I've done acc_shift_imm is only used in the writeback modes. It does only use 0 or 64 so we could move it down to 1 bit but I figured some extra flexibility would be good (unless it proves to be a pain to implement!)

> Only allow some combinations of wrs*_qwsel
Again I think this will be too constraining for building up arbitrary size multiply kernels

Though I think we've now come up with a way for it to fit? When I was designing it I did look at how it might slot into the RISC-V custom instruction space to see how feasible it may be and it did fit. I'll have a think about bits we could cut out and take a proper look at the current encoding proposal.

**Comment by rswarbrick** [comment]
I'm not sure I completely follow Stefan's messages above but, yes, it sounds like he might have worked out how to rejig things.

Basically, the 2 opcodes we're using in the RISC-V instruction space allow 26 bits, so the counts above add up to 1/4 of the space. Since OTBN is super-specialised and doesn't actually have many instructions, maybe that's fine - at least it's less than 100%! :-D

**Comment by GregAC** [comment]
> Basically, the 2 opcodes we're using in the RISC-V instruction space allow 26 bits, so the counts above add up to 1/4 of the space. Since OTBN is super-specialised and doesn't actually have many instructions, maybe that's fine - at least it's less than 100%! :-D

This was pretty much my feeling it's a bit of a monster instruction but the others aren't so huge so it should all fit.

**Comment by wallento** [comment]
It has custom-2 opcode for itself now. @rswarbrick was missing `hwsel`, thats another bit. So it uses up all instructions now.

**Comment by wallento** [comment]
RSHI: It has custom-3 now, but only 1/4 of it, new field "funct2" [13:12]

**Comment by wallento** [comment]
CMP/CMPB: Fixed the coding to include the shift_bytes. Unfortunately the coding needed to get an update after the new spec.

**Comment by wallento** [comment]
general: Removed quirky parts of the coding, no real need to be so compact. We can now do most things in funct3, sometimes funct31 is used. I added the format dimension as color coding to make it easier to read.

**Comment by rswarbrick** [comment]
This looks close. I've updated the YAML code to match. The tooling still finds collisions (manually wrapped to make it easier to read):

```
Invalid schema in YAML file at 'hw/ip/otbn/data/insns.yml':
Ambiguous instruction encodings: 'bn.subm' and 'bn.and' both match bit pattern 0x0000602b,
'bn.subm' and 'bn.or' both match bit pattern 0x8000602b
```

**Comment by rswarbrick** [comment]
@wallento: Once you've come up with a fix, is there any chance you could try it out with the tooling, to avoid yet another go-around? If #2801 hasn't yet been merged, I think the following sequence of commands should work:

``` bash
git fetch origin pull/2801/head
git checkout -b yaml-encoding FETCH_HEAD
# hack hack hack (at least uncomment the encoding for bn.subm)
hw/ip/otbn/util/yaml_to_doc.py hw/ip/otbn/data/insns.yml
```

**Comment by wallento** [comment]
Yes, sorry, just found that I have a hiccup in the coding. Will fix ASAP

**Comment by rswarbrick** [comment]
This looks good. I think we have a non-ambiguous encoding for every instruction. Let's close this issue now: we can always file follow-ups if we think there are improvements to be made.

@wallento: Does that sound right to you?

**Comment by wallento** [comment]
Yes, I will keep the Google spreadsheet around as visual editing is helpful, but the primary source is insn.yml from now on.
Can be closed.

**Comment by imphil** [comment]
The encoding is now defined and documented since #2799, see https://docs.opentitan.org/hw/ip/otbn/doc/index.html#instruction-format.

**Comment by imphil** [comment]
@moidx @cdgori: We do now have an instruction encoding for OTBN, as shown in https://docs.opentitan.org/hw/ip/otbn/doc/index.html#instruction-format. The base instruction set follows RV32I, the BN instruction set uses the RISC-V extension spaces. Turns out there's not that much encoding space left after all to play around with things. The encoding we have now is *an* encoding, not necessarily *the* encoding. Please have a look and let us know if there's the need to discuss some of its properties in more detail. (It's much easier to do that now that we have a complete proposal in the doc.)
