### ISSUE TITLE
[xbar] top-level xbar connection

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#2464]
In current top-level xbar test bench, we connect to the wires between xbar and IPs. As @sriyerg  pointed out, there are potential issues, like misconnection or extra masking between IP port and the wire we drive, which may not be caught. @sriyerg may add more rational.

We decided to drive on the IP ports, but since some connections of some IPs are hand written, we need more info from xbar hjson (top_earlgrey.gen.hjson) or topgen, in order to generate connections to correct IP ports automatically. 
1. instance name of hand written connected IP
2. port name or prefix/suffix of port name if there are multiple TL ports in an IP (such as ibex, rv_dm) or it uses the non-standard port name
3. mem type as mem has a different prefix `u_tl_adapter_`

Also use this issue to track this xbar DV TODO.

This also relates to #2401

**Comment by sriyerg** [comment]
Consider the connectivity of `tl_*_o.a_source[7:1]` from Ibex to XBAR (and hence, to all devices connected to the XBAR interconnect). With regular functional testing, Ibex can only wiggle the bit 0. The rest of the 7 bits shows up as uncovered on all hosts and devices and on the interconnect. 

How can we prove that there is nothing in the design that could be gating or masking those upper bits? It may not be critical since they are unused, but, we still do need to close coverage by somehow proving that all of those bits are also hooked up properly between hosts / devices and the interconnect. 

It is for this reason that we reuse our existing XBAR IP level testing, expand it to consider the full interconnect as our DUT (rather than a single discrete instance) and overlay the testing on top of the full chip. Instead of driving the interconnect ports, we drive the ports of the hosts and devices instead (SV forces), so that we can conclusively prove that not only all bits of `a_source` from the host is connected to the interconnect, but end-to-end to all devices. Likewise for all other TL signals, which cannot achieve a full 100% coverage due to top integration limitations. 

We want to be able to rely on automation to achieve this. We want to be able to templatize the way we force-drive the TL interfaces on the hosts and devices with our TL agents. Due to limitations indicated by @weicaiyang, we are currently unable to do so. We mitigate this by attaching our TL agents to the auto-generated internal wires (between hosts/devices and the interconnect) instead for the affected hosts and devices. That defeats our original purpose unfortunately, so it will be great if we could figure out a fix to accommodate our requirements.

**Comment by eunchan** [comment]
Want to clarify the intention. The purpose of driving from the module should be solely checking the connection between the module port and the Xbar port. One good thing is that TL-UL only uses typedef struct for h2d/d2h. So the scenario Sri mentioned is not possible, unless someone manually modifies in the top template (for those modules hand-instantiated).

Easiest way is to have manual force connections in xbar TB template too. Then I agree Weicai's opinion that whether managing hand-crafted connections everytime we see the failure when new hand-crafted module lands is not worth to use valuable time of DV engineers.

So, the firm ground is that the tool at least gives the enough information for TB gen to auto-connect everything. Making topgen to do it, however, needs more time of the tool engineers (maybe me?) than managing the template of manual connections in my opinion. As the change is most of the modules that are not comportable to the IP spec (e.g. Ibex, rv_dm). Maybe eventually we can do this by making `rv_core_ibex` to have inter-module signals for everything. But not today.

@tjaychen @msfschaffner It would be good if you guys also weigh in your opinions to this issue.

**Comment by tjaychen** [comment]
sorry i'm really late to this..never saw this.
How many manual connections are there at the moment? It is mainly the 2 coming out of ibex and the one coming out of rv_dm?

**Comment by eunchan** [comment]
Related to PR #3040 

- Will prepare XBAR DV to connect to the peripherals' TL port (including memories) in following PRs.
  + @eunchan will prepare a library function for DV script to figure out which peripheral the xbar port connects to
  + @eunchan suggested to move Xbar DV gen code in `topgen.py` after `elab_intermodule()` function so that all inter-module signals' connections are made.

**Comment by weicaiyang** [comment]
> Related to PR #3040
> 
> * Will prepare XBAR DV to connect to the peripherals' TL port (including memories) in following PRs.
>   
>   * @eunchan will prepare a library function for DV script to figure out which peripheral the xbar port connects to
>   * @eunchan suggested to move Xbar DV gen code in `topgen.py` after `elab_intermodule()` function so that all inter-module signals' connections are made.

Thanks @eunchan. Will update xbar DV connection after that.

**Comment by tjaychen** [comment]
is this resolved now..? should we close this?

**Comment by eunchan** [comment]
I think yes in tooling side. @weicaiyang  please close this if you think DV side also can be closed

**Comment by weicaiyang** [comment]
@tjaychen @eunchan 
In a recent update, we connect AST on the interconnect rather than ports. Perhaps keep this open until we find a better approach for it

**Comment by tjaychen** [comment]
o that's right. Thanks for the reminder Weicai.
I'll try to find time to circle back and fix it.

**Comment by weicaiyang** [comment]
as discussed with Tim, we plan to move ast inside the top_earlgrey. Closing this issue.
