### ISSUE TITLE
[otbn] Produce assembly for modulo exponentiation with OTBN v0.1 syntax

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#2469]
Produce an assembly snippet for doing a modulo exponentiation in the OTBN v0.1 syntax as proposed in #2393.

**Comment by felixmiller** [comment]
Assembly is here: https://github.com/felixmiller/ot-dsim/blob/new-isa/asm/otbn_bn.asm

**Comment by imphil** [comment]
Left to do: add it to the "snippet collection" in the hw/ip/otbn tree.

**Comment by rswarbrick** [comment]
Just a quick note: this needs a little bit of editing to assemble with the proposed `otbn-as` tool. The changes I've noticed are:

  - The first operand of `bn.mulqacc.so` should have `.L` or `.U` rather than `.l` or `.u` (or we need to change the docs).
  - The shifts in calls to `bn.addc` need a `B` suffix (so `w4 << 16B`)
  - The calls to `bn.cmpb` have an extra operand (probably was the destination register?)

**Comment by rswarbrick** [comment]
I just started a PR to add the `otbn_bn.asm` to a new snippets collection. But I noticed a Chromium licence in the directory: is this a derived work, that needs the chromium licence on it too? @felixmiller (who wrote/rejigged the code).
