### ISSUE TITLE
[OTBN] Create area estimate for v1-bronze

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#2473]
For bronze, we need an area estimate for OTBN. A rather rough (whatever that means in percent) is sufficient.

The IMEM and DMEM SRAMs have already been accounted for, so focus should be on:
- ALU
- Other blocks (decode, fetch, LSU, control flow)
- register files

**Comment by imphil** [comment]
@GregAC mentions: just the area estimate I think as the area will be estimated from that RTL plus other numbers ((Mock RTL Area + Ibex Area) * Security Hardening overhead * fudge factor was the plan)

**Comment by GregAC** [comment]
Mock RTL is now available in this PR: https://github.com/lowRISC/opentitan/pull/2639, have pinged @msfschaffner to run some implementation trials on it.

**Comment by imphil** [comment]
Thanks to @msfschaffner we got implementation numbers back and are assuming 157 kGE without security hardening.

* #2690 contains the OTBN design for bronze
* https://docs.google.com/document/d/1kUcBXuquL6V06IkcmcEUROpudjw8UB_0EytumCC0WP4/edit# has been updated to contain the area estimate and how it was calculated.

**Comment by imphil** [comment]
The mock RTL used for the area estimate is now also committed into `otbn-dev` as part of https://github.com/lowRISC/opentitan/pull/2639.

**Comment by msfschaffner** [comment]
Hey @imphil, @GregAC,

We just got the new standard cells from Nuvoton, hence I repeated the synthesis sweep for OTBN. 
A few things have changed, including the GE, since it turned out that we were not using the right factor for area normalization. 
This is a bit unfortunate, since we probably have to update the estimates for Bronze.

I have updated the document linked above - can you PTAL?

**Comment by imphil** [comment]
Greg updated the numbers, and I updated the random gate generator parametrization in the bronze branch. Should be OK now.
