### ISSUE TITLE
[rtl] pinmux mio[16-19] functionality

### ISSUE THREAD

**Issue by sriyerg** [lowRISC/opentitan#2484]
On the core<->pinmux side, mio[16-19] bits are connected to gpio[16-19] with no other alt functions muxed with those pins. 

At the padring<->pinmux side, however, mio[16-19] maps to special chip inputs (jtag_spi_n, bootstrap, jtag_trst and jtag_srst). 

This seems problematic - there is nothing preventing SW from configuring GPIO[16-19] and corrupt/modify those inputs (example, cause a JTAG reset). 

Seems like the right way to do this is by putting those on 'other' mux select lines as alternate functions, rather than intermix with the internal GPIO lines. Unless of course, this is how it was intended to be designed for some specific reason? 

In any case, I feel implementation details such as this ought to be documented somewhere..

**Comment by tjaychen** [comment]
i think the padring<->pinmux stuff was a temporary patch by @msfschaffner.
The jtag stuff specifically, eventually needs to be tied into the life cycle behavior of the chip, which requires more modifications on the pinmux side.

The bootstrap on the other hand should just be a GPIO though, I'm less clear why that one is in the special category.

**Comment by msfschaffner** [comment]
Yes, this is only a temporary fix.

Before instantiating the new `padctrl` module, some USB and JTAG muxing logic was hardcoded together with inferrable pad instances, which is not compatible with the way we intend to instantiate the pads in the `padring`. The `padring` is a completely structural module and we do not intend to have any synthesizable logic in there. 

Hence, I had to move that custom muxing logic out of the padring, and since the strap sampling and JTAG qualification was still an ongoing discussion at that time, I moved the JTAG muxing logic into the `jtag_mux` module in the `*_asic` and `*_nexysvideo` chip-level wrappers. I plan to address this after Bronze, and the intention is to pull that muxing logic back into the pinmux in a similar way as @sriyerg described above.

RE the bootstrapping pin: there should not be anything special about that pin except for its specific placement. I.e. this is just a GPIO that is mapped to a specific pin on the FPGA, hence the comment in RTL.

**Comment by sriyerg** [comment]
Thanks for the explanation, @tjaychen and @msfschaffner. I understand that the JTAG muxing is temporary and the boot strap pin only matters at the start of the simulation when the CPU is executing the boot rom image. Once it gets to the 'test' image, it can be treated as a regular GPIO. I just wanted to record this so that I remember to update the chip level GPIO test.

**Comment by sriyerg** [comment]
This no longer needs to remain open.
