### ISSUE TITLE
[earlgrey-aes] Ambiguity in description for aes_prng_reseed_test regarding "Stall" feature requires clarification

### ISSUE THREAD

**Issue by github-gcontributor** [lowRISC/opentitan#24857]
### Test point name

[chip_sw_aes_prng_reseed](https://github.com/github-gcontributor/opentitan/blob/master/hw/top_earlgrey/data/ip/chip_aes_testplan.hjson#L145)

### Host side component

None

### OpenTitanTool infrastructure implemented

None

### Silicon Validation (SiVal)

Yes

### Emulation Targets

- [ ] None
- [ ] CW310
- [x] Hyperdebug + CW310
- [x] CW340 

### Checklist

There is an ambiguity in the description of the aes_prng_reseed_test regarding the "Stall" feature of the AES module in the OpenTitan project. The test description mentions that the encryption operation to "STALL" when the entropy is disabled.
One of the bit in the status register is STALL bit "kDifAesStatusStall". 
I do not see any test (in the given list) covering STALL bit feature test, I assume the test aes_prng_reseed_test is meant to cover the STALL bit generation.  However, the stall bit definition do not mention its relation to disabling the entropy rather starving/deprived of data to continue operation.

The test seems to cover the scenario where the AES module stalls due to entropy unavailability, but it is unclear how the STALL bit is involved.
It is unclear whether the aes_prng_reseed_test is intended to cover the STALL bit generation in this context.

My observation during the operation of the test, the only possible stall/hault indication is the test waits (halts/stalls) for output data to be valid for the data.  There is no explicit status or indicators to describe "the waiting for entropy to be enabled event" in the description. i.e. The status doesn't explicitly signal when it's waiting for entropy to be enabled. The only indication of a stall is a wait for output data validation.
 
It is possible that the STALL bit is only designed to indicate stalling due to output backpressure, not entropy starvation.  If later case is true, the AES RTL might need enhancement to include a status bit for entropy starvation or the documentation should clearly state the intended behavior.

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [ ] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [ ] Host-side component developed
- [ ] HJSON test plan updated with test name (so it shows up in the dashboard)
- [ ] Test added to dvsim nightly regression (and passing at time of checking)
- [ ] For SiVal test cases, test is running relevant FPGA or silicon regression

**Comment by vogelpi** [comment]
Hi @github-gcontributor ,
thanks for filing this issue. You're right, the STALL bit in the status register is not relevant for this test. It only indicates when the module doesn't proceed because software hasn't read the previous output. This is documented here https://opentitan.org/book/hw/ip/aes/doc/registers.html#status--stall .

Also, you're right that currently no other test seems to cover the STALL bit. However, all tests use the output valid and input ready bits of the status registers. This is already sufficient to operate the module properly. The main purpose of the stall bit is for debugging software as well as to simplify block-level DV.

I think it would be good to also signal stalling due to entropy starvation. It could even be using the same bit (to maintain software compatibility). We may want to do this for a future revision.

**Comment by github-gcontributor** [comment]
Added test "https://github.com/lowRISC/opentitan/pull/25082"
Closing the issue now.
