### ISSUE TITLE
[earlgrey-aes] Clarification needed on PRNG_RESEED_RATE `PER_64` behavior in `aes_prng_reseed_test`

### ISSUE THREAD

**Issue by github-gcontributor** [lowRISC/opentitan#24899]
### Test point name

[aes_prng_ressed_test]:https://github.com/github-gcontributor/opentitan/blob/master/hw/top_earlgrey/data/ip/chip_aes_testplan.hjson#L145

### Host side component

None

### OpenTitanTool infrastructure implemented

None

### Silicon Validation (SiVal)

Yes

### Emulation Targets

- [ ] None
- [ ] CW310
- [x] Hyperdebug + CW310

### Contact person

vogelpi

### Checklist

The aes_prng_reseed_test is configured with mask_reseeding set to kDifAesReseedPer64Block.
The test processes blocks in a loop, expecting the PRNG to reseed after every 64 blocks.
The test halts and waits for entropy to be enabled and the reseed to occur for the block index 63. (starting block from 0)

According to the documentation, the masking PRNG should reseed "approximately" once every 64 blocks. However, during the aes_prng_reseed_test, the AES module halts and waits for a new reseed for the 63rd block (assuming blocks are numbered from 0 to 63). This suggests that the PRNG reseed is being triggered one block earlier than expected.

While the expected behaviour should be, with mask_reseeding set to kDifAesReseedPer64Block, the AES encryption should continue uninterrupted for 64 blocks. The auto PRNG reseed should be anticipated/triggered for the next set of 64 blocks.

Is this behavior consistent with the AES module's design, or does it have offset in the reseed counter?
Should the documentation be updated to reflect the actual behavior (one less than per 64 block), or is a fix needed in the AES module's implementation?
Is the PRNG reseed supposed to occur after processing 64 blocks, or is it expected to occur earlier.  The term "approximately" in the documentation might indicate that the reseed can occur slightly before or after 64 blocks, but clarification is needed.

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [ ] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [ ] Host-side component developed
- [ ] HJSON test plan updated with test name (so it shows up in the dashboard)
- [ ] Test added to dvsim nightly regression (and passing at time of checking)
- [ ] For SiVal test cases, test is running relevant FPGA or silicon regression

**Comment by vogelpi** [comment]
> According to the documentation, the masking PRNG should reseed "approximately" once every 64 blocks. However, during the aes_prng_reseed_test, the AES module halts and waits for a new reseed for the 63rd block (assuming blocks are numbered from 0 to 63). This suggests that the PRNG reseed is being triggered one block earlier than expected.
> 
> While the expected behaviour should be, with mask_reseeding set to kDifAesReseedPer64Block, the AES encryption should continue uninterrupted for 64 blocks. The auto PRNG reseed should be anticipated/triggered for the next set of 64 blocks.

Hi @github-gcontributor , this behavior is expected and it's matching the description in the documentation: You're doing 64 blocks and while doing block number 64, the reseed operation is triggered. The block then only finishes after the reseed has finished. After this, you can again do 63 blocks and again during the 64th block, a reseed is being triggered. So you will end up with 2 reseeds for 128 blocks.

The term "approximate" is there for two reasons:
1.) Software can refresh the key (provide the same key but remasked with fresh randomness). This may trigger another reseed operation - depending on other settings, see e.g. https://opentitan.org/book/hw/ip/aes/doc/registers.html#ctrl_aux_shadowed--key_touch_forces_reseed .
2.) Software can configure a different key and IV to start another message using otherwise identical settings. This means the block counter (responsible for triggering reseeds) is not changed.

**Comment by vogelpi** [comment]
Thanks for the feedback @github-gcontributor . I can't approve and merge your PR as @nasahlpa has requested changes. Please try to answer all open questions and implement Pascal's feedback to move things forward.

**Comment by github-gcontributor** [comment]
Sure
