### ISSUE TITLE
[OTBN] Device memory map

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#2540]
In the OTBN bus device we provide three areas of memory:
- Control/Status registers
- A window into OTBN instruction memory (IMEM)
- A window into OTBN data memory (DMEM)

IMEM and DMEM are currently both 4 kB in size.

This issue is about finding a good address space layout for OTBN as bus device (i.e., as seen from Ibex; this is *not* about how the OTBN core sees IMEM/DMEM from its side).

If we want to have a reasonably tight address space, we can do something like the following. Keeping control/status registers at the beginning of the address space is OpenTitan convention, and we should stick to it.

```
0x0         control/status registers
0x1000      IMEM
0x2000      DMEM
```

If we want to provide a bit of expansion space for IMEM and DMEM without changing the address map, we can do something like this, providing a 16 kB address space for both IMEM and DMEM at the expense of consuming more address space for the OTBN device.

```
0x0         control/status registers
0x4000      IMEM address space
	0x4000 - 0x4FFF: IMEM
0x8000      DMEM address space
	0x8000 - 0x8FFF: DMEM
```

From a software and hardware perspective, I'm not sure if we need the expansion space. It's not unlikely we'll increase IMEM and/or DMEM size, but since all register maps are auto-generated (both in HW and in SW), we only need to change a parameter. However, relying on all that machinery for a potential last-minute change to increase IMEM or DMEM seems risky, and there might be code out there which doesn't use it, so providing the 16kB space seems safer.

What's your take on that?

*In the [current spec version](https://docs.opentitan.org/hw/ip/otbn/doc/index.html#register-table) I produced a slightly odd design (TM) which isn't properly prefixing the regions.*

**Comment by imphil** [comment]
@tomroberts-lowrisc @GregAC @lenary

**Comment by tomroberts-lowrisc** [comment]
This might be asking something that's already been addressed (hah!), but does it need to expose all the memory directly? i.e. could the OTBN just provide a single address / data register that auto increments as you write to it / read from it?

**Comment by GregAC** [comment]
> If we want to provide a bit of expansion space for IMEM and DMEM without changing the address map, we can do something like this, providing a 16 kB address space for both IMEM and DMEM at the expense of consuming more address space for the OTBN device.

I'd be in favour of this kind of approach, I'd even say up the address space to something relatively huge (e.g. 1 MiB each). Unless there are any particular reasons to prefer a tight address map?

**Comment by imphil** [comment]
> does it need to expose all the memory directly?

It doesn't necessarily need to, but it makes things easier. 

- Software on the main CPU reads the OTBN computation results back from DMEM in pre-defined areas, having it not fully mapped makes that harder to do so.
- We don't have a DMA engine today, but I see other peripherals, such as HMAC, also be designed in a way that occupies a larger address space (for a FIFO, in the HMAC case) to allow a potential DMA engine to simply increase the address for bulk transfers. It's all hypothetical at this point, but keeping things consistent will make things easier for us down the road, hopefully.
- Ultimately, we're not talking about a huge address space for the device in a world where we have 32b to waste, i.e. we can go the simple route.

> Unless there are any particular reasons to prefer a tight address map?

None I know of. And I do think we've seen other peripherals using address space rather freely, such as PLIC.

> I'd even say up the address space to something relatively huge (e.g. 1 MiB each)

I like that, the more I think about it, the more I think I was over-optimizing by preferring a smaller address space.

**Comment by lenary** [comment]
I had a long reply typed out, and it got lost. Then @imphil wrote out part of my feelings in his comment.

@tomroberts-lowrisc I think an auto-incrementing approach would be a bad idea. It may prevent later adding DMA, and seeking around to extract information seems error-prone and probably won't give you much bandwidth for extracting info after the run completes.

--

I think the PLIC is not a good comparison, for two reasons. 1: we're following the RISC-V PLIC specification (or planning to), which tells us how big the PLIC needs to be, quite apart from our requirements.

Where we're using gaps to make our lives easier in the DIFs is where the number of registers in a multireg is controlled by an instantiation parameter of the device. The DIFs are supposed to be parameterisation-agnostic (something we're moving towards, where the parameter values are represented in the DIF at run-time, not compile-time), and this means you don't use each register's `_OFFSET` macro, instead you use the first register's `_OFFSET` macro and then calculate the other register's offsets based off that. Here is a good example:
https://github.com/lowRISC/opentitan/blob/0eb35283ef2ee65ac6093bcc4e469bfc5ef7e409/sw/device/lib/dif/dif_padctrl.c#L87-L105

I took a quick look at the `otbn.hjson` file that's been proposed, and it seems we're not using parameters (yet). In this case, I don't see an issue with using the tighter memory map, as we need to recompile if `otbn.hjson` changes anyway, and the reason for generating the `_OFFSET`s from the hjson is exactly so we can slightly change the layout later without software breaking entirely. That said, I don't know if you intend to use hardware parameters for the size of dmem and imem.

I do think if you do the sparse approach, you end up having to enforce that the area sizes are never larger than the gap you left originally, and eventually you degenerate into the tight layout anyway (once you have expanded memory enough). Though this takes longer if you allocate a bigger gap.

My preference for the moment would be to go with the tight map, and if we later add parameters for the memory sizes, then I could see the advantage of gaps (because you won't need to calculate the offset of the second memory based off run-time information).

**Comment by imphil** [comment]
> That said, I don't know if you intend to use hardware parameters for the size of dmem and imem.

Currently the one and only source for IMEM and DMEM size is the `window.items` field in the hjson -- it's passed as parameter to the hardware SRAM primitives, and it's used in my prototype DIF. So as long as we keep relying on that tooling, we're fine.

However, re-generating the address map is disruptive when we only want to change the size of the OTBN SRAMs. While it all *should* work, it increases risk. All software needs to recompiled. Logic in the crossbar changes. You cannot run main-CPU binaries compiled for versions with less SRAM on versions of OT with more SRAM, etc. 

There's one more point: we need to allocate space in the global address map for OTBN as well -- and AFAIK, that's hand-crafted to give each device a maximum address space. We don't gain anything by not filling that space out right from the start, but we loose some flexibility (see above).

**Comment by imphil** [comment]
Whatever we decide here is relatively easily changed at this stage in the development cycle, so we don't need to come up with the ultimate answer. However, the "closer to right" we can get this, the less we need to think about it in the future :smile: 

@gkelly @eunchan What's your take on that?

**Comment by tomroberts-lowrisc** [comment]
Has no bearing on DMA - any noddy DMA can access fixed and incrementing addresses, and the bandwidth is the same whatever (32b a cycle). Agree though it depends on the access patterns - lots of random access to smallish chunks would be a pain.

**Comment by sjgitty** [comment]
> If we want to provide a bit of expansion space for IMEM and DMEM without changing the address map, we can do something like this, providing a 16 kB address space for both IMEM and DMEM at the expense of consuming more address space for the OTBN device.

I lean to this approach for future proofing, though no one should be addressing base addresses by hand, so even this probably doesn't matter.
