### ISSUE TITLE
[OTBN] Integrate OTBN into top_earlgrey

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#2580]
Even though the OTBN implementation itself is still to be written, the device interface as it is seen from Ibex is reasonably stable already (https://docs.opentitan.org/hw/ip/otbn/doc/index.html#register-table).

When do people feel is a good time to enable OTBN in top_earlgrey?

- Enabling OTBN in top_earlgrey is non-invasive: it's a "dead" bus device until it is actually used by software, so existing software or hardware shouldn't regress from it.
- Enabling OTBN will cause a fair number of changes to the crossbar, and the alert and interrupt handlers (all auto-generated). Having all these changes in master will keep master closer to a final version, making it easier to see timing/area bottlenecks right from the start.
- Having OTBN enabled in top_earlgrey is also a pre-requisite to write software (such as DIFs) for it (in master).

My take on it: let's enable it soon as possible, without giving any kind of "quality badge" to it. Doing so will make us more productive in OTBN development, and in overall system development.

If you're interested, that's how the code looks: https://github.com/imphil/opentitan/tree/otbn-enable-toplevel. Almost all of it is auto-generated (all code in the `autogen` folders.)

**Comment by imphil** [comment]
@sjgitty @eunchan what's your take on that?

**Comment by cdgori** [comment]
@imphil - I agree with your take, enable ASAP - correspondence to final in master will be better, earlier.  It's a pretty "inert" bus device so the risk seems low.

**Comment by tjaychen** [comment]
@sriyerg adding Sri for DV perspective.

Just my opinon...I'm always in favor of early top level integration as long as it doesn't break the integration test cases.

**Comment by eunchan** [comment]
Agree with Tim.

**Comment by sjgitty** [comment]
Bring it in to master in stages (as I assume you would); making sure it
doesn't break the build (as I assume you would); and we can review the
pieces as they're ready.

**Comment by sriyerg** [comment]
> @sriyerg adding Sri for DV perspective.
> 
> Just my opinon...I'm always in favor of early top level integration as long as it doesn't break the integration test cases.
> 
> Even more in favor in this case if it helps make bronze look more "real".

Sorry, late to the party. There are test breakages at the chip level in the nightly regressions due to integration of OTBN without any qualification:
https://reports.opentitan.org/hw/top_earlgrey/dv/latest/results.html

From DV perspective, it is ideal to integrate IPs at the chip level after they reach D1 V1 quality. This ensures that the port list and the SW interface is solid, and the basic datapath with the IP is working, paving the way for 'light' chip level testing. But depending on the size of the IP, it may take a while to complete the V1 steps. So the next best thing would be to integrate it at least after running the CSR suite of tests. After autogenerating the initial UVM testbench, those CSR tests can be run within minutes. Those issues can be quickly debugged (most of the times they are exclusions, but sometimes it uncovers some design / documentation issues, such as interrupts asserting unnecessarily right out of reset).

**Comment by rswarbrick** [comment]
@sriyerg: I'll take a look at this later today. For what it's worth, a PR that was merged 6 days ago isn't a very good place for a bug report. Maybe raise an issue next time?

**Comment by sriyerg** [comment]
> @sriyerg: I'll take a look at this later today. For what it's worth, a PR that was merged 6 days ago isn't a very good place for a bug report. Maybe raise an issue next time?

This is not a bug report. I'm just catching up on reviews / issues where my opinion was sought. Seemed unnecessary to file yet another issue on the same topic.
