### ISSUE TITLE
[otbn] Automatically generate documentation from Python model

### ISSUE THREAD

**Issue by wallento** [lowRISC/opentitan#2618]
If the Pseudo code is in Python, the code could be generated from the documentation.
Also the instruction coding could be generated from the documentation.
It would essentially be:
```md
# Instruction Formats
## L Format
<some systematic way to describe it>
# Instructions
## LOOP
Format: L
Description: ...
Pseudocode:
<python code>
```
and translate this to:
```python
class InstructionLFormat(InstructionFormat):
  # code generate from the systematic description, essentially bit juggling and helper functions

@isa("LOOP", opcode=.., ...)
class InstructionLOOP(InstructionLFormat):
  def execute(self, model):
    # Code from above
```

> estimate 16
> remaining 2021-02-22 4

**Comment by rswarbrick** [comment]
I think that it would probably be better to do this "the other way around", so we add magic comments in the golden model that the documentation can use to show the implementation. For the decode, however, I think it makes lots of sense to extract this from the "instruction database". Initial strawman database here: https://github.com/lowRISC/opentitan/issues/2719.

**Comment by wallento** [comment]
Yes, thinking about it, I think I agree, maybe docstring can be extended for this?

**Comment by rswarbrick** [comment]
Maybe. I was imagining something even stupider, where the extractor doesn't need to understand python syntax. So you'd have lines like this:

```python
  # OTBN_INSN:BN.ADD START
  ... my implementation here
  # OTBN_INSN:BN.ADD END
```

If it's easy to load up the Python code and do reflection to find the relevant stuff, maybe that would be neater, but I'm not sure it's required.

**Comment by wallento** [comment]
Are you planning to implement it in Python? I think I have a good idea how this can be done by enhancing the way that codings etc. are done

**Comment by wallento** [comment]
Woah, I have something incredibly elegant, based on https://docs.python.org/3/library/inspect.html
I will polish it over the weekend and put into the PR!

**Comment by rswarbrick** [comment]
That sounds great! Yes, this will be in Python (an extension to the existing `yaml_to_doc.py`).

**Comment by wallento** [comment]
There is some first work here: https://github.com/wallento/opentitan/blob/otbn-python-model/util/otbnsim/otbnsim/doc.py
It generates dicts and should be able to replace the yaml as drop-in, we should discuss the format

**Comment by rswarbrick** [comment]
We've got a reasonable way towards doing this nicely now. There are still some improvements we could make, though. Here's a list of what I know is left to do:
- [ ] Figure out how to represent ECALL
- [ ] Figure out how to represent error conditions
- [ ] (Maybe) avoid using `return` in instruction definitions? It looks a bit odd; maybe just use if/else branching.
- [ ] Figure out how to represent loop state (`state.loop_start(iters, bodysize)` looks a bit rubbish)
- [ ] Inline or document `logical_byte_shift`.
- [ ] Inline `add_with_carry` (especially as it's kind of trivial except for in BN.ADDC)
- [ ] Similarly for `sub_with_borrow`
- [ ] Improve how we represent flag state changes
- [ ] Handle indexed WSR accesses (`state.wsrs.read_at_idx(...)`)
- [ ] Properly handle named CSR / WSR accesses (`state.csrs.flags`, rather than `state.read_csr(...)`)
- [ ] Come up with a nicer formulation for `get_quarter_word_unsigned`. Maybe read the whole WDR and then do the lane extraction in a (static) method on the instruction object?
- [ ] Similarly for `set_half_word_unsigned`, although there's just one call site, so maybe just inline it.
- [ ] Inline `set_mlz_flags`?

**Comment by rswarbrick** [comment]
There are a few things left here, but we've definitely got to the "decreasing return for effort" stage. I'm going to close this and we can always track and/or fix specific further improvements separately.
