### ISSUE TITLE
[doc] Hardware Designs Dashboard text unreadable unless in dark mode

### ISSUE THREAD

**Issue by asb** [lowRISC/opentitan#2634]
![Screenshot_2020-06-26 OpenTitan Documentation](https://user-images.githubusercontent.com/1900/85821781-48df4280-b771-11ea-9743-6fd543900ad0.png)
https://docs.opentitan.org/doc/project/hw_dashboard/
The table contents are all in white, and only visible if switching to dark mode.

**Comment by imphil** [comment]
I don't find this document linked from https://docs.opentitan.org/doc/project/ either, so maybe it's an old page? The linked one is at https://docs.opentitan.org/hw/ and works just fine.

**Comment by asb** [comment]
Ah, the bug is likely that this old page is hanging around then. It's the first or second result on Google for opentitan dashboard.

**Comment by imphil** [comment]
@towoe or @gkelly might know more

**Comment by towoe** [comment]
Interesting find. I do not see this page on a local instance. So might this be a deployment relic?

**Comment by sjgitty** [comment]
Yeah, that appears to be `https://docs.opentitan.org/doc/project/hw_dashboard/` which should have been deprecated. I can remove that with a PR

**Comment by sjgitty** [comment]
> Yeah, that appears to be `https://docs.opentitan.org/doc/project/hw_dashboard/` which should have been deprecated. I can remove that with a PR

ooh I see, it is removed from our GH repo, yet it lingers in docs. @gkelly any idea what is going on there? Does hugo need a scrub before rendering?

**Comment by gkelly** [comment]
The way the docs push works is that it generates locally and then `gsutil rsync`s the tree over to the hosting bucket. When I first wrote the scripts I was worried that a bad generation run would potentially wipe the current documentation set out if the output directory was empty, so I didn't pass `--delete` to the rsync. Let me check the logs to see if it's ever happened, and if not I can just add `--delete` so that it takes old pages out of the serving bucket.
