### ISSUE TITLE
[otbn] loading cryptographic constants into wide register

### ISSUE THREAD

**Issue by felixmiller** [lowRISC/opentitan#2661]
Maybe I am not seeing it but it seems to me that we are currently lacking a clean way of loading cryptographic constants into wide registers.

I am looking for replacements for sequences like [this one](https://chromium.googlesource.com/chromiumos/platform/ec/+/refs/heads/cr50_stab/chip/g/dcrypto/dcrypto_p256.c#50) (line 50 to 65).

@imphil You had a replacement sequence proposed for the `movi <reg>.<limb>, <imm>` type of instruction [here](https://docs.google.com/document/d/14zRcRz8d-1aY7gJ9EbsKhAizM3tRLASAoypGqDpOl1c/edit#heading=h.2doq5elm953j).
(section _Load immediates into wide registers: movi_) and it is indeed a good replacement for any constants used as pointers later on since they go in GPRs now, but it seems to me it can't be used for loading the crypto constants.

**Comment by imphil** [comment]
Since GH was down before Felix and I discussed this issue in chat.

We need a solution which:
- Allows us to load constants into WREGs
- These constants need to be part of the (code) integrity check.

I can see two general approaches:

1. Put the constants into a "constant section" of DMEM (think .rodata), and load them together with the initial DMEM before starting OTBN. That's how "normal" software would do it: the loader would load constants directly into RAM before starting the application.
   - Pro: Fast: Loading of constants from DMEM into a WDR takes a single cycle.
   - Pro: Space efficient: The encoding is more efficient; the exact efficiency gain depends on the size of the immediate in a "load wide immediate" function.
   - Con: The integrity check needs to be cover not only code, but also the (constants within) DMEM. There are multiple approaches to that; which one is most efficient/preferred will depend on a couple other factors.

2. Put the constants into the instruction stream in the form of immediates. There are a couple ways of doing that that I can think of right now (and probably a couple more).
   1. A wide load immediate instruction.
   2. Make the WDR 0 (w0) a "zero-register" (a register which always reads 0 and discards writes), as in RV32, and use `BN.ADDI` for loading.
   3. Provide a register-to-register bridge between the 32b GPRs and the 256b WDRs, and use "ADDI dest x0, immediate" to load 32b registers with constants, and then transfer them to the wide side.
   4. (Already possible today.) Use 32b instructions with immediates to write these constants to DMEM from the 32b side, and then load this DMEM word into a WDR from the 256b side.


I personally would explore Option 1 first to see if we have other reasons why extending the integrity check to DMEM might be a good idea. This will then give us a better understanding of the cost tradeoff.

If we want to put constants into the instruction stream, I'd make `w0` a zero register. Doing that aligns with what we do on the 32b side, which makes the whole architecture easier to understand. The cost, of course, is one less 256b register available to software, which might or might not be a loss.

**Comment by cdgori** [comment]
I am generally in favor of option #1 - these specific constants look to be curve-parameter related, and putting them into ".rodata"-like regions sounds good to me.  We might be able to enforce other access semantics (e.g. no writes once executing, or something like that, or perhaps some other continuous integrity check) on that region to keep software from mangling the curve parameters (which is a known type of attack on EC), but even just having the initial integrity check is a good start.

**Comment by tjaychen** [comment]
Sorry i'm a bit out of date here.  For what the integrity check you guys are talking about, is that supposed to be done by OTBN or the host processor? If it's the host, then I definitely agree with option 1... because the host will load the code / data as a block out of flash anyways.  Where it places everything inside OTBN i think is just semantics.

Am I missing something?

**Comment by felixmiller** [comment]
- Yes, the constants in the linked code are curve domain parameters. I also agree that putting such constants into dmem is the more natural way. Nevertheless I wouldn't close the door on the possibility to have constants also in the instructions stream too early.
- Practically this is already possible with the current spec, since the mod register is mapped on CSR. We can therefore load constants in the mod reg and move them to any wide register. This is of course not intended usage. To make this more generic I would suggest to map one generic wide register (e.g. w0) on CSRs instead of the mod WSR. This mechanism can then also be used to load a modulus and should not increase hw complexity.
- Regarding integrity checks: These are checks to be done at some point within otbn. In case we want to support fully verified cryptographic primitives (one way functions) at some point independent of code verification by the host.

**Comment by cdgori** [comment]
@felixmiller for the integrity checks one way functions comment - do you imagine a local-to-OTBN hash (SHA2?) engine to do this?  Or something else?  Just trying sync up my understanding with yours.

**Comment by rswarbrick** [comment]
Are we still considering this? Naively, I would have thought that we'd do any hashing/signing on "the segments that are loaded". This would mean that passing curve parameters in DMEM (like we're doing at the moment) would be absolutely fine.

**Comment by cdgori** [comment]
Working through my backlog, tagging @felixmiller here to comment.  I feel like we settled on passing curve params via DMEM at some point, but early on Felix wasn't 100% sure that would be the solution.

**Comment by felixmiller** [comment]
I think this can be closed now. In our curve-specific crypto code (P-256, P-384) we moved the constants to the data section a while ago. For the (yet to come) generic version, we will have to pass the domain parameters through the IBEX/DMEM interface anyways.

**Comment by rswarbrick** [comment]
Sounds good! Thanks for the confirmation.
