### ISSUE TITLE
[usbdev] Is tx_mode_se needed?

### ISSUE THREAD

**Issue by mdhayter** [lowRISC/opentitan#2704]
Currently there is an output "tx_mode_se". Can we replace it by just controlling the enable on "se0"? If se0 enable is set then the tx is set to "differential" mode (i.e. d and se0) and if se0 is disabled then it is normal mode (dp and dn).

**Comment by vogelpi** [comment]
Hi @mdhayter ,
This change will be a bit more invasive as those signals propagate through the top level. But yes, this can be done. Right now the enable for both se0 and tx_mode_se is statically set to one.

I am out of office this week, but will look into this next week.

**Comment by a-will** [comment]
This is a fairly minor cleanup, so it doesn't need to take priority. However, I'd be in favor of removing it.

This seems pretty straightforward. Instead of hard-coding the enable for `se0` to 1, we can assign it based on the TX configuration register. Then an integration can use the enable at the top level to drive the transceiver's mode pin, if needed.
