### ISSUE TITLE
[hw, gpio/pinmux/padctrl] intended behaviour of the Pad Control Pad Wrapper

### ISSUE THREAD

**Issue by silvestrst** [lowRISC/opentitan#2707]
https://docs.opentitan.org/hw/ip/padctrl/doc/generic_pad_wrapper.svg
https://docs.opentitan.org/hw/ip/padctrl/doc/padctrl_block_diagram.svg

My interpretation of the two above diagrams, taking GPIO inputs and outputs as an example, is following:
Via [Pinmux](https://docs.opentitan.org/hw/ip/pinmux/doc/index.html), if we connect GPIO0 output to MIO0 output, and GPIO1 input to MIO0 input. Then when we drive GPIO0 output, we would be able to read the value on the GPIO1 input.

This is what schematics for [Pinmux](https://docs.opentitan.org/hw/ip/pinmux/doc/index.html) and [Pad Control](https://docs.opentitan.org/hw/ip/padctrl/doc/index.html) suggest. Furthermore, the [GPIO](https://docs.opentitan.org/hw/ip/gpio/doc/index.html), "GPIO input" section also implies this behaviour:

> The contents of DATA_IN are always readable and reflect the value seen at the chip input pad regardless of the output enable setting from DATA_OE. If the output enable is true (and the GPIO is connected to a chip-level pad), the value read from DATA_IN includes the effect of the peripheral's driven output 

Is my interpretation correct? It would be great if someone could clarify this for me.

**Comment by silvestrst** [comment]
Hi @msfschaffner , I wasn't sure who to ask, `git log` showed that you have quite a few recent commits on Pad Control, so I have assigned this issue to you (formality). Thanks.

**Comment by silvestrst** [comment]
@GregAC @tomroberts-lowrisc

**Comment by silvestrst** [comment]
@gkelly and @lenary for visibility

**Comment by msfschaffner** [comment]
Hi @silvestrst,

Your interpretation is correct. Since we're using bidirectional pads, the value driven to a pad can be read back via the corresponding input signal.

Is there something that does not behave the way it should?

**Comment by silvestrst** [comment]
Hi @msfschaffner , I am currently working on combined GPIO, Pinmux and Pad Control sanity test, essentially:

> Via Pinmux, if we connect GPIO0 output to MIO0 output, and GPIO1 input to MIO0 input. Then when we drive GPIO0 output, we would be able to read the value on the GPIO1 input.

When I tried it on verilator, I didn't seem to get the driven signal on GPIO1 input (see the quote above). I have then dumped a Verilator trace (by launching it with "-t") and did not see expected changes in signals there either (I have accidentally deleted the trace, so can't specify the exact signals I was looking at).

It of course could be that one of the DIFs that I am using is bad, or my test is bad, but before digging in, I just wanted to confirm that mentioned above setup would be observed and function as expected on verilator?

I guess "Pad Wrapper" is not an actual separate module, it would be great if you could let me know what signals I should trace in simulation that correspond to those in the "Generic Pad Wrapper" diagram.

Thanks

**Comment by msfschaffner** [comment]
Ah I see. The issue is that you are running this on Verilator, since the chip-level module for Verilator (`top_earlgrey_verilator`) is different from the ASIC and FPGA chip-level modules (`top_earlgrey_asic`, `top_earlgrey_nexysvideo`). The Verilator top does not instantiate the padring, and hence it does also not simulate the pad wrapper.

This is a known issue. Also the FPGA and ASIC tops are slightly different. We discussed this already at the end of last year (see https://github.com/lowRISC/opentitan/issues/295) but never really managed to fully align all top-levels that we have.

We should revive this alignment effort though. @tjaychen @eunchan @sjgitty for visibility.

As a general warning (I think I have mentioned this before), I should say that the pinout / padctrl / pinmux will undergo changes after Bronze due to additional requirements that came in recently. Hence my recommendation would be to not invest too much effort in writing SW tests for padctrl / pinmux, since the CSR layout will likely change.

**Comment by silvestrst** [comment]
@msfschaffner thank you for clarifying this for me!

> We should revive this alignment effort though.

Am I understanding correctly that this is planned work, and verilator should be able to simulate this behaviour at some point in future?

> As a general warning (I think I have mentioned this before), I should say that the pinout / padctrl / pinmux will undergo changes

I was mainly working on insel/outsel functionality, for which the CSRs will stay the same? Is this still holds true? But anyhow, I am  planning to hold off this work for now.

**Comment by msfschaffner** [comment]
> Am I understanding correctly that this is planned work, and verilator should be able to simulate this behaviour at some point in future?

This is something we will align eventually, yes. It just has not been very high up the priority list.
Note however that there will likely remain small differences between the platforms, since it is not always possible to make them completely identical.

> I was mainly working on insel/outsel functionality, for which the CSRs will stay the same? Is this still holds true? But anyhow, I am planning to hold off this work for now.

The insel / outsel functionality will remain, but the CSR names and the corresponding indices will likely change. 
I'll contact you before we go in and make these changes in order to check how that would impact the DIF side. 

Apologies for blocking you on this.

**Comment by silvestrst** [comment]
@msfschaffner no problem at all, it is likely that I will have to hold off work on this peripheral for some time anyway. Thank you for getting me up to speed with the RTL top level differences and in general the progress.

**Comment by silvestrst** [comment]
* Pinmux and pad control are currently being reworked (merged together)
* Verilator target doesn't have some of the pad control functionality implemented
