### ISSUE TITLE
[ibex] Enable bit-manipulation extension

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/opentitan#2708]
Thanks to the great work of @ganoam Ibex has now support for the RISC-V Bit-Manipulation Extension draft version 0.92 and the implementation is fully verified upstream using RISCV-DV. I think we can consider to enable it also in OpenTitan.

The implementation comes in two flavors that can be selected via parameter. The two flavors enable the following subgroups of the extension:

- Balanced: Expected increase in core area 2.2 kGE, no impact on ASIC timing, enables:
  - Zbb - base extension: e.g. count leading/trailing zero, pop count, min/max...
  - Zbs - single-bit instructions: set, clear, invert, extract (useful for controlling peripherals)
  - Zbf - bit-field place (very useful for controlling peripherals) 
  - Zbt - ternary: conditional move, mix, funnel shift (useful for constant execution time)
- Full: Expected increase in core area 6.4 kGE, no impact on ASIC timing, enables all of the above as well as:
  - Zbp: generalized reverse, or-combining and shuffling (bitwise reverse and byteswap, zero-byte masking already part of Zbb)
  - Zbe: parallel bit extract and deposit (unlike in bit-field place, non-contiguous placement and extraction can be handled)
  - Zbc: carry-less multiplication
  - Zbr: CRC32

Unless we are going to implement crypto algorithms in software, the balanced implementation is probably sufficient. But I would be interested to hear your opinions.

It's worth nothing that even though this implementation is verified, the spec is still a draft. Before being ratified it might still change and those changes may be backwards incompatible. (Neither GCC or Clang have committed to maintaining support upstream for unratified versions of the specification.)

In addition, compiler support is currently not mature. Only few instructions (30 of 95, only instructions of the balanced flavor above) can be inserted automatically. Consequently, the performance gain is low (+1.7% in CoreMark, +1% in Embench). The remaining ones require the use of intrinsics. But many of the available instructions seem to be helpful for the DIFs/mmio where it seems worth to use intrinsics. My understanding is that both our LLVM and GCC toolchain have support.

For more information
- On the implementation: https://ibex-core.readthedocs.io/en/latest/instruction_decode_execute.html
- On the draft spec: https://github.com/riscv/riscv-bitmanip/blob/master/bitmanip-0.92.pdf
- On compiler support: https://www.embecosm.com/2019/10/22/gcc-risc-v-bit-manipulation-extension/

**Comment by vogelpi** [comment]
This is probably relevant for many people. To ping some: @sjgitty , @tomroberts-lowrisc, @tjaychen , @cdgori , @eunchan , @msfschaffner,  @moidx , @asb, @gkelly , @lenary , @alphan ...

**Comment by lenary** [comment]
> My understanding is that both our LLVM and GCC toolchain have support.

This is approximately correct. We have been building a combined toolchain with support for the B extension for about a month now, and could switch to using it instead. It supports assembling B instructions, and in gcc's case, compiling to B instructions (support for this has not landed in LLVM upstream yet). All the toolchain's libraries are built without the use of the B extension so that they can be run on ibex with or without B extension support.

**Comment by vogelpi** [comment]
Thanks @lenary. If I understand this correctly, it means that using the current OpenTitan LLVM toolchain:
- We could start to use bitmanip instructions via inline assembly e.g. in mmio when dealing with peripherals.
- No bitmanip instructions would be automatically inserted as for example with the patched GCC (which can only add a small subset anyway at the moment).

**Comment by lenary** [comment]
We have been building a toolchain. It is **not** the one that developers currently download, but a migration would not be as difficult as the one we just did to migrate to clang.

If we switched to it:
- We could use B instructions in inline assembly.
- GCC would generate B instructions when compiling C code.
- Clang would *not* generate B instructions when compiling C code.

---

I'm not sure how well you can control *which* B instructions GCC would generate, as I know ibex will only support a small subset of the entire B extension. It would be useful to know precisely which parts of the B extension that Ibex plans on supporting.

---

One issue we have is the toolchain chooses the `-march` and `-mabi` flags (because these have to be compatible with the built toolchain libraries). We only ship one config file that sets these for meson, and meson_init.sh only looks for one of these configurations (unless manually overriden). These configuration files should not be manually edited.

Switching to the new toolchain will have to happen *after* bit manipulation was switched on for Ibex, so that we don't get CI failures. In all honesty, it also needs to wait until @luismarques is back so I can work with him to ensure I've not missed anything.

**Comment by cdgori** [comment]
> Unless we are going to implement crypto algorithms in software, the balanced implementation is probably sufficient. But I would be interested to hear your opinions.

This seems correct to me.   The carry-less multiply would be the most appealing part of the full implementation, but I think all of our Galois-field stuff is going to be in (dedicated) hardware.

Do we have any idea of potential code size reductions from utilizing the balanced implementation?  Seems like DIFs could become smaller because of single-bit / bit-place instructions.  This alone might be able to justify the incremental area.

**Comment by vogelpi** [comment]
Thanks a lot @lenary for the clarification and for providing more details.

Regarding which B instructions are going to be supported: It's the idea of this issue to make a decision. But as you say, GCC does not allow you to control which B instructions are generated. Currently, it only emits instructions in the balanced group described above anyway: Zbb, Zbs, Zbf, Zbt. So for the moment, we would be safe to enable only the balanced group  in Ibex and use GCC without your latest modification. However, having B emission disabled seems to be safer until GCC allows to precisely control which instructions to emit.

**Comment by vogelpi** [comment]
> Do we have any idea of potential code size reductions from utilizing the balanced implementation? Seems like DIFs could become smaller because of single-bit / bit-place instructions. This alone might be able to justify the incremental area.

Noam did some experiments with CoreMark and Embench and the effect on code size was negligible. However, he wasn't using inline assembly for this and just relied on GCC inserting them. Also, we have support for compressed instructions in Ibex which already gives reductions in code size. This somewhat diminishes potential code size gains of the B extension (B instructions are always 32-bit).

In the PULP systems, we added a custom B extension (long before the RISC-V B extension, I think it even started when we were still using OpenRISC) and we were using these instructions in the runtime functions (interrupt handling, peripherals etc.) a lot. This gave us nice gains in performance and energy.

**Comment by lenary** [comment]
Code Generation for the B extension has landed in upstream LLVM (not sure if in time for LLVM 11, it just missed the branch, but might get backported). This allows you to enable/disable by sub-extension, so it's certainly something we could look into re code size of Balanced vs Full. It's good to know that GCC currently only emits from the Balanced set, but again this isn't behaviour we want to rely on.

I'm not sure when I can schedule the investigation of how enabling B code generation affects code size, but that feels like the next step: getting data so we have something to base the decision on. I hope that our current software codebase will be representative.
