### ISSUE TITLE
[RFC] Add support for AES CFB-128 and OFB-128 modes

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#2727]
This issue proposes the addition of Cipher Feedback (CFB) and Output Feedback (OFB) cipher block modes to AES to meet the TPM2.0 specification requirements. 

Note that CFB mode is the only cipher required by the TPM2.0 specification. We request support for OFB mode as well since it is very similar to CFB and may be potentially implemented via incremental changes.
 
Reference: [TPM Library Part 1 Architecture Family: 2.0 Level 00 Revision 01.59](https://trustedcomputinggroup.org/wp-content/uploads/TCG_TPM2_r1p59_Part1_Architecture_pub.pdf) Section 11.4.7 Symmetric Encryption.

Filed as RFC since this is a feature request.

Adding for visibility: @vogelpi @alphan @cdgori @gkelly @sjgitty @tjaychen

**Comment by vogelpi** [comment]
Thanks @moidx for opening this issue and adding a reference to the relevant TPM spec.

On top of the current architecture, these modes can be added at low hardware cost:

- CFB-128 meaning CFB with a feedback length or segment size of 128 bits can be added at zero hardware cost. (Theoretically, the feedback length can be any number between 1 and 128. But according to the referenced document TPM 2.0 only requires 128 - the most simple variant.)
- OFB requires one more 128-bit mux input.

By adding one more 128-bit mux input, block operation for both modes can be made 1 cycle faster assuming the input data can be provided fast enough by the processor (12, 14, 16 instead of 13, 15, 17 depending on the key length).

In terms of verification, I think cost is also reasonable. @rasmus-madsen already added support for CBC and CTR modes in DV. Testing also CFB-128 or OFB is mainly a matter of adding support in the DPI model which I would do.

**Comment by vogelpi** [comment]
One more note on the feedback length or segment size: Common values are 1, 8 and 128. If we need support for values other than 128, the implementation is going to be much more costly as this requires a lot of additional muxing resources. Low-power devices I have seen so far usually only support 128 bits (what is needed for TPM 2.0). I thus suggest only to implement this version, i.e., CFB-128.

**Comment by cdgori** [comment]
I think it's fair to refine the RFC to be only for CFB-128.  If we find another application in the future that needs say, CFB-8, we can make another RFC.

Given the small resources for CFB-128 (and the need for it in TPM) this is a pretty simple one to justify, I hope.  OFB basically comes "for free" with this, other than the DV cost.

**Comment by sjgitty** [comment]
The Technical Committee has reviewed this RFC and requested modifications.

The modifications requested include to clarify the mode sizes requested. If as @vogelpi has suggested, only CFB-128 and OFB-128 are requested, then the necessary changes seem minor enough to have had sufficient review. If other mode sizes are needed, the TC has requested to estimate the cost so that other reviewers can weigh in. Also, if other sizes are requested, the TC would like clarity on the role of satisfying TPM as a requirement to weigh against the increased cost.

The TC will re-review in two weeks after the modifications have been made.

**Comment by vogelpi** [comment]
Thanks @sjgitty for reporting back.

According to the TPM 2.0 specification (referenced by @moidx ) the CFB is used with following parameters:

![tpm_cfb](https://user-images.githubusercontent.com/20307557/87643743-853c0800-c74b-11ea-9941-63b2529298e1.png)

Size of feedback buffer, variable and plaintext variable are all equal to n (size block cipher = 128 for AES). I don't have access to the cited ISO/IEC document to verify the meaning of these parameters but the [corresponding NIST document](https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-38a.pdf) just mentions one single parameter for CFB which is the segment size/feedback length.

OFB does not have a corresponding parameter. Always all 128 bits are fed back.

**Comment by moidx** [comment]
Updated title to reflect the feedback configuration constrained to the block size.  I agree with @cdgori and @vogelpi to restrict this RFC to CFB-128 and OFB-128 as this fulfills the TPM requirement.

**Comment by alphan** [comment]
I also don't have access to the cited ISO standard but just wanted to point out that this [page](https://www.iso.org/standard/38761.html) says that it has been revised by [ISO/IEC 10116:2017](https://www.iso.org/standard/64575.html).

**Comment by sjgitty** [comment]
The Technical Committee has reviewed this RFC and approved the RFC as stated. Thank you for the clarifying updates to the proposal.

**Comment by vogelpi** [comment]
The discussed modes have been implemented a while ago already and they are both supported in DV. I consider all the required work to be done and will close this issue now.

Please feel free to reopen if necessary.
