### ISSUE TITLE
[uart, dv] How is rx_overflow interrupt verified

### ISSUE THREAD

**Issue by tunghoang290780** [lowRISC/opentitan#2763]
Hi,

I run uart_fifo_overflow test and got the waveform for interrupt (internal) event signals and output ports. From the waveform, it seems that rx_overflow interrupt is not asserted so how is that feature verified?

![image](https://user-images.githubusercontent.com/53881329/87090788-61c60a00-c1ed-11ea-8c9d-6c332f4526a2.png)

**Comment by sriyerg** [comment]
@weicaiyang is on vacation until August. I will try to take a look tonight.

**Comment by tunghoang290780** [comment]
> @weicaiyang is on leave until August. I will try to take a look tonight.

@sriyerg thanks

**Comment by weicaiyang** [comment]
Hi Tung,

Sorry for the late reply. I can finally connect to my workstation.

In the overflow test, it simply overrides below task so that it may continue send rx item even fifo is full.
```
  virtual task wait_for_rx_fifo_not_full();
  endtask : wait_for_rx_fifo_not_full
```

I just reran one test with seed=1 and I can see rx overflow happens a few times
![Screen Shot 2020-08-07 at 2 25 20 PM](https://user-images.githubusercontent.com/49293026/89691084-e96e6980-d8bc-11ea-8d0b-348abfbc1a40.png)

In your test, there may be 2 reasons that we didn't see rx overflow
1. It randomizes a small amount of rx items, which is not enough to have overflow. It could happen in some seeds, but chance is low
2. `intr_rx_overflow_o` may be gated by `intr_enable`. when `intr_enable` ==0, interrupt isn't shown in the pin.

**Comment by rasmus-madsen** [comment]
@weicaiyang @tunghoang290780 
this is something that should be caught by coverage in the future.

**Comment by weicaiyang** [comment]
> @weicaiyang @tunghoang290780
> this is something that should be caught by coverage in the future.

@rasmus-madsen we have coverage for each interrupt. One sim may not hit this rx_overflow but regression should cover it.

**Comment by rasmus-madsen** [comment]
@weicaiyang sorry for the late reply.
Great. that Is all I was trying to say, as long as we have coverage - not seeing this in a single test is not concerning.

**Comment by weicaiyang** [comment]
@tunghoang290780 do you have more comment? Or can we close this issue now?

**Comment by tunghoang290780** [comment]
@weicaiyang sorry for my late response. I closed this issue!
