### ISSUE TITLE
[otbn] Would it make sense to split `bn.mulqacc` into several different instructions?

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#2777]
The current syntax for `mulqacc` is this:
```
      BN.MULQACC [<wb_variant>][<zero_acc>] [<wrd><wrd_hwsel>,] <wrs1>.<wrs1_qwsel>, <wrs2>.<wrs2_qwsel>, <acc_shift_imm>
```

The `<wrd>` argument is required if and only if `<wb_variant>` is specified. This is a bit complicated. Would it make more sense to define one opcode for when writeback is enabled and one for when it's not? (This would not have any effect on the encoding or the hardware; just on assembly syntax).

**Comment by rswarbrick** [comment]
@GregAC: I know you specified this in the first place. Would this split make sense to you?

@felixmiller, @wallento

**Comment by GregAC** [comment]
Mentally I think I had seen it as three different instructions anyway `BN.MULQACC` `BN.MULQACC.SO` `BN.MULQACC.WO` 

Perhaps we just need a documentation tweak so rather than having a `[<wb_variant>]` field we just list three different instruction mnemonics along with the current description with the appropriate tweaks? Preferably we don't want to replicate the rest of the instruction description three times.

**Comment by rswarbrick** [comment]
Cool, sounds sensible to me. I'll try a documentation patch now.

**Comment by felixmiller** [comment]
I don't really have a preference here, @rswarbrick proposal lgtm and is probably a bit better readable on the asm level

**Comment by felixmiller** [comment]
Also, the `<wrd_hwsel>` argument is only needed for the .SO variant not for the .WO variant, right?
