### ISSUE TITLE
[otbn] Build system integration

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#2936]
We are starting to produce (example) software targeting the OTBN processor. This effectively is a separate processor architecture with a dedicated (assembly-only) toolchain.

We have two use cases for the software produced by this toolchain:

- Normally, OTBN software is loaded into OTBN from Ibex by writing it to a special device register. For this use case, we have the following flow: OTBN assembly -> OTBN assembler -> ELF file -> objcopy -> a C header containing the binary as define/char const -> compile/link with the actual software (running on Ibex)

- For simulations and DV with OTBN in isolation, we will directly provide a way to load the OTBN-ELF-file into the simulation (i.e. without letting Ibex load the software into OTBN)

The question is: how do we want to produce the OTBN software, i.e. how do we want to call the toolchain? Are we OK with calling the toolchain components (assembler, objcopy, etc.) in a simple script which produces the right header file for inclusion in the main software (e.g. meson calling an external script to produce this data, as we do for auto-generated headers), and use similar scripts for our simulation use cases, or do we want more fully-featured build system integration?

@gkelly @lenary 

---

Tracking:
- [x] #3311 
- [x] Make `as` available with find_program() in Meson: #3310, https://github.com/lowRISC/lowrisc-toolchains/pull/33. Needs an update of the minimum required pre-built toolchain in #3801 

> estimate 8
> remaining 2020-10-30 1

**Comment by rswarbrick** [comment]
Another way to do part (1) is `OTBN ELF file -> objcopy -> binary blob in Ibex ELF file (my_blob.o)`. If you do that, you can link your Ibex code against the ELF object and the build system looks much less weird (no auto-generated source code).

**Comment by lenary** [comment]
I don't think meson can do two cross-compiler toolchains (for separate parts of the build). So I think we end up having to invoke scripts from meson to generate the otbn object, and then put it into something DV or sw can use. This is yet another mark against meson. 

For Ibex images, if we're injecting directly into the ibex elf file as @rswarbrick proposes, we can only do that for one OTBN image at a time without some kind of manifest format, which I'd rather not define until we know what SW needs. For the moment, I feel we should start by doing it @imphil's way (generating a header), and later transition to the more complex ELF injection.

**Comment by rswarbrick** [comment]
I'm fine with that approach, but I'm not quite sure what you mean about needing a manifest format. I was imagining that you would generate N binary blobs in N ELF files, each defining a symbol like `my_algorithm_seven` or whatever. Then the "manifest" is just a load of lines like `extern void *my_algorithm_seven;` in the Ibex source code. Indeed, the linker will throw away any objects we turn out not to need.

Thinking about it, these might need their own section (to ensure they end up next to each other), otherwise you have to explicitly lay them out in OTBN memory, but that's equally true for the C header approach too.

**Comment by lenary** [comment]
Copying the data is easy. Generating symbols that point to the right place in the final binary isn't, and you also probably want both a start address and a length at least in the manifest (if you're swapping in and out parts of the OTBN image dynamically).

**Comment by lenary** [comment]
Oh I'm wrong, objcopy can create the symbols that point into the right place, sorry.

**Comment by lenary** [comment]
Ok, so I don't mind which of Philipp's/Rupert's approaches we take, but it will have to be with scripts external to meson, and not with another cross-compilation configuration.

**Comment by imphil** [comment]
"will have to be with scripts external to meson" Sounds like a use case for Makefiles!

**Comment by asb** [comment]
> Another way to do part (1) is `OTBN ELF file -> objcopy -> binary blob in Ibex ELF file (my_blob.o)`. If you do that, you can link your Ibex code against the ELF object and the build system looks much less weird (no auto-generated source code).

I missed the previous discussions about using ELF vs a flat binary for OTBN, but either way, using objcopy with --binary-architecture to easily link it in without generating header files etc seems a nicer approach to me.

**Comment by lenary** [comment]
@imphil I guess I might not have been clear by saying "scripts external to meson": we'll need to use meson external commands, so that device software can still depend on the results of building otbn images - we just cannot use meson's inbuilt cross-compiler support because we're already using that for ibex.

**Comment by rswarbrick** [comment]
Thinking about what @lenary said:

> ... and you also probably want both a start address and a length at least in the manifest (if you're swapping in and out parts of the OTBN image dynamically).

This is true. In fact, it's probably a bit more complicated than that. For example, you'll probably want to support having algorithms A and B, which both use common code C. So you'll need to load either A+C or B+C (but maybe they don't both fit in OTBN memory at once).

The usual approach to this problem is called an "overlay". The binutils linker actually has [overlay support](https://sourceware.org/binutils/docs/ld/Overlay-Description.html#Overlay-Description) (a nice surprise!). In the example above, you'd have 2 overlaid regions. One would contain A and the other would contain B. The `NOCROSSREFS` feature in the linker catches silly errors like accidentally calling function in B from code in A.

So I'm imagining that we'll bundle up all the OTBN code for the application into a single, linked (OTBN) ELF. We could then use objcopy to transmogrify that into something that could be linked with Ibex code. This needs judicious application of the `--keep-global-symbol` flag, which lets us join the two namespaces cleanly. The result would be an ELF blob with some symbols pointing at the start and end of the "segments" of code and data, together with some symbols pointing at the the entry points we want to keep. Note that these symbols would be pointing at a sort of "double-LMA": the (Ibex) address of the data, before it gets copied to OTBN.

The Ibex code then needs to load stuff into OTBN. If we're doing clever things with overlays, there's some logic here, but it's not massively complicated. It will need to know a "single-LMA" for each blob: the address in the Ibex address space corresponding to the OTBN memory where the blob should be written.

Finally, the Ibex code will need to set a couple of pointers in OTBN addresses (the VMA). For example, it will probably need to set a reset vector register. That needs a little more simple arithmetic, converting from the base address of OTBN's instruction memory as seen from Ibex to the base address as seen from OTBN (which is zero, in fact).

And then you're done. Easy!

In practice, there are various ways for this to come unstuck (such as alignment problems between sections, missing entry points and so on), so it's probably wise to have a "link-otbn-application" script, which does some sanity checks on the result.

**Comment by lenary** [comment]
I did not expect to see the following when referencing overlay loading:
> And then you're done. Easy!

I really think if we start using overlays this early, we have strayed far from "the simplest thing that can work". I can see us getting to a point of requiring them, but I think we can deal with the duplication of code across images before then. 

All I meant for manifest and dynamic loading is if I want to run a specific algorithm on OTBN, even if I'm loading a single blob, I still need to know where it is, and what length it is (and potentially where to load it into OTBN memory if it cares). I may also need to to check the hash of that blob, if I care it's not been tampered with.

**Comment by moidx** [comment]
I agree with @lenary's comments.

In terms of programming model, we need to be careful with how Ibex interacts with otbn. For crypto isolation purposes, Ibex software requires the ability to determine the state of execution of otbn, and have the ability to, in some cases, safely-clear data memory and regs before execution. 

So far my understanding is that we have enough IMEM to execute all required public crypto algorithms without having to reload IMEM between runs. The controller software can safely clear state (need to add a tracking issue for this), reload IMEM if needed, trigger otbn runs with deadline (#2748), and finally clean-up state.
