### ISSUE TITLE
[otbn] Evaluate spec change: set flags in BN.MULQACC

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#2979]
For ECC crypto, @felixmiller has determined in https://github.com/lowRISC/opentitan/issues/2470 that BN.MULQACC which is also able to set flags would save one instruction.

With the 128x128 multiplications (OTBN `MULH`) a typical sequence for a full 256x256 mult looks like this:
```
BN.MULH w3, w1.L, w2.L
BN.MULH w4, w1.U, w2.U
BN.MULH w5, w1.U, w2.L
BN.ADD w3, w3, w5 << 128
BN.ADDC w4, w4, w5 >> 128
BN.MULH w5, w1.L, w2.U
BN.ADD w3, w3, w5 << 128
BN.ADDC w4, w4, w5 >> 128
```

(this gives [w4, w3] = w1*w2)

The last instructions in such a sequence is always an `ADDC` with the consequence that the flags are set based on the result.
Often the MSB needs to be tested afterwards (e.g. in a subsequent Select instruction).

Workaround in the PoC is to add a [dummy](https://github.com/felixmiller/ot-dsim/blob/new-isa/asm/otbn_p256_mul64.asm#L82) `BN.ADD` at the end of each multiplication and add 0 to the result. This adds quite some overhead though and we should probably set the flags in `BN.MULQACC.SO` and `BN.MULQACC.WO` well.

We need to make sure though that this does not brake things elsewhere (a previously set flag supposed to survive a multiplication instruction)

Tasks in this issue:

- [x] Come to an agreement if we should do that.
- [ ] Update the spec with the new semantics
- [ ] Update the implementation (RTL and simulator)

> estimate 4

**Comment by imphil** [comment]
@felixmiller is commenting in https://github.com/lowRISC/opentitan/issues/3683
> We might think of setting the MLZ Flags in the MULQUACC instruction if:
> 1. This is not a timing problem in the HW
> 2. We are sure that we do not clobber flags anywhere that are needed after an MULQACC where we can switch to the other FG
> 
> This would save us dummy instructions in the multiplication kernels, where this is performance critical.
> I need to analyze #2 first before we move forward.

**Comment by GregAC** [comment]
The current MULQACC implementation doesn't touch the flags but this can be altered so it does. We should probably see the timing results for the version without first to understand how much slack we have to play with (as this is likely to increase the critical path).

One outstanding question is are we happy with only affecting FG0? We'll need to play with instruction encodings if we want to target FG0 and FG1.

**Comment by GregAC** [comment]
At this point I can easily add flag computation for a fixed flag group to `MULQACC`. I think we still need to decide on whether we want `MULQACC` to choose a flag group (meaning playing with the encoding). @felixmiller any thoughts?

**Comment by felixmiller** [comment]
@GregAC: I would say if we have the encoding space available it would be better to allow setting the flag group (Didn't we somehow find an empty bit recently).

Another thing I came across: 
The typical sequence where `MULQACC` setting the flags would be helpful looks like this (last 4 instructions of mult kernel in Barrett):

```
bn.mulqacc            w9.0, w11.1,  64
bn.mulqacc.so w18.L,  w9.1, w11.0,  64
bn.mulqacc.so w18.U,  w9.1, w11.1,   0
bn.add                w18, w18, w31
```
the last instruction is the dummy instruction for setting the flags currently.

An issue I am seeing now is that the actual result (in `w18`) that has to be evaluated for the flags is never fully available in a single `MULQUACC` since it is assembled over two instructions. Or could it be gained from the accumulator in the 3rd instruction somehow before shifting?
In order to answer #2 from @imphil 's question above I tested setting the `C` and `M` flag in `bn.mulqacc.so` when used to shift out the upper half word and the `L` flag when used to shift out the lower half word. There is no point in setting `Z` flag since we don't know whether the other half word was zero.
This then allows to get rid of the dummy add. It did not create an issue with existing code (RSA+ECC).

If this is the only way to set the flags I wonder if this does not over-complicate the spec...

**Comment by GregAC** [comment]
One way to get the bit is only allow shifts of 0 and 64 for shifting the multiply result before adding to the accumulator (the <acc_shift_imm> field in the spec). We only use 0 and 64 I think. I specified the 128 and 196 just to add a little extra functionality, but didn't have a particular use in mind. Given we don't seem to have a use for them and we do have a use for the flag group setting it would make sense to sacrifice one for the other.

On the half-word writes how about a slightly more complex flag semantics much like you've already mentioned? 

- When writing to `.L` only set the `L` flag
- When writing to `.U` only set the `M` flag

Zero is trickier but not impossible e.g. we could do

- When writing to `.L` set `Z` based on the half-word it's writing
- When writing to `.U` clear `Z` if the half-word it's writing is non-zero otherwise leave it alone

I'm not certain what to do with `C`. We could generate something based upon the carry out of the accumulate sum but with the way we're using `MULQACC` you shouldn't ever get a carry generated so leaving `C` alone, like with the logical operations would be a reasonable option.

**Comment by imphil** [comment]
Agreed to move forward with this spec change. Requires updates to spec, ISS, SW, and RTL.

**Comment by rswarbrick** [comment]
For `bn.mulqacc` (without writeback), I assume we're going to leave flags unchanged? In which case, shall we keep the 2-bit shift, or knock that down to 1 as well for uniformity?

**Comment by GregAC** [comment]
I'd go for uniformity

**Comment by rswarbrick** [comment]
I've written a proposed patch for the spec and done the corresponding ISS changes. Of course, everything will break if we push this up without changing the RTL too, so I've just pushed it to a [branch on my fork](https://github.com/rswarbrick/opentitan/tree/mulqacc-flags). You should be able to get a copy with something like:

    git fetch https://github.com/rswarbrick/opentitan.git mulqacc-flags
    git checkout -b FETCH_HEAD mulqacc-flags

@GregAC: Please can you take a look? I think the new spec does what we agreed above (and *think* that I implemented it right in the ISS!). Note that the smoke test doesn't assemble with this change: the calculation of w31 on line 259 uses a shift of 128. Looking harder, this code comes from the "replacing MULH" example. Are we sure we're ok with losing that trick? If not, we could choose to keep the larger shifts for `bn.mulqacc` and `bn.mulqacc.wo` and only disallow them for the `.so` variant (which means we can re-use the destination halfword bit).

**Comment by GregAC** [comment]
I think we can avoid the need for the 128 bit shift by using two `.so` as the final two instructions.

However I quite like the idea of keeping larger shifts for the plain `bn.mulqacc` and `bn.mulqacc.wo`. It has some intuitive sense behind it in that if you're using `.so` you're accumulating things bit by bit, shifting out as you go so 0 and 64 is all you need (with 128/192 what you accumulate doesn't effect the 128-bits you're shifting out), but with `bn.mulqacc` and `bn.mulqacc.wo` alone you're doing things a bit differently so the wider shift possibilities are more useful.

**Comment by rswarbrick** [comment]
Ok, sounds good. I'll update the spec to look like that (with 2 bits for shifting except for `bn.mulqacc.so`).

**Comment by rswarbrick** [comment]
Oh, wait! There's a spare bit in `bn.mulqacc.so` anyway! We can have 2-bit shifts everywhere. Yippee!

**Comment by rswarbrick** [comment]
Right. I've pushed up what I hope is a much more sensible solution. It's at the branch above, and I've also opened a draft PR so that people can ~~shoot it down~~ make constructive criticism :-)
