### ISSUE TITLE
[Ibex/NMI] How to connect the first alert handler escalation signal to the NMI of the processor

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#2990]
Raising an NMI is the lowest severity countermeasure that the alert handler can trigger in OpenTitan if a certain (programmable) escalation condition has been met (e.g., too many alerts or one highly critical alert have been triggered). Such an escalation event is signaled to the module implementing the countermeasure using a differential signalling protocol for security reasons. 

Hence, in order to connect the escalation signals to the NMI of Ibex, we need to convert the differential protocol to a single-ended one using an instance of the `prim_esc_receiver`, preferably as physically close as possible to the processor core. Hence, I think it would probably be best to instantiate the escalation receiver right inside the `rv_core_ibex` wrapper. See #2988 for a draft PR that prototypes the NMI connection from the alert handler to Ibex, and LMKWYT.

Another point we should consider is the encoding of the NMI itself (the `.esc_en_o ( irq_nm   )` signal). I.e., while the escalation enable is level encoded, it behaves rather like a pulse that is asserted for a programmable amount of cycles corresponding to the length of escalation Phase 0 in the alert handler [escalation timers](https://docs.opentitan.org/hw/ip/alert_handler/doc/index.html#design-details). Hence, without any other latching mechanism at the processor side, the NMI will eventually be deasserted automatically if the processor does not respond within the time window of Phase 0. 

Do we think that this is acceptable from a programming-model standpoint? Note that the escalation timer contains a 32bit counter, hence if properly configured it should be possible to give the processor ample time to respond. 

Other than that here shouldn't be a need for another NMI latching / cause register between the`prim_esc_receiver` and the NMI input of Ibex, since there are currently no other NMI sources. I.e., it is clear that if an NMI is triggered, the action to perform by SW is to examine the alert handler CSRs in order to figure out what went wrong.

**Comment by tjaychen** [comment]
I feel like encoding a large timer alone should be enough. Am I correct in saying that the escalation phase would remain asserted until software goes into the alert_handler to do something to de-assert it? 

Because if that's the case, I feel like maybe it makes sense to decrease the counter and just have an "indefinite" option, basically requiring the software to `ack`.

Am I understanding this correctly?

**Comment by cdgori** [comment]
So, #2988 looks fine.

I have three questions/comments here though:

1) if we need fast (or fastest) escalation, Ibex will almost certainly miss this transient, if I understand correctly?  At the moment we are depending on the single-NMI to not require a cause register, but maybe put a note somewhere in the code that if another NMI source is added then a cause register might be needed?

2) We don't need to latch the NMI because by definition it will trigger a jump to the handler, right?  (Software/Ibex will "know" that it's handling an NMI that was triggered previously, just not exactly how long ago, yes?)

3) Tim's comment sort of resonates for me that "indefinite" (or "asserted until cleared") would be a reasonable course of action, just to have positive confirmation of the origin (and closing the loop on clearing behavior).

**Comment by msfschaffner** [comment]
Thanks for the comments! 

Replying separately here, first to @tjaychen:

So at the moment, the escalation counters by design never wait for a software ack in order to protect against cases where the processor might be wedged. I.e., we guarantee that the escalation timers eventually proceed to phase 1 / 2 / 3 in order to trigger higher severity countermeasures, and the escalation signals are asserted accordingly:

![image](https://user-images.githubusercontent.com/41358501/88595248-77be3200-d017-11ea-9ee9-1b4eac72cba4.png)

If we want to keep that property, one way we could achieve the "indefinite" option is to latch the escalation signals on the alert handler side and keep them asserted until either the escalation protocol is aborted (by CPU intervention), or the escalation protocol concludes, thereby triggering a full-chip reset.

Such a change would be relatively simple on the design side - but we should keep in mind that the DV impact might be significant due to FPV of the submodules, and due to several weird corner cases in escalation signalling (CC @cindychip).

RE @cdgori:

1. Indeed. In case of a "fast-track" alert, it would even be possible to entirely skip phase 0 by configuring the alert handler to trigger higher severity countermeasures right away in phase 0 (phase to escalation signal mapping is freely configurable). 

2. That is my understanding, yes. So even a short assertion of the NMI should have the processor jump to its NMI handler immediately, and given that there is only one NMI source at the moment, the cause registers in the alert handler should be sufficient. (But it is certainly good to add the note on number of NMI sources to the code, as you suggested).

3. Yes, I tend to agree with that point also (modulo the DV effort). See comment above on how this could be added in a relatively straightforward manner.

**Comment by msfschaffner** [comment]
Update: @tjaychen and I just had a discussion offline (well still online, but not on this thread ;)).

We can probably leave the alert handler escalation mechanism as it is currently implemented, but should emphasize in the programmers manual that it is really important that 1) the NMI pulse is long enough for Ibex to register it, and 2) the last escalation phase is made really long, in order to make it difficult to suppress the escalation pulse via glitches. 

I.e., in a typical configuration, an escalation protocol for, say alert class A, will first go through Phase 0 in order to trigger an NMI. Since the NMI is not masked, even a relatively short NMI pulse should have the processor jump to the NMI handler immediately. Hence, if the processor is not wedged, it should respond quickly. The action to be taken is to check the AH CSRs, and abort escalation (if justified). Also, the cause can be uniquely identified, since there are currently no other NMIs in the system (hence no additional cause register is needed).

If the processor does not respond within the time window of Phase 0, escalation will run away and eventually trigger a system reset in Phase 3. It just needs to be highlighted in the programming manual that this last phase should be made really long 
 - ideally by setting the counter to the maximum of 2^32-1, corresponding to roughly 42s at 100MHz. If the reset controller is not able to trigger a system reset within 42s, we probably have other problems...

@imphil or @GregAC, just to confirm: do you think it is ok to keep the NMI essentially a pulsed signal, and if so, what would be the minimum recommended amount of cycles that this signal needs to be asserted for?

**Comment by GregAC** [comment]
There is a subtlety around interrupt response we're currently looking at it (see https://github.com/lowRISC/ibex/pull/1034 and https://github.com/riscv/riscv-isa-manual/issues/544). The core issue is how you handle an interrupt that appears when there is an outstanding memory request. We need to know the response to the request so we know if we should jump to the exception handler if there's a bus error. However if we take the interrupt before we see that response there's no easy way to neatly resume and take a precise exception if the outstanding access saw a bus error whilst we began taking the interrupt.

I was currently tending towards effectively ignoring interrupts whilst you were waiting for a memory request response and only taking them after you'd dealt with the response. This means that an NMI pulse could get missed depending upon the maximum time expected for a memory request response.

One way to avoid this issue is to switch to async interrupts on bus error, though note even in this case if there's an outstanding request that's awaiting response sitting in the WB stage whilst Ibex will instantly jump to the interrupt handling state on seeing the NMI nothing will actually execute until the WB stage clears out when the response returns.

The short answer is minimum recommend amount of cycles for a pulse on NMI to get noticed depends upon the maximum expected response time on the data bus.

Yet another option would be to allow the NMI to throw the ongoing access away and ignore the response. This makes resuming trickier (mepc could point to the load or store you were in the middle of executing but you'd end up repeating it which you may or may not care about depending on whether it was targeted at a peripheral or normal memory or point to the instruction after it in which case if it did cause a bus error you wouldn't know and jump into code that was presuming it had completed successfully).

**Comment by vogelpi** [comment]
If it wasn't for the the issue around interrupts/NMI during loads/stores @GregAC described, we could just say the pulse width needs to be the greater than the longest instruction in Ibex i.e. 37 cycles for the divide. However the issue with loads/stores is a real problem and I am not sure there will be a quick and easy solution to that.

Related to this: A long time ago, we were discussing to add transaction monitors in front of peripherals to produce a graceful timeout e.g. when the accessed peripheral is clock gated or in reset #93. Is this still something we consider?

**Comment by rswarbrick** [comment]
Maybe this is impossible because of the RISC-V spec, but couldn't we just latch the signal and treat this as an edge-triggered "not-quite-interrupt"?

**Comment by msfschaffner** [comment]
Thanks for the detailed responses! 

@vogelpi and I had a chat about this topic today, and we still think that we can leave the current implementation and https://github.com/lowRISC/opentitan/pull/2988 as-is, despite the subtleties detailed by @GregAC. The reasoning is the following: The first phase in which the NMI is asserted is the last chance for the processor to react to an escalation scenario. If the processor does not respond within that phase, the assumption (from the point of view of the alert handler) is that the processor has been compromised. Upon expiration of that phase, the escalation timer will proceed to higher severity phases under any circumstances, in which case the secrets will be wiped and the chip will be reset. 

Hence, it does not matter much whether the NMI is latched (either at the alert handler or the processor side), since escalation will proceed and kill the chip anyways if the processor cannot respond to an NMI (for whatever reason). We should just make sure that the programming guide explains that the NMI phase shall be made long enough to give the processor ample time to respond (this is similar to setting a proper timeout for a watchdog timer). This part is somewhat dependent on the final implementation of NMIs in Ibex and the system configuration, and the guidance may have to be updated once the implementation has been finalized.

(As a side note, we should be aware that NMIs triggered via escalation are rare and can be seen as a last resort before triggering drastic countermeasures. There are additional filtering and interrupt mechanisms in the alert handler that can send out regular IRQs before triggering escalation. E.g., the alert handler can be configured to send out a regular IRQ upon each alert, and delay escalation until a certain amount of alerts has been registered.)

Does that seem reasonable to everyone?

**Comment by cdgori** [comment]
I think that is OK for me given our framework.

(I have a nagging feeling that there are some classes of escalation where the time intervals cannot be as long as having multiple levels of IRQ + counting of detected alerts + escalation delays though.  I think we're OK as long as we understand that it's possible that a analog-sensor-detected glitch or shield-sensor compromise, say, results in a near-immediate reset of the device.  I'm also coming from a mentality where a CPU was not involved in the handling of alerts, they were directly responded to by hardware modules, which is a bit different than OT, so perhaps my expectations need to adjust as well.  Also, there are some obvious concerns about doing this kind of rapid non-CPU-intervened reset for any sensor that requires calibration or potentially might generate false-positive events.)

**Comment by msfschaffner** [comment]
Good point @cdgori. 

I should say that there is a way to configure the escalation timers to bypass NMI and pull more drastic countermeasures right away. I.e., we have four such escalation timers (one for each alert class A - D). You can choose to bin all highly critical alerts into, say, class D, and the corresponding timer can be configured to drive the highest severity countermeasure in phase 0 right away, if that is needed (without going through IRQ 
 + accumulation + NMI delays first).

**Comment by msfschaffner** [comment]
Thanks for everybody who participated in this discussion!

You can access the slides from today's silicon meeting that summarize this issue under [this link](https://docs.google.com/presentation/d/13vCmzbY6hw8rksu2ejhiHl5pCfCnh50JiHv5Xl5TZo8).

I have merged in https://github.com/lowRISC/opentitan/issues/2990 since it is in line with the current thinking.

Closing this issue down (we can reopen if it turns out that further modifications are needed).
