### ISSUE TITLE
Question - avoiding CDC issues when configuring SPI device?

### ISSUE THREAD

**Issue by nmoroze** [lowRISC/opentitan#3025]
Hi,

I noticed that the OpenTitan's SPI peripheral requires that software only change certain configuration registers when the SPI interface is idle, due to the lack of synchronization for these registers into the SPI clock domain. 

I'm curious what the intended way for software to meet this requirement is? I noticed the `abort` register being used in a software example in this repo, but it seems to me like that only aborts I/O on the TX side at this point. Is that planned to be changed in the future?

The other possibility I thought of is that software could monitor the CSB input since it's exposed as a register, but then this could be susceptible to something like a time-of-check to time-of-use error. 

Thanks!

**Comment by sjgitty** [comment]
Hi @nmoroze thanks for the question. The short answer is that software has to manage this in coordination with the host on the outside, and/or expect potential corruption if there are configuration changes during flight. Since the host is external and in control, there is no real guarantee that you've reached a quiescent period (your TOCTOU comment).

On the hardware side, the longer answer involves CDC investigations that haven't been completed yet, so there will be more detail as those are completed. We will attempt to guarantee no hardware corruption via synchronization as best as we can, but as you probably know, with the SPI clock coming from the outside world, there isn't a lot we can do to control that clock source. The constraints here are a bit gnarly. The best takeaway for this question is that we'll try and document these details better as we complete the design.

@eunchan @tjaychen @mcy for visibility.

**Comment by tjaychen** [comment]
i think this is something wroth exploring in the future.
@a-will also pointed out some concerns, especially for things like reset where it may be difficult for software to gauge something is idle. 

We might need to continue this idea of registering software intent, and propagating it through hardware at the right moment. 
For now, we should probably mark this as future release.

**Comment by andreaskurth** [comment]
Triaged for `spi_device`. Assigning to M2.5 with https://github.com/lowRISC/opentitan/labels/Priority%3AP2 because we should confirm that we have met all requirements regarding idleness and (re-)configuration for this release.  If so, we can defer this to https://github.com/lowRISC/opentitan/labels/Type%3AFutureRelease.

**Comment by andreaskurth** [comment]
We will address this issue by adding an enable bit to prevent partial configuration (#14665). That enable bit will get CDC-synced to the SPI clock domain. Software will be able to disable SPI, configure it, and then re-enable it. I'm thus closing this issue.
