### ISSUE TITLE
[DV/FPV] Compile errors in the autogenerated CSR assert module

### ISSUE THREAD

**Issue by sriyerg** [lowRISC/opentitan#3035]
The autogenerated CSR assertion module done using reggen has compile errors for the following modules - flash_ctrl, spi_device, alert_handler, keymgr and usbdev. 

@cindychip

**Comment by cindychip** [comment]
New update: Current unsupported IPs:
1. alert_handler and entropy_src - the regwen is W1C instead of W0C.
Issue #1922 has recorded this descrepency. Once the alert_handler regwen
is unified to W0C, should be able to enable the check.

2. flash_ctrl - the enable registers have RO property, this is not supported currently.
FPV csr assert will need to solve this.

**Comment by cindychip** [comment]
PR https://github.com/lowRISC/opentitan/pull/3583 is merged, close this issue.
