### ISSUE TITLE
Decide on minimum supported RHEL version

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#313]
We have contributors working on RHEL6, first released in 2010. It is very likely that many of our scripts use functionality which isn't available there. 

Reported issues with RHEL6:
- ~`realpath` is not available~ (removed from our scripts since initial report)
- Support for Hugo: https://github.com/lowRISC/opentitan/issues/914

If we decide to support RHEL6, we need to add testing for this configuration to avoid regularly breaking their workflow.

@rasmus-madsen: Just to confirm, there's no plan to move to a more recent version of RHEL (or any other distribution) any time soon (RHEL6 is EOL 2020).

**Comment by rswarbrick** [comment]
As I understand it, WD are now on RHEL 7 and it's been more than 2 years since we last ran into this. I think it's probably best to close this issue until it next bites us. We already have some "no guarantees about RedHat" text in our install instructions, so this is only going to be a problem if partners need it to work.
