### ISSUE TITLE
[dv: tl ul] Host agent is not comforming to spec on request

### ISSUE THREAD

**Issue by rasmus-madsen** [lowRISC/opentitan#3208]
According to the TL UL specification 1.8.0 on p24
Wen ever the host wants to make a request is must also be able to receive a response in the same cycle.

> For example, a designer might be tempted to implement a master interface which holds d ready
LOW while a valid is HIGH in order to delay a concurrent response message until the following
cycle. However, this represents an indefinite delay on Channel D that is not allowed by any of the
forward progress ready rules. Indeed, a TL-UL–conforming slave interface may have connected
d valid and d ready to a valid and a ready respectively. Thus, the non-conforming master
interface has introduced a deadlock.

![image](https://user-images.githubusercontent.com/53917183/90800763-61a14a00-e315-11ea-8fa5-9175f00053d2.png)

our host is clearly not respecting this.

![image](https://user-images.githubusercontent.com/53917183/90801070-bc3aa600-e315-11ea-89dd-ffcfba827d3b.png)

**Comment by sriyerg** [comment]
Thanks for bringing this up. Wr will try to have this addressed soon.

**Comment by weicaiyang** [comment]
In current driver, a_valid and d_ready can be high in the same cycle. In your waveform, d_ready is high randomly which doesn't depend on a_valid. I found an example from uart waveform.
<img width="866" alt="Screen Shot 2020-08-20 at 10 26 34 AM" src="https://user-images.githubusercontent.com/49293026/90805067-faad7200-e2cf-11ea-88be-07dd2a4c1d29.png">

d_ready only relies on delay setting `cfg.d_ready_delay_min, cfg.d_ready_delay_max`
```
      d_ready_delay = $urandom_range(cfg.d_ready_delay_min, cfg.d_ready_delay_max);
      // break delay loop if reset asserted to release blocking
      `DV_SPINWAIT_EXIT(repeat (d_ready_delay) @(cfg.vif.host_cb);,
                        wait(reset_asserted & (pending_a_req.size() != 0));)

      cfg.vif.host_cb.h2d_int.d_ready <= 1'b1;
```

if you use run option `-ro +zero_delays=1`, d_ready is always high. 
<img width="981" alt="Screen Shot 2020-08-20 at 10 28 08 AM" src="https://user-images.githubusercontent.com/49293026/90805078-fe40f900-e2cf-11ea-9a3a-eaee18220895.png">

**Comment by rasmus-madsen** [comment]
Hi @weicaiyang  
thank you for your reply, I am aware of the zero_delay option. but what I am saying is the current behavior where d_ready is not always asserted with a_valid is not allowed by the specification.

**Comment by weicaiyang** [comment]
> Hi @weicaiyang
> thank you for your reply, I am aware of the zero_delay option. but what I am saying is the current behavior where d_ready is not always asserted with a_valid is not allowed by the specification.

Sorry, I missed your point. I thought address and data phase could be more independent, like AXI.
Let's check with designers if we implement TLUL host in this way. If yes, we should add assertion checker for it.
Thanks for catching this issue.

@eunchan @tjaychen 
From TL spec, when host drives a_valid = 1, d_ready should be high as well. I'm not sure if our design also follows this rule.
From xbar waveform below, I set d_ready always high in corei interface, but in design eflash interface d_ready is 0 when a_valid = 1
<img width="981" alt="Screen Shot 2020-08-20 at 11 22 26 AM" src="https://user-images.githubusercontent.com/49293026/90810239-84ad0900-e2d7-11ea-9007-2dd88fbb7bc0.png">

**Comment by tjaychen** [comment]
thanks for pointing this out!
I need to read this a little more because i'm not too clear on the snippet exactly what this means.

It's very very unlikely in our design we are ever going to have same cycle returns (because that would just loop a_valid immediately back). 

So is the spec saying that whenever the host issues a transaction it must always be ready to accept the return payload? Because that would be a super nice property and would allow us to get rid of downstream FIFOs that assume host can be 'not ready' and therefore we need to hold off the response.  If this is true however, I don't even see the point of `d_ready`... so i would definitely need to do some reading.

**Comment by rasmus-madsen** [comment]
@tjaychen yes you are correct it is clearly stated that the host cannot post a request without being ready to accept a response.
so the host should implement a FIFO if this is not the case. you should not need downstream FIFO's.

the d_ready as understand it is a flow control mechanism if the device does not respond immediately there is nothing to prevent the Host posting another request or a series of requests. 
this might result in burst response behavior and here the Host might need to throttle the device?.

**Comment by tjaychen** [comment]
ah i see (sorry i still havent' re-read the spec yet since my last response
:) ).

But i guess this implies the host just needs to be able to accept the
response from the "current" device it is issuing a transaction to, and it
does not necessarily need to buffer up all requests it has issued in the
past right?
So in theory.. let's say host issued commands  like this..
device A
device B
device C

but internally it only is able to receive 1 response at a time.

The host may then still throttle devices later because it may not be able
accept 3 transactions in a row.  So when a device responds, it could still
be back-pressured?
I really need to go read the spec ..

**Comment by weicaiyang** [comment]
It looks like host should keep d_ready high when it starts an item. And d_ready can only drop when bus is idle. This makes me think d_ready should be always high after reset and this signal is kind of useless.

If host supports outstanding transactions and can't process a transaction in 1 cycle, fifo will be needed.
Assume host issues 3 items. It should keep d_ready high until receive 3 responses. And it could receive 3 responses in a row
```
If a master interface cannot deal with receiving a response message on the same cycle as its
request message, then it can instead put a buffer after its Channel D input. The buffer absorbs a
concurrent Channel D response message and presents d ready HIGH until it has been filled. This
response handling logic satisfies the forward progress rules while allowing the slave to respond as
quickly as possible. All agents must follow the rules: Either proactively deal with the possibility of
a concurrent response, or place a buffer on the receiving input port to absorb it.
```

**Comment by rswarbrick** [comment]
@rasmus-madsen:
> the DV should always follow spec - i.e it should test that we do not fail if we attach to a compliant host!

I don't think that we're exporting pieces of the chip's IP, so this might be a bit academic. Note that our host implementation can fail when attached to a compliant device: that's the whole point of this conversation. So I agree that our peripherals should be spec-compliant. The question is whether we care that our core isn't.

**Comment by asb** [comment]
> > @rswarbrick we could suggest to the SiFive that they give concrete examples on this to clarify in future versions
> 
> Does anyone (@asb @domrizz0 @imphil) know an active SiFive Github participant that could weigh in on our back-and-forth here, and that we could request more clarify from?

@hcook - might you be able to help clarify our reading of the current TileLink specification? I don't think there's a dedicated repo for these discussions right now but let me know if I missed it. Many thanks in advance.

**Comment by weicaiyang** [comment]
> if we decide not to be compliant with the specification. I think this should only apply to the design itself.
> the DV should always follow spec - i.e it should test that we do not fail if we attach to a compliant host!

if our design isn't compliant to spec for this feature. I think our DV agent should have 2 modes
1. default mode, compliant to the spec. when a_valid = 1, d_ready must be 1.
2. non compliant mode, when a_valid = 1, d_ready can be 0/1, so that we can verify our device which can handle `a_valid=1 and d_ready=0` correctly. In OT tests, we should enable this mode.

**Comment by tjaychen** [comment]
following up to @weicaiyang / @eunchan 's point, we are also thinking about maybe for opentitan devices explicitly disallowing the type of devices that would cause issues.. (ie the return same cycle and connected a_valid / d_valid / a_ready / d_ready)

at least we're having a hard time seeing how this might be beneficial to this class of chip.  Would be great to hear what you think.

**Comment by tomroberts-lowrisc** [comment]
@tjaychen that would get my vote - looks like a timing nightmare in any system
I'd also support @weicaiyang's suggestion, since it makes the DV more exportable, which is valuable even if the design isn't 100% spec compliant.

**Comment by rasmus-madsen** [comment]
The master should never violate the spec IMO also i dont see the need for a dual mode in the master.
Also i think the slave driver can have a simple constraint knob called allow_same_cycle_response. So no need for a dual mode..

We can say we don't support samecycle response but that mean we just have a TL UL like interface and not actually a TL UL interface.  Since we violate the rules of foreward progress/deadlock avoidance.

I am currently away on vacation with only my cell so my responses will be delayed
________________________________

**Comment by weicaiyang** [comment]
> The master should never violate the spec IMO also i dont see the need for a dual mode in the master. Also i think the slave driver can have a simple constraint knob called allow_same_cycle_response. So no need for a dual mode.. We can say we don't support samecycle response but that mean we just have a TL UL like interface and not actually a TL UL interface. Since we violate the rules of foreward progress/deadlock avoidance.

@rasmus-madsen 
it's the host which violates the rule. Our host design may drive `a_valid = 1 and d_ready = 0`. I'm thinking to add a knob called allow_d_ready_low_when_a_valid_high for the host driver. Then, we can verify the DUT (TLUL device) if it handles `a_valid = 1 and d_ready = 0 `correctly.

**Comment by rasmus-madsen** [comment]
@weicaiyang 
I am sorry but I must be missing a point somewhere.
Why do you want to have a non-compliant host VIP?
I don't see how having the DV being able to support the full spec can hurt us. 
The only place I can see we can get hurt is, if the DV device respond in one cycle!

So we can put in the DUT spec that out RTL host does not support same cycle response - but the DV should support it.

is there any reason for not making the DV spec compliant - with the addition of having a knob that disables same cycle responses in our device (VIP) ?

@sriyerg @rswarbrick can you guys add your thoughts?

**Comment by tjaychen** [comment]
@rasmus-madsen i think the point Weicai is trying to make is... if we don't require our hosts to behave exactly as spec (ie, d_ready=1 when a_valid=1), then our host driver also needs to emulate that behavior to make sure our system doesn't break. 

I think realistically though, our host (singular, ibex) probably does behave according to spec.  Right now ibex i believe goes through a tlul host adapter and then a FIFO.  Since our fabric / protocol doesn't support burst, I'm fairly certain (not 100% sure) d_ready will always be high when a_valid goes out.

**Comment by tomroberts-lowrisc** [comment]
I think that's correct that d_ready will be high when a_valid is high.
But, if a device did respond with d_valid on the same cycle as a_valid, the Ibex core would ignore it and (probably) deadlock. We might be able to support that using the adapter FIFO, but I think the plan is to remove the FIFOs for ASIC, since they kill performance somewhat.

**Comment by weicaiyang** [comment]
@tjaychen 
> Since our fabric / protocol doesn't support burst, I'm fairly certain (not 100% sure) d_ready will always be high when a_valid goes out

I tied the ibex d_ready to 1 to test xbar in the waveform below, but when the transaction passes through the xbar, d_ready=0 at the cycle a_valid=1. So, our xbar isn't compliant with this rule.
<img width="981" alt="Screen Shot 2020-08-20 at 11 22 26 AM" src="https://user-images.githubusercontent.com/49293026/90810239-84ad0900-e2d7-11ea-9007-2dd88fbb7bc0.png">

**Comment by weicaiyang** [comment]
> I think that's correct that d_ready will be high when a_valid is high.
> But, if a device did respond with d_valid on the same cycle as a_valid, the Ibex core would ignore it and (probably) deadlock. We might be able to support that using the adapter FIFO, but I think the plan is to remove the FIFOs for ASIC, since they kill performance somewhat.

From our DV side, I think we can assume OpenTitan devices never drive same cycle response. Perhaps add assertion `(a_valid & d_valid == 1) && a_source == d_source` never happens.

**Comment by tjaychen** [comment]
> @tjaychen
> 
> > Since our fabric / protocol doesn't support burst, I'm fairly certain (not 100% sure) d_ready will always be high when a_valid goes out
> 
> I tied the ibex d_ready to 1 to test xbar in the waveform below, but when the transaction passes through the xbar, d_ready=0 at the cycle a_valid=1. So, our xbar isn't compliant with this rule.
> <img alt="Screen Shot 2020-08-20 at 11 22 26 AM" width="981" src="https://user-images.githubusercontent.com/49293026/90810239-84ad0900-e2d7-11ea-9007-2dd88fbb7bc0.png">

@weicaiyang 
do you happen to waves sitting around i can look at? I thought the fabric was either using a FIFO or bypassed..if it's the latter, I think that would mean it's actually originating from the host...

I'll run a sim and take a look too.

**Comment by tjaychen** [comment]
i took a quick look at this... the '0' is because the `socket_m1` module is waiting for d_valid and its payload to figure out which host it needs to route back to..it then picks the `d_ready` of that host.

This is not technically 'violating' the spec IMO, because the it's really just a bunch of muxing, and the fabric is waiting to pick.

**Comment by rasmus-madsen** [comment]
Many threads here to keep track of.

My prior comments were based on an understanding of a fabric where there is one how (CPU) and x slaves.
I realize now that we do in fact have internal hosts. 

lucky for me @rswarbrick was able to decipher my messages and formulate what I was really trying to say.
> I don't think that we're exporting pieces of the chip's IP, so this might be a bit academic. Note that our host implementation can fail when attached to a compliant device: that's the whole point of this conversation. So I agree that our peripherals should be spec-compliant. The question is whether we care that our core isn't.

I don't think we care if our internal bus is spec compliant as long as we agree on the protocol.

so with that in mind, I agree with the suggestion from @weicaiyang that we should also make our DV host support both modes.
the mode should IMO be selected by random since our devices should be able to handle d_ready high with a_valid.
but we should verify our devices do not break when this is not the case.

**Comment by tjaychen** [comment]
just a note, @weicaiyang and I were experimenting late last week and at the moment our fabric is not able to support a device that returns in the same cycle. 

The fix for this is easy (and we tried it out), but as @tomroberts-lowrisc mentioned, it creates kind of a unnecessary timing burden, especially for our project.

I could put in a parameter for it, but since it's not something our DV will likely stress, I don't really much of a point.  It sounds like others in this thread also agree.  Is that right?

**Comment by sjgitty** [comment]
> just a note, @weicaiyang and I were experimenting late last week and at the moment our fabric is not able to support a device that returns in the same cycle.
> 
> The fix for this is easy (and we tried it out), but as @tomroberts-lowrisc mentioned, it creates kind of a unnecessary timing burden, especially for our project.
> 
> I could put in a parameter for it, but since it's not something our DV will likely stress, I don't really much of a point. It sounds like others in this thread also agree. Is that right?

I tend to agree. It would be ideal to be 100% spec compliant. We've advertised already that we're not currently, but under much more benign conditions (extra bits for useful transmission purposes). This is a more clear violation. That said, we've got real stuff to get made, and we've evaluated the pros and cons. But I do think we're not finished yet, I'd like to see this conversation at our next Silicon meeting to make sure we're in agreement with the right final decision. If the decision is as you suggest, we should at least a) advertise the discrepancy in our TLUL documentation; b) provide a hint to a solution for others that might want to provide compliance; c) (optional / ideal) put pressure on the TLUL "community" to reconsider this position. Perhaps they'll have some point that we haven't considered yet.

So let's finalize the discussion next Tuesday 2020-09-08 (I've put it on the agenda), then document this in our online collateral so that others that are using our IP are aware of the situation. Perhaps we'll find someone with enough interest to provide a parameter for the feature, at least in our bus elements.

WDYT?

**Comment by tjaychen** [comment]
that sounds good to me Scott.

**Comment by mateenfaisal** [comment]
@rasmus-madsen , @weicaiyang - it seems we have addressed this issue through this https://github.com/lowRISC/opentitan/pull/3331.  

What is the remaining work (doc, design, verif) here? If none, shall we close this issue?

**Comment by rasmus-madsen** [comment]
@mateenfaisal I agree I think we can close this.
@weicaiyang if you agree can you please close this?

**Comment by weicaiyang** [comment]
close via #3331
