### ISSUE TITLE
[OTBN] Get performance numbers for RSA 3k encode

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#3248]
We do have an implementation of RSA 2k for the old implementation, which we used to get execution time numbers from. We now need to get execution time numbers for RSA 3k encode for the current ISA.

@felixmiller What do you think is the easiest way to get those numbers? Extend the RSA 2k algorithm from the other implementation and let is run on the old simulator, or port it all over to the modified ISA? 

> estimate 2

**Comment by felixmiller** [comment]
**Re ISA:** I would suggest to do anything w.r.t. to performance from now on on the OTBN ISA only. Although performance numbers should be pretty much similar from an algorithmic standpoint, we could miss non-algorithmic aspects otherwise. E.g. saving pointers for subroutine calls is a bit more expensive in otbn and if this happens within nested loops we might miss things we have to tweak.
We already have the full lib available (`modexp.S`) for OTBN to run full RSA with the new ISA. It should (I have to confirm) be capable of handling 3K RSA as well. In general, we have yet to confirm our 2k predictions for the OTBN (relates to #2635).

**Re Simulator:** The "old" simulator can also run the new (otbn) ISA. However, in the long term, I would suggest that we have some cycle counting capability also in the "new" simulator. Maybe it is already there, i haven't played with it so far. It is just that the "old" simulator is very experimental and will probably be retired at some point. For getting those numbers either way would work. However, if the new one has already some statistic features and already supports the full new ISA, I would suggest that we don't bother with the old one. If not, and we need this numbers fast, I can work with the old one for now.

**Comment by rswarbrick** [comment]
> I would suggest that we have some cycle counting capability also in the "new" simulator. Maybe it is already there, i haven't played with it so far

I agree that we will need more than we've currently got, but there's a slightly hacky way to get cycle counts already: run the standalone simulator with `--verbose` and push the trace through `wc -l` :-D. Obviously, this is an instruction count, not a cycle count, but it might already be good enough. I'm not sure whether we know the cycle timings for the different instructions (branches etc.) yet?

**Comment by imphil** [comment]
> I'm not sure whether we know the cycle timings for the different instructions (branches etc.) yet?

Yes, we do. 

I'll port over the performance evaluation framework I had in the old simulator as part of thew work on loop and call stack evaluation. (At least the relevant parts, it was rather specialized in the end.)


On RSA 3k: @felixmiller if you can provide a code snippet for RSA 3k that would be fantastic, I can then take over.

**Comment by felixmiller** [comment]
Ah, I missed the word "encode" in the subject. So this is only about verification, right? This is definitely supported up to 4k already. Actually from assembly perspective everything is contained in `modexp.S` already. I can come up with a python script for the old simulator for 3k verification. From there, the calling convention and data preparation should be visible then

**Comment by felixmiller** [comment]
Turns out this is all you need to add a test for RSA 3072 in the "old" simulator:
https://github.com/felixmiller/ot-dsim/commit/2c3dbf13c70fde1802a33ff9bd5ebe094dca5697

I also pushed some statistics here:
https://github.com/felixmiller/ot-dsim/tree/new-isa/stats

The results for the otbn instructions don't yield the full detailed statistics that you added for the dcrypto instructions, only cycle/instruction count and the instruction histogram.

For RSA 3072 encrypt/verify we currently land at 1023011 instruction/cycles, so ~10 ms.

**Comment by felixmiller** [comment]
> estimate 0 2020-10-19

Performance is now 972496 cycles for RSA 3072 verify/encrypt. So ~10 ms @ 100MHz

Didn't upload the trace file, since very large. Let me know if you need it.

```
wc trace_enc_3072.txt 
   972496  10873518 109401794 trace_enc_3072.txt

```

**Comment by imphil** [comment]
@moidx FYI ^

Note:
* These numbers are OTBN only, they don't include the initialization of OTBN from Ibex (e.g. transfer or IMEM/DMEM, setting of pointers, etc.).
* The implementation is not hardened, but also not optimized.

**Comment by imphil** [comment]
Thanks a lot @felixmiller! Let's consider this issue resolved for now.
