### ISSUE TITLE
[OTBN] Specify BN.WSRRS and BN.WSRRW behavior

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#3338]
The BN.WSRRS and BN.WSRRW instructions are currently (under/non-)specified, which leads to effectively implementation-defined behavior in the two simulators.

Do we want these instructions to follow the RISC-V behavior, and are we OK doing so without having a `x0` zero register available on the wide side?

FYI, that's the implementation in the old simulator right now, and the behavior assumed in the modexp.S source code.

```
class IBnWsrrs(GInsWsr):
    """Atomic Read and Set Bits in WSR"""

    MNEM = 'BN.WSRRS'

    def execute(self, m):
        wsr_val = m.get_wsr(self.wsr)
        m.set_reg(self.wrd, wsr_val)
        wsr_new = wsr_val | m.get_reg(self.wrs)
        m.set_wsr(self.wsr, wsr_new)
        trace_str = self.get_asm_str()[1]
        return trace_str, None


class IBnWsrrw(GInsWsr):
    """Atomic Read/Write WSR"""

    MNEM = 'BN.WSRRW'

    def execute(self, m):
        wsr_val = m.get_wsr(self.wsr)
        m.set_reg(self.wrd, wsr_val)
        wsr_new = m.get_gpr(self.wrs)
        m.set_wsr(self.wsr, wsr_new)
        trace_str = self.get_asm_str()[1]
        return trace_str, None
```

This implementation leads to `bn.wsrrw     w4, 2, w4`, as found in the modexp.S code, to be executed as (assume WSR 2 is RND for this discussion, see https://github.com/lowRISC/opentitan/issues/3337)

```
w4 = <random value>
RAND_WSR = value of gpr 4
```

Especially setting the WSR to a value of a GPR is surprising, and I don't think the code in modexp.S actually relies on it.

Furthermore, BN.WSRRW should be used for writing a WSR, not reading it. (In fact, ~reading~ writing the RND WSR isn't supported.)

@felixmiller

**Comment by felixmiller** [comment]
- The `get_gpr(self.wrs)` is a bug, I guess a copy paste error from the `CSRRW` instruction. Since it is a random number this does not impact the computed result. In fact, in the old simulator there is no LFSR implemented and a constant value is always (supposed to be) returned by reading RND. This bug maybe introduces some "randomness" now but still does not impact functionality.
- We don't need RISC-V behavior here. I think a simple `WSRW` and `WSRR` would serve all our use cases as well. I don't think that we ever need to set/clear individual bits of a WSR, nor do we need an atomic swap. But I can understand that there is a desire to keep this consistent with the CSR world where, afaik, there is no `CSRW`/`CSRR` either.
- In fact there is a usually an all-zero WDR available. Just one that you zeroize in one of the very first instructions and keep it. I think there is no need to make it hard wired to 0, like `x0`, but this would be a separate discussion. It is mostly `w31` in our code (I know `w0` would be the better choice but the dcrypto folks started this. It makes sense from the perspective that there are often other constants which are then stored in the other registers close to the end of the reg file)
- However, the code was (mostly) automatically converted, therefore you don't have the knowledge available at conversion time to know for sure that there is a zero register (and which one it is). Therefore I used the `WSRRW` in the conversion script instruction to replace dcrypto`s `strnd` construct
- What do you mean by "In fact, reading the RND WSR isn't supported."? In general? or do you mean _writing_ to it is not supported? How would you draw a 256 bit random number then? Or is it only not supported through the `WSRRW` instruction and you should use `WSRRS` instead?
- I also realize another thing when looking at this code which is also an artefact from the automatic conversion: Random numbers are only used for two things in this file (1) initializing regs with a random value (2) doing a random branch. For (2) only a single bit is evaluated and the dcrypto sequence was: 1. draw random number, 2. do some dummy operation to set flags based on this number. 3. branch on the value of the L flag. This got converted to OTBN in the same sequence just that step 2 is replaced by three instructions: read the CSR with the mapped flag, isolate the l flag with `ANDI`, branch on the result. We can have this much simpler by just reading the random value from the CSR and branch of any of it's bits. By this, most of the `WSRRW`s would disappear anyways. We still need them (or something similar) when we need to init regs.

**Comment by imphil** [comment]
> What do you mean by "In fact, reading the RND WSR isn't supported."? 

I meant writing, sorry. I edited the original text.

**Comment by felixmiller** [comment]
edited the related question

**Comment by imphil** [comment]
Thanks for your comments @felixmiller. I agree with them, let's see how we can make progress on this.

* I agree that full-word reads and writes from the WSRs are the only important feature now.
* Still, for consistency, it would be nice to keep the wide and narrow access to special purpose registers the same, even though we don't need all the features of CSRRS/CSRRW and BN.WSRRS/BN.WSRRW (at the moment).
* In RISC-V, there are pseudo-instructions for simple reads and writes using these instructions.
  * A simple CSR read is `CSRRS rd, csr, x0` (short: `CSRR rd, csr`)
  * A simple write to a CSR is `CSRRW x0, csr, rs1` (short: `CSRW csr, rs1`)
  * To make the short forms available as pseudo-op, we need a dedicated zero-register. 

This leaves us with a couple of next TODOs:

1. To unblock us while we have this discussion: Let's implement and use CSRRS/CSRRW and BN.WSRRS/BN.WSRRW as described in the RISC-V spec. This is how the current spec was meant to be, without explicitly saying so, and will need updates to the simulators, and updates to the modexp.S code.

   @felixmiller the new simulator should already behave that way, could you do a PR to change the modexp.S code and adjust the old simulator?

2. We should discuss if we want/can introduce a dedicated zero register. With a zero-register, we can define read/write pseudo-ops `BN.WSRW <wsr>, <wrs>` (to write the value in the source register `<wrs>` into the WSR `<wsr>`) and `BN.WSRR <wrd>, <wsr>` (to read the WSR `<wsr>` into WDR `<wrd>`). I've opened https://github.com/lowRISC/opentitan/issues/3350 to look into that.

**Comment by felixmiller** [comment]
Here is a PR: #3355
Old simulator is also fixed

What about just defining the pseudo instructions `WSRR` and `WSRW` and let them use `w0` as zero reg?
Plus have a note on this in the spec + add a note in some yet to come programming guide that it is encouraged to use `x0` constantly as zero reg (if we decide in #3350 not to hard wire it). If we hard wire it, we are also fine.

**Comment by GregAC** [comment]
To keep things consistent could we say we only support plain read/write and any use of `CSRRS`/`CSRRW` that doesn't use the zero register to turn them into plain read/write is an illegal instruction?
