### ISSUE TITLE
[otbn] Designate a wide zero-register

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#3350]
In the narrow general-puprose register file in OTBN, we have a register which always reads zero, and ignores writes: the x0 register.
There's no such thing in the wide data register (WDR) file.

**Use cases for a wide zero-register**

* Use in algorithms which require a wide data operation with zero.
* Easier zero-ing of wide registers (with BN.MOV or BN.MOVR from the zero-register)
* Easier initialization of wide registers with a small constant (using e.g. `BN.ADDI <wrd>, w0`).
* Easier/standardized implementation of BN.WSRRS and BN.WSRRW when used only for reading/writing a full-width data word. For example, the operation to read a wide special-purpose register is `BN.WSRRS <wd>, <wsr>, w0` (assuming w0 is the zero register). To make this code easier to write, a pseudo-operation "WSR read" `WSRR <wd>, <wsr>` could be provided.

**Discussion.** 
If we designate a zero-register, we loose one wide general-purpose register. If algorithms need it (meaning, they use all 32 WDRs for values other than zero) that's a significant downside. So the main question is: how many algorithms need all 32 registers for values other than zero?

@felixmiller wrote in https://github.com/lowRISC/opentitan/issues/3338:
> In fact there is a usually an all-zero WDR available. Just one that you zeroize in one of the very first instructions and keep it. I think there is no need to make it hard wired to 0, like x0, but this would be a separate discussion. It is mostly w31 in our code (I know w0 would be the better choice but the other implementation folks started this. It makes sense from the perspective that there are often other constants which are then stored in the other registers close to the end of the reg file)", 
 
To better understand the trade-offs, here are two questions:
* @felixmiller: In the algorithms with register pressure that you've seen, is there always a register which is initialized to zero and never touched again?

* @tomroberts-lowrisc In Ibex, IIRC you used the x0 register in the random instruction insertion security feature. If we would want to do something similar for the big number instruction subset in OTBN, would having a wide zero-register help?

CC @moidx and @cdgori

**Comment by rswarbrick** [comment]
Other than the WSR instructions, are there any other instructions where a register that ignores writes makes any difference? If not, I'd propose adding variant WSR instructions if necessary and keeping a "software-defined" wide zero register.

**Comment by felixmiller** [comment]
Let's put it that way, in all the code I've seen there was such a register available. However, I've also seen that the register is re-initialized and my guess is that it is clobbered in some subroutines. I can check this and come back with more information.

I have some security concerns though, with a hard-wired WDR. One of the main use cases for the SW defined zero reg is that it is used in `SEL` operations to avoid data dependent branching. E.g. depending on some flag, either a constant or zero is selected and then the result is added to some other value in the next instruction. I am concerned that a hard wired reg would induce leakage here, when the reg file is not accessed in the usual way. @cdgori probably best to comment on this. You could of course use some other reg then for this or you could just "simulate" the hard-wired reg (actually store the zeros in mem but make it non-modifiable)

**Comment by felixmiller** [comment]
Just checked again and at least in `modexp.s` there is always `w31` as an all-zero reg available. It is initialized at multiple places (since you can jump in the code at multiple positions) but write access is always only through `bn.xor w31, w31, w31`.
We could easily swap `w31` and `w0`, if we want to have it more consistent with the 32 bit world.

**Comment by GregAC** [comment]
I think we're better off allowing software to reserve a register for 0 if it wants it rather than hard-wiring and altering the WSR instructions they're just plain read/write.

**Comment by cdgori** [comment]
> I think we're better off allowing software to reserve a register for 0 if it wants it rather than hard-wiring and altering the WSR instructions so they're just plain read/write.

Seems sensible to me, I do agree with @felixmiller 's comment above about potential leakage when accessing a hardwired zero-reg vs a "normal" regfile reg set to zero by convention, though we'd have to study the context(s) quite carefully to see if it would be an actual issue.  I can also imagine some theoretical problems where what we assume to be a zero is glitched/contaminated to something other than zero and then all hell breaks loose in the math.  Which of those two is potentially worse seems pretty hard to say though.

**Comment by rswarbrick** [comment]
> I can also imagine some theoretical problems where what we assume to be a zero is glitched/contaminated to something other than zero and then all hell breaks loose in the math.

Hmm, that's a really good point. If we can find the encoding space, I'm convinced it would be a good idea to add (non-pseudo) `BN.WSRW` and `BN.WSRR` instructions. Then we either keep the `BN.WSRRW` and `BN.WSRRS` instructions or not. But that can probably wait until this milestone is done. I'll open a (low priority) issue to track it.

**Comment by felixmiller** [comment]
I fully agree that it makes sense to add these instructions as non-pseudo. However, for me the reasoning here is more that it removes unnecessary complexity by removing unused features (which otherwise of course could contribute to the attack surface). Also given the fact that these instruction exist in the CSR context (even though as pseudo instructions) it would not be too weird to have them as non-pseudo in the WSR context.

The security concerns I have w.r.t. leakage and a hard wired zero register, I see more with other usage (mainly selects) than with `BN.WSRRS` and `BN.WSRRW` where I would not be concerned even with a hard-wired all-zero WDR. Here, we would always only use this zero-reg, so you could not distinguish different occurrences of these instructions based on the power profile (at least not based on the usage of the zero reg)

to @cdgori's point: I see this not so much critical w.r.t. to algorithmic usage (although as Chris points out we would have to study this carefully) I see it a bit more critical w.r.t. to the nature of the `BN.WSRRS` instruction and the interpretation of the source reg as a bitmap. In contrast to glitches at other places, a single glitch here would be sufficient to set a `WSR` to a specific value (and not only flip a single bit)

**Comment by imphil** [comment]
Looks like this proposal doesn't work well, so let's keep the current spec and not implement a w0 hard-wired zero register.

**Comment by cdgori** [comment]
Just re-iterating the concern of being mindful of the potential effects of glitches on a soft-provisioned (as opposed to hard-wired) zero-reg (mostly as captured by @felixmiller above, but really anywhere the soft zero-reg is used).
