### ISSUE TITLE
[mask rom] Handling errors in mask ROM modules

### ISSUE THREAD

**Issue by alphan** [lowRISC/opentitan#3385]
Creating this issue to start a conversation on how we should handle errors, e.g. return codes from DIF libraries or signature verification failures, in mask ROM code and to capture the alternatives that we (@lenary, @mcy, and I) have considered so far:

- **Take immediate action**: Mask ROM modules do something drastic, such as shutting the chip down, as soon as they encounter an error by calling a function like `noreturn void shutdown_with_reason(severity_t);`
  - This means that there will be `N` places that can trigger a shutdown. These will not be controlled by the boot policy module and not every error justifies a shutdown.
- **Use fine-grained return codes**: Mask ROM modules return fine-grained return codes, analogous to `BadArg, Error, etc.` used by DIF libraries.
  - The boot policy module is responsible for handling errors. Fine-grained return codes _may_ be useful. E.g., since we don't expect to see `BadArg`, we can interpret it as an attack. This implies that we will have code that translates different return codes which goes against our goal to keep mask ROM code simple.
- **Return success/failure**: Only the success/failure information is propagated to `boot()` where the boot policy module determines what needs to be done, e.g. trying the next ROM EXT, retry boot, shutdown, etc.
  - The boot policy module is responsible for handling errors and return codes are simpler than the second option.

Looking forward to your comments.

**Comment by mcy** [comment]
Some additional thoughts:
- @lenary suggested that maybe it might be acceptable for functions directly called by `boot()` can call `shutdown()`. I'm not sure I think this is much better than it being reserved for `boot()`.
- Given that we (seem to) expect all of our DIF actuations to never fail, if we go with fine-grained error codes, I think an opaque `kDifError` is ideal.
- Another option is to specify a global result enum, which is slightly more fine-grained than a bool:
```
enum {
  kOk,
  kFailure,
  kSecurityCritical,  // Distinguished so that `boot()` can unconditionally
                      // raise alerts when something catastrophic happens.
  // etc.
}
```
- @alphan mentions that having N places that can trigger a shutdown is bad because this is beyond the purview of the boot policy module, but it's also a problem because it complicates testing. ~~Regardless of what we choose, the shutdown function will need to be mocked out and expectations run on it. The deeper in the callstack shutdowns can happen, the more pervasive these expectations will become. I personally don't think it's a huge issue~~ This actually turns out to be a rather large issue, since mocking a `noreturn` function is... non-trivial, if not impossible. I suspect there's something clever we can do with `EXPECT_DEATH` or continuations, but thinking about it I suspect that this isn't the kind of function we can just mock...

Unfortunately, one thing that is unavoidable in all scenarios is checking DIF return codes. We will either need some amount of control flow to map DIF return codes to whatever return code style we settle on, or just ignore them and assert that such errors are impossible outside of the bootstrap module. Both of these options suck.

I think a lot of this is will be very dependent on whatever the secure code guidelines wind up looking like. I'm personally a little nervous about propagating an error up the stack instead of taking immediate action, but that's difficult to quantify at this point.

**Comment by lenary** [comment]
It sounds like we need to punt on this until the secure coding guidelines are ready - what I would say is that if for the moment we can only ever call `shutdown` from the main boot function, that would be a lot easier for testing.

Something that isn't entirely clear from this is that `shutdown` is part of the Boot Policy module, as we may need to do specific things in shutdown depending on the boot policy (or, more to the point, some errors may just result in attempting to boot the backup image, rather than a full shutdown). The aim is still to only update the boot policy's flash area on a successful boot, but that doesn't mean to say the shutdown sequence isn't different depending on the policy, reset reason, etc.

**Comment by tjaychen** [comment]
can i throw one more thing onto the pile?
In addition to the normal events, on security chips there will also be countermeasures and their related alert aggregation.

In order to avoid unexpected surprises (false positive sensor causing the device to not boot), we may want to ask ROM to look at the countermeasure output instead of directly triggering a hardware response.  This might also play into how you want to handle errors.

**Comment by silvestrst** [comment]
@alphan thank you for creating this issue.

For my better understanding what were your thoughts regarding the:
> Take immediate action: Mask ROM modules do something drastic, such as shutting the chip down, as soon as they encounter an error by calling a function like noreturn void shutdown_with_reason(severity_t)

Is the idea here is to minimise the time system is running in an erroneous state? Are there any other benefits that you see?

**Comment by silvestrst** [comment]
@mcy 
> Unfortunately, one thing that is unavoidable in all scenarios is checking DIF return codes. We will either need some amount of control flow to map DIF return codes to whatever return code style we settle on, or just ignore them and assert that such errors are impossible outside of the bootstrap module. Both of these options suck.

I am not sure I see DIF return codes mapping into Mask ROM error codes as an issue. Presumably we could define common error codes for all Mask ROM modules, and let the individual modules decide how to interpret the DIF errors, etc...

**Comment by alphan** [comment]
> Is the idea here is to minimise the time system is running in an erroneous state? Are there any other benefits that you see?

In a nutshell, yes. I _think_ there may be cases that need to be handled more gracefully, e.g. signature failures due to tooling issues or bad images, etc., but we should aim to limit any leakages, i.e. power consumption & EM not just I/O, as much as possible.
