### ISSUE TITLE
[sw, mask_rom/rom_ext] On-device testing strategy

### ISSUE THREAD

**Issue by silvestrst** [lowRISC/opentitan#3451]
# THIS ISSUE HAS BEEN CREATED TO START THE MASK ROM AND ROM_EXT ON-DEVICE TESTING

Previously we did not have boot_rom tests (if I am not mistaken, please correct me if I am wrong). Now when we are working on the Mask ROM and ROM_EXT, I think it is a good idea to decide how should:

- Mask ROM and ROM_EXT on-device tests be built.

- The directory layout (under `sw/device/tests/<mask_rom/rom_ext>` or some other something different)?

## On-device test cases types

- Do we need on-device sanity/unit tests?

- Are we intending to use existing test framework that we use for DIF unit/sanity tests?

- ...

### Unit/Sanity tests

There are several "unit test" type of tests variants on-device test cases that I can think of:

- Mask ROM only

- ROM_EXT only

- Mask ROM + ROM_EXT
  For example, we could load both Mask ROM and ROM_EXT into the verilator, parse the ROM_EXT image on the Mask ROM side to see whether the ROM_EXT manifest has is valid (testing Mask ROM ROM_EXT parser and the ROM_EXT manifest).

### Integration tests
???

## Quick proof-of-concept PRs that I have made to roughly sketch how "unit tests" could look like

**NOTE: these PRs essentially are just "conversation starters" **

Only implemented a rough proof-of-concept build of Mask ROM test image for both:
Similar to our existing `riscv_crt`, I have split out the Mask ROM/ROM_EXT CRT and linker into a separate library #3449
Similar as above, but without splitting the CRT + linker into a separate library #3450
Both PRs build successfully.

**Comment by mcy** [comment]
I think the main thing we need to think about is "what do we want to test"? In particular, when running tests on-device, it's much harder to build test assertions to check that we have brought the hardware into a state we want.

For something like Keys & Signatures, this is probably easy, because we're just checking that OTBN is behaving like the RSA oracle we expect it to, but for something like System State, do we want to check that the keymgr outputs the expected value for the CreatorRootKey?

I think a very important exercise is to go through all of the Mask ROM modules and sketch potential test plans (esp. around how we define and check expectations). Given that a lot of the relevant hardware and DIFs aren't going to exist for a while, I almost feel like this might be worth punting until midway through Milestone 4.

**Comment by silvestrst** [comment]
Please do add other people if you think it is relevant to them, and also feel free to remove yourself from assignees if you think this is not applicable to you.

**Comment by alphan** [comment]
Thanks for starting this conversation @silvestrst! I see two things here: (1) What will these tests look like and how will we run them? (2) What will these tests actually test?

It looks like you approached this from (1) but I also agree with @mcy's comments regarding (2) and would like offer some thoughts: I think of these tests as integration tests that test the interaction between mask rom (modules) and the hardware. While we have a great deal of flexibility in on-host tests (for mocking hw and sw dependencies), for on-device tests, I expect our approach and the extent of tests will be shaped by what the hw can actually do. Since this will vary from module to module and will take more time to settle, we may want to start with sanity tests that test happy paths (to make some progress now) and consider additional tests on a module-by-module basis (to increase test coverage). WDYT?

**Comment by silvestrst** [comment]
Closing, can be revisited when wider work on testing starts. The consensus was that we don't need smoke tests for Mask ROM, as the major benefit of that is to quickly check that the peripherals work - which is already done in the `boot_rom`.
