### ISSUE TITLE
[otbn] Register representation in python for otbnsim

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#3560]
Python integers are infinite width and signed, bignum registers are a fixed 256-bit width and are not particularly signed or unsigned (though there's no bignum instructions that operate specifically on signed numbers in particular all multiplies assume unsigned integers).

We need a uniform way to map bignum registers on to Python integers.

I would suggest we write things in such a way that integers representing registers are always positive and in the range 0 - (2^256 - 1). Assertions should be used to check all registers match these requirements an appropriate point (e.g. when they are used by an instruction).

Similar consideration needs to be applied for the base registers.

**Comment by rswarbrick** [comment]
We can do as you suggest, but that means re-writing Stefan's `Register` class. (No biggie, and I think it would remove the last dependency on his simulator).

Alternatively, we keep with what currently exists, where the `Register` class internally stores a signed number (the 2's complement intepretation of the 256 bits stored in the register) and you call `my_register.unsigned()` to get the unsigned interpretation. Since I don't really see any benefit of changing this, I'd do that.

**Comment by rswarbrick** [comment]
I'm convinced about the "unsigned everywhere" approach, but think it's better to hide the representation and just provide "read_signed" or "write_unsigned" accessors, so it's super explicit. I'm hacking on code to do this now: how hard can it be? :-)
