### ISSUE TITLE
[otbn] x1 when used as pointer

### ISSUE THREAD

**Issue by felixmiller** [lowRISC/opentitan#3608]
What should be the behavior if someone uses `x1` to dereference registers or dmem addresses?

e.g.

`bn.lid x2, 0(x1)` or `bn.lid x2, 0(x1++)`

This would mean that we pop from the call stack, or even pop first and push an incremented value.
Especially the latter could be a security issue, since someone could modify the call stack if they manage to glitch the reg field in one of the instructions using indirect addressing.

I think from a toolchain perspective this can already be handled on the assembly level and issue a warning or error. Nevertheless, we probably need to raise an alert in the RTL.

**Comment by felixmiller** [comment]
@imphil @rswarbrick @GregAC

**Comment by rswarbrick** [comment]
As I understand it, the fate magic call stack is still slightly in question :-) Maybe it would make sense to park this question until we've definitely decided we want one?

**Comment by rswarbrick** [comment]
I think the current spec and RTL is that this "just works" (although it's likely to make a mess of your call stack). The first example pops the top of the call stack. The second pops and pushes, so updates the top, incrementing it by 32.

I wonder if we need some form of hardening that disallows such things. I suspect that pretty much any CFI implementation will be much better protection, though, so I'm probably in favour of leaving them allowed. @imphil: Since you are currently our CFI wizard, do you have any opinion?

**Comment by GregAC** [comment]
It does indeed 'just work'. Adding an error on call stack accesses from certain instructions is easy enough though should that be desired.
