### ISSUE TITLE
[mask_rom] Zero all RAM

### ISSUE THREAD

**Issue by gkelly** [lowRISC/opentitan#3619]
We currently don't zero RAM because of the presence of the DV trigger for simulation termination. This needs to be resolved before shipping the Mask ROM image.

**Comment by tjaychen** [comment]
i just wanted to clarify, are we planning to 0 the ROM under all reset conditions? 
It'll be important to separate the reasons why we've reached ROM.  As an example we don't really want to 0 the retention RAM unless its the right reboot reason. 

I wrote this [doc](https://docs.google.com/document/d/14JMwu1YcJYeyR77Issx4ic25g0xXxjbMGUrMJJokCEs/edit?usp=sharing) some time ago, it would be good to see what you think.

**Comment by lenary** [comment]
This issue is specifically tracking an issue where we don't zero a particular area of the main ram (but zero the rest), because writes to that area have effects in the DV testbench and verilator. I would prefer if we don't turn this into an issue that tracks all Ram Zeroing questions in the Mask ROM.

Yes we're aware of that document, and yes we're tracking the resolution (or not yet) of some of the questions in it.

**Comment by tjaychen** [comment]
sounds good. Thanks Sam.
