### ISSUE TITLE
[rtl] best practices for RTL coding in light of security

### ISSUE THREAD

**Issue by sjgitty** [lowRISC/opentitan#367]
This issue is related to #366 

The request in this issue is to study the area of RTL coding in light of
security, namely come up with guidelines for the best ways to code
state machines and other logic that can appropriately react when entering
otherwise-unexpected states due to attack.

**Comment by cdgori** [comment]
Just putting some random thoughts here for later discussion/incorporation into guidelines, based on some discussion from this morning.  Please add other comments/thoughts here so we can properly write up guidelines going forward.

-In security logic, it's not OK to assume values/states are "not reachable" - explicit handling logic for what happens when those values are present/reached will need to be added to the code/design.  DV will then need to figure out how to cover/hit something that is unreachable (typically this is done by simulated glitch injection).

-Conversely, it is difficult to determine what logic is "security logic" - so probably best to err on the side of marking more things security logic than not.  (As a small example, earlier today we discussed how Ibex could become "security logic" because of the type of code executing on the core.  Almost any primitive will also need to be treated this way if it can be used in security logic, as another trivial example.)

-Important to review what the actual default value/branch-to-take is for any invalid-case handling logic - sometimes it's better to map onto a functionally valid already-existing case, and sometimes it's better to create a new error case that handles this explicitly.  Hard to know which is better, we should discuss situationally as this comes up.  (Generating an error is interesting for an adversary to know that they triggered some error-handling path, but is nice for DV, bringup and diagnostics - mapping onto existing arcs/states gives a sort of silent failure which could be more frustrating for the attacker but just as annoying for the DV/bringup process.  We need to balance these two things out properly.)

-For buses/data covered by a valid/ready signal, the choice of the "invalid" address location is similarly "interesting" - if possible, prefer an address map that has a "parking" address location that is safe/safer to use.  (This comes up very frequently in NVM/flash address buses, but is potentially relevant for SRAMs/regfiles as well, if the SRAM/regfile contents are sensitive values like keys or decrypted data.)

**Comment by sjgitty** [comment]
> Just putting some random thoughts here for later discussion/incorporation into guidelines, based on some discussion from this morning. Please add other comments/thoughts here so we can properly write up guidelines going forward.
Thanks @cdgori 

> -In security logic, it's not OK to assume values/states are "not reachable" - explicit handling logic for what happens when those values are present/reached will need to be added to the code/design. DV will then need to figure out how to cover/hit something that is unreachable (typically this is done by simulated glitch injection).
There is more nuance here, no? Take the case of an `logic [1:0] enum` with three legal states `{mode0, mode1, mode2}`. Which do we want? One that defines it as just a legal case and asserts? One that highlights that it is "special"? Or further, one that detects the problem (but otherwise allows the code to be optimized)?

```systemverilog
// current proposal
`ASSERT(Case_A, sel inside { mode0, mode1, mode2}, clk_i, !rst_ni)
always_comb begin
  out0 = '0;
  out1 = '0;
  unique case (sel)
    mode1: out0 = foo;
    mode2: out1 = bar;
    default: ;
  endcase
end
```

```systemverilog
// special indication
`ASSERT(Case_A, sel inside { mode0, mode1, mode2}, clk_i, !rst_ni)
always_comb begin
  out0 = '0;
  out1 = '0;
  unique case (sel)
    mode0: ;
    mode1: out0 = foo;
    mode2: out1 = bar;
    default: begin
      out0 = '1;
      out1 = '1;
    end
  endcase
end
```

```systemverilog
// hardware response expected; code otherwise optimized; no assertion
always_comb begin
  out0 = '0;
  out1 = '0;
  detect_problem = 1'b0;
  unique case (sel)
    mode0: ;
    mode1: out0 = foo;
    mode2: out1 = bar;
    default: detect_problem = 1'b1;
  endcase
end
```


> -Conversely, it is difficult to determine what logic is "security logic" - so probably best to err on the side of marking more things security logic than not. (As a small example, earlier today we discussed how Ibex could become "security logic" because of the type of code executing on the core. Almost any primitive will also need to be treated this way if it can be used in security logic, as another trivial example.)
Agreed, though I imagine we could declare certain modules (in scope) for security scrutiny. eg UART or GPIO might be skipped from this sort of scrutiny and testing?

> -Important to review what the actual default value/branch-to-take is for any invalid-case handling logic - sometimes it's better to map onto a functionally valid already-existing case, and sometimes it's better to create a new error case that handles this explicitly. Hard to know which is better, we should discuss situationally as this comes up. (Generating an error is interesting for an adversary to know that they triggered some error-handling path, but is nice for DV, bringup and diagnostics - mapping onto existing arcs/states gives a sort of silent failure which could be more frustrating for the attacker but just as annoying for the DV/bringup process. We need to balance these two things out properly.)
Yeah, this gets to my code examples above. Maybe we can use those as conversation pieces for what is better when in order to provide guidance.

**Comment by cdgori** [comment]
Just providing a pointer to a comment I made on issue #113 (on handling of default in state machine encodings) since it has been closed.

**Comment by msfschaffner** [comment]
@cdgori is this something we could include in the security coding guidelines? or maybe it has already been included?

**Comment by msfschaffner** [comment]
CC @dsandrs

**Comment by tjaychen** [comment]
i believe we can consider this issue closed with the following already published.
https://docs.opentitan.org/doc/security/implementation_guidelines/hardware/

If anyone disagrees, please re-open the issue.
