### ISSUE TITLE
[bootstrap/spiflash] Rework hash checking and acknowledgment

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/opentitan#3682]
When stabilizing the SPI Flash tool for #3647, I noticed that most of the reliability issues we were seeing with SPI are actually not due to errors on the SPI transmission, but due to how the bootstrap code and the SPI flash tool interact together. In fact, disabling the feedback from the device to the host made the whole SPI flashing work directly. Also, in case of errors, the information the user is given is sometimes very counter intuitive.

Having had a closer look on the bootstrap code in `sw/device/boot_rom/bootstrap.c` I seriously think this should be reworked (actually just `bootstrap_flash()`). But maybe we do this for a good reason and I just don't understand get it. This is actually why I created this issue and didn't do a PR directly. 

Right now, the code loops and waits until at least a full frame has been received. The frame is then copied from the peripheral buffer in the SPI device into RAM, and we extract the frame number from this received data. All good so far.

But then, things get to start strange:
1. If the extracted frame number is not the expected one, we signal the previous `ack` buffer to the host. This `ack` buffer contains the computed hash of the **previous** frame. For Frame 0, it's just an empty buffer. IMO, we should send back an error message and not just a random hash here.

2. If the extracted number is the expected one, we check the hash by computing it over the received data and comparing it with the received hash. If they don't match, we send back to the host again the previous `ack` buffer i.e., the **previous** hash or the empty buffer. I guess it would be more useful to send back the wrong hash of the currently received frame.

3. If the computed hash and the received hash match, we generate again the hash, store it in the `ack` buffer and signal it back to the host. Meaning, we compute the hash twice.

4. After having correctly received a frame but before having got the next one, it seems we still have enough bytes received as we extract the frame number (always 0 in that case) and compare it again with the expected one. I didn't figure out how this can be possible but it's obviously the case looking at the UART output:
```
I00001 bootstrap.c:158] Bootstrap requested, initialising HW...
I00002 bootstrap.c:181] HW initialisation completed, waiting for SPI input...
I00003 bootstrap.c:101] Processing frame #0, expecting #0
I00004 bootstrap.c:127] Flash erase successful
I00005 bootstrap.c:101] Processing frame #0, expecting #1
I00006 bootstrap.c:101] Processing frame #1, expecting #1
I00007 bootstrap.c:101] Processing frame #0, expecting #2
I00008 bootstrap.c:101] Processing frame #2, expecting #2
I00009 bootstrap.c:101] Processing frame #0, expecting #3
I00010 bootstrap.c:101] Processing frame #3, expecting #3
I00011 bootstrap.c:101] Processing frame #0, expecting #4
I00012 bootstrap.c:101] Processing frame #4, expecting #4
I00013 bootstrap.c:101] Processing frame #0, expecting #5
I00014 bootstrap.c:101] Processing frame #5, expecting #5
I00015 bootstrap.c:101] Processing frame #0, expecting #6
I00016 bootstrap.c:101] Processing frame #6, expecting #6
I00017 bootstrap.c:101] Processing frame #0, expecting #7
I00018 bootstrap.c:101] Processing frame #7, expecting #7
I00019 bootstrap.c:101] Processing frame #0, expecting #8
I00020 bootstrap.c:101] Processing frame #8, expecting #8
I00021 bootstrap.c:101] Processing frame #0, expecting #9
I00022 bootstrap.c:101] Processing frame #9, expecting #9
I00023 bootstrap.c:101] Processing frame #0, expecting #10
I00024 bootstrap.c:101] Processing frame #10, expecting #10
I00025 bootstrap.c:101] Processing frame #0, expecting #11
I00026 bootstrap.c:101] Processing frame #11, expecting #11
I00027 bootstrap.c:101] Processing frame #0, expecting #12
I00028 bootstrap.c:101] Processing frame #12, expecting #12
I00029 bootstrap.c:139] Bootstrap: DONE!
I00030 boot_rom.c:42] Boot ROM initialisation has completed, jump into flash!
I00000 hello_world.c:49] Hello World!
I00001 hello_world.c:50] Built at: Oct  4 2020, 12:48:04
I00002 demos.c:18] Watch the LEDs!
I00003 hello_world.c:57] Try out the switches on the board
I00004 hello_world.c:58] or type anything into the console window.
I00005 hello_world.c:59] The LEDs show the ASCII code of the last character.
I00006 demos.c:56] FTDI control changed. Enable JTAG.
```
As you can see, after Frame 0, it seems as if every other frame received is Frame 0 again.

5. Depending on timing, i.e., how long it takes to receive the next full frame, we either signal back the acknowledgement to the host once or potentially multiple times. On the host side, we seem to ignore the first acknowledgment in any case.  

6. If we have received all frames, we return. Without signaling the acknowledgment of the last frame a second time. This is why on the host side, we don't check the correct reception of the last frame.

It would be good if someone could confirm this. Then we can rework the code or at least explain why things are like this and put proper comments.

**Comment by tjaychen** [comment]
@vogelpi, this constantly repeating frame 0 is a bit weird.
I feel like this is happening because the device at its reduced frequency is taking so long to process frames that the host goes ahead and repeats sending the frame (because it did not receive an ack from the last one).  Although I would not expect a bunch of 0's...but instead expect incrementing frames though...

I do agree it seems weird we are hashing twice, I don't really see an advantage in doing that.

@mcy 
@moidx

**Comment by tjaychen** [comment]
one thing to check, did you try changing `hash_read_delay_us` in ftdi_spi_interface.h to see if it helps with the strange repeating #0 frames problem?

my guess right now is that due to decreased clocks, everything is taking much longer. As part of that, the host issues a read to check the hash. Except spi is a full duplex interface, and even though they're issuing a read, the host is probably also depositing tons of '0's' into your queue. 

This makes me wonder if this happens in general though..

**Comment by moidx** [comment]
The bootstrap protocol is currently implemented in SPI in generic mode, where there is not handshake signal between the device and host. The `ack` value is used to synchronize the frames between the host and the device.

More details on the current protocol here: https://docs.google.com/document/d/1psaNZNn9IpG8ACcCAhIDtjaoX84hCeerFh6fZk2r1kQ/edit#heading=h.vq1mwktd0mj2

Originally, the protocol was supposed to behave as follows:

host transaction | host-device buffer | device-host buffer 
---- | ------------------ | --------------------
Tx and Rx     | `Frame(N)`            |  `ack(N-1)`

But, at some point the spiflash utility was refactored to wait for an `ack` for the current frame. This caused the first frame to be sent twice, but the overall behavior was equivalent to the one above:

host transaction | host-device buffer | device-host buffer 
---- | ------------------ | --------------------
Tx     | `Frame(N)`            |  Stored in `internal mpsse buffer`? need to check
Rx     |  Push `0s` if device-host is empty? |  `ack(N)`

Re 3. The `ack` hash covers the entire frame, whereas the `frame.hash` covers the frame number and the data. `ack` is a strong signal that bootstrap processed the previous frame, a CRC would have sufficed, but in practice HMAC is fast enough. Based on your comments, it seems that you are proposing to set `ack = frame.hash`.

Re 4. The fact that you are getting inconsistent frames implies that the host is running much faster compared to the device. The host ends up pushing additional data (`0s`) to try to read the current `ack`. 

Re 6. Yes. The device could send an `ack`  for the last frame before jumping to flash, but then I guess you'd have to continue playback of the `ack` until the host sends an `exit` frame? This can probably be done with minimal changes.

Please see lowrisc/opentitan#1513 for a discussion on an improved interface. Note however, that this is a tricky subject because we rely on bootstrap at manufacturing time (specially when running in `PROD` state where debug interfaces are not available, and where the tester only supports test vectors). This is currently under discussion and it is subject to change.

**Comment by vogelpi** [comment]
Thanks @tjaychen and @moidx for providing more details and clarifications! This makes a lot more sense to me now. I think we don't need to rework this right now. It should be sufficient to document the protocol a bit in the source code.

**Comment by moidx** [comment]
Closing as obsolete as we have now moved to a new bootstrap protocol
