### ISSUE TITLE
[padctrl] Default attributes for open-drain pads

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#3699]
We need to pay close attention to the default attributes of open-drain pads, especially how they relate to some of the modules that have reset / power on related behavior.

Specifically, the static pad state expected by these modules during full operation should also be true right after reset.  Meaning we need to be careful about their pull-up / pull-down states, open-drain function enable and probably input enable (rather, any attribute not directly controlled by the module themselves).

**Comment by msfschaffner** [comment]
@tjaychen do we want to review this together (i.e. go over the pinout). 
At the moment, all PU/PD and OD attributes default to "disabled".

**Comment by tjaychen** [comment]
ah yes indeed (@toshaq FYI), these are mostly related to the sysrst_ctrl default functions.

**Comment by msfschaffner** [comment]
ok this is going to be somewhat annoying to do due to the way the registers are defined in the pinmux.
i.e., we do not have a good way of defining non-zero defaults selectively for multiregs.
also, there is currently no mechanism that allows to override pad attributes from a comportable IP.

QQ: if both these signals need to be driven to 0, and SW needs to manually release them, is OD mode really required at startup (since it's just driving to 0)?

I mean, electrically speaking, the OD capability would only be required for the release, right? or are there other electrical side effects in the pad implementation that we should double check?

**Comment by tjaychen** [comment]
i think this is probably true as long as we don't ever drive '1' onto the pin.
@toshaq what do you think? any risk if we have these as normal push-pull until software configuration?

we will still drive 0 actively until that time.

**Comment by msfschaffner** [comment]
> i think this is probably true as long as we don't ever drive '1' onto the pin.
exactly. we would not have to make any design changes right now if we only need to drive '0' after reset...

**Comment by toshaq** [comment]
Yeah this looks OK to me. I think as long as we continue to drive it low and never drive it high we should be OK. Is the sink current capability in Push Pull configuration 8mA? Will there be any concern if someone is actively driving it high (like an intruder for example?)

**Comment by msfschaffner** [comment]
Ok, so based on this thread and the discussion we had via email, I think the conclusion was that this is ok as-is and does not require any more design changes. Right @tjaychen?

**Comment by tjaychen** [comment]
yep this sounds good to me.
