### ISSUE TITLE
[topgen, connect] Need help to connect a signal between to modules

### ISSUE THREAD

**Issue by rmbhagwat** [lowRISC/opentitan#3792]
I want to connect "usbdev_sense" signal to another internal peripheral module instantiated under "top_earlgrey".
But I'm unable to do so using "inter_signal_list".

Is there any **clear-cut documentation** about connecting inter-module signals?

Even I tried "inter_module" procedure inside "hw/top_earlgrey/data/top_earlgrey.hjson" but I was not successful.
Either it expects req-ack kind of relationship or expects dedicated/multiplexed IO if I simply define "usbdev_sense" input signal.

Why is the topgen and peripheral connections so complex? Please provide documentation with some examples.
Thank you.

**Comment by sjgitty** [comment]
@eunchan when you get a chance.

**Comment by eunchan** [comment]
Unfortunately, current version doesn't support the in/out port connecting to other instances. To do that, you need to explicitly define that port (sense) as a inter-module signal in usbdev.hjson 

The other way you can do is to create another port in USBDEV HWIP that connects the sense signal but define that port as inter-module signal. THen you can connect to other instances.

OpenTItan top-level explicitly distinguishes the actual input/output (from / to outside of the chip) and the inter-module signals. That's why this difficulty arouses.

**Comment by rmbhagwat** [comment]
Thank you @eunchan
