### ISSUE TITLE
[sw, mask_rom/ROM_EXT] TODOs and open questions

### ISSUE THREAD

**Issue by silvestrst** [lowRISC/opentitan#3875]
These are some of the questions that have materialised from #3836 , and I expect that this list will grow.

- [ ] `rom_ext_boot` signature (what information should be passed from Mask ROM to ROM_EXT)

- [ ] Mask ROM -> ROM_EXT handover. Which peripherals should be re-configured, and which should retain their configuration

- [ ] Is the way we are handling current "return" of "noreturn" function correct, or does it need to change?
```
...
  while (true) {
    wait_for_interrupt();
  }
}
```
- [ ] What Ibex registers should be cleared before the handover (if any)?

- [ ] When should the Ibex icache be enabled?

- [ ] Possibly dedup parts of the CRT code, see [comment](https://github.com/lowRISC/opentitan/pull/3836#discussion_r507798694).

**Please feel free to add other items directly to this issue!**

**Comment by silvestrst** [comment]
@alphan @lenary @gkelly @mcy @jon-flatley

**Comment by lenary** [comment]
In answer to some of these:
- A lot of handover stuff we do need to clarify and design, and haven't done so yet. This is a good place to collect issues around that.
- Handling noreturn functions is currently incorrect - we should power off the device rather than a WFI loop, but I'm not sure we know how to power down the device from software yet, so a wfi loop is fine today.

**Comment by moidx** [comment]
Marking this issue as obsolete. @alphan please reopen if you have any concerns.
