### ISSUE TITLE
[otbn] Improve co-simulation performance

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#4006]
The combined OTBN top-level RTL simulation with model running in step has fairly poor performance (around 3 kHz on my machine), it would be good if this can improved. For reference Ibex without tracing running in simple system can run at around 200 kHz on my machine. With the co-simulation model we may not be able to reach these speeds but we should look at what we can do to get some improvements.

**Comment by rswarbrick** [comment]
Block-level simulations are mostly done over VCS, where we use ~90% of cycles in VCS and only ~10% in the ISS. Maybe that's slightly inflating the VCS numbers (because of stalls waiting for context switches), but it suggests we won't get a massive speed-up in block-level sims whatever we do.

Chip-level simulations are barely affected by the OTBN / ISS stuff, it seems.

@GregAC: Do you think there's still benefit in digging into this? If not, maybe we should close it?

**Comment by GregAC** [comment]
Let's close it
