### ISSUE TITLE
ISR for GPIO interrupts

### ISSUE THREAD

**Issue by hadirkhan10** [lowRISC/opentitan#4034]
Hello, I have a confusion regarding thinking about an ISR for GPIO interrupts. If for e.g I configure GPIO pin 0's interrupt enable bit and enable `intr_ctrl_en_lvllow` for GPIO pin 0 (assuming initially the IO pads return 0000s for all pins) then how can the ISR handle the interrupt? Writing 1 to the `intr_state` register would clear the interrupt for that pin but since still the GPIO pin 0 would be 0 (we never wrote anything to it) the interrupt would again be latched in the `intr_state` register. So how would the ISR deal with it? Does it also change the GPIO out value for that pin (write 1 to it) so that the peripheral logic does not again latch the interrupt signal on to the `intr_state` register?

**Comment by hadirkhan10** [comment]
Because after performing abc... instructions the ISR would do an `mret`, this would cause the core to return back to the interrupted instruction, but since the peripheral logic would again latch the interrupt signal in the `intr_state` register the `external_irq` to the core would be high again and will again cause the ISR to be executed.

**Comment by hadirkhan10** [comment]
The flow works fine while raising interrupts with the `intr_test` register. The programmer can enable the interrupts by writing 1 for the corresponding GPIO pin in the `intr_test` register causing the `intr_state` bit for that pin to get high. This would enable the `external_irq` signal to the core and will cause the ISR to be called. Before doing an `mret`, the programmer can wirte 1 to the `intr_state` register to clear the interrupts and write 0 to the `intr_test` register for that pin causing the `external_irq` to the core to get low and successfully returning to the interrupted instruction without jumping again to the ISR.

**Comment by sajjadahmed677** [comment]
I think it depends on your program. because enabling and then handling a particular interrupt is totally based on your required application. so, if you are done with your task then you should disable interrupts for that pin. then, it doesn't matters what value is on that pin you are simply not getting interrupt again from that pin. for more details you can review PLIC documentation.

**Comment by rswarbrick** [comment]
Hi @hadirkhan10. Thanks for the question. I think the problem that you were seeing here is due to the fact that OpenTitan uses level-based interrupts. So you have to tell the peripheral (GPIO in this case) to drop its interrupt request before you return from the ISR.

The fact that this has been dormant for over a year suggests that you either figured that out or gave up(!) so I'm going to close this issue now. But if you're still trying to get something like this working, please feel free to open a follow-up and we'll try to respond a bit quicker this time.
