### ISSUE TITLE
[otbn] Make Python model discoverable for out-of-tree simulation runs

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#4097]
In CI, we use the Verilator simulation from a build artifact (distribution) directory which isn't inside the source tree. This breaks an assumption in OTBN's ISSModel class:

```
DEBUG    root:utils.py:362 Error when constructing ISS wrapper: Cannot find a git top-level directory containing /home/vsts/work/1/a/build-bin/hw/top_earlgrey/Vtop_earlgrey_verilator.
DEBUG    root:utils.py:362 
DEBUG    root:utils.py:362 Vtop_earlgrey_verilator: ../src/lowrisc_ip_otbn_0.1/dv/model/otbn_model.cc:518: unsigned int otbn_model_step(ISSWrapper*, const char*, unsigned int, const char*, unsigned int, const char*, svLogic, unsigned int, unsigned int): Assertion `model && imem_scope && dmem_scope && design_scope' failed.
```

The same problem will apply to anyone trying to use binary releases of OpenTitan.

Multiple solutions exist, such as packaging the simulator as proper Python package (see #3036) and ideally also including it in the distribution (which will then use $PATH for discovery), or implementing more logic into ISSModel to honor $REPO_TOP (which is set to the repository toplevel in CI runs through `util/build_consts.sh`, and continuing to use the ISS Python code directly from the source tree.

@rswarbrick 

> estimate 8

**Comment by rswarbrick** [comment]
Are there any paths that our generated binaries know how to find? (Like an "install prefix", which might point into the `build-bin` directory). If so, I propose we use such a path and add a symlink somewhere that we can resolve through it. I really don't like the idea of hacking on the user's environment (as we discussed before), so would much prefer something less fragile.

**Comment by rswarbrick** [comment]
I'm also ok with including otbnsim in the distribution, but would like the code to find it explicitly in that case, rather than relying on $PATH.

**Comment by sriyerg** [comment]
At Google, there is a limitation on how simulations are run (all files required to run a simulation are required to be copied over to a separate storage area on the network visible to the compute machines that invoke VCS / Xcelium). I presume the OTBN ISS, which needs to run inline with the simulation also needs to be a part of this data set (which I guess is what you mean by 'distribution'?). If `otbnsim` has other dependencies on things in-tree, then those would have to be moved too relative to it (not sure if there is, just making sure). Unfortunately, symlinks are not suitable either. With DVSim, we specify a `scratch_root` path which is where all build and run artifacts are created, so that becomes the anchor for finding things. Perhaps the same can be done for Verilator based sims as well? My apologies if I've misunderstood something.

**Comment by rswarbrick** [comment]
That makes sense. Looks like we'll have to do "proper distribution" for otbnsim.

Just out of interest, why don't you copy the entire OT tree onto the compute workers? It's only ~100MiB (if you skip `.git`), which is probably peanuts compared to the NFS traffic you'll get from running VCS / Xcelium.

**Comment by sriyerg** [comment]
> That makes sense. Looks like we'll have to do "proper distribution" for otbnsim.
> 
> Just out of interest, why don't you copy the entire OT tree onto the compute workers? It's only ~100MiB (if you skip `.git`), which is probably peanuts compared to the NFS traffic you'll get from running VCS / Xcelium.

Yes, that's true. I'd been hesitant to do that thus far (we'd be copying a whole bunch of things that are irrelevant to the simulation), but I guess that would be the most robust solution. I suppose the size is small enough even for people running sims on their laptops / local workstations that the copy (with update) operation does not make a huge dent on the run time.

**Comment by rswarbrick** [comment]
Oof, this is going to be difficult if we really don't want to execute from the source tree. At the moment, `otbnsim` has a dependency on the shared utility code in `hw/ip/otbn/util`, which is not a problem. But it also runs `reggen`. Do we really want to try to package all of this stuff up?
