### ISSUE TITLE
[aes] DUT stalls after data_out is cleared mid config

### ISSUE THREAD

**Issue by rasmus-madsen** [lowRISC/opentitan#4118]
@vogelpi I have enabled random clearing of the registers
in this test the data_out register is cleared in the middle of a configuration.
the dut is configured as
```
 ----| MESSAGE #           0 
 
	 ----| 		 AES MESSAGE ITEM   	      |----	 
	 ----| 
	 ----| Mode: 	  	 	 AES_CFB                         	 
	 ----| Operation:   	 	 AES_DEC                         	 
	 ----| has Configuration error:  FALSE  	  	        	 
	 ----| Mode error en:  	 0 
	 ----| Key_len error en: 	 0  	         	 
	 ----| Message Length:  	  	          23             	 
	 ----| Key Length:   	 	 001                             	 
	 ----| Key Share 0: 	 	 a503533f 52944a3d a5946300 27c3aa7e 6fc1b5e4 ff784285 e8ccf9c9 173df719 
	 ----| Key Share 1: 	 	 69420446 882991f5 f8a0cc9a 8cab4aff ab299bc4 b0201a3c a38d2bf2 7bcdd3be 
	 ----| Key Mask:  	  	 0                               |----	 
	 ----| Initializaion vector:     	    	 51235ab8 0e63fd78 55262ec9 4d3a2687 
	 ----| Manual Mode : 0      	   	 
```
the DUT configuration register is written first
and then the Key, IV and data is interleaved with a reset in the mix in the following order
```
 ----| Configuring the DUT in the following order:  
	 ----| 	 key_share0_1
	 ----| 	 key_share1_5
	 ----| 	 key_share1_0
	 ----| 	 key_share1_4
	 ----| 	 key_share1_2
	 ----| 	 iv_2
	 ----| 	 key_share1_7
	 ----| 	 key_share0_0
	 ----| 	 iv_3
	 ----| 	 key_share0_6
	 ----| 	 key_share0_5
	 ----| 	 key_share1_6
	 ----| 	 data_in_3
	 ----| 	 clear_reg    <<<<<<<<<<<<<< clear output reg here
	 ----| 	 iv_1
	 ----| 	 key_share1_3
	 ----| 	 key_share0_3
	 ----| 	 key_share0_7
	 ----| 	 data_in_1
	 ----| 	 key_share0_2
	 ----| 	 data_in_2
	 ----| 	 key_share0_4
	 ----| 	 key_share1_1
	 ----| 	 iv_0
	 ----| 	 data_in_0
```

the DUT never starts the operation.
is this expected behavior?
I would not expect clearing the output register would contaminate the configuration.
you can pull my code from my aes_clear_reg branch
and run seed `1950155261`
`./util/dvsim/dvsim.py aes_sim_cfg.hjson -i aes_clear -r 1 -t vcs --xprop-off -v=m -s=1950155261 -w -d=vpd`

**Comment by rasmus-madsen** [comment]
@vogelpi it seem to happen for any kinds of resets.
resetting data_in, key or iv  before complete will also stall the DUT until all 3 have been re-programmed.

**Comment by vogelpi** [comment]
Thanks @rasmus-madsen for reporting this issue. I will look into it but first need to re-install VCS...

Quick question: by "reset" you mean a synchronous clear triggered by writing to the trigger register, right?

Something to be aware about: if you initiate a clear, this might take more than one cycle during which the module should indicate being busy. During that time, writes to the key and IV registers are ignored. So the original case reported above could be expected behavior depending on the time between `clear_reg` and `iv_1`.

For the second case, i.e., where clearing `data_in`, `key` or `iv` will stall the DUT until all 3 have been re-programmed: This should not be the case, clearing any of them should not have implications on the others. Unless some writes following the clear are ignored because the DUT is busy, there could be a bug. I'll have to investigate.

**Comment by vogelpi** [comment]
Hey @rasmus-madsen ,
I couldn't reproduce the behavior with the seed/command you provided above. The DUT is configured for ECB decryption (instead of CFB) and the IV register is never written. There is also just one initial clear performed. Can you please verify that with this command and the commit `1a4cdf0c43f6297d3b150f9d53dde7d522e0387a` you can reproduce the behavior?

**Comment by rasmus-madsen** [comment]
so polling for IDLE seems to resolve this issue. I have one seed failing that I would like to resolve before closing this.

also we should really update the Documentation with the requirement to poll for Idle after any kind of register clearing

**Comment by vogelpi** [comment]
Thanks for the update Rasmus. Yes, I agree that we should document the need for polling idle when clearing registers. I will do a PR for this.

**Comment by rasmus-madsen** [comment]
@vogelpi 
If I configure the AES module for CTR (or any other mode using IV) and make it calculate the first block.
then clear the IV - wait for IDLE and re-program the same IV
then calculate another block.

I would expect output to be the same if the IV register is cleared or not as long as it is reprogrammed to the same IV
but the DUT gives a different output for the second block when I reset or even if just re-program the IV to the same value.

is this expected behavior?

**Comment by vogelpi** [comment]
Hey @rasmus-madsen ,
I am not sure I fully understand the procedure you've described. It's important to note two things about the IV:
1. The IV registers are updated by HW during operation.
2. Writing the IV registers while idle basically triggers a new message to start.

So if you say "re-program the same IV" after running the first block, the expected behavior is to return again the same output that you got from the first block (given that also the input is the same). I think this is what you expect, too.

Instead, if your experiment is to get the second block if
a) the IV is not cleared after the first block, and
b) the IV is cleared and then configured to the original IV
then the result of a) and b) is not expected to be the same. Because the IV registers are updated during operation. b) will start a new message. The output is only expected to be the same as with the first block if you also used the same input data. In contrast a) gives you the second block of the message - even if you provide the same input.

If you prefer, we can also have a quick chat to discuss this.

**Comment by rasmus-madsen** [comment]
@vogelpi ahh that makes total sense. 
for some reason I was convinced only the key was updated in the fly.

I will adjust the dv.

**Comment by rasmus-madsen** [comment]
Document was updated in #4186 to clarify the correct use of the dut in case of any trigger.
this resolved the issues reported in this issue
