### ISSUE TITLE
[otbn] Clearing of instruction/data memory state on reset

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#4133]
Do we want to clear/overwrite the data stored in OTBNs instruction and data memories on reset? If so, what should it be overwritten with? Random data? Zeros?

**Comment by cdgori** [comment]
I can't think of a reason to clear or secure-wipe the instruction memory, unless there is some particular failure mode where data could be erroneously stored in instruction memory by OBTN?  (I was sort of assuming this was not possible.)  

I can make arguments for either clear-to-zero or secure-wipe (with random) of the data memory and would be interested to hear the opinions of others.

**Comment by moidx** [comment]
I am not sure if clearing the instruction memory is required. What would be the threat model considerations? @felixmiller, is IMEM confidentiality within scope if we keep the crypto library closed?

For DMEM, we need to compare using scrambling key rotation versus secure wipe.  Due to the diffusion properties of the scrambling approach, do we end up with a similar leakage model in both options?

Calls that complete execution may wipe assets before return, I would like to hear thoughts from a programming model perspective. We have discussed in previous security wg meetings the need for DMEM clear with random data to handle interrupted operations (either rotating scrambling keys or implementing secure wipe). 

It terms of performance, we may lean towards a hardware based solution. Having this option will also allow us to connect clearing functionality as part of the escalation path in the alert handler (@msfschaffner).

**Comment by rswarbrick** [comment]
Good point about the scrambling key. I don't think we can blat memory as part of OTBN finishing, though: Ibex uses DMEM as a channel for getting the answer back! Maybe we need a "rotate memory key" command register that Ibex writes to once OTBN has finished?

For added security, OTBN software could write zeros to all but the stuff it intends to return, but it would be difficult to do that in hardware (because the HW doesn't know what to clear). The only way that I can think to do *that* is with some sort of "watermark" register: The OTBN software could write to a CSR saying e.g. how many words of DMEM should be kept, then OTBN would clear all memory above that word as part of the `ecall` exit. That seems reasonably complicated, though: I'm not convinced it's worth doing.

**Comment by moidx** [comment]
Hi @rswarbrick, the secure clear functionality is mainly considered for the following scenarios:

1. Before starting execution of a crypto routine. 
2. After a failure is detected or as a result of an alert handler escalation. 
3. After the host (Ibex) has read the results from a successful crypto routine, as part of a cleanup sequence. 

The use case you are describing is currently outside the scope of this feature given the current TCB definition, where the host is trusted to control the state of OTBN.

**Comment by rswarbrick** [comment]
@moidx Thanks for the response. I think maybe I'm not completely understanding you. As I understood this PR, it was about whether OTBN's hardware should have some sort of "erase memory" feature. For your examples (1) and (3), I don't think we need any particular hardware support: Ibex can write over the bus to clear the memory itself. (Although maybe there's an efficiency argument for doing it within the block?)

For (2), I'm not sure: do we need something that's not controlled by Ibex software? In which case, I guess OTBN would need to respond to being prodded by the alert handler.

Re-reading what you wrote in your [previous comment](https://github.com/lowRISC/opentitan/issues/4133#issuecomment-733982877), maybe my confusion is about what you mean by "*Calls that complete execution may wipe assets before return*". Does *return* mean completion of the OTBN code (i.e. getting to an ecall instruction) or do you mean something higher-level? (I assumed the former, but I'm not sure that I'm right).

**Comment by moidx** [comment]
> @moidx Thanks for the response. I think maybe I'm not completely understanding you. As I understood this PR, it was about whether OTBN's hardware should have some sort of "erase memory" feature. For your examples (1) and (3), I don't think we need any particular hardware support: Ibex can write over the bus to clear the memory itself. (Although maybe there's an efficiency argument for doing it within the block?)

@rswarbrick, you are correct, (1) and (3) could be implemented in software, but it may be preferred to do it in hardware as a performance optimization. My understanding is that this issue is to discuss the trade-offs for implementing clear memory for (1), (2) and (3) use cases.

> 
> For (2), I'm not sure: do we need something that's not controlled by Ibex software? In which case, I guess OTBN would need to respond to being prodded by the alert handler.
>

For (2), this is something that can be controlled by Ibex or directly by the alert handler escalation sequence, both options are available and under consideration. @msfschaffner can provide more details on the specifics of the alert handler. 
 
> Re-reading what you wrote in your [previous comment](https://github.com/lowRISC/opentitan/issues/4133#issuecomment-733982877), maybe my confusion is about what you mean by "_Calls that complete execution may wipe assets before return_". Does _return_ mean completion of the OTBN code (i.e. getting to an ecall instruction) or do you mean something higher-level? (I assumed the former, but I'm not sure that I'm right).

The terminology in my comment can get confusing. Both cases could apply:

*    An OTBN function may clear the asset (i.e. key) right after use and before returning. This is possible when output 
     parameters do not include the asset. 
*   The host code wrapping the OTBN call can implement a cleanup sequence after processing the OTBN return value. 

The main point of that comment is that we need a secure way to handle cleanup on interrupted operations (e.g. timeout, or other failures).

**Comment by felixmiller** [comment]
regarding the aspect of confidentiality of OTBN code (IMEM). Technically, if OTBN is only used for running code that is part of the crypto lib, the code is considered as "TSF data" and only has to be protected for integrity. If it supposed to run user code, this user code has to be protected for both confidentiality and integrity. Personally, I don't see the need to claim confidentiality for OTBN code.

**Comment by msfschaffner** [comment]
As @moidx has mentioned above, a cheap way to wipe the DMEM quickly would be to clear the scrambling key register. If we think that is a viable approach in terms of security (see note on diffusion at the end of this comment), we could use this mechanism for (1), (2) and (3) above:
- For "normal" operation during preparation and cleanup (1), (3), we could just expose a CSR to trigger a key renewal. SW could trigger that both before and after executing a crypto function on OTBN. I suggest to align the CSR structure with what we implemented for the `sram_ctrl` since essentially this is using the same scrambling mechanism underneath:
https://github.com/lowRISC/opentitan/blob/88ced0296b6eed080bafdaa0374dc9795da4c6d2/hw/ip/sram_ctrl/data/sram_ctrl.hjson#L56-L124
- For escalation via the alert subsystem, we could consider clearing the scrambling key register to a random netlist constant whenever the `lc_escalate_en` life cycle signal is asserted. alternatively, we could add an LFSR clearing mechanism to OTBN - but that will add more combo delay to critical paths and the clearing itself is going to take several cycles to complete. 

Note on diffusion:
It should be noted that the scrambling mechanism is a reduced round PRESENT cipher employed in CTR mode, hence the diffusion properties are not outstanding. I.e., CTR mode only XORs a key stream onto the data, which by definition does not diffuse the data at all. We slightly augmented this scheme by passing each individual byte through two layers of Sboxes and permutations, thereby achieving at least a limited amount of diffusion (we do that on a per-byte basis to make this scheme compatible with sub-word writes on the main SRAM). another noteworthy augmentation of the CTR mode is address scrambling, which transforms the address space non-linearly via two rounds of Sboxes/permutations and a nonce that gets renewed together with the key.

**Comment by imphil** [comment]
Instruction memory clearing/wiping will be covered by the security feature `OTBN.H.SEC_WIPE_IMEM`, which can be triggered separately from other wiping functionality (according to current plans). This gives SW developers to clear IMEM on demand cheaply/with hardware support.
