### ISSUE TITLE
Unable to with opentitan using GDB, OpenOCD and Olimex-Arm-USB-tiny-h JTAG.

### ISSUE THREAD

**Issue by zeeshanrafique23** [lowRISC/opentitan#4198]
I know there are two option to use JTAG to communication with SoC using OpenOCD. One is the using external JTAG and another one is using ft-2232 interface. --Please correct me if I am wrong.
Now I am using [lowrisc-earlgrey.cfg](https://github.com/lowRISC/opentitan/blob/bfaf88058776f23428b317aad90ae93b822d6747/util/openocd/target/lowrisc-earlgrey.cfg) as target file for OpenOCD and but I don't have the file for ft-2232 interface for [Arty-7 A35T](https://reference.digilentinc.com/reference/programmable-logic/arty/reference-manual), can any one please help to point to that file.

I am trying to follow the [SiFive Freedom E310 Arty FPGA Dev Kit Getting StartedGuide](https://sifive.cdn.prismic.io/sifive%2Fed96de35-065f-474c-a432-9f6a364af9c8_sifive-e310-arty-gettingstarted-v1.0.6.pdf) as reference.

**Comment by zeeshanrafique23** [comment]
Here is xdc file snippet where I am trying to mention signals in/out
`## Pmod Header JD
set_property -dict { PACKAGE_PIN D4    IOSTANDARD LVCMOS33 } [get_ports { jtag_tdo_o }]; 
set_property -dict { PACKAGE_PIN D3    IOSTANDARD LVCMOS33 } [get_ports { jtag_trst_ni }]; 
set_property -dict { PACKAGE_PIN F4    IOSTANDARD LVCMOS33 } [get_ports { jtag_tck_i }]; 
#set_property -dict { PACKAGE_PIN F3    IOSTANDARD LVCMOS33 } [get_ports {  jd[3] }]; 
set_property -dict { PACKAGE_PIN E2    IOSTANDARD LVCMOS33 } [get_ports { jtag_tdi_i }]; 
set_property -dict { PACKAGE_PIN D2    IOSTANDARD LVCMOS33 } [get_ports { jtag_tms_i }]; 
set_property -dict { PACKAGE_PIN H2    IOSTANDARD LVCMOS33 } [get_ports { rstn }]; 
#set_property -dict { PACKAGE_PIN G2    IOSTANDARD LVCMOS33 } [get_ports { jd[7] }]; 
`

**Comment by rswarbrick** [comment]
Hi @zeeshanrafique23. I'm really sorry that we didn't reply to this earlier. We don't officially support that FPGA, so you're slightly "on your own". Also, the top-level layout and tooling have changed a lot since November 2020. I'm going to close this issue because I don't think it's really describing the problems that you'll have if you try to do this today.

But I still doubt that porting to that FPGA board will work! So please open another issue with your recent attempts if you're still interested in getting this working.
