### ISSUE TITLE
SW uses toolchain in 2 places

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#4219]
I have set `TOOLCHAIN_PATH`
> echo $TOOLCHAIN_PATH
> /edascratch/ms_edatools/riscv-tools/riscv-gnu-toolchain/20200904-1

And then find meson uses the toolchain as I set in `$TOOLCHAIN_PATH`, but [toolchain.txt](https://github.com/lowRISC/opentitan/blob/master/toolchain.txt) is hard-coded to use the default one `/tools/riscv/`

So, I got this log from simulation. Can we change it to all use $TOOLCHAIN_PATH if it's set?

> Using meson toolchain file at **/edascratch/ms_edatools/riscv-tools/riscv-gnu-toolchain/20200904-1/meson-riscv32-unknown-elf-clang.txt**.
> \+ meson -Dot_version=opentitan-snapshot-20191101-1-3141-g9e163d8c -Dbin_dir=/edascratch/weicai-opentitan/ot/top_earlgrey.sim.vcs/master/sw/build-bin -Dtock_local=false -Dkeep_includes=false -Dcoverage=false --cross-file=/edascratch/ms_edatools/riscv-tools/riscv-gnu-toolchain/20200904-1/meson-riscv32-unknown-elf-clang.txt /edascratch/weicai-opentitan/ot/top_earlgrey.sim.vcs/master/sw/build-out
> Purging superfluous -I arguments from /edascratch/weicai-opentitan/ot/top_earlgrey.sim.vcs/master/sw/build-out.
> The Meson build system
> Version: 0.54.0
> Source dir: /usr/local/google/home/weicai/ot/uart
> Build dir: /edascratch/weicai-opentitan/ot/top_earlgrey.sim.vcs/master/sw/build-out
> Build type: cross build
> WARNING: Unknown options: "build.c_std, build.cpp_std"
> The value of new options can be set with:
> meson setup <builddir> --reconfigure -Dnew_option=new_value ...
> Project name: opentitan
> Project version: 0.1
> C compiler for the build machine: cc (gcc 10.2.0 "cc (Debian 10.2.0-9) 10.2.0")
> C linker for the build machine: cc ld.bfd 2.35.1
> C++ compiler for the build machine: c++ (gcc 10.2.0 "c++ (Debian 10.2.0-9) 10.2.0")
> C++ linker for the build machine: c++ ld.bfd 2.35.1
> C compiler for the host machine: **/tools/riscv/bin/riscv32-unknown-elf-clang** (clang 11.0.0 "lowRISC clang version 11.0.0 (https://github.com/llvm/llvm-project.git fa038e03504c7d0dfd438b1dfdd6da7081e75617)")

@sriyerg is working on fixing this.

**Comment by sriyerg** [comment]
I found the issue. What we were trying to do was to get it installed to a Google-wide common location (let's call this 'release area', which is what the `TOOLCHAIN_PATH` is eventually set to) which is controlled by Google IT. The `--target-dir` where we "install" it first is used only as 'staging'. This unfortunately does not work because the meson build system reads the build info files (which are pointing to the staging area rather than the release area). Option 1: add `--release-dir` switch to `get-toolchain.py` that enables this usecase. Option 2: Fuhgetaboutit.
