### ISSUE TITLE
[life cycle] Decide on strategy to handle life cycle related broadcasts across power domain boundaries

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#4244]
The life cycle controller may not always be in the always on domain (although we can discuss if it actually makes sense to keep it in the always on domain always). 

As a result of this, it means any consuming agent of life cycle that is in fact always on may need to have some way of knowing what the relevant values should be before power goes offline.  

So this issue is encompassing really two items

- Identify the always on modules that need to consume life cycle and whether there is a need for such modules to understand the life cycle information across power boundaries (there may not be).
- If the answer to the above bullet is yes, then we need to identity the correct strategy to ensure such a definition is consistent.

**Comment by tjaychen** [comment]
@arnonsha 
@zi-v 
It would be good to get some input on what domains you plan to put critical DFT logic and how you view its role here as well.

**Comment by zi-v** [comment]
We haven't yet concluded how exactly are we going to use the LC state variables, but regardless, I think it would be safer if we can assume that an 'all zero' is a legit value expressing lock state. If you feel uncomfortable by the reduced hamming distance between locked and ulocked imposed by the '0x0' -> '0xA' vs '0x5' ->'0xA' We can consider adding more bits to the LC variable.
The 'all zero' will be easier to pass through isolation logic.
I don't think we need the lifecycle to reflect an 'open' state while the chip is in 'always-on' (a.k.a deep-sleep) state.

**Comment by msfschaffner** [comment]
Ziv, to your point on making the off state all-zero and wider...
That is possible, and one of the reasons why we defined the ON / OFF values in the LC package such that they can easily be changed, if needed.

**Comment by arnonsha** [comment]
I think it would be safer to just put the part that drives the LC information to the consumers on AON (Assuming this is sequential logic).

**Comment by tjaychen** [comment]
@msfschaffner do you want to update the bug with our discussed solution and we can close it?

**Comment by msfschaffner** [comment]
Sure, here is a quick summary:

Since non-escalation signals are only tested for the `ON` state at the consumer side, it does not really matter whether the isolation value is `0x0` or `OFF` since both are considered to be inactive (and hence legit values to be used for isolation).

The only signal we really need to pay attention to in terms of isolation is the `lc_escalate_en` signal, since this is tested for `!= OFF` at the consumer side. Hence, only the `OFF` value is a legit isolation value for this signal. However, we only have a few escalation signals that cross power domains (1-2 for power manager and AON watchdog timer) and hence it should be manageable to manually set the isolation value to `OFF` for these. 

RE the DFT enable signals, I think we first have to see whether we really need these to remain asserted during deep-sleep. These signals are driven by the life cycle controller, which is currently not in the AON domain. Moving it to AON may not be straightforward due to the current life cycle model where we re-sense the OTP state on every boot. But depending on which DFT signals need to survive a deep-sleep cycle, we may be able to work around that since the TAP isolation logic is going to be located in the pinmux.

**Comment by tjaychen** [comment]
ah yes, i think we did not capture that point.
I believe the current thinking for DFT_EN is that it would fall into the non-escalation signal category.
Ie, there are always on modules that consume it, but don't need it during low power states.  So therefore it is okay as long as it isolates to some non-on value.

**Comment by msfschaffner** [comment]
@tjaychen @arnonsha @eunchan this is something we should audit again to make sure we use the correct isolation values.

**Comment by msfschaffner** [comment]
@tjaychen should we do this pre M2, or as part of the UPF review for M3?

**Comment by tjaychen** [comment]
hmmm....i feel like we should review this as part of M2.
I think the main thing that worries me is the statement we made about most things are looking for an "ON", i'm not sure how to prove that is the case.

Thankfully we don't have THAT many always on modules, so we can probably walk through them and quickly review.

**Comment by msfschaffner** [comment]
Ok, sounds good!
We can probably do that similarly to the clock group review that we did recently...

**Comment by cdgori** [comment]
@tjaychen you unassigned me - anything you needed here for completeness?  Seems like you guys hashed this out pretty thoroughly.

**Comment by tjaychen** [comment]
o i just unassigned because i think the rest is just actually tracking down the ports / signals.

**Comment by msfschaffner** [comment]
As discussed above, the main signals that we should audit are the `escalate_en` signals that cross power boundaries. These need to have an `Off` isolation value since they could otherwise cause spurious escalations upon power gating events. All other signals should theoretically be fine with an all-zero isolation value, since only the `On` value will activate the corresponding function.

At the moment, the only escalation signal that crosses power boundaries is the one going to the pwrmgr here.

However, after #15317 has landed, we will have to make a change to the pinmux strap sampling logic so that the `dft_en` / `debug_en` signals can survive a reset under specific circumstances (see #15494). For that to work correctly, we will likely have to introduce another `escalate_en` that crosses power boundaries and goes to the strap sampling logic.

Hence I suggest holding off with this final review until the referenced changes have landed.

**Comment by tjaychen** [comment]
I did a quick audit, there are a few blocks we should have a look at. 
always on modules: `pwrmgr`, `rstmgr`, `clkmgr`, `sysrst_ctrl`, `adc_ctrl`, `pwm`, `aon_timer`, `sram_ret`, `pinmux`

- `pwrmgr` - only uses `true_strict` detection.
- `rstmgr` - no `lc_ctrl` broadcast
- `clkmgr` - Used as part of `all clocks bypass`, meaning as currently constructed, we cannot continue to bypass clocks during low power.  Is this a concern? I don't think it should, but it might need to be clarified. 
- `sysrst_ctrl` - no `lc_ctrl` broadcast
- `adc_ctrl` - no `lc_ctrl` broadcast
- `pwm` - no `lc_ctrl` broadcast
- `aon_timer` - uses `lc_escalate_en`, need `lc_escalate_en` == OFF in order to continue counting during low power. This probably needs to change to NOT count when `lc_escalate_en` == ON.
- `sram_ctrl` - uses `lc_escalate_en` and `lc_hw_debug_en`. `lc_escalate_en` is used `true_loose`, so an isolated value of 0 will actually trigger the local escalation.  `lc_hw_debug_en` is used as part of instruction fetch using `true_strict` detection.
- `pinmux` - uses both `lc_hw_debug_en` and `lc_dft_en` , but will not be needed after the reset domain reorg.

**Comment by msfschaffner** [comment]
Ah good point regarding `clkmgr`. As long as the internal oscillators work, this should not be a concern, right?

For the `sram_ctrl` the `lc_debug_en` only applies to the main SRAM now (we disconnected it from the retention SRAM), so I think that one should be fine.

**Comment by tjaychen** [comment]
ah thanks for the reminder on `sram_ctrl`.
So it's just `aon_timer` then right?

**Comment by tjaychen** [comment]
i mis-spoke regarding `aon_timer`.  Looking closer, i think `aon_timer` does actually need its `escalate_en` input to be correctly isolated. 
`clkmgr` i don't think really matters, we just need to accept that we can't use that mode across low power. 

are those the only things?

**Comment by msfschaffner** [comment]
I believe so, yes. that leaves us with `aon_timer`, `sram_ctrl_main` and `pwrmgr` that need correct isolation values, right?

**Comment by tjaychen** [comment]
wait i thought `sram_ctrl_main` didn't need it because it's not always on?
I'm actually not sure `pwrmgr` even needs it, since it does only a strict true check.

**Comment by msfschaffner** [comment]
ah sorry, let me back up (not enough coffee ;)). 

you are right and `sram_ctrl_main` does not need it, since it is not AON.

for `pwrmgr`, since that only uses strict checks, we should be good as well. I think I had the escalation interface in mind - but that should not need any special isolation values since we keep the escalation receiver in the same reset domain as the alert handler (which will be kept in reset in deep sleep).

so that basically leaves us with `aon_timer`.

**Comment by tjaychen** [comment]
quick question @msfschaffner / @arnonsha, should we check in a file in `top_earlgrey/data` or something to indicate what signals these are? I'm asking because the reset domain fix will introduce a couple more.

**Comment by msfschaffner** [comment]
@arnonsha and I talked this morning. we agreed that he will wait until the reset domain fix landed, and then we will send a list of the signal paths. not sure what the best way for this is... should we check in a UPF parseable file that can be hooked into the UPF flow for this under `hw/top_earlgrey/syn/`?

**Comment by tjaychen** [comment]
i was honestly thinking for now even an hjson file is fine. Although a tcl file with some struct is good too (since UPF is tcl compatible).  I was more or less thinking we just want to have somewhere to keep it in the code base and not rely on issues.

**Comment by msfschaffner** [comment]
yeah we could just make a TCL that defines a few constants.

**Comment by arnonsha** [comment]
A TCL file that could be sourced by the main UPF sounds good to me

**Comment by msfschaffner** [comment]
with #15494 we now need non-zero iso values on:
- aon_timer / escalate_en
- pinmux / escalate_en
- pinmux / lc_check_byp

I will add a TCL file for this shortly.
