### ISSUE TITLE
[otbn] Should we supply PC or other information on error?

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#4327]
Currently on an error only an error code is provided, which can make debugging tricky. Do we want to extend the error information?

The simplest thing to do would be to include an error PC, simply the PC of the instruction executing at the time the error is seen. We could add further information, e.g. the DMem address of a read that resulted in an error. I feel a PC should be sufficient though.

> estimate 4

**Comment by rswarbrick** [comment]
Sounds like a good idea. Maybe we should just expose "stopping pc" on the register interface, updated with the current PC whenever OTBN stops. Since we don't have any exception handling, I think this will give what we want (and should be pretty trivial to plumb in).

There is a slight information leak, which might be a problem on the security side. For example, suppose that my code does some data dependent control flow from which I can extract secret information. Then I can fire alpha particles (or whatever!) at the chip during the run and read out the PC at my leisure. Maybe we just need to have an enable register that turns this feature on or off? Then the Ibex code can turn it on when doing on-silicon debug, and leave it turned off the rest of the time.

This question probably needs some security review.

@felixmiller: Do we have any code that does data-dependent branching? Will we?

@moidx, @cdgori: This looks like it would be helpful for debugging. Are there any other "security elephant traps" that we should be careful to skirt?

**Comment by GregAC** [comment]
We could factor in life-cycle state and avoid providing the error PC in certain life-cycle states.

**Comment by moidx** [comment]
I agree that being able to read the current PC is a useful feature. In the current security model, I don't consider Ibex access to the OTBN PC to be an issue. 

Under what conditions would an attacker be able to read any OTBN control/status register? The current requirement is that only a crypto library running in M mode will be able to interact with OTBN. For private key operations, such library will be integrity protected as part of the secure boot implementation. I suspect that an attacker being able to read any OTBN register in a production state device will probably have the ability to successfully attack other assets. 

@GregAC, do you have an initial list of internal state error codes to review as part of this issue? For example, illegal instruction, *overflows, *integrity, etc?

**Comment by rswarbrick** [comment]
Cool, that sounds like we should just add a "stop PC" CSR.

I think that this issue probably isn't the right place to discuss the list of error codes. I don't think anything is written down about them other than what appears in the documentation. We'll probably have something firmer in a week or so (since Greg's working on the RTL for error handling and pinning down the loose corners of that bit of the spec at the moment)

**Comment by felixmiller** [comment]
@rswarbrick we currently only have data dependent branching in the [ECDSA verification routine](https://github.com/lowRISC/opentitan/blob/88ced0296b6eed080bafdaa0374dc9795da4c6d2/sw/otbn/code-snippets/p256.s#L715) but leakage is uncritical there. General guideline for OTBN SW is that data dependent branching is forbidden in any OTBN code dealing with secrets.

I agree with @moidx that in our current model we do not consider OTBN and Ibex as different security perimeters and Ibex has full control on any data exchanged with OTBN. It would be a different story if we planned to enable self-contained isolated algorithms on OTBN (with side loading of assets) or if we considered OTBN as an isolated execution environment for user code. In such a case it would be preferable if the feature could be disabled permanently via fuses.

**Comment by cdgori** [comment]
I generally agree with @moidx - I don't see a problem with Ibex access to OTBN PC.  But, @felixmiller has a valid point about isolation/side-loading considerations, so I would be interested in doing what @GregAC proposed about considering LC state and only allowing this in dev, just to prevent any potential future issues were we to pursue such sideload/isolation methods in the future.  It seems like that's not too much of a restriction since most developer samples will be in dev mode already...

**Comment by tjaychen** [comment]
hey all,
this is a bit late, but do you guys remember this proposal (it's rough and outdated at this point)
https://docs.google.com/document/d/1KnmIt7vj8vkfqgAIcx6HJo8KH6zirFNF1TxlL5K6Aso/edit?usp=sharing

The idea was also to expose some kind of useful information from a processing element, and make it only available only through specific life cycle states. 

In addition to life cycle states though, how do we feel about letting software control this visibility really early in the boot stack? (for example ROM_ext or probably more realistically boot loader?)  That will mean if this needed to be debugged due to a boot failure, we'd need a specifically signed image.

**Comment by cdgori** [comment]
Probably no surprise, but that freaks me out, since it could easily capture non-sideloaded keys.  We'll have to then consider all the surface area of this and how strong our LC-based locking of it is, and if that can be thwarted.

If we do want it, I'd probably go even farther and make the enabling of this functionality somehow folded into the attestable state that diversifies the keymgr derivation paths (at minimum), so that devices with this turned on are even more non-interoperable with those that have it turned off.

**Comment by tjaychen** [comment]
hey chris,
the stuff in the doc is way out dated.  Instead of capturing transactions, it's more going down the line of letting different processing element deciding what to supply as crash information.  But capturing the raw data on the bus wouldn't be a good idea... it would more or less be metadata about that data (for example PC). 

That crash information would then be modulated via fuses or early boot chain setting. If it's tied to life cycle fuse, it's already probably the identity process. Similarly, if we leave it as software controlled in the boot chain, we can do something similar as part of software binding in key manager (i think it can be used as that).

**Comment by rswarbrick** [comment]
This discussion is a bit outdated and the specific question about stop address was split out (by accident) into #7158, which we've just resolved for now. Let's close this issue since we seem to have agreement that we're not going to report anything extra at the moment.
