### ISSUE TITLE
Newbie guide to contributing fixes to Opentitan

### ISSUE THREAD

**Issue by svenka3** [lowRISC/opentitan#4331]
Hello,
  One question while I was trying to fix some low hanging issues on Riviera/Questa support.

From https://github.com/lowRISC/opentitan/blob/master/CONTRIBUTING.md I read:

>> Create pull requests from a fork rather than making new branches in github.com/lowrisc/opentitan.

I generally follow the fork --> clone --> add remote --> branch --> commit flow as in:

https://jarv.is/notes/how-to-pull-request-fork-github/

Do you folks differ slightly in that, you don't want me to create a branch? 

Also, what exactly you mean by "do not commit" - how do I raise a pull request otherwise?

Sorry if this is too simple, but not so obvious to me.

Regards
Srini

**Comment by rswarbrick** [comment]
Hi! Our `CONTRIBUTING.md` is arguably a bit confusing and should probably say "merge" in some of the places it says "commit". I'll push a patch to redraft it a little in a minute.

We use the usual GitHub PR flow, as you described. The "don't create new branches in `github.com/lowrisc/opentitan`" bit is saying that you should create a new branch on your fork and raise a PR (just like you normally would). Apparently, we lowRISC employees need reminding not to mess up our namespace :-)

I'm closing this (since the answer is "Yep, do what you expect!"). Please reopen if you feel the question isn't fully answered.
