### ISSUE TITLE
Renaming dir sim-vcs inside fusesoc.hjson

### ISSUE THREAD

**Issue by svenka3** [lowRISC/opentitan#4334]
Hi,
  How do i change the sim-vcs directory name to say sim-{tool}

Inside my scratch DIR: 

>> opentitan/scratch/uart.sim.questa/master/default/

"ls"

build.log  env_vars  sim-vcs  src

I wish I can change it to sim-{tool}

I see hw/dv/tools/dvsim/fusesoc.hjson

  sv_flist_gen_dir:   "{build_dir}/sim-vcs"
  // VW sv_flist_gen_dir:   "{build_dir}/sim-{tool}"

Tried the above, didn't really work - I still see sim-vcs getting created.

Any comments please?

Thanks
Srini

**Comment by rswarbrick** [comment]
@sriyerg (as the dvsim expert!)

**Comment by sriyerg** [comment]
We run FuseSoC only to generate the filelist. By default, it assumes VCS as the simulator of choice. FuseSoC creates and puts the generated file list in that folder - we do not create that folder as a part of dvsim step. We instead set the `sv_flist_gen_dir` which basically tells dvsim where to pick up the generated file list from. I understand that it is minor annoyance that it does not reflect the correct tool being used, but in practice, it is completely harmless and should make no difference to what simulator is actually being used. 

If you want to, you can try fixing it by adding this to `questa.hjson`:  `sv_flist_gen_opts: ["-sim=questa"]` (you may need to confirm that FuseSoC supports Questa). The reason for not doing this by default: at the start of the project, FuseSoC supported only a few commercial simulators. It would fail when we added support for a new tool, even though we were stopping at the filelist generation step as opposed to going all the way building the simulation executable. Since it doesn't really matter, we decided to not have that switch at all.

**Comment by sriyerg** [comment]
Can this be closed?

**Comment by svenka3** [comment]
My 2 cents - if you can rename it to be generic than VCS it would be great

**Comment by sriyerg** [comment]
Sure, we will think of a way to fix it. It is very low on our priority though.
