### ISSUE TITLE
Figure out why clang builds are significantly slower than GCC

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#4481]
We currently build device software with both clang and GCC. The clang builds take in CI 2:55 min ([example](https://dev.azure.com/lowrisc/opentitan/_build/results?buildId=28479&view=logs&j=5df5adf8-3577-5927-f0b2-31afed2697ee&t=dcb8db2a-d944-5acc-e50e-bea93f2a14e9)), the GCC builds take 1:30 min ([example](https://dev.azure.com/lowrisc/opentitan/_build/results?buildId=28479&view=logs&j=4adc1f0e-dd73-525b-7895-21c8cb22c36a&t=95ef6d26-7469-5848-e178-e99301410aa7)).

That seems quite a significant discrepancy, are there optimization flags that we don't pass to both compilers, or is clang really that much slower?

@lenary @luismarques

**Comment by luismarques** [comment]
That's unexpected. I'll have a quick look at it on my local machine to see if I spot any obvious issues.

**Comment by luismarques** [comment]
In my local machine the device software builds take nearly the same time when using Clang and GCC.
I don't see anything obvious that may be the culprit in the CI machine.
As a next step, I suppose that we could change the build scripts so that ninja would output a timestamp per build step, to see if the slowdown is due to specific steps (e.g. compiling vs linking) or something more spread out.

**Comment by lenary** [comment]
@luismarques if you download the Pipelines run logs, each log line has a full timestamp. I don't know if there's an easier way to do the analysis though.

**Comment by luismarques** [comment]
I wrote a [quick and dirty script][1] to parse the log messages for Clang and GCC and to compare the time each build step takes. I use it like this: `python3 time.py | sort`.

For the results to be meaningful, I think we need to do a PR where we build with `j1` and analyse those build logs, otherwise the time between messages doesn't reflect how long each step took. @lenary @imphil want to do that PR?

[1]: https://gist.github.com/luismarques/81c114309931afa52eec0a878a212f3e

**Comment by imphil** [comment]
@luismarques you can do a PR that changes the CI setup and just take the measurements from there.

**Comment by luismarques** [comment]
The cause of why Clang-based builds are slower than GCC-based ones doesn't have to do with the time that Clang and GCC take to compile and link things. Instead, it's the `embedded_target.py` script that's slower to process the binaries produced during the Clang-based build. If I change that script to create dummy files then the builds do take the same time for GCC and Clang on my machine.

BTW, I was doing this quick investigation as a background task, so I did some silly mistakes due to not paying sufficient attention. Initially I claimed that on my machine the builds took the same time for Clang and GCC. That was incorrect. When I invoked `./meson_init.sh toolchain-file.txt` I forgot the `-t` option, but the script didn't complain. That might be worth fixing @lenary.

**Comment by lenary** [comment]
Re the "forgetting `-t` not causing errors" issue - the idea is that `./meson_init.sh` will go to reasonable lengths to find the correct toolchain file if you don't specify `-t`. That said, I guess it's not erroring if there are extra, unprocessed arguments, so that is probably worth looking into :)

**Comment by luismarques** [comment]
Yes, that's what I meant, passing the toolchain file but omitting `-t`, which technically is just passing an extraneous argument.

**Comment by lenary** [comment]
https://github.com/lowRISC/opentitan/pull/4715 addresses that issue. 

I'd be interested to understand why `embedded_target.py` is taking longer with clang - i saw some delays when trying to use LLD with it, but I thought that was how long the tool really took. Maybe we have more linker script issues to diagnose.
