### ISSUE TITLE
[otbn] Preventing any actions on error

### ISSUE THREAD

**Issue by GregAC** [lowRISC/opentitan#4507]
Currently on error OTBN comes to an immediate halt but the faulting instruction could still trigger visible actions, such as writing to the register file or memory. The general concept is once an error is seen OTBN state (including dmem) should be considered trashed. SW checks the error and starts over. There may be some security concerns with this.

We can alter the behaviour so a faulting instruction cannot perform any writes or other architecturally visible actions.

> estimate 4

**Comment by rswarbrick** [comment]
I would probably prefer a behaviour that said "all side-effects of the bad instruction are cancelled" or "all side-effects of the bad instruction take effect", but that's mainly laziness on my part: it makes writing the spec and the ISS easier!

**Comment by GregAC** [comment]
Initially this was an oversight on my part, I just later realised it could be reasonable behaviour!

I believe we've got "all side-effects of bad instructions take effect" right now though there may be some interesting corners cases as to exactly what those side-effects do. I'm perfectly happy to switch to "all side-effects of bad instructions are cancelled" I suspect it will be simpler for the ISS as there's bound to be something fiddly with the former option.

**Comment by rswarbrick** [comment]
I think either is probably easy for the ISS. At the moment, it tries to do "all side-effects of bad instructions are cancelled", because that's what we agreed we'd do. I'm a little worried about the security implications of allowing memory writes from a glitched instruction, so would probably prefer the cancelling behaviour. Is there a strong reason not to do that?
