### ISSUE TITLE
Q: Why do we need to zero out the stack in the bootROM reset code?

### ISSUE THREAD

**Issue by tdietert** [lowRISC/opentitan#4565]
In the bootROM CRT file, the stack is "[setup](https://github.com/lowRISC/opentitan/blob/a3a75a18fdb09f106991e7fd09fd5bac573b2eca/sw/device/boot_rom/rom_crt.S#L55)" and [zeroed out](https://github.com/lowRISC/opentitan/blob/a3a75a18fdb09f106991e7fd09fd5bac573b2eca/sw/device/boot_rom/rom_crt.S#L96) before the program [jumps](https://github.com/lowRISC/opentitan/blob/a3a75a18fdb09f106991e7fd09fd5bac573b2eca/sw/device/boot_rom/rom_crt.S#L127) to the [_boot_start](https://github.com/lowRISC/opentitan/blob/a3a75a18fdb09f106991e7fd09fd5bac573b2eca/sw/device/boot_rom/boot_rom.c#L32) function in `boot_rom.c`.

I understand why the stack pointer must be initialized, but am uncertain about why the stack needs to be zeroed out here. Won't the `_boot_start` procedure decrement its stack pointer as necessary and write the relevant data to the stack accordingly when, for instance, it calls another function in its body? Why do the memory locations in the stack need to be 0 before handing off control flow to the boot code? 

I did briefly research this question, and the best answer I could come find is a stack overflow answer commenting that the stack memory locations may contain sensitive data, and that if the reset code doesn't zero out the stack's memory locations, then this sensitive data may be leaked... but then that implies that the boot code has been compromised in order for that sensitive data to be used maliciously. 🤔 

If anyone can explain to me why we zero out the stack before calling `_boot_start`, I would be very grateful! 🙇

**Comment by lenary** [comment]
> the best answer I could come find is a stack overflow answer commenting that the stack memory locations may contain sensitive data, and that if the reset code doesn't zero out the stack's memory locations, then this sensitive data may be leaked

You're right here, but you've missed one particular possibility. When restarting the chip, the SRAM may not be powered down for long enough to clear out previous values. In order to be totally sure the previous values are not there, we take the time to wipe the stack, to ensure values are not left for later stages to read.

Another issue is that you assume that all stack writes are in the bounds of their stack allocation. This is not something that is easy to guarantee - though we would like the ROM image to be free of buffer overflow opportunities, actually achieving this is very difficult, and we can't claim to have done so 100%. We have had issues with this in the past, in test flash images loaded by the Boot ROM. 

The Boot ROM is not actually going to be the production ROM image, it's only an image we're using for testing. We're working on the Mask ROM (`sw/device/mask_rom`) which will be used on the final chip to do secure boot from chip reset. This is likely to enable SRAM scrambling before wiping RAM (it currently zeroes all of RAM), which will help ensure no contents from previous boots can be read successfully.

There is a separate retention RAM on the chip, which is specifically preserved during low-power and restart, but there are specific guarantees on when the ROM image needs to clear that depending on the reset reason. 

I hope this offers a comprehensive answer to your query.

**Comment by tdietert** [comment]
Hi @lenary, thank you for the explanation! I have a few questions as a result:

When you write
> You're right here, but you've missed one particular possibility. When restarting the chip, the SRAM may not be powered down for long enough to clear out previous values. In order to be totally sure the previous values are not there, we take the time to wipe the stack, to ensure values are not left for later stages to read.

What is the problem if the previous values are still on the stack given the way the RISC-V ABI works? The prolog of procedures are going to decrement the stack pointer and store necessary registers on the stack overwriting any previous data, and then the epilog is going to increment the stack pointer and load the saved register data back into their corresponding registers. Why does the boot code care if the stack contains data from a previous run? Is this because the boot code will jump to arbitrary programs that may be able to read the old memory contents-- I wouldn't think so, because I assume the chip is running trusted, secure programs that won't maliciously try to read data from accessible memory. What am I misunderstanding?

Also, you say
> Another issue is that you assume that all stack writes are in the bounds of their stack allocation.
I'm not sure if you mean that I've assumed it, or if someone working on the opentitan firmware might assume it. Can you elaborate on this point (if you have the time)? For instance, if feels like you are implying that zero-ing out the stack somehow prevents buffer overflows or constraining stack writes within the bounds of the stack allocation.

Lastly, I'm a little confused about this "global" heap and stack space, the heap size, and the size of `ram_main` (65KB). In the linker script, the heap is declared to be the top addresses of `ram_main`, and the rest of it is given to the stack. I have a few resulting questions:
- What types of programs are going to be run on the opentitan chip that only necessitate 65KB of RAM?
- Why is the heap given a fixed size if it can grow during runtime (are we not providing a `malloc` type function in the board level API?)?
- Do we need to know the heap size _only_ to calculate the address space of the stack so we can zero it out in the boot code?

Thanks in advance for all your help-- I'm just learning about opentitan and the firmware world, and deeply appreciate any time you can allocate to answering my questions! 🤗  Obviously, it's not a problem if you can't readily make the time to help me understand some of these low-level nuances. 🙇

**Comment by tdietert** [comment]
_Oh and one more question (for posterity, at the least!):_

I see this `.idata` section in the linker script
https://github.com/lowRISC/opentitan/blob/a3a75a18fdb09f106991e7fd09fd5bac573b2eca/sw/device/boot_rom/rom_link.ld#L92-L94
and the `_data_init_start` symbol used in the stack zero-ing
https://github.com/lowRISC/opentitan/blob/a3a75a18fdb09f106991e7fd09fd5bac573b2eca/sw/device/boot_rom/rom_crt.S#L110
and am wondering how this works! 

It seems that the `.idata` section doesn't tell the linker to actually copy any sections since no sections are mentioned in the section command body, yet the comment above the `.data` section says https://github.com/lowRISC/opentitan/blob/a3a75a18fdb09f106991e7fd09fd5bac573b2eca/sw/device/boot_rom/rom_link.ld#L98

Thus, in the `rom_crt.S` file linked previously where the data in the `.idata` section in ROM is supposedly being copied to the runtime location in RAM, I'm wondering where the data in the `.idata` section actually gets into the `.idata` section before being copied to RAM:
- Is there a compilation flag that tells the `boot_rom.c` file to output data in the `.idata` section in ROM?
- Why does this comment assert that `.idata` is the same length as `.data`, and where might this be specified?
https://github.com/lowRISC/opentitan/blob/a3a75a18fdb09f106991e7fd09fd5bac573b2eca/sw/device/boot_rom/rom_crt.S#L104-L106

Thanks again!

**Comment by mundaym** [comment]
Hi @tdietert, @lenary is on vacation at the moment but I can take a stab at your question about `_data_init_start`. I think the key magic here is the `AT(_data_init_start)` section attribute applied to the `.data` section:

https://github.com/lowRISC/opentitan/blob/a3a75a18fdb09f106991e7fd09fd5bac573b2eca/sw/device/boot_rom/rom_link.ld#L100

My understanding is that this puts the initial image for the `.data` section into the ROM starting at `_data_init_start`. From there it is the responsibility of the crt code to copy it into the correct location in RAM. The `AT` command documentation gives a good example of this: https://sourceware.org/binutils/docs/ld/Output-Section-LMA.html#index-AT_0028lma_0029

**Comment by lenary** [comment]
Hi @tdietert! Sorry for the delay in getting back to you! I hope these will be comprehensive answers to your questions, as I have recently stopped working on the OpenTitan project.

Before we begin, I want to caution about two things:
1. The Boot Security Model (including how boot stages are planned to be securely isolated from each other) is still being defined. Some of the specific answers you're looking for may change as this reaches definition, and I'm only able to comment on public information.
2. The `boot_rom` code will not be the ROM image for the final chip. `boot_rom` is the first boot stage for our test systems, and we decided to start again with a clean implementation that we can secure, rather than to try to harden that implementation. That implementation is in `sw/device/mask_rom` and there's [a document](https://docs.opentitan.org/sw/device/mask_rom/docs/) which describes what that code will do. I hope some of the reasoning is clearer there, and some of the code too - but the implementation is currently very barebones. 

# Zeroing to avoid Leaking Information

> What is the problem if the previous values are still on the stack given the way the RISC-V ABI works? The prolog of procedures are going to decrement the stack pointer and store necessary registers on the stack overwriting any previous data, and then the epilog is going to increment the stack pointer and load the saved register data back into their corresponding registers. 

You are correct that this overwrites some previous data, and the data will always be written to the stack by a function before it is read again. No previous stack values will affect the data future functions need to store on the stack.

The problem we're solving is an information leak problem. Think of a function `a`, which calls `b_stores_lots_of_secret_info`, and then `c` (so `b_stores_lots_of_secret_info ` and `c` are both called from `a`). If `b_stores_lots_of_secret_info` stores a secret to a stack slot that isn't overwritten by `c`, then functions after `a` might be able to read it. The epilog of `b_stores_lots_of_secret_info` is not required by the ABI to zero the stack that it used, and for efficiency usually will not. In fact, getting compilers to keep stores which are never read later (by a correct program) is very difficult, as usually these stores look "dead" to the optimiser. Lots has been written about how Dead Store Elimination is bad for leaking information like this, and various compilers and libraries provide methods to write over sensitive data in a way the compiler won't interfere with. 

> Why does the boot code care if the stack contains data from a previous run? Is this because the boot code will jump to arbitrary programs that may be able to read the old memory contents-- I wouldn't think so, because I assume the chip is running trusted, secure programs that won't maliciously try to read data from accessible memory. What am I misunderstanding?

The Secure Boot System cannot make assumptions about later boot stages, including that those stages are not malicious or contain security holes. All later boot stages are in writable memory, so it's a stronger proposition to assume you don't know anything about future boot stages, than to assume they're trustworthy and secure. So each boot stage has to clear out sensitive values before the next stage runs, and it is good practice to do the same on first boot, before the first stage, so there's no leakage between restarts.

> > Another issue is that you assume that all stack writes are in the bounds of their stack allocation.
> I'm not sure if you mean that I've assumed it, or if someone working on the opentitan firmware might assume it. Can you elaborate on this point (if you have the time)? For instance, if feels like you are implying that zero-ing out the stack somehow prevents buffer overflows or constraining stack writes within the bounds of the stack allocation.

You're right that it doesn't prevent buffer overflows. What it helps to cut down on is the leakage of information on a buffer overflow. If we are allocating arrays on the stack, buffer overflows are fairly likely, and it would be good to ensure those don't leak sensitive info. The zeroing is a defence-in-depth protection, not a primary protection against buffer overflows (which is careful and considered code review, given we're using C).

# Stack and Heap Sizes

Sadly, I cannot comment on what the intended programs are, as I'm not sure what information there is public.

Early boot stages, especially the ROM, likely will not have a heap, and all allocations will be static or on the stack. Any RAM not used for the stack is left for static allocations during boot stages without a heap. 

# `.idata` in the Linker Script

`idata` means "initial data", as a convention. This is the copy of the `.data` section which will be copied into RAM when the program starts (we have no OS loader etc), so it can be used during program execution. @mundaym explains how that works, it depends on the ["Load Memory Address"/"Virtual Memory Address" concept](https://sourceware.org/binutils/docs/ld/Basic-Script-Concepts.html#Basic-Script-Concepts) from linker scripts, and I hope he has provided a comprehensive answer. 

You're right that the end address of `.idata` is not well-defined, and is very implicit. We know that `.idata` contains exactly the same contents as the `.data` section, it's just at a different address.

We use the `.data [<virtual address>] : AT(<load address>) { … } > ram` in the `boot_rom` linker script, which is equivalent to the `<section> [<virtual address>] { … } > ram AT> rom` in the `mask_rom` linker script, but I find the latter clearer, as it relies less on saving a ROM address for the load address, and instead will just choose the next (correctly aligned) virtual address in RAM, and the next (correctly aligned) load address in ROM. 

With the definition in the `boot_rom` linker script which uses explicit load/virtual addresses, if we want anything else in the ROM after the `.idata` section, we need to tell the linker script exactly what virtual and load address to keep it at (even if both are the same), using `AT>` will do the right thing with effectively allocating the memory for `.data` into both RAM and ROM, which is why I wrote the `mask_rom` linker script differently.

Linker Scripts are complex, and not usually well documented, and linking is complex because it's where a lot of things come together - one's OS or simple C Runtime (CRT) in the case of embedded systems, the program language you're using, the compiler, project data, and processor characteristics. There are a lot of moving pieces to this, and even more technical debt than you might imagine. The amount of implicit behaviour in linker scripts is also not very helpful. 

I've found [ld's documentation](https://sourceware.org/binutils/docs/ld/) useful (but not trivial to navigate), as well as the book ["Linkers and Loaders" by Levine](https://linker.iecc.com). More recently [Stargirl documented in much greater detail the linker script for one of her open source projects](https://blog.thea.codes/the-most-thoroughly-commented-linker-script/). I'll also admit to being confused by [linker script issues reasonably frequently still](https://github.com/tock/tock/pull/2180).

(Aside: I'm sure my colleagues will find it fitting that my last contribution to OpenTitan is a long answer that covers the CRT and our Linker Scripts).
