### ISSUE TITLE
Problem ::: ROM size increase beyond 32KB

### ISSUE THREAD

**Issue by rmbhagwat** [lowRISC/opentitan#4593]
I tried to increase the ROM size from 16KB to 32KB by changing only following file and it works: -
```
diff --git a/hw/top_earlgrey/data/top_earlgrey.hjson b/hw/top_earlgrey/data/top_earlgrey.hjson
index a1f37412..a11aa04e 100644
--- a/hw/top_earlgrey/data/top_earlgrey.hjson
+++ b/hw/top_earlgrey/data/top_earlgrey.hjson
@@ -411,7 +411,7 @@
       type: "rom",
       base_addr: "0x00008000",
       swaccess: "ro",
-      size: "0x4000"
+      size: "0x8000"
```

But when attempted to change it to 48KB or 64KB, nothing appears on UART serial.
```
diff --git a/hw/top_earlgrey/data/top_earlgrey.hjson b/hw/top_earlgrey/data/top_earlgrey.hjson
index a1f37412..82fefff7 100644
--- a/hw/top_earlgrey/data/top_earlgrey.hjson
+++ b/hw/top_earlgrey/data/top_earlgrey.hjson
@@ -411,7 +411,7 @@
       type: "rom",
       base_addr: "0x00008000",
       swaccess: "ro",
-      size: "0x4000"
+      size: "0x10000"
```
I see the proper vmem file, hw/top_earlgrey/sw/autogen/top_earlgrey_memory.ld and vivado using 16 BlockRAM slices of RAMB36E2.

What could be the probable problem/dependency?

Thank you.

**Comment by rmbhagwat** [comment]
64KB ROM is working when the start address is multiple of 64KB boundary.
with default 0x8000 starting address, it was not working. when I gave 0x10000, it started working.

What could be the logical reason?

**Comment by msfschaffner** [comment]
I believe the issues you are experiencing are due to the following constraints:
1) the ROM employs a scrambling mechanism that permutes the address. Therefore, the ROM size needs to be aligned with a power of two, since otherwise that mapping is not bijective.
2) the crossbar just strips off base address prefixes when routing transactions into peripherals, and does not subtract the base address. addresses should hence be constructed so that the local address range within a peripheral does not overlap with the base address:  `<base address prefix> | <local address space>`

@rswarbrick might be worth putting in a check into our tooling for these things, WDYT?

**Comment by rswarbrick** [comment]
We've actually already got that check (I just tried it out!) in `tlgen/validate.py`, line 292. I just tweaked `rom_ctrl`'s registers to start 4 bytes later and got this:
```
ERROR: Size mask and base address are overlapping.  Check the config. Addr(0x411e0004 - 0x411e1003)
```

**Comment by rswarbrick** [comment]
I think the original question has been answered (thanks, Michael!) and the possible tooling task turns out to have been done already, so I'm going to close this.

**Comment by msfschaffner** [comment]
Thanks for checking, @rswarbrick. Do you know wether we also check that the ROM size is a power of two? That could also be made a design assertion...

**Comment by rswarbrick** [comment]
Good point. I don't think we do at the moment, but it's easy enough to add to the `rom_ctrl` RTL. I'll file a PR.

**Comment by rswarbrick** [comment]
Oh! Yes we do: it's `DepthPow2Chk_A` in `prim_ram_1p_scr`. (Obviously that won't do anything with Verilator, but it should catch stuff on commercial simulators).

**Comment by msfschaffner** [comment]
Ah right. So we're covered then ;).
