### ISSUE TITLE
[aes] Simplify clearing functionality

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/opentitan#4653]
Currently, aes features several bits in the trigger register to separately clear
- key registers,
- iv registers,
- data input registers, and
- data output registers.

@rasmus-madsen just told me that from a verification standpoint this is bad. There are many different corner cases to test (e.g. clear key without iv). Also, some of them are very difficult to test. For example the iv registers are updated internally by the module. Thus, clearing the key after having computed a first block and then re-providing the same key and data will not give the same output. Also, from a software viewpoint, there is probably very little value in allowing the module to clear the key registers but not the iv registers.

For this reason, @rasmus-madsen and I suggest to simplify the clearing functionality. We see two possible options:
1. A trigger single bit to clear everything in one shot: key, iv, data in, data out registers.
2. Two trigger bits to separately clear:
    i) key, iv, and data in registers
    ii) data out registers

Option 2. has the advantage that software - after starting the last block of a message - can already trigger the first part of the clearing i). This will start immediately after finishing the last block but not touch the data out registers. Software has time to read out the last data block and then clears them after that ii).

Before implementing this change, I wanted to quickly get your opinion @cdgori , @tjaychen , @moidx . Do you see a problem with that?

**Comment by rasmus-madsen** [comment]
@vogelpi is correct - some of the tricky corners are as mentioned if you update a key "mid" message - this is currently allowed but there is no way to do such a thing in our current c-models. 

Another Corner case is if clearing key and output data after providing information to trigger the automated start.
it is impossible to detect if the clearing happened before or after the first block was calculated - i.e if that should be a part of the calculation.

having the clearing functionality as suggested will remove all these corner cases where it is hard to predict if a previous block needs to be included, by ensuring that clearing input registers, is effectively the same as starting a new message. and will make the verification space significantly less complex

**Comment by cdgori** [comment]
Sorry, I missed this in the run-up to Christmas holiday, it got buried too far back in email stack.  :(

I completely understand the concern raised by @rasmus-madsen about separate clears, so addressing that seems like a good idea to me.

I have a slight preference to your option 2, if it does not create too many verification headaches.  Assuming the canonical implementation (i.e. the DIF) did as you say and used the 2.i functionality to clear data_in/key/iv immediately after supplying the final data block, this would mean that the key&iv exist in the AES module for the shortest amount of time.  Basically this is a more "atomic" operation that having the software need to chase loose ends and remember to clear the key & iv later.

But if option 2 is judged to introduce undue verification complexity then option 1 is also acceptable to me.  (It's possible that even choosing option 2, because of the way some protocols work, that software will not "know" at the time it is submitting what is really the final data block, that it is actually the final data block, and so it will behave more conservatively and defer clearing 2.i and 2.ii to some later point when it picks up the data_out, at which point it does "know" that this is the final data block using this key/iv pair.  Basically option 2 gives an optimization possibility, which I would hope could be used, but can't say for sure that it would be.)

**Comment by vogelpi** [comment]
Awesome, thanks for your feedback @cdgori . After consulting with @rasmus-madsen , we have decided to go with option 2. I will now start the implementation of this.
