### ISSUE TITLE
[keymgr] can we skip hw/sw output when an error occurs

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#4770]
@tjaychen 
I feel it's a bit hard to check the output doesn't match to any meaningful data when an error occurs.

In other non-security IP, we may just skip checking the output if it's an error case. But since this is security IP, we probably need to make sure output doesn't expose any secret if there is an error.
Currently, we update output for some error cases like invalid OP, but no output update for some cases like invalid input in gen-sw/hw-out. Also, some error cases aren't defined as clear as normal case, like max_key_version for StDisable is 0 in RTL, which triggers easily invalid input if key_version > 0, and blocks the hw/sw output update. It's a challenge for scoreboard to model all these differences and may be not very worthy.

If design doesn't change the output or set output to 0 for error cases, we just need to compare those meaningful outputs from normal operation with expected values. For invalid OP, we still need to output random data to KMAC for KDF, but it's fine as this is needed and this behavior is also very consistent. WDYT?

**Comment by tjaychen** [comment]
@weicaiyang 
first of all, should i try to make this clearer in the doc?
There are basically 3 categories of responses (at least that was my intent).

Ie, if invalid input (and there's a variety of things that qualify as invalid input) or invalid data from kmac (all 0's or all 1's), we do not update any of the sideload keys or internal key.

If we encounter some kind of fatal error, OR we explicitly transition to disable, the internal key is updated, but sideload keys are kept.

If we disable key manager overall, then everything is wiped. 

Does this generally agree with your understanding?
The main reason for updating the internal values during fatal error is mostly because that error case is unexpected and we need to locally "wipe".  While the invalid input or output could be some kind of software mistake.

Would it be easy to check just that during specific moments "something" has changed? Instead of tracking the exact value?

**Comment by weicaiyang** [comment]
sorry, what I refer to are SW output (reg SW_SHARE*OUT*) and HW sideload output. Internal key update looks good to me.
For gen-id operation in Init or Disabled state, we update SW output and this is an InvalidOp.
For gen-sw/hw OP in Init or Disabled state, we update SW output or HW sideload output if no other errors like InvalidIn/Out. But max_key_version in these states are 0. So, most likely we will see InvalidIn error.

If we don't update output in above 2 cases, it will be easier to check in scb.

**Comment by tjaychen** [comment]
wait @weicaiyang that sounds more like a bug on my end.
The idea behind disable was "supposed" to behave like any other normal state, ie, it would keep updating.  The only difference being that it would report invalid operation.  

It sounds like the problem you're really facing is that because during disable we always select 0 for the max_key_version, you're seeing issues where it is never updating.  Is that right?

**Comment by weicaiyang** [comment]
From below RTL, only max_version in 3 working states can be non-zero. For other states, max_version actually isn't defined in spec. The checking for key version is the same in Disabled. So when key_verison isn't 0, I see gen-sw-out doesn't update register SW_SHARE in Disabled state.


```
  for (genvar i = KeyMgrStages; i < 2**StageWidth; i++) begin : gen_key_version_fill
    assign max_key_versions[i] = '0;
  end

  assign max_key_versions[Creator]  = reg2hw.max_creator_key_ver;
  assign max_key_versions[OwnerInt] = reg2hw.max_owner_int_key_ver;
  assign max_key_versions[Owner]    = reg2hw.max_owner_key_ver;
```
but TBH, we don't see the value of updating entropy value to SW_SHARE. Is it more safe to use set them to 0?

**Comment by tjaychen** [comment]
so we wanted to avoid deterministic values mostly because that could have unintended leakage..
let me think a bit about how to handle this case.

**Comment by weicaiyang** [comment]
> so we wanted to avoid deterministic values mostly because that could have unintended leakage..
> let me think a bit about how to handle this case.

for some error cases we update SW output with entropy data. For some cases we don't update. If users can set the `key_version`, then they can control output not updated after an OP.
Not sure if this has higher chance to leak secret.

**Comment by tjaychen** [comment]
let me have a closer look. I think basically what we're saying is that during invalid states, we want to have more consistent behavior to what is happening, is that right?

**Comment by tjaychen** [comment]
@weicaiyang i'm thinking about changing this to ..

During Init / Disabled state, any operation that causes us to select random data as input.. ie
- generate call during Init state
- disable call during Init state
- any call during Disabled state

will update the selected gen_* destination.  This should make the contents more consistent at a minimum. 

The invalid input i want to think about a bit more on what would be the right input should be for `max_key_version`.

**Comment by tjaychen** [comment]
@weicaiyang can this issue be closed now?

**Comment by weicaiyang** [comment]
> @weicaiyang can this issue be closed now?

closing it. Thanks for the reminder
