### ISSUE TITLE
[vcs] Autogenerated VCS Makefiles not listing C++ include dirs 

### ISSUE THREAD

**Issue by aalthoff-ttgl** [lowRISC/opentitan#4773]
Hi all,

VCS builds fail due to incorrect use of filelist +incdirs+ and needed args on the VCS command line.

Details:

After running, e.g. 
`fusesoc --cores-root . run --flag=fileset_top --target=sim --tool=vcs --setup --build lowrisc:systems:top_earlgrey`
the Makefile written to 
`$REPO_TOP/build/lowrisc_systems_top_earlgrey_0.1/sim-vcs/Makefile` 
does not contain the include dirs for the C++ files listed in the filelist: 
`$REPO_TOP/build/lowrisc_systems_top_earlgrey_0.1/sim-vcs/lowrisc_systems_top_earlgrey_0.1.scr`

Instead, the C++ include dirs are listed as `+incdir+` plusargs in the filelist. This doesn't work, and the build fails (after a few other HDL fixes - out of scope for this issue). 

`+incdir+` plusargs only tell VCS where to look for includes in HDL files. In order to specify passthrough arguments for the C++ compiler, the VCS command can use `-CC` and `-LDFLAGS` (among others detailed in the VCS manual) at the end of the line, each followed by the appropriate passthroughs for the C++ compiler. 

This is true as of VCS P-2019.06-1.

**Comment by imphil** [comment]
The behavior you're describing is expected. What are you trying to achieve? We don't run top-level simulations through fusesoc directly, but use dvsim instead, where we pass additional options to VCS (or other simulators) as needed. You can find a bit of documentation at https://docs.opentitan.org/doc/ug/getting_started_dv/#building-and-running-tests.

**Comment by aalthoff-ttgl** [comment]
@imphil - thanks for the info and quick response.

My question then is: Is there a proper method to do the same thing with VCS as is done in the Verilator flow described [here](https://docs.opentitan.org/doc/ug/getting_started_verilator)?

What I'm trying to do: generate the top-level design files and firmware, and simulate system-level use cases with VCS in a manner similar to the Verilator flow. 

I did this before (last year) with previous iterations of the design.

So I'm not referring to steps needed to run the simulation, or (necessarily) UVM for DV, only building the simulation binary using VCS with the eventual goal of using DPI to interface with the sim. From what I can tell from the (collective) docs, a way to do this would be akin to `fusesoc --cores-root . run --flag=fileset_top --target=sim --setup --build lowrisc:systems:top_earlgrey_verilator`.

There is no "getting started with VCS" page yet, as far as I could find, so I extrapolated that adding `--tool=vcs` and altering the target would do the job. And it (kind of) does! ...with the exception of the incorrect +incdir+ lines in the filelist and missing -CC -I and -LDFLAGS -lstdc++ args in the Makefile (modulo independent (afaiks) HDL issues).

**Comment by sriyerg** [comment]
What you are trying to do is something we have never tried. We run DV simulations with VCS using `util/dvsim/dvsim.py`, a regression tool that ships with the repo. 

I am not unsure what you are trying to achieve. But IIUC you want to stop at the simv generation step? You can still do that using `dvsim`. Try running the following:

```console
  ./util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i chip_uart_tx_rx --build-only
```

This will not run any tests, only generate the simulation executable. Note that the top level design used is slightly different (lowrisc:system:top_earlgrey_asic) than the one used by Verilator. The UVM testbench around it does not have the same DPI-C constructs as Verilator either, because we have UVM agents in place instead of those.  

To run the full regression:

```console
  ./util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i all 
```

To find individual tests to run, try passing `--list tests`. 

Note that even though it is a UVM based testbench, for the most part, we are doing integration testing (system level usecases) natively with Ibex running a bare-metal SW image (same as Verilator). We run most of the same tests as Verilator. A small subset of DV tests bypass the CPU and directly run UVM test sequences instead. We use those UVM agents to send and receive data over the SoC interfaces (UART, SPI, GPIO etc) instead of the DPI-C constructs. 

The HJSon file supplied to `dvsim` describes the test entries (most of them require SW image to be compiled). The SW image to be compiled for a test is sequenced by `dvsim` itself, so meson / ninja does not need to be invoked separately to build the firmware. Each SW image may be paired with a UVM test sequence which sends stimulus / performs checks from the testbench side, based on the SW test's needs.

Let me know if this works for you.
