### ISSUE TITLE
Artix-7 XC7A100T

### ISSUE THREAD

**Issue by sundas56** [lowRISC/opentitan#4791]
Hello, has anyone tried to port opentitan on Artix-7 XC7A100T?, I don't have the nexy video fpga board.

**Comment by vogelpi** [comment]
Hi @sundas56 ,
unfortunately, this FPGA is not big enough to implement the full `top_earlgrey` design. However, since the FPGA board we currently use for side channel analysis ([the ChipWhisperer CW305](http://store.newae.com/cw305-artix-fpga-target-board/)) features the same FPGA devices, we have come up with a reduced version called `top_englishbreakfast` just for performing side channel analysis of the AES block. So this design doesn't have otbn, kmac, otp and some other core IPs of OpenTitan. You can build the Verilator simulation using
```
fusesoc --cores-root . run --flag=fileset_topgen --target=sim \
  --setup --build lowrisc:systems:top_englishbreakfast_verilator
```
and the FPGA build using
```
hw/top_englishbreakfast/util/prepare_sw.py
fusesoc --cores-root . run --flag=fileset_topgen --target=synth lowrisc:systems:top_englishbreakfast_cw305
```
Please have a look at the following PR to get more insight:  #4329

**Comment by sundas56** [comment]
Thanks

**Comment by sundas56** [comment]
Can I integrate opentitan's AES IP with risc-v EL2, issues with tlul and axi interface??

**Comment by vogelpi** [comment]
I don't know the EL2 design and thus can't really say. You would probably have to design a TLUL-to-AXI adapter for the AES unit. But this should be doable. Maybe you even find an open-source implementation for that somewhere.

**Comment by sundas56** [comment]
ok, thanks for your suggestion.
