### ISSUE TITLE
[flash_ctrl] ECC handling

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#4812]
Need to think about differentiation between instruction and data for flash ECC errors. 

Right now, when a correctable ECC is encountered, it is fixed and passed on.
When an uncorrectable ECC is encountered, an error is passed back upstream. 

However for file system data, the software needs some idea that the flash is error'd and now needs to be erased.
I would prefer to not differentiate between instruction and data accesses on the flash.. although we can do that too.

Would it be sufficient to just expose the fact there was an error and leave software to handle the rest? The fact there has been an error should be enough for software to know that data needs to be erased.  If the instruction is corrupted, the next signature verification will never work anyways, so there needs to be another higher level recovery mechanism.

**Comment by rswarbrick** [comment]
Presumably if this was an instruction fetch, the processor is going to get stuck shortly. Can we differentiate by triggering a fatal alert in the software for the relevant exception vector?

**Comment by tjaychen** [comment]
@msfschaffner 
that's actually a very good point, i'm not sure at the moment there is a way for software to trigger an alert.
Michael I quickly glanced at the spec, and i didn't see explicit mention of being able to do this.  I think it actually would be helpful for software to have an easy way to trigger the alert system also.

**Comment by tjaychen** [comment]
actually backing up, @rswarbrick it might more sense for this alert triggering to be in flash_ctrl.
So flash_ctrl can capture the fact there was an uncorrectable ECC error, and software can decide whether to full-on trigger the alert. 

That way we still get I / D differentiation, and it is still in software control.

**Comment by msfschaffner** [comment]
Yeah at the moment there is no direct way to trigger an alert through the alert handler CSRs.
But I think it would be better to add this additional trigger CSR to the IP under consideration for alert classification reasons (i.e., the alert handler can tell that the flash controller was the origin, and bin it accordingly).

In your model, would we still be sending out recoverable alerts for both ECC cases, or would we entirely rely on SW to decide whether to trigger an alert or not?

**Comment by tjaychen** [comment]
i think we need to leave the choice to software since the behavior will be somewhat different for instruction or data.
For instruction, they probably want to trigger the alert and kill the system (or do a manual reboot without the alert).
For data, it's actually could be part of normal flash clean up as Ziv pointed out, and we just need to go in and erase.

**Comment by msfschaffner** [comment]
Right, we will likely have to leave that choice up to SW.

I guess what I was trying to say is... should we still send out recoverable alerts for both ECC error types such that the alert subsystem can react with an escalation protocol in cases where the processor does not respond in time?

The decision to double down and make ECC uncorrectable fatal can then still be left to SW.
I guess we could directly go and manually reset the chip in that case, since SW is already involved (although that would lead to a different reset cause, and not all countermeasures would be triggered).

**Comment by tjaychen** [comment]
yeah it does not hurt to at least connect up the recoverable alerts.  Because then we at least have the choice to have an alert system response.

**Comment by zi-v** [comment]
I think it is more accurate to refer to ECC errors on 'fetch' vs 'read' because in FW update for example, code is actually treated as data.
Anyway, I agree with the notion that a flash_ctl driven immediate NMI is good for fetch (preferably triggered before the errored fetch is executed, otherwise, other unexpected stuff, including other exceptions/NMIs may happen) . If flash_ctl can do the distinction, I think it is better to limit this NMI to errored-fetches only because such NMIs may have a destructive nature (because NMI brutally stops everything else without distinction, even atomic code portions that run with interrupt-disable).

**Comment by tjaychen** [comment]
hey ziv,
just to clarify a bit how this works (and to combine some of @msfschaffner thoughts).

When performing an instruction fetch and there is an ECC error (uncorrectable), an error will be sent back to the processor. 
The processor then as @rswarbrick mentioned, will jump into exception handling.  In that exception handling, we will know that it is an instruction error, and from there we can choose a software response to trigger a fault alert (or take some other action, software can just as easily reset).  If there is more code that is bad (because it was a massive glitch), I think most likely the software will just die, and we will have to recover through watchdog. 

We could do something more fancy and trigger some kind of error timeout, but I don't really think that's worth doing. 

And to your point, yes this is only error-fetches and not error reads.  The ibex has separate instruction and data ports. So code being treated as data actually will manifest as a different kind of error.   It is actually a larger question what BROM should do when in the process of verification it encounters an error.  If the software is A/B copy, I imagine it should simply jump to the other copy, but this is worth discussing in a separate thread.

**Comment by zi-v** [comment]
Tim, thanks for the detailed explanation. My point is that the exception jump itself, if unaskable, imposes a system risk. If maskable, no guarantee it will be executed before the errored code. 
That's why I proposed to make the exception unaskable and to limit it only to the fetch case. The data error can be a regular interrupt and can be handled by software. Regardless, maybe we can have a status register with the last ECC errored address(es).
BTW if a flash word is completely screwed, there is a non negligible chance that the ECC will look correct (or at least correctable) so I don't think we can rely on the exception mechanism for bad data detection.

**Comment by rswarbrick** [comment]
Maybe I'm missing something, but I thought this was a discussion about an instruction fetch that fails an ECC check? In that case, Ibex will fault precisely. The bus will have returned an error (with no data), so there isn't an instruction for the processor *to* execute.

**Comment by tjaychen** [comment]
sorry Ziv, I'm not quite sure what point you're making.

I'm in agreement with Rupert, the instruction error line is not "maskable".  The ibex will fault upon seeing this error and it will not execute the bad instruction.  Was that your concern?

And yes, data errors (not the instruction fetch port) will have to be handled differently.  I'm actually not completely sure a data error (and hence another exception is the programmers model software wants to know that it needs to do data clean up, but I will chase that down separately).

**Comment by zi-v** [comment]
If {unrecoverable errored fetches cause non-maskable interrupt} and {unrecoverable errored other reads cause regular interrupt} then it is OK.
The point I was trying to make is that I think should avoid the case of {unrecoverable errored non-fetch reads cause non-maskable interrupt}.
If this is how both you and Rupert see it, then we are aligned.

**Comment by tjaychen** [comment]
maybe i should clarify, Rupert please correct me if this is wrong.

Bus errors, whether it's on the instruction port or the data port BOTH
cause exceptions (not sure if they're both precise, I think data might not
be).
So in that sense they are both "non-maskable".

So the downstream behavior, as controlled by the exception handler is
really what determines what will happen next.
The exception handler is obviously yet another piece of code, so if that
code errors too, my thinking is that the chip will basically just die and
wait for a watchdog.
But if not, then we will have the flexibility of following software
dictated behavior.

Assuming the exception handler does not error, then it can choose to make
the instruction errors terminal, or it can choose to have some kind of
recovery behavior (which is likely what we would need for data errors).

**Comment by zi-v** [comment]
Non-maskable exception by itself breaks the code flow because it bypasses the interrupt masking mechanism (even if the exception itself it is not errored). If a code section applies 'interrupt disable', it is usually done so for a reason and I think it should be honored as much as possible. I don't see a reason to break it in the case of ECC errored data (not-fetch) which can use regular interrupt.

**Comment by tjaychen** [comment]
I'm not sure I completely agree.
Especially for instruction ECC errors, I do think there needs to be some
kind of clear cut response.  Otherwise without an error, it means the cpu
may consume bad code, and that behavior would be unpredictable (although
most likely to be decode error)
For data reads, I definitely agree with what you're saying.  And I am
thinking (for other reasons also) that it might make sense to suppress the
error there.

What sort of atomic operation are you worried about though Ziv? In my mind,
the only thing that really matters is the non-volatile memories.
And I thought for those we have all checked the interrupted conditions?
It is true that if we are in the middle of a flash update something may go
completely haywire, but those errors can happen in general and should be
covered by higher level protocols and not hardware.

**Comment by zi-v** [comment]
Regarding "for instruction ECC errors, I do think there needs to be some kind of clear cut response": I agree.
I thought the debate was on non-fetch reads. If we agree that non-fetch reads should be handled with regular (maskable) interrupt, then we are in line.

**Comment by tjaychen** [comment]
ahh okay.
So maybe we've been talking in circles :)

Yes, for non-fetch reads I do plan on handling this differently and not
require exception handler entry / exit (that's not exactly a nice software
programmer model).
There is a larger proposal involving all of this, I hope to share it with
everyone soon.
