### ISSUE TITLE
May I use the vip_uart_svt_O-2018.09 Verification IP from Synopsys. Inc to verifiy the ip of uart(lowRISC/opentitan)?

### ISSUE THREAD

**Issue by JmheYouzi** [lowRISC/opentitan#4867]
https://github.com/lowRISC/opentitan/tree/cce60945e7bd169095a1976d40c489ddfc018c8d/hw/ip/uart

 Can you give me some suggestions or  help?

**Comment by sriyerg** [comment]
The main goal of OpenTitan is to remain as open source as possible. Hence, we build our own UVM agents (which are also freely available) rather than use something off the shelf. 

If you wish to use proprietary VIPs, the testbench can no longer remain in the open source domain - you will have to develop and maintain it privately in your workstation because no one else will have the licenses to compile / run simulations with the VIP. Plus, you will need permission from Synopsys to put pieces of their proprietary code in an open source repo, given that there are multiple competing VIP vendors out there. Just by pasting the image above, you could be violating some terms and conditions with Synopsys! The use of anything proprietary goes against the nature of open source.

It will be good to understand though, what is the need for this. The UART agent used in this testbench already ships with the repo:
https://github.com/lowRISC/opentitan/tree/master/hw/dv/sv/uart_agent

If you feel there are key features lacking in the agent (I am sure we could write more covergroups), I will instead encourage you to contribute to the code and make enhancements as needed.

**Comment by JmheYouzi** [comment]
Thank you very much for your kindness!

**Comment by sriyerg** [comment]
BTW, UART IP is fully verified with UVM testbench here:
https://github.com/lowRISC/opentitan/blob/cce60945e7bd169095a1976d40c489ddfc018c8d/hw/ip/uart/dv/uart_sim_cfg.hjson

We run nightly regressions on all of our IPs, including the full chip. The results can be found here:
https://reports.opentitan.org/hw/top_earlgrey/dv/summary.html

**Comment by JmheYouzi** [comment]
Thanks a lot !
