### ISSUE TITLE
[verilator/sw] "Program header number is not of type PT_LOAD" with clang builds

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#4884]
When building the device software with clang, I see the following warnings when loading the ELF files into Verilator:

```
Program header number 3 in `build-bin/sw/device/boot_rom/boot_rom_sim_verilator.elf' is not of type PT_LOAD; ignoring.
Program header number 3 in `build-bin/sw/device/tests/dif_otbn_smoketest_sim_verilator.elf' is not of type PT_LOAD; ignoring.
```

They are not harmful (it seems). But we should see if we want to change the compiler/linker settings to better match what GCC produces, or downgrade/remove the warnings in the Verilator memory loader.

**Comment by rswarbrick** [comment]
I suspect this is just debug info. Since the segments aren't marked as PT_LOAD, they won't have any effect. The warnings are a bit ugly, but can be reasonably helpful if something has come unstuck. I'd probably favour leaving them in for now (since we're not triggering them with the usual builds).

Closing because I don't think we're going to take action on it. If anyone wants to hack on this in the future, look at `FlattenElfFile` in `dpi_memutil.cc`.
