### ISSUE TITLE
[hmac] Add support for SHA / HMAC context switch

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#49]
can i make a wishlist request (long term)? This is something that's come up a few times. It seems that a lot of software use cases end up in a situation where multiple threads want to use the SHA engine at the same time. However, if each is using the engine to SHA an indeterminate amount of data, it means that the SHA engine itself needs to context switch (ie, a thread cannot hold on to it forever). So it would be nice to be able to save SHA context and restore another to proceed with data dumping. 

Just something to think about. Even if we don't need it, I am sure someone in the OT community will eventually.

**Comment by sjgitty** [comment]
On a mission to clean up old issues, scraping from stalest to freshest.

I think we can close this as it is being tracked in the 2020 planning for HMAC
improvements, unless @eunchan you would prefer to keep it open until the
specification is updated?

**Comment by tjaychen** [comment]
it may be helpful to confer with Chris / Felix on how useful they think
this is.

**Comment by cdgori** [comment]
With Scott's suggestion that sideloading prevents context-saving/swapping, I think it's interesting and pretty safe to implement.  

But as to whether we need it or not, I don't have a good sense of the workloads we expect, and if two SHA'ing "threads" are going to be contending for the hardware.  @tjaychen you said this came up in the past, so I'm assuming it's real, but maybe an example would help.  (The one I imagine right away is verifying integrity on a boot image or some other huge structure but needing to be able to do various housekeeping stuff like ACKs/responses to messages that require hashes, and blocking on the huge-payload hash would make this hard/impossible.)

**Comment by tjaychen** [comment]
Yes your description of where this came up is right.  Except the difference
is that the "huge payload" was actually coming off-chip from another
client.  This client does not provide information on exactly how much
information needed to be hashed, other than periodically supplying data and
eventually a "done".
Because of this, there was no good way of knowing when to release the
hardware and use it for internal house-keeping things.  I cannot remember
if this was a usecase in production, or something someone thought could
happen and thus had to design for (I feel like it's the second)

**Comment by sjgitty** [comment]
This is evidently a real case scenario in a certain product whereby they're
forced
to use SW hash / HMAC when the HW unit is busy. Unfortunate situation that
could
be alleviated with this feature (assuming it is worth the cost).

**Comment by cdgori** [comment]
I feel a little ... conflicted then.  

If there is truly a need for an "interrupting" / quick HMAC (rather than just a SHA), where would the key for the interrupting HMAC come from?  If we disallow context switching when sideloading then the implication is that will be a SW-managed/held key, which I'd prefer not to rely on / force usage of.

Handling context swapping/restoring with sideloaded keys is definitely opening a much bigger can of worms though.  It's hard for me to balance these two things out, unless we understand the use-case better, I think.

**Comment by sjgitty** [comment]
I believe the use case is a) processor-given key for HMAC (or even keyless
SHA-256) is active on a large hash
task; b) secure-given key is requested for HMAC. In this scenario, task a)
is interrupted with a save of the
internal state, task b) is allowed to proceed, then task a) does a restore
and continues. This seems safe in
that task a) is not exposing anything secret via the save/restore process,
and task b) is un-interruptable.
wdyt?

**Comment by tjaychen** [comment]
Personally i think we still need to find a way to make the secure-given key case context switchable. 
If we for example require the secure case to not be switchable, it would restrict it to a smaller number of use cases.  That might lead to a user eventually deciding to abandon the secure use case altogether and just do everything in SW.  

I definitely get Chris' point there are dangers in allowing the secure case to be context swapped.  But I think it makes sense to closely examine those risks and find a way to make it usable (with some restrictions that the software would need to manage) - ie, always accumulate to one block size before pumping it into hardware.

**Comment by cdgori** [comment]
Scott's example does not present too many risks to me, since the context-switched-out operation is using a non-sideloaded key.   (If we stick to some rule that says that sideloaded keys are non-context-switchable that makes the analysis very simple.)

Tim's comment that we might need to figure out how to make a sideloaded key context-switchable will require a lot more study.  (but he is correct that if we make conditions for using sideload too restrictive such that no one uses it, we have failed.)

For sure doing things on a block boundary is going to be a good idea.   I think that most of my concerns will be handled if we do a good job of random-wiping the context-swap-storage area after the "pop" from that stack happens, or possibly before the "push" onto that stack.  

(I think most of the pathological cases that my spidey-sense is worried about come from crafting special messages to HMAC and triggering the context switch such that a known-intermediate-key overwrites an unknown-key in a way that leaks information about that unknown-key, but there may be others I have not considered.)

**Comment by tjaychen** [comment]
After discussing with the software teams, this sounds like it would be a very nice feature to have.
However, I don't think this should be milestone gating and can theory be something we add for production.

In any case, there are clear software workarounds. 

How does everyone think about this? We can hopefully defer the issue until later.

**Comment by sjgitty** [comment]
(I think this holds for KMAC context switch too.)

My 2c is this falls into the category of post-ES "improvements" that we can consider for production. We have too many of these nice-to-have features that we're still considering that we need to get off the fence on. IMO it falls into the bucket of "not needed to prove analog / certification / tricky product features" therefore goes into that bucket of post-ES. But I'm on the side of enlarging that bucket, and we should run this by SW, CB, and Dom to get their opinion on it. @domrizz0 @gkelly @mdhayter

**Comment by tjaychen** [comment]
yes we had an initial conversation with CB. And that conclusion was that kmac context switching is not necessary (see #3479 
HMAC context switching on the other hand, is very nice to have.  However everyone acknowledges it is not a must have.

**Comment by tjaychen** [comment]
this issue has already been clarified in other issues and can be closed.

**Comment by eunchan** [comment]
Re-open this issue as discussed in #13497

**Comment by cdgori** [comment]
Most of my earlier comments/concerns are reduced/eliminated (for HMAC) because we decided to not implement sideload.  Thus, the key material is software-originated/observable in all cases by the processor, regardless of context switch.  Software does probably need to take best-effort care to compartmentalize access to individual HMAC keys though.

KMAC context switch (if used/allowed) needs to be carefully considered because all of my concerns about leaking sideloaded keys are applicable then.  My comments about block boundary and random wipe are probably the minimum necessary to allow this, we might be able to do better.

**Comment by jadephilipoom** [comment]
> @jadephilipoom Do we have use cases of multiple concurrent HMAC/SHA2 hashing operations? What we discussed and concluded was `no`. So, we expected HMAC/SHA2 may be locked up if the message length is unknown. That's why HMAC control flow was changed from 'explicit length configured by SW' to 'streaming (start -> process)'.

There are definitely concrete use cases for this for the OS-visible cryptolib. Concurrent HMAC operations are required in order to comply with the TPM specification, for instance -- of course levels higher up can create software implementations, but if they want to use the hardware they do need save/restore for some cases.

**Comment by eunchan** [comment]
> > @jadephilipoom Do we have use cases of multiple concurrent HMAC/SHA2 hashing operations? What we discussed and concluded was `no`. So, we expected HMAC/SHA2 may be locked up if the message length is unknown. That's why HMAC control flow was changed from 'explicit length configured by SW' to 'streaming (start -> process)'.
> 
> There are definitely concrete use cases for this for the OS-visible cryptolib. Concurrent HMAC operations are required in order to comply with the TPM specification, for instance -- of course levels higher up can create software implementations, but if they want to use the hardware they do need save/restore for some cases.

Thanks for the response Jade. OK. Let's aim to implement this in next release.

**Comment by tjaychen** [comment]
@eunchan, @jadephilipoom and I had a quick sync on this topic.  The short term conclusion is that this is not worth doing right now as there are software alternatives.

Longer term, the issue is a bit more nuanced.

It is relatively simple to add the context save and restore feature, however, the current HMAC engine is unhardened.  This makes not only HMAC, but SHA-256 vulnerable to attacks (Jade explained that could be specifically vulnerable to extension attacks).

So if we do want to add context save and restore in the future, we should also think about adding hardening. Otherwise we'll need to somehow distinguish between the use cases that need hardening vs those that do not. 

In addition, we should also look into the performance of the software driven hardened SHA on otbn. If this is performant enough, in the long term we could also think about moving away from a dedicated HMAC engine altogether. 

@johannheyszl / @moidx / @msfschaffner FYI

**Comment by jadephilipoom** [comment]
> It is relatively simple to add the context save and restore feature, however, the current HMAC engine is unhardened. This makes not only HMAC, but SHA-256 vulnerable to attacks (Jade explained that could be specifically vulnerable to extension attacks).

To elaborate on this a bit: if you're hashing a secret value, and the attacker sees your SHA-256 hash state, the attacker can produce the hash of <secret value> || <something else of the attacker's choice>. This is definitely a bit of a niche attack vector and not a huge concern, but it's just to say that under certain circumstances it's possible for an attacker to take advantage of knowing the hash state, especially if the hash function is being used improperly.

**Comment by msfschaffner** [comment]
Related: https://github.com/lowRISC/opentitan/issues/5058

**Comment by johannheyszl** [comment]
agree that read access to SHA-256 state would require hardening in the sense of careful logical restrictions against extension attacks (i.e. through misusing the SW interface and potentially circumventing SW isolation).

agree that hardening against SCA etc. (physical attacks) is another (orthogonal) issue when processing secrets in SHA-256 (i.e. for HMAC computation).

**Comment by jadephilipoom** [comment]
After some more thought, an even worse case than a length-extension attack is the fact that, if you're hashing secret data (as you would be for HMAC, since you hash the key), the internal hash state after e.g. only one round would leak information about the secret data.

**Comment by johannheyszl** [comment]
It is my understanding that, if needed, a context switch is easier to add to the SW SHA-2 implementation and given the security implications, we currently don't plan to implement it for the HMAC IP.

**Comment by jadephilipoom** [comment]
Hey, I actually really do want this feature!

**Comment by jadephilipoom** [comment]
A lot of APIs require the ability to have an init/update/final interface for hash functions and HMAC, and a hardware implementation is much faster than software. Even if we wouldn't use it for hashing secret values, the majority of hashing use cases are for non-secret values and a hardware implementation would be extremely beneficial. For cryptolib, for example, we can barely use the HMAC block at all because this context swtich feature is missing. We can use it for one-shot hashing, but for init/update/final it doesn't work because a badly behaved process could lock up the HMAC block by not finishing the hash or HMAC it started.

**Comment by johannheyszl** [comment]
We currently plan to implement, @gdessouky

**Comment by andreaskurth** [comment]
As just discussed out-of-band with @jadephilipoom and @gdessouky, we think it's sufficient for the HMAC/SHA2 HW to support switching between two data sequences once a block (512 bit for SHA-256, 1024 bit for SHA-384/512) has been hashed. That way, SW only has to save & restore the intermediate hash value (stored in the digest registers) and the current message length. If context switching at finer granularity would have to be supported in HW, the HW change would be far more complex and SW would have to save & restore more HW-internal registers, including the working variables and the message schedule counter. Limiting context switch to block granularity should be easy enough to handle in SW by buffering data in memory up to a block is full and then passing full data blocks to the HMAC/SHA2 HW IP.

**Comment by andreaskurth** [comment]
Closing as completed in #21307.
