### ISSUE TITLE
[alerts] Need for gating alert cause registers with life cycle

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#4902]
Split out from #3767:

During the Q&A session as well as in PR https://github.com/lowRISC/opentitan/pull/4781#discussion_r554118992 we have been discussing that we should probably guard the error/cause register giving more details on the alert source with a lifecycle signal. DEV, RMA, TEST_UNLOCKED were mentioned as states in which those regs should be accessible. It was also mentioned that we should get more input on this from the labs.

**Comment by rswarbrick** [comment]
For IPs that are programmed by software before they're first used, another option would be a one-way "you're in production mode now" register. That way, not every IP block would need a connection to the lifecycle controller, making things a little less rat's-nestish. I raised #4519 a while ago to discuss this for OTBN (but there hasn't been further discussion yet).

**Comment by weicaiyang** [comment]
we have a `devmode_i` to control if TL error will be returned for unmapped address. We enable this kind of TL error in development mode and hide this info in production mode. It seems to serve the same propose as we need here. Perhaps we can consider to reuse this signal.

**Comment by cdgori** [comment]
I thought `devmode_i` was only for DEV.  This needs DEV | RMA | TESTUNLOCK.

@rswarbrick I am actually accustomed to this being a little rat's-nestish - if each block takes in the lifecycle state vector and decodes it locally there's less of a central place to glitch for these kind of permission gates.  (Obviously the registers in LC that drive the state vector are the primary concern but that's where we would/should put the majority of our countermeasures/detectors anyway.)  I could certainly be convinced that having LC pre-decode some of these is OK too though, since it guarantees consistency of application.

**Comment by weicaiyang** [comment]
> I thought devmode_i was only for DEV? This needs DEV | RMA | TESTUNLOCK.

just feel a bit of waste if devmode_i is only used to gate the unmapped address error. it will be nice if we can consolidate them to gate the unmapped address error and alert cause together.

**Comment by rswarbrick** [comment]
@weicaiyang: I agree. I would have thought the unmapped address behaviour should be the same as the "expose alert cause" behaviour. Am I right in thinking that `devmode_i` isn't actually wired up anywhere yet? `git grep '\.devmode_i'` shows everything wiring it up to a constant `1'b1`.

**Comment by tjaychen** [comment]
yeah devmode_i really needs to be hooked up to lc_hw_debug_en or something
along those lines.

**Comment by tjaychen** [comment]
btw regarding the alert cause i don't think we can actually qualify them with life cycle. 
I'll try to write a more thought out response later.

**Comment by msfschaffner** [comment]
`lc_hw_debug_en` for the `devmode_i` signal is I think the correct life cycle signal, yes (DEV, RMA, TEST_UNLOCKED*).
@cdgori is this something that should only be connected to specific peripherals, or should we connect all CSR nodes in the system?

**Comment by cdgori** [comment]
I don't have a strong opinion either way.  

The concerns would be:
(1) A local fault causes one module to believe `lc_hw_debug_en` is falsely asserted when it isn't, in a module that has different behavior based on the value.  This is basically unavoidable as a possibility
(2) Same thing but the module ignores the value of `lc_hw_debug_en` because it doesn't have different behavior.  At that point the fault is irrelevant (?)
(3) Somehow an induced local fault from case 2 back-propagates to LC module central generation of `lc_hw_debug_en` and influences other consumers of the signal that are in case 1.  This is pretty unlikely (to me) because physically the buffer/inverter trees should suppress this kind of propagation.

Normally one is worried about two modules interpreting any signal differently due to a local glitch, but here the actual implication of the signal being falsely asserted is more critical than the split interpretation problem (to me).

@msfschaffner Is there a big advantage to connecting it to all CSR nodes, even ones that don't consume it?

**Comment by msfschaffner** [comment]
Thanks for elaborating this. My thoughts:

(1) We try to guard against that by making the value multibit up to the point where it is consumed.
Not sure it makes sense to do more than that. 
(2) should be irrelevant, I think. 
(3) I do not think back propagation is an issue here due to the life cycle synchronizer regs and buffers. 
 
Connecting it to all CSR nodes would make the design more uniform - after all, all CSR nodes expose this signal, and the decision whether or not it is actually consumed depends on the CSR node's local address map. I believe most of these address maps have "holes" somewhere at the end of the address space, so I think it does make sense to connect the signal to all CSR nodes.

**Comment by tjaychen** [comment]
i think this is related to the recent `devmode` discussion that was had. So for the purposes of "this" iteration, we probably want to keep the alert cause readable by software.

**Comment by rswarbrick** [comment]
Ok, I think that's what the design does at the moment too. Is there any more discussion needed here or should we close the issue?

**Comment by msfschaffner** [comment]
We probably want to come back to this in a future iteration. So let's leave it open and label it accordingly.

**Comment by gdessouky** [comment]
Triaging for `lc_ctrl`:

Summarizing this discussion and discussion from referenced issues, currently `devmode_i` is hardwired to 1 so that software always receives an error in the event of an access to unmapped space. This indicates the device is in DEV mode and allows that the error response is visible to the software. It might be ideal for security peripherals in production mode to not send out an error response, so that write misses silently fail, and read misses silently fail, and return random data for instance. Otherwise, TL-UL error response is returned. 

This [#10311](https://github.com/lowRISC/opentitan/issues/10311) here indicates that  "it was decided that for OpenTitan's "current usecase", there is no need to hide the tlul error from software. Further, exposing these errors may be beneficial for in the field debugging. For future usecases, this question should be re-examined as it may be a very reasonable choice to lock down the error response and indication."

Are we now for M2.5 in such a future use case where it makes sense to lock the SW-visible error response in PROD mode to eliminate side-channel information on accessing unmapped space?

It is suggested above (and [here in comments](https://github.com/lowRISC/opentitan/pull/4781)) that we can do this by tying `devmode_i` to `lc_debug_en` and guarding the error/cause register giving more details on the alert source with this signal? This would make the error details visible to SW only in DEV/RMA/TEST_UNLOCK modes.

**Comment by gdessouky** [comment]
Summarizing after an offline discussion, there is not much security gain or even necessity to obscure the errors from software irrespective of life cycle state. An FI attacker would figure things out still eventually, even if there is a silent fail and random data is sent back over TL-UL. Secondly, In OT, with open architecture and implementation, obscuring the error from software does not help either. Engineering effort required would be heavy on DV side, and usability and diagnosis for a benign user will be hampered.

**Comment by gdessouky** [comment]
Does it make sense to close this issue now @GregAC?

**Comment by GregAC** [comment]
Yes I think so @gdessouky thank you for looking into this.

**Comment by cdgori** [comment]
Thank you for summarizing.  

While I agree with the statement that 
|An FI attacker would figure things out still eventually via other side-channel means even if there is a silent fail and random data is sent back over TL-UL
there is sometimes still security value in making it more difficult.

But, I think that the marginal value of that increased difficulty has to be balanced against the annoyance factor / loss of usability / extra DV effort that you described, so this is a reasonable trade-off to me.
