### ISSUE TITLE
[mem_ctrl] Add characterization counters

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#5186]
In an effort to find out how much "slow" byte writes can impact our system performance, add some characterization counters into mem_ctrl for sram.

The counters should register the conditions that would have caused a stall assuming ECC is implemented, as well as the number of stall cycles based on those conditions.

**Comment by tomroberts-lowrisc** [comment]
As a minor clarification, it could maybe be rephrased to "sub-word writes" since half-word writes will also incur the same penalty.

**Comment by tjaychen** [comment]
o yes good point. Thank you.

**Comment by msfschaffner** [comment]
@gkelly did a statistical analysis of existing application code intended to be run on OpenTitan and concluded that only a very small fraction of memory accesses are actually byte writes. The performance impact of slower byte writes in case of ECC is therefore very small, hence the use of ECC on SRAM (instead of byte parity) is considered feasible, and we've decided to move forward with that.

Going forward, the performance impact of byte writes can also be taken into account when writing new code.

@tjaychen @moidx I cannot find the raw statistics at the moment. do you happen to have access to those numbers?
if so, can you attach them to this issue and close it?

**Comment by tjaychen** [comment]
I think the original analysis was done over some proprietary code, so it's
probably not best to attach them here.
Chris is there a forum where we should raise this? Maybe at the next
software meeting for long term data collection on the open source side?

**Comment by msfschaffner** [comment]
This is obsolete by now.
