### ISSUE TITLE
dvsim enhancement for fixed-seed and max-parallel arguments 

### ISSUE THREAD

**Issue by sha-ron** [lowRISC/opentitan#5285]
Currently  fixed-seed and max-parallel arguments can be used only from command line, it will be helpful to be able to define it also from hjson file.
@sriyerg

**Comment by rswarbrick** [comment]
I think the point is that the hjson file describes something parameterised by the seed: if you want a specific seed, it doesn't seem unreasonable to say so. I suppose we could do something like specifying the "start seed" in the hjson file, but that feels like it works against the usual flow, which is to try to explore as much of the search space as possible.

For max-parallel, I *really* don't think this should appear in the hjson file. It should have no effect on the results, and should be set depending on the machine you're on. Another person running the same hjson config will probably want a different value. There's an environment variable (`$DVSIM_MAX_PARALLEL`) that you can set in your bashrc to avoid killing your machine / licence server.

**Comment by sriyerg** [comment]
Hi @sha-ron,

[I had typed up my response but forgot to hit send. This echoes / adds a bit to what @rswarbrick already said.]

The max parallel setting is work-site specific - at Google, we can run a large number of simulations at a time so our max-parallel setting is quite large. DVSim does read the `DVSIM_MAX_PARALLEL` setting in case it needs to be set for all users in a particular partner site. Typically, this would be set to the number of simulator licenses you are willing to allow a user to checkout at a time to keep the usage under control. 

You can set `export DVSIM_MAX_PARALLEL=N` before invoking DVSim so that you don't need to specify the `-mp / --max-parallel` switch every time. 

As for the `--fixed-seed` it is really a command line override. The default behavior is to always pick a completely random seed to maximize the design state space. If you want to rerun a failing simulation with a specific seed, you can set `--seed <seed-num>` on the command line. Could you remind me again, what would be the value of allowing this to be set in the HJson?

For both of these, I feel it is better to not allow them to be set in the HJson because if it gets set and overlooked, it affects the simulation performance for other OT partners.

**Comment by sha-ron** [comment]
@sriyerg @rswarbrick 
We don’t have many VCS licenses so if someone forgot to set the –max-parallel it would disturb other users. I wasn’t  aware of DVSIM_MAX_PARALLEL option, will try it.
I wanted the fixed-seed for the AST since I thought it will be more comfortable for the users during development, for massive runs I/they can change it.
But I see what you and Rupert say about the coverage and I understand your concern about it being overlooked so maybe indeed better not to have this option.

**Comment by rswarbrick** [comment]
> We don’t have many VCS licenses so if someone forgot to set the –max-parallel it would disturb other users. I wasn’t aware of DVSIM_MAX_PARALLEL option, will try it.

That option got added after I ate all the lowRISC VCS licenses once too often :-)

**Comment by sha-ron** [comment]
hhh.. that's how you get to the most useful stuff:) Tried it and it works so I guess we can close this issue. thanks
