### ISSUE TITLE
Register overview table

### ISSUE THREAD

**Issue by towoe** [lowRISC/opentitan#5297]
I was just playing around with creating an overview table for the registers for IPs.
I hated to scroll around to find the offsets and this makes it also more obvious to know what registers are available.
Would like to have some feedback if something like this would be nice to have? And if yes, any wishes?
(Currently this does not work for pinmux, the shortcode processing with Hugo has same "file too big" issue.)

![2021-02-18-230609](https://user-images.githubusercontent.com/8666134/108427943-2ccb6c80-723e-11eb-8062-9dc29183cd30.png)

**Comment by rswarbrick** [comment]
I really like this! I'd suggest removing the title ("uart") from the register table, since it's going to appear in the block's document anyway. Also, maybe we don't need the length field, since most registers are going to be 4 bytes wide. I wonder what it looks like if we prefix the description with the width when it's bigger (for memory windows, essentially).

**Comment by cindychip** [comment]
I like this one too, Thanks for suggesting this! For modules that have many registers, it is browse them all.
I agree with Rupert that we maybe can remove the `uart` title, but i think the `length` might be useful to show memory size?

**Comment by msfschaffner** [comment]
@towoe this looks like a nice addition, I also found myself in the situation where I was scrolling endlessly until I actually found what I was looking for. Would you mind prepping a PR for this so that we can get this into our docs?

**Comment by timothytrippel** [comment]
+1, this is a great idea!

**Comment by msfschaffner** [comment]
This has now been implemented - closing.
