### ISSUE TITLE
Unable to query or set MCOUNTEREN CSR on Ibex CPU on Nexys Video FPGA

### ISSUE THREAD

**Issue by gemarcano** [lowRISC/opentitan#5322]
Is the MCOUNTEREN CSR defined/implemented on the Earl Grey CPU? As far as I can tell, the MISA register indicates that there is U mode support (as expected), and as such I thought this required MCOUNTEREN support, but trying to access this register leads to illegal instruction exceptions, even from M mode.

I tried accessing the CSR through a kernel (Tock) and also just plainly from GDB while in M mode (through OpenOCD), to no success.

**Comment by vogelpi** [comment]
Hey @gemarcano ,
thanks for opening this issue. This is actually an issue related to Ibex and not primarily OpenTitan and thus best discussed in the Ibex repo. I've filed an issue over there, see lowRISC/Ibex#1278.

Regarding the actual issue, I think you are right. The register should at least be readable as all 0. But let's discuss in the Ibex repo. I am closing the issue here.

**Comment by vogelpi** [comment]
Let's keep this open until it got actually fixed also in OpenTitan.

**Comment by vogelpi** [comment]
I forgot about this. The fix has been vendored into OpenTitan a long time ago. Thus closing the issue now.
