### ISSUE TITLE
[lc_ctrl] Connect all life cycle signals on the top-level

### ISSUE THREAD

**Issue by msfschaffner** [lowRISC/opentitan#5462]
There are still a few life cycle signals that need to be hooked up on the top-level:

- [x] `lc_keymgr_en_o`, https://github.com/lowRISC/opentitan/pull/5437
- [x] `lc_cpu_en`, https://github.com/lowRISC/opentitan/pull/5437
- [x] more `lc_escalate_en` connections?
- others?

Also, some life cycle signal connections need to be modified:

- ~~[ ] replace `lc_dft_en` by `lc_nvm_debug_en` in OTP?~~
- [x] replace `lc_escalate_en` by `lc_cpu_en` in the always ON timer, https://github.com/lowRISC/opentitan/pull/5480
- others?

**Comment by tjaychen** [comment]
yeah, replacing aon_timer with `lc_cpu_en` makes sense to me.
I can quickly do that PR since Tom might be really busy with other things at the moment.

**Comment by msfschaffner** [comment]
Great, thanks!

**Comment by msfschaffner** [comment]
@tjaychen how do we want to proceed with `lc_nvm_debug_en` for OTP?

**Comment by tjaychen** [comment]
i don't see any specific reason why otp needs to make use of
lc_nvm_debug_en.
There doesn't appear to be a use case right now where otp gets a secret
injected that needs to be hidden from the tester.

I think I might later re-name this signal to be more flash specific, ie
`lc_flash_debug_en`, since there is a specific need in that case.

**Comment by msfschaffner** [comment]
OK sounds good.
In that case I think we can close this issue.
