### ISSUE TITLE
[verilator] Running more than one verilator model concurrently segfaults

### ISSUE THREAD

**Issue by gkelly** [lowRISC/opentitan#562]
As reported by @mcy in #524, you cannot run multiple concurrent verilator models.

**Comment by asb** [comment]
Copying from #1183:
There are issues with this due to devpts and fixed TCP ports (see e.g. #1155). Although both can be worked around with application of isolation technology like Virtual Machines or containers, this is a far from ideal solution. It should be possible to run multiple OT verilator instances in parallel on a single user account without a container for each one.

Multiple solutions are possible, e.g. using Unix Domain Sockets rather than TCP, cycling through TCP ports until an available one is found etc etc.

**Comment by tjaychen** [comment]
i think this has long been addressed.  Can probably be closed now.
