### ISSUE TITLE
aes block doesn't reset with idle_o set

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#5646]
After POR the AES block's idle_o output is 1'b0, yet the ctrl fsm is in the IDLE state. In addition, the equation setting idle_o in aes ctrl fsm is
      IDLE: begin
        idle_o    = (start_chk == SP2V_HIGH || key_iv_data_in_clear_i || data_out_clear_i ||
                    prng_reseed_i) ? 1'b0 : 1'b1;
        idle_we_o = 1'b1;
and it turns out the last three terms in the condition of the ternary expression in the rhs of idle_o are 1.

**Comment by matutem** [comment]
![Screenshot 2021-03-16 18 21 33](https://user-images.githubusercontent.com/80294896/111400414-862f8b80-8684-11eb-9245-28d958407eaf.png)

**Comment by sriyerg** [comment]
Looks like there are a couple of factors (branches in terms of design coverage) that affect the clk idle signal. I suppose it got added in the design after the AES testplan was last reviewed. Please consider adding and entry for it:
https://docs.opentitan.org/hw/ip/aes/doc/dv_plan/#testplan

Thanks!

**Comment by vogelpi** [comment]
Hi @matutem ,
thanks for opening the issue. This is actually intended behavior: The reset causes the KEY_IV_DATA_IN_CLEAR, DATA_OUT_CLEAR and PRNG_RESEED bits in the TRIGGER register to be set to 1 (see the aes.TRIGGER in the [register table](https://docs.opentitan.org/hw/ip/aes/doc/#register-table)). As a result, the main controller FSM will reseed the PRNG and then clear key, IV, and data registers with pseudo-random data. This process will clear the bits in the TRIGGER register. Once it has completed, the `idle_o` signal will go high (also observable from the STATUS register) and the module is ready for initialization by software.

I think I should better document this procedure and maybe change some reset values in the STATUS register:
- IDLE could be 1'b0 instead of 1'b1: due to the procedure mentioned above, it will anyway go low in the second cycle after reset)
- STALL is not defined
- OUTPUT_LOST is not defined
- OUTPUT_VALID is not defined
- INPUT_READY should 1'b0 instead of 1'b1: it will be go high anyway after the clearing sequence has finished

Or do you think the behavior itself is problematic for DV?

I am also including @rasmus-madsen who is doing all the AES DV.

**Comment by rasmus-madsen** [comment]
@sriyerg sorry I am not following your comment - maybe part of the conversation was internal between you and @matutem?
I am unsure what you feel is missing in the dv-doc?
if it is the idle_o that will eventually be documented when I finish everything else in V2, it has very low priority as it is a status only and is already documented in the AES spec.

but also edn, and lifecycle is missing. these will also be added eventually

**Comment by matutem** [comment]
Pirmin, I am just learning the design, so it would help me if you mention why we need to go through a long sequence of operations after reset instead of just clearing all state. Commenting on #5651 is okay, since I am closing this one.
