### ISSUE TITLE
Run Opentitan ELF files on Spike

### ISSUE THREAD

**Issue by chenc6** [lowRISC/opentitan#5690]
Hi folks

I am having some issues when using spike to run **hello_world_sim_verilator.elf** from _opentitan/build-bin/sw/device/examples/hello_world_
I have tried to run it in both baremetal and pk methods. Unfortunately, neither of them work.
Here are how I run them:
1. baremetal method:
	$spike --isa=rv32imc -l hello_world_sim_verilator.elf
	$Error: terminate called after throwing an instance of 'trap_load_access_fault'
2. pk method:
	$spike --isa=rv32imc -l pk hello_world_sim_verilator.elf
	or
	$spike --isa=rv32imc -l pk -p hello_world_sim_verilator.elf
The pk method keeps running and never terminates. When I check its log file, it causes several exceptions such as "_trap_load_page_fault, trap_store_page_fault_, etc."

Please help me solve this issue.
Thank you

---------------------------------------------
Note: Here are the details about my setup:
 - I use the lowRISC-provided prebuilt toolchain https://docs.opentitan.org/doc/ug/install_instructions/#software-development
	riscv32-unknown-elf-gcc (crosstool-NG 1.24.0.41-475d72f) 9.2.0
	Spike RISC-V ISA Simulator 1.0.1-dev
 -  System information: I am running on a VM
	Linux User-VirtualBox 5.8.0-45-generic #51~20.04.1-Ubuntu SMP Tue Feb 23 13:46:31 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
 -  Spike: https://github.com/lowRISC/riscv-isa-sim 
       -  build configuration: ../configure --prefix=$prebuilt_RISCV
 -  pk: https://github.com/lowRISC/riscv-pk
        - build configuration:  ../configure --prefix=$prebuilt_RISCV/riscv32-unknow-elf --host=riscv32-unknow-elf --with-abi=ilp32 --with-arch=rv32imc

**Comment by chenc6** [comment]
Hi Folks,

I just want to check if someone can help me solve this issue? 

Any help would be greatly appreciated!

Thank you

**Comment by luismarques** [comment]
Hi @chenc6,

Spike simulates a RISC-V machine, with (despite some command-line options) a very specific configuration in terms of devices, memory mappings, etc. PK is a basic kernel that runs on that machine and implements the Linux syscall interface. It forwards those calls to the Linux host that spike is running on, so in general it only makes sense to use it to run Linux-style programs. Linux also generally assumes a RISC-V ISA with the GC extensions, and PK is compiled accordingly, which is why it misbehaves when run on an IMC machine, not even providing you an error message.

The OpenTitan device firmware is written targeting a different machine than what spike is emulating. With quite a bit of effort, you might be able to change the firmware so that the machine-specific portions match what spike emulates. Or you can modify spike to emulate the OpenTitan device. Both options are non-trivial, and might not even be worth considering unless you have a very good reason to. Depending on your needs, a better option might be to not attempt a full port but instead change the device code just enough that you can run a relevant subset of the device firmware in spike. For instance, a while ago I built an FPGA-based RISC-V arcade system that provided IO for video, audio, joystick, UART, etc, with a specific memory map. To also test the game with spike, instead of a custom simulator, I had the option to build with the game with most of those IOs disabled. The serial IO would also be performed with a write syscall (using pk) instead of by using the UART memory-mapped registers. It sounds like a similar setup might be a good choice for you.

I hope that helps. Let me know if you have any more questions.

**Comment by alistair23** [comment]
There is an OpenTitan model in QEMU that you can use instead. There are instructions available here: https://github.com/tock/tock/tree/master/boards/earlgrey-nexysvideo#running-in-qemu

**Comment by chenc6** [comment]
Hi @luismarques,
Thank you for your suggestions. I think running a subset of firmware is exactly what I want to do.

May I know how should I disable those IO and UART relevant registers, or how should I modify the firmware to what I want?

Also, it seems like each time the spike can only emulate one elf file, however, opentitan requires three files (bootrom, flash, otp) to simulate properly. Could you also tell me how to use spike properly in this case?

**Comment by luismarques** [comment]
> May I know how should I disable those IO and UART relevant registers, or how should I modify the firmware to what I want?
> 
> Also, it seems like each time the spike can only emulate one elf file, however, opentitan requires three files (bootrom, flash, otp) to simulate properly. Could you also tell me how to use spike properly in this case?

If the answer to those questions isn't relatively straightforward for you to answer, perhaps Alistair's suggestion of using QEMU is a better fit for your situation? It already implements the appropriate OpenTitan machine model.

**Comment by chenc6** [comment]
Hi @alistair23 @luismarques 

Thank you for your suggestions. We are trying to use qemu. However, we are not sure whether the qemu is working or not and how to verify it. 

I follow the link provided by Alistair, [https://github.com/tock/tock/tree/master/boards/earlgrey-nexysvideo#running-in-qemu](url)  . I have tried either 
           `make OPENTITAN_BOOT_ROM=<path_to_opentitan>/sw/device/boot_rom/boot_rom_fpga_nexysvideo.elf qemu` 
or
           `make OPENTITAN_BOOT_ROM=<path_to_opentitan/sw/device/boot_rom/boot_rom_fpga_nexysvideo.elf> APP=/path/to/app.tbf qemu-app`. 

However, the qemu keeps working until we manually terminate it without generating useful information. The output from terminal looks like this: `
$ make OPENTITAN_BOOT_ROM=<path_to_opentitan>/build-out/sw/device/boot_rom/boot_rom_fpga_nexysvideo.elf APP=<path_to_libtock-rs>/rv32imc.tbf qemu-app`

`
    Finished release [optimized + debuginfo] target(s) in 0.02s
   text	   data	    bss	    dec	    hex	filename
  89401	   6544	   9840	 105785	  19d39	/home/chenc/Desktop/opentitan_tool/tock/target/riscv32imc-unknown-none-elf/release/earlgrey-nexysvideo
qemu-system-riscv32 -M opentitan -kernel /home/chenc/Desktop/opentitan_tool/tock/target/riscv32imc-unknown-none-elf/release/earlgrey-nexysvideo.elf -bios ../../../../opentitan/build-out/sw/device/boot_rom/boot_rom_fpga_nexysvideo.elf -device loader,file=../../../libtock-rs/rv32imc.tbf,addr=0x20030000 -nographic -serial mon:stdio`

`qemu-system-riscv32: terminating on signal 15 from PID 19891 (bash)`
The last line of information appears once we manually terminate the simulation by killing its PID. 

Could you help me figure out the use of qemu? I really appreciate it!.

Chen

---------------------------------------------------------------------------------------------------------------------------------------
Below are details of how we install tock:

1. Get the Rust userland library for Tock (libtock-rs) for TBF applications, [https://github.com/tock/libtock-rs/blob/master/README.md](url)

2. Then compile a hello_world TBF file
`$ cd [LIBTOCK-RS-DIR]`
`$ make flash-opentitan`
`$ tar xf target/riscv32imac-unknown-none-elf/tab/opentitan/hello_world.tab`

3. install qemu of tock
`git clone https://github.com/tock/tock.git`
`cd TOCK_ROOT`
`make ci-setup-qemu`

4. change to the earlgrey-nexysvideo board and begin simulation (There is no board folder called opentitan)
`$ cd [TOCK_ROOT]/boards/earlgrey-nexysvideo`
We have tried to compile the Kernel for either FPGA or Verilator,
`make BOARD_CONFIGURATION=fpga_nexysvideo`
or
`make BOARD_CONFIGURATION=sim_verilator`
but none of them work.
`make OPENTITAN_BOOT_ROM=<path_to_opentitan>/build-out/sw/device/boot_rom/boot_rom_fpga_nexysvideo.elf APP=<path_to_libtock-rs>/rv32imc.tbf qemu-app`

-------------------------------------------------------------------------------------------------------------------
Our device information is the same as listed in the initial comment. But one thing I want to mention is that because we didn't use FPGA and Xilinx Vivado, we keep the set up of Verilator. So when we build the opentitan design, we still use
`$ fusesoc --cores-root . run --flag=fileset_top --target=sim --setup --build lowrisc:systems:chip_earlgrey_verilator` . 
I am not sure if this will be the case.
