### ISSUE TITLE
Enable CI FPGA tests with mask_rom enabled

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#5695]

**Comment by tjaychen** [comment]
quick question, don't we already include the ROM as part of FPGA?
Also, it would be great to keep @sriyerg in the loop.  As the ROM starts getting heavier, we need to have a discussion how to keep things factored so that DV does not incur a heavy start-up penalty.  This might mean DV needs to be able to stub out certain functions.

**Comment by moidx** [comment]
Hi @tjaychen, we'll make sure to keep you and @sriyerg in the loop with any planned changes here.

Currently we have `boot_rom` integrated in FPGA testing, and we want to also enable `mask_rom` which will be the target used to implement all the MaskROM functionality. 

Eventually, we'll either phase out `boot_rom` or use it only in constrained test configurations.

**Comment by moidx** [comment]
This isssue is now tracked in #6684
