### ISSUE TITLE
[sw/mask_rom] Production ready console logging utilities 

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#5773]
`/home/moidx/opentitan/sw/device/lib/runtime/log.h` requires some changes for production readiness. Consider adding support for a PROD release flag in the build system, or an alternative option to meet the following requirements:

1. Some log messages are only useful for debug in pre-silicon and FPGA environments. Consider adding support for debug messages.  Debug messages should not be included in production release builds.
2. Other log messages shall compile out unused code, e.g. `kDeviceLogBypassUartAddress` for production release builds targeting FPGA and silicon builds. 
3. Document guidance on usage of logging utilities.

**Comment by cfrantz** [comment]
As far as the mask_rom (and rom_ext) are concerned, this is my perference:

1. Developers may use LOG() statements for any debug messages.
2. All LOG() statements will be eliminated in a production build (e.g. compiler flags will be used to redefine LOG statements as do-nothing macros).
3. Anything that must be printed to the console should use `printf` directly.  All intentional prints to the console must be reviewed, documented and approved.

**Comment by alphan** [comment]
Closing this since
* we can debug the ROM over JTAG (this is more general since it covers both asm and C code), and
* ROM has to fit in 32 KiB. The ROM printf library is pretty compact but I can't say the same for the log library. If we go with the latter we could run into issues when the size of the production ROM (without log output) approaches this limit.

@cfrantz @moidx please feel free to reopen if you think we should work on this.
