### ISSUE TITLE
[entropy_src] entropy_data does not match incoming entropy

### ISSUE THREAD

**Issue by senelson7** [lowRISC/opentitan#5800]
Value read from entropy_data register does not equal concatenation of incoming entropy in bypass mode. It appears not all of the incoming entropy data is captured.

**Comment by mwbranstad** [comment]
@imphil Steve and I were thinking that he would close this issue once he has verified the fix with his test - this closes the loop. Do you agree, or have a different process in mind? Or are we doing this wrong since we wanted to test out the debug/fix loop path.

**Comment by imphil** [comment]
If you add a "Fixes #NNN" to a commit message or a PR, the issue gets close automatically when merging ([docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)). That's the "normal" flow. If that doesn't match what you're looking for, you can:

* Avoid "Fixes #NNN" in the commit message, and instead add use e.g. "Fix for #NNN" or "Related to #NNN". This will still add a connection between the PR and the issue, but not auto-close it.
* Let the issue close automatically, and re-open it if the problem is not fixed. This approach is what most projects use and assumes that the fix works by default; manual action (re-opening the issue) is only required if the fix doesn't work.

**Comment by mwbranstad** [comment]
Thanks, that was very helpful.
