### ISSUE TITLE
Alert Manager should have a software alert

### ISSUE THREAD

**Issue by cfrantz** [lowRISC/opentitan#5896]
There are cases where it is useful for software to trigger alert escalation (e.g. boot ROM or other software encounters an exceptional condition and wants to shut everything down).

Add a software alert source to alert manager and add a register interface to trigger the software alert.

**Comment by msfschaffner** [comment]
This should not be difficult to add. How soon is this feature needed?

I have a couple of other pending alert handler tasks and would bunch this together with those if this is not urgent (post silver).

**Comment by tjaychen** [comment]
i dont' think it's super urgent, so definitely okay to be post-silver.
Michael if you get tied up with other things, let me know also, i can help
look at it.

**Comment by tjaychen** [comment]
@msfschaffner 
since we have to add a `device` module for ibex to capture all of its alerts for forwarding, I'm thinking we can add the software triggered alerts there as well.  That way we don't have to change anything about the existing `alert_handler`, other than expand the number of connections.

**Comment by msfschaffner** [comment]
Good idea, That sounds good to me!

**Comment by msfschaffner** [comment]
Closing this issue down for now, since such SW alerts are now implemented as described above. Feel free to reopen if something is missing.
