### ISSUE TITLE
[Question] Incorrect nightly DV report

### ISSUE THREAD

**Issue by tunghoang290780** [lowRISC/opentitan#5901]
I received nightly DV reports via email which sometimes showed error tests for IP (see below screenshot). However, when I click into failed IP (e.g. pattgen IP), it showed all tests passed. There might be issues in scripts used to collect and generate the nightly reports.

![image](https://user-images.githubusercontent.com/53881329/113231547-55d51900-9250-11eb-9b78-7edc1b76bfca.png)

**Comment by cindychip** [comment]
Thank you for raising this issue Tung. 
Here is what happened:
1. When you received the email it is Tuesday March 30th, and when you click the link to pattgen, it refers to the [latest report](https://reports.opentitan.org/hw/ip/pattgen/dv/latest/results.html) (for today it is actually March 31st). 
  So that means if you check it tomorrow, the link should refer to April 1st.
2. If you go down [pattgen](https://reports.opentitan.org/hw/ip/pattgen/dv/latest/results.html) and click ["2021.03.30_14.34.56"](https://reports.opentitan.org/hw/ip/pattgen/dv/2021.03.30_14.34.56/results.html), this should refer to the March 30th result. 

So the issue here is the email always refer to the latest results, and the latest results get updated daily.

**Comment by tunghoang290780** [comment]
@cindychip thank you for the explanation
