### ISSUE TITLE
[question] clock frequencies on FPGA

### ISSUE THREAD

**Issue by jackieke724** [lowRISC/opentitan#5905]
The [clk_mgr spec ](https://docs.opentitan.org/hw/ip/clkmgr/doc/) does not match the actual clock frequencies on FPGA. For example, it says the CPU runs at 100 MHz but actually 10 MHz on FPGA. According to #3647, it seems to be a temporary hack due to the large negative slack. Is that correct?

If I do not include OTBN, can the design at the current stage run at the frequencies on the spec?

**Comment by imphil** [comment]
You'll need to give it a try and see how far you get, unfortunately.

**Comment by jackieke724** [comment]
Ok, thanks. 
Do you plan to improve timing? When would that be?
Do I assume all frequencies on the spec are divided by 10? For example, does the spi device operates at 2.5 MHz, and its SCK operates at 10 MHz?

**Comment by imphil** [comment]
In OpenTitan, FPGAs are only a prototyping platform. As such, we are not specifically optimizing timing for FPGAs. However, we're happy to accept contributions to improve timing on FPGAs, e.g. by you. Please open a pull request!

For the individual frequencies the most reliable approach is to look at the synthesized design in Vivado to see what frequencies get calculated -- otherwise it's easy to get lost in the clock division logic.

**Comment by jackieke724** [comment]
Thank you.
