### ISSUE TITLE
[keymgr] LC turns off when advancing from StReset to StInit

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#5922]
@tjaychen 
advancing from StReset to StInit is a bit special. When LC turns off during this operation, op_status will be success and no error, no alert will be triggered. State is updated to StInvalid and key are wiped. Does this make sense? Triggering an error seems better.

![Screen Shot 2021-04-02 at 11 34 03 AM](https://user-images.githubusercontent.com/49293026/113443703-58965200-93a7-11eb-93e3-8dbd35b26f5c.png)

wave:
/edascratch/weicai-opentitan/ot/km_regr/keymgr-sim-vcs/9.keymgr_lc_disable/out

**Comment by tjaychen** [comment]
yes that doesn't sound quite right. Let me take a look.
If it goes to StInvalid it should mark as an error.

**Comment by tjaychen** [comment]
actually @weicaiyang coming back to this one a bit... when LC turns off (ie keymgr_en goes low) that's not technically an error case right? Because it doesn't necessarily mean locally the keymgr faulted or provided bad input, but rather the system has informed keymgr to shutdown.

If for example you disabled keymgr_en during other states when there are no errors, shouldn't we also go to invalid with a "success" report?

**Comment by weicaiyang** [comment]
> actually @weicaiyang coming back to this one a bit... when LC turns off (ie keymgr_en goes low) that's not technically an error case right? Because it doesn't necessarily mean locally the keymgr faulted or provided bad input, but rather the system has informed keymgr to shutdown.
> 
> If for example you disabled keymgr_en during other states when there are no errors, shouldn't we also go to invalid with a "success" report?

If I remember correctly, we don't report an error when LC turns off but no operation is in WIP. If any operation comes across with LC shutting off, we report an error for this operation as this operation can't be completed as expected.
For other operation, if LC is turn off during the operation, we do fire an error.
For advance, maybe this no-error issue only occurs when advancing from StReset, because I didn't see an issue when it's advancing from other states (need to double check). As long as it's consistent, I'm fine. But SW needs to always check what state it enters even the op_status is success.

**Comment by tjaychen** [comment]
ahhh you are right. I forgot about this. When in the keymgr wipe state, any operation that is ongoing or started is treated as illegal. 

So reset to init is indeed kind of special.  The enable is actually not looked at during reset (because it's possible to be in the reset state and enable = 0 to start with).  So what you're seeing is that the FSM transitions to st init and then gives up. 

Because it "completes" the transition, there technically was no illegal operation to start with. I need to think about this.  Maybe i need to add a condition that during the transition states, if enable suddenly drops again we have to register this as an error.
