### ISSUE TITLE
[usbdev] revisit connections

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#6043]
revisit usbdev connections one more time and make sure all the relevant signals are muxed correctly for production purposes.
There is an explicit split between `asic` and `fpga` right now, and we need to make sure that the `asic` side has all the functionality it needs. 

- [ ] `sense` should be moved to a muxed pin that can be used in both `asic` and `fpga`.

See also #6042

**Comment by tjaychen** [comment]
@mdhayter

**Comment by a-will** [comment]
Just checking, but are there any changes in mindset here? It looks like a good idea to me.

According to the spec, `sense` should gate whether the pull-up is enabled, so it would be convenient if we had it go through the pinmux and get the overrides through ordinary MIO configuration (instead of the bits in `usbdev.phy_config`).

Even when usbdev is powered down in deep sleep, we'd likely want to continue sampling VBUS `sense` in the AON domain and shut off the D+ pull-up if VBUS goes away (and probably report the event to usbdev for when it wakes up. With the current wake-up logic, this would cause a wake event--The pull-up will go away, causing the detector to not see an idle signal anymore.).

**Comment by mdhayter** [comment]
Based on previous experience, many use cases of the discrete OT will not need the voltage sense pin (and will be short on GPIOs because that is a rule of the universe). So having the pin available to be muxed seems like a good direction.

One reason to have the detection if you can even when bus powered is because (at least a couple of years ago when I last looked) if the Linux driver had trouble enumerating (or re-enumerating) its ultimate hammer was to drop and restore VBUS.
It also does this between different enumeration methods.

**Comment by a-will** [comment]
The 1 task looks to be done, as of #10253. Please re-open if I've jumped the gun.
