### ISSUE TITLE
[dvsim] Ctrl-C now waits 10 seconds

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#6061]
If you start a dvsim run and immediately hit Ctrl-C, you'll see something like this:
```
INFO: [StatusPrinter]           [   legend    ]: [Q: queued, D: dispatched, P: passed, F: failed, K: killed, T: total]
INFO: [StatusPrinter] 00:00:00  [    build    ]: [Q: 0, D: 1, P: 0, F: 0, K: 0, T: 1]   0%
^CINFO: [Scheduler] Received SIGINT. Exiting gracefully. Send another to force immediate quit (but you may need to manually kill child processes)
INFO: [StatusPrinter] 00:00:10  [    build    ]: [Q: 0, D: 0, P: 0, F: 0, K: 1, T: 1] 100%
INFO: [StatusPrinter] 00:00:10  [     run     ]: [Q: 0, D: 0, P: 0, F: 0, K: 1, T: 1] 100%
INFO: [FlowCfg] [results]: [chip]:

```

We used to stop immediately, but it seems that recent changes to the scheduler/launcher/dispatcher (I'm not sure which bit) have broken things.

@sriyerg: I think this was your change. Could you take a look and see whether there's something simple to fix things?

**Comment by sriyerg** [comment]
In my last change, I removed the `sys.exit(1)` call after `self._kill()` when SIGINT is detected, to prevent dvsim from immediately exiting. The rationale was to allow the status indicating whatever passed or failed before the user interrupted, and the final results table to be printed (i.e. all the reports to be generated) before exiting. IMO it is useful information to look at, even though the simulation run is known to be broken.

As is turns out, when `stop_now.set()` is called, the `stop_now.wait()` returns vacuously, rather than actually waiting for the set timeout. This makes sense from the `threading.Event` usage point of view, but has a side effect in our case - the `while True` loop ends up spinning with 0 delay, causing a the loop contents to execute a ~million times. The `poll()` returns False, because no jobs are running. The only thing stopping the loop it is the next print interval at 10s. From the profile data:

```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
    365/1    0.001    0.000   10.622   10.622 {built-in method builtins.exec}
        1    0.000    0.000   10.622   10.622 dvsim.py:5(<module>)
        1    0.000    0.000   10.424   10.424 dvsim.py:598(main)
        1    0.000    0.000   10.025   10.025 FlowCfg.py:362(deploy_objects)
        1    1.412    1.412   10.002   10.002 Scheduler.py:115(run)
   968345    0.427    0.000    2.180    0.000 threading.py:556(wait)
   968346    0.661    0.000    1.899    0.000 Scheduler.py:389(_dispatch)
  1936694    0.734    0.000    1.736    0.000 Scheduler.py:16(sum_dict_lists)
   968346    0.407    0.000    1.425    0.000 Scheduler.py:338(_poll)
   968344    1.033    0.000    1.362    0.000 Scheduler.py:459(_kill)
   968346    0.495    0.000    1.322    0.000 Timer.py:27(hms)
```

When the print interval is reached, the `check_if_done()` determines that we are indeed done, and only then we exit. 

Thanks for reporting - this is fixed with #6245.
