### ISSUE TITLE
[aes/dv] Failing to trigger fatal alert after forcing illegal mode

### ISSUE THREAD

**Issue by rasmus-madsen** [lowRISC/opentitan#6201]
@vogelpi 
so I have created at test aes_alert
that for now just forces `tb.dut.u_aes_core.ctrl_q.mode` by setting multiple bits (usually one hot)
the value is kept for the duration of the test.
the test fails so the mode is not ignored but the neither the alert output or the status bit is set to indicate an alert had happened.
![image](https://user-images.githubusercontent.com/53917183/115392250-a3ee9400-a1e0-11eb-909f-3ecaa762c1f5.png)

any see should reproduce this with vcs

`./util/dvsim/dvsim.py hw/ip/aes/dv/aes_sim_cfg.hjson -i aes_alert -r 1 -t vcs  --waves=vpd`

from my aes_alert branch

**Comment by vogelpi** [comment]
Hey @rasmus-madsen,
thanks for looking into this and filing the issue. This kind of error should definitely signal a fatal alert and lock up the FSM.

However, in this particular case, I think it doesn't happen because the detection happens inside the shadow register `tb.dut.u_aes_core.u_ctrl_reg_shadowed`. Can you try to force the signal `tb.dut.u_aes_core.u_ctrl_reg_shadowed.committed_q` instead? This signal is directly connected to the `ctrl_q` your forcing now. It should lead to a storage error signaled in `tb.dut.u_aes_core.ctrl_err_storage_d` and ultimately lock up the FSM and signal an alert. Note that `committed_q` contains more than just the mode.

**Comment by rasmus-madsen** [comment]
@vogelpi that works thank you

**Comment by vogelpi** [comment]
Okay cool, glad to hear this is working :-)
