### ISSUE TITLE
[kmac] Measure the security risks for dummy entropy in KMAC

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#6285]
This issue is a follow-up of PR #6262 

In the PR #6262, KMAC entropy manager creates dummy (all zero) entropy right after out-of-reset state. This is inevitable to let ROM_CTRL to run cSHAKE or SHA3 operation without SW aid in order to verify ROM content.

This revision, however, leads to the possibility that KeyMgr may run KDF without proper entropies if software missed the configuration. In my opinion, this chance is rare as OpenTitan has multiple steps of detecting fault injection attacks.

This issue is to analyze the possibilities and searching for better solutions if needed.

**Comment by tjaychen** [comment]
@moidx @cfrantz 

I think this effectively boils down to software sequencing.  Ie, until entropy is actually ready, we need to make sure we don't run any keymgr derivation steps so that the root seeds aren't exposed via side channel. 

Are you comfortable making this guidance for software? It would not be difficult I think, to ask KMAC to expose the status of its entropy state to keymgr, and let keymgr decide it will not issue a transaction because entropy is not ready.

**Comment by moidx** [comment]
Hi @tjaychen, I think it is reasonable to lean on mask ROM for this. We are planning to implement incremental consistency check for critical registers, so we can add a state check before keymgr configuration.  We have to tie this with the post boot-init entropy source configuration sequence.

**Comment by tjaychen** [comment]
sounds good.
Thanks Miguel!
Then let's close this one down.
