### ISSUE TITLE
[Question] PLIC priorities and interrupt selection

### ISSUE THREAD

**Issue by sajjadahmed677** [lowRISC/opentitan#6288]
Hello everyone!
I have question regarding plic interrupt priorities and interrupt selection.
According to plic documentation. it selects interrupts based on priorities if there are multiple interrupts, the interrupt with highest priority will be serviced.
But, here comes the confusion. how it is possible to have multiple interrupts at the same instant of time in single hardware thread environment.
we know that  our high level language is sequential in nature. lets take an example. i have two API's for ```gpio``` and ```spi```.

int main()
{
    int a, b;
    a = gpio_read();
    b = spi_read();
}
in above example ```a``` will have the value of any gpio pin and ```b``` will have value read from spi. 
whenever i call the ```gpio_read``` it will configure gpio modue, plic and core for interrupts and after handing it will disable them. same goes for spi, because the code is sequential in nature i wont get any interrupt from spi until gpio is serviced.
so, my question is in which condition we can have multiple interrupts at same instant of time in single thread environment??

**Comment by tjaychen** [comment]
The interrupt model really is assuming we've activated multiple pieces of
hw in parallel and let them run.
Using your example, imagine we've set up the spi interface and are now
waiting for a host transaction.
We've also set up gpio, connected it to a different host as some kind of
side band signaling.

Since these interfaces are connected to two unrelated, asynchronous hosts,
the interfaces can have activities at different times.
It is then not inconceivable that interrupts can fire at the same time and
we read back multiple bits set.

The same could also be true for internal timers, internal crypto modules
that are just kicked off and waiting to complete etc.

**Comment by sajjadahmed677** [comment]
Thank you @tjaychen !
what i understand is that, it is possible to have multiple interrupts at the same instant when different hosts are configure the different devices of the system. or specifically talking in PLIC terminology, when different targets configure devices then we can have multiple interrupts.
but, when we have only single host like, a single core in the system then it's not possible to have multiple interrupts at the same instant. refer to my example,
int main()
{
int a, b;
a = gpio_read(); // host 1
b = spi_read(); // host 2
}
if there are two hosts one configures the ```gpio``` and the other one configures the ```spi``` then its possible to have both interrupts at same time but, if there is only one host then we always have single interrupt at a time.

**Comment by tjaychen** [comment]
sorry i'm not quite sure we're talking about the same thing.

When you say host, do you mean a host external to the device? or the processor in `top_earlgrey`.

If we pull back a bit and assume the following:

There is a device called top_earlgrey with a single processor, and multiple peripherals (timers / gpio's / spi's).
In this context, let's assume the processor configures only two things.
- the timer, set to interrupt the process once per ms
- the spi module, used to communicate with an external host (another device somewhere in the system).

Given this, it's possible for both the timer interrupts and the spi interrupts to assert at the same time, since their timing is completely independent of one another.   The spi configuration for example, just sets the module up for operation.  It does not mean an interrupt immediately pops up.  When an interrupt shows up is dependent on when another agent talks to it.

**Comment by sajjadahmed677** [comment]
yes by host i mean a single processor that is in ```top_earlgrey``` which is ```ibex core```.
my point is that the devices(timer/spi/gpio's) will only interrupt the processor whenever i configure them in my program or call the API of the device.
again referring to my example above. the nature of my code is sequential it will not move to next instruction until the previous one completes. like, ```a``` will have the value read from ```gpio``` and then ```b```` will have the value read from ```spi```.
in this case i will not have interrupts from both devices at the same time.
lets take another example.
int main()
{
int a, b;
a = gpio_read(); // host 1
delay(5);
b = spi_read(); // host 2
}
in this code i am using a timer module for having the delay of 5ms again this code will not configure multiple interrupts together. if you can give me an example code which illustrates the condition where multiple interrupts can be generated related to the C code.

**Comment by tjaychen** [comment]
i'm not sure what you are trying to ask.
Are you asking whether in a real system we can have multiple interrupts at
the same time? If that's the question, the answer is definitely yes.
Or are you asking if you can construct a code sequence such that only 1
interrupt can happen at a time? If that is your question, then yes that is
also true.

I feel like you are assuming that interrupts can only be triggered when the
host processor performs some kind of action.  This is *NOT* true in our
design.
Most of our interrupts will be triggered by some independent activity
outside of what instruction the processor is currently executing.  If that
were not true, we wouldn't really have the need for interrupts.

I'll try to give one more example.  We have multiple accelerators in our
system, for example HMAC and KMAC.
One way for software to use this is as follow:
- software configures HMAC to process X amount of data.  This will take
some time.
- Before the HAMC completes, software then configures KMAC to process Y
amount of data.
- software now just sits in an idle location (WFI) for the hardware to
interrupt it when it finishes.  It is thus possible for the two
accelerators to finish at the same time and interrupt at the same time.

Alternatively, the software could also do the following
- configure HMAC to process X amount of data.
- Wait for the HMAC's done interrupt
- Once it receives the interrupt, then configure KMAC to process Y amount
of data
- Wait for the KMAC's done interrupt.

In this fashion, you will never have multiple interrupts.

**Comment by sajjadahmed677** [comment]
Thank you @tjaychen!
I got your point now. and yes my question was about the sequence of code. as you mentioned in your second example.
