### ISSUE TITLE
[ prim/prim_packer_fifo ] Assertion fail on clear?

### ISSUE THREAD

**Issue by martin-lueker** [lowRISC/opentitan#6296]
In PrimPackerFifo:

The assertion ValidOPairedWidthReadyI_A fails if clr_i is asserted and ready_i is not.  Is this intended?

**Comment by martin-lueker** [comment]
Also as a minor spelling nit: Should the assertion be more properly named: `ValidOPairedWithReadyI_A`? (With vs. Width?)

**Comment by tjaychen** [comment]
i don't think this is intended. I think the likely reason is that the assertion forgot to cover the case where `clr_i` could make `rvalid_o` 0 without performing a read.

@mwbranstad can you confirm? I think you originally added this module.

**Comment by martin-lueker** [comment]
Would it be okay then to just add `&& !clr` to the sequence definition?

**Comment by martin-lueker** [comment]
> Would it be okay then to just add `&& !clr_i` to the sequence definition?

That seems to work in the current case.

**Comment by tjaychen** [comment]
yeah that fix sounds good to me.

**Comment by martin-lueker** [comment]
Great, made this into a PR: #6301

**Comment by mwbranstad** [comment]
so the history is that the prim_packer_fifo was created to be "pin compatable" with prim_fifo_sync, and as such, the asserts were ported over as is. Meanwhile, the function of the clr_i changed slightly for the case where the AST RNG designer wanted a certain post-reset behavior. Since clr_i is a special case of behavior, modifying the assert as defined sounds good to me.
