### ISSUE TITLE
[otp_ctrl] Unused hw_cfg

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#6404]
It would be good to have the ability to remove the unallocated buffered flops inside partitions such as hw_cfg.
Right now most of hw_cfg is empty, and that will probably still be the case when everything is done.

An alternative option is we just take the extra space and push it into the unbuffered software partitions.  That would be a fine solution also without incurring additional hardware.

This issue is already well known, just filing for tracking purposes.

**Comment by msfschaffner** [comment]
Agreed, there are a ton of unneeded flops sitting in that partition right now.
However, since the digest is calculated over the entire partition, these flops cannot be optimized away in RTL (unless we introduce a mechanism to hardwire the unused buffer flops to 0).

So I think the way to go is to shrink the HW_CFG partition once we have connected all chicken switches, and give the free space to the SW_CFG partitions.

**Comment by tjaychen** [comment]
sounds good to me, thanks @msfschaffner
