### ISSUE TITLE
[otbn] Produce end-to-end performance numbers for RSA and ECDSA

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#6449]
We have spread out over various forums performance numbers for RSA encrypt/decrypt of various key sizes, as well as ECDSA P-256 and P-384 numbers. Confirm those with the most recent version of OTBN, and add them to the tracking spreadsheet.

Depends on an end-to-end test for ECDSA P-384 first, tracked in https://github.com/lowRISC/opentitan/issues/6448

**Comment by felixmiller** [comment]
Collecting here but also adding to the spreadsheet:

**P-384:**
Curve point test: 
```
OTBN executed 421 instructions in 441 cycles.
The execution stalled for 20 cycles (4.8 percent).
The execution would take 0.00 ms @ 100 MHz.
```

Base point multiplication: 
```
OTBN executed 1679280 instructions in 1720044 cycles.
The execution stalled for 40764 cycles (2.4 percent).
The execution would take 17.20 ms @ 100 MHz.
```
ECDSA verify:
```
OTBN executed 1266058 instructions in 1294428 cycles.
The execution stalled for 28370 cycles (2.2 percent).
The execution would take 12.94 ms @ 100 MHz.
```

ECDSA sign:
```
OTBN executed 1753898 instructions in 1794680 cycles.
The execution stalled for 40782 cycles (2.3 percent).
The execution would take 17.95 ms @ 100 MHz.
```

**P-256:**
todo: let's add those after the current OTBN sprint, since we are making fundamental changes to the P-256 lib

**RSA:**
1024 bit verify/encrypt:
```
OTBN executed 115852 instructions in 129346 cycles.
The execution stalled for 13494 cycles (11.6 percent).
The execution would take 1.29 ms @ 100 MHz.
```
1024 bit sign/decrypt:
```
OTBN executed 2302414 instructions in 2439771 cycles.
The execution stalled for 137357 cycles (6.0 percent).
The execution would take 24.40 ms @ 100 MHz.
```
1024 bit verify/encrypt:todo
1024 bit sign/decrypt: todo
2048 bit verify/encrypt:todo
2048 bit sign/decrypt: todo
3072 bit verify/encrypt:todo
3072 bit sign/decrypt: todo
4096 bit verify/encrypt:todo
4096 bit sign/decrypt: todo

**Comment by felixmiller** [comment]
@imphil Do you think we should add standalone tests for the larger RSA keys to the code-snippets dir?
I have them lying around, just large assembly files due to the baked in keys...
