### ISSUE TITLE
[rtl] Eliminate sources with autogen file

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#6519]
Many source files have a corresponding .tpl file that causes
the creation of a corresponding file under some autogen
directory.

The chip uses the autogen files, and that is what we are
really building. RTL designers obviously care mostly about
the autogen files since they are what get synthesized.

The non-template files are **not** useful, and cause endless
trouble for DV unit testing. See
https://github.com/lowRISC/opentitan/issues/6432 and
https://github.com/lowRISC/opentitan/issues/5808

For reference, the ip blocks with .tpl/autogen files are
pwrmgr
xbar_main
flash_ctrl
rv_plic
clkmgr
padctrl
alert_handler
pinmux
rstmgr
xbar_peri

Sri has mentioned a way to address this matter, which was
used for the alert_handler block.

**Comment by sriyerg** [comment]
We developed the generic parts of the alert handler testbench in the IP area and dumped the chip specific parameter set to a file in the chip area. We run tests exclusively only from the chip area, which references the parameter set to know what values are to be used. Though, IMO, this is not at all a good way to maintain IPs in general.

It is really a hassle for DV to have pieces of HW split in different places (some things in the common IP area and some auto-generated in chip area) with an intricate web of dependencies going back and forth between them. The better approach would have been to take the fully parameterized IP route, where `reggen` auto-generates a parameterized register block from HJSon in the IP area (it would generate a parameterized module rather than fixing the parameters in a pkg, which forces us really to dump a separate set of reg top and reg pkg specifically for the chip just to be able to use a different set of parameter values). 

IPs such as `clkmgr` makes this problem worse - its entire implementation is duplicated in 2 places - IP and the chip area, and both look quite different. The version in the IP area needs to be ignored, but that is not obvious to anyone. If we build a testbench around the auto-generated one in the chip area with completely custom port names, then that presents a big problem when we get to the next chip - it is easy for the designer to quickly dump a new design with small modifications to the template - but the entire DV effort has to be duplicated and manually updated for the new chip - unless we also start writing the entire DV in mako templates (which IMO is a crazy thing to do). It would be great to design blocks like those also in a parameterized manner instead. But for the short term - we should probably do away implementations that are not used anywhere. 



It would be really great if we could instead hand-write a parameterized version of it too.

**Comment by imphil** [comment]
There is work ongoing to clean up the templating together with the toplevel generation based on the ipgen tool (#5636). A (now outdated) preview of how that could look is at #5782. We did de-prioritize this work before to get other toplevel changes in first (the top -> chip refactoring that Michael did) and de-risk silver. But with silver done I'll pick this work up again next week, and will be presenting more on the approach in one of the next silicon meetings. Please reach out in the meantime if you have specific questions.

**Comment by tjaychen** [comment]
I'm downgrading this to P3 as this belongs in the same class of issues where templated modules need to be moved from their legacy location in the hierarchy to `ip_autogen`. This will remove a significant amount of the "example" confusion.

**Comment by tjaychen** [comment]
the spirit of this issue is now being tracked in #8440 
Eventually when the movement of these blocks into `ipgen` is complete, this will be resolved as well.
I'm closing this one down to track in the other.
