### ISSUE TITLE
[rom, keymgr] Advance state from INIT to ROOT_CREATOR results in error.

### ISSUE THREAD

**Issue by moidx** [lowRISC/opentitan#6653]
Use PR lowrisc/opentitan#7109 to reproduce this issue.

Attempting to advance from `INIT` to `CREATOR_ROOT` results in: 

```cc
WORKING_STATE = Disabled
OP_STATUS = DONE_ERROR
ERR_CODE = 0xe
```

Reproduction steps:

```shell
cd ${REPO_TOP}
# build verilator
./meson_init.sh -f
ninja -C build-out/

FLASH_BIN_TEST=build-bin/sw/device/silicon_creator/testing/sw_silicon_creator_lib_driver_keymgr_functest_sim_verilator.elf
build-bin/hw/top_earlgrey/Vchip_earlgrey_verilator \
  --meminit=rom,build-bin/sw/device/boot_rom/boot_rom_sim_verilator.scr.40.vmem \
  --meminit=otp,build-bin/sw/device/otp_img/otp_img_sim_verilator.vmem \
  --meminit=flash,${FLASH_BIN_TEST}
```

**Comment by moidx** [comment]
Hi Tim, 

I added additional code to the functional test referenced above to program the `CreatorSecret` and `OwnerSecret` in their respective info flash pages. I have to double check the operations to make sure I am doing this correctly. 

The devices by default are running in `RMA` state.

I haven't checked yet to see if other secrets are initialized.

**Comment by moidx** [comment]
I tried to lock the `SECRET2` partition and put the device in `DEV` or `PROD` mode, but this results in a flash erase error. 

Locking `SECRET2` and running the test in `RMA` mode still fails to advance into `CREATOR_ROOT`.

**Comment by tjaychen** [comment]
thanks Miguel.
Let me bring this thing into DV and have a look.
It's very likely you've run into some kind of design issue since this area
of flash is not well tested.

**Comment by tjaychen** [comment]
okay i think i understand what's going on. 

A few things.
- the flash -> keymgr seed transmission only happens at power up when the seed is determined to be transmittable (`SECRET2` is locked)
- the creator flash seeds can only be programmed if `SECRET2` is not locked, ie, you provision the flash seed and the root keys together in one shot. 

So I think the two test cases you went through

1. dev_state = RMA, `SECRET2` not locked
In this state we are able to program the flash.  However, after programming, `keymgr` is still unaware of it because the "transmit" window has passed.  

2. dev_state = DEV, `SECRET2` is locked
Since `SECRET2` is locked, even though you normally would have permission to the info page, it is now locked out, resulting in an `erase` error.


So we can do a few things here
1. I can try adding a manual reset and that should trigger seed transmission again
2. Add a mechanism to allow software to request transmission of flash seeds thus relaxing the boot up requirement.  I don't see a huge reason why we have to allow transmission at start-up only.  Let me know what you think.  This last change would require some tweaknig.

**Comment by alphan** [comment]
It looks like this issue was created just before we added signature verification to Mask ROM (#6550). Updated reproduction steps to use `build-bin/sw/device/boot_rom/boot_rom_sim_verilator.scr.40.vmem` since functional tests use the test boot rom but I'm not sure if anything else needs to be updated. @tjaychen @moidx PTAL.

**Comment by tjaychen** [comment]
thanks @alphan ! this definitely explains why i couldn't reproduce this test exactly. 
@moidx does it make sense for this test, we create a signed version of it? I think you wanted to test the ROM programming of some of the inputs as part of the test?

**Comment by tjaychen** [comment]
i think this issue can be resolved now as we managed to get the test working.
