### ISSUE TITLE
[verilator] Add a sim-timeout mechanism

### ISSUE THREAD

**Issue by sriyerg** [lowRISC/opentitan#6659]
The Verilator testbench `chip_earlgrey_verilator` does not have a simulation timeout mechanism (AFAIK). If a test hangs due to a bug somewhere, it needs to be manually killed. It will be useful to have a timeout mechanism instead that will gracefully kill the test if it took too long to run. 

The timeout can be made programmable so that it is set to a reasonable value for most tests. There may of course be tests that might end up being longer running - for those, we should be able to increase the timeout via a runtime plusarg switch.

**Comment by imphil** [comment]
Our verilator test wrapper does have command line argument `--term-after-cycles` that should fulfill your needs. In https://github.com/lowRISC/opentitan/pull/6664 @rswarbrick  also added a way to trigger the same functionality from within the top-level C++ wrapper file.

This gives the ability to set a default for the toplevel simulation, and allows for overriding this default with a command line switch, which is I think all this issue asked for.

@sriyerg, Please let me know if something is missing, or close the issue otherwise.

**Comment by sriyerg** [comment]
Thanks; yes, that should do it!
