### ISSUE TITLE
[ I2C (design+DV), pinmux ] Move virtual open drain operation to  pinmux

### ISSUE THREAD

**Issue by martin-lueker** [lowRISC/opentitan#6812]
Currently "virtual open drain" is explicitly implemented in I2C IP.  However this should be a feature of the pinmux, so that pinmux can either do virtual open drain or true open drain.

**Comment by JunminHe** [comment]
Can you give me some help of i2c question issue? Thank you ! 
https://github.com/lowRISC/opentitan/issues/6811

**Comment by msfschaffner** [comment]
CC @tjaychen

This feature is already available as "pad attribute" in the pinmux. So technically you can rely on that. Note however that only some of the pins in the pinout have support for true open drain mode (this is dependent on the pad type). See also the pinout table here (`BidirOd` vs `BidirStd` pads):

https://github.com/lowRISC/opentitan/blob/0a0de1ff16d583028681713f8dc99ec5d0377b41/hw/top_earlgrey/data/top_earlgrey.hjson#L1034-L1112

**Comment by mdhayter** [comment]
Note that keeping the open drain control in the I2C IP block rather than the pinmux will make it easier to do a version of the IP to support the newer I3Cbasic protocol. Some of the speed increase comes from switching from open drain to push-pull mode (to allow the clock to go up to 12.5MHz) when communicating with higher speed devices, but for I2C peripherals and detecting bus conflicts the open drain mode is still used too. (Of course depending on the detail of BidirOd it could be better to use a control pin on the pin itself to change modes.)

**Comment by tjaychen** [comment]
@martin-lueker i think it's fine to keep virtual open drain on i2c (especially if you've already implemented it). In addition to what Mark said, this would also make the module more integration friendly with other pinmuxes, especially those that no understanding of virtual open drain. 

The pinmux open drain in my opinion is a backup option to support these functions if the module doesn't already understand it (for example GPIO), but if it's already there, we don't have to take it out.

**Comment by msfschaffner** [comment]
I believe this has been resolved (feel free to reopen if that is not the case).
