### ISSUE TITLE
synth_design failed on 2020.1 but been successful in 2018.3

### ISSUE THREAD

**Issue by nicolast0604** [lowRISC/opentitan#6891]
Hi 
I tried the opentitan fpga but encounter a strange issue.
It seems successful in 2018.3 but always failed in 2020.1. (Isn't 2020.1 the version recommended?)

is there anyone met the same situation?

**Comment by nicolast0604** [comment]
INFO: [Synth 8-3354] encoded FSM with state register 'tap_state_q_reg' using encoding 'one-hot' in module 'dmi_jtag_tap__parameterized0'
---------------------------------------------------------------------------------------------------
                   State |                     New Encoding |                Previous Encoding
---------------------------------------------------------------------------------------------------
                    Idle |                              000 |                              000
                    Read |                              001 |                              001
           WaitReadValid |                              010 |                              010
                   Write |                              011 |                              011
          WaitWriteValid |                              100 |                              100
---------------------------------------------------------------------------------------------------
INFO: [Synth 8-3354] encoded FSM with state register 'state_q_reg' using encoding 'sequential' in module 'dmi_jtag__parameterized0'
Parent process (pid /tools/Xilinx/Vivado/2020.1/bin/loader: line 286: 13196 Killed                  "$RDI_PROG" "$@"
13196) has died. This helper process will now exit

**Comment by imphil** [comment]
`Parent process (pid /tools/Xilinx/Vivado/2020.1/bin/loader: line 286: 13196 Killed "$RDI_PROG" "$@"` is the relevant line, the INFOs before that are unlikely to be related to the problem. It seems that Vivado got killed, probably due to an out-of-memory error. Have a look at the system logs especially for OOM-killer related information, and try to find other crashdump information.

This isn't something specific to OpenTitan, so if you're lost head over to the Xilinx forum, they might be able to help you out better than we can.
