### ISSUE TITLE
[process] create a security review template based on the security design guidance

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#7074]
Based on the contents of the to-be-made-publicly available security design guidance, we should come with a template for reviewing designs for security. 

- [ ] Add examples of what are considered privilege operations

**Comment by tjaychen** [comment]
@mateenfaisal 
@dsandrs

**Comment by moidx** [comment]
Is this already covered by the D2S and V2S review templates?

**Comment by cdgori** [comment]
Not exactly :(

I think the idea is to have some more enumerated guidance for the RTL reviewers, but maybe @tjaychen remembers more exactly what he meant here.  I think the D2S/V2S templates are pretty good for the security-council roles because just following along with the specified/tagged actions for the milestone gets you to do what is necessary to black-box inspect the functionality.

**Comment by johannheyszl** [comment]
@vogelpi and I discussed it. A security review template seems very useful for future IP design reviews, e.g. for integrated.

**Comment by johannheyszl** [comment]
We will revisit this, when the actual need arises. Closing for now.
