### ISSUE TITLE
[doc/clkmgr] Update spec for clk_hints and status

### ISSUE THREAD

**Issue by matutem** [lowRISC/opentitan#7126]
The spec for the clk_hints and clk_hints_status needs to add a bit for the otbn.

**Comment by tjaychen** [comment]
actually @matutem , when you mentioned the spec was not updated, where are you referring to?
Because it's here in the [hjson](https://github.com/lowRISC/opentitan/blob/master/hw/top_earlgrey/ip/clkmgr/data/autogen/clkmgr.hjson#L289), and also here in the [open source documentation](https://docs.opentitan.org/hw/ip/clkmgr/doc/index.html#Reg_clk_hints)

**Comment by matutem** [comment]
This is obsolete, and may have been a mistake. Sorry.
