### ISSUE TITLE
[rv_core_ibex] Simple address translation open items

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#7181]
- do we actually need separate configuration for dbus / ibus? Probably not, since there's no reason for them to be translated differently
- we may need more regions for translation as there is no guarantee that various parts of the boot stages will always be in the same flash partition.

**Comment by cfrantz** [comment]
My main concern is that each boot stage can make a decision about whether to choose the A or B side:

ROM -> ROM_EXT (A or B)
ROM_EXT -> BL0 (A or B)
BL0 -> Kernel/App (A or B)

Each of these stages have different projected sizes, they may not easily layout nicely into FLASH on power-of-two boundaries.  Consider if ROM_EXT is 16K, BL0 is 16K and Kernel is 256K.

ROM_EXT: start: 0x0, end: 0x4000
BL0: start: 0x4000, end: 0x8000
Kernel: start 0x8000, end: 0x48000

I think we'll probably be ok by aligning each translation region with the beginning of it's corresponding half of flash and setting the length to 512K, but then we'll need a region per boot stage.

**Comment by tjaychen** [comment]
@cfrantz do you think it makes more sense to align these to a start/end address (with relatively coarse granularity...say 4K or 16K)?
the alignment of two i'm doing right now would not work so well for some of the cases shown here. 

i can also do some research to see what riscv does for their virtual memory systems.

**Comment by cfrantz** [comment]
I think there are two possible solutions here:
1) Relax the NAPOT restrictions and allow the remap region to be assembled from coarse-grained chunks via the remap registers (as you suggested in your prior comments).

2) Keep the NAPOT restrictions and provide several windows at $8x00_0000, such as one per remap register.  If we chose this route, that would mean something like: 
- ROM finds ROM_EXT and maps side A or B to $8000_0000 and jumps to the ROM_EXT entry point at that address.
- ROM_EXT finds BL0 and maps side A or B to $8100_0000 and jumps to the BL0 entrypoint (which might be at something like $8100_4400 because we map the whole side and find the BL0 offset from the beginning by the size of ROM_EXT).
- BL0 finds the kernel and maps side A or B to $8200_0000 and jumps to the kernel entrypoint (again, which might be at something like $8200_8400 because its offset from ROM_EXT+BL0).

**Comment by tjaychen** [comment]
@cfrantz both sound good to me. 
do you have a preference? If we go with the first option, i would recommend doing it on the boundary of our flash erase, since we'll have to at a minimum separate by that granularity anyways.

the second option doesn't require any HW change, so we could stick with that and see how it works out during your software prototyping and pivot as needed.  Let me know.

**Comment by tjaychen** [comment]
After some discussions, we will stick with NAPOT for now.
If there are issues for software in the future, this scheme will be adjusted accordingly.

**Comment by tjaychen** [comment]
@udinator
