### ISSUE TITLE
Accessing OTBN registers on FPGA results in system hang

### ISSUE THREAD

**Issue by alistair23** [lowRISC/opentitan#7187]
When running on the FPGA accessing any OTBN register results in a full system hang.

This occurs on commit a28c280bb976ef15b7192779c2a3f93b746fa2ca but has also occurred for awhile.

I have confirmed that running the `otbn_rsa_test_fpga_nexysvideo` or the `otbn_ecdsa_p256_test_fpga_nexysvideo` test results in a hang.

**Comment by rswarbrick** [comment]
As @imphil pointed out in another issue, OTBN is stubbed out for NexysVideo builds (because the whole of OpenTitan is now too big to fit on that card). So it ain't gonna respond :-)

If you want OTBN on an FPGA, you'll need to use a larger FPGA like our CW310 builds. (Or do some work to stub out a different part of the design instead to get things fitting on the NexysVideo).

**Comment by alistair23** [comment]
Thanks for the clarification
