### ISSUE TITLE
[formal] Find out how to reduce the number of data pattern in Jasper

### ISSUE THREAD

**Issue by eunchan** [lowRISC/opentitan#727]
If an assertion checking the the correctness of the data output (or stored) based on the given input data `data_i` and `mask_i` in `prim_packer, FPV takes more than a few hours. FPV seems try to populate all the combinations of `data_i` pattern.

Assume the data to be `inside { values, ... }` doesn't help. Need to figure out (or discuss with AE).

CC: @cindychip

**Comment by cindychip** [comment]
Hi Eunchan,

Sorry it took so long to address this issue.
I think by adding an assumption here for data (`data_i inside {...}`) does help reduce the run time. What makes it still runs very slow is the `mask_i` variable. Due to the size of `mask_i` (32 bits), formal engine has to run all the combinations, thus takes a very long time.
If you add another constraint for `mask_i`, the tb can converge very soon.

But I think if we constrain the `mask_i`, it limits the functionality check of the prim_packer. I think limiting the input data width might be a better solution. I made a PR here (https://github.com/lowRISC/opentitan/pull/2431) for you to review.

Thanks,
Cindy

**Comment by eunchan** [comment]
Thanks for the follow-up. OK I should limit the mask_i too. in HMAC :) I will close this issue.
