### ISSUE TITLE
[prim_esc_receiver] reserve ping corner case

### ISSUE THREAD

**Issue by cindychip** [lowRISC/opentitan#7489]
Hi Michael,

I wonder if there is a corner case where the reverse ping might not work:

Here is the sequence I was thinking:
1). TB force esc_tx.esc_n to always be 1 to create a signal integrity error.
2). Send first ping request (that can trigger prim_esc_receiver's counters).
3). Ping request failed because esc_tx.esc_n is set to 1. -> However, it does not trigger an `ping_en` in prim_esc_receiver because of the signal integrity error, and ping counter never starts.
4). prim_esc_sender get the ping's signal integrity error, and triggers a real escalation request.
5). The escalation request always experiences signal integrity error because esc_tx.esc_n stays 1, and `esc_en_o` is not set in the `prim_esc_receiver`. So I think the escalation signal will never reach to the escalation receiver side.

Do you think we shall fix this?

![image](https://user-images.githubusercontent.com/11466553/127077185-6ff6b66a-07ee-4fdc-b494-e936f015f4fe.png)

Thanks,
Cindy

**Comment by msfschaffner** [comment]
Hey @cindychip, this is a good point, and essentially corresponds to a situation where the escalation line has been permanently compromised / severed.

At the moment we rely on the remaining escalation channels to trigger other escalation actions in such a case - i.e., if the alert handler detects that one of the escalation senders does not work due to signal inegrity, it can trigger all other escalation senders.

However, there is a case to be made that a signal integrity error on the escalation lines should trigger the corresponding escalation action right away.

@tjaychen @cdgori WDYT?

**Comment by cindychip** [comment]
Thanks Michael - Do you think this will work?
For signal integrity error for the last (most important) escalation_receiver, can we directly trigger `esc_en`?

**Comment by msfschaffner** [comment]
Something like that, but I don't think we need to distinguish the channels here (i.e., we already have a way to feed this condition back to the other escalation channels via the integrity alert). Rather I was just thinking about asserting the escalation enable in prim_esc_receiver if this condition is detected (similar to the auto-escalation feature of the reverse ping mechanism).

**Comment by tjaychen** [comment]
yeah i agree. I think a signal integrity error (assuming i understood correctly) on the receiver side, should definitely start the escalation process. This also makes sense that it's on the receiver side to me, since if we see an integrity error, we can't promise that any further indication from the sender side will actually work.

**Comment by msfschaffner** [comment]
Ok sounds good I'll look into how this could be added. I need to think about the clock / power management issues anyways now (both for the alert and escalation channels).

**Comment by cdgori** [comment]
100% agree with @tjaychen - it should cause escalation, and on the receiver side (because the sender is now in unknown condition).

**Comment by sriyerg** [comment]
[A little late, but] thanks Cindy for finding and reporting this.
