### ISSUE TITLE
[mem] Implement HW support of ECC protection on main memory with byte access

### ISSUE THREAD

**Issue by sjgitty** [lowRISC/opentitan#76]
ECC is preferred on main memory, but we also want to have byte-access. Options

1) ECC on main memory, software does RMW to avoid byte accesses
2) ECC on main memory, hardware does RMW on byte accesses
3) parity on main memory, byte accesses are easy

Need software input on the cost of lowRISC/stwg-base#1

**Comment by imphil** [comment]
@tjaychen @msfschaffner I think there has been some thinking on this issue recently, can you update this issue with the current status?

In terms of implementation, we now have `prim_ram_1p_adv` as a wrapper available for such functionality, and `prim_ram_2p_adv` as an example how to implement some of the ECC/Parity functionality, not yet considering write masks.

**Comment by tjaychen** [comment]
@imphil 
thanks Phil will do. Sorry I need to document the memory scrambling / ecc / parity discussion we did a couple of months ago.

I just have not gotten to it.  It is in a way..somewhat on-hold because I am hoping to get some security lab guidance to make sure it is okay.

**Comment by tjaychen** [comment]
assign to myself to documentation purposes

**Comment by imphil** [comment]
@tjaychen no worries, we just got reminded of this one today when talking about the icache, but there's nothing blocked at the moment by this issue.

**Comment by imphil** [comment]
Not the solution, but an implementation step towards it, is in https://github.com/lowRISC/opentitan/pull/2418

**Comment by tjaychen** [comment]
this issue is quite stale now. 
Just for the sake of closure, we opted for scrambling + parity on the main sram.  
This is because we determined that it was important for have a fast (single cycle) working memory for the processor, and the potential latency of ECC piling up, in the absence of something like a dcache (other security holes) just was not worth it.

I'm closing this now, if anyone objects, please feel free to re-open.
