### ISSUE TITLE
[otbn] Wrong version of register used for range checks in bn.lid

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#7639]
Example code:
```asm
.section .text
  addi     x21, x0, 0
  bn.lid   x21, 0(x21++)
  ecall

.section .data
  .word 0
  .word 0
  .word 0
  .word 0
  .word 0
  .word 0
  .word 0
  .word 0
```

Note that `x21` is used as both a source and a destination. The code that checks whether `x21` is in range as the name of a register is checking the value after it's been incremented by 32, so flags this as an illegal instruction.

Attached is a simple directory with Makefile that lets you generate the same example. Unzip it in the top of the OpenTitan folder, build the Verilator sim with `fusesoc --cores-root=. run --target=sim --setup --build lowrisc:ip:otbn_top_sim`, then `make -C indirect-bug test`.

[indirect-bug.zip](https://github.com/lowRISC/opentitan/files/6945643/indirect-bug.zip)

@GregAC: I think this is probably triggered by the fix for #7579: presumably we need to flop `rf_indirect_err` in `otbn_controller` for load/store instructions?

> estimate 2

**Comment by GregAC** [comment]
This turned out to be a bit trickier than first thought. It's not just about the timing of when to check the error but the timing of the read for the indirect destination register index. Architecturally both should be read before any activity occurs so in this scenario the newly incremented `x21` shouldn't be the indirect destination register, the old version should be used (the same as used for the base address).

So I've introduced a flop that holds the read value from the first cycle of the instruction. This also partially backtracks what I did for #7579, now both register reads always occur on the first cycle. I've checked the #7579 behaviour again and I believe everything now works correctly :)
