### ISSUE TITLE
What frequencies to use for TLUL interface

### ISSUE THREAD

**Issue by weicaiyang** [lowRISC/opentitan#7647]
Initially, we decided we could just randomly pick 24Mhz, 25Mhz, 48Mhz, 50Mhz or 100Mhz in our block level TB for TLUL.
We added 6Mhz recently as OTP may run with this frequency. Some of our existing TB don't expect to run with such slow clock and it's 4 time slower than 24Mhz, which causes some test timeout or other errors.

I have 2 questions.
1. can we only use 6Mhz for OTP. For other block, we use 24Mhz or higher, so that we don't need to fix those errors due to this frequency, unless we do have some benefit of testing with 6Mhz.
2. are we happy with these defined frequencies, or should we use a range like 24-100Mhz instead?

@tjaychen @eunchan @sriyerg @matutem @cindychip @rswarbrick any thoughts?

**Comment by tjaychen** [comment]
i think if a module is all digital and has only one clock to start with, there is much value to testing with something slower than 24MHz.

I think where it gets interesting is where there are async interfaces (did you mean `spi_device` instead of `otp`?) OR if there are included macros that some kind of fixed timing assumption (flash and otp). The latter however only makes sense when we have the real model, the open source ones don't care at all. 

I think those frequencies look good in general. SPI host at the top level technically operates at 96MHz.  So I kind of wonder if we should add that as a test point (or just replace 100MHz with 96MHz).

**Comment by sriyerg** [comment]
Here's my preference:
- Make `clk_freq_mhz` as an integer instead of a fixed set of enums. 
- Add a constraint to limit multi-clock designs to be within min and max of known freqs (`clk_freq_mhz inside {[10:100]};`). 
- For single-clock designs, what clock freq is set is immaterial - we could set it to anything.   
- For multi-clock, we add constraint to limit the clock ratio to be no more than 8 (or whatever is more appropriate). 
- Extended env cfg class (including further extensions in partner env) can turn off the base class constraint in `pre_randomize()` and add its own constraints (such as 96MHz for SPI, 6MHz for partner otp env cfg). 
 
IMO the real issue here is the fact that we are using an `enum` instead of `int`, which makes it hard to more freely constrain things. The 6MHz literal was added to the enum to support partner env, which is now breaking the open source envs because now the randomly chosen clock ratios are too wide, blowing up the sim time.

**Comment by weicaiyang** [comment]
> i think if a module is all digital and has only one clock to start with, there is much value to testing with something slower than 24MHz.

I guess you mean **not** much value to testing with something slower than 24MHz


> I think where it gets interesting is where there are async interfaces (did you mean `spi_device` instead of `otp`?) OR if there are included macros that some kind of fixed timing assumption (flash and otp). The latter however only makes sense when we have the real model, the open source ones don't care at all.

According to @cindychip, OTP use 6Mhz before the calibration.

> I think those frequencies look good in general. SPI host at the top level technically operates at 96MHz. So I kind of wonder if we should add that as a test point (or just replace 100MHz with 96MHz).

Thanks for the info. We should use 96Mhz for spi host.

**Comment by weicaiyang** [comment]
> Here's my preference:
> 
> * Make `clk_freq_mhz` as an integer instead of a fixed set of enums.
> * Add a constraint to limit multi-clock designs to be within min and max of known freqs (`clk_freq_mhz inside {[10:100]};`).
> * For single-clock designs, what clock freq is set is immaterial - we could set it to anything.
> * For multi-clock, we add constraint to limit the clock ratio to be no more than 8 (or whatever is more appropriate).
> * Extended env cfg class (including further extensions in partner env) can turn off the base class constraint in `pre_randomize()` and add its own constraints (such as 96MHz for SPI, 6MHz for partner otp env cfg).
> 
> IMO the real issue here is the fact that we are using an `enum` instead of `int`, which makes it hard to more freely constrain things. The 6MHz literal was added to the enum to support partner env, which is now breaking the open source envs because now the randomly chosen clock ratios are too wide, blowing up the sim time.

Agree to change enum to int. Enum can't be overridden or customized for a particular block. Int is much more flexible.

For block which only has clocks for TLUL and EDN, what default frequencies should we use for TLUL or EDN in the base class? Is it 10-100Mhz also a bit too wide? I'm afraid using 10Mhz may still affect our existing TBs.
Should we use (24-100mhz) or those meaningful values (24Mhz, 25Mhz, 48Mhz, 50Mhz or 100Mhz) ?

For multi-clocks, each block owner should add additional constraint or more frequency based on the design requirement.

**Comment by rswarbrick** [comment]
I agree with Sri's comments above. About this specific question:

> Should we use (24-100mhz) or those meaningful values (24Mhz, 25Mhz, 48Mhz, 50Mhz or 100Mhz) ?

I'd suggest using any old frequencies. If a block has multiple clocks and *needs* them to have a particular relationship, surely it's up to the block's environment configuration to sort that out.

**Comment by tjaychen** [comment]
> > i think if a module is all digital and has only one clock to start with, there is much value to testing with something slower than 24MHz.
> 
> I guess you mean **not** much value to testing with something slower than 24MHz
> 
> > I think where it gets interesting is where there are async interfaces (did you mean `spi_device` instead of `otp`?) OR if there are included macros that some kind of fixed timing assumption (flash and otp). The latter however only makes sense when we have the real model, the open source ones don't care at all.
> 
> According to @cindychip, OTP use 6Mhz before the calibration.
> 
> > I think those frequencies look good in general. SPI host at the top level technically operates at 96MHz. So I kind of wonder if we should add that as a test point (or just replace 100MHz with 96MHz).
> 
> Thanks for the info. We should use 96Mhz for spi host.

o yes you're right.  When clocks are uncalibrated, OTP can get very slow (just like the chip facing side of SPI device).
When the clock is THAT slow, the OTP needs to be able to support read reliably, and for writes it has to switch to an external clock.

Having said all that however, this test is only really interesting if we have the real OTP model. Because the fake one will just behave like a memory, so whatever clock we feed it makes not too much of a difference.  Does it make sense to still have this test, but run it only for proprietary simulations?

**Comment by weicaiyang** [comment]
> Having said all that however, this test is only really interesting if we have the real OTP model. Because the fake one will just behave like a memory, so whatever clock we feed it makes not too much of a difference. Does it make sense to still have this test, but run it only for proprietary simulations?
This is probably a question for OTP DV owner. I think it's needed for proprietary simulation but it does no harm to run 6Mhz in open-source simulation. Since we reuse the TB, it may be easier to have the same configuration and coverage for both simulation.

**Comment by tjaychen** [comment]
that sounds good to me.

**Comment by cindychip** [comment]
yeah since we reuse the TB, it is easier to support both open source and close source simulation. But i agree with what Tim mentioned, open source does not really have much to test..
We could move it to a closed source env if that makes things easier.

**Comment by weicaiyang** [comment]
Thanks for all the inputs.

Will update 2 things
1. change `enum` to `int` have more flexibility
2. add constraint to randomize clock frequency for TLUL clock, alert clock and EDN clock in this range {24:100}, but have high distributions for these frequencies (24Mhz, 25Mhz, 48Mhz, 50Mhz and 100Mhz).

**Comment by weicaiyang** [comment]
@tjaychen what actual frequencies do we use for TLUL and EDN in most of the blocks?

As @matutem pointed out, we should avoid testing too wide range that we don't actually use.

**Comment by tjaychen** [comment]
for tlul, most blocks fall under either main (~96MHz) or io_div4 ( 24MHz).
EDN also is the same, with a slightly heavier bias towards 96MHz.

**Comment by weicaiyang** [comment]
> for tlul, most blocks fall under either main (~96MHz) or io_div4 ( 24MHz).
> EDN also is the same, with a slightly heavier bias towards 96MHz.

Thanks Tim. Sounds like we should also increase the weight for 96Mhz.
