### ISSUE TITLE
Read of internal states incorrect

### ISSUE THREAD

**Issue by senelson7** [lowRISC/opentitan#7703]
The issue is that the internal state read happens immediately after the internal state selector write. Need a cycle between to let hardware switch pointer.

**Comment by mwbranstad** [comment]
Backpressure to the reg block is needed to fix this in a reasonable way, but it is not available. Since this is fundamentally a debug function, a software patch of reading the int_state_num after writing it will guarantee the clock separation needed between the write of the id and the read of the values. No hardware change required.
