### ISSUE TITLE
[fpga] Stub out Aes (or other similar algorithmic modules)

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#7707]
hey all,
as part of #7687, @imphil and i have been discussing what other "big" things we can stub out.

One thing we settled on was Aes, both because Aes is pretty substantial and because Aes is not on the boot path. 
(we are stubbing out for Nexysvideo).

If we do decide to stub out Aes, my opinion (and maybe we should have done this with Otbn also) is that we should add a software readable register that can inform the software whether the hardware actually exists.  If it does not, the DIFs should probably provide some kind of error state or re-direct to a software algorithm. 

What do you guys think? 

I should note the motivation behind "stubbing" out and not just outright remove something is because we didn't want to change the "skeleton" of the design, but instead wanted to hollow out certain portions.

**Comment by vogelpi** [comment]
I don't mind stubbing out AES but wouldn't add the register. Not because of the register, but because of the software changes involved (DIF, libraries etc.). Also, removing AES won't give us much. The configuration used on the NexysVideo is around 5 kLUTs which amounts to ~4% of the available LUTs on the board (see attached report for details). This will buy us another month maybe until we harden/add some other features elsewhere and we will be in the same situation. But it will definitely not improve CI times significantly.

Instead, I suggest that for the NexysVideo, we create a separate top level with the following:
- Reduced Flash and memory sizes.
- Ibex + debug support
- Few peripherals (1x UART, 1x SPI device, 1x SPI host, USB device)
- Some crypto IPs only and without hardening (HMAC, AES, KMAC, OTBN if it fits)
- No entropy complex - very costly on FPGA
- No OTP ctrl, LC ctrl, alert handler, keymgr - very costly on FPGA, more features and things might come that further blow these up, and I believe this is also what brought us again into the current situation.

This platform will not be suitable for developing secure boot etc. but this should anyway happen on our main development platform only. What the platform will be useful for is to develop/test software using the peripherals, crypto accelerators, for developing/testing OTBN code, to showcase some IPs and to keep people involved that don't have access to more costly boards and tool licenses, i.e., for the open source community.

On the hardware side, we are already there: we have a very similar configuration today (English Breakfast for the CW305 board). This proves that our code generator tooling works for such scenarios. English Breakfast doesn't have OTP, alert handler, entropy complex, keymgr but it's functional.

What needs some attention is the software side. At the moment, we have to rely on a hacky script (`hw/top_englishbreakfast/util/prepare_sw.py`) to patch the some software sources. All that is needed to remove this script and enable building software for multiple top levels is the following:
1. There are hardcoded references to `top_earlgrey` in the software sources and inside `meson.build`. -> We can just replace `top_earlgrey` with `opentitan`.
2. The software build flow should not use auto-generated, but checked in sources under `hw/top_earlgrey/sw`. Instead, it should invoke `topgen` before building.
3. We need a mechanism in software to distinguish (at compile time is sufficient) if a top level doesn't have some IPs. We already have a mechanism to distinguish different chips/targets (Verilator sim, FPGA, chip-level DV), see `sw/device/lib/arch/device_fpga_*.c`. We can extend this to also differentiate e.g. top_earlgrey from top_englishbreakfast or whatever.

Note: I am NOT saying we need to run all software on all top levels. But it should be feasible to have the development boot ROM, a hello world/USB example, some smoke tests for the NexysVideo.

Here the utilization report for the NexysVideo (entropy source and OTBN are already stubbed out):
[top_earlgrey_utilization_hierarchical.txt](https://github.com/lowRISC/opentitan/files/6973839/top_earlgrey_utilization_hierarchical.txt)

**Comment by alphan** [comment]
> (tjaychen) If it does not, the DIFs should probably provide some kind of error state or re-direct to a software algorithm.

I agree with @vogelpi here , IMHO we should not do this since it would require quite a bit of work.

> (vogelpi) This platform will not be suitable for developing secure boot etc. but this should anyway happen on our main development platform only. What the platform will be useful for is to develop/test software using the peripherals, crypto accelerators, for developing/testing OTBN code, to showcase some IPs and to keep people involved that don't have access to more costly boards and tool licenses, i.e., for the open source community.

I think this is a more achievable goal if it makes sense for everyone.

> (vogelpi) We need a mechanism in software to distinguish (at compile time is sufficient) if a top level doesn't have some IPs. We already have a mechanism to distinguish different chips/targets (Verilator sim, FPGA, chip-level DV), see sw/device/lib/arch/device_fpga_*.c. We can extend this to also differentiate e.g. top_earlgrey from top_englishbreakfast or whatever.

This is fine for hardware-specific constants and some simple cases but I'm not sure if this would be enough for other cases. E.g. if a program depends on the AES DIF library and if the AES peripheral does not exist on some FPGA, I don't think we should be building that program for that FPGA at all. We should check to see if there is a clean way to handle this in meson without modifying every executable target and how the same thing could be achieved in bazel and avoid repeating the same work if possible.

**Comment by tjaychen** [comment]
i personally really dont' want to go the route of a separate top.. it gets
really really hard to maintain over time.
It also means we would need to refactor things such that it can support
different tops, and i just don't think we are there yet.

To me having the DIFs error back for now would be a shorter term solution
that is clearer.

If we really want to go the separate top route, it is better IMO to do
dynamic generation and not maintain a static top.

**Comment by tjaychen** [comment]
@imphil @vogelpi 
i think it's worth asking at this point what is the purpose of the nexysvideo fpga. 
is it so someone can evaluate the crypto modules?

**Comment by tjaychen** [comment]
> @imphil @vogelpi
> i think it's worth asking at this point what is the purpose of the nexysvideo fpga.
> is it so someone can evaluate the crypto modules?

what i am REALLY getting at ... does it make sense to just use top_englishbreakfast on nexysvideo and go from there? 
Because it sounds like what Pirmin is proposing is a lot like englishbreakfast (but slightly bigger),  but until we define a clear goal for nexysvideo, i feel like englishbreakfast is just as good a goal as any...

**Comment by vogelpi** [comment]
Hey @tjaychen ,
porting top_englischbreakfast to the NexysVideo sounds like a good start. In addition to AES we can then add also OTBN and maybe KMAC but stub it out on the CW305 (there is really no space for anything else than hardened AES). This way we can avoid introducing another top.

But of course we still need some reasonable software support there. The issue you've linked is again a good example why we should stop using the hacky scripts.

The main purpose of the NexysVideo should be to have an easily accessible platform for software development (excl. secure boot). This includes people working on libraries, DIFs, Tock OS, OTBN crypto code etc.

**Comment by vogelpi** [comment]
> > (vogelpi) We need a mechanism in software to distinguish (at compile time is sufficient) if a top level doesn't have some IPs. We already have a mechanism to distinguish different chips/targets (Verilator sim, FPGA, chip-level DV), see sw/device/lib/arch/device_fpga_*.c. We can extend this to also differentiate e.g. top_earlgrey from top_englishbreakfast or whatever.
> 
> (alphan) This is fine for hardware-specific constants and some simple cases but I'm not sure if this would be enough for other cases. E.g. if a program depends on the AES DIF library and if the AES peripheral does not exist on some FPGA, I don't think we should be building that program for that FPGA at all. We should check to see if there is a clean way to handle this in meson without modifying every executable target and how the same thing could be achieved in bazel and avoid repeating the same work if possible.

I think that if a top-level doesn't have the AES peripheral, topgen will not export `aes_regs.h` and the DIF can't be built in the first place. Anyway, this really isn't about providing a full-fledged build system for the secondary top levels. All that is needed is a little bit of support (see the three points outlined above) that allows us to stop using hacky scripts. If we run into further issues we can still discuss again.

**Comment by tjaychen** [comment]
this issue is deprecated and replaced by #7814
