### ISSUE TITLE
Flash Controller: Excess data being erased

### ISSUE THREAD

**Issue by alistair23** [lowRISC/opentitan#7730]
The auto-generated code from OpenTitan includes this:

```c
// Number of bytes per page
#define FLASH_CTRL_PARAM_BYTES_PER_PAGE 2048
```

Indicating that there are 2048 bytes in each page.

If `FLASH_CTRL.MP_BANK_CFG` `ERASE_EN_0` and `ERASE_EN_1` aren't enabled we should be able to erase a page at a time. So we should be able to erase only 2048 bytes in an operation.

What I'm seeing when running on the Nexys Video FPGA is that the page erase operation at address `0x200c0000` is instead erasing from `0x20040000` upwards. This seems to be wrong. Even if I was erasing an entire bank (0x80000 bytes) this is still erasing the previous bank as well.

I don't see anything in `flash_ctrl_test` to ensure that other data isn't erased and due to https://github.com/lowRISC/opentitan/issues/7728 I am unable to test this in `flash_ctrl_test`. It does look like too much data is being erased on a flash operation though.

**Comment by tjaychen** [comment]
do you see similar behavior when running verilator? it wouldn't be super surprising if there is a bug here, the flash controller logic is not super well verified yet. 

one thing i should point out first though (and maybe this is related to the fpga problem you're observing), due to the nexysvideo fpga not being big enough, we actually need to run some scripts first to reduce the flash size.   Please see [here](https://docs.opentitan.org/doc/ug/getting_started_fpga/#create-an-fpga-bitstream).

So when you build locally, you'll also have to make sure to run that script first before doing anything. This is all related to issu #7707, please feel free to have a look. 

What might be happening is that because the flash is shrunk, when you erase 0x200c0000, it actually thinks its 0x2004000.
However, the fact the flash controller does not error seems to be a bug itself.  I can help take a look at this.

**Comment by alistair23** [comment]
I haven't checked on Verilator.

Thanks for pointing that out. Is it worth swapping over to the ChipWhisperer CW310 then to fit more of the design?

Do you know what the flash size is reduced to?

I'm not building the bistream locally (just using one from the CI).

If the flash is smaller then I'm expecting that might be the issue.

**Comment by tjaychen** [comment]
yeah i think it is the issue.
the flash is reduced by half.

So instead of one bank at 0x2000_0000 and one at 0x2008_0000, it is now
0x2000_0000 and 0x2004_0000.
So when you erased 0x200c_0000, due to the flash not checking the address
is completely out of bounds, it actually wraps to 0x2004_0000, and likely
erased the incorrect data (i think).

Yes switching to CW310 will give you the "most" complete system. I haven't
looked into exactly how cw310 isw built, but it is meant to be the FPGA
that can hold the entire design.

**Comment by alistair23** [comment]
Argh! That is exactly the issue!

I tried changing the addresses, but they were always above 0x2008_0000. It didn't even occur to me it would wrap around.

Thanks for figuring that out so quickly. I have been pulling my hair out trying to figure out what is going on.

I'll close this as you have opened https://github.com/lowRISC/opentitan/issues/7731

Thanks again for the help!

**Comment by sriyerg** [comment]
Unfortunately flash_ctrl IP is not verified, so bugs in the design are expected. Apologies for the inconvenience.
