### ISSUE TITLE
[otbn,rig] Model bug with updating known value after an increment

### ISSUE THREAD

**Issue by ctopal** [lowRISC/opentitan#7805]
I am having an error and it seems like it is related to `BN.MOVR`. It picks 32 as an acceptable value (which causes the error). 

![Screenshot from 2021-08-18 11-09-10](https://user-images.githubusercontent.com/87007427/129883373-c3261f80-9062-4d4d-a779-40cd388826a7.png)

 
`_pick_gpr_for_indirect_wdr` method is checking if the known value is great than 31 so that's why I am thinking we are not successful with updating the value. `update_for_bnmovr` under `model.py` is incrementing `grs` and `grd` while masking them with 31. So, in the case of 31+1, it flips back to 0 and the model thinks the value is now 0 (while the real value is actually 32).

I am not sure if it's correct to think like this, so @rswarbrick if you can have a look at it, it would be really great.

Thanks!

**Comment by rswarbrick** [comment]
Yep, that sounds like a bug in the RIG (it matches an older version of the spec). Looking at the code, I think the simplest fix is to just change the mask argument from 31 to 0xffffffff. In theory, we should also check that the value isn't too big beforehand (because otherwise execution will stop and the update won't happen), but that doesn't really matter because we'll never care about the contents of the model afterwards anyway.

**Comment by rswarbrick** [comment]
Actually, looking at the call sites, please could you remove the mask argument completely and just hard-code it as `(1 << 32) - 1` in the function body?
