### ISSUE TITLE
regtool generates different register names depending on parameter configuration

### ISSUE THREAD

**Issue by rasmus-madsen** [lowRISC/opentitan#7836]
for IPs that that has multiregs
it seem that the regtool will generate multiregs without index for a count of 1 
but it will generate indexed registers for a count > 1

this becomes a problem for verification and I don't see a way to support both in the code.

Consider the following (non compiling) code
```
 virtual task program_configopt_regs();
    if (SPI_HOST_NUM_CS > 1) begin 
      for (int i = 0; i < SPI_HOST_NUM_CS; i++) begin    
       ral.configopts[i].cpol.set(spi_host_regs.cpol[i]);
       ral.configopts[i].cpha.set(spi_host_regs.cpha[i]);
       ral.configopts[i].fullcyc.set(spi_host_regs.fullcyc[i]);
       ral.configopts[i].csnlead.set(spi_host_regs.csnlead[i]);
       ral.configopts[i].csntrail.set(spi_host_regs.csntrail[i]);
       ral.configopts[i].csnidle.set(spi_host_regs.csnidle[i]);
       ral.configopts[i].clkdiv.set(spi_host_regs.clkdiv[i]);            

    end else begin
      ral.configopts.cpol.set(spi_host_regs.cpol[0]);
      ral.configopts.cpha.set(spi_host_regs.cpha[0]);
      ral.configopts.fullcyc.set(spi_host_regs.fullcyc[0]);
      ral.configopts.csnlead.set(spi_host_regs.csnlead[0]);
      ral.configopts.csntrail.set(spi_host_regs.csntrail[0]);
      ral.configopts.csnidle.set(spi_host_regs.csnidle[0]);
      ral.configopts.clkdiv.set(spi_host_regs.clkdiv[0]);   
    end
     csr_update(base_reg);
  endtask // program_configopt_regs
  ```
I think the register tool should always add the index to multiregs even if there is only one instance.

**Comment by rswarbrick** [comment]
@weicaiyang: I think this was an intentional decision on your part? But I'm probably with Rasmus on this: let's make the index always appear.

**Comment by weicaiyang** [comment]
Yes, that's intentional.

I can change to `cfg_reg cfg[1]` if the multi-reg only has one instance. It should be a very simple change, but there are some drawbacks.
1. `cfg_reg cfg[1]` looks weird, it's an array with only one element.
2. then we have to use `ral.cfg[0]`. Using `ral.cfg` will cause compile fail. But from spec point of view, we don't know this is defined as a multi-reg with one instance. We need to figure it out from hjson file.

The other approach is to get the reg handle by name if the index may not exist like this case. Similar to the multi-reg which can be equally divided, we have to use `get_reg_by_name`

@rasmus-madsen @rswarbrick WDYT?

**Comment by rasmus-madsen** [comment]
@weicaiyang I think it should be `cfg_reg_cfg[0]`
anyway, I very much prefer the always indexed solution - no matter how it may look. as it simplifies the code a lot.
and the only place the "weirdness" exists is in the autogenerated register file which no one will look at anyway.

**Comment by sriyerg** [comment]
Fine with always creating an array of CSRs even if its sized to 1, especially if it eases DV code development.
