### ISSUE TITLE
[pwrmgr] Escalation reset request too "graceful"

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#7928]
At the moment, `pwrmgr`'s escalation reset request is very graceful. Ie, it effectively behaves as an always-enabled reset request.
However, this also means if someone can glitch the FSM to some invalid state, or gate some of the checks that would be done as part of a normal routine (ie clocks in clkmgr), the escalation reaction would effectively be blocked.

Given that an escalation does NOT need to be graceful, we really need to short-circuit this path otherwise it may be a bit vulnerable. 

Similar, the pwrmgr's fsm also needs to be sparsely encoded..and whenever it is in an invalid state, behave similarly to escalation.

**Comment by msfschaffner** [comment]
I think I agree with you @tjaychen.
How about we do the following?

1) make the FSM sparse, trigger a reset right away when it is glitched into an invalid state
2) kick the FSM into an invalid state upon escalation

This would be similar to how OTP partitions behave, with the exception that reset would be triggered right away upon a glitch (instead of sending out an alert first and then waiting for the escalation to be asserted).

**Comment by tjaychen** [comment]
yes i agree, that's what i'm generally thinking as well.

**Comment by cdgori** [comment]
Solution sounds reasonable to me (and good catch on the inhibition of the escalation, that's a real problem).  

I think I looked at a PR a few min ago that moved the pwrmgr FSM to sparse already, so seems like you are heading this way.
