### ISSUE TITLE
[ibex] Provide simple access to random numbers 

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#7946]
There is a desire to provide easy access to "lower quality" random numbers from Ibex. There are no requirements w.r.t. access latency, or bandwidth.

We discussed possible solutions today in the lowRISC hardware team meeting and came up with a solution that is reasonably easy to implement. There are a number of other options, so please let us know if the solution discussed here doesn't meet some requirements which we might have forgotten about.

- The randomness is sourced from edn0.
- Randomness is cached from the edn in a single entry cache register. Ibex can read this register as memory mapped device CSR from the Ibex comportable wrapper. Let's call this register RND_DATA.
- We also provide a second memory mapped register that indicates if a read from RND_DATA is possible, i.e. if the cache is filled. Let's call this RND_STATUS.

The operation from Ibex software is then as follows:
- Poll RND_STATUS until data is available.
- Read RND_DATA.
- rinse and repeat.

Every read from RND_DATA will automatically refill the cache, so normally this operation should just be two memory mapped register accesses which both return within a cycle.

This solution is nice because it's reasonably self-contained within the Ibex wrapper and doesn't need changes to the Ibex internals, as it would be if we had added a RISC-V custom CSR. By providing a polling interface and the small cache  register we also avoid hanging the bus if the edn cannot deliver random numbers (fast enough), e.g. due to a misconfiguration.

**Comment by GregAC** [comment]
As discussed I've written a spec for this see https://github.com/lowRISC/opentitan/pull/8062, @tjaychen @moidx @rswarbrick @imphil let me know what you think.

**Comment by imphil** [comment]
Since I just stumbled across it: The RISC-V cryptography extension specifies a `seed` CSR, which provides 16 bits of entropy. See https://github.com/riscv/riscv-crypto/releases/tag/v1.0.0-rc2-scalar for details. That's harder to implement than what we ended up agreeing on here, but might be worth taking a look at in the future.

**Comment by felixmiller** [comment]
This issue was discussed in the Security WG meeting on 2021-09-02. Feedback/summary:

Miguel: Have the need for randomness already during the boot sequence, don’t have strict performance requirements, need a seed once a while but can stretch that in software
greg: planning to add a few registers to the ibex wrapper. It will be a polling interface to get data directly from the EDN0. There is an RND status bit as well to determine if the data is available/fresh. This approach is ideal as it doesn’t cause Ibex to block.
greg: We also consider implementing a CSR. We rejected that idea because currently CSRs don’t block, which would require adding a custom interface to Ibex. 
rupert: If for whatever reason we decide to reconfigure the entropy_src, it is possible without major use of the polling interface.
Miguel: Is it just 32-bit at a time?
Greg: EDN gives 32-bit per cycle, the idea of the FIFO is to sync the clock domain 
Miguel: would it be possible to capture the design and DV effort required for this?
Tom: yes, would do a top-level test so that DV effort is low
Greg: the actual RTL will be simple, but we should first write a little spec to agree on
Rupert: do we have some spec/documentation for the Ibex wrapper
Tim: yes, all the additional features of the wrapper are documented there
Tim: should we also agree on the double-fault dump capture?
Greg: yes it would be nice to push that out into the wrapper as it’s pretty OT specific, have a little internal detector to detect an exception while handling another one, then raise external signal, on the OT side, one would want the original MEPC from crashdump + the new MEPC from the CSR
Miguel: do we have an issue for this?
[Ibex issue](https://github.com/lowRISC/ibex/issues/1117#issuecomment-901966168)
Greg: will add that to the note
tim: the double fault will cause an escalation and the information will get  dumped to the alert manager.
Manuel: RISC-V just released a spec for public review on entropy for crypto? Defined an interface for high-quality entropy
https://github.com/riscv/riscv-crypto/releases/v1.0.0-rc2-scalar

**Comment by tjaychen** [comment]
edn connection has been implemented.
