### ISSUE TITLE
[otbn,dv] Add an explicit coverpoint for a straight-line instruction at top of memory

### ISSUE THREAD

**Issue by rswarbrick** [lowRISC/opentitan#8129]
"Falling off the top" should cause an error, but it's different from the normal "branch to an invalid address" situation so we should probably make sure we handle it properly.

> estimate 2

**Comment by GregAC** [comment]
@rswarbrick has this been done?

**Comment by johngt** [comment]
Could do a directed test.
Add cover point

**Comment by ctopal** [comment]
@GregAC Do we want a cross where we have: (straight-line instruction mnemonic x (instr_addr == top_addr)). Or just any straight-line instruction would be enough to mark this coverpoint as seen. WDYT? I tend towards the second option since response from OTBN would not necessarily change depending on which straight-line instruction is at the top of the instruction memory.

**Comment by ctopal** [comment]
> remaining 2022-08-08 1
