### ISSUE TITLE
[otbn] Specify writes to external CSRs during LOCKED state

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#8162]
(At least) for testing purposes we need to specify what happens when OTBN is in LOCKED state (after it has seen a fatal error) and we see reads from the bus to the CSR nodes.

We have at least two registers which should remain accessible and return useful values even if OTBN is LOCKED: the STATUS register (which indicates that OTBN is locked), and the FATAL_ALERT_CAUSE register, which can be read to determine why OTBN is locked.

What should do we for [all other registers](https://docs.opentitan.org/hw/ip/otbn/doc/index.html#register-table)? 
1. Read 0, ignore writes
2. Return a bus error
3. Hang the bus (return nothing)

I'd go for option (1) to make life easier for software to debug a fatal alert.

> estimate 4
> remaining 2021-10-17 1

**Comment by imphil** [comment]
@tjaychen @cdgori Any preference from your side?

CC @GregAC @rswarbrick

**Comment by rswarbrick** [comment]
(1) sounds fine to me, but the implementation might be a bit gnarly for any non-ext registers. Are you imagining a single cycle where we assert `de` for all the registers to clear and pass them zeros?

**Comment by cdgori** [comment]
(1) seems preferable.  (3) is bad.  If (1) is unworkable / too gnarly for some reason, I'd go for (2).  Though, I think (2) gets into that dynamic error modeling situation we discussed in another issue (?), so best to avoid if we can.

**Comment by tjaychen** [comment]
i think as long as the system doesn't respond in a meaningful way, i'm not sure we absolutely have to zero the read path. I am not sure what anyone would gain from it, especially since all the secrets will have been wiped.  The most interesting bit is probably the FATAL_CAUSE (to see what triggered), and that we have to allow anyways. 

If we are okay with that as a compromise, we could accomplish what Philipp is suggesting by adding a hardware modulated regwen, which under certain circumstances just blocks off writes.

To me it is more important to block off writes and freeze the whole thing in place, I don't feel like reads are a huge deal.  Although if we feel strongly about that, we can also add enhance regwen to regwen/regren

**Comment by cdgori** [comment]
I think (I hope?) we are agreed about blocking writes, and it's more "should reads (other than STATUS and FATAL_ALERT_CAUSE) behave consistently with any other memory spaces"

But you are right @tjaychen from a quick look at all the registers I can't see where anyone gains anything from reading them, so maybe not needed except for consistency.

**Comment by GregAC** [comment]
I'd note we already force returning 0s for dmem/imem reads after we've seen an illegal bus access (where Ibex tries to access them when OTBN is running). Though oddly seems the RTL still allows writes after this!

I think we should definitely return 0s on reads to imem/dmem after OTBN is locked and this is trivial to implement.

Perhaps you could argue INSN_CNT gives you something interesting (maybe you're aiming to inject a fault at some particular OTBN instruction and this helps you focus on it?) and is also easy to give 0 on reads when OTBN is locked as the value is provided by OTBN.

For other registers still allowing reads seems fine and avoids some slight trickyness with implementation (as @rswarbrick it's a pain for non-ext registers).

Spec wise we could give a table of registers that return 0 when OTBN is locked and others that still allow reads and state all writes are ignored.

**Comment by tjaychen** [comment]
That sounds good to me.
