### ISSUE TITLE
[top] No option in top_earlgrey.hjson to use <module>.hjson that is not under hw/ip or hw/top_earlgrey  

### ISSUE THREAD

**Issue by sha-ron** [lowRISC/opentitan#8207]
Specifically AST attr in top_earlgrey.hjson is defined as "reggen_only" so ast.hjson is taken from hw/top_earlgrey/ip/ast/data.
When using the 'real' (not open source) AST need to use a private ast.hjson that is located somewhere else (under Nuvoton's private repository) .

**Comment by tjaychen** [comment]
@sha-ron do you need for this for the full ral modeling at chip level? 
We can certainly add a flag to look elsewhere is that is the cleanest solution. 

@zi-v 
@Jacob-Levy 
Is there any way for you guys to expose a fully compatible (in terms of address map only) open source hjson?
You don't need to show any information on how any of it is used.  Ideally we would like the open source / closed source to at least match in terms of spacing / naming to test out our infrastructure.

**Comment by tjaychen** [comment]
@msfschaffner this is a bit different from the prim_csr thing, since ast isn't sitting behind another hjson or anything.

**Comment by sha-ron** [comment]
@tjaychen 
yes need this for the ral modeling at chip level. A flag can be great,

**Comment by tjaychen** [comment]
is it at all possible to align the register names / address space between
open source / closed source? Because that would be the easiest way i think.

**Comment by sha-ron** [comment]
Revealing the closed source names to the open source is problematic and using meaningless names in the closed makes it harder to debug and less readable.

**Comment by msfschaffner** [comment]
CC @moidx

**Comment by msfschaffner** [comment]
As @tjaychen noted, we would ideally just use one hjson in the open-source for this. 
We know that this is not ideal from a closed-source documentation perspective - but it actually makes things simpler from a tooling, testing and SW perspective since we would not have multiple hjson sources that need to be tested. See also the [solution for the prims](https://docs.google.com/document/d/1pnDU3-V2BwEbw2nxFmSClJTIODKlCGhPS4TFC8n7D04/edit#heading=h.l7qwxjui9ien) that we had discussed.

In any case - even if such a switch is implemented as proposed by Nuvoton - Nuvoton needs to guarantee that the open-source hjson is compatible with the closed-source one in terms of address ranges and CSR properties.
Our open-source ROM is going to use software constants generated from the open-source hjson, and this needs to work 100% with the closed source AST (CC @moidx).

**Comment by Jacob-Levy** [comment]
Hi Michael,  

I already updated the OS ast.hjson to match the NTIL ast.hjson
as far at the number of register and the adress space tot match the NTIL.
The name I choose for the OS are generic  and all are 32-bit R/W.

I think Sharon issue relate to the full NTIL registers DV test and it is not different that the synthesis of the full chip (secure code included). 
Arnon had to develupe a flow to address the implementation and 
I think  the NTIL full chip DV need to do the same from  the NTIL database 
and not from the OS database.

**Comment by tjaychen** [comment]
so sounds like the conclusion is we have to have a way of picking alternative search paths, is that right? 
does it make sense to say..in terms of search path priority..

alternative search path > top_earlgrey > ip?

**Comment by Jacob-Levy** [comment]
I asked @arnonsha to look into implementing  similar solution of the implementation flow for the DV as far as the ip/ast.

**Comment by sha-ron** [comment]
> so sounds like the conclusion is we have to have a way of picking alternative search paths, is that right?
> does it make sense to say..in terms of search path priority..
> 
> alternative search path > top_earlgrey > ip?

As I see it yes but we will also hold an internal discussion on Sunday to make sure.
Can the alternative path be a parameter or something we configure in the hjson file? 
The NTIL ast.hjson is located under the Nuvoton repository and not under top_earlgrey>ip.

**Comment by tjaychen** [comment]
i was originally thinking it would be a script input argument.. but you
have a good point.
How exactly would this be used? If it's in an hjson file, which hjson file
would our topgen read to know that there is another search path?

**Comment by Jacob-Levy** [comment]
In NTIL, we have two version of ast.hjson. One in the non-secure domain and the final one in the secure domain.

The implmentation flow runs in the secure domain. for DV we can still do most of the testing in the non-secure domain but we still need to run the DV in the secure domain to check that
the implementation data  is fully tested.

**Comment by sha-ron** [comment]
I thought we will use a new hjson that will import_cfgs the foundry chip level cfg hjson and this new hjson will include the path definition.

**Comment by tjaychen** [comment]
okay sounds good, if there is a new hjson that would make sense.
Sri what do you think? I think effectively we need to be able to pass a new
topgen argument based on hjson args.

**Comment by sha-ron** [comment]
Talked about it internally and having a new argument will be great.

**Comment by tjaychen** [comment]
adding @imphil to see if he has any opinions on this, and whether it would work better as part of the `ipgen` scheme.
I'm not completely certain yet..but i feel like there might be something there.

**Comment by msfschaffner** [comment]
@sha-ron I take it this is meant for top-level tests only, is that correct?

Please note that at the chip-level, SW like ROM code or drivers are relying on the open-source version of the AST register description (and all the generated constants).

We therefore need to make sure that the AST registers are correctly working using the generic open-source description only.
See [this document](https://docs.google.com/document/d/13KOT_asY3KCNONVM9isVHJ5lrRV_zqf7B08S4ILTt5s/edit?resourcekey=0-0LBv-5VE-f2ezqtoIZ19-A) here which describes this requirement in more detail.

So, no matter whether we add such a switch or not for debugging purposes or not, we still need to have tests in place that verify whether the AST registers work with the generic open-source AST description at the top-level. In order to avoid duplicate work it is probably better to just stick with the generic description, even though this may initially be harder to debug.

**Comment by sha-ron** [comment]
@msfschaffner 
yes this is for top-level tests that use the proprietary AST.
Checking that the AST registers are working the open-source description is of course needed and we will have such tests.
But we also need to run top-level tests with the "real" AST registers (that some of them are proprietary/in the secure domain) and for that purpose we need the switch.
