### ISSUE TITLE
[otbn] add end-to-end test for rsa_verify.s and rsa_verify_3072.s

### ISSUE THREAD

**Issue by felixmiller** [lowRISC/opentitan#8226]
Currently we only have an end-to-end test for the full (modexp) RSA lib [here](https://github.com/lowRISC/opentitan/blob/master/sw/device/tests/otbn_rsa_test.c), but not for the optimzed versions for code verification.

Add a similar test for `rsa_verify.s` and `rsa_verify_3072.s`. The test should at least cover exponents 3 and F4.

**Comment by GregAC** [comment]
@rswarbrick do you feel this test is still required?

**Comment by rswarbrick** [comment]
I'm probably not the right person to answer this. @jadephilipoom / @felixmiller: Thoughts?

**Comment by jadephilipoom** [comment]
We have plenty of end-to-end tests for RSA-3072 now (in `sw/device/silicon_creator/lib/sigverify_functest.c` and `sw/device/tests/crypto/rsa_3072_verify_functest.c`; both files are configured to run a dynamic set of test vectors, which is set to a small sanity-check for CI but can be set to use hundreds of adversarial tests from wycheproof or randomized tests; I test both whenever I make a change). I'd say this issue is outdated, unless Felix has objections; although `rsa_verify` doesn't have the same test setup, it's part of the implementation plan for the crypto library that everything will be testable on these large sets.

**Comment by moidx** [comment]
Hi @jadephilipoom, can this issue be closed now?

**Comment by jadephilipoom** [comment]
Yes, I think so!
