### ISSUE TITLE
[all] need C/Rust register definitions for all releases and ToT

### ISSUE THREAD

**Issue by vsukhoml** [lowRISC/opentitan#8277]
OpenTitan evolves quickly and some registers are changing as a result. This complicates driver development as registers have to be reviewed with every sync. To support development of firmware solutions for OT we need to export register definitions, starting addresses into something which can be directly consumed by C and Rust.
Acceptable forms would defining constants for component's base address and either offsets or structs for each register and field.
It is desirable to make it easier for use with Rust  (TockOS), but C should also be covered. TockOS as an example provides it's way to detailed register specification using library https://github.com/tock/tock/tree/master/libraries/tock-register-interface.
Defining structs is a bit more preferable than defining offsets of registers as it typically results in more efficient code generation - compiler can compute offset from already loaded in register base address rather than loading constant again (may change with better compiler).

**Comment by msfschaffner** [comment]
CC @arunthomas

**Comment by domrizz0** [comment]
I was under the impression regtool addressed this issue?

**Comment by msfschaffner** [comment]
Afaik, our `regtool` can generate such headers for both C and Rust.
@timothytrippel / @drewmacrae can you maybe point @vsukhoml to the appropriate command or build rule in meson / bazel?

**Comment by timothytrippel** [comment]
Meson build rules that invoke `reggen` are [here](https://github.com/lowRISC/opentitan/blob/c3628a53481278bc63e60f40f35e580bc291900e/meson.build#L205-L252). Note meson only builds C headers for now, and we probably won't expand this since we are transitioning to bazel soon.

Custom Bazel rule that invokes `reggen` is [here](https://github.com/lowRISC/opentitan/blob/c3628a53481278bc63e60f40f35e580bc291900e/rules/autogen.bzl#L12-L38), and the instantiations of that rule are within each IP's data dir, e.g., for the adc_ctrl see [here](https://github.com/lowRISC/opentitan/blob/c3628a53481278bc63e60f40f35e580bc291900e/hw/ip/adc_ctrl/data/BUILD#L9-L14). Similarly, bazel only builds C headers for now, but this rule can be expanded to generate Rust constants too (just different flags to pass to `reggen`).

To build an individual IP's autogenerated C header you can use  `bazel build //hw/ip/adc_ctrl/data:adc_ctrl_regs`.

To batch generate all the header files for all IPs, you can just use the makefile in `hw/`, by running `make -C hw regs-rust` for Rust and `make -C hw regs-header` for C headers.
