### ISSUE TITLE
[hw/sw] HJSON pinmux configurations 

### ISSUE THREAD

**Issue by timothytrippel** [lowRISC/opentitan#8380]
There may be multiple intended use cases of the OpenTitan SoC, each using various (sub)sets of on-chip peripherals. Additionally, there are multiple supported targets for simulating/operating OpenTitan hardware on, each supporting various pinout configurations. We need a mechanism to configure the pinmux module, via its DIFs, based on intended use-case and target (DV and verilator sims, FPGA, and silicon) combinations.

To configure the pinmux for testing all intended use-cases, across all targets we support, we could develop an enhanced interface with the following requirements:

- At the lowest level, the pinmux will be configured using its corresponding DIFs.
- Above, a separate interface will drive the pinmux DIFs to set various pinmux configurations, depending on the: top-level, use-case, and target.
    - This separate interface may have several different parts, depending on the part of the system that requires this information. Specifically, for DV simulation, the UART agent will need to know which port to connect too (see #8355)
- Pinmux configurations for various use-cases may be defined in separate HJSON files, that:
    - may be similar to how pinout configurations are described in `top_{earlgrey,englishbreakfast}.hjson` files.
    - may follow the naming convention: `{toplevel}_{pinmux_cfg}_{target}.hjson`
    - may be located in: `sw/device/pinmux_config/configs/`
- Parts of the "separate interface" for driving the pinmux DIFs may reside in: `sw/device/lib/testing/`, while other scripting parts may reside in `util/`

**Comment by msfschaffner** [comment]
This seems to be out of date by now since we ended up dealing with this differently.
I.e., each software test configure the parts it cares about in the pinmux via the DIF.
Likewise, the DV environment has a way of muxing in interfaces in a coarse grained way, basing the pin locations on the primary use case.

It thus feels like this issue can be either closed, or deferred into the backlog if we intend to come back to this again.

CC @sriyerg @tjaychen

**Comment by timothytrippel** [comment]
Yep this can be closed now.
