### ISSUE TITLE
[spiflash] Build spiflash utility as static library, or don't use OpenSSL

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#843]
The spiflash tool uses OpenSSL and dynamically links against OpenSSL 1.0 or OpenSSL 1.1 whichever is available. Unfortunately, that makes our binaries rather hard to port, because OpenSSL cannot be installed in parallel; so newer distributions with OpenSSL 1.1 cannot run the spiflash binary. Static linking could solve that (need to check licensing), as would not using OpenSSL for this utility.

**Comment by cdgori** [comment]
Since this is the surviving issue (#3705 was closed) - I want to register a comment: we should at least give some consideration in choosing a SHA256 implementation that is very widely used, and believed more likely to be correct.  

3705 at least seemed to contemplate writing our own SHA256, which is certainly possible but I would say not recommended, or sourcing some other less-widely-used implementation.  I understand that there are concerns about OpenSSL and its licensing or being a heavy dependency for a simple tool, but wanted to highlight that there is also some benefit to using a really well-vetted implementation, in terms of likely correctness/certainty.  (There's also the flip-side risk issue that we potentially become vulnerable to an exploit targeted specifically to OpenSSL's implementation, which is probably the "biggest target" for adversaries.)

**Comment by moidx** [comment]
Closing this as we are currently using a vendored in library from the chromeos project.
