### ISSUE TITLE
[clkmgr] Possible enhancement to peri 

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#8610]
This might be covered implicitly, but i wanted to state it.
For this [item](https://github.com/lowRISC/opentitan/blob/master/hw/top_earlgrey/data/chip_testplan.hjson#L692), we want to make sure that peripheral clocks can be turned off without killing the system. Ie, the software should be able to turn off peripheral clocks and still access memories / flash / bus, etc, anything necessary to turn the clocks "back on".

**Comment by tjaychen** [comment]
@matutem i think this as you mentioned is implicitly covered.
If you agree, can you confirm and close this issue?

**Comment by matutem** [comment]
So you wonder if we will be able to write clk_enables to disable and then to re-enable any peripherals? I believe that is the case, since the CPU should still be able to run code with all peripheral and transactional clocks turned off. We could close this issue and create one if the (to be created) full-chip test that disables clocks fails somehow. If you think this is a risky item we could raise the priority of the corresponding test to avoid late surprises. Added Sri. WDYT?

**Comment by tjaychen** [comment]
yeah so i should clarify, this particular function, being able to disable peripheral clocks and turn them back on, is more a "debug" feature than a real functional feature.

In reality, there will be almost no scenarios where we can turn off peripheral clocks and actually expect things to still work normally.  So this is largely more useful in determining the power consumption of the peripheral clock tree. 

So I don't think this has to be a super high priority, but it would be very good to have it. (I thought this was already covered by your testplan though).

**Comment by matutem** [comment]
Tim, I am trying to sort this out:
- If you are referring to turning peripherals off via clkmgr.clk_enables, then I think this is not an issue since the CPU and flash are still running, and will be trivial to test it in full chip tests that modify clkmgr.clk_enables.
- If you are instead referring to turning peripherals off via low power transitions, then wakeup needs to be correctly configured via SW, and any enabled wakeup will cause the system to get back. Even if wakeups are incorrect, an aon_timer event (if configured) can also bring the system back.
So I don't see this as an actual issue; instead I think the full chip tests should test the scenarios described above.

What do you think?

**Comment by tjaychen** [comment]
yes that sounds good. Just to clarify, i was specifically referring to the first bullet point.
Ie to make sure the design did not accidentally place an infrastructural component (ie bus, memory) into peripheral category.
Thus making a peripheral "off" kind of like a suicide option.

**Comment by tjaychen** [comment]
this test has been added [here](https://github.com/lowRISC/opentitan/blob/master/sw/device/tests/clkmgr_peri_off_test.c).
