### ISSUE TITLE
[Hugo] Indicate position in documentation

### ISSUE THREAD

**Issue by towoe** [lowRISC/opentitan#866]
For the documentation an overview of the current site is presented, and one can use links on the current page to navigate to sub-pages.
Only the address bar gives an indication to the current level. The browser back feature must be used to navigate back.
Using a breadcrumb navigation would be more useful.
I created a first version for that in [my fork](https://github.com/towoe/opentitan/commit/2cbcf523e4c32bffdac64230cec2f383ea22b8f4) but I think this is not a nice solution. Maybe it is helpful as a starting point.

**Comment by eunchan** [comment]
Sorry I didn't run this PR on my side. When I look at the short code, it looks like the shortcode slices the permalink URL with `/` delimiter, and create link on each level. Do I understand correctly?

If yes, I think it has no benefit. breadcrumb needs to store the previous history into the cookie so that it can go back to the page what it was not the parents. Using cookie on hugo, I am not sure this can be done without javascript coding.

I agree it would be good to have the feature, but wonder whether it is worth to put our effort to implement it or not.

**Comment by gkelly** [comment]
If you update the cookies used please make sure you include me in the reviews, we'll need to update the cookie policy doc.

**Comment by asb** [comment]
Hi Eunchan, "breadcrumb" navigation has [two definitions](https://en.wikipedia.org/wiki/Breadcrumb_(navigation)). One involves cookies and showing history of pages visited. Here we're talking about adding navigation indicating where in the hierarchy you are, to make it easy to "go up a level" etc.

**Comment by towoe** [comment]
> If yes, I think it has no benefit. breadcrumb needs to store the previous history into the cookie so that it can go back to the page what it was not the parents. Using cookie on hugo, I am not sure this can be done without javascript coding.
> 
You are correct.
It just reflects the hierarchy and not the previous visited site.

**Comment by eunchan** [comment]
Thanks for correcting my ignorance. I probably am too outdated on the web
dev. :)
