### ISSUE TITLE
[otbn] Potentially refactor otbn_start_stop_control into otbn_controller

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#8689]
OTBN currently has a `otbn_start_stop_control` module which delays the "start an execute operation" signal to the main `otbn_controller` module until URND has received valid data from the EDN.

This setup makes it harder to reason about the behavior of OTBN, and I'm suggesting to fold the `otbn_start_stop_control` into the `otbn_controller`. This will become especially valuable as we add the secure wipe operations to OTBN, which also require handling of the start of the operation.

I think I now weakly convinced myself that the current setup works, even if OTBN goes into locked state while it is in `OtbnStartStopStateUrndRefresh` (e.g. still resetting INSN_CNT to zero, and ensuring that we don't do any work in the execute operation), but I went in circles with my thoughts a couple times to get there :-)

**Comment by GregAC** [comment]
I had intentionally split them as I didn't want to clutter the controller with all the start and stop stuff, instead having it focus exclusively on actual execution.

It is a bit awkward that we've got the two state machines that effectively need to be in 'sync'. Maybe instead of a single pulse from `controller_start_o` to start the controller we instead have an output to hold high whilst execution is occurring e.g. `controller_run_o`. Then when looking exclusively at `otbn_start_stop_control` it should be obvious when the controller is actually able to do stuff.

We could move the locked state into `otbn_start_stop_control` and it would just force `controller_run_o` to 0. Currently I think we'll still be able to execute the secure wipe commands (well will be when the PR is merged) when we're locked, which may not be an issue but isn't the way OTBN is specified to work.

**Comment by GregAC** [comment]
To avoid RTL churn this is better dealt with in a future release, unless D2S work can be made easier by this refactoring.

**Comment by cdgori** [comment]
> It is a bit awkward that we've got the two state machines that effectively need to be in 'sync'.

This is the only part that gives me pause.  We need to think about what happens if they get out of sync (e.g. by fault injection).

**Comment by rswarbrick** [comment]
I've spent a reasonable amount of time getting my head around these two FSMs in the last couple of weeks. And I'm convinced that the existing structure is actually pretty sensible!

The start/stop controller handles starting/stopping the processor (duh), but also handles things like RND keying and secure wipe. They didn't really exist when we split things out (and I think raised this issue) in the first place.

I don't really think that things will be made simpler by squashing the two blocks together. @GregAC: do you agree? In which case, maybe it makes more sense just to close this.

**Comment by msfschaffner** [comment]
I am moving this to PROD.M3 for D2S assessment (see @cdgori 's comment above).
If we determine that there is no vulnerability here, I think this issue can be closed.
