### ISSUE TITLE
[keymgr] input selection blanking

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#8947]
Similar to otbn's current regfile, keymgr also has a situation where specific values are selected out of a large set of flops in one cycle. 

Instead of allowing the selection to be purely one cycle as it is now, we should consider flopping these to ensure there are no spurious selections.  Ultimately this really only matters on the root key, so it may only matter for the cdi selection.

**Comment by cdgori** [comment]
Yep, as we talked about offline, this would be ideally done to prevent spurious reads of key material.

**Comment by msfschaffner** [comment]
Should we tag this as a future enhancement as well?

**Comment by ballifatih** [comment]
Triaged for `keymgr`. I do not fully understand the context here, so I am not able to judge how important this fix is.

**Comment by vogelpi** [comment]
I am not entirely sure about this. IIUC, this is about implementing some sort of blanking where `keymgr` can selects chunks of a big register or from multiple registers to store them in a smaller register or one specific register. The intent is to avoid SCA leakage between the different chunks or big registers as the selector signal can take on different values before stabilizing.

Assuming I got this right I, think there is no point in implementing this for `keymgr` because:
- `keymgr` always keeps 2 shares of the secrets. Such spurious leakage is either between Share 0 of two different secrets or Share 1 of two different secrets. Or if the selection is among words, the leakage would be about different words in the same share. In any case, this doesn't tell anything about either of the secrets.
- The root key is always loaded/XORed into the `key_state_q` register for which both shares have been preloaded with the same randomness. I.e., any such leakage within the shares will be different each time due to the preloading.

For `otbn`, the point of having this is really that Share 0 and Share 1 end up in two different registers of the same register file. On the read muxes of the register file, these two shares can get combined without blanking which is to be avoided at all cost.

I thus recommend to not do this and close the issue. But I might have missed something. What is your view @cdgori ?

**Comment by johannheyszl** [comment]
Thanks @vogelpi I agree with you assessment and support 'close as not planned'
