### ISSUE TITLE
[usb, top] Investigate method for double usb pads

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#9046]
We may need to add a two pads for each USB_P and USB_N function. 

If we were to do so, the output from usbdev would drive both sets.
The input we would arbitrarily pick one, and the pad controls would need to be unique. 

Given these constraints, what is the easiest way to enable this function in top_earlgrey?

The USB pads are manual pads, so we can hook them up as we see fit.  However I believe once we declare two sets of pads, that will create two sets of ports at the `chip_earlgrey_asic` level.

@msfschaffner is that right?

**Comment by msfschaffner** [comment]
Ok, the easiest way would be to add two more manual pads as you describe - the only issue with that is that we get two more ports at the chiplevel (we can try to manually short the two ports with a wire so that they belong to the same net in RTL, though).

As for the pad attributes, do they have to be unique per pad instance or per pad group (D+/D-)? 

Or do we only have to control the attributes of the output pads and can set the input ones to zero?

**Comment by tjaychen** [comment]
per Ziv's request, the pad control should be unique.
As for having two chip level ports (that's kind of what I expected as well), I think that is acceptable as well, because we can always short in the package. 

I just think for the upcoming milestones it's not worth trying to tweak the automation too much to accommodate an on-die shorting if it's a lot of work.

What do you think? You're a better judge of how much it would take.

**Comment by msfschaffner** [comment]
Yeah just adding two pads and making the rest of the connections manually is the most straightforward way to do this right now.

As for the pad attributes, we currently only have two registers in the pinmux (for D+ and D-).
I see on Ziv's block diagram that one pad in a pair has the attributes shorted to zero. 
That case can be accommodated. 

If this requirement has changed and we need the equivalent of four pad attribute registers, we may have to add two additional fake IO channels to the usbdev so that the current tooling can create and connect the attribute registers...

**Comment by tjaychen** [comment]
i could be mistaken, but i think Ziv wanted two sets of pad attributes
because he wanted to control drive strengths.

Ziv can you confirm?

**Comment by msfschaffner** [comment]
I have prepared an initial draft in #9059 so that you can see how the solution I had in mind would look like.

**Comment by zi-v** [comment]
There is no need for extra registers. Best would be to force the input path of one of the pads disabled and drive the output control of both pads (e.g. USB_P and USP_P1) by the same source/register. It is also an option (less preferred), to keep the input control of both pads the same, but this will cost in some extra leakage.

**Comment by zi-v** [comment]
To clarify, regardless, the input data (pad to core) should be taken only from one of the pads

**Comment by msfschaffner** [comment]
understood. we currently only connect one of the input buffers to the core. however, due to a scripting limitation, both input buffers are currently always enabled (I need to check whether we can change that in a straightforward way).

as for the output control (output value and output buffer enable), this is now also implemented as you described: output control is driven to both USB_P and USB_P1.

but just to double check:
is it ok to drive the pull-up/pull-down, inversion etc attributes to a pad pair from the same register, as well?

**Comment by zi-v** [comment]
Double pull-up means double pull-up strength. If you are OK with that, it can be done.
