### ISSUE TITLE
[spi_host] DUT not writing incoming data to fifo

### ISSUE THREAD

**Issue by rasmus-madsen** [lowRISC/opentitan#9285]
After splitting the SPI HOST fifo into RX and TX 
the RX data is not being written to the FIFO

3 segments are being transmitted
0: cmd - 1byte - tx/rx
1: addr - 4 bytes - tx_only
2: read - 4 bytes  rx_only

in the wave below it can be seen that the DUT receives h'0A - h'0A - h'0A - h'0A 
but the wdata is stuck at 0
![image](https://user-images.githubusercontent.com/53917183/142442079-7457b15b-589c-4fb9-9547-b59357bee887.png)

to reproduce checkout spi_smoke and and run
./util/dvsim/dvsim.py hw/ip/spi_host/dv/spi_host_sim_cfg.hjson -i spi_host_smoke -r 1 -t xcelium --job-prefix="nc run -C ncsim_interactive -Il" -w=shm -s=1

**Comment by martin-lueker** [comment]
Very Interesting.   The IP is currently (was recently?) working both in IP and in verilator.  I'll take a look.

**Comment by rasmus-madsen** [comment]
I am pretty sure it worked fine before the FIFO split

**Comment by martin-lueker** [comment]
The verilator and FPGA tests were after that, so this is very curious.

**Comment by martin-lueker** [comment]
Hi Rasmus, 
   I see the failure, but I also don't see any data coming in on `cio_sd_i`:

![image](https://user-images.githubusercontent.com/47870387/142922847-f852517b-888b-43e7-bb31-a99b916d4b5b.png)

(See orange traces, taken at the dut level).   This is with a direct fetch from your spi_smoke branch.

Is there something I'm missing here?  Could there be something wrong with how the testbench is connected?

**Comment by martin-lueker** [comment]
Looking at this much more closely I see there is another big problem with your test bench (and with the RTL) you are submitting a Rx/Tx segment in the first segment, but there is no data (sdi[1] is high-Z).  This needs to be fixed.   Also I see that some of the sd_i lines are X, they should all be known or at  least High-Z so they can be pulled down.

This does however uncover a bug in the RTL (but perhaps not the bug you are looking for) where the first segment is not actually putting any data in the FIFO.  I'll fix that.

**Comment by martin-lueker** [comment]
Hi @rasmus-madsen, this is now passing, with changes to RTL (as described in #9374)  as well as a couple fixes to your test bench which are captured in [this patch](https://github.com/lowRISC/opentitan/files/7592126/0001-spi_host-dv-Hack-fixes-to-test-bench.txt).

**Comment by rasmus-madsen** [comment]
@martin-lueker thank you for the patch. I am going to omit it as I already have a fix for the tb - sorry I forgot to update the issue.
Question: didn't you say that the sio's should be pullups - I see your patch is implementing pulldowns.

I did the pulldown in a different way - that is emulation an actual pulldown to all pins independent of what the other side is driving.

I think you could probably achieve the same in your code by 
changing 
`assign cio_sd_i_pulldown[i] = $isunknown(cio_sd_i[i]) ? 1'b0 : cio_sd_i[i];`
to
`assign (weak0, strong1) cio_sd_i_pulldown[i] = cio_sd_i[i];` 
then you don't need the unknown check

but I didn't verify that.

**Comment by martin-lueker** [comment]
Hi @rasmus-madsen,
   No worries about the patch, I wasn't actually thinking you'd apply it as is.  It was mean to show you the minimum that I had to add to get a pass. I figure that you have multiple fixes for improving these issues.   I just added it though so you could look at it and see what _sorts_ of changes needed addressing to get this issue addressed.   There are two items where I've applied (admitted) hack fixes in this patch:
   1. Regarding support for multiple segments & multiple TLUL reads.  You have two segments with RX activity here: segments 1 and 3.  The scoreboard section that is monitoring the TLUL bus for RXDATA read activity has a queue that is never getting cleared.  This means that when you try to verify the third segment you find that the queue still has data from the first segment in it.  This was causing the test to fail because the TLUL data from the first segment was included in the TLUL data for the second segment.
   2. Regarding the pull-up/pull-down.  IIRC, @msfschaffner said this should be a pull-up.  However for some reason I don't understand the testbench is currently _sending_ High-Z on the SPI bus during the first segment, but then also _expecting_ 0x0 from TLUL for the first segment.  I know you'll fix this properly, but just to keep the scoreboard moving I used a pulldown to pass the first segment check.

So again, the patch wasn't meant the be incorporated as is.  However if you are looking to independently confirm #9374 works, you will need to address these two issues in some fashion.

**Comment by rasmus-madsen** [comment]
@martin-lueker in general the testbech should drive the bus with highZ that is the task of the DUT.
but since we don't have a pin mux in the environment I assume that someone thought that this was how to do it.
I have fixed the testbench so the TB where the DUT is instantiated acts like the pin mux and actually uses pull-ups on the spi_if,
so when no-one is driving the bus it will look like all ones.

This is how it looks now (different seed multiple writes to device)
![image](https://user-images.githubusercontent.com/53917183/143306277-3be732dd-5869-4b48-ad3b-8abaa37d787f.png)
