### ISSUE TITLE
[rom] Additional bypass options

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#9295]
Consider adding additional otp options to bypass specific ROM options.  Such as.

1. RNG consumption
2. memory scrambling
3. execution (see #9228)
4. AST bypass (see #9296)

The last point is needed specifically because when there is no valid image loaded, ROM will initiate shutdown activity.
This may make it difficult to do any kind of testing on first silicon.

**Comment by mundaym** [comment]
From a software perspective it is much simpler (and therefore easier to harden) to have one option that skips AST configuration, entropy complex setup / RNG consumption and memory scrambling all in one go. Would that be sufficient or do you think we need finer granularity for debugging purposes?

I'll follow up on (3) in that issue because that is a more independent issue I think.

**Comment by tjaychen** [comment]
i think the original spirit of this issue has been addressed.
I don't think we really intend to have an option to skip entropy consumption and memory scrambling at this point.

We should probably close this issue if we agree that's the path we are taking.

**Comment by alphan** [comment]
Agreed. Just for the sake of completeness, we now have the following OTP items:
* ROM_EXEC_EN
* AST_INIT_EN
* JITTER_EN (gated by AST_INIT_EN)
