### ISSUE TITLE
[rom] AST initialization or bypass

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#9296]
AST initialization is currently being planned in ROM.
However, there may be a need to patch the initial AST configuration (from OTP) or bypass it altogether.

It should be explored as to what is the most sensible solution.

**Comment by cfrantz** [comment]
We should reserve a flash INFO page for register programming overrides.

1. Develop a an encoding for the blob in the INFO page that is reasonably tight but simple to decode.
2. Decide how to sign the blob so new blobs can be delivered and verified as legitimate silicon_creator artifacts.
3. Add a boot services API to request installation of a new blob.

**Comment by tjaychen** [comment]
@alphan also had a thought also that we can tie this into OTP enabled bypass.
So for example if an OTP is set or not set, we bypass the AST initialization completely and just work on it later.

It's not really clear to me if that is enough for this purpose.

**Comment by alphan** [comment]
Didn't have the chance to think about this yet but as @tjaychen said this needs some exploration because 
* AST can have an affect on flash functionality, and
* It's not clear to me yet what we want to patch and when.

If the the effect of the patch is expected to be minor in the sense that the initial config by mask rom does not hinder any functionality and we expect this "patch" to be a one-time event during bring-up we can reserve an info page with minimal management. If when this patch is applied is not critical, we can also consider including it in rom_ext. If the patch is something that we need to maintain like an artifact that can be updated, then we probably need boot services support as @cfrantz suggested.

**Comment by zi-v** [comment]
We don't expect more than a couple of updates throughout the lifetime of the product, but we want to be able to apply those changes in the field. One example of something we would like to patch is a configuration value that was considered safe when we hit production, but after millions of shipments, it appears to cause a high return rate due to over sensitivity or so.
Need to consider security aspects like authorization, rollback protection and attack resiliency of the mechanism

**Comment by mundaym** [comment]
@zi-v How do you envisage the 'patch' being applied? Could we reconfigure the AST later (e.g. in the ROM_EXT) or will we need to apply the patch to the original configuration before initialising the AST in the mask ROM?

> Need to consider security aspects like authorization, rollback protection and attack resiliency of the mechanism

If we can delay the reconfiguration until the ROM_EXT and bundle the 'patch' with that as @alphan suggests then we get those features more-or-less for free which would be nice.

**Comment by zi-v** [comment]
We can delay the re-config to ROM_EXT (we still we do need initial configuration to be done by ROM).
Note that if you bundle the configuration blob with the ROM_EXT signature, updating it might have attestation implications. Please consult @moidx as well.

**Comment by tjaychen** [comment]
@alphan @moidx @cfrantz 
i think we can close this issue now.
We've already talked about how/where AST configuration could be bypassed, and I believe we already have everything we need in ROM.
