### ISSUE TITLE
[util] ralgen connectivity to topgen

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#9323]
As a part of fixing #8207, we introduced an "alternate" hjson path for modules such as ast.
However, when ralgen is invoked, it does not know to pass this alternate path to topgen, so the resulting register model generated would still be the old one.

We will have to update the flow to make sure the path can be passed through fusesoc generators to topgen. 

@sha-ron i think this is the issue you were describing. Let me know if it's filed somewhere else.

**Comment by sha-ron** [comment]
Yes we need a way to pass the path through hjson/dvsim.
It is described in 8207 but indeed it is already closed. Thanks for opening this one Tim.

**Comment by sriyerg** [comment]
Ralgen is a FuseSoC "generator", which wraps over topgen and ralgen invocations. Unfortunately, my knowledge of FuseSoC is limited, so I am not sure if there is a way to modify a FuseSoC core file (in the open source) that already uses the open source specific settings to create the RAL model externally, from a closed source testbench. Only thing supported is FuseSoC flags, which are boolean values that enable or disable filesets. Luckily, it works for enabling / disabling filesets that are generated. 

The solution I have settled on with #9325 will work as follows:
1. Skip the RAL generation that happens on parsing the `hw/top_earlgrey/dv/env/chip_env.core` entirely by passing the following FuseSoC flag in your Nuvoton chip_sim_cfg.hjson:
```
    sv_flist_gen_flags: ["--flag=skip_ral_gen"]
```
2. Add your own RAL generation step in your extended chip env core file:
```
generate:
  ral:
    generator: ralgen
    parameters:
      name: chip
      top_hjson: relpath/to/top_earlgrey.hjson
      hjson_path: path # Must be the parent dir containing ast.hjson
```
3. Since this RAL generation step is happening outside of the processing of chip_env.core file, we may run into a issue - we need to somehow ensure that the RAL generated in the step above is placed as a dependency of the open source chip_env.core, so that compilation does not break. 

I hope this works, but if it doesn't, #9325 has support for one alternative approach - I will talk about it after you try the above :)

**Comment by tjaychen** [comment]
thanks @sriyerg ! I'll have a look at the other PR to better understand the alternative approach (the alternative approach i think is what you said would be more stable right?)
