### ISSUE TITLE
[lc_ctrl] Make lifecycle state values more ergonomic for software

### ISSUE THREAD

**Issue by mundaym** [lowRISC/opentitan#9337]
From the discussion in https://github.com/lowRISC/opentitan/pull/9319#issuecomment-975891419.

Silicon creator software frequently has to make decisions based on the current lifecycle state. The resultant code can get quite complex with large switch statements needed to handle all the possible (and impossible!) states.

Some ideas for improving this:

1) Make TEST_UNLOCKED a single state (rather than TEST_UNLOCKED0, TEST_UNLOCKED1, etc.) and track the counter in a separate field and/or register.
2) Categorise the states and encode the categories into field(s) in the state (e.g. have a field that specifies whether the state is a production or non-production state).
3) Remove states that do not allow code execution from the software interface (or merge them into a single invalid state).

@alphan has a table showing how the mask ROM is expected to behave in each lifecycle state which might be useful for categorisation purposes.

**Comment by alphan** [comment]
Thanks @mundaym, came here to add (3) but you already captured it :) In most cases, they are handled by the `default` case in code but result in some additional work in tests.

Just for the sake of clarity, if we decide to implement (1) as a field, it would be nice to keep the definition uniform for all states, i.e. all states have that counter field but for non-test states it is simply all zeros so that we could just use mask to clear that part and use a single switch statement.

**Comment by msfschaffner** [comment]
Thanks for opening this issue, @mundaym!

To your points (some of these comments were carried over from the PR):

0. regarding the RAW state being all-zero: I think I am not too worried about this. i.e., in order to do something interesting in the ROM, you would have to glitch to a non-zero 30bit value. and if we detect that we are in RAW, we would trigger the shutdown module, right? likewise on the HW side, glitching into RAW is 1) difficult to do, and 2) all "interesting" features (debug, processor, DFT) are disabled if we detect that we are in RAW.

1. we've coupled the state and test count since it was more convenient to do in HW. i.e., we do not have to maintain another multibit counter in OTP (like the total transition counter), thereby simplifying the state transition logic quite a bit. note: an easy way to extract the test count would be to subtract the first test state and apply a 5bit mask (the state values are monotonously increasing).

2. Isn't the masking approach potentially dangerous? i.e., what happens if you glitch the mask to all-zeros in the processor? I thought direct comparison with actual state values would be safer... (but maybe I am mistaken). If we want to do something like that, wouldn't it be safer to come up with a solution that does not require any masking? i.e., just expose a multibit "OK we are in prod" value in a separate CSR that does not have to be masked?

3. I would advise against that. The CSR node is shared between the lifecycle JTAG TAP and the bus interface, and splitting out the individual states (even the ones where code execution is not possible) can give us valuable debug and bringup information. I.e., while it is true that SW cannot run in all these states, we are always able to read the CSRs via the JTAG TAP.

@alphan can you link the ROM table @mundaym has mentioned above so I can take a look and think some more about the categorization?

**Comment by mundaym** [comment]
> Isn't the masking approach potentially dangerous? i.e., what happens if you glitch the mask to all-zeros in the processor?

I think masks are probably OK so long as we are performing `==` checks (as opposed to `!=` checks which we should try and avoid anyway). My guess is that, generally speaking, a mask would need to be glitched to something other than all zeros for a `==` check to succeed.

> I thought direct comparison with actual state values would be safer... (but maybe I am mistaken).

It is in simple cases where we are doing a direct comparison (e.g. `if (lc == PROD) { ... }`) but switch statements generate more complex code and typically rely on techniques like binary searches for speed. So if I write something like this:

```
switch(lc) {
case PROD:
  f();
  break;
case TEST_UNLOCKED0:
case TEST_UNLOCKED0:
case TEST_UNLOCKED0:
case TEST_UNLOCKED0:
case TEST_UNLOCKED0:
  g();
  break;
default:
  break;
}
> If we want to do something like that, wouldn't it be safer to come up with a solution that does not require any masking? i.e., just expose a multibit "OK we are in prod" value in a separate CSR that does not have to be masked?

**Comment by mundaym** [comment]
> we've coupled the state and test count since it was more convenient to do in HW. .. note: an easy way to extract the test count would be to subtract the first test state and apply a 5bit mask (the state values are monotonously increasing).

Ack. I think there are things we can do on the software side to make the values more ergonomic if we don't want to make the hardware changes.

> Isn't the masking approach potentially dangerous? i.e., what happens if you glitch the mask to all-zeros in the processor?

I think masks are probably OK so long as we are performing `==` checks (as opposed to `!=` checks which we should try and avoid anyway). My understanding is that, generally speaking, a mask would need to be glitched to something other than all zeros for a `==` check to succeed.

> I thought direct comparison with actual state values would be safer... (but maybe I am mistaken).

It is in simple cases where we are doing a direct comparison (e.g. `if (lc == PROD) { ... }`) but switch statements generate more complex code and are lowered using techniques like binary searches which can make branches depend on single bit values. There are ways to harden them but it would be nicer to avoid switch statements in the first place where we can.

> If we want to do something like that, wouldn't it be safer to come up with a solution that does not require any masking? i.e., just expose a multibit "OK we are in prod" value in a separate CSR that does not have to be masked?

That approach would be fine by me.

**Comment by moidx** [comment]
I discussed this in more detail with @msfschaffner, and at this state of the hardware design, we would be required to add a translation layer in hardware to meet this feature request (move the switch statement from C to gates), increasing the verification burden and impacting the next design milestone.  

We can leave this open as a future feature request, but our recommendation is to postpone this for a later design iteration. I will update the issue labels to reflect this.

**Comment by tjaychen** [comment]
this sounds good to me!
Thanks for agreeing to postpone this!

**Comment by tjaychen** [comment]
@moidx are you okay with moving this to "future release"? Ie something we maybe do for production but not engineering sample?

**Comment by msfschaffner** [comment]
I believe moving this to a future release is the way to go, yes. @moidx please re-label if that is not accurate.

**Comment by moidx** [comment]
ack. Sounds good.

**Comment by gdessouky** [comment]
Triaged for `lc_ctrl`: no security or functionality implications here. It's a nice fix, but sounds probably disruptive/heavy on the DV effort. Will label as https://github.com/lowRISC/opentitan/labels/Type%3AFutureRelease.

**Comment by msfschaffner** [comment]
@cfrantz to assess whether we should do this for PROD.

**Comment by msfschaffner** [comment]
Closing as not planned since our infrastructure and SW may be affected by this quite substantially.
Please let me know if there is a strict requirement for changing this and we can reopen the issue.
