### ISSUE TITLE
[aes/dv/dpi] c functions does not compile in their current form

### ISSUE THREAD

**Issue by rasmus-madsen** [lowRISC/opentitan#941]
HI @vogelpi 
I hope you got home well.

I have started the process of building the reference model but the current aes_model code in place does not compile with neither vcs or cadence.

1.	It looks like we need to reference the aes.c/h from aes/model/…
should we create a fusesoc core in model? Or should we just reference the files individually from the fusesoc core under dv/aes_model_dpi/
2.	If I reference the files there are compile errors inside the aes.h/aes.c
![image](https://user-images.githubusercontent.com/53917183/68476385-d3971f80-022a-11ea-9f14-61aa7c238b79.png)

I assume I do not need to precompile the aes.c/h but only OpenSSL or BoringSSL.

could you take a look?

thank you

**Comment by vogelpi** [comment]
Hi @rasmus-madsen ,
thanks for filing the issue. I forgot to commit the `aes_model.core` file and add the dependency in `aes_dpi_model.core`. When developing this, the dependency was always resolved in the .core-file of my simulation, which I did not push yet. I am sorry for that.

I have created a PR to fix the issue here lowRISC/opentitan#952 and would be happy if you could have a look at it.
Best,
Pirmin
