### ISSUE TITLE
[rom_ctrl] checker_good "always" high

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#9497]
This is not really an issue but just something that looks odd in waveforms.
I was running a `pwrmgr_smoke_test`, and basically the `checker_good` signal out of `rom_ctrl` is always high, even though low power.
I think this just boils down the `digest` and `exp_digest` registers having the same reset value.

Functionally this is fine, but i wonder if it's worth making these default values dis-similar so the checker_good is more of a pulse high.

**Comment by rswarbrick** [comment]
Making sure I understand: the problem is that when the `rom_ctrl` block is in reset, the `checker_good` signal is high? I'm not sure that matters, since it's a signal that's qualified by the "done" signal. This acts like a "vld", so the value of `checker_good` is indeterminate if "done" is low.

I could tweak things to avoid this (by changing the reset value of `matches_q` to zero in `rom_control_compare`), but it's a bit awkward and adds an extra step when going through the "Waiting" state. Note that if we do this, we'll still have some cycles where we're asserting good (but not done).

Alternatively, I could explicitly qualify the good signal on done:
```systemverilog
  assign done_o = (state_q == Done);
  assign good_o = matches_q & done_o;
```
but that also seems a bit silly, since the whole point of the `done_o` signal is to act as a valid signal for `good_o`.

What do you think?

**Comment by tjaychen** [comment]
yeah that's why originally i said this just looks weird in waves and not really an issue.
I was honestly thinking you could just give complementary reset values to expected digest and digest.

I think the not super convincing argument here that some will make is that if good is always 1 for a long period of time, then during that duration the attack surface is just 'done'.  If we can get done to be 1 at the right time, maybe the check will just be skipped over on pwrmgr side.

**Comment by rswarbrick** [comment]
Ah, I see. Well, the plan is for both of these signals to be multi-bit encoded so I'm hoping they aren't easy to glitch. And the second suggestion I had above wouldn't actually help (you'd just have to glitch `done_o` upstream of the AND gate). I guess the first suggestion would shorten the window a bit. Do you think it's worth doing?

(Note: We don't have expected digest and digest in the design in the way I think you're imagining. We compare them 32 bits at once, so there aren't really reset values that could be made complementary)

**Comment by tjaychen** [comment]
wait.. is it not these 
https://docs.opentitan.org/hw/ip/rom_ctrl/doc/index.html#Reg_exp_digest_0
https://docs.opentitan.org/hw/ip/rom_ctrl/doc/index.html#Reg_digest_0

admittedly i might have read the code wrong, because initially it looked like these two having the same reset value was causing the signal to be high all the time. 

Maybe the right answer is just wait for the multi-bit signals and everything will be fine. I would just suggest the default multi-bit value should probably be false :)

**Comment by rswarbrick** [comment]
It's those registers, but we don't have the values for those registers until we've read them from the ROM :-) And we compare 32 bits at a time because we do the reads at that width anyway, so there doesn't seem any point in having a massive 256b comparator.

**Comment by tjaychen** [comment]
wait i'm sorry, i didn't mean have a big comparator. 
i just meant that the individual reset values are different. Right now they're all 0 no? at least in my sim last night, i thought that just led to things being matched all the time. I'll check again.
