### ISSUE TITLE
[kmac, clkmgr] KMAC clock idle state (via hint), can't auto restart?

### ISSUE THREAD

**Issue by davebwil** [lowRISC/opentitan#9512]
For the top level test case "chip_sw_kmac_idle" the test description states:

Verify the KMAC idle signaling to clkmgr.
 - Write the KMAC clk hint to 1 within clkmgr to indicate KMAC clk is ready to be gated.
   Verify that the KMAC clk hint status within clkmgr reads 0 (KMAC is idle).
 - Initiate an KMAC operation with a known key, plain text and digest.
   Verify that the KMAC clk hint status within clkmgr now reads 1 (KMAC is not idle),
   before the KMAC operation is complete.

While writing some code for this, the first part looks to be working, setting the clkmgr KMAC hint
and then checking the status confirms the clk status is 0 (KMAC is idle).
However when then attempting to initiate a KMAC operation (i.e SHA3) the system locks up
(I assume the KMAC clock is not restarting.) The idle signal which is monitored by clkmgr looks to be driven high when KMAC FSM is idle and msgfifo is empty.
Is it the case that these signals cannot change once the clock is stopped and we are therefore stuck with idle high?

The test description implies the clock should auto restart and not rely on unsetting the clock hint.

**Comment by tjaychen** [comment]
Yeah the scheme here is not as smart as auto-clock gating (imply both auto stop and auto start).
Instead the scheme here is meant purely to "keep clocks going until kmac is finished" to ensure that while kmac is operational, we cannot manipulate the clocks to create an undesired result.

So once you set the hint, we only shut the clocks off when the unit is idle.  If you want it to run again, you'd actually need to turn it on via software, so the "auto-ness" is one direction only.

as a side note, when you file these top level issues in the future, if it's not clear who to assign them to, could you assign it to @sriyerg, @timothytrippel and @tjaychen first? We can then re-distribute as needed.

Otherwise if there's no assignee, the issue might just fall through the cracks.

**Comment by GregAC** [comment]
Question answered, so closing
