### ISSUE TITLE
[bazel] verilator tests timeout if kicked off at once with `bazel test //...`

### ISSUE THREAD

**Issue by drewmacrae** [lowRISC/opentitan#9652]
```bazel test //sw/device/boot_rom:verilator_boot_rom_test```
results in
```Target //sw/device/boot_rom:verilator_boot_rom_test up-to-date:
  bazel-bin/sw/device/boot_rom/verilator_boot_rom_test
INFO: Elapsed time: 666.791s, Critical Path: 666.46s
INFO: 19 processes: 6 internal, 10 linux-sandbox, 3 local.
INFO: Build completed successfully, 19 total actions
//sw/device/boot_rom:verilator_boot_rom_test                             PASSED in 35.0s
```
compare to
```bazel test //...```
```//sw/device/boot_rom:verilator_boot_rom_test                            TIMEOUT in 900.1s```

**Comment by drewmacrae** [comment]
giving the opentitan_functest  ```tags = ["cpu:6"],```
doesn't appear to work on my workstation(I expect it to only run verilator tests 2 at a time such that they don't time out.), so I'm using ```--local_test_jobs=HOST_CPUS*0.2``` to make everything more stable. the verilator tests don't appear to parallelize gracefully.

**Comment by rswarbrick** [comment]
Not sure whether this is something about the Bazel job dispatcher or about the verilator tests themselves. But I think we build Verilator tests so that they run with 4 cores by default (see `build-chip-verilator.sh`, which passes `--threads 4`). I don't *think* you can control how many threads the simulation uses at runtime, or at least I couldn't see something like that in [the manual](https://verilator.org/guide/latest/verilating.html#multithreading), so you might want to tweak how you are building the verilated binaries. Of course then latency will increase by roughly a factor of 4, which might be a show-stopper for anyone who wants to use *one* of the binaries on the command line.

**Comment by drewmacrae** [comment]
I think it's all to do with the bazel configuration. Thanks for calling out the 4 threads thing. I didn't know that and it helps. Running 9 copies on a 12 core machine made tests that normally pass in about 1minute timeout after 15m so it's worse than 4x, I'd wave my hands and say it's probably something with cache evictions and that we should aim to give these tests 4 cores if possible. We should make bazel sequence the tests appropriately WRT the number of cores available. There's a couple ways to do it, one of which already works on my machine and forms a nice starting point. The other is more elegant if we can make it work because it would let us specify the number of cores provided to a test or a kind of test.

**Comment by msfschaffner** [comment]
@drewmacrae can this issue be updated or closed?

**Comment by drewmacrae** [comment]
There's a way I want to fix this and we can still work around it so I'd prefer to just decrease its priority and keep it until I see the fix upstream or get a chance to walk through the rules and figure out where we're dropping the tag.

**Comment by drewmacrae** [comment]
I'm not sure how much of the Verilator flakiness comes from this.
