### ISSUE TITLE
run_seq_with_rand_reset_vseq  Generate unaligned register write

### ISSUE THREAD

**Issue by rasmus-madsen** [lowRISC/opentitan#9932]
when running the `spi_host_csr_mem_rw_with_rand_reset`
the sequence generate a write request to a register which is in fact a FIFO. the address is unaligned so the TLUL adapter flags an error in the response.

as can be seen in the wave below the TL UL address [1:0] is 2'b11
which triggers the unaling error check in the reg adapter.
is this expected behavior for this test? it looks like the register should behave as any other register.
![image](https://user-images.githubusercontent.com/53917183/148555171-ff4aeca0-2510-4ef8-b854-884e65026ac9.png)

recreate sha b5eefa44470c62121d4556b349ef2709b7e69bce
/util/dvsim/dvsim.py hw/ip/spi_host/dv/spi_host_sim_cfg.hjson -i spi_host_csr_mem_rw_with_rand_reset -r 1 -t xcelium -w=shm s=2930650901

**Comment by weicaiyang** [comment]
addr[1:0] = 2'b11 is actually allowed if it's memory and supports byte write.
In this case, size is 0 and mask is 'b1000. So it doesn't violate the TL protocol.

@martin-lueker last time, we tried to fix some memory issue in #8844, because we used tl_adapter_reg for memory instead of tl_adapter_sram. This is another case which is allowed for memory but it's prohibited in tl_adapter_reg.

not sure if we can just simply modify the address to be word aligned to avoid filing this error? I did a similar hack locally and the test is passing.
```
assign tx_win_i_new.a_addr = (tx_win_i.a_addr[31:2], 2'b00);
assign tx_win_i_new... = tx_win_i...;

  tlul_adapter_reg #(
    .RegAw (AW),
    .RegDw (DW)
  ) u_adapter_tx (
    .clk_i,
    .rst_ni,
    .tl_i    (tx_win_i_new),
    .tl_o    (tx_win_o),
    .we_o    (tx_valid_o),
    .re_o    (tx_re),
    .addr_o  (),
    .wdata_o (tx_data_o),
    .be_o    (tx_be_o),
    .rdata_i ({DW{1'b0}}),
    .error_i (tx_access_error),
    .busy_i  ('0)
  );

```

**Comment by rasmus-madsen** [comment]
@weicaiyang I think this is the wrong way to go - to hack the RTL to make a test pass
we should fix the test.

if not I suggest just excluding the register in the test rather than hacking the code

**Comment by weicaiyang** [comment]
> @weicaiyang I think this is the wrong way to go - to hack the RTL to make a test pass We should fix the reg adapter or change the test
> 
> if not I suggest just excluding the register in the test rather than hacking the code

The hacking is just to experiment a design fix. Adding a parameter to disable the word-align check may also work
@martin-lueker can you take a look and see if we can fix it?

**Comment by weicaiyang** [comment]
@martin-lueker can you take a look at this issue?

**Comment by weicaiyang** [comment]
add @tjaychen 

Tim, let's summarize this issue here.
spi_host uses `tlul_adapter_reg` for a memory and this memory supports byte write. 
For memory, we allow to use unaligned address, for example 'b11 with mask = 'b1000 to access the 4th byte.
In `tlul_adapter_reg`, we require the first byte is always enabled, as CSRs starts from 1st byte and when there is write, it has to write all the fields in the CSR. So, address LSB 2 bits must be 'b00.

Since this is a memory but implemented with  `tlul_adapter_reg`, can we internally tie the LSB 2 bits to 0, so that it supports more flexible byte write (no need to have aligned address)? Or other approach if it's easier, like switch to use `tlul_adapter_sram`, parameterize `tlul_adapter_reg` to allow unaligned address.

```
assign tx_win_i_new.a_addr = (tx_win_i.a_addr[31:2], 2'b00);
assign tx_win_i_new... = tx_win_i...;

  tlul_adapter_reg #(
    .RegAw (AW),
    .RegDw (DW)
  ) u_adapter_tx (
    .clk_i,
    .rst_ni,
    .tl_i    (tx_win_i_new),
    .tl_o    (tx_win_o),
    .we_o    (tx_valid_o),
    .re_o    (tx_re),
    .addr_o  (),
    .wdata_o (tx_data_o),
    .be_o    (tx_be_o),
    .rdata_i ({DW{1'b0}}),
    .error_i (tx_access_error),
    .busy_i  ('0)
  );
```

**Comment by tjaychen** [comment]
hmm... just judging on the surface, it sounds like the better approach is
just to switch to tlul_adapter_sram.
Although i don't think there's an actual memory in spi_host, is it just a
memory-like construct underneath?

i'll need to have a look.

**Comment by tjaychen** [comment]
i had a quick look.
@weicaiyang is right. Since we are using `tlul_adapter_reg` here, the logic needs to obey the register rules, which are codified [here](https://docs.opentitan.org/doc/rm/register_tool/#error-responses).

Specifically, we cannot make non-word accesses to non-word aligned address. What you are doing in this test, writing to a [1:0] != 00 is not allowed for any other register either. 

Given @martin-lueker usage, i think it is actually fine to do exactly as @weicaiyang suggested, which is tie the lower bits to 0. When you do that, you will satisfy the register access rules, and the byte enables are still correctly generated, which means downstream behavior is still correct. 

@martin-lueker if you don't have any objections, that's the route i propose. `tlul_adapter_sram` is much heavier is I don't think is strictly necessary here.

**Comment by weicaiyang** [comment]
> i had a quick look. @weicaiyang is right. Since we are using `tlul_adapter_reg` here, the logic needs to obey the register rules, which are codified [here](https://docs.opentitan.org/doc/rm/register_tool/#error-responses).
> 
> Specifically, we cannot make non-word accesses to non-word aligned address. What you are doing in this test, writing to a [1:0] != 00 is not allowed for any other register either.
> 
> Given @martin-lueker usage, i think it is actually fine to do exactly as @weicaiyang suggested, which is tie the lower bits to 0. When you do that, you will satisfy the register access rules, and the byte enables are still correctly generated, which means downstream behavior is still correct.
> 
> @martin-lueker if you don't have any objections, that's the route i propose. `tlul_adapter_sram` is much heavier is I don't think is strictly necessary here.

Thanks @tjaychen 
If no objection, I can try out that approach in a few days.

**Comment by tjaychen** [comment]
i can have a look later also, and run through existing spi-host regressions to see if it makes anything worse.

**Comment by martin-lueker** [comment]
> i had a quick look. @weicaiyang is right. Since we are using `tlul_adapter_reg` here, the logic needs to obey the register rules, which are codified [here](https://docs.opentitan.org/doc/rm/register_tool/#error-responses).
> 
> Specifically, we cannot make non-word accesses to non-word aligned address. What you are doing in this test, writing to a [1:0] != 00 is not allowed for any other register either. Although I see no reason why this couldn't happen in real production settings.
> 
> Given @martin-lueker usage, i think it is actually fine to do exactly as @weicaiyang suggested, which is tie the lower bits to 0. When you do that, you will satisfy the register access rules, and the byte enables are still correctly generated, which means downstream behavior is still correct.
> 
> @martin-lueker if you don't have any objections, that's the route i propose. `tlul_adapter_sram` is much heavier is I don't think is strictly necessary here.

Hi @tjaychen, Hi @weicai,
   This sounds great.   I approve this solution.  I also agree that the sram adapter would be pretty difficult.
   Thank you so much for looking into this.  It has been an extremely busy meeting+travel+meeting week for me, so I really appreciate both of your time and assistance on this. 


> i had a quick look. @weicaiyang is right. Since we are using `tlul_adapter_reg` here, the logic needs to obey the register rules, which are codified [here](https://docs.opentitan.org/doc/rm/register_tool/#error-responses).
> 
> Specifically, we cannot make non-word accesses to non-word aligned address. What you are doing in this test, writing to a [1:0] != 00 is not allowed for any other register either. Although I see no reason why this couldn't happen in real production settings.
> 
> Given @martin-lueker usage, i think it is actually fine to do exactly as @weicaiyang suggested, which is tie the lower bits to 0. When you do that, you will satisfy the register access rules, and the byte enables are still correctly generated, which means downstream behavior is still correct.
> 
> @martin-lueker if you don't have any objections, that's the route i propose. `tlul_adapter_sram` is much heavier is I don't think is strictly necessary here.

Hi @tjaychen, Hi @weicai,
   This sounds great.   I approve this solution.  I also agree that the sram adapter would be pretty difficult.
   Thank you so much for looking into this.  It has been an extremely busy meeting+travel+meeting week for me, so I really appreciate both of your time and assistance on this.
