### ISSUE TITLE
[SYSRST_CTRL] ulp_status register is not updated when pwrb_det_pulse is detected

### ISSUE THREAD

**Issue by patel-madhuri** [lowRISC/opentitan#9963]
The ulp_status register reads value 0 even when the pwrb_det_pulse is detected. The ulpfsm is at DONE_ST state. the pulse is detected when the bus clk is disable and I am reading the register after enabling the bus clock. 

The command to run the test and re-generate the issue is 
./util/dvsim/dvsim.py hw/ip/sysrst_ctrl/dv/sysrst_ctrl_sim_cfg.hjson -i sysrst_ctrl_ultra_low_pwr --waves --tool xcelium --fixed-seed 4078968123

The draft PR is 
https://github.com/lowRISC/opentitan/pull/9962

**Comment by patel-madhuri** [comment]
@msfschaffner Could you please have a look at this issue?

**Comment by msfschaffner** [comment]
Hi @patel-madhuri, I took a look at the waves. The RTL seems to behave correctly. The problem we're seeing here is due to the fact that the TL-UL read transaction is issued at the same time as the bus clock. Hence, the status values have not had any time to propagate through the synchronizer to the bus clock domain and we are reading 0 therefore. I suggest to wait a couple of cycles (at least 2-3) after re-enabling the bus clock.

FYI @weicaiyang @tjaychen I believe this should not be a real issue in the system, since a full wakeup is going to take many many bus cycles until the processor can execute again.

**Comment by tjaychen** [comment]
yes i think that's generally true. But just in case software needs to poll for any reason, is this something they could reasonably just keep reading until they get the right data?

**Comment by msfschaffner** [comment]
We probably can, if needed, since we're expecting the ULP status register to be set to 1 after getting a wakeup request from `sysrst_ctrl`.

**Comment by tjaychen** [comment]
sounds good.

**Comment by patel-madhuri** [comment]
Thank you for the feedback. As we now have clear understanding, I am closing this issue.
