### ISSUE TITLE
pwm specification should comment on the supported range of clocks

### ISSUE THREAD

**Issue by rasmus-madsen** [lowRISC/opentitan#9999]
The PWM specification should comment on what range of clocks are supported. 
it should also comment on the relationship between TL <-> core clock.

this is needed to know what range the clocks should be used to verify the CDC

> estimate 1

**Comment by martin-lueker** [comment]
(Coming back to this after the V2 review)

The CDC is now managed by the reg-tool interface generator.  That said, do we need any special documentation for this?

**Comment by cindychip** [comment]
@msfschaffner @tjaychen do you have any insight on this?

**Comment by rasmus-madsen** [comment]
@martin-lueker I think this issue can be closed- the responsibility of verifying the CDC is now somewhere else

**Comment by andreaskurth** [comment]
Triaged for `pwm`. Assigning to M2.5 with https://github.com/lowRISC/opentitan/labels/Priority%3AP3 because as per the last comment:
- "There's no clock frequency requirement anymore that we know of." So documentation needs to be updated but that could happen post M2.5.
- Block-level DV should check this: The clocks are being randomized, and we collect coverage for it in `clock_cg`, which is currently at 100%. However, the TL clocks are mapped to a single bin, so that bin and the cross with the core clock is not very meaningful. This should be improved to verify this more thoroughly.

**Comment by msfschaffner** [comment]
This is low-prio and not needed for M2.5 hence deferring.

**Comment by moidx** [comment]
Moving to M5 based on priority.
